### ISSUE TITLE
TouchId for iOS

### ISSUE THREAD

**Issue by carlosrfernandez** [bitwarden/mobile#10]
It'd be great to have touch Id on iOS in the future (and I think some Android devices also come with this feature). 

That way we don't have to input the master PW all the time :)

**Comment by kspearrin** [comment]
Touch Id is already supported on iOS. Simply go to settings within the app to turn it on.

**Comment by carlosrfernandez** [comment]
Omg haha what a rookie mistake. Thanks for the quick reply. And thanks for the awesome job you're doing. Hopefully in the future I can contribute something to your project.
