### ISSUE TITLE
Lockup on login on Android

### ISSUE THREAD

**Issue by tarka** [bitwarden/mobile#100]
Version: 1.70 (10 Jun 2017), Android (Nexus6P, current, June patch level)

On attempting to login I get a hard UI freeze. 'adb logcat' shows the logs getting spammed with the following messages:

    06-12 09:51:11.233 23808 23808 I MonoDroid: UNHANDLED EXCEPTION:
    06-12 09:51:11.233 23808 23808 I MonoDroid: System.InvalidOperationException: MAC failed.
    06-12 09:51:11.233 23808 23808 I MonoDroid:   at Bit.App.Utilities.Crypto.AesCbcDecrypt (Bit.App.Models.CipherString encyptedValue, Bit.App.Models.SymmetricCryptoKey key) [0x0005d] in <799d68d344f448e9bc0343051072d77b>:0 
    06-12 09:51:11.233 23808 23808 I MonoDroid:   at Bit.Android.Services.AndroidKeyStoreStorageService.TryGetAndMigrate (System.String key) [0x0005c] in <78884717d53644bcac4fa55efd77fb43>:0 
    06-12 09:51:11.233 23808 23808 I MonoDroid:   at Bit.Android.Services.AndroidKeyStoreStorageService.Retrieve (System.String key) [0x0001a] in <78884717d53644bcac4fa55efd77fb43>:0 
    06-12 09:51:11.233 23808 23808 I MonoDroid:   at Bit.App.Services.AppIdService.GetAppId (System.String key, System.Nullable`1[System.Guid]& appId) [0x0001d] in <799d68d344f448e9bc0343051072d77b>:0 
    06-12 09:51:11.233 23808 23808 I MonoDroid:   at Bit.App.Services.AppIdService.get_AppId () [0x00000] in <799d68d344f448e9bc0343051072d77b>:0 
    06-12 09:51:11.233 23808 23808 I MonoDroid:   at Bit.Android.HockeyAppCrashManagerListener.get_Description () [0x00010] in <78884717d53644bcac4fa55efd77fb43>:0 
    06-12 09:51:11.233 23808 23808 I MonoDroid:   at HockeyApp.Android.CrashManagerListener.n_GetDescription (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <90cd0425bb934907904d0e0218cfff7c>:0 
    06-12 09:51:11.233 23808 23808 I MonoDroid:   at (wrapper dynamic-method) System.Object:68b84562-36fc-47a8-a439-17012edf1796 (intptr,intptr)
    06-12 09:51:11.263   556   556 D SoftKeymaster: system/keymaster/soft_keymaster_device.cpp, Line 700: Requested digest(s) supported for algorithm 1 and purpose 1
    06-12 09:51:11.263   556   556 D SoftKeymaster: system/keymaster/soft_keymaster_device.cpp, Line 1202: Operation supported by Keymaster QTI HAL, passing through to keymaster1 module
    06-12 09:51:11.265   374   377 D DrmLibTime: got the req here! ret=0
    06-12 09:51:11.265   374   377 D DrmLibTime: command id, time_cmd_id = 770
    06-12 09:51:11.265   374   377 D DrmLibTime: time_getutcsec starts!
    06-12 09:51:11.265   374   377 D DrmLibTime: QSEE Time Listener: time_getutcsec
    06-12 09:51:11.265   374   377 D DrmLibTime: QSEE Time Listener: get_utc_seconds
    06-12 09:51:11.265   374   377 D DrmLibTime: QSEE Time Listener: time_get_modem_time
    06-12 09:51:11.265   374   377 D DrmLibTime: QSEE Time Listener: Checking if ATS_MODEM is set or not.
    06-12 09:51:11.265   374   377 D QC-time-services: Lib:time_genoff_operation: pargs->base = 13
    06-12 09:51:11.265   374   377 D QC-time-services: Lib:time_genoff_operation: pargs->operation = 2
    06-12 09:51:11.265   374   377 D QC-time-services: Lib:time_genoff_operation: pargs->ts_val = 0
    06-12 09:51:11.265   374   377 D QC-time-services: Lib:time_genoff_operation: Send to server  passed!!
    06-12 09:51:11.265   563   581 D QC-time-services: Daemon: Connection accepted:time_genoff
    06-12 09:51:11.266   563  4794 D QC-time-services: Daemon:Received base = 13, unit = 1, operation = 2,value = 0
    06-12 09:51:11.266   563  4794 D QC-time-services: Daemon:genoff_opr: Base = 13, val = 0, operation = 2
    06-12 09:51:11.266   563  4794 D QC-time-services: offset is: 1 for base: 13
    06-12 09:51:11.266   374   377 E QC-time-services: Receive Passed == base = 13, unit = 1, operation = 2, result = 0
    06-12 09:51:11.266   374   377 D DrmLibTime: QSEE Time Listener: ATS_MODEM is set. Try to retrieve it.
    06-12 09:51:11.266   563   581 E QC-time-services: Daemon: Time-services: Waiting to acceptconnection
    06-12 09:51:11.266   563   581 D QC-time-services: Daemon: Connection accepted:time_genoff
    06-12 09:51:11.267   563  4795 D QC-time-services: Daemon:Received base = 13, unit = 1, operation = 1,value = 0
    06-12 09:51:11.267   563  4795 D QC-time-services: Daemon:genoff_opr: Base = 13, val = 0, operation = 1
    06-12 09:51:11.267   563  4795 D QC-time-services: Daemon: genoff get for 13
    06-12 09:51:11.267   563  4795 D QC-time-services: Daemon:rtc_get: Time read from RTC -- MM/DD/YY HH:MM:SS6/11/70 0:14:42
    06-12 09:51:11.267   563  4795 D QC-time-services: Daemon:Value read from RTC seconds = 16503282000
    06-12 09:51:11.267   563  4795 D QC-time-services: Daemon:Value read from generic offset = 1480754188000
    06-12 09:51:11.267   563  4795 D QC-time-services: Daemon:Final Time = 1497257470000
    06-12 09:51:11.267   374   377 D DrmLibTime: QSEE Time Listener: Time GenOff - seconds: 1497257470
    06-12 09:51:11.267   374   377 D DrmLibTime: time_getutcsec returns 0, sec = 1497257470; nsec = 0
    06-12 09:51:11.267   374   377 D DrmLibTime: time_getutcsec finished! 
    06-12 09:51:11.267   374   377 D DrmLibTime: iotcl_continue_command finished! and return 0 
    06-12 09:51:11.267   374   377 D DrmLibTime: before calling ioctl to read the next time_cmd
    06-12 09:51:11.268   563   581 E QC-time-services: Daemon: Time-services: Waiting to acceptconnection

**Comment by tarka** [comment]
Note: Uninstall and reinstall fixed the issue.

**Comment by kspearrin** [comment]
Thanks @tarka . I see this happening for quite a few people in the crash logs but am unable to reproduce it on my end. Can you tell me the steps that led up to this crash? Were you logged into the previous version and then just updated to v1.7.0?

**Comment by tarka** [comment]
This is an existing install, recently upgraded. The sequence to reproduce:

* Open BW
* Username is already configured
* Insert password
* Press login button (top-right)
* Lockup

Unfortunately I can no longer reproduce as a reinstall fixed it for me.

**Comment by kspearrin** [comment]
@tarka So you were logged out of bitwarden after the upgrade and needed to log in again?

**Comment by tarka** [comment]
I believe so. I hadn't actually used BW recently though.

**Comment by kspearrin** [comment]
Ok, thanks. What would you consider recently? 1 week? 1 month+? Also, do you which version you were on prior to upgrading to v1.7.0?

**Comment by tarka** [comment]
Probably 2-3 weeks. I'm not sure what the previous version was, but I update the installed apps daily (at least), and I'm on the beta channel.

**Comment by kspearrin** [comment]
Ok, let me try some different scenarios to see if I can figure out how reproduce it. Obviously something is happening because I am seeing several crash logs for it.

**Comment by kspearrin** [comment]
Should hopefully be resolved now with 1.7.0 build 852 now in beta channel.
