### ISSUE TITLE
Autofill API works on Firefox (Fennec) but not Beta or Preview (Fenix) on Android

### ISSUE THREAD

**Issue by rob83gh** [bitwarden/mobile#1001]
## Describe the Bug
I have a Samsung Galaxy S7 with Android 8.0.0. Bitwarden auto-fill API service works in Firefox 68.9.0 (Fennec) but not in Firefox Beta or Preview 78.0.0 (Fenix). Bitwarden auto-fill accessibility service does work in both but is slower and does not work on some sites where auto-fill API did.

## Steps To Reproduce
1. Open any login page
2. Focus the username or password field

## Expected Result
Bitwarden autofill popup should appear

## Actual Result
No popup appears

## Screenshots or Videos
n/a

## Environment
- Samsung Galaxy S7
- Android 8.0.0
- Firefox Beta 78.0.0-beta.1

## Additional Context
With the impending move to the Fenix codebase, Firefox for Android seems to lose autofill API functionality that used to work on the Fennec codebase. This would be a shame since it's the only browser that currently works at all with auto-fill API on my device.

**Comment by tgreer-bw** [comment]
Is it just not showing the option to autofill? If so it's because the Fennec project has a special list for autofill options right now. We've reached out to see if we can get on the list, but there isn't a reason to believe that Bitwarden won't be supported once it moves to general availability.

Perhaps @mportune-bw may be able to add some clarity here as well.

**Comment by rob83gh** [comment]
Ah, okay, I did not know there was a list. Yes, it is just not showing any option to autofill.

**Comment by rob83gh** [comment]
Fenix is currently rolling out on the Firefox release channel in the play store. My phone updated to version 79.0.4 and auto-fill service stopped working.

**Comment by robpearman** [comment]
I have been having the same issue for a little while. I'm running the latest Bitwarden 2.5.0 and Firefox beta 80.0.0-beta.6 on a Samsung Galaxy S9 running Android 10, kernel 4.9.118. 

Bitwarden often either doesn't show the option to auto fill a username or password field an a Firefox Web page, or sometimes flashes it on screen and closes it before I can press it. Perversely it worked fine loggin on to Github to add this comment and is somewhat unpredictable. If I can provide any more info to help diagnose just let me know.

**Comment by rob83gh** [comment]
Auto-fill accessibility service still works but not as well, i.e. often doesn't show at all, or only fills one box but not the other, and is slower overall. Copy paste from the app is sometimes the only way.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
