### ISSUE TITLE
2-step authorization not working for current token

### ISSUE THREAD

**Issue by 1ktribble** [bitwarden/mobile#1002]
When logging into Bitwarden, the current token does not authorize my login successfully using Google's Authorization tool. However, once that token has expired and the next token shows, the former token is then accepted.

Android v. 9
Samsung Note 8
Bitwarden Version: 2.5.0 (3093)

**Comment by kspearrin** [comment]
Check and correct the system time on your device.

**Comment by clayadams5226** [comment]
@1ktribble Did updating the system time resolve your issue?

**Comment by 1ktribble** [comment]
@clayadams5226 yes - that fixed my issue.
