### ISSUE TITLE
PIN Code unlock not working

### ISSUE THREAD

**Issue by Myaael** [bitwarden/mobile#1004]
## Describe the Bug
Bitwarden asking for master password while PIN Code unlock is enabled.

## Steps To Reproduce
1. Set up PIN Code
2. Clear Bitwarden from recent apps
3. Re-open Bitwarden / Attempt to use for auto-fill services

## Expected Result
A screen prompting you for your PIN code.

## Actual Result
A screen prompting you for your master password.

## Environment
- Device: Samsung Galaxy S10
- Operating system: Android 10
- Build Version: 2.5.6 (3110)
- Is this a Beta release: N

## Additional Context
PIN Code prompt works correctly when using "Lock now" from settings menu, and when Bitwarden remains in recent apps.
Downloaded through F-droid store.

**Comment by clayadams5226** [comment]
@Myaael when you enable PIN Code you should get a pop-up asking if you want to require unlocking with your master password when the application is restarted. If you select 'no' on this prompt it should resolve your issue. Clearing Bitwarden from your recent apps is equivalent to an app restart.
