### ISSUE TITLE
F-Droid repo not being updated

### ISSUE THREAD

**Issue by NipponBill** [bitwarden/mobile#1007]
## Describe the Bug

The F-Droid repo for Bitwarden should be at or near the Google App Store or other APK downloads
## Steps To Reproduce

Installed Bitwarden via F-Droid several months ago by adding the Bitwarden F-Droid Repo
## Expected Result

Bitwarden version should be at least 2.5.x
## Actual Result

Bitwarden version is 2.3.1 with no updates available

## Environment

- Device: Google Pixel 3aXL
- Operating system: GrapheneOS
- Build Version: 2.3.1 (2257)
- Is this a Beta release? [N]

**Comment by kspearrin** [comment]
You may need to reinstall. We did a key change a few versions ago which may have orphaned you from updates.

**Comment by NipponBill** [comment]
I uninstalled Bitwarden via F-Droid. Attempting to reinstall resulted in "Error installing Bitwarden"
<img src="https://user-images.githubusercontent.com/883285/87212948-5ba26b80-c35c-11ea-9c8d-7d0352fc9f9d.png" width="50%">

Thinking it might be the repository, I removed the Bitwarden repo from F-Droid, rebooted the phone, then re-added the BW repo. Now when I lookup Bitwarden in F-Droid I see 2 available versions, both 2.5.6
<img src="https://user-images.githubusercontent.com/883285/87213014-c2c02000-c35c-11ea-8be1-ff81cf50d4a2.png" width="50%">
Attempting to install via the _Install_ button, or the first version of 2.5.6, F-Droid flashes a blank white screen momentarily, then returns to the main screen.  No errors or other messages. 
Attempting to install the second version of 2.5.6 in the list results in the initial error,  "Error installing Bitwarden, Failed to install due to an unknown error"

I have attempted various combinations of removing the BW repo, closing F-Droid, and rebooting the device. The result has been the same.

**Comment by kspearrin** [comment]
@mportune-bw Can you confirm?

**Comment by mportune-bw** [comment]
Something is wrong but it happens a little differently on my end.  The default install results in the blank screen flash as described by @NipponBill .  In the Versions section I only see one other 2.5.6 (instead of two), and that one installs properly for me.  I then uninstalled it to try again, and now both the default install & "Version" install work properly.  I'll investigate.

**Comment by mportune-bw** [comment]
I tried installing fresh from F-Droid again, but this time while I got the same blank screen flash (with no indication of Bitwarden being installed) about 8-10 seconds later the F-Droid app suddenly changed to show `Uninstall` and `Open` options, and a toast appeared to let me know the shortcut had been added to my desktop.

I've confirmed our APKs are signed correctly and behave properly (by preventing overlap) when installing manually via ADB, so I'm kind of at a loss here.  Is it possible something broke recently within the F-Droid app?  I looked through their support forums and while I found a few posts about apps not updating properly, I didn't see anything major.

@NipponBill Here's a direct link to the F-Droid build of Bitwarden 2.5.6 if you'd like to install manually.  I'd be interested to know if the APK still fails to install for you outside of the F-Droid app.

https://github.com/bitwarden/mobile/releases/download/v2.5.6/com.x8bit.bitwarden-fdroid.apk

**Comment by NipponBill** [comment]
Thanks for the help @mportune-bw 
I tried downloading and installing the APK you linked to, but I got this:
<img src="https://user-images.githubusercontent.com/883285/87359166-44ed5600-c5a2-11ea-9a60-4308d0844c08.png" width="50%">
I get the same message "App not installed." after deleting the file and downloading again.

The F-Droid situation remains the same after this attempt. There are still 2 versions of 2.5.6 listed and they act the same as described above.

**Comment by mportune-bw** [comment]
Thanks for checking that @NipponBill .  Just to confirm, is your device still set to allow APK loading outside of the Play Store?  Beyond that I'm unsure of why this would be happening, as I'm able to download and install the APK via the same link on my test devices (one of which is a Pixel 3).

**Comment by NipponBill** [comment]
> is your device still set to allow APK loading outside of the Play Store?

On **GrapheneOS** there is no access to the Google Play Store at all. I can only use things like _F-Droid_ or _Aurora_, or download APKs directly. I have to authorize loading these APKs each time, or I have to authorize the app to load and install the APKs. That's what I had to do when following that link in the screenshot above.

I agree this is odd. I wonder if a subsequent version number of Bitwarden will help... How often are there updates to the F-Droid repo by BW?

 I really miss the BW app on the phone, as it is necessary for a lot of my day-to-day use.

**Comment by kspearrin** [comment]
I just testing installing v2.5.6 from F-Droid on my Nexus 5X and it seems to work without issue

**Comment by NipponBill** [comment]
I figured it out.

I had created a separate user profile in Android. That profile had Bitwarden 2.3.1 installed from F-Droid. Uninstalling BW from that profile, and then reinstalling was successful. Back on the main profile, I still saw multiple versions of BW listed, but installing from the 2nd listing was successful.

**Comment by mportune-bw** [comment]
Great to hear, thanks for letting us know.
