### ISSUE TITLE
Autofill not working for HTTP authentication form on Chrome Android

### ISSUE THREAD

**Issue by minhng99** [bitwarden/mobile#1009]
## Describe the Bug

Autofill does not show up on Basic HTTP Authentication form of Chrome 83.0.4103.106 on Android

## Steps To Reproduce

Try to use the autofill feature on such form in Chrome.

## Expected Result

Auto-fill working normally.

## Actual Result

There's no auto-fill overlay/notification displayed, using the *Auto-fill* shortcut on Quick Panel shows "No password fields detected".

## Screenshots or Videos

![20200712_221236](https://user-images.githubusercontent.com/14113155/87250084-4a3b8b00-c452-11ea-998c-dfa716297da4.jpg)

## Environment

- Device: Samsung Galaxy Note10 Lite (SM-N770F)
- Operating system: Android 10, Samsung OneUI 2.1
- Build Version (go to "Settings" → "About" in the app): 2.5.0 (3093)
- Is this a Beta release? [N]

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
