### ISSUE TITLE
New force close after updating from Google Play

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/mobile#101]
Hi,

Right after updating to 1.7.0 I can't open the app.
I have to clear app data to be able to use bitwarden.

[Log_2017-06-12_14-51-02.txt](https://github.com/bitwarden/mobile/files/1068201/Log_2017-06-12_14-51-02.txt)

**Comment by kspearrin** [comment]
Duplicate #100

**Comment by kspearrin** [comment]
Actually this is a different issue.

**Comment by kspearrin** [comment]
Are you able to consistently reproduce this if you go from 1.6.5 => 1.7.0 upgrade? You can leave the beta to get 1.6.5 again. Or use these APKs:

1.6.5: https://github.com/bitwarden/mobile/releases/download/v1.6.5/com.x8bit.bitwarden.apk
1.7.0: https://ci.appveyor.com/api/buildjobs/h5tqmria5ij5uie5/artifacts/com.x8bit.bitwarden-847.apk

**Comment by kspearrin** [comment]
Some potential fixes in 852. In beta channel now.

**Comment by Primokorn** [comment]
The update works flawlessly this way.
The force closes seem to happen when updating from a beta to a newer one.

**Comment by kspearrin** [comment]
Great. Thanks.

The beta => beta crashes are just because of bugs I keep creating, and then fixing :)

**Comment by Primokorn** [comment]
Gotcha then I'll stop reporting them ;-)

**Comment by kspearrin** [comment]
No, please don't! It's important to make sure we catch them in beta so I don't push them to production channel :) I can deal with the noise.

**Comment by Primokorn** [comment]
OK, no problem.
