### ISSUE TITLE
Samsung internet, two autofill boxes, two different URI

### ISSUE THREAD

**Issue by Batmanerman** [bitwarden/mobile#1016]
## Describe the Bug

Autofill will not work with Samsung Internet on S20+. Shows URI as androidapp://com.sec.android.app.sbrowser, and not as website. Then, when selecting from that list, it autofills and then a new autofill box shows up with the correct web URL. Basically get two autofill boxes. 

## Steps To Reproduce

Bitwarden android 2.5
Samsung internet 12.0.1.47
Autofill enabled, normal and accessibility 
internet://flags/#force-renderer-accessibility, web accessibility enabled (without this enabled, I do not get second box, but then also no website shows up in URI) 

Go to Github signin page, autofill box shows up with URI of androidapp://com.sec.android.app.sbrowser, select Github login from your list, box disappears and new one shows up with URI of the Github website (which is correct).

**Comment by ariccb** [comment]
I'm having the same exact experience. The first autofill button that shows up is rounded and blue, and the second (correct one that correctly autofills) is black and white and rectangular, no rounded edges.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
