### ISSUE TITLE
Disable Save Prompt not working

### ISSUE THREAD

**Issue by nquijano** [bitwarden/mobile#1017]
On Android Pie 9.0 with May 2019 security patch for LG G6 Thin Q, unrooted, with autofill and accessibility services enabled, I get spurious and annoying save prompts, that also carry the danger of overwriting a valid password with bad data. 
I enabled accessibility service as the autofill is missing nearly all login fields. Since then, I've been getting a lot of BW's popups to either save what it thinks is a new password (not the case) or to update an existing one that hasn't changed. Also, it seems to ignore the URL blacklist for autofill.

**Comment by andreapx** [comment]
Is this issue been forgotten?

**Comment by blackandyellowgecko** [comment]
I also have the same problem!

**Comment by alionti998** [comment]
Happening with 2.15.0

**Comment by alionti998** [comment]
Thanks, my device is a Samsung A70. It's been happening with the latest version (2.15.0). Previous versions had no issues, last OS update was on November 24. Uninstall/reinstall makes no difference. Blacklist URIs also does no prevent prompt. It's been happening on Firefox and Samsung calculator app.

**Comment by andreapx** [comment]
@jlf0dev if I can be of any help with logs, tests, something else, just let me know!

**Comment by jlf0dev** [comment]
@alionti998 Thanks for the information, which OS are you on? Android 11?

@andreapx Could you provide your device model and OS version as well?

Thanks for the help, still tracking this one down.

**Comment by alionti998** [comment]
Hi @jlf0dev , I'm currently on Android 11

**Comment by andreapx** [comment]
Hi @jlf0dev I'm using a OnePlus 6T with Android 11 (OxygenOS 11.1.2.2)

**Comment by jlf0dev** [comment]
@andreapx @alionti998 could ya'll provide a workflow I could reproduce the save prompts with? I know Firefox was mentioned, is there a website it happens every time on? Are you using the accessibility service to autofill and it still prompts to save? Thanks

**Comment by alionti998** [comment]
Hi @jlf0dev , after doing some quick testing it seems to happen with this scenario:

1. Make sure Bitwarden Android App vault is locked.
2. Autofill any website using the Firefox mobile extension
3. Observe the save prompt when logging in

All autofill services are enabled in the app including accessibility.

**Comment by jlf0dev** [comment]
Thanks for the response @alionti998. Still having some trouble reproducing the save prompt. Could you look and see if I've done anything wrong here? A screen recording showing your steps would help tremendously if you have the time.

https://user-images.githubusercontent.com/24985544/149164783-3677824f-0ff9-4941-813a-1d6d2cb7612b.mp4

**Comment by andreapx** [comment]
Hi @jlf0dev to me happens always on the app andOTP (app for OTP/2FA), every time I insert the pin, I get the popup that asks "Save password to Bitwarden?" This happens with vault locked and unlocked.
It doesn't seem to happen on logins with Firefox.

**Comment by alionti998** [comment]
Hi @jlf0dev 
Here's a short video, note that I'm using the Bitwarden extension to Autofill. The Bitwarden Android app vault is locked and save prompts are disabled on both the extension and app

https://user-images.githubusercontent.com/22989161/149230876-2bebce49-198c-4ffd-b51b-b6a070f40e38.mp4

**Comment by jlf0dev** [comment]
Thanks for all the help everyone. While these issues appear to be of separate origin, I believe the "Disable Save Prompt" isn't working as intended to prevent these prompts. I'll look into this further and we should have a fix soon.
