### ISSUE TITLE
Autofill not working on Samsung Internet Beta

### ISSUE THREAD

**Issue by jenabaivab** [bitwarden/mobile#1022]
## Describe the Bug

Autofill not working on Samsung Internet Beta

## Steps To Reproduce

1. Go to 'github.com'
2. Click on 'sign in'
3. Click on url box or password box

## Expected Result

Autofill options to appear

## Actual Result

Nothing appears from Bitwarden

## Screenshots or Videos

![Screenshot_2020-07-26-19-31-18-03](https://user-images.githubusercontent.com/60446763/88480991-ce276400-cf76-11ea-8bf3-67de793ea2c1.jpg)

## Environment

- Device: Realme X2
- Operating system: Android 10
- Build Version : 2.5.0(3093)
- Is this a Beta release? N

**Comment by Greenderella** [comment]
I've just tested and autofill works fine in Samsung Internet V 12.0.1.47 and Bitwarden 2.5.0(3093), you may just need to review the settings for both Autofill Framework Service and Auto-fill Accessibility Service: https://bitwarden.com/help/article/auto-fill-android/

**Comment by jenabaivab** [comment]
The samsung internet beta version is 12.1.1.29. Both permissions are provided as well, normal and accessibility.

**Comment by Greenderella** [comment]
Could you try disabling and re-enabling them again?

**Comment by jenabaivab** [comment]
That didn't help either.

**Comment by Greenderella** [comment]
Some user with Android 10 reported that the autofill function actually works best with the Auto-fill Accessibility Service disabled, so they only relay on the Framework one.

Also, it's GitHub the only page where you experience this?

**Comment by jenabaivab** [comment]
Tried disabling accessibility, didn't help. On the contrary, I stopped seeing Bitwarden autofill on Brave and Chrome.

Not just github, I tried other websites as well. The auto-fill windows doesn't appear anywhere.

**Comment by jenabaivab** [comment]
A user on reddit confirmed, it's not working on the beta version.

**Comment by jenabaivab** [comment]
Are there any developments with this issue?

**Comment by RePacked** [comment]
Can confirm. Not working on:

Samsung Internet Browser
Samsung Internet Browser Beta 
DuckDuckGo Browser

Device: OnePlus 8
Operating system: Android 10 (OxygenOS 10.5.9.IN21BA)
Build Version: 2.5.0 (3093)
Is this a Beta release? No

**Comment by yurividal** [comment]
Samsung internet beta 13 was just released today. They have open some extra APIs for developers to add extensions, and their release note specifically states that Dashlane has an extention that works with the browser.

https://medium.com/samsung-internet-dev/samsung-internet-13-0-beta-692d2673d9fe

Maybe we can get a bitwarden extension!? I think that's probably our only way to get this to work.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by douglasparker** [comment]
@eliykat That issue looks entirely unrelated. This isn't an issue that happens on specific websites. It simply doesn't work at all.

**Comment by eliykat** [comment]
Hi @douglasparker, that issue is intended to capture all cases where autofill isn't working, or isn't working consistently, whether it's generally or in specific instances. I've updated the wording to reflect this.
