### ISSUE TITLE
TOTP QR Code Scan Causes APP Crash Samsung Galaxy S10+

### ISSUE THREAD

**Issue by jn1102** [bitwarden/mobile#1023]
Upon scanning a QR Code, the app crashes.

Bitwarden crashes while scanning QR code generated by M365. (And others, but this causes crashing consistently).

This is the "other" QR Code that is basic TOTP NOT the Microsoft Authenticator QR Code.

1. Open Bitwarden on Android and navigate to existing item
2. Open item and tap the "edit" pencil in the bottom right
3. Tap the camera icon under (TOTP)
4. Scan QR Code
5. App Crash

## Expected Result

I expect the 6 digit rolling TOTP code to show up.

App Crash

## Environment

- Device: Samsung Galaxy S10+
- Android 10 July 1 2020 update
- Build Version: Kernel 4.14.117 QP1A.190711.020.G975USQS4DTF6
- Is this a Beta release? No.

**Comment by cscharf** [comment]
Duplicate issue. Resolved with: https://github.com/bitwarden/mobile/issues/975
