### ISSUE TITLE
Security Code(CVV) cannot be hidden/shown after toggling visibility

### ISSUE THREAD

**Issue by vachan-maker** [bitwarden/mobile#1029]
## Describe the Bug

Issue similar to #1025  #1027 
Pin does not hide when pressing the hide button after showing the pin.

## Steps To Reproduce
_Do not save the item_

1. Open the card type
2. Enter some digits in the security code field
3. Press the eye icon multiple times

## Expected Result

Pin should be shown and hidden properly

## Actual Result
Pin cannot be hidden after showing the pin.

## Environment

Device: Huawei Honor 5C EMUI 5.0.2
Operating system: Android 7.0 Nougat
Build Version 2.5.0 (3093)
- Is this a Beta release? [Y/N] N

**Comment by cscharf** [comment]
This should be resolved with https://github.com/bitwarden/mobile/pull/1027 as soon as that is released. It is the same root cause.
