### ISSUE TITLE
Chrome extension on iPadOS 13 doesn’t find matching site

### ISSUE THREAD

**Issue by jimpassmore** [bitwarden/mobile#1035]
## Describe the Bug

In iPadOS 13 (at least 13.5 and 13.6) using Chrome, after sharing to BitWarden the extension does not find the vault entry.  All works as expected in Firefox.

## Steps To Reproduce

1. Using Chrome, go to a site with a login.
2. “Share” to Bitwarden

## Expected Result

BitWarden should suggest a login corresponding to the site.

## Actual Result

BitWarden shows a message saying “there are no items in your vault” when trying this from Chrome.  All works fine in Firefox.

## Screenshots or Videos

From Firefox
![FFbit](https://user-images.githubusercontent.com/6353588/89749422-a6b3b980-da95-11ea-903d-e1400f7fc54c.jpeg)

From Chrome
![Chrome it](https://user-images.githubusercontent.com/6353588/89749460-ce0a8680-da95-11ea-8ec1-f9feb9f7d40b.jpeg)

## Environment

- Device: iPad 7th Gen
- Operating system: iPadOS 13.6
- Build Version (go to "Settings" → "About" in the app): 2.5.0 193
- Is this a Beta release? N

**Comment by mokshmridul** [comment]
Im having the exact same issue as this on iPasOS (Beta 5).
Note: I am also using Botwarden_RS as the backend Vault.

**Comment by ss89** [comment]
I can confirm the same issue on iPhone (11 pro)
iOS 13.7
Bitwarden 2.5.0
Chrome 85.0.4183.109
3rd party api implementation on the backend side
