### ISSUE TITLE
Unable to view notes - iOS

### ISSUE THREAD

**Issue by rynmdk** [bitwarden/mobile#104]
When creating a note with no login information, only notes, you are unable to see these when you view the item.

![img_1384](https://user-images.githubusercontent.com/30160565/28292657-e4380042-6b47-11e7-9131-4802c2a50da9.PNG)
![img_1383](https://user-images.githubusercontent.com/30160565/28292658-e438b316-6b47-11e7-8fd7-6b500c92f36b.PNG)

**Comment by kspearrin** [comment]
Hmm. I am unable to reproduce. Does this happen every time or just this one entry?

**Comment by rynmdk** [comment]
Yep seems to be the same for every note that i add. As a workaround if I add something into the URI field it allows the note to show as it should, but if there is only just a name then same issue.

**Comment by kspearrin** [comment]
That's odd. The latest dev build I am using doesn't produce that so maybe we fixed it going forward already.

**Comment by kspearrin** [comment]
Is this still a problem?

**Comment by rynmdk** [comment]
Hi sorry for the late reply. This is no longer an issue. Thanks
