### ISSUE TITLE
bitwarden 2.5 on zenfone 2, android 6.0.1 (x86) doesn't work

### ISSUE THREAD

**Issue by ronkwann** [bitwarden/mobile#1042]
## Describe the Bug
bitwarden 2.5 (Google Play) on ASUS Zenfone 2 (z008), newly installed Android 6.0.1 x86 (Official ASUS rom version WW-4.21.40.311) doesn't work.

Tap on icon, "bitwarden" banner flashes, then quits

on the other hand, bitwarden 2.4.2 universal apk found on apkmirror_dot_com does work normally on the same phone.

## Steps To Reproduce

1. Tap on "Bitwarden" icon
2. "bitwarden" banner flashes

## Expected Result

App launches normally and allows me to login or create a new account.

## Actual Result

App quits after the banner and falls back to launcher.

## Environment

- Device: ASUS Zenfone 2 (z008)
- Operating system: Android 6.0.1 x86
- Build Version: 4.21.40.311
- Is this a Beta release? N

## Additional Context

this is an x86 phone.

**Comment by flaviovs** [comment]
Exact same thing here: Lenovo Yoga Book with Android 6.0 on x86.

Installed 2.5.6 APK from GitHub and now the app opens.

**Comment by clayadams5226** [comment]
Hi @ronkwann, are you still having this issue with the newest version of the app?

**Comment by clayadams5226** [comment]
It appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
