### ISSUE TITLE
Support Android 11's keyboard autofill

### ISSUE THREAD

**Issue by johns2s** [bitwarden/mobile#1046]
Android 11 is introducing changes to move autofill from the current drop-down menu into the keyboard, which looks like it'll resolve some of the issues people have had with the current implementation. 

It'd be great if Bitwarden could support this on day 1.

https://developer.android.com/preview/features/ime-autofill

**Comment by tgreer-bw** [comment]
😄  https://community.bitwarden.com/t/support-autofill-via-keyboard-on-android-11/13783

Feel free to join the community and vote on the topic (and lots of others) - it is something we're looking into for sure.

**Comment by johns2s** [comment]
Merged
