### ISSUE TITLE
Auto-fill not working on username in Teams app

### ISSUE THREAD

**Issue by realgrm** [bitwarden/mobile#1053]
## Describe the Bug

 Auto-fill not working on username in Teams app

## Steps To Reproduce

Since I already have signed in accounts, these are the steps:
1. Open Teams app (microsoft.teams.com)
1. Click on the hamburger menu
1. Click on 'Add account'
1. Click on 'Sign in with another account'
1. Click on 'Enter email, phone, or Skype'
1. (Auto-fill doesn't work)
1. Long press on 'Enter email, phone, or Skype'
1. Click on 'Autofill'
1. (Auto-fill doesn't work)
1. Write the username
1. Click on 'Sign in'
1. (It redirects to a webpage)
1. Click on 'Password'
1. (Auto-fill works)

## Expected Result

 Auto-fill username

## Actual Result

 Not auto-filling username. Even when long-pressing on the field and selecting 'Autofill' . It only fills the password on the next step

## Screenshots or Videos

- Clicking for auto-fill username
![image](https://user-images.githubusercontent.com/23300290/91638541-aa789300-e9e6-11ea-8610-4ad524365190.png)

- Not auto-filling username
![image](https://user-images.githubusercontent.com/23300290/91638591-f6c3d300-e9e6-11ea-85b8-ccf7d2e3ba0a.png)

- Auto-filling password
![image](https://user-images.githubusercontent.com/23300290/91638639-4904f400-e9e7-11ea-9324-e73aaeaa4df6.png)

## Environment

- Device: Oneplus 7 (GM1900)
- Operating system: Android 10 (Oxygen OS 10.3.3.GM57AA)
- Build Version: 2.5.0 (3093)
- Is this a Beta release? N
- Teams app version: 1416/1.0.0.2020081801

## Additional Context

I have 2 business account logged in in this app, and it doesn't allow to take screenshots. So I can't use UI Automator Viewer to get the '.uix' file.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
