### ISSUE TITLE
Autofill not woring on Android Binance mobile app

### ISSUE THREAD

**Issue by laurentfrenette** [bitwarden/mobile#1057]
## Describe the Bug

Autofill is not working well with the mobile Binance (#1 bitcoin Exchange) app. On the login screen, the autofill pop up is there, but when you click on it, nothing happens the first time. The second time you do it, only the password gets autofilled and not the username.

## Steps To Reproduce

1. Download the official Binance app on Google Play Store https://play.google.com/store/apps/details?id=com.binance.dev&hl=fr_CA
2. Create a dummy account entry on Bitwarden containing a regex rule for the matching keyword "Binance" and add a random email/password (no need to have a real account)
3. Open the binance App and try to autofill the login form with the previously created dummy account.  You'll notice that on the first attempt, both the email & password input won't be autofilled.
4. Try to autofill again. This time, only the password input will be autofilled.

## Expected Result

It would be expected that both the email & password input field would be autofilled when you click autofilled.

## Actual Result
On the mobile Android Binance app, When you click "Autofill" the first time time, nothing happens. The second time you click it, only the password field gets autofilled and the email/username remains unfilled.

## Screenshots or Videos

No screenshots available as the Binance app doesn't allow you to take screenshot for security purposes.

## Environment

- Device: Google Pixel 3
- Operating system: Android 10
- Build Version : QQ1A.191205.008
- Is this a Beta release? No

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by freeelectron-ro** [comment]
Please solve it, because it is still present this  bug

**Comment by Wladastic** [comment]
Still an issue

**Comment by mohamedpsx** [comment]
Still an issue - any planned fix for this?
