### ISSUE TITLE
Passphrase Generator Options Reset

### ISSUE THREAD

**Issue by lschober-bw** [bitwarden/mobile#1059]
## Describe the Bug

The passphrase generator has two options that can be toggled.

- Capitalize
- Include Number

If these are toggled on and the user locks the application, then unlocks and navigates to the generator, these two options are reset to the default off position.

This behavior is consistent across Android 10 and iOS 13.6.1. 

Devices using Android 9 are not affected and do not exhibit this behavior. The two options are persisted through locking/unlocking.

## Steps To Reproduce

1. Log in or unlock the application
2. Navigate to the generator and select passphrase
3. Toggle on the "Capitalize" and "Include Number" options.
4. Navigate to Settings > Security > Lock Now to lock the application
5. Unlock the application and open the passphrase generator

## Expected Result

Both "Capitalize" and "Include Number" options are enabled.

## Actual Result

Both are disabled.

## Environment

- Device: Pixel 2 XL, iPhone SE (2020)
- Operating system: Android 10, iOS 13.6.1
- Build Version (go to "Settings" → "About" in the app):  2.5.6 (3110), 2.5.0 (1.93)
- Is this a Beta release? N

**Comment by captainhook** [comment]
I am seeing similar behaviour.
Organisation policy is set to require 'Capitalize' and 'Include Number', however both options are toggled off and disabled in the Android app even from a clean login (cleared app data).
