### ISSUE TITLE
[Bug] No site detection with Firefox (Android)

### ISSUE THREAD

**Issue by JanSeW** [bitwarden/mobile#107]
Hey guys,

today I've tried to use Bitwarden with the newest Firefox release (not Klar) on Android.
But the Bitwarden notification doesn't appear (on the contrary to Chrome).

So I think this is a bug.
Hope, this will be fixed soon.

Thxalot,
JanSe

**Comment by kspearrin** [comment]
@JanSeW This is a known issue that we can do nothing about unfortunately. Firefox does not support accessibility events. This is documented here in our help article: https://help.bitwarden.com/article/auto-fill-android/

Here is a bug report for Firefox (4 years old): https://bugzilla.mozilla.org/show_bug.cgi?id=961540

**Comment by scheinercc** [comment]
Hi @kspearrin, does that mean I can't use auto-fill with Firefox for Android at all?

**Comment by kspearrin** [comment]
@scheinercc Not with the accessibility service. Soon you will be able to install the bitwarden browser extension into Firefox Android which offers a usable solution (though not as convenient as the app).

**Comment by scheinercc** [comment]
Awesome! Looking forward to the app :) (also commented on the bug - it sometimes helps)

**Comment by Primokorn** [comment]
@scheinercc you can already use the addon from AMO. It works well with FF beta.

**Comment by kspearrin** [comment]
Addon is now available fore Android. Search for it from Firefox Settings -> Addons.

**Comment by scheinercc** [comment]
Works with Nightly as well.

**Comment by kumarharsh** [comment]
The Firefox team is working on adding autofill. It may land soon.

**Comment by rix1337** [comment]
Might say farewell to brave quite soon, then. :+1:

**Comment by Primokorn** [comment]
@kumarharsh The new API or the legacy one (from the notification panel)?

**Comment by rix1337** [comment]
Both, according to the bugzilla ticket.

Just installed the latest mobile nightly... which doesnt work with bitwarden for me.

**Comment by kumarharsh** [comment]
Sorry, I forgot to add the links to bugzilla in my previous comment. Here they are for reference. Seems like Firefox would use the new API introduced in Oreo...

https://bugzilla.mozilla.org/show_bug.cgi?id=1330257
https://bugzilla.mozilla.org/show_bug.cgi?id=1485810
