### ISSUE TITLE
TOTP not working on iOS application

### ISSUE THREAD

**Issue by ronivay** [bitwarden/mobile#1076]
## Describe the Bug

Just upgraded my self-hosted bitwarden to premium version and added couple TOTP tokens (github and paypal). They both work fine on desktop application and desktop browser extension but not on iOS application. Application itself doesn't show TOTP codes anywhere and doesn't offer an option to copy TOTP code from the "my vault" list. 

Credential autofill works as it should in the Safari mobile browser but TOTP codes aren't copied to clipboard even though it's not disabled in settings. I can see Copy TOTP code through browser extention menu along with Copy username and Copy password but clicking the Copy TOTP code doesn't do anything as with other options clearly say like "username copied" and those are actually copied to clipboard, TOTP code not.

## Steps To Reproduce

Enable TOTP and try to login 2FA enabled service through Safari.

## Expected Result

TOTP code copied to clipboard automatically when enabled and possible manually through browser extention. I would expect the application to show these codes as well so they could be manually copied if other options fail. Currently only the TOTP "url" is shown but nothing else. Desktop application, browser extention and web ui all show the rolling code when login item is opened. Currently it's not possible to login to 2FA enabled services with mobile without opening the Web UI with mobile browser to fetch the TOTP code.

## Actual Result

TOTP code not copied and can't be copied at all with browser application.

## Environment

- Device: iPhone 11 pro
- Operating system: IOS 14.0
- Build Version (go to "Settings" → "About" in the app): 2.6.0 (262)
- Is this a Beta release? N

**Comment by ronivay** [comment]
Oh well, just syncing the vault wasn't enough as it was with desktop browser extension. Complete logout/login fixed all this which i didn't realize to do earlier.

**Comment by jamesjarvis** [comment]
Just came across this issue as well, turns out logout -> login also fixed it for me 👍🏻

**Comment by dzg** [comment]
I tried logging out and in and still not seeing any TOTP codes on iPhone app. What am I missing?
