### ISSUE TITLE
Crash on startup on iOS

### ISSUE THREAD

**Issue by hamtaai** [bitwarden/mobile#1078]
## Describe the Bug

When I open the app it crashes instantly.

## Environment

- Device: iPhone 6
- Operating system: iOS 12.4.8
- Build Version (go to "Settings" → "About" in the app): 2.6.0
- Is this a Beta release? No.

## Additional comments

It started happening in 2.6.0 only, before that all was fine.

**Comment by k-van-man** [comment]
Same here on iPad Air 2 with IOS 14.0

after enter a password (Good or bad) the Bitwarden app disappears, its stil runnend but not logged in.

It works on iPhone SE2 with IOS 14.0

**Comment by jjsadek** [comment]
Same here, iPhone XR IOS 14.0. App crashes right after master password authentication. Tried rebooting and the problem persists.

**Comment by kurzdev** [comment]
Can confirm, after entering Master Password and clicking "Log In" the app immediately crashes on iOS 14 (selfhosted, 2FA activated)

**Comment by Override92** [comment]
Also crashes on my OnePlus 6 running android 10.

**Comment by Mohrengemuse** [comment]
I'm on a OnePlus 7 and get the same behaviour. After reinstallation, the first login works, than crashing again.

**Comment by cscharf** [comment]
Thanks everyone, we'll be attempting a new patch release here very soon that should resolve this issue.

**Comment by benpete22** [comment]
> I'm on a OnePlus 7 and get the same behaviour. After reinstallation, the first login works, than crashing again.

I too am on a one plus 7. 
I uninstalled and reinstalled, and now I am able to open the app, but when I try to enable Biometric unlock it crashes every time.

**Comment by mportune-bw** [comment]
Closing this as the fix has been published and is pending review

**Comment by benpete22** [comment]
> > I'm on a OnePlus 7 and get the same behaviour. After reinstallation, the first login works, than crashing again.
> 
> I too am on a one plus 7(pro).
> I uninstalled and reinstalled, and now I am able to open the app, but when I try to enable Biometric unlock it crashes every time.

I was also able to resolve this issue by deleting my passcode on my Android phone, then setting up the passcode and biometric unlock again.
Sounds like if you setup your fingerprints before upgrading to Android 10 it was still using an old API call for Fingerprint instead of Biometric.

**Comment by Mohrengemuse** [comment]
@benpete22 thanks! That helped me too.

**Comment by hamtaai** [comment]
I updated to 2.6.1 and the issue is gone, thanks!
