### ISSUE TITLE
Biometric got crashed

### ISSUE THREAD

**Issue by ngdangtu-vn** [bitwarden/mobile#1088]
## Describe the Bug
If users got an automatically update from Google Play Store, the app will constantly got crashed. The only way to fix it is reinstalled. After reinstalled, crash is gone but along with it is biometric. (I think biometric is in love with crash or something)

## Steps To Reproduce
Activate Biometric security system in Setting.

1. Open app
2. Goto `Settings`
3. Goto `Security` section
4. Unlock with Biometrics (it is `disable` before we click on it)
5. Touch the fingerprint sensor
6. Enjoy the crash

## Expected Result
The biometric security system should be `active` and work normally like previous version.

#### Before reinstall: 
Lady & Gentleman, crashed everywhere. On the root, under rug, in the kitchen couple. Crash is everywhere. And report crash is the only option in the infinitivellion options that Mister-Weird has foreseen.

#### After reinstall:
I got nothing but crashed. But I'm still able to open the app like normal.

## Screenshots or Videos
[![crash msg after reinstalled](https://i.imgur.com/iOi7xnW.jpg)](https://imgur.com/a/2kJwGhx)

## Environment

- Device: LGM-G600S
- Operating system: Android 8
- Build Version: 2.6.0
- Is this a Beta release? N

## Additional Context
I've nothing to regret.

**Comment by mportune-bw** [comment]
Update will be released shortly

**Comment by benpete22** [comment]
I was also able to resolve this issue by deleting my passcode on my Android phone, then setting up the passcode and biometric unlock again.
Sounds like if you setup your fingerprints before upgrading to Android 10 it was still using an old API call for Fingerprint instead of Biometric.
