### ISSUE TITLE
Cannot create or view saved autofill logins on Simplenote - iOS

### ISSUE THREAD

**Issue by laserstrike** [bitwarden/mobile#109]
When using autofill for the iOS version of Simplenote, I tap the keyhole icon but my saved Simplenote login does not show up. Even when instructed to create one after tapping the keyhole icon, I input the necessary credentials and tap save, but instead I am taken back to the empty There are no logins window.

**Comment by kspearrin** [comment]
This should be fixed in the next version. Simplenote is passing "simplenote.com" as the URI, which is not a valid URI (should be "http://simplenote.com"). I put in a patch for it. See https://github.com/bitwarden/mobile/commit/8e2d654b407e276bd3aad9a46f3b65859518b1d8
