### ISSUE TITLE
IOS autofill

### ISSUE THREAD

**Issue by nguyencaoducminh** [bitwarden/mobile#1090]
## Describe the Bug
When go to app after there are changes with touch ID the app requires to enter master password again however if you have using touch ID to autofill on, you can still use autofill without enter master password.

## Steps To Reproduce
Step 1: Set up a test touch ID.
Step 2: Enter the Bitwarden app.
Step 3: Tap the master password input box to open keyboard.
Step 4: Click to autofill the password.
Step 5: Use you fingerprint to fill the master password.

Note: Make sure you have ‘Password Autofill’ on and ‘Unlock with touch ID’ enable and also save you master password in vault

## Expected Result
The autofill should require to enter master password.

## Actual Result
The autofill let you use fingerprint without require to enter the master password again.

## Screenshots or Videos
Link to a video: https://drive.google.com/file/d/12pbhje8262fPSFFplYHx7pq9IzUW0f-C/view?usp=drivesdk

## Environment
- Device: iPhone 6s
- Operating system: IOS 14.0
- Build Version: 8.02.01
- Is this a Beta release? N

**Comment by kspearrin** [comment]
@Hinton
