### ISSUE TITLE
Autofill not identifying correct result on lightning browser

### ISSUE THREAD

**Issue by jerryn70** [bitwarden/mobile#110]
I tried to login github using lightning browser, when i click the password field bitwarden shows notification and when I click the notification it didn't show github result. 
It shows acr.ligthning.com as the url and shows add button . That means bitwarden is not recognized the url that I visited . This same issue is also with Firefox focus browser.

**Comment by kspearrin** [comment]
We have to add support for each browser individually. This one is not on the list, but we can add it.

Is this it?

https://play.google.com/store/apps/details?id=acr.browser.lightning
https://play.google.com/store/apps/details?id=acr.browser.barebones

**Comment by jerryn70** [comment]
Yes.

please add Firefox focus also 

https://play.google.com/store/apps/details?id=org.mozilla.focus

**Comment by kspearrin** [comment]
Added for next release: https://github.com/bitwarden/mobile/commit/2ed5c0c5cc23876a4d5090870f1907a489d8f132
