### ISSUE TITLE
Make text in Android pascal case

### ISSUE THREAD

**Issue by vachan-maker** [bitwarden/mobile#1103]
Text in Android is full upper case while text in iOS is pascal case. Especially text placed within buttons. This issue is not a serious one. Just wanted to point this out. Thanks

**Comment by clayadams5226** [comment]
Hi @vachan-maker, are you still seeing this issue? Please use the Issue Template [https://github.com/bitwarden/mobile/blob/master/ISSUE_TEMPLATE.md](url) when creating issues so we can better assist you. This ticket will be closed due to vagueness and can be reopened if needed.

**Comment by vachan-maker** [comment]
> 
> 
> Hi @vachan-maker, are you still seeing this issue? Please use the Issue Template [https://github.com/bitwarden/mobile/blob/master/ISSUE_TEMPLATE.md](url) when creating issues so we can better assist you. This ticket will be closed due to vagueness and can be reopened if needed.

On all Android devices, the text is actually in Pascal Case. But on iOS text is lower case. Chad actually did confirm this. 
Keep this issue closed, its not a big deal.
