### ISSUE TITLE
Android App Immediately Closes when Unlocking AND Syncing Failed

### ISSUE THREAD

**Issue by Gitarski** [bitwarden/mobile#1111]
## Describe the Bug

With the latest Android Bitwarden App, 2.6.1, when I login or after I've logged in and try to Unlock the session, the application immediately closes.  When I enter an incorrect password, the app correctly displays that the wrong password was entered.

I tried to re-install the previous version of the app and then after successfully logging in, a message popup shows Syncing Failed.  Manually syncing produces the same Syncing Failed popup.

## Steps To Reproduce

When logging in:

1. Start the app
2. Enter valid credentials
3. Click on Login

When already logged in and unlocking session:

1. Enter master password
2. Click on Unlock

## Expected Result

Show vault

## Actual Result

Applications closes and goes back to previous page.  For example, if app is started from application list, it closes and immediately goes back to the application list.

## Screenshots or Videos

N/A

## Environment

- Samsung Galaxy Note 3
- Operating system: Android 10 (Havoc 3.5 from XDA)
- Build Version (go to "Settings" → "About" in the app): QQ2A.200501.001.B3
- Is this a Beta release? N

## Additional Context

I had been using the Bitwarden app for a while and it was working properly.  I also had the auto-fill working.  I believe with the latest update, the stated problems started.

I also tried to re-install an older version and then the Syncing Failed started happening after successfully logging in.

I am using a locally hosted docker version of BitwardenRS.  When I go to the web page, all works properly.  The login page on the web shows version 2.10.1.  The chrome extension works properly.  Note that I do not have SSL set up and it's been like that since I installed it.  I cannot login to the web vault on Chrome...error is "Cannot read property 'ImportKey' of null"...however, I am able to login using Microsoft Edge and can see the vault and navigate properly.

Is there a debug log that can be turned on?  Or if/when it's on, where can the log be found on my phone?  When I view the log on the server, there is nothing odd.  In fact, this is in the log regarding syncing:

[2020-10-05 14:31:07][rocket::rocket][INFO] GET /api/sync application/json:
[2020-10-05 14:31:07][_][INFO] Matched: GET /api/sync?<data..> (sync)
[2020-10-05 14:31:07][_][INFO] Outcome: Success
[2020-10-05 14:31:07][_][INFO] Response succeeded.
[2020-10-05 14:31:09][rocket::rocket][INFO] GET /api/sync application/json:
[2020-10-05 14:31:09][_][INFO] Matched: GET /api/sync?<data..> (sync)
[2020-10-05 14:31:09][_][INFO] Outcome: Success
[2020-10-05 14:31:09][_][INFO] Response succeeded.

**Comment by mportune-bw** [comment]
I would contact the BitwardenRS team for an update.  2.10.1 is from mid-2019 - the client releases can drift only so far from the server releases before potential problems arise.  If the problem still occurs after you've updated everything, go ahead and re-open this issue.

**Comment by Gitarski** [comment]
FYI, for others that may have similar issues or need a couple of clues...

I updated to the latest docker image and then created my own Certificate Authority and keys for Bitwarden.  Worked out well.  I first exported old vault and reimported it...all back up.

Changes that I needed to make is add an ssl directory mount and specify the files used for Rocket TLS.
