### ISSUE TITLE
Different character restriction between mobile and desktop for card numbers

### ISSUE THREAD

**Issue by mmattel** [bitwarden/mobile#1113]
## Describe the Bug

Comparing desktop to mobile, on mobile (IOS) you can only type numbers but no letters in the card number field. This may sound strange as you might think that a debit card like ATM has numbers only and desktop is wrong. It is the other way round, desktop is correct allowing alpha-numeric characters (A-Z, 0-9, blank). In Europe, a bank card for use with ATM only has a "number" field (=IBAN) starting with the country (like AT, DE ect) following by numbers representing a hash code, the bank id and the bank account number.

## Steps To Reproduce

1. Create a new item from type card
2. Try to add a IBAN in the number field based on the criteria above

## Expected Result

Being able to enter A-Z, 0-9, blank
eg: ATxx xxxx xxxx xxxx xxxx

## Actual Result

You can enter numbers only

## Environment

- Device: iPhone SE
- Operating system: iOS 14
- Build Version (go to "Settings" → "About" in the app): 2.6.1 (278)
- Is this a Beta release? N

## Additional Context

It might be an alternative to add a card type like ATM-EU where you have instead a IBAN + a mandatory field named BIC. In this case, desktop needs this card type too.

**Comment by kspearrin** [comment]
Fixed with https://github.com/bitwarden/mobile/pull/1097
