### ISSUE TITLE
Visual Autofill Bug on iOS

### ISSUE THREAD

**Issue by ACodingGenie** [bitwarden/mobile#1115]
When using auto fill feature on iOS to sign into another app, the user cannot see what they're typing into the search field inside of vault when using "Black" theme.

## Steps To Reproduce

1. Open an app or web browser to sign into something.
2. Hit "Passwords" on your iOS keyboard.
3. Tap the magnifying glass if applicable to search for something. 
4. Notice how you cannot see what you are typing.

## Expected Result
User should be able to see what they're typing in auto fill's search field. 

## Actual Result
User can't see what they're typing because its the same color (black) as the background.

## Screenshots or Videos
You can sort of see it in this screenshot because its high res, but its impossible to see on a reflective display. 
![Screenshot](https://user-images.githubusercontent.com/68975831/95939396-fa9a9180-0da9-11eb-8817-41b3695c2e1d.PNG)

## Environment
- Device: iPhone SE 2020
- Operating system: iOS 14.0.1
- Build Version: 2.6.1 (278)
- Is this a Beta release? N

## Additional Info:
**Haven't found a way to consistently create this bug but will update if I can.**

**Comment by mportune-bw** [comment]
Fixed in next release
