### ISSUE TITLE
Support for newer builds of Ungoogled Chromium

### ISSUE THREAD

**Issue by nullsurfer** [bitwarden/mobile#1118]
Bitwarden already supports [Ungoogled Chromium](https://github.com/wchen342/ungoogled-chromium-android)  browser as added here https://github.com/bitwarden/mobile/issues/969. Newer builds however, are not supported because they changed the package name from `org.ungoogled.chomium` to `org.ungoogled.chomium.stable`

Please add the latest package name to supported browsers.

**Comment by contribucious** [comment]
@nullsurfer [PR](https://github.com/bitwarden/mobile/pull/1119) done. :thumbsup:
