### ISSUE TITLE
Unlock with both: Biometrics and PIN Code is fine with only one method

### ISSUE THREAD

**Issue by x80486** [bitwarden/mobile#1129]
## Describe the Bug

I have set both: `Unlock with Biometrics` and `Unlock with PIN Code`; any time I close the (mobile) application and open it up again, I just have to use one method to be able to finally use the application — instead of both methods.

## Steps To Reproduce

1. Setup `Unlock with Biometrics` and `Unlock with PIN Code`
2. Close the application and open it up again
3. Use either one method (successfully)

## Expected Result

User must be able to use both methods successfully in order to start using the application instead of just one of them.

## Actual Result

Only one method is sufficient.

## Environment

- Device: Nokia 8.3 5G
- Operating system: Android 10
- Build Version: 2.6.1 (3178)
- Is this a Beta release? N

**Comment by clayadams5226** [comment]
This is the expected behavior. PIN and biometric are meant to be exclusive from one another.

**Comment by x80486** [comment]
OK, well that's...unfortunate. I think you should consider, in the future, to make them both required — and probably have an option to toggle between both choices.

Feel free to close this one...otherwise make it a feature request :heart_eyes:
