### ISSUE TITLE
Auto-fill doesn't work for org.codeaurora.swe.browser

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/mobile#113]
Hi,

Examples where it works: Reddit
Examples where it doesn't work: web vault of bitwarden (oops :-)), XDA developers forum.

Using CAF based browser on Android 7.1.2.
bitwarden 1.8.1

*STR*:
1. Open https://vault.bitwarden.com/#/
2. Select the password filed to get bitwarden notification
3. Open bitwarden from the notification and search your credentials in your vault
4. Select *auto-fill* 
5. Back to the website, nothing happens. The field are still empty.

**Comment by kspearrin** [comment]
We purposely block it on the bitwarden web vault.

**Comment by Primokorn** [comment]
What about XDA?
Same issue on Github.

**Comment by kspearrin** [comment]
I have not tested XDA, but GitHub is one of the websites that is part of the testing process. It works for me there.

**Comment by kspearrin** [comment]
Try restarting the browser. I've seen it get into a state where it never works before and had to restart for some reason.

**Comment by Primokorn** [comment]
I tried by disabling Incognito mode (the browser must be restarted) and by force closing the app.

**Comment by Primokorn** [comment]
It works with Firefox Focus though.

**Comment by kspearrin** [comment]
> Using CAF based browser on Android 7.1.2.

What is CAF browser? Maybe we don't support this one yet.

**Comment by Primokorn** [comment]
package name: org.codeaurora.swe.browser
https://forum.xda-developers.com/android/apps-games/app-code-aurora-s-chromium-swe-browser-t3603932

**Comment by kspearrin** [comment]
Ah yea, we have to add each browser support manually so we'll have to look into this.

**Comment by Primokorn** [comment]
Yes I know it but I thought it could be somehting else since it works on other websites.
Looking forward to the next update :)

**Comment by kspearrin** [comment]
Wait, so `org.codeaurora.swe.browser` works sometimes?

**Comment by Primokorn** [comment]
Yes, on Reddit.com for instance.

**Comment by Ulugbeg** [comment]
I have the same problem (same browser) (in that it doesn't work), but haven't found a page where it DOES work (don't have a reddit account). Tried for instance amazon (.co.uk) and github. 

Behavior for me: it does show the shield in the notification bar, I can then select the auto-fill service, but then it says there are no logins in my vault for -- (that last bit is waht it actually litterally says - 'Logins for --' and below: there are no logins in our vault for --.

So it could be that what I'm seeing is actually a different problem? If so, let me know and I shall file a stand-alone bug.

**Comment by Primokorn** [comment]
@Ulugbeg This is something different and not a bug. The auto-fill service uses the package name of the browser to find credentials in your vault.
So switch to "My Vault" tab, search for your credentitals and select them.

**Comment by bendingtime** [comment]
@kspearrin should or can i add Samsung Internet Browser beta for android to list of supported? It is based on chrome but bitwarden does not work at all on it.

**Comment by kspearrin** [comment]
@bendingtime We already have samsung browser on the list, however, it does not send proper accessibility events. It cannot be supported at this time.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
