### ISSUE TITLE
Support for Soul Browser on Android

### ISSUE THREAD

**Issue by Guy-N-Cognito** [bitwarden/mobile#1131]
Please add support for **Soul Browser** on Android:
[https://play.google.com/store/apps/details?id=com.mycompany.app.soulbrowser](https://play.google.com/store/apps/details?id=com.mycompany.app.soulbrowser)

**Comment by Greenderella** [comment]
Hi @Guy-N-Cognito 

The request has been forwarded to our development team. If everything goes as expected, the support should be released in an upcoming update.

**Comment by djsmith85** [comment]
Hi @Guy-N-Cognito,

thanks to @dldhk97 the support for the Soul Browser was added with #1348.

This will be included in the next release.

**Comment by Icemanjoseph** [comment]
Good morning how can I off my webrtc leak on soul browser on Android

**Comment by djsmith85** [comment]
Closing this now.

@Icemanjoseph Unfortunately I cannot answer your question. Possibly someone from the Soulbrowser community at https://github.com/SoulBrowser/SoulBrowser can help.
