### ISSUE TITLE
No way to autofill on website and in-app

### ISSUE THREAD

**Issue by Nxt3** [bitwarden/mobile#114]
For example, the URI varies for the CapitalOne app and the CapitalOne desktop website. This is the case for several sites.

This means that I'll be able to autofill in the CapitalOne Android app--but not on the CapitalOne desktop website via the Bitwarden Chrome extension.

So, when adding the URI for a login, I have to choose whether I want to be able to autofill on desktop or mobile apps; I don't think this is user friendly and can be confusing when you're comparing the service to something like Lastpass (which seems to handle this well).

**Comment by kspearrin** [comment]
I think you want https://blog.bitwarden.com/new-feature-equivalent-domains-dd29aa462bb7

**Comment by Nxt3** [comment]
That does sound like what I want. Is there no way to do this from the app though? I didn't think you had to setup the rules manually in Lastpass.

**Comment by kspearrin** [comment]
You have to use the web vault to adjust these. Our web vault is mobile friendly.

**Comment by Nxt3** [comment]
I just got this working.

However, I think I've found a bug.
If I had added a login on Android via the prompt, it will add a login with the URI being the package name of the app. However, if I have the Domain Rule set to: "_capitalone.com, androidapp://com.konylabs.capitalone_", then it won't prompt for autofill on desktop. Only when I go back and edit the login to have the URI _capitalone.com_ will it prompt on both platforms.

Hopefully that makes sense.

**Comment by Nxt3** [comment]
Chrome on MacOS.

**Comment by kspearrin** [comment]
@Nxt3 I just tested this with Chrome on Windows and Android and it worked fine. Domain rule:

```
capitalone.com, androidapp://com.konylabs.capitalone
```

**Comment by kspearrin** [comment]
Make sure you have synced your apps before testing.

**Comment by Nxt3** [comment]
What is the URI for the CapitalOne login in the Vault though?

**Comment by kspearrin** [comment]
@Nxt3 `https://www.capitalone.com/`

I think you are saying that if it was `androidapp://com.konylabs.capitalone` it won't work on desktop?

**Comment by Nxt3** [comment]
Correct. If I have it set to "CapitalOne.com" everything works as intended. If it's the package name, it won't work even with the domain rule.

**Comment by esmoyer** [comment]
I'm still getting this issue as well with my credit union app. I even auto added the app login when offered through the Android O autofill but there is still no reciprocity between web and mobile app. I even copied the URI it saved when saving the login for the app on Android.

**Comment by talha131** [comment]
@esmoyer Work around for now, as suggested by @Nxt3 is

1. Save auto login of credit union **web** to your bitwarden account
1. Add equivalent domain from bitwarden web for credit union web and credit union mobile app
   Example for `capitalone` is `capitalone.com, androidapp://com.konylabs.capitalone`
1. Sync your mobile bitwarden app

Now when you will launch credit union app, bitwarden will offer auto fill from it from credit union web login.

**Comment by esmoyer** [comment]
I have done just that, and still nothing. Unless I have entered it wrong, but I have tried it as many ways as I could think of. I usually have to search for the login credential as it says "There are no items in your vault for [appname]." And when I manually search for the credential, it warns me about filling it into the app as it's not associated. Maybe it's just this banking app. I will check it with some others and see if I get the same result. Thanks though!
![capture](https://user-images.githubusercontent.com/17444085/36032073-67cacf3a-0d72-11e8-9b93-fd80ffa8aeb6.JPG)

**Comment by esmoyer** [comment]
Tried it with a couple other apps, yes it is indeed the credit union app that for some reason isn't wanting to associate. Thanks!

**Comment by auctionsjeff** [comment]
@ArmoredDragon, I think this is implemented. I seem to recall an option called something like "Yes, Add". 
@Nxt3 Is any part of this issue still outstanding? I skimmed the comments and it seems fixed based on my experiences in the app...
