### ISSUE TITLE
Android/Chrome: Autofills wrong fields on asia.nikkei.com

### ISSUE THREAD

**Issue by johns2s** [bitwarden/mobile#1154]
## Describe the Bug

When using Android 11's autofill service in Chrome, BW Autofills the email associated with an account on asia.nikkei.com in the email and password fields. The password is filled into the email field of the newsletter signup form below. 

This behavior doesn't appear in Firefox Nightly, however using Dashlane autofill in Chrome worked properly, which leads me to believe this is a Bitwarden issue.

This behavior is present in Chrome 86 and 89.

## Steps To Reproduce

Go to [this link](https://asia.nikkei.com/login?redirectTo=/) . Tap the autofill option that appears on the top of gboard.

## Expected Result

Newsletter signup field remains empty, login form accurately filled out

## Actual Result

Login fails because the email is autofilled in the password field and the password is in an email field.

## Environment

- Device: Pixel 3
- Operating system: Android 11
- Build Version: Version: 2.6.2 (3245)
- Is this a Beta release? Yes

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
