### ISSUE TITLE
Impossible to read QRCode from my Android Phone

### ISSUE THREAD

**Issue by JOduMonT** [bitwarden/mobile#1157]
Hi;

So it is probably a very specific issue, I'll try to give as much as details I could.

## flower

I use BitWarden on 3 devices (2x Android & iPad) and 2 browsers (Firefox & Brave) on 3 laptops (Linux and MacOS) I believe it is the smartest and the most completed solution to manage my password (better than LastPass and/or KeepassX), anyway this is not the point.

## context

Mainly everything works well except when I want to activate the 2nd Authentication by using a QRCode. (Some services, such as Buffer and Nethserver, don't offer the code solution and only give you the QRCode to scan).

### devices

My Android are:

- Samsung Note 4 (model SM-N910W8) with Android 6 and apps from F-Droid
- Google Nexus 7 with LineageOS 14 (Android 7 (Nougat))

The softwares are:

- **BitWarden** for Android: 2.7.0 (but also the version before)
- **QRCode**: 1.7

## issue (the bug)

Both Android can't read a QR-Code because BitWarden always close.

As QR-code reader I tried QR & Bar code Scanner and Binary Eye and I confirm QR & Bar Code Scanner works well as standalone application.

### Steps To Reproduce

Hopefully it could be reproduce by installing Bitwarden on an Android (maybe it is only related to Android 7) and try to scan a QR Code from Bitwarden.

## Expected Result

I would love to not have to run for the iPad every time I have to scan a QR-Code.

## Actual Result

_My temporary solution is the use the Familial iPad for this step._
I have to convince my daughter to let me use the iPad for few minute, log in Bitwarden, run to my computer, scan the QR-Code, logout bitwarden than give back the iPad

**Comment by Greenderella** [comment]
Could be related to both devices running older versions of Android, unfortunately I don't have access to an older device to test this. 

Will you first try uninstalling the app, powering off your device and re-installing? Does this issue still persist?

In the past other users have reported that doing a factory reset on older devices and installing Bitwarden first helped them to solved similar issues.

**Comment by JOduMonT** [comment]
> Could be related to both devices running older versions of Android, unfortunately I don't have access to an older device to test this.
> 
> Will you first try uninstalling the app, powering off your device and re-installing? Does this issue still persist?
> 
> In the past other users have reported that doing a factory reset on older devices and installing Bitwarden first helped them to solved similar issues.

I understand this issue is very specific to my ecosystem; and it is more an annoyance for me than anything else.

I'll try your trick and tell you later.

@Greenderella thanks for your message.

**Comment by clayadams5226** [comment]
Hi @JOduMonT , it looks like there is a viable workaround or resolution for the issue you're experiencing. Please let us know if this resolves the originally posted.
