### ISSUE TITLE
iOS 14.2 application crash after unlock

### ISSUE THREAD

**Issue by willquill** [bitwarden/mobile#1159]
## Describe the Bug

Bitwarden app on iOS 14.2 crashes after unlocking Bitwarden

## Steps To Reproduce
Two different ways to reproduce:

1. Be using an app that requires a password. Tap the password field, tap "Passwords" above the keyboard which, if the Bitwarden extension is enabled in iOS, will bring up Bitwarden. Unlock Bitwarden with FaceID. Bitwarden instantly crashes.

2. Open the Bitwarden app on its own (outside the context of opening within another app). Unlock Bitwarden with FaceID. Bitwarden instantly crashes.

## Expected Result

Bitwarden should not crash after unlocking it.

## Actual Result

Bitwarden instantly crashes after unlocking.

## Screenshots or Videos

I implemented a recommended solution but will do a screen recording if it happens again.

## Environment

- Device: iPhone 11
- Operating system: iOS 14.2
- Build Version (go to "Settings" → "About" in the app): 2.7.0 (358)
- Is this a Beta release? No
- Additional details: I use Duo for MFA, and I use a shared organization for some passwords. This issue first started happening when I attempted to view a password that I had previously created in my vault and shared with another user in my shared organization.

## Additional Context

Reported on Reddit in November 2020 on iOS 14.2: https://old.reddit.com/r/Bitwarden/comments/jyzfuk/im_going_to_have_to_quit_using_bitwarden_if_i/

Reported on Reddit in August on iOS 13.6 as well: https://www.reddit.com/r/Bitwarden/comments/i7c0in/bitwarden_app_crashing_on_ios/

I personally experienced the issue with FaceID, but the user in the 13.6 thread mentions that the issue occurred after typing the master password.

## Failed attempts to resolve

Complete delete the Bitwarden app from iOS. Reinstall the app. Issue comes back after a few days.

## Workaround

Yesterday, I implemented the workaround recommended [here](https://www.reddit.com/r/Bitwarden/comments/i7c0in/bitwarden_app_crashing_on_ios/g119o6p/):
> I had an issue similar to this recently where, after using 2FA to login once, it kept receiving some unhandled error/exception after that and would crash the iOS app whenever I logged in.

> I fixed it by:

> • Delete the app

> • Logged in from a browser and deauthorizing all sessions in the settings section

> • Reinstall app

> This forced a re-log on all devices but cleared the login crashing problem for me.

While I've implemented this workaround, I never saw an unhandled error/exception.

Since implementing yesterday, I haven't seen the issue come back. But last time I reinstalled without deauthorizing and it took a few days for the issue to reappear.

**Comment by ChrisLane** [comment]
I've also been experiencing this, it makes bitwarden completely unusable and urgently needs a fix.

**Comment by Nailik** [comment]
I think this could be related to the Android App Crashing and the Chrome Addon being unable to login.
see https://github.com/bitwarden/mobile/issues/1125

**Comment by janne-alatalo** [comment]
I have this problem too on IOS 14.2 with Bitwarden version 2.7.0 (358). Not sure when the problem started. Autofilling passwords on safari worked fine, but today I tried to open the application and it started crashing as soon as the face id authenticated me in. I also tried to log in with password, but that didn't work, it still crashed. After that I tried to log out and log back in but that didn't work either, it still crashed as soon as I logged back in. I just now deleted and reinstalled the application, and that worked. Too bad that it isn't permanent fix.

Hopefully this gets fixed as soon as possible! The application has worked flawlessly until now :)

**Comment by mportune-bw** [comment]
@willquill Thanks for the info. I have what I believe is the stack trace in question but reproducing it is proving to be difficult.  If you can answer a few more questions it would be really helpful:

- Are you using our cloud hosted service or your own server?  If it's your own, are you using our official docker containers or a 3rd party such as `bitwarden_rs`?  And are you on the latest version?
- Which Duo authentication method are you using for 2FA?  Have you tried others, and does it make a difference?
- What plan are you using for the shared organization? (free or paid, and if paid which tier?)

**Comment by willquill** [comment]
> @willquill Thanks for the info. I have what I believe is the stack trace in question but reproducing it is proving to be difficult. If you can answer a few more questions it would be really helpful:
> 
>     * Are you using our cloud hosted service or your own server?  If it's your own, are you using our official docker containers or a 3rd party such as `bitwarden_rs`?  And are you on the latest version?
> 
>     * Which Duo authentication method are you using for 2FA?  Have you tried others, and does it make a difference?
> 
>     * What plan are you using for the shared organization? (free or paid, and if paid which tier?)

1. Cloud hosted service. Latest version of iOS app and iOS.
2. I always use push for Duo, though I have the option when authenticating to use text or phone call. When this issue occurred, it always occurred 2+ days after I had already authenticated with Duo (via push, as usual) and had retrieved many passwords since authenticating.
3. Paid. Which tier? Well...there might be another bug here. In the Firefox extension, I go to Settings > Premium Membership > Managed membership. It launches `https://vault.bitwarden.com/#/?premium=manage` but the only text on the page is "Function host is not running" so I am unable to look up my membership tier. Image here: https://imgur.com/a/wdPZhes. And in the iOS app, I do not have the ability to check my tier.

**Comment by janne-alatalo** [comment]
> @willquill Thanks for the info. I have what I believe is the stack trace in question but reproducing it is proving to be difficult. If you can answer a few more questions it would be really helpful:
> 
>     * Are you using our cloud hosted service or your own server?  If it's your own, are you using our official docker containers or a 3rd party such as `bitwarden_rs`?  And are you on the latest version?
> 
>     * Which Duo authentication method are you using for 2FA?  Have you tried others, and does it make a difference?
> 
>     * What plan are you using for the shared organization? (free or paid, and if paid which tier?)

I can add more info too if that helps you to debug the problem.

1. I'm using your cloud hosted version too.
2. I'm using the Authenticator app for 2FA, but I have email verification code also enabled.
3. I'm not using any organization features. Its my personal account that I'm using. I have the $10/y premium membership.

Extra thoughts: Original issue creator said that the problem started for him when he tried to view a shared password that he had created before. I don't think this is the problem. I have never used any password sharing features in the app.

**Comment by mportune-bw** [comment]
Thank you both, very helpful.  (Apologies for the web vault trouble yesterday @willquill, we were having some Azure issues).

> After that I tried to log out and log back in but that didn't work either, it still crashed as soon as I logged back in.

@janne-alatalo Did this ^ crash occur when you submitted your password on login, after 2FA, or at some other point?

**Comment by janne-alatalo** [comment]
> 
> 
> Thank you both, very helpful. (Apologies for the web vault trouble yesterday @willquill, we were having some Azure issues).
> 
> > After that I tried to log out and log back in but that didn't work either, it still crashed as soon as I logged back in.
> 
> @janne-alatalo Did this ^ crash occur when you submitted your password on login, after 2FA, or at some other point?

Sorry, I'm not 100% sure, but if I remember correctly it asked the 2FA code, and crashed immediately after that. So basically at the point where I would normally be able to see my vault.

**Comment by clayadams5226** [comment]
@willquill can you open the app and go to Settings and let us know what you have your "Vault Timeout" set to?

**Comment by willquill** [comment]
15 minutes. It’s always been this way, I’ve never touched this setting.

**Comment by mportune-bw** [comment]
Is anybody here still experiencing this with the current release (2.7.2)?

**Comment by ChrisLane** [comment]
> Is anybody here still experiencing this with the current release (2.7.2)?
Still experiencing this on 2.7.2.

**Comment by lodi-g** [comment]
Experiencing the same issue on iOS, version 2.8.0.

**Comment by ChrisLane** [comment]
@mportune-bw is there some way I can give you some debug info or we could collaborate on this?
This is a critical bug and has stopped my family members from being able to easily get into their accounts for 3 months or so.

**Comment by ShuffledBits** [comment]
I believe I'm having this same problem on two different devices.

**Setup**
- Bitwarden iOS, 2.15.0 (1225)
- Vault Timeout - 1 minutes
- Vault Timeout Action - Lock
- Unlock with Face ID - Enabled
- Unlock with PIN Code - Disabled
- iPhone 11 Pro
- iOS 15.2

**To Reproduce**
- Start Bitwarden on the phone.  
- Unlock it
- Swipe up from the bottom of the screen to view the home screen
- Wait for at least one minute (I've waited for two just to be sure).
- Tap Bitwarden again to start the app.
- The app crashes before it tries to use Face ID.

If you tap the app again, it starts normally and uses Face ID to unlock.  Also, if you close the app (i.e. bring up the app switcher and swipe up to force exit Bitwarden), it opens correctly.

I get the same behavior on an iPad without Face ID, but with the option to unlock using your fingerprint.
