### ISSUE TITLE
[Feature Request] Faster Auto-Fill popup

### ISSUE THREAD

**Issue by jakauppila** [bitwarden/mobile#116]
Would it be possible to add additional auto-fill options that may allow faster password entering?

Trying the app out coming from Lastpass and find that the experience of having to click the notification and selecting the right entry is a bit slower than the popup that Lastpass offers.

![2017-08-05 23 55 51](https://user-images.githubusercontent.com/4100127/29000731-6f327186-7a3a-11e7-8d39-672644bf5a64.png)

**Comment by kspearrin** [comment]
We don't plan on this simply because we will soon be moving to Android O's Autofill APIs which will provide a native method that is better than any method we could come up with. See https://github.com/bitwarden/mobile/issues/57
