### ISSUE TITLE
When using autofill on Android, password is filled instead of username on Amazon, Google and probably some other websites

### ISSUE THREAD

**Issue by Leopold702** [bitwarden/mobile#1173]
## Describe the Bug
I noticed that on websites that separate entering username and password into two stages (Amazon and Google are two examples of such websites) Bitwarden fills login field (that is asked on the first stage) with password

## Steps To Reproduce

1. Go to [Amazon's](https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3F_encoding%3DUTF8%26ref_%3Dnavm_hdr_signin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=anywhere_v2_us&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&) or [Google's](https://accounts.google.com/signin/v2/identifier?hl=en) sign in page via Google Chrome
2. When asked for username/email trigger Bitwarden autofill
3. Make sure that account password was inserted into username/email field

## Expected Result
Username/email should be filled instead of password

## Actual Result
Password is filled instead of username/email

## Environment

- Device: Google Pixel 3a
- Operating system: Android 11
- Build Version: 2.7.0 (3257)
- Is this a Beta release? Y

**Comment by SergeantConfused** [comment]
Hi there,

Can you please check if you encounter this behaviour on Firefox?

Thank you in advance,

**Comment by Leopold702** [comment]
For some reason autofill doesn't work for me at all in stable Firefox and Firefox Beta. However it worked in Firefox Nightly and fields were filled correctly on both Amazon and Google websites, so apparently problem is related specifically to Chrome. I tried in all four versions: Stable, Beta, Dev and Canary.

**Comment by SergeantConfused** [comment]
Thank you.

What options under 'Auto-fill Services' do you have enabled?

**Comment by Leopold702** [comment]
Initially I had only "Auto-fill service" and "Use Inline Autofill" enabled. After your question I tried to also enable "Use accessibility" option, but it didn't help. Problem remains when all three are enabled.

**Comment by clayadams5226** [comment]
Autofilling usernames only will not be possible on Android. We don't have any way of detecting a username field if it is not accompanied by a password field.

**Comment by ehaynes99** [comment]
Can this be reopened? This affects most sites with SSO capabilities. Even if you can't detect/autofill a username field, it shouldn't just blindly insert the password in an `<input type="email"` field. These get stored in autofill, are frequently passed through third-party validators, and often have event that fire requests to e.g. check for an SSO integration on focus lost.

However, other password managers handle this correctly. E.g. Keepass has this fallback:
https://github.com/PhilippC/keepass2android/blob/fcd3cddbc7c7b9d5ea2ca34940d051e3262b6c90/src/keepass2android/services/AutofillBase/StructureParser.cs#L130

```c#
if (usernameFields.Any() == false)
{
    //for some pages with two-step login, we don't see a password field and don't display the autofill for non-manual requests. But if the user forces autofill, 
    //let's assume it is a username field:
    if (isManualRequest && !passwordFields.Any() && _editTextsWithoutHint.Count == 1)
    {
        usernameFields.Add(_editTextsWithoutHint.First());
    }
}
```

**Comment by Camusensei** [comment]
I'd like to vote for re-opening this bug. At least bitwarden shouldn't fill a VISIBLE field with the password in this case. I always am horrified every time I see (any of) my password displayed anywhere (even if they are most of the time randomly generated)
