### ISSUE TITLE
Two unique auto-fill overlays appearing

### ISSUE THREAD

**Issue by vachan-maker** [bitwarden/mobile#1179]
## Describe the Bug

Two types of auto-fill overlays appearing when trying to auto-fill.

## Screenshots

![Screenshot_2020-12-15-17-39-32-04](https://user-images.githubusercontent.com/65799568/102213477-cbfd7c00-3efc-11eb-8fba-19835c4d798e.jpg)
![Screenshot_2020-12-15-17-39-25-45](https://user-images.githubusercontent.com/65799568/102213486-ce5fd600-3efc-11eb-8d3d-3c3369e20c22.jpg)

## Device information

Oppo A5
Color OS 
Android 10
Bitwarden Beta 2.7.0 3258

**Comment by SergeantConfused** [comment]
Hi there,

Yes, that's how it supposed to behave. This assists in knowing whether the overlay is coming from the Auto-fill service (White and Blue) or the Accessibly service (White and Black).

I hope this helps, please let me know if you have any questions.


All the best,

**Comment by vachan-maker** [comment]
> 
> 
> Hi there,
> 
> Yes, that's how it supposed to behave. This assists in knowing whether the overlay is coming from the Auto-fill service (White and Blue) or the Accessibly service (White and Black).
> 
> I hope this helps, please let me know if you have any questions.
> 
> All the best,

Thanks for the reply.
I didn't know that. I thought it was a bug.

**Comment by SergeantConfused** [comment]
No worries. You're most welcome!
