### ISSUE TITLE
[Feature request] Website information: copy to clipboard

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/mobile#118]
Hi,

When we press the field of Notes, the content is copied to the clipboard.
Could you do the same thing for the website field?

Thank you.

![screenshot_20170810-084632](https://user-images.githubusercontent.com/5938828/29158027-9c823f64-7da9-11e7-9ffc-f58cd98bcfb6.png)

**Comment by kspearrin** [comment]
Available in next version.
