### ISSUE TITLE
Autofill service using 15% cpu constantly

### ISSUE THREAD

**Issue by ReekyMarko** [bitwarden/mobile#119]
In the midst off searching what was draining my OP3T battery so quickly, I discovered that the bitwarden autofill was using 15% cpu all the time, even when the screen was off. I observed this over adb using top. I have disabled the service for now, for the sake of my poor battery, but if the devs could optimize the service a bit some time in the near future, that would be great.

My phone specs if that is needed tracking down this issue:
OnePlus 3T
LineageOS 15.1-20170810-NIGHTLY-oneplus3
Kernel 3.18.31-lineageos-g069a9ee
Rooted and using MicroG instead of GAPPS

**Comment by kspearrin** [comment]
@ReekyMarko We have battery saving options available under Settings > Features > Autofill.

Unfortunately the accessibility services burn a lot of battery, but these options can help.

**Comment by ReekyMarko** [comment]
Thanks for the tip!
