### ISSUE TITLE
iOS - Password generator freezes the app

### ISSUE THREAD

**Issue by Twiglet1022** [bitwarden/mobile#1190]
## Describe the Bug

Password generator in iOS app freezes app.

## Steps To Reproduce

1. Open the Bitwarden app
2. Authenticate to access vault
3. Tap on “Generator” at the bottom of the screen
4. App is now frozen and unresponsive

## Expected Result

Password generator works without freezing the app.

## Actual Result

App is frozen and completely unresponsive.

## Screenshots or Videos

This is what I see when I switch to the generator tab. This screen is completely unresponsive and I have to force-quit the app to use it again.

![73F6BF18-6C6E-4512-87E8-025A7477AB58](https://user-images.githubusercontent.com/29353990/103038872-701f9c80-4567-11eb-9491-4a20a98394b4.png)

## Environment

- Device: iPhone 12 mini and iPhone SE (2016)
- Operating system: iOS 14.3 and multiple earlier versions
- Build Version (go to "Settings" → "About" in the app): 2.7.2 (401)
- Is this a Beta release? N

## Additional Context

- I’ve had this problem for a few months.
- The password generator in the extension still works fine. It’s only the app version that freezes.
- I think it started happening after I tried to generate a pass phrase for the first time. The screenshot shows the last settings I used which it’s now perpetually stuck on.

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
