### ISSUE TITLE
Bitwarden iOS app won’t authenticate with YubiKey NFC 5

### ISSUE THREAD

**Issue by kland23** [bitwarden/mobile#1192]
When trying to log into the Bitwarden iOS app it prompts for the YubiKey 5 NFC but will not recognize the key.

![image](https://user-images.githubusercontent.com/64702629/103107401-8a0ebd00-4603-11eb-998f-ef8c9e64e87b.jpeg)

**Actions Taken**

- Deleted and reinstalled app

- Hard reset iPhone

- Tested the YubiKey with Yubico Authenticator app on the same device and the key was successfully recognized

**Comment by Greenderella** [comment]
Hi @kland23 

As per my current testing YubiKey 5 NFC is working as expected on iOS 14.3 with an iPhone SE 2020 and Bitwarden 2.7.2 (https://drive.google.com/file/d/1G6km8zcYdAHG09PhmlG_g1I_XKQHftyu/view?usp=sharing), you just need to hold it in the correct spot at the back of the device, near the camera.

Please make sure that your device supports NFC, and that you have your key is correctly configured as **Yubico OTP** and not FIDO U2F.

Remember that if you are self-hosting then you will need to configure the YubiKey API credentials in your environment variables. Please refer to this article for more detailed instruction: https://bitwarden.com/help/article/environment-variables/.

Try downloading the **YubiKey Manager** (https://www.yubico.com/products/services-software/download/yubikey-manager/) and make sure every box is checked like this:

![image](https://user-images.githubusercontent.com/5418577/103139737-9b2cfc00-46df-11eb-876b-a60f6f7e0e04.png)

Also, the **YubiKey personalization tool** (https://www.yubico.com/products/services-software/download/yubikey-personalization-tools), will let you configure with slot to use over NFC. Most likely, the slot that contains the credential needed for your Bitwarden account is in slot 1, so please try following through the steps on https://support.yubico.com/hc/en-us/articles/360016614700 to configure it. 

If it's blank like in this page, just press the **Program** button:

![image](https://user-images.githubusercontent.com/5418577/103139820-8ef56e80-46e0-11eb-938a-3719f92d0b3f.png)

**Comment by myhau** [comment]
I had a similar issue for YubiKey 5C NFC. Yubico OTP was disabled by default. This solved the problem for me:

> Please make sure that your device supports NFC, and that you have your key is correctly configured as Yubico OTP and not FIDO U2F.

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
