### ISSUE TITLE
Large fonts in Android

### ISSUE THREAD

**Issue by molaeiali** [bitwarden/mobile#1199]
I'm not sure when, but since a recent update, everything's font is huge on Bitwarden Android App, I cannot screenshot because of privacy policies but it's big font size!

Is it intended to be or a bug? Is there any settings to change it?

**Comment by Greenderella** [comment]
Currently there is no way to change the font size of the Bitwarden app exclusively, it is linked to the general font size of your Android device, you may want to check it following this guide: https://support.google.com/accessibility/android/answer/6006972?hl=en#:~:text=Change%20font%20size&text=Open%20your%20device's%20Settings%20app,to%20choose%20your%20font%20size

If that doesn't seem to work, try uninstalling the app, powering off your device and re-installing.

**Comment by molaeiali** [comment]
Thanks, I did a "Clear data" and re logged-in, It's OK now (aka Reinstalled) I don't know what resulted on fonts being large, and is it related to a problem in code or not, I didn't have large fonts on any other app
