### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by gaoyaoxin** [bitwarden/mobile#12]
The 1.0.0 version requires iOS 9.0 or later and is only compatible with iPhone 5s or later.
Is it possible for older devices and former systems to run this phenomenal app?

**Comment by gaoyaoxin** [comment]
![1](https://cloud.githubusercontent.com/assets/20694974/19834609/0d6906b0-9ea1-11e6-8a44-c0c080de742e.jpg)

**Comment by kspearrin** [comment]
This requirement exists because we use xamarin. In order to support < iPhone 5s we have to build for ARMv7 architecture inside the app. Doing this with xamarin causes the size of the app to go from 50mb to 100mb. Because of this we only support ARM64 architectures, which is iPhone 5s and up.

**Comment by gaoyaoxin** [comment]
I noted that there are some screenshots on iPhone4 devices.
e.g.
https://github.com/bitwarden/mobile/blob/master/store/apple/en-US/screenshots/3.5-inch%20(iPhone%204)%20-%20Screenshot%202.png

It could be more than welcome to create another app compatible with older devices.

**Comment by kspearrin** [comment]
@gaoyaoxin All that is required is to change the build options on this existing app to build for lower compatibility. It will work just fine. I just do not want to double the size of the app that is distributed on the app store for very few users on much older devices.
