### ISSUE TITLE
Use Material Design in Android app

### ISSUE THREAD

**Issue by carlylemiii** [bitwarden/mobile#120]
The app currently uses a navigation bar along the top. This doesn't jibe with Material Design guidelines, which DO now support navigation buttons, but they should be along the bottom.

https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-usage

Making this design change would be more visually appearing, be more usable for the end user with a larger screen (really, the point of these navigation buttons anyway), and it would be more in line with the iOS counterpart. All in all, this would be a great change to make.

"Settings" might belong in an overflow button, or in a sidebar (hamburger button menu), not sure. You'd have to make the right call there.

**Comment by Nxt3** [comment]
It's because the Dev is using Xamarin. It sucks :(

**Comment by mathearts** [comment]
But Xamarin allows for material design-like theme: https://developer.xamarin.com/guides/android/user_interface/android-designer/part_4_-_material_design_features/

**Comment by kspearrin** [comment]
@carlylemiii I'm not an Android user, but I thought the navigation at the top was the Android standard? Is the bottom nav something new?

**Comment by carlylemiii** [comment]
Re-looking through the specs, I guess it's fine as is actually, but I've not seen it implemented with icons on top besides in Bitwarden.

https://imgur.com/a/YQu2I

The bottom is a newer addition to the guidelines because as devices are getting larger, the bottom of a screen is more easily reached than the top.

**Comment by kspearrin** [comment]
I like it at the bottom better too. We could whip up a custom control implementing the bottom navigation but I would rather wait for Xamarin.Forms to create some official implementation for [TabbedPage](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/navigation/tabbed-page/) (what we're using now).

**Comment by teddyfrozevelt** [comment]
One thing is that the header should just say bitwarden and not the name of the tab you're on.

**Comment by Nxt3** [comment]
and the title of the toolbar shouldn't "move" with swiping between tabs. 

I think the smartest thing would be to follow Material Design for the toolbar in that the title is static ("Bitwarden"), and there is a bottom navigation bar with the tabs; disable swiping between tabs if you use a bottom bar.

**Comment by teddyfrozevelt** [comment]
Also think about using a Floating Action Button to add an entry from anywhere.

**Comment by teddyfrozevelt** [comment]
Also think about using a Floating Action Button to add an entry from anywhere.

**Comment by kspearrin** [comment]
Next version uses a new bottom navigation view. Check it out on play store beta.
