### ISSUE TITLE
Very old version in Google Play store

### ISSUE THREAD

**Issue by TheDuffman85** [bitwarden/mobile#1203]
## Describe the Bug

Current version in German Google Play store is still version 2.6.1 released on 2020-09-23.

## Steps To Reproduce

1. Go to Google Play
2. Search for Bitwarden
3. See version in App details

## Expected Result

Version 2.7.2 or at least 2.7.0

## Actual Result

Version 2.6.1

## Screenshots or Videos

![Screenshot_20210101-160902](https://user-images.githubusercontent.com/9296618/103441200-92db4080-4c4c-11eb-927d-997bdab042f5.jpg)

## Environment

- Device: OnePlus 7 Pro
- Operating system: Android 10
- Is this a Beta release?: N
- Country: Germany
- Language: German

**Comment by clayadams5226** [comment]
This is the expected version in the Play Store. We have started a gradual rollout of 2.7.2. It sounds like the rollout just hasn't made it to you yet.

**Comment by TheDuffman85** [comment]
Version 2.7.0 was releast 47 days a ago. I think it's unlikely that it didn't hit me yet. Could it be that the staged rollout is limited to specific countries? Because the play store documentation states, if the stages roll out is limited to specific countries, the update will only hit the selected countries.

"If you choose specific countries for your staged roll-out, the upgrade will be limited to users with Google Play accounts in those locations."

**Comment by Maximilian85** [comment]
I am also affected and the available version in the Play Store is 2.6.1 from 9/23/20. It seems to be not only a bug in the rollout.

Germany / Xiaomi / Android 10
