### ISSUE TITLE
Android Bug - Can't Launch URL

### ISSUE THREAD

**Issue by Aldous-Huxley** [bitwarden/mobile#1205]
1. In the Bitwarden Android app, go to any saved login account information.
2. Scroll down to the URIs (URL).
3. Press the icon with the box with a right arrow protruding out of it. This is suppose to launch the URI like it always has. It does not anymore.

Using Bitwwarden 2.7.0 (3528)
Android 11 (With no GAPPS), No Google services.

**Comment by SergeantConfused** [comment]
Hi there,

Please note this has already been reported here: https://github.com/bitwarden/mobile/issues/1164
Please let me know if you have any further questions.

All the best,

**Comment by clayadams5226** [comment]
Closed as a duplicate https://github.com/bitwarden/mobile/issues/1164
