### ISSUE TITLE
Build Error!

### ISSUE THREAD

**Issue by ganjiayi** [bitwarden/mobile#1208]
attribute android:supportsInline-Suggestions not found.	
D:\mobile-2.7.2\src\Android\Resources\xml\autofillservice.xml	

![image](https://user-images.githubusercontent.com/11990508/103521380-9e7c7080-4eb3-11eb-8f69-bb3514d68bfc.png)

**Comment by mportune-bw** [comment]
@ganjiayi Make sure your nuget packages are all updated, specifically `Xamarin.AndroidX.Autofill` should be on `1.1.0.3-beta01`
