### ISSUE TITLE
Android - not locking after vault timeout expires

### ISSUE THREAD

**Issue by tehniemer** [bitwarden/mobile#1209]
I'm running version 2.7.2 on a OnePlus 6 with Android 10 and it is no longer locking after the duration set in the vault timeout field.

**Comment by ricardf** [comment]
Same behaviour on oneplus 8 pro (Oxygen 11)

**Comment by SergeantConfused** [comment]
Hi there,

Please note this has already been reported here: https://github.com/bitwarden/mobile/issues/1196
I hope this helps.

All the best,

**Comment by tehniemer** [comment]
That did help, I excluded the app from battery optimization and it's locking as expected now. Shouldn't have to do that, but it works for now.

**Comment by clayadams5226** [comment]
Duplicate https://github.com/bitwarden/mobile/issues/1196
