### ISSUE TITLE
[Feature Request] Android app - Folder Views

### ISSUE THREAD

**Issue by evazquez00** [bitwarden/mobile#121]
Enhancement Request.

Would like to be able to collapse folders to reduce on-screen clutter and enhance "quick find and select".

Desired minimum of per-folder collapse with tracking of last state as in the Vault WebUI, though a global setting to "Start in collapsed View" would be great as well.

**Comment by anortiz08** [comment]
I second this feature request!

**Comment by kspearrin** [comment]
Available in next version or current android beta.
