### ISSUE TITLE
[Android] - App Crashes After Attempting Unlock With Password

### ISSUE THREAD

**Issue by nezartarbin** [bitwarden/mobile#1212]
## Describe the Bug 

Hi! I am having an issue where, when I open my app, I attempt to login / unlock by entering my password. As soon as I hit "unlock" (after I fill in my password) the screen immediately goes back to home screen, indicating that the app crashed. Subsequent attempts have the same result.

## Steps To Reproduce 

1. Launch the app 
2. Fill in password 
3. Hit "unlock" button

## Expected Result 
The vault is unlocked and launched correctly.

## Actual Result

 the app seems to crash, because screen goes back to home immediately.

## Environment

- Device: OnePlus 8T
- Operating system: Android 11
- Build Version: 11.0.5.7.KB09CB
- Is this a Beta release? No

## Additional Context 
I am self-hosting Bitwarden. It works without issues on the web app, and it used to work on the mobile app too.

Whenever I attempt to delete the app and reinstall, the first login is successful and I can unlock the vault without issue. It is only after the first login that the issue starts to happen. But every time I uninstall and reinstall, it works for one login.

Upon further investigation, I found out that, instead of filling in the password, if I log out (by choosing the option from the top right menu) then log back in (with both email and password), it works without issue. But if I don't explicitly log out to log back in, and simply unlock the vault, it crashes.

I tried both the F-droid and the Google Play store versions.

Help me please, and thank you for this amazing software :)

**Comment by mportune-bw** [comment]
What version of the app are you using, and are you using the latest docker images?

**Comment by zucki** [comment]
I have the same problem.
I'm using:
Samsung Galaxy S8 with Android 9
Bitwarden Mobile App version 2.7.0 from F-Droid and Bitwarden repo
latest bitwardenrs docker with Bitwarden Version 2.16.1

**Comment by nezartarbin** [comment]
I no longer have this issue, so I am closing.
