### ISSUE TITLE
Unable to PASTE into password field on Android App

### ISSUE THREAD

**Issue by yurividal** [bitwarden/mobile#1215]
## Describe the Bug
On android app, when manually adding an entry, the password field does not allow for press-hold -> paste

## Steps To Reproduce

Click the + icon, type a name, type a username, try to paste an item from clipboard into password.
Also, keyboard button for clipboard disappears .

## Expected Result

User should be able to paste a password, in case it has come from somewhere else.

## Actual Result

No popup for paste, or keyboard paste button shown.

## Environment

- Device: Samsung Galaxy s20
- Operating system: Android 11 OneUI 3.0
- Build Version (go to "Settings" → "About" in the app): 2.7.2 (3300)
- Is this a Beta release? Y

**Comment by francoispeyret** [comment]
Same issue here : Android 14.
