### ISSUE TITLE
Unable to PASTE into password field on Android App

### ISSUE THREAD

**Issue by yurividal** [bitwarden/mobile#1215]
## Describe the Bug
On android app, when manually adding an entry, the password field does not allow for press-hold -> paste

## Steps To Reproduce

Click the + icon, type a name, type a username, try to paste an item from clipboard into password.
Also, keyboard button for clipboard disappears .

## Expected Result

User should be able to paste a password, in case it has come from somewhere else.

## Actual Result

No popup for paste, or keyboard paste button shown.

## Environment

- Device: Samsung Galaxy s20
- Operating system: Android 11 OneUI 3.0
- Build Version (go to "Settings" → "About" in the app): 2.7.2 (3300)
- Is this a Beta release? Y

**Comment by laxlyllama2** [comment]
On Note20 Ultra here just updated to Android 11 and unable to paste into Name / Username / Password / Authenticator Key fields. I am able to paste into the notes though.

**Comment by sodimm** [comment]
You can paste a password, you just need to disable the obfuscation first.
Click on show password and you will be able to paste.

**Comment by rhtenhove** [comment]
Disabling obfuscation indeed works for the password field here. The problem still persists in all other fields except notes. So name, username, TOTP, URL. Fields that I don't wish to have to enter manually.

Oneplus 8 Pro
Android 11
Version: 2.9.1 (3444)

**Comment by mjmeli** [comment]
Same issue on S21 Ultra on Android 11. A workaround is that you can type into the field and then delete the text. You should now be able to bring up the copy/paste/etc. menu.

**Comment by unwishedjack** [comment]
Android 11, Galaxy A71 I was also having this issue, Bitwarden support sent me here. I can confirm either clicking the show password icon (eye) on and off or writing something then deleting allows you to paste. :)

**Comment by iamtodor** [comment]
Was such logic implemented on purpose or is it accidental? I mean is it a feature or bug?

**Comment by iamtodor** [comment]
Was such logic implemented on purpose or is it accidental? I mean is it a feature or bug?
Bitwarden Version 2.11.3 (3653)

**Comment by SampsonCrowley** [comment]
Feature or not, it is a *bug*. Keeping users from pasting new entries is a dangerous way to cause data loss

**Comment by SampsonCrowley** [comment]
This should be High priority on the Android App, as it is a HUGE accessibility issue

**Comment by SampsonCrowley** [comment]
Removing obfuscation does not work for me. Pixel 5, Android 11 or 12
