### ISSUE TITLE
Android - Unable to see whole password

### ISSUE THREAD

**Issue by evazquez00** [bitwarden/mobile#122]
My eyes are, unfortunately, not as young as they used to be.

As a side-effect I have set my Android phone to use "Large" text in the "Accessibility" settings area so that I can see /read on the device.

The BitWarden app apparently doesn't know how to handle this, so after the fourteenth (14th) character, it ellipses (...) the remnant.

This is problematic since a good bit of my use is console logins to various client (i.e. I log in via Windows RDP or directly at a keyboard /mouse in a data center) systems, all of which have different login and credential requirements.

While I can copy, then paste into a text editor, remembering to change the font to a "monospace" so I can tell the difference between "l", "I", "|" and "1", and then key in the password, this seems a bit complex for what should be a simple operation.

There seems to be plenty of screen real estate, is it possible to "wrap" and "scrollbar" the revealed password so that the entire string is visible when unmasked?

**Comment by kspearrin** [comment]
I have adjusted this for next release. It will wrap at full font size.
