### ISSUE TITLE
Android - Bitwarden does not recognize the Username field on Oaken Financial's login page.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#1222]
## Describe the Bug
Bitwarden on Android does not recognize the username field here:
https://online.oaken.com/cb/pages/jsp-ns/login-cons.jsp
Using custom fields and/or different browsers did not help.

## Steps To Reproduce
1. Open the following link: https://online.oaken.com/cb/pages/jsp-ns/login-cons.jsp
2. Tap on the Username field.

## Expected Result
To have Bitwarden offer to autofill.

## Actual Result
Bitwarden does not show up or recognize this field.

## Screenshots or Videos
N/A.

## Environment

- Device: Samsung Note 10+.
- Operating system: Android 11.
- Build Version: 2.7.2 (3300).
- Is this a Beta release? N.

## Additional Context
This was tested on Brave, Firefox, and Chrome.
Under Auto-fill Services; Auto-fill service, Use Inline Autofill, Use Accessibility, Use Draw-Over were all activated.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
