### ISSUE TITLE
Firefox doesn't fill fields after picking them in the app

### ISSUE THREAD

**Issue by theRealPadster** [bitwarden/mobile#1223]
## Describe the Bug
In Firefox Nightly (currently version 210116, but it's been this way for a while), when I select the bitwarden dropdown item of a form field, it takes me to the bitwarden app and I can pick the login to use. Then it goes back to Firefox, but 90% of the time it doesn't fill the form field in and I have to copy/paste them from the app myself. It sometimes works when I navigate to a different page or reload the page, after picking my login. 

## Steps To Reproduce
Use bitwarden autofill API and Firefox Nightly. 
Go to a site that you have a saved login for. 
Tap the form field. 
Select bitwarden. 
Pick your login. 
It goes back to Firefox, with nothing filled in. 

## Expected Result
When you pick the login from the bitwarden app, it fills the fields in on the page in Firefox. 

## Actual Result
When you pick the login from the bitwarden app, it goes back to Firefox with the fields still empty. 

## Screenshots or Videos
What it looks like before picking anything. (And after selecting your login)
![Screenshot_20210117-140303](https://user-images.githubusercontent.com/1565883/104853182-307d7380-58cd-11eb-8bff-3742ce16a627.png)
What it looks like after picking my login and going back a page, then navigating to the site's login page again. 
![Screenshot_20210117-140449](https://user-images.githubusercontent.com/1565883/104853191-36735480-58cd-11eb-86ad-2e096435a9bf.png)

## Environment

- Device: Pixel 2
- Operating system: Android 11
- Build Version: Version: 2.6.1 (3178)
- Is this a Beta release? No

## Additional Context

Most of the time it doesn't work. Sometimes the bitwarden dropdown item doesn't even show up. I can sometimes get it to work if I reload or go to another page and go back.

**Comment by nri82** [comment]
i am having the same problem.

**Comment by smithed** [comment]
same problem, with the difference that I'm using the new inline fill. It notices prompt, I go to bitwarden to log in, return to firefox, click to fill...and nothing. Always works after reloading the page, and still fails even if I'm already logged into my vault.

**Comment by Derkades** [comment]
This also happens with Keepass2Android and doesn't happen with any other app (at least for me) so probably a firefox issue

**Comment by 9ary** [comment]
This is a Firefox regression, not a BW issue. I've bisected Firefox and found the commit that broke it. See https://github.com/mozilla-mobile/fenix/issues/16583.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by 9ary** [comment]
I'm just leaving this here in case anyone finds this issue in the future, because it was evidently closed without reading the thread at all (but there's also no reason to keep it open):
This is **not** an issue with the Bitwarden app. It's a bug in Firefox that's being tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1693152. It affects all autofill providers on Android, and there's nothing Bitwarden can or should do about it.
