### ISSUE TITLE
iOS - Bitwarden is not showing a favicon for https://www.komposanusa.com/.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#1226]
## Describe the Bug
Bitwarden's iOS client is not showing the favicon of https://www.komposanusa.com/.

## Steps To Reproduce
1. Open Bitwarden.
2. Add a Login item and name it Test, add 'https://www.komposanusa.com/' as a URI, and save.

## Expected Result
To see the favicon.

## Actual Result
You see a globe.

## Screenshots or Videos
N/A.

## Environment

- Device: iPhone SE 2020.
- Operating system: iOS 14.3.
- Build Version: 2.7.2 (401).
- Is this a Beta release? N.

## Additional Context
The Windows Desktop client and the web vault show the favicon of this website.

**Comment by kendratodd** [comment]
@SergeantConfused, I am now seeing this favicon on iOS. Would you be able to confirm?

**Comment by SergeantConfused** [comment]
Yes, I now see the favicon. Thank you!

**Comment by kendratodd** [comment]
Thank you @SergeantConfused! I'll go ahead and close this as it appears to have been resolved 👍
