### ISSUE TITLE
2.8.0 missing from F-Droid repository

### ISSUE THREAD

**Issue by nvllsvm** [bitwarden/mobile#1232]
Version 2.8.0 is missing from the [F-Droid repository](https://mobileapp.bitwarden.com/fdroid/).

**Comment by Disqu3-mirOir-qt** [comment]
i agree , 2.7.2 - 2.8.0 only .ipa (ios)

**Comment by cscharf** [comment]
Thanks all, our mobile rollouts do take some time both for submission and approval, from the time we roll the release and tag in GitHub, please be patient and we'll get it out soon.

**Comment by Disqu3-mirOir-qt** [comment]
i use bitwarden repository for get more fast , but same resultat , why not push apk on github ? thanks

**Comment by Fei1Yang** [comment]
It seems the F-Droid repository is currently broken, there is only an [APK](https://github.com/bitwarden/mobile/tree/gh-pages/fdroid/repo) in it and all other necessary metadata are missing.

**Comment by JokerQyou** [comment]
Bitwarden's F-droid repo seems to have problem building. No F-droid repo metadata was generated, and [the APK file](https://github.com/bitwarden/mobile/blob/gh-pages/fdroid/repo/com.x8bit.bitwarden-fdroid.apk) was also not an actual APK, but rather a text file containing only this line: `Not Found`. I think something happens to your CI script, better have a look.

**Comment by mportune-bw** [comment]
Issue has been fixed, version 2.8.2 is now available in F-Droid repo
