### ISSUE TITLE
Android - Autofill prompt flashes on screen and cannot be tapped or used.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#1237]
## Describe the Bug
The autofill banner flashes and does not remain in place for you to tap on it and use it.

## Steps To Reproduce
1. Install Call Recorder from Boldbeast Software Inc.
2. Open Call Recorder, go to Settings, App Settings, and tap on Password and set a password.
3. Exit the application.
4. Launch Call Recorder and tap on the password field.

## Expected Result
To autofill using Bitwarden.

## Actual Result
The autofill prompt flashes and you cannot tap it.

## Screenshots or Videos
N/A.

## Environment

- Device: Samsung Note 4.
- Operating system: Android 6.0.1.
- Build Version: 2.6.1 (3178).
- Is this a Beta release? N.

## Additional Context
This has been reported to occur on an Android 7 device, too.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
