### ISSUE TITLE
Android - Bitwarden does not recognize the username field on CFTS' site through Firefox.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#1238]
## Describe the Bug
On Firefox, Bitwarden does not show the accessibility or autofill service overlay when you tap the username field, but does show the accessibility overlay when you tap the password field. When you autofill from the password field using the accessibility overlay, Bitwarden only autofills the password and leaves the username field blank.
Also on Firefox, inline autofill detects both the username and password fields, and autofills both when used from either field, but inline autofill is inconsistent in Firefox.
On Chrome, both inline and accessibility service detect both fields consistently, and Bitwarden autofills both fields.

## Steps To Reproduce
1. Open https://www.ctfs.com/content/dash/en/public/login.html in Firefox.
2. Tap on the username field.

## Expected Result
For the accessibility or autofill overlay to show up and to use it to autofill your credentials.

## Actual Result
No overlay shows up, and you cannot autofill from the username field.

## Screenshots or Videos
![1](https://user-images.githubusercontent.com/73389600/105611718-98492800-5dbf-11eb-8b7c-ffb403e89144.png)
![2](https://user-images.githubusercontent.com/73389600/105611719-997a5500-5dbf-11eb-8599-d61d288c99ad.png)

## Environment

- Device: Samsung Note 10+.
- Operating system: Android 11.
- Build Version: 2.8.0 (3349).
- Is this a Beta release? N.

## Additional Context
Inline autofill is not always presented as an option in Firefox, but always is in Chrome.
This has been reported to occur on an Android 7 device, as well. The screenshots are from this device.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
