### ISSUE TITLE
Playstore version stuck for some users

### ISSUE THREAD

**Issue by iamperson347** [bitwarden/mobile#1241]
## Describe the Bug

Some users appear to be stuck on version 2.6.1 when installed from the Google playstore. A little bit of discussion took place on reddit regarding the potential issue. 

https://www.reddit.com/r/Bitwarden/comments/l45ul7/playstore_version_out_of_date/?utm_medium=android_app&utm_source=share

## Steps To Reproduce

Unknown - does not appear to be affecting all users.

## Expected Result

App is updated to latest version within reasonable amount of time after new release.

**Comment by mportune-bw** [comment]
We roll new versions out gradually.  That said there was an issue discovered with version 2.7.2 so that release was halted, leaving most users on 2.6.1.  The new version (2.8.2) is being rolled out now.
