### ISSUE TITLE
Android - Bitwarden does not recognize the credential fields via Firefox and Chrome for 2 websites.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#1243]
## Describe the Bug
Tapping on the email address field in both websites does not prompt Bitwarden to offer to autofill them. This was tested through Firefox and Chrome.

## Steps To Reproduce
1. Open https://www.anibis.ch/fr/login.aspx or https://www.playstation.com/fr-ch/
2. Tap on the email address field.

## Expected Result
For Bitwarden to prompt to autofill.

## Actual Result
Bitwarden does not show a banner or prompt to autofill.

## Screenshots or Videos
N/A.

## Environment
- Device: Samsung Note 10+.
- Operating system: Android 11.
- Build Version: 2.8.0 (3349).
- Is this a Beta release? N.

## Additional Context
N/A.

**Comment by lablans** [comment]
I can confirm this issue on Google Pixel 5.

**Comment by Ennneerrrgggyyy** [comment]
Same problem with Pixel 2XL

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
