### ISSUE TITLE
iOS - Bitwarden does not recognize the credential fields via Firefox and Chrome, but does through Safari.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#1244]
## Describe the Bug
Tapping on the email address field in both websites does not prompt Bitwarden to offer to autofill them when browsing through Firefox and Chrome, but via Safari it does offer to autofill them.

## Steps To Reproduce
1. Open https://www.anibis.ch/fr/login.aspx or https://www.playstation.com/fr-ch/
2. Tap on the email address field.

## Expected Result
For Bitwarden to prompt to autofill.

## Actual Result
In Firefox and Chrome, Bitwarden does not show a banner or prompt to autofill.

## Screenshots or Videos
Chrome:

![Chrome](https://user-images.githubusercontent.com/73389600/105839254-e3d71e00-5fd9-11eb-8888-960ffdb610fc.PNG)

Firefox:

![Firefox](https://user-images.githubusercontent.com/73389600/105839258-e5084b00-5fd9-11eb-9940-04d380cf4e63.PNG)

Safari:

![Safari](https://user-images.githubusercontent.com/73389600/105839264-e6397800-5fd9-11eb-8714-4edbda1e0a13.PNG)

## Environment
- Device: iPhone SE 2020.
- Operating system: iOS 14.3.
- Build Version: 2.8.0 (449).
- Is this a Beta release? N.

## Additional Context
N/A.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
