### ISSUE TITLE
Autofill doesn't recognize the website i am in, but the auto-fill tile does

### ISSUE THREAD

**Issue by yurividal** [bitwarden/mobile#1245]
Android 11.
Samsung Browser.
When I try to input a password with bitwarden, most of the times it does not recognize what website I am in. And only shows: 
items for --

But, on those same websites, if I select the autofill tile from the drop-down menu, it is able to detect the website correclty.

Are those 2 using 2 different methods to find out the website?

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
