### ISSUE TITLE
IOS Bug - Bitwarden app doesn’t show up when searching for it in IOS search bar

### ISSUE THREAD

**Issue by urvish0215** [bitwarden/mobile#1248]
## Describe the Bug
Bitwarden doesn’t show up when searching for “Bitwarden” or any substring of it.

## Steps To Reproduce

1. Go to homescreen.
2. Slide down to open up the search bar.
3. Type in “Bitwarden” or any substring of it

It doesn’t return Bitwarden app.

## Expected Result

when typing “Bitwarden”. It should return Bitwarden app in search results.

## Actual Result

Bitwarden app doesn’t show up in search results.

## Environment

- Device: IPhone 6S
- Operating system: iOS 14.2
- Is this a Beta release? N

## Additional Context

I have reinstalled app and restarted phone. It did not fix issue

**Comment by Greenderella** [comment]
Hi @urvish0215, I'm unable to reproduce this issue. Could you please try to update your phone to iOS 14.4 and then uninstall the app, power off your device and re-install? Does this issue still persist?

**Comment by urvish0215** [comment]
Hi.

I tried this on a iPhone 6 Plus with iOS 12.4.9 and it also did not reproduce.

It might just be an issue with iOS 14.4

I do not intend to update so please consider this issue closed.

Thanks.
