### ISSUE TITLE
Autofill popup hides Bitwarden on sixt entry

### ISSUE THREAD

**Issue by ristein** [bitwarden/mobile#1250]
## Describe the Bug
In the popup when having max. five entries it shows a button to open Bitwarden as last entry. After adding one and having six entries there is no Bitwarden button anymore.

## Steps To Reproduce

Having min. six entries to autofill in one app:
1. Go to that app (i.e. k9)
2. Click on some password field
3. Scroll down to last entry in popup
4. No entry for Bitwarden app

## Expected Result
show Bitwarden button as last entry to manage entries and directly fill this.

## Actual Result
no Bitwarden button

## Environment

- Device: Oneplus 7 pro
- Operating system: Android 10
- Build Version: Custom Rom
- Is this a Beta release? N

**Comment by SergeantConfused** [comment]
Hi there,

I've tested this in an application login page and on a web page, and I was unable to reproduce this behaviour. I've added 8 items, and the 'Go to my vault' button was still present as the 9th option.
Please uninstall Bitwarden, reboot your device by turning it off (long press) and back on, reinstall Bitwarden, and test this again.
Please keep me posted, and try to include screenshots if this persists.

Thank you in advance,

**Comment by ristein** [comment]
Thank you for your reply.
After a reboot it works just fine.
I couldn't reproduce that issue again.
So, I guess, we can just dismiss this issue.
Only one other minor thing i experienced:

When clicking the popup while the vault is locked and unlocking it then but not choosing one item but going back, it still says vault is locked instead of showing those entries. A refresh on that page or app-screen is neccessary then.
