### ISSUE TITLE
Auto-fill not working on Android 11 but working on previous android

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/mobile#1264]
## Describe the Bug

I bought a new phone Samsung S21, I was previously using Samsung S8. While transferring (manually installing my apps one by one) from my old phone, I noticed that auto-fill is now working on several apps while it was working on my old phone.

## Steps To Reproduce

Check this on Android 11, preferable Samsung's phone.

List of apps:
ADP Mobile Solutions
https://play.google.com/store/apps/details?id=com.adpmobile.android

Macy's
https://play.google.com/store/apps/details?id=com.macys.android

SmartThings
https://play.google.com/store/apps/details?id=com.samsung.android.oneconnect

MySynchrony
https://play.google.com/store/apps/details?id=com.syf.mysynchrony

E*TRADE: Invest
https://play.google.com/store/apps/details?id=com.etrade.mobilepro.activity

Bank of America Mobile Banking
https://play.google.com/store/apps/details?id=com.infonow.bofa

Fidelity Investments
https://play.google.com/store/apps/details?id=com.fidelity.android

## Expected Result

The tile shows up.

## Actual Result

no tile shows up.

## Environment

- Device: Samsung S21
- Operating system: Android 11
- Build Version (go to "Settings" → "About" in the app): [e.g. 2.3.0 (2221)]
- Is this a Beta release? N

**Comment by jimrandle** [comment]
I have a similar issue with bitwarden and etrade on and older android. 6.0.1 I believe it has to do with the different user interface between the mobile app and the browser app. This may be complicated by the fact that the browser accesses us.etrade.com and the mobile app cm.etrade.mobilpro.activity. 
When I allow bitwarden to fill in the password I get an invalid password response from etrade. If I instead use the copy password function then paste the password into the mobile app I can sucessfully log in. My hypothesis is that bitwarden is putting something extra into the password field with autofill. 
I can't prove this, as etrade does not offer the option of showing a visible password. A possibility might be that it is putting the login name in the password field, but this is speculation.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
