### ISSUE TITLE
Edge Android Autofill

### ISSUE THREAD

**Issue by Jmalfano20** [bitwarden/mobile#1270]
## Describe the Bug

Autofill in Microsoft Edge Android does not prompt

## Steps To Reproduce

1. Have site and password info saved on bitwarden ex Facebook.com
2. Open chrome and got Facebook.com. Note that autofill is prompted
3. Open Edge and go to Facebook.com and note autofill is not prompted. 

## Expected Result

Autofill prompt to be shown like on chrome

Issue:

No prompt provided

## Environment

- Device: GALAXY S21 5g
- Operating system: Android 11 One UI 3.1
- Build Version (go to "Settings" → "About" in the app): Bitwarden Version: 2.8.0 (3349)
- Is this a Beta release? [Y/N] N

## Additional Context

Following this Note from site 
https://bitwarden.com/help/article/auto-fill-android/

"  Note
Android has many web browsers. It can be hard to keep up with them all. We have to add support for each browser individually.

If auto-fill does not work on your browser, please report it at https://github.com/bitwarden/mobile/issues so that we can add support. "

**Comment by DarrellK** [comment]
Same
Device: Pixel 4a
Operating system: Android 11 Update 5 (Feb 2021)
Build Version (go to "Settings" → "About" in the app): Bitwarden Version: 2.8.0 (3349)
Is this a Beta release? [Y/N] N

**Comment by Ajorat** [comment]
Same. OnePlus Nord, Android 10 (Oxygen OS 10.5.10AC01BA)
(Also turns out it does this on GitHub 😆, fine on Chrome, no autofill on Edge)

**Comment by ryanbowden** [comment]
Same issues,
Samsung S20 Note Andriod 11, one ui 3.1

Chrome works, Edge does not

**Comment by Leon99** [comment]
+1.
Given that it uses Chromium, I wonder how hard it is to add support for it?

**Comment by prairiesnpr** [comment]
It actually does work (Samsung S21), but only when edge is first started.  If you come to a site that you want to autofill, closing edge and reopening will result in the autofill prompt and a successful fill.  After some period of time, the autofill prompt stops showing and edge has to be restarted again.

**Comment by Sekers** [comment]
Also, please add in support for Edge Canary > https://play.google.com/store/apps/details?id=com.microsoft.emmx.canary

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
