### ISSUE TITLE
Android: Larger than "default" font sizes are too large

### ISSUE THREAD

**Issue by jgodfrey** [bitwarden/mobile#1272]
## Describe the Bug

On the below-mentioned device, setting the system font (_Settings | Display | Advanced | Font size_) to anything larger than _Default_ (so, _Large_ or _Largest_) causes the text used in Bitwarden to be far larger than expected. 

## Steps To Reproduce

* Set the system font to _Default_
* In Bitwarden, verify the text size looks _as expected_
* Set the system font to something larger than _Default_
* In Bitwarden, verify the text size is _much_ larger than expected, and larger than the Android UI and other apps on the same device with the same font settings.

## Expected Result

I expect the text to be a _reasonable_ size when using larger than default system font sizes.

## Actual Result

The text in Bitwarden is much larger than expected and larger than other apps on the same device using the same font setting.

## Environment

- Device: Pixel 4 XL
- Operating system: Android 11
- Build Version): 2.8.0 (3349)
- Is this a Beta release? N

**Comment by kendratodd** [comment]
From https://github.com/bitwarden/mobile/issues/1318, this also impacts the ability to login to the app:
>  Device: Samsung S10
>  Operating system: Viewed on Android 10 & 11 OS
>  Build Version (go to "Settings" → "About" in the app): 2.8.0 (3349)
>  Is this a Beta release? N

**Comment by peterHoburg** [comment]
One of my coworkers is also reporting this issue. It is preventing him from moving over from another password manager to BW. S21 with larger than default font is making the BW app unusable.

**Comment by SergeantConfused** [comment]
Hi everyone,

Please note that this also happens in iOS. Increasing the font size to the max under Accessibility > Display and Text > Larger Text pushed the Login page buttons outside the view and you cannot scroll down to reach them, thus you cannot log in.

All the best,

**Comment by fchagas97** [comment]
Any ideas on how to solve this? I use Android and there is no large font option (the font size is standard), but the texts in the app are absurdly large, making it almost impossible to use the app.

**Comment by djvfx** [comment]
So this seems to still be an issue...right?  I have a Samsung Note 8 and the FONTS ARE HUGE.  many are truncated and very difficult to read.  I do use larger text but many of my apps have settings to reduce and enlarge so I use accordingly.
Any update/input appreciated!

**Comment by fchagas97** [comment]
> So this seems to still be an issue...right? I have a Samsung Note 8 and the FONTS ARE HUGE. many are truncated and very difficult to read. I do use larger text but many of my apps have settings to reduce and enlarge so I use accordingly.
> Any update/input appreciated!

Yes, still an issue.

**Comment by binarydad** [comment]
Still an issue. Any movement on this? Thanks.

**Comment by lbalogh** [comment]
Yes this is still an issue. I've just switched from 1Password to Bitwarden on my girlfriend's Galaxy S21 and fonts are so big that the app is almost unusable

**Comment by binarydad** [comment]
FYI, still having this annoying issue. Sometimes the fonts go back to normal, and then randomly it'll go back to large. No idea why it flips back and forth like this.

**Comment by gajda-b** [comment]
14 month passed and the bug is still not solved!!
I am ne user of bitwarden and I am disgusted how they solve issues! So it is not worth paying!!

**Comment by dahamsta** [comment]
I only just noticed this a few weeks ago, I can't believe how large the fonts are, and how I didn't notice it before! Please fix it.

**Comment by jstetten** [comment]
Without simply saying "me too", could one of the maintainers be nice enough to verify that they can at least reproduce the giant font size problem throughout the app (as seen in various screenshots)?

Thank you in advance.

**Comment by dbosompem** [comment]
Hi @jstetten, apologies for the inconveniences caused. This bug will be reproduced and will be added to our internal boards to be worked on while we keep you in the loop.

**Comment by douglasparker** [comment]
Bitwarden font still looks extremely big when using a higher resolution despite the system font being 2 ticks above the smallest font.

I have to put the system font size to the smallest possible for Bitwarden to look normal, but then my system apps look too tiny.

**Comment by douglasparker** [comment]
@aj-rosado This is still an issue...
