### ISSUE TITLE
Autofill search cannot open keyboard (iOS)

### ISSUE THREAD

**Issue by yeagerd** [bitwarden/mobile#1273]
## Describe the Bug
Cannot open keyboard to autofill password for iOS app for apps that doesn't auto-detect properly. The cursor is in the search box, the list of results is below, but the keyboard does not open and there is no clear way to invoke it.

## Steps To Reproduce
1. Go to an app like Vanguard that doesn't expose the information necessary for BitWarden to find the autofill information or for which the user has multiple credentials saved.
2. Click on the password field in the app.
3. Click on the iOS keyboard "Passwords" autofill button; Bitwarden launches

## Expected Result
Either
1. Cursor is not in the search text field.  Clicking the search text field brings up keyboard.

< or >

2. Cursor is in the search text field and the keyboard is present.

## Actual Result
1. Cursor is already in the search text field, so there is nowhere to click to bring up the keyboard.

< and >

2. Keyboard is not present.

## Environment
- Device: iPhone 12 mini
- Operating system: iOS 14.4
- Build Version: 2.8.0
- Is this a Beta release? N

## Additional Context
- FaceID is enabled.
- Vault timeout is set to 4 hours.
- Vault timeout action is Lock.
- Unlock with PIN is Disabled.

**Comment by markaldridge** [comment]
Same problem on an iPhone 12 Pro Max running iOS 14.2.1

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
