### ISSUE TITLE
Auto-fill not working consistently in Chrome for Android

### ISSUE THREAD

**Issue by raywdude** [bitwarden/mobile#1276]
## Describe the Bug

When you first start the Chrome app, and go to a page to login, the auto-fill options work (either overlay or in-line in keyboard). However, if you navigate to a different page after that, then the auto-fill features completely stop working. Even if you navigate straight back to the page you were just at where Auto-fill was working at.

## Steps To Reproduce

1. Open Chrome on Android
2. Navigate to "Chase.com",  click "Sign in" and tap on the username box and see either the Overlay or In-line options on keyboard
3. Tap "Sign In"
4. On the same tab, navigate to "Discover.com" and tap on the username box - neither overlay nor in-line options are showing up now.
5. Open overview (recent apps) menu, and swipe away Chrome.
6. Re-open Chrome, which will resume back on "Discover.com", tap on the username box - notice that the auto-fill options mysteriously return...

## Expected Result

The auto-fill feature should ALWAYS work.

## Actual Result

The auto-fill feature completely stops working after doing the above steps.

## Environment

- Device: Samsung Galaxy Z Fold 2 (SM-F916U1)
- Operating system: Android 11 (One UI 3.0)
- Build Version (go to "Settings" → "About" in the app): 2.8.0 (3349)
- Keyboard: Gboard
- Chrome version: 88.0.4324.181
- Is this a Beta release? [Y/N] N

## Additional Context

I switched over from LastPass, which worked most of the time with auto-fill in Chrome for Android. Hopefully this is fixed soon.

## Video

Attached video reproducing the problem: https://user-images.githubusercontent.com/1065479/108616193-32a98500-73d9-11eb-81e2-86c24f9d7b97.mp4

**Comment by SergeantConfused** [comment]
Hi there,

Welcome to Bitwarden!
I tested this on our web vault's login page and then on tutanota's login page, and it worked as expected. I've tested this using inline autofill via GBoard on a Note 10+ running Android 11 (One UI 3.0).
Please uninstall Bitwarden, reboot your device, reinstall it, and make sure all your autofill options are activated: https://bitwarden.com/help/article/auto-fill-android/ and all your power saving options are deactivated: https://dontkillmyapp.com/samsung
I did encounter some trouble when using the Accessibility service (black and white shield) to perform autofill, and I'm looking into that, but that did not prevent Bitwarden from displaying the autofill banner.

Keep me posted on how this works out for you.


Thank you in advance,

**Comment by raywdude** [comment]
Hi Sergeant,

Thanks for your reply.

I only have the Auto fill Service and Inline options enabled in BitWarden and I'm not enabling any power saving options.

I'm intentionally not using the accessibility method because that causes overall system responsiveness to noticeably be hampered.

As a total shot in the dark, I tried installing Chrome Beta 89 and that one shows the BitWarden autofill options consistently every single time. When I go back to Chrome Stable (88) the same thing described in the OP still occurs consistently.

Another thing I noticed is while testing more sites on Chrome Beta 89 is, sites like Newegg's mobile site, when you try to login, it prompts for email only first and when you activate BitWarden autofill, it fills your password into the email field.

Thanks,
Ray

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by eliykat** [comment]
Hey @KamilKolonko, I've double checked with the team and #1389 is intended for all autofill-related issues. I've updated the description of #1389 to be clearer about this. In this case, we've been unable to reproduce the issue internally (I attempted myself just to make sure before replying to you), so it's likely some combination of hardware/browser/website which that issue is intended to capture. If you can complete the Google form, that will ensure that this is appropriately triaged along with other mobile autofill issues.
