### ISSUE TITLE
Auto-fill not working in Samsung Internet browser 13.2.2.4 at all

### ISSUE THREAD

**Issue by raywdude** [bitwarden/mobile#1277]
## Describe the Bug

The auto-fill feature never worked in Samsung Internet browser for me..."wait for 12.x"...didn't work. "wait for 13.x"...still doesn't work.

## Steps To Reproduce

1. Have latest version of Samsung Internet browser (13.2.2.4) installed
2. Have latest version of BitWarden installed
3. No matter which web site or form you to go, neither the Overlay or In-line options for Auto-fill ever pop up in Samsung's browser. Works in Chrome on first try* (see Chrome issue https://github.com/bitwarden/mobile/issues/1276)

## Expected Result

The auto-fill feature should work, at least on par with Chrome.

## Actual Result

The auto-fill feature does not work at all.

## Screenshots or Videos

N/A

## Environment

- Device: Samsung Galaxy Z Fold 2 (SM-F916U1)
- Operating system: Android 11 (One UI 3.0)
- Build Version (go to "Settings" → "About" in the app): 2.8.0 (3349)
- Keyboard: Gboard
- Is this a Beta release? [Y/N] N

## Additional Context

Neither LastPass nor BitWarden work in Samsung Internet browser for me.

**Comment by sso-bitwarden** [comment]
Password managers won't work on browsers that are not using Android's autofill API and accessibility events. Examples: Samsung Browser, OH Browsers, Pure Browsers, etc.

**Comment by Tosko4** [comment]
I got a workaround though, https://github.com/bitwarden/mobile/issues/895#issuecomment-822217867

Sent an email to the samsung browser team. https://github.com/bitwarden/mobile/issues/895#issuecomment-822231828

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
