### ISSUE TITLE
Android Dolphin browser . No autofill

### ISSUE THREAD

**Issue by sarek01001** [bitwarden/mobile#1278]
Hello there im using dolphin broser from years and now switched from lastpass to bitwarden

## Describe the Bug
no autofill
seem that bitwarden only match  the uri
-----
androidapp://mobi.mgeek.TunnyBrowser
----

and not the website that is on the window

## Steps To Reproduce

1)open dolphin broser and try to  use bitwarden
2)no match  with any website
3) if you try to save a pw ... the uri saved on bw is  ; androidapp://mobi.mgeek.TunnyBrowser

## Environment

- Device: samsung s20
- Operating system: android 11
- Is this a Beta release? [Y/N] N

thanks

**Comment by eugene-papko** [comment]
Same here. Latest versions of Bitwarden and Dolphin. SM-G975U running Android 11. Would be great to get it fixed.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
