### ISSUE TITLE
[Android] Editing Notes is user-hostile

### ISSUE THREAD

**Issue by tp0** [bitwarden/mobile#128]
- View some login
- Tap edit
- Activate the Notes text field and type _more_ lines that you're able to see at once.
- Only way to scroll the Notes text field is to drag the caret. That's cumbersome and it is easy to get a situation where you can't actually see where/what you're typing.

Expected result: the Notes text field can be scrolled separately with a gesture or the Notes field dynamically expands with each new line always showing all of the content.

**Comment by kspearrin** [comment]
Hmm I thought it did scroll with gesture. I'll have a look. Thanks.

**Comment by kspearrin** [comment]
Fixed https://github.com/bitwarden/mobile/commit/e4c96dc6d8b46146f4ace9c4ef09defb9717b5e2
