### ISSUE TITLE
Autofill in Chrome on Android inconsistent

### ISSUE THREAD

**Issue by mdollemore** [bitwarden/mobile#1282]
## Describe the Bug
Coming from Lastpass to Bitwarden. Lastpass was never great at autofill, but Bitwarden unfortunately seems even worse.
Lots of sites never work, such as github, other only work after all chrome tabs are closed and then chrome is exited.
The below two common sites are examples of both types of behaviour.

## Steps To Reproduce

Github
1. With uri github.com/login saved in vault with username and password 
2. From Vault click Launch
3. Site opens in Chrome, but no bitwarden option to use username/password

Udemy
1. With uri www.udemy.com/join/login-pop saved in vault with username and password
2. Delete any open tabs in Chrome and then exit Chrome
3. From Vault click launch for udemy
4. Bitwarden autofill options works as expected.
5. Do the same but with other tabs open in Chrome and do not exit Chrome
6. Bitwarden autofill options fails to appear.

## Expected Result
Github - Expect to see autofill option to select the bitwarden username/password when fields are selected
Udemy - autofill works consistently and without the need to close all tabs and exit Chrome

## Actual Result
Github - Never shows the option to use autofill
Udemy - Autofill only works after all Chrome tabs are closed and Chrome is exited.

## Environment

- Device: Samsung S8
- Operating system: Android 9
- Build Version PPR1.180610.011.G950FXXSBDUA3
- Is this a Beta release? No
- Chrome version: 88.04324.181 and also Chrome Beta 89.0.4389.57

## Additional Context

Much prefer Bitwarden to LastPass, but dissappointed that Autofill is so inconsistent. If this was fixed the LastPass or BitWarden decision would be a no brainer.

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
