### ISSUE TITLE
(ios) App Extension is not working on Chrome and Edge

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/mobile#1284]
## Describe the Bug

App Extension enabled, hoping it's able to auto-fill on Chrome and Edge

## Steps To Reproduce

1. Enable App Extension
2. Open Chrome
3. Click Share, Bitwarden
4. Unable to find saved item

1. Enable App Extension
2. Open Edge
3. Click Share, Bitwarden
4. Click item
5. username password still empty

## Expected Result

Able to find item and auto-fill

## Actual Result

Chrome: Unable to find item
Edge: can't auto-fill, username password fields stay empty

## Environment

- Device: iPhone SE
- Operating system: iOS 14.4
- Build Version: 2.8.0
- Is this a Beta release? N

**Comment by cornuwel** [comment]
Same device and version. Just wanted to add DuckDuckGo Privacy Browser to the list. Same behavior as Chrome through share.
No keyboard autofill at all.

**Comment by rrileyca** [comment]
Can confirm. It would probably be useful to see what string is going into the "auto-search". I have a bunch of endpoints at home like http://portainer.local, and they work in desktop browsers but don't work in iPhone 11 Safari/Chrome/DuckDuckgo.

**Comment by eliykat** [comment]
This should be fixed for Chrome with the changes here: https://github.com/bitwarden/mobile/pull/1254. Not sure about Edge, however if you're still experiencing this issue, please log it per the information below.

---

Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by rrileyca** [comment]
@eliykat great thank you. There hasn't been a release in a while, any idea when the next release will hit? I'm assuming this PR will be in it?

**Comment by eliykat** [comment]
@rrileyca That PR was included in the March release (v 2.9.0, the same release that added Send). If you've upgraded to that version and you're still experiencing issues then maybe it's a different problem.

**Comment by rrileyca** [comment]
@eliykat Unfortunately nothing has changed for me. I'm using 2.9.1. Whether I do the Share>Bitwarden flow or I use the Passwords button in the iOS keyboard, no results are found.

**Comment by rrileyca** [comment]
@eliykat sorry correction - some of my local domain names are not being matched. It seems like the pattern is anything that ends in `.local` doesn't work. For example, `pihole.local`. Is that normal behaviour?

**Comment by eliykat** [comment]
@rrileyca I'm not aware of any rule (or reason) that would exclude `.local` domains. Please report it via the form in #1389 with any updated information from your testing, and it'll be triaged for one of our devs to review. Thanks!
