### ISSUE TITLE
URI Not Opening

### ISSUE THREAD

**Issue by tiptruck** [bitwarden/mobile#1286]
## Describe the Bug
When viewing an item, pressing the icon (square with arrowpointing right) in the URI field does not open the URI.

## Steps To Reproduce

Open My Vault
Open an item eg a user/passward entry
Press the square and arrow icon next to the website URI
## Expected Result
The website should open in the default browser

## Actual Result
Nothing happens

## Environment

- Device: [e.g. iPhone6] Samsung Tab S7
- Operating system: [e.g. iOS 8.1] Android 11
- Build Version 2.8.2 (3365)
- Is this a Beta release? [Y/N] Y

## Additional Context
Works correctly on my other device (Nokia 6.1 Android 10.

**Comment by rindertb** [comment]
and #1164 See also [Reddit ](https://www.reddit.com/r/Bitwarden/comments/lm626f/android_11_app_will_not_open_web_browserpages/god20a4/?context=3)and [community](https://community.bitwarden.com/t/android-app-settings-click-on-items-no-respond/18504).

**Comment by tiptruck** [comment]
This is a duplicate of #1164. Closing.
