### ISSUE TITLE
Username autofill not working correctly

### ISSUE THREAD

**Issue by vivek201** [bitwarden/mobile#1287]
## Describe the Bug

The autofill is showing the correct username but I need to erase the username and put it again to successfully login

## Steps To Reproduce

1. Click on the saved password
2. Click Login but it fails
3. Clear the username 
4. Paste the same username from bitwarden
5. It logins

## Expected Result

It should login the first time

## Actual Result

The login fails until I clear and re-enter the username

## Environment

- Device: Android
- Operating system: Android 8.1.0
- Build Version: 2.8.0 (3349)
- Is this a Beta release? N

## Additional Context

This is only happening for a couple of apps and it seems to be working fine for others.

**Comment by Greenderella** [comment]
Could you share with us the name of the apps, so we can test them?

**Comment by vivek201** [comment]
- Sunrise Smart (com.f1soft.sunrisemobilebanking)
- MeroShare (com.meroshare.app)
These are both local banking apps.

**Comment by clayadams5226** [comment]
Hi @vivek201 , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Comment by vivek201** [comment]
I recently figured out the issue. For some reason, the username was saved with whitespace at the beginning and that's what was causing the issue. I hasn't happened with any other apps so far.
