### ISSUE TITLE
Several items in settings not working with Android 11

### ISSUE THREAD

**Issue by lylej77** [bitwarden/mobile#1290]
Hello,

Web Vault, Help & Feedback and Import Items don’t work with Android 11. All other settings options are working. I'm using a Pixel 4a.

Originally tried on 2.8.0, joined the beta and it’s not working with 2.8.2 (3365) either.

It does work on my tablet running Android 9.

**Comment by 5646543518** [comment]
I recently upgraded to a phone running Andorid 11 and cannot even sign in to BitWarden. It hangs at the "Loggin in" prompt then eventually just fails with an error that the action was interrupted.

**Comment by tupaschoal** [comment]
I'm also seeing this, there are other options not working: Change master password / Import Items / Share your vault / Bitwarden web vault / Help and Feedback

**Comment by tupaschoal** [comment]
Has this been fixed @mportune-bw ? Just want to understand the closing
