### ISSUE TITLE
Unable to Type Master Password when using Autofill

### ISSUE THREAD

**Issue by JeffResc** [bitwarden/mobile#1295]
## Describe the Bug

Keyboard does not come up when typing in Master Password (only when activated via the "Passwords" button when filling out a form)

## Steps To Reproduce

1. Go to a password form in Safari, Firefox, any app...
2. Click autofill password from Bitwarden
3. Do not use biometrics
4. Click master password and try to type it in

## Expected Result

For a keyboard to appear so that I may enter my master password

## Actual Result

No keyboard appears and I am unable to enter my password

## Screenshots or Videos

[Video](https://imgur.com/a/6MUewod)

## Environment

- Device: iPhone 11 Pro Max
- Operating system: iOS 14.3
- Build Version (go to "Settings" → "About" in the app): 2.8.0 (449)
- Is this a Beta release? N

## Additional Context

I don't have a picture or video because I cannot reproduce this currently, but sometimes once you authenticate and use the search tool at the top, once you click in the text box to start your search, the keyboard does not appear either.

Both of these have been happening for about two months now and I tried waiting it out to see if it would be fixed, but it still has not been fixed in the latest version of the app.

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by JeffResc** [comment]
For anyone who stumbles upon this with the same issue, please see #1114.
