### ISSUE TITLE
Accessibility Service Gets Disabled Randomly

### ISSUE THREAD

**Issue by danieldugas** [bitwarden/mobile#1303]
## Describe the Bug

same as https://github.com/bitwarden/mobile/issues/484

## Steps To Reproduce

1. enable accessibility service for bitwarden
2.  works
3. few days later, is disabled again

## Expected Result

should stay enabled

## Actual Result

does not stay enabled

## Environment

Android 10
10.0.0.383
Bitwarden 2.8.0

## Additional Context

Extra disappointing is that I need this only because bitwarden autofill doesn't work on Firefox android (similar to https://github.com/bitwarden/mobile/issues/683 and https://github.com/bitwarden/mobile/issues/784)

**Comment by magdumnikhil** [comment]
MIUI Global 12.1.1 based on Android 11

**Comment by Greenderella** [comment]
Hi @danieldugas,

If you keep experiencing the Auto-fill Accessibility Service becoming disabled, check these settings in this order.
1. Double-check your Battery Optimization settings, you will want to make sure it is turned off for Bitwarden.
2. If you use a Battery Saver or Task Manager app then you may try to disable it to see if it makes any difference. If disabling the app makes a difference, add Bitwarden to the exception list.
3. Check the built-in Task Manager. You will need to bring up the running apps view and then hold down or swipe up on the Bitwarden app and then select Lock.
4. If you have tried all the above, and it is still not staying active and if you are using a Samsung device, you may need to check your Samsung KNOX configuration. This is most likely only something to check if your device is part of a company, work, or enterprise profile. 

The service can also halt if you "Force stop" the Bitwarden app. Here is an interesting site regarding devices and their battery optimization default configurations: https://dontkillmyapp.com/

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
