### ISSUE TITLE
Autofill detection improvements for android

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/mobile#131]
Search login URI and Name for search terms that come from the android package name. These will be added as fuzzy results in the autofill detected list of logins.

**Comment by kspearrin** [comment]
https://github.com/bitwarden/mobile/commit/4008fb3a536989195fc7b7396550ec06fe90c884

**Comment by kspearrin** [comment]
@Primokorn I think you were one that wanted improvements around this want to test this in the Play Store beta?

**Comment by Primokorn** [comment]
I updated to v1.10.0 - 942 but I see no changes.
I tried to log in on XDA Developers forum using Atlas web browser (nextapp.atlas.rk). I don't see XDA in the suggestion list.

**Comment by Primokorn** [comment]
`http://forum.xda-developers.com/` or 'https://forum.xda-developers.com/register.php' (I have 2 accounts in my vault)

**Comment by Primokorn** [comment]
Same thing with my Nextcloud. URI `https://ncloud.zaclys.com/`
bitwarden is still looking for `nextapp.atlas`

**Comment by kspearrin** [comment]
@Primokorn I am testing XDA right now and autofill works with the app https://play.google.com/store/apps/details?id=com.xda.labs.play&hl=en ? 

As for new cloud, looks like that wont ever work without a domain rule. The package name has nothing in common with the web URI.

**Comment by Primokorn** [comment]
I'm talking about the XDA forum using a web browser.
I think I misunderstood this issue... Can bitwarden app detect the top domain of the current visited web site then suggest related credentials from the vault?
I downloaded XDA Labs and bitwarden does suggest my XDA credentials (and one from YU forum...).

**Comment by kspearrin** [comment]
@Primokorn Maybe I am misunderstanding you too? That is how bitwarden has always worked.

- www.xda-developers.com
- forum.xda-developers.com
- xda-developers.com

These are all treated the same and will display the same results.

**Comment by Primokorn** [comment]
Actually I thought you implemented a detection as per the visited web pages (top domain).
Having fuzzy results is still a great feature.
