### ISSUE TITLE
Android: Largest font size makes it impossible to log in

### ISSUE THREAD

**Issue by paulhennell** [bitwarden/mobile#1318]
## Describe the Bug

A logged out user launching the Bitwarden app on android is unable to see the login buttons when the display font is set to the maximum font size available.

## Steps To Reproduce

0. (Log out of bitwarden 👍)
1. Set the font to the maximum size in Android (Settings > Display > Font size and style)
2. Open Bitwarden App.
3. Try to scroll or reach login option.

## Expected Result

You should be able to scroll / log in

## Actual Result

The largest font pushes the button off screen and you cannot scroll to reach it.

## Screenshots or Videos

Tells me **"Screenshots are not possible because of security"**

## Environment

- Device: Samsung S10
- Operating system: Viewed on Android 10 & 11 OS
- Build Version (go to "Settings" → "About" in the app): 2.8.0 (3349)
- Is this a Beta release? N

## Additional Context

See also the likely related #1272.

**Comment by kendratodd** [comment]
Hi @paulhennell - thank you for the report! I'm going to consolidate this issue into https://github.com/bitwarden/mobile/issues/1272 and close this one as a duplicate for now.
