### ISSUE TITLE
Text bug on Android  

### ISSUE THREAD

**Issue by QLPem** [bitwarden/mobile#1319]
## Describe the Bug

 After the new Update for the Bitwarden send feature the My Vault section in German is not displayed corretly but if you click on the other sections the my Vault section is fully displayed
## Steps To Reproduce

 Your Android Smartphone need to be in German and you need the newest Bitwarden version

## Expected Result

 My Vault = Mein Tresor only My = Mein is displayed in german

## Actual Result

My Vault = Mein Tresor. Only the half of Mein Tresor is displayed correct that means you only see My = Mein if you have the 
My Vault section selected

## Screenshots or Videos

![Pic 1](https://user-images.githubusercontent.com/69923250/111221891-609a7780-85db-11eb-9525-5ae61714f86d.jpg)
![Pic 2](https://user-images.githubusercontent.com/69923250/111221900-62fcd180-85db-11eb-8b5f-055b912754a2.jpg)

## Environment

- Device: [Samsung Galaxy s9]
- Operating system: [Android 10]
- Build Version (go to "Settings" → "About" in the app): [2.9.1(3444)]
- Is this a Beta release? [N]

**Comment by m-terlinde** [comment]
Hey guys,

I've the same issue on my Fairphone 3, rest of the specs are the same.

Thanks,
Matthias
