### ISSUE TITLE
Latest apk only available on Google Play

### ISSUE THREAD

**Issue by vinnyperella** [bitwarden/mobile#1322]
## Describe the Bug

Version 2.9.1 is not listed on github or f-droid so the only way to download it is Google Play which a lot of people do not use. It would be cool if you could provide the apk elsewhere.

## Steps To Reproduce

Look at https://github.com/bitwarden/mobile/releases and see the latest version listed is 2.9.0. There is also no update to the fdroid repo it still shows 2.9.0 as the latest.  

## Expected Result

The latest version, 2.9.1, should be available on guthub and fdroid if the Google Play store is updated. Unless the update is specifically for the play store version.

## Actual Result

Latest version listed is 2.9.0.

**Comment by mportune-bw** [comment]
Apologies for the delay, this should be fixed now.
