### ISSUE TITLE
Can't add new Send item in Android app

### ISSUE THREAD

**Issue by gdamas23** [bitwarden/mobile#1323]
## Describe the Bug

It's impossible to add a new Send item from the Android app. It's an endless loop of not being able to add a file within the Send view.

## Steps To Reproduce

1. Click on the "Send" tab at the bottom of the default screen.
2. Click the blue plus sign.
3. Name your Send whatever you'd like.
4. With the "File" type selected, click "Choose File".
5. The default Android file view is opened. Select your file.
6. I immediately have to verify my Master Password again (I use the fingerprint biometrics).
7. Upon verifying, it takes me back to the "My Vault" tab.

## Expected Result

I expected to be able to choose a file and then it redirects me to the current in progress "Send" item I was creating.

## Actual Result

I keep getting sent back to the "My Vault" tab so I can't create a Send link.

## Screenshots or Videos

I have screenshots and recording turned off, but if you need me to send in a video, let me know.

## Environment

- Device: Pixel 3 XL
- Operating system: Android 11
- Build Version (go to "Settings" → "About" in the app): 2.9.1 (3444)
- Is this a Beta release? N

**Comment by mportune-bw** [comment]
Hi @gdamas23 , thanks for reporting this.  It sounds like your `Vault Timeout` set to `Immediately`, is that correct?

**Comment by gdamas23** [comment]
Yes, that is correct. Changing the Vault Timeout to 1 minute makes the
issue not occur. Good to know. Still not ideal, but a valid workaround.

**Comment by mportune-bw** [comment]
Thanks for confirming.  Agreed it's not ideal - definitely a bug I'm looking into.

**Comment by gabrbrand** [comment]
@mpbw2 I don't know whether this bug reapeared in the last years, but I'm experiencing this behavior again.
I'm not able to select a file to send when vault timeout is set to immediately.

Version: 2025.6.1 (20398)
📱 samsung SM-A556B 🤖 15@35 📦 prod
🧱 commit: bitwarden/android/release/hotfix-v2025.6.0-bwpm@e8878d321546a846909c70c00cdf8d7071f0ecf0
💻 build source: bitwarden/android/actions/runs/15984517798/attempts/1
