### ISSUE TITLE
Bitwarden not working with WebView

### ISSUE THREAD

**Issue by Slion** [bitwarden/mobile#1324]
Users of Fulguris Web Browser are reporting Bitwarden is not working. Google's own autofill service is working fine so I'm trying to understand what is preventing Bitwarden to get the job done.

I've also opened an issue in the Fulguris repository: Slion/Fulguris#177

**Comment by Slion** [comment]
On the following page is explained how an autofill service should parse provided data:
https://developer.android.com/guide/topics/text/autofill-services
I find the traverseStructure and traverseNode methods interesting. I wonder how Bitwarden could fail to retrieve the proper WebDomain if it is using that approach of traversing from the rootViewNode.

**Comment by jamal2362** [comment]
I think you must make an Pull-Request with your Package name.

https://github.com/bitwarden/mobile/commit/685548ab723543bd05a671f485e5cb27c688cb2b#diff-4f8cec091436d3dd5e83798a9727a121a81a82a90766200d840966a6b3ea9bc5

**Comment by Slion** [comment]
Thanks @jamal2362 mystery solved. Browsers need to be added to bitwarden's authorized list for autofill to work.
https://github.com/bitwarden/mobile/pull/1333
