### ISSUE TITLE
[Bug] Crashing unexpectedly after attempting to autofill credit card details on Chrome (and maybe other apps) with quick tile (see the demo video inside)

### ISSUE THREAD

**Issue by K0media** [bitwarden/mobile#1326]
## Describe the Bug

Mobile app crashes unexpectedly after tapping the autofill quick tile (Android) with accessibility services on.

## Steps To Reproduce

1. Install Bitwarden mobile app and log in;
2. Set up proper permissions for accessibility services to enable using the custom quick tile from notifications pane;
3. Go to a credit card form (e.g.: Bitwarden premium), tap the autofill entry and (if not previously saved) look up for the credit card entry to input to that form.
4. (reloads the app or if you do it twice while logged in it will crash.)

## Expected Result

It should autofill the credit card details fine instead. But it's currently crashing.

## Actual Result

Leading to fatal app crash. Please see the log details here:
https://clipto.pro/l/yAAG6mxmMMuQkBkv5

## Screenshots or Videos

Full video showing the issue scenario (click the image below to view on YouTube):
[![Click here to view on YouTube.](http://img.youtube.com/vi/mgzEtiW2E5g/0.jpg)](http://www.youtube.com/watch?v=mgzEtiW2E5g "Bitwarden autofill crash video")

## Environment

- Device: Xiaomi Redmi Note 8
- Operating system: Android 10 (MIUI 12, latest stable version, for the device, non-root)
- Build Version: Bitwarden v2.9.1 (beta)
- Is this a Beta release? Yes.

## Additional Context

It might be related to #1276. Not sure if it happens only with Google Chrome for Android, but it may happen with the same crash for other apps too.
After it happens once, the accessibility service becomes "glitched", so you can't use it switching off/on again, unless you clear the full app data and log off successfully (as shown in the demo video above).

**Comment by clayadams5226** [comment]
Hey @K0media, thanks for the bug report. Card Card auto-fill is not supported on mobile at this time, however it should not crash the app. I'll gt this prioritized and sent to the team to investigate.

**Comment by K0media** [comment]
> Hey @K0media, thanks for the bug report. Card Card auto-fill is not supported on mobile at this time, however it should not crash the app. I'll gt this prioritized and sent to the team to investigate.

Just noticed something else: the same behavior **occurs occasionally if I reboot** the device or after a while.

So I have to do the same procedure of the video above in order to get it back to work.

Not sure what's going on here, but I can examine further if needed.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by wsolorza** [comment]
Same here but shady for websites. When I gave it permissions for the camera for some reason it fixed it for a few days but now it's back to freezing as soon as I click the auto fill it's just a blank page if I wait about 35 to 60 seconds then it appears
