### ISSUE TITLE
iOS Autofill Does Not Work With iFramed Pages

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/mobile#133]
ex. https://account.authorize.net

**Comment by eliykat** [comment]
Closing this as part of the effort to collate all autofill defects in #1389.

---

Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
