### ISSUE TITLE
iOS - Master Password Does Not Work on Mobile

### ISSUE THREAD

**Issue by arianitu** [bitwarden/mobile#1331]
## Describe the Bug
My master password does not work on mobile, but works on the Web and Chrome Extension. My password is quite long, so I am unsure if the iOS app is cutting off the password when sending to the server.

I've even tried to copy and paste the master password directly from my browser to my phone and it still does not work. I'm slightly worried about input handling on BitWarden now.

## Steps To Reproduce

I am unsure how to reproduce since it's probably an issue with my password in particular.

## Expected Result

My password should work on iOS app.

## Actual Result

My password does not work on IOS. It says "Wrong email or password"

## Environment

- Device: iPhone XS MAx
- Operating system: iOS 14.4.1
- Build Version (go to "Settings" → "About" in the app): I cannot get this from the login screen, but I downloaded the app today (March 22nd.)
- Is this a Beta release? N

## Additional Context

I am not using any strange unicode characters, I am using standard alphanumeric + symbols + space.

**Comment by doctorkelp** [comment]
I'm experiencing this issue, too.

**Comment by arianitu** [comment]
Now my password doesn't work anywhere.... did BitWarden change their password handling?

**Comment by arianitu** [comment]
@doctorkelp looks like it was my e-mail. I don't think BitWarden verifies your email so make sure its correct.

My password now works fine.
