### ISSUE TITLE
Doesn't detect nordaccount.com. (No Overlay)

### ISSUE THREAD

**Issue by vegedb** [bitwarden/mobile#1335]
## Steps To Reproduce

1. Go to 'https://nordaccount.com/ using any app (firefox,chrome,brave,bromite)'
2. Click on 'login'

## Expected Result

There should be a bitwarden overlay.

## Actual Result

Bitwarden overlay is non-existent on this website. 

## Environment

- Device: [android phone]
- Operating system: [android 11]

## Additional Context

Previously logging in is directly from the app, which bitwarden detects. Now, Nord has changed to browser login only.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
