### ISSUE TITLE
Bitwarden causing email and other app crashes

### ISSUE THREAD

**Issue by DukeAdam** [bitwarden/mobile#1337]
## Describe the Bug
Since installing the bitwarden app yesterday, it has caused a large number of apps on my phone to crash on startup. 
All I did since installing was enable 2FA and setup Authy. 
Causes app crashes for apps like MyFitnessPal, AIB bank app, Gmail, Outlook. 

## Steps To Reproduce
The following steps are what I did yesterday, which I believe caused the error. 

Installed the Bitwarden app and log in using existing account
Use Twilio Authy for 2FA
Go to settings in Bitwarden
Click on Auto-fill services and select Autofill slider, this then brings up the Autofill app selector page, choose bitwarden, accept service statement
Also setup Unlock with PIN code
Close out app. 

Since then this is the first indication that I have seen of an issue with my device, so can only conclude that the issue is with something to do with Bitwarden/Authy.
Have uninstalled and reinstalled Bitwarden and Authy and still giving issues as well as  have restarted device several times cleared cache. 
No joy

## Environment
- Device: Huawei P20 Lite
- Operating system: Android 9.1
- Build Version: 2.9.1 (3444)
- Is this a Beta release? No

**Comment by goodvibes2** [comment]
Google had a problem with Android updates yesterday. I suggest doing all play store updates and then if problem has gone away, close this issue.

**Comment by DukeAdam** [comment]
You're right. Updated all apps and the issue disappeared. 
Thank you
