### ISSUE TITLE
Android: App keeps asking to enable accessibility service even though the service is already on

### ISSUE THREAD

**Issue by ziffusion** [bitwarden/mobile#1341]
## Describe the Bug

When trying to use autofill from the Bitwarden tile in the Android Quick Settings menu, the application keeps asking to enable accessibility service even though the service is already on.

## Steps To Reproduce

1. Click on the Bitwarden tile in the Android Quick Settings pull down.

## Expected Result

1. The app should autofill the usename password fields on the page.

## Actual Result

1. The application displays an error message asking to enable the accessibility service even though the service is already on.

## Screenshots or Videos

![Screenshot_20210328-184633](https://user-images.githubusercontent.com/341389/112771076-f41a7200-8ff7-11eb-9a33-15d3d1dc9a5e.png)

![Screenshot_20210322-092525](https://user-images.githubusercontent.com/341389/112771077-f8df2600-8ff7-11eb-8473-7d6f84e3c06f.png)

![Screenshot_20210328-184000](https://user-images.githubusercontent.com/341389/112771082-01cff780-8ff8-11eb-8cbe-ee18b84f4fe1.png)

## Environment

- Device: Motorola One Fusion+
- Operating system: Android 10
- Build Version: 2.9.1 (3444)
- Is this a Beta release? N

**Comment by unknownsoldierx** [comment]
Moto G Power (2020). Android 10.

Same problem here. Bitwarden setting 'Use Accessibility' stays disabled even though it's enabled in OS settings.

**Comment by Greenderella** [comment]
Hi @ziffusion,

If you keep experiencing the Auto-fill Accessibility Service becoming disabled, check these settings in this order.

1. Double-check your Battery Optimization settings, you will want to make sure it is turned off for Bitwarden.
2. If you use a Battery Saver or Task Manager app then you may try to disable it to see if it makes any difference. If disabling the app makes a difference, add Bitwarden to the exception list.
3. Check the built-in Task Manager. You will need to bring up the running apps view and then hold down or swipe up on the Bitwarden app and then select Lock.

The service can also halt if you "Force stop" the Bitwarden app. Here is an interesting site regarding devices and their battery optimization default configurations: https://dontkillmyapp.com/

**Comment by aliekiddo** [comment]
@Greenderella I also have this problem, battery optimisation is off for Bitwarden.
The 'Use Accessibility' toggle in the app will not turn on despite turning the accessibility settings off and on again in Android settings.

**Comment by rsngfrce** [comment]
I have experienced this issue as well, but I have also experienced for apps other than Bitwarden, so I don't believe it is a Bitwarden specific issue.

(Samsung Galaxy S10e, Android 11. I believe I have battery optimization under control, but believe I have apps getting killed due to memory issues since upgrading to Android 11)

**Comment by Indranil012** [comment]
Same issue, battery optimization is already disabled.
device- Poco M2
android version - 10
miui 12.0.4

**Comment by mod-john** [comment]
All Battery Saving and Battery Optimisation is turned off for Bitwarden and accessibility is turn on but same issue. The switch won't go to enabled and the auto fill title claims it's not enabled.

Phone is a Blackview BV5900 running Android 9

**Comment by anuraag488** [comment]
On miui 12.0 enabling autostart solved issue for me.

**Comment by mod-john** [comment]
> On miui 12.0 enabling autostart solved issue for me.

How do you do this?

**Comment by anuraag488** [comment]
> > On miui 12.0 enabling autostart solved issue for me.
> 
> How do you do this?

![Uploading IMG_20210906_175130.jpg…]()

**Comment by anuraag488** [comment]
> > On miui 12.0 enabling autostart solved issue for me.
> 
> How do you do this?

![IMG_20210906_175130](https://user-images.githubusercontent.com/7353086/132216860-089fe57a-9e32-41b5-8e68-9f32cbb5aadf.jpg)

**Comment by sso-bitwarden** [comment]
+1 

Samsung A32 5G, Android 11.

**Comment by mod-john** [comment]
This is still an issue for me.
![Screenshot_20211116-013837](https://user-images.githubusercontent.com/12935853/141880449-3414ad70-927f-452c-b715-0e9017765e55.png)

**Comment by kniahlz** [comment]
I had this happen to me on Android 13 (pixel 7) after migrating from the pixel 6. The only way to fix it was to uninstall/reinstall bitwarden. Now it is working. My guess is that something doesn't transfer over correctly 🤷‍♂️
