### ISSUE TITLE
Android: App keeps asking to enable accessibility service even though the service is already on

### ISSUE THREAD

**Issue by ziffusion** [bitwarden/mobile#1341]
## Describe the Bug

When trying to use autofill from the Bitwarden tile in the Android Quick Settings menu, the application keeps asking to enable accessibility service even though the service is already on.

## Steps To Reproduce

1. Click on the Bitwarden tile in the Android Quick Settings pull down.

## Expected Result

1. The app should autofill the usename password fields on the page.

## Actual Result

1. The application displays an error message asking to enable the accessibility service even though the service is already on.

## Screenshots or Videos

![Screenshot_20210328-184633](https://user-images.githubusercontent.com/341389/112771076-f41a7200-8ff7-11eb-9a33-15d3d1dc9a5e.png)

![Screenshot_20210322-092525](https://user-images.githubusercontent.com/341389/112771077-f8df2600-8ff7-11eb-8473-7d6f84e3c06f.png)

![Screenshot_20210328-184000](https://user-images.githubusercontent.com/341389/112771082-01cff780-8ff8-11eb-8cbe-ee18b84f4fe1.png)

## Environment

- Device: Motorola One Fusion+
- Operating system: Android 10
- Build Version: 2.9.1 (3444)
- Is this a Beta release? N

**Comment by Lippiece** [comment]
Sorry for mentioning you, @mpbw2, but I don't see how https://github.com/bitwarden/mobile/pull/1556 is related to the issue.

Experiencing this on GrapheneOS on Pixel 6a. Reinstallation didn't help, as well as disabling any protections and battery optimisations.

Can I share any info that might help with debugging?
