### ISSUE TITLE
Android - Bitwarden is not offering to autofill any website through Firefox on EMUI 9.0.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#1342]
## Describe the Bug
Bitwarden does not offer to autofill any website through Firefox on a Huawei Mate 10 Pro device.

## Steps To Reproduce
1. Open your Firefox (87.0) browser.
2. Go to https://www.paypal.com/ and/or https://www.reddit.com/
3. Try to log in.

## Expected Result
To see the option to autofill when you tap on the email address field.

## Actual Result
No response from Bitwarden in Firefox.

## Screenshots or Videos
N/A.

## Environment
- Device: Huawei Mate 10 Pro.
- Operating system: Android 9.
- Build Version: 2.9.1 (3444).
- Is this a Beta release? N.

## Additional Context
Bitwarden offers to autofill those same 2 websites via Chrome on the same device, and also inside native applications.

**Comment by kaysond** [comment]
Subscribing.

This is related to: https://support.mozilla.org/en-US/questions/1328343 to which a moderator replied that it could be a compatibility issue with the new architecture of Firefox for Android.

Another symptom is that when Bitwarden is locked, and you are able to get into the autofill service menu, unlocking Bitwarden then selecting the correct password entry does not actually autofill the webpage form.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
