### ISSUE TITLE
Problem recognizing ip address?

### ISSUE THREAD

**Issue by Palf994** [bitwarden/mobile#135]
I have the password for my router configuration page saved in Bitwarden. When I access the page on a computer, Bitwarden recognizes the address (http://192.168.1.1) and will fill in the password normally. The iOS plugin for Chrome, however, doesn't list any logins for that page. This is the only entry I'm having this problem with on iOS. I've tried modifying the entry by removing the "https://", but that doesn't fix it, and in fact it prevents it from working on my computer. Anything else I could try?

Thanks

**Comment by kspearrin** [comment]
This bug is fixed in the next version of iOS. Thanks.
