### ISSUE TITLE
iOS - select and copy text does not work when viewing notes

### ISSUE THREAD

**Issue by kapitainsky** [bitwarden/mobile#1351]
When viewing notes it is not possible to use iOS copy text feature. In order to copy anything from note field it is required to enter edit more. The same applies to login item note field.

in iOS even when text is not editable e.g. content of some website in browser it is always possible to select and copy text but Bitwarden blocks it.

1. It does not follow platform behaviour
2. It is not very user friendly - lets say I have note where I store some codes. I open BW and want to copy one of them - in order to do this I have to start editing it and I can make mistake, delete something etc.

## Steps To Reproduce

view any note and try to copy text from note field - not possible to select anything
then enter edit mode and copy is possible

## Expected Result

Text field even in view mode should be selectable and allow copy. 

## Environment

- Device: various iPhones
- Operating system: iOS 14.4.2
- Build Version: 2.9.1 (544)
- Is this a Beta release? N

**Comment by prasad-4268** [comment]
This is 3 years later - when is this fix being deployed for Premium users?

For me it used to work perfectly until a few minutes ago. Now it is exhibiting this bug behavior by not allowing me to copy a word from notes in browse mode. Did my ios version get updated with the older version with the bug?

Hope someone from BitWarden replies....
