### ISSUE TITLE
PIN unlock broken on iOS

### ISSUE THREAD

**Issue by cyberfunk** [bitwarden/mobile#1352]
On iOS when selecting PIN for unlock the feature does not work at all except when testing it in the settings page. If you lock the app in Bitwarden settings it will prompt for PIN and not master password if you unlock the app. If you try to access Bitwarden anywhere else say on a website or when opening an app it prompts for the master password no exceptions. iOS 14.3 Bitwarden latest release. My master password is really long so typing it in repeatedly with accuracy and high frequency is madness.

**Comment by SergeantConfused** [comment]
Hi there,

Please disable your PIN, re-enable it, tap 'No' on the prompt that shows up, and let me know if that helps. More on this here: https://bitwarden.com/help/article/unlock-with-pin/

Thank you in advance,

**Comment by cyberfunk** [comment]
> Hi there,
> 
> Please disable your PIN, re-enable it, tap 'No' on the prompt that shows up, and let me know if that helps. More on this here: https://bitwarden.com/help/article/unlock-with-pin/
> 
> Thank you in advance,

That fixed it thanks! I bet I'm not the first one to make that mistake (I hope🤦‍♂️)

**Comment by SergeantConfused** [comment]
You're most welcome!
And do not worry about it, you're not! 😊
