### ISSUE TITLE
App does not fill password if authentication was required to open autofill

### ISSUE THREAD

**Issue by namansood** [bitwarden/mobile#1355]
## Describe the Bug
If I click a textbox and the autofill says I need to authenticate, after authenticating it does not fill the textfield, or show the autofill again.

## Steps To Reproduce
1. Wait for lock timeout to expire so the wallet is locked.
2. Open a login page (in my case, on Firefox Mobile at outlook.com).
3. When the autofill dropdown appears asking you to authenticate, click it, then authenticate (in my case with fingerprint).
4. A window opens listing the username/password combinations for that site. Click the one you want.

## Expected Result
Either the combination is filled in, or the autofill pops back up.

## Actual Result
I'm dropped back to the browser and nothing is filled in. Tapping the text field again does not bring up the autofill back.

## Environment

- Device: OnePlus 6T
- Operating system: Android 10
- Build Version: 2.9.1 (3444)
- Is this a Beta release? No

## Additional Context
In the case of a browser, if I press Back and then come back to the page with the login form _before_ the vault timeout expires again, the autofill appears as expected and fills the form. I tried to disable vault timeout as a temporary countermeasure, but that doesn't seem to help (vault times out anyway).

**Comment by SergeantConfused** [comment]
Hi there,

Thank you for bringing this to my attention. I'm able to reproduce this in Firefox 87 on Android 11, can you please let me know if you encounter this behaviour in Chrome?

I thank you in advance for your understanding and cooperation.

**Comment by namansood** [comment]
Hi! Chrome works as it should with no problems.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
