### ISSUE TITLE
Displayed as package name rather than URL

### ISSUE THREAD

**Issue by kjw3000** [bitwarden/mobile#1358]
## Describe the Bug

Hello. I am a Stargon browser developer. I received a user's inquiry and checked it. We have confirmed the problem of being set as the package name in Bitwarden. Hopefully this will be reflected in the next update.

https://play.google.com/store/apps/details?id=net.onecook.browser

## Steps To Reproduce

1. Go to any website and login.
2. Bitwarden Autofill notification appears.
3. Select the notification.
4. It shows net.onecook.browser instead of website

## Expected Result

The user login site url should appear.

## Actual Result

It shows net.onecook.browser on top

## Environment

I don't know exactly, but it seems to occur in most of the models.

**Comment by lloo07** [comment]
This issue doesn't seem to be resolved yet.
