### ISSUE TITLE
Autofill not working with firefox

### ISSUE THREAD

**Issue by hakkikaancaliskan** [bitwarden/mobile#1359]
## Describe the Bug
Both ime autofill and pop up autofill don't work most of the time (5% of the time it's working) on Firefox

## Steps To Reproduce
Go to any website with login (for me it's trendyol.com)
Tap to username or password field

## Expected Result

Autofill should shown on ime or via pop up 

## Actual Result

Nothing happens. I've checked permissions of bitwarden, no problem.

## Screenshots or Videos

This issue happens with bot ime and pop up autofill
https://user-images.githubusercontent.com/17825767/113778651-59c3d800-9735-11eb-8c09-5a40dd9f1301.mp4

I'm unable to take a screenshot of bitwarden autofill settings but first 2 (autofill general pref and ime autofill) prefs are turned on, last 2 are turned off.
## Environment

- Device: Xperia XZ1
- Operating system: LOS Android 11
- Build Version: 2.9.1
- Firefox version: 88 beta 4, it's also not working with release version, nightly looks kinda better
- Is this a Beta release? No.

**Comment by hakkikaancaliskan** [comment]
Autofilling other apps have no problem, just firefox.

**Comment by luximus-hunter** [comment]
are you using the extention or app on android? if youre using the extention, try the app. if youre using the app, make sure to check all its settings, like if the overlay permissions are set

**Comment by hakkikaancaliskan** [comment]
Extension works perfectly. Problem is on the app. I've uninstalled/installed,already gave all the permissions. Android's native autofill not working reliably with Bitwarden and firefox. I don't want to use accessibility service that running all the time.

**Comment by luximus-hunter** [comment]
is it possible that this firefox being weird instead of BitWarden?

**Comment by hakkikaancaliskan** [comment]
Of course possible but afaik other password managers are working fine, i think some kinda co-operation is needed for this issue, idk 🤷
A lot of people reporting this issue in reddit

**Comment by evilmango** [comment]
I'm able to consistently get the autofill menu to display with suggestions after using the "go to vault" autofill option. Behaviour seems to depend what type of input you trigger this from. 

In a username field, choose go to vault, pick a login and it will autofill those details into the form - then it will show the autofill menu with suggestions prefilled.

If you're in a password field and do the same thing it will autofill and show the menu again but with just the "go to vault" option.

**Comment by hakkikaancaliskan** [comment]
> I'm able to consistently get the autofill menu to display with suggestions after using the "go to vault" autofill option. Behaviour seems to depend what type of input you trigger this from. 
> 
> In a username field, choose go to vault, pick a login and it will autofill those details into the form - then it will show the autofill menu with suggestions prefilled.
> 
> If you're in a password field and do the same thing it will autofill and show the menu again but with just the "go to vault" option. 

That's accessibility services' behavior, not native autofill.

**Comment by evilmango** [comment]
OK, understand. I've disabled that and now most of the time I'm not seeing the menu at all. 

I've found now I am able to get it to appear about 50% of the time by opening the Firefox three dot menu, then tapping off the menu on the page (not closing the menu).

**Comment by evilmango** [comment]
Additionally, switching tabs stops this behaviour and it doesn't seem possible to trigger the menu until you refresh the page.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
