### ISSUE TITLE
Android app crash when trying to paste in Note field

### ISSUE THREAD

**Issue by MichaelDemeyer** [bitwarden/mobile#136]
On Android, in edit mode, when long pressing the "Note" field to display the "paste" popup action, the application force-close

**Comment by kspearrin** [comment]
Not able to reproduce on my Nexus 5X (android 8.0). Can you provide more information about your device?

**Comment by MichaelDemeyer** [comment]
Happen on my Samsung Galaxy S7 on Android 7.0. 
Reproduced with language FR_FR and EN_US, and two different keyboards (Swiftkey and samsung stock keyboard).

**Comment by kspearrin** [comment]
Does this still happen?

**Comment by MichaelDemeyer** [comment]
Not anymore. I think the bug can be closed.
