### ISSUE TITLE
Inoperative in Kiwi Browser

### ISSUE THREAD

**Issue by green1052** [bitwarden/mobile#1361]
## Steps To Reproduce

4. Click on '...'

## Screenshots or Videos

![Screenshot_20210407-155514_Kiwi Browser](https://user-images.githubusercontent.com/34261355/113823491-ae109b80-97b9-11eb-87b6-11a11c38be05.jpg)

## Environment

- Device: [S20+]
- Operating system: [Android 11]
- Build Version (go to "Settings" → "About" in the app): [2.9.2 (3460)]
- Is this a Beta release? [N]

**Comment by sso-bitwarden** [comment]
This is expected. Kiwi Browser doesn't support Android Auto-Fill API nor Accessibility Service.
Fortunately, they support Chrome Extension and you can install our Chrome extension and enable On Page Load Autofill.

**Comment by green1052** [comment]
thx
