### ISSUE TITLE
Autofill Lag iOS 14

### ISSUE THREAD

**Issue by TheNotSoShiftySEO** [bitwarden/mobile#1368]
## Describe the Bug
AutoFill passwords lags for 30 seconds after pressing the key button. It also lags when you attempt to change AutoFill Passwords in the "Settings" app.

## Steps To Reproduce

1. Go to Safari or any app
2. Click on the key icon when attempting to login to an account. 

## Expected Result

There should be no lag.

## Actual Result

There's a 30 second delay

## Environment

- Device: iPhone 12 Pro
- Operating system: 14.4.2 (18D70)
- Is this a Beta release? N

**Comment by Greenderella** [comment]
Hi @TheNotSoShiftySEO 

I'm unable to reproduce this issue on iOS 14.4.2. Will you first try uninstalling the application, resetting your device (Power Off/On) and re-installing? Does this issue still persist?

Let me know if that helps.

**Comment by TheNotSoShiftySEO** [comment]
Hi Alex,

After some testing it looks like this is an iCloud glitch causing this issue. This can be closed.
