### ISSUE TITLE
iOS shows passwords in Vault even though I deleted both my Vault and my account

### ISSUE THREAD

**Issue by chvillanuevap** [bitwarden/mobile#1369]
## Describe the Bug

After deleting my Vault and account on Bitwarden.com, I can still log into the iOS app using FaceID, and see all of my passwords there.

## Steps To Reproduce

1. I created a Bitwarden account and imported my passwords from Google Chrome.
2. Later, I installed the iOS app and logged in on my iPhone XS running 14.4.2. I also set up FaceID.
3. I deleted my Vault on the Bitwarden.com website, and then I deleted my account.
4. My iOS app still logs me in (using FaceID), and still has all of my passwords there.

## Expected Result

Passwords on iOS app should have been deleted along with my FaceID login capability.

## Actual Result

Even though I deleted my Vault AND my account on Bitwarden.com, the app on iOS still logs me in using FaceID and still shows all of my passwords.

Is this data deleted if I remove the app?

## Environment

- Device: iPhone XS
- Operating system: 14.4.2
- Build Version (go to "Settings" → "About" in the app): 2.9.1 (544)
- Is this a Beta release? N

**Comment by Nihal247** [comment]
Hi @chvillanuevap and thank you for your patience.

Make sure you really deleted your account. You can visit the https://vault.bitwarden.com website to check for it.

Thank you in advance.

**Comment by chvillanuevap** [comment]
I'm pretty sure it was closed. I'm closing this issue anyway since I'm no longer using Bitwarden.
