### ISSUE TITLE
entitlement issue xamarin build iOS

### ISSUE THREAD

**Issue by petervnv** [bitwarden/mobile#137]
Hi,

I'm trying to compile the iOS app to test it out and I'm having trouble with the xamarin solution no matter what I try.
I'm able to compile the app but when it's being run on the iPhone visual studio/xamarin complains about wrong provisioning/entitlements.

I've changed the BundleID in iOS plist to net.company.my and in iOS.Extension to net.company.my.find-login-action-extension, I've created 2 new AppIDs in the Developer Console with those 2 BundleIDs, I've created the App Group group.net.company.my and both those AppIDs have that group assigned in their entitlements. 
Both AppID's have enabled the following 4 entitlements: 
App Groups (with group.net.company.my), Game Center, iCloud and In-App Purchase.

I let xamarin generate my provisioning profiles and everything seems to compile fine until it deploys the ipa to the iPhone. where I get this error:

"Your code signing/provisioning profiles are not correctly configured. Probably you have an entitlement not supported by your current provisioning profile, or your device is not part of the current provisioning profile. Please check the iOS Device Log for details (error: 0xe8008016).

Application could not be uploaded to the device."

I must be doing something wrong but I cannot figure out what it is.

Can anyone help?

Cheers

**Comment by kspearrin** [comment]
Welcome to Xamarin configuration hell. It's quite annoying.

Here's what my entitlements look like in the corresponding xcode project:

**Comment by artur** [comment]
@kspearrin i'm having the same problem and replicated the entitlements, but when uploading to the device it gives me the following error:

 on the device 'Artur's iPhone': Your code signing/provisioning profiles are not correctly configured. Probably you have an entitlement not supported by your current provisioning profile, or your device is not part of the current provisioning profile. Please check the iOS Device Log for details (error: 0xe8008016).

This is kinda frustrating because it doesn't say which entitlement item is not there.
Can you help me here ?
Thanks!

**Comment by kspearrin** [comment]
I'm not really sure. I'm happy to provide whatever you need to see form my configuration but without seeing what you have I don't really know what else to try.

A few more screenshots of my xcode:

Vault app:

![screen shot 2017-09-26 at 7 45 52 am](https://user-images.githubusercontent.com/1190944/30872079-ed4cafe2-a2b6-11e7-8d16-9bb88807da83.png)
![screen shot 2017-09-26 at 12 28 49 pm](https://user-images.githubusercontent.com/1190944/30872078-ed4b735c-a2b6-11e7-91c3-9cf2ce1850c9.png)
![screen shot 2017-09-26 at 12 28 57 pm](https://user-images.githubusercontent.com/1190944/30872077-ed48e704-a2b6-11e7-96fd-67597a33fd09.png)
![screen shot 2017-09-26 at 12 29 18 pm](https://user-images.githubusercontent.com/1190944/30872082-efc93f38-a2b6-11e7-8baa-cf2227691124.png)

Extension app:

![screen shot 2017-09-26 at 12 29 36 pm](https://user-images.githubusercontent.com/1190944/30872090-f4b2850e-a2b6-11e7-9aaf-56f0056b834e.png)
![screen shot 2017-09-26 at 12 29 47 pm](https://user-images.githubusercontent.com/1190944/30872092-f4c318ba-a2b6-11e7-9d94-b7f6eda3088b.png)
![screen shot 2017-09-26 at 12 29 55 pm](https://user-images.githubusercontent.com/1190944/30872091-f4c248f4-a2b6-11e7-9cb3-1a7f29c52049.png)
![screen shot 2017-09-26 at 12 34 43 pm](https://user-images.githubusercontent.com/1190944/30872150-1d7d469a-a2b7-11e7-9802-b66eb3b1037b.png)


Please let me know if you figure it out.

**Comment by kspearrin** [comment]
Make sure you launch your xcode app on your device and that it works there.

**Comment by kspearrin** [comment]
In VS, you can also right click the iOS projects and go to Properties -> iOS Bundle Signing to ensure it uses the correct identity/profile, etc. Mine are set to automatic through.

**Comment by artur** [comment]
@kspearrin thanks for the explanation.

I think I know what am I doing wrong, i'm trying to deploy right from Xamarin/Visual Studio, without going through any xcode project.

Now the newbie question, do I need to create a xcode project for this ?

**Comment by kspearrin** [comment]
There has to be a corresponding xcode project that has your provisioning profiles and entitlements all set up. There's info in Xamarin docs which you should read. I'd start with a simple test project first to make sure you are up and running fine before trying bitwarden.

**Comment by artur** [comment]
@kspearrin i just made the xcode project, replicated the entitlements, run the application everything fine.
But then I go to the Xamarin project and same error, and confirmed the profiles.
How can I debug this further ?

**Comment by kspearrin** [comment]
Sorry, I'm not sure. I'd try getting a simple test project like I suggested working first.

**Comment by artur** [comment]
@kspearrin do you have test project that you can share ? because either i'm doing something wrong on the xcode extension target or something else is misconfigured ??

**Comment by artur** [comment]
@kspearrin solved it! Was forgetting to add my macbook's certificate to the development profile created for this!

Thanks for the help!

**Comment by petervnv** [comment]
I finally got it working too!
Thanks to both of you.

By the way, I tried pointing the BaseAddress in src/App/Utilities/ApiHttpClient.cs to https://vault.my.domain to test out self-hosting but it still tries to login to the bitwarden service by default.
Am I looking in the wrong place to change the destination?

**Comment by kspearrin** [comment]
You also need to change it in IdentityHttpClient.cs, or just change the environment on the login page of the app.
