### ISSUE TITLE
After fingerprint unlock have to redo auto fill before it works.

### ISSUE THREAD

**Issue by asislife20** [bitwarden/mobile#1371]
## Describe the Bug

 After tapping auto fill it asks for fingerprint once unlocked it goes back to the page without filing in the auto fill data. You have to try a second time with it already unlocked to get data to auto fill.

## Steps To Reproduce

How can we reproduce the behavior:
Try to auto fill while locked, input fingerprint bit warden closes without filing, then click auto fill again and it works

## Expected Result
Put in fingerprint bit warden auto fills info

## Actual Result

Put in fingerprint bitwarden closes without filing info

## Environment

- Device: [Nubia Red Magic 5G]
- Operating system: [Android 10]
- Build Version (go to "Settings" → "About" in the app): [2.9.1]
- Is this a Beta release? [N]

**Comment by SergeantConfused** [comment]
Hi there,

I'm unable to reproduce this on 2 devices with Chrome running Android 11. I open a login page, click on the email address field, tap on the Accessibility service's banner or use In-line autofill, and then my credentials get entered right after I unlock Bitwarden using my fingerprint the first time. What browser are you using, please?


Thank you in advance,

**Comment by asislife20** [comment]
I'm using firefox on Android. If it would help I can try to send you a video of the issue. It's not a huge deal, I can definitely live with it, I just wanted to let you know in case others are having the same issue. Thanks, have a great weekend!

⁣Get BlueMail for Android ​

**Comment by asislife20** [comment]
I figured out if I have the main android autofill service enabled it did this,  but only using the accessibility service and enabling draw over this doesn't occur. I'm thinking this is more of a device specific android issue. I'm closing the issue since I was ableto get it working correctly. Thanks.
