### ISSUE TITLE
No autofill on privacy.com

### ISSUE THREAD

**Issue by makitso** [bitwarden/mobile#1373]
Android tablet 7.1.2
Save privacy.com login page to desktop shortcut -- saves as web app.
Click on  shortcut opens privacy.com web site.  Can not get BitWarden to populate username or password.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by Krychaz** [comment]
Hi, 

Would you be able to add any other site as desktop shortcut and see if it will populate the username & password?

**Comment by makitso** [comment]
Yes, other shortcuts work both as website apps and normal shortcuts.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
