### ISSUE TITLE
Credentials aren't entered and auto-fill overlay doesn't appear after unlocking vault

### ISSUE THREAD

**Issue by E66666666** [bitwarden/mobile#1379]
## Describe the Bug

The auto-fill overlay does not appear after unlocking the vault. A page refresh is needed to have the auto-fill service overlay appear again.

## Steps To Reproduce

1. Lock the vault.
2. Go to any page with a login.
3. Tap on one of the fields. The "Auto-fill with Bitwarden / Vault is locked" overlay appears.
4. Tap on the overlay and unlock the vault by either password or biometrics.
5. (Optional?) Tap on the found login credentials inside the Bitwarden app.
6. The Bitwarden app returns to the browser. No credentials are actually entered.
7. Tap again on one of the fields. No overlay appears.
8. Refresh the page.
9. Tap on the fields again. The overlay finally appears, and a login can be selected.

## Expected Result

In step 6, I would expect the login credentials to have been entered after the Bitwarden app returns.

If not possible, I would expect the auto-fill overlay to appear when tapping one of the fields.

## Actual Result

After authenticating and selecting a set of login credentials, none are actually entered.

When returned to the login page, no auto-fill overlay appears when tapping on one of the fields.

A refresh of the page is required to get the auto-fill overlay to appear when tapping on one of the fields.

## Screenshots or Videos

[Video on YouTube](https://www.youtube.com/watch?v=pKH7WFNaSpU)

The recording is censored by Android during steps 4 -> 5 -> 6.

## Environment

- Device: Google Pixel 4a 5G
- Operating system: Android 11
- Build Version: 2.9.1 (3444)
- Is this a Beta release? No

## Additional Context

- Browser: Firefox Nightly, latest version (Nightly 210417 17:00, build #2015805195)

Has happened ever since I switched from Lockwise to Bitwarden though, Lockwise did not have this specific issue.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites and apps, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
