### ISSUE TITLE
Android - No autofill on airbnb app

### ISSUE THREAD

**Issue by Krychaz** [bitwarden/mobile#1387]
## Describe the Bug

Bitwarden autofill is not working with the official airbnb app on Android (11) 

## Steps To Reproduce

1. Download the official AirBnB app from Google Playstore 
2. In the bitwarden app, create a credentials for airbnb with this URI: com.airbnb.android 
3. Go to your airbnb app, click on login
4. Try to autofill

## Expected Result

A bitwarden popup will ask to autofill the fields 
## Actual Result

No autofill option is presented, even doing long press -> autofill doesn't prompt the airbnb credentials 

## Environment

- Device: [OnePlus Nord & OnePlus 9]
- Operating system: [Android Oxygen 11]
- Build Version:2.9.1(3444)
- Is this a Beta release? [N]

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites and apps, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
