### ISSUE TITLE
Password is filled instead of username on mobile Gmail login page.

### ISSUE THREAD

**Issue by uOOOO** [bitwarden/mobile#1388]
## Describe the Bug

Password is filled instead of username to username input form in mobile Gmail login page.

This is not reproduced in desktop Chrome but mobile Chrome.

## Steps To Reproduce

1. Open Chrome on desktop
2. Go to desktop Gmail web login page.
3. Add credentials to Bitwarden.
4. Make sure autofill works on desktop Chrome browser.
5. Open Chrome on Android device.
6. Go to mobile Gmail login page.
7. Click username input form and then click the autofill item was added previous steps.

## Expected Result
Filled username instead of password.

## Actual Result
Filled password instead of username.

## Environment

- Device: Xiaomi Redmi Note 5 Pro, Samsung Galaxy A50
- Operating system: Android 9, Android 11
- Build Version (go to "Settings" → "About" in the app): 2.9.1 (3444)
- Is this a Beta release? N
- Chrome Version : 90.0.4430.91

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites and apps, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
