### ISSUE TITLE
Overlay showing in andOTP after declining to save password

### ISSUE THREAD

**Issue by MattiasC** [bitwarden/mobile#1392]
## Describe the Bug
The overlay is showing in the middle of the screen and covering items in andOTP.

## Steps To Reproduce
1. Open andOTP which is configured with a PIN code
2. The overlay to automatically fill the PIN code is shown (but I do not use it)
3. Enter the PIN code for andOTP
4. Select "No thanks" in the "Do you want to save the password in Bitwarden?" dialog which is shown on the bottom of the screen (Might be phrased a bit differently since mine is in Swedish)
5. The bottom dialog closes and the overlay that was shown when entering the PIN code is shown again at the same place on the screen as it did the first time

## Expected Result
All Bitwarden dialogs and overlays should be closed.

## Actual Result
The auto fill overlay is shown again.

## Screenshots or Videos
![bitwarden-andotp](https://user-images.githubusercontent.com/25339604/116866683-211bff00-ac0c-11eb-8f59-864df06dd8c6.png)

## Environment

- Device: Pixel 3a
- Operating system: Android 11
- Build Version: 2.9.1 (3444)
- Is this a Beta release? N

## Additional Context
(I have not filmed it since I don't want my accounts to be shown publicly.

**Comment by Greenderella** [comment]
Hi @MattiasC,

You may want to try blacklisting andOTP's autofill capabilities. More information here: https://bitwarden.com/help/article/blacklisting-uris/

**Comment by eliykat** [comment]
Hi @MattiasC, please try @Greenderella's suggestion, and feel free to contact us if you need further help. You can contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content.

In the meantime, I'll close this issue. Thanks!
