### ISSUE TITLE
Bitwarden Mobile auto-fill doesn't parse the website URL correctly for MS Edge Dev

### ISSUE THREAD

**Issue by fabis94** [bitwarden/mobile#1393]
## Describe the Bug

MS Edge has a Canary and a Dev version available on Android (possibly iOS as well), and Bitwarden doesn't integrate with it well, because whichever site you trigger auto-fill from, the Bitwarden app doesn't take the Edge website URL into account and instead looks for items for "com.microsoft.emmx.dev".

## Steps To Reproduce

1. Download MS Edge Dev on Android
2. Go to netflix.com
3. Trigger the auto-fill from the login page

## Expected Result

The auto-fill should launch Bitwarden correctly so that it looks for items relevant to the page open in Edge

## Actual Result

The auto-fill will launch Bitwarden and look for items for "com.microsoft.emmx.dev"

## Screenshots or Videos

"Can't screenshot due to security policy"

## Environment

- Device: Galaxy S21 Ultra
- Operating system: Android 11
- Build Version (go to "Settings" → "About" in the app): 2.9.1 (3444)
- Is this a Beta release? [Y/N] No

## Additional Context

I've no idea, but I assume this happens because BitWarden isn't configured to understand that "com.microsoft.emmx.dev" is actually a web browser

**Comment by djsmith85** [comment]
Hi @fabis94 , thank you for reporting. I think this was implemented with #1370 and will be included in the next release.

**Comment by fabis94** [comment]
Ok thanks!

**Comment by djsmith85** [comment]
@fabis94 Glad I could help. Could you please close the issue. It saves the Devs from going through solved issues.
