### ISSUE TITLE
Unable auto fill CITI mobile app

### ISSUE THREAD

**Issue by jegannathanmaniganadan** [bitwarden/mobile#1398]
I could not auto fill citi mobile app using bitwarden on my apple device. Is this expected ? Let me know if there is any additional information needed.

**Comment by eliykat** [comment]
I'm not sure about the specific app, but you can report any autofill issues in the issue below. This helps us collate all these reports and improve our overall functionality, without cluttering up Github. Thanks!

---

Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
