### ISSUE TITLE
Incorrect French translation "MatchingItems"

### ISSUE THREAD

**Issue by tnakrev** [bitwarden/mobile#1400]
In Android mobile app, the item "MatchingItems" is incorrectly translated in French. It should be : "Élements correspondants" instead of "Aucun élément correspondant".

**Comment by cscharf** [comment]
Please feel free to contribute a fix in Crowdin. https://crowdin.com/translate/bitwarden-mobile/45/en-fr?filter=basic&value=0#q=MatchingItems

**Comment by cscharf** [comment]
Oh, and thank you for reporting it!
