### ISSUE TITLE
No autofill popup is displayed in Twitch app on Android

### ISSUE THREAD

**Issue by humleflue** [bitwarden/mobile#1415]
## Describe the Bug

The small Bitwarden popup doesn't display on the official Twitch app's login screen, which means that I'm unable to autofill. 

## Steps To Reproduce

1. Open the Twitch app for the first time. 
2. Press the Log In button

## Expected Result

I expect a popup box to appear enabling me to autofill the username and password. 

## Actual Result

No popup is displayed. 

## Screenshots or Videos

Unfortunately the Twitch app does not allow me to record nor screenshot. 

## Environment

- Device: OnePlus 5T
- Operating system: Android 10, OxygenOS 10.0.1
- Build Version: OnePlus A5010_43_201029
- Is this a Beta release? N

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
