### ISSUE TITLE
Inconsistent placement of the "use another method" button in the 2FA authentication screen

### ISSUE THREAD

**Issue by ghost** [bitwarden/mobile#1419]
## Describe the Bug
When logging in Bitwarden, the "log in" button is located at the bottom, but in the next screen, the "use another method" button is in the same place of the "log in" button, instead of the "continue" button. If you accidentally press the "use another method" button and press back, the whole process will be canceled. This inconsistency creates a non-intuitive design.

## Steps To Reproduce
1. Log in with your credentials (2FA must be enabled).

## Expected Result
The continue button should be at the bottom.

## Actual Result
N/A

## Screenshots or Videos
N/A

## Environment
- Device: A50
- Operating system: Android 11
- Build Version (go to "Settings" → "About" in the app): 2.10.0 (3516)
- Is this a Beta release? no

## Additional Context
N/A

**Comment by eliykat** [comment]
I agree, I moved the log in buttons in #1073 but didn't extend the changes to the 2FA screen. If anyone would like to tackle it they're welcome, otherwise I'll put it on the to-do list.
