### ISSUE TITLE
Sometimes "Verify PIN" does not automatically bring up keyboard

### ISSUE THREAD

**Issue by ElTopo** [bitwarden/mobile#142]
bitwarden for android: 1.11.0(974)
android version: Lollipop 5.1.1

Sometimes when I open bitwarden and am at "Verify PIN" screen, the on-screen keyboard is not present for PIN input. Tapping on the PIN area once does not bring up the keyboard either (I guess the app thinks this tap is for turning off keyboard). After I tap the PIN area the second time the keyboard does not show up.

This is a little bit inconvenient. When I am at "Verify PIN" screen generally I want to input PIN, or use Back button to cancel/leave bitwarden, it does not make much sense to turn off keyboard at this point.

I hope bitwarden works like authy does:
https://play.google.com/store/apps/details?id=com.authy.authy
(by the way, authy always brings up the keyboard at its PIN screen).

Can you make sure the keyboard is always present at this screen?

**Comment by kspearrin** [comment]
Thanks. We're aware of this problem. We've been trying to fix this for a while now.

**Comment by kspearrin** [comment]
Merging with #149
