### ISSUE TITLE
Using the Password Leak Checkmark button in the iOS app while language set to Russian doesn't produce a numeric value properly ($VALUE$)

### ISSUE THREAD

**Issue by aj-bw** [bitwarden/mobile#1420]
## Describe the Bug

When opening Bitwarden app, selecting any login item, selecting edit, pressing the checkmark beside the password field, it produces a prompt that says "The password has been exposed XnumberX time(s) in data breaches. You should change it.

Doing this while your iPhone is set to Russian language, where it should produce a number, it just says "$VALUE$ )

## Steps To Reproduce

Set your iPhone language to russian
Open BW app
select vault item ( it can be a vault item with a breached password or without. it happens on either )
select edit
select check mark

## Expected Result

produce a prompt with an numerical value of times it has been leaked

## Actual Result

produces the prompt but with a variable name $VALUE$ instead of a numerical value

## Screenshots or Videos

![2021-06-08_15-58-25](https://user-images.githubusercontent.com/81774843/121200709-f132cd80-c841-11eb-9410-ba3f5abf93ee.jpg)

## Environment

- Device: iPhone Xs
- Operating system: iOS 14.5 and 14.6
- Build Version (go to "Settings" → "About" in the app): 2.10.0 (616)
- Is this a Beta release? N

## Additional Context

verified on multiple iOS devices

**Comment by djsmith85** [comment]
Hi @aj-bw this is a translation error. The translations for Bitwarden are done via Crowdin. I've found the problematic text and it seems that it's not using ´{0}` as a variable placeholder but instead ´$VALUE$` which doesn't get replaced. 

Here's a link to the respective translation: https://crowdin.com/translate/bitwarden-mobile/45/en-ru?filter=basic&value=3#q=expose

As I am not a Russian speaker, please add a correct or vote for an existing translation which includes `{0}´ as a placeholder.

Kind Regards,

Daniel

**Comment by eliykat** [comment]
Good pick up @djsmith85. @aj-bw, I'd really appreciate it if you could help us out by fixing the translation in CrowdIn. If not, please confirm that the placeholder is in the correct place, maybe I can change it without needing to know any Russian. ;)

**Comment by djsmith85** [comment]
Closing this, as the translation got fixed. https://crowdin.com/translate/bitwarden-mobile/45/en-ru#3356
