### ISSUE TITLE
Tapping vault item not working

### ISSUE THREAD

**Issue by larena1** [bitwarden/mobile#1424]
## Describe the Bug
When searching in the vault and then tapping any of the found items, it will neither open that item nor offer to autofill that as it used to before. Is that intended or maybe just a regression caused by migrating stuff to collectionview in one of @mportune-bw's recent commits or so? 

## Steps To Reproduce
Search in the vault, tap any found item

4. Click on '...'

## Environment

- Device: [e.g. iPhone6] android
- Operating system: [e.g. iOS 8.1] 10
- Build Version (go to "Settings" → "About" in the app): [e.g. 2.3.0 (2221)] latest
- Is this a Beta release? [Y/N] no

**Comment by kendratodd** [comment]
Thank you for the report @larena1! We actually had an internal ticket for this as well, and it has just been fixed by this PR: https://github.com/bitwarden/mobile/pull/1426. 

This should go out in the next release (2.11) , so I'm going to close this out for now. Thanks again!
