### ISSUE TITLE
[Feature request] Add URI icons

### ISSUE THREAD

**Issue by unpeudetout** [bitwarden/mobile#143]
I think we could add icons to the left of items in the vault from the URI registered. It would allow a better readability, and identify faster the item we want. I don't know if you see what I mean

We "just" have to get the favicon of the website and save it in a file or a cache (or something like that).

We could also implement it into the web version and the extension.

**Comment by kspearrin** [comment]
related https://github.com/bitwarden/browser/pull/285

**Comment by kspearrin** [comment]
done for next release

**Comment by unpeudetout** [comment]
Thanks a lot !
