### ISSUE TITLE
No longer able to autofill credentials from search results

### ISSUE THREAD

**Issue by hmnd** [bitwarden/mobile#1438]
## Describe the Bug

Android app no longer able to autofill from search results.

## Steps To Reproduce

1. Open autofill for a site.
2. Search for credentials in the autofill popup.
3. Tap a credential or tap the kebab menu > view next to a credential.

## Expected Result

If the credential itself is tapped, the user is prompted to autofill or autofill and save.
If the credential is viewed, options to autofill, and autofill and save are presented at the bottom of the page.

## Actual Result

No options to autofill are presented.

## Environment

- Device: Pixel 5
- Operating system: Android 12
- Build Version: 2.10.1 (3546)
- Is this a Beta release? Y

## Additional Context

I remember that a month or two ago, the option to autofill from the 'view' page was added in addition to autofilling by tapping on search results. Seems that both are now gone.

**Comment by SinTan1729** [comment]
Same is happening in OnePlus Nord CE 5G (Android 11).

**Comment by giteke** [comment]
Same issue

- Device: Pixel 4 XL
- OS: Android 12
- Build Version: 2.10.1 (3546)

**Comment by Snuupy** [comment]
+1

Device: Pixel 4a
OS: Android 11
Build: 2.10.1 (3546)

**Comment by Snuupy** [comment]
Downgraded to 2.10.0 (3516) and was able to get it working again.

**Comment by giteke** [comment]
> Downgraded to 2.10.0 (3516) and was able to get it working again.

Worked for me as well

**Comment by j7e** [comment]
+1 for me

Device: Samsung A40 
OS: Android 11
Build: 2.10.1

Additional info: as well as being unable to autofill from search, I'm unable to open and view items from search within the app. To open and view an item, I have to manually scroll through my vault to find it.

**Comment by mportune-bw** [comment]
Thanks everyone for the info.  Build 3585 is live in the beta channel, please give it a try and see if autofill works for you again.

**Comment by hmnd** [comment]
@mportune-bw Looks like it works correctly now. Thanks!

**Comment by mportune-bw** [comment]
@hmnd Great to hear, thanks for the confirmation!
