### ISSUE TITLE
Doesn’t work on iOS email apps

### ISSUE THREAD

**Issue by bpsib** [bitwarden/mobile#1450]
## Describe the Bug

The passwords option doesn’t show up on email apps in iOS. I have tried both the iOS Mail app and the Outlook app.

## Steps To Reproduce
Open an email app such as the iOS Mail app

1. Go to 'Mail'
2. Click on 'Outlook.com' (or any other email provider)

## Expected Result
The passwords option should show on the keyboard

## Actual Result
There’s no passwords option

## Screenshots or Videos
![EC748F76-5192-4DEF-A0FD-DBB3149C4DCB](https://user-images.githubusercontent.com/5899155/124309287-67390480-db62-11eb-911e-3451ae5e2c75.png)

## Environment

- Device: iPhone XR
- Operating system: iOS 14.6
- Is this a Beta release? N

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
