### ISSUE TITLE
Not working when signing in with Google on Samsung browser beta

### ISSUE THREAD

**Issue by sH1222J** [bitwarden/mobile#1456]
## Describe the Bug

Not working when signing in with Google on Samsung browser beta

## Steps To Reproduce

1.x
2.x
3.x
4.x

4. Click on '...'

## Expected Result

Normally, auto-completion services or inline auto-completion should work.
It doesn't work.
There are times when low probabilities work, but rarely.
![Screenshot_20210711-144424_Samsung Internet Beta](https://user-images.githubusercontent.com/28824568/125184502-591d6f00-e259-11eb-9c6d-5920adb9e98d.jpg)

...

## Actual Result

 Attached is the photo.

## Environment

- Device: [e.g. iPhone6] 갤럭시s10e sm-g9700

- Operating system: [e.g. iOS 8.1] 
Android 11 / oueui 3.1 / Kernel Version 4.14.190-21607573
Samsung Browser Beta 14.2.1.69
bitwarden 2.10.1
BITWARDEN 2.10.1
- Build Version (go to "Settings" → "About" in the app): [e.g. 2.3.0 (2221)
RP1A.200721.012.G9700ZHS5FUE4

- Is this a Beta release? [Y/N] N

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
