### ISSUE TITLE
Mobile App crashes after enabling orgarnizations

### ISSUE THREAD

**Issue by zigapovhe** [bitwarden/mobile#1457]
The moment since I enabled organizations on web app, the mobile app do not even open. It crashes instantly after trying to auto-fill text fields, or open app via app drawer on my Pixel 3XL (Android 10). Worked before as charm. Does anyone else face the same issue? 

And yes, I'm using the latest mobile app version.

**Comment by mportune-bw** [comment]
Thanks for the report @zigapovhe , are you by chance using the beta (build 3585)?

**Comment by zigapovhe** [comment]
@mportune-bw I can confirm that crash is indeed fixed on latest beta version. Works as expected. Thanks!
