### ISSUE TITLE
"Cancel" is no good word for "Back"

### ISSUE THREAD

**Issue by CodingMarkus** [bitwarden/mobile#146]
The word "Cancel" always implies, that an action is not performed or that an already performed action is undone. See this screenshot:

![img_2634](https://user-images.githubusercontent.com/26418089/31546722-c5b0513e-b024-11e7-8be0-e77277d8ebe4.PNG)

The word "Cancel" in the upper left  makes me believe, that any changes I made there won't be stored. In fact, the correct word here would be "Back" or even better, using the iOS back arrow that Apple uses in their interfaces:

![img_2635](https://user-images.githubusercontent.com/26418089/31546767-0aa79a40-b025-11e7-8c83-21595c14201a.PNG)

bitwarden 1.11.1 (21) on iOS 11.0.3

**Comment by kspearrin** [comment]
You are correct. We should use "Close" here like we do on other modals.

**Comment by CodingMarkus** [comment]
"About" screen is also saying "Cancel". Well, you cannot change anything there but using the same keywords everywhere is probably best for users to understand.

**Comment by kspearrin** [comment]
Fixed for next release. https://github.com/bitwarden/mobile/commit/37f05f0a120ab1c286db84d908d2593c9ca39e67

Thanks!
