### ISSUE TITLE
Android erratic vault locking 

### ISSUE THREAD

**Issue by rsngfrce** [bitwarden/mobile#1460]
## Describe the Bug

Bitwarden vault is erratic at locking. I have it set to lock after 15 minutes and sometimes find it unlocked after hours. This behavior is strangly erratic as well. When logging in here, the vault was unlocked when it shouldn't have been for my user ID, but then required to be unlocked for my password (I have been experiencing this same behavior elsewhere as well). I seem to get an odd jumping between apps/pages when this happens as well, which is difficult to describe, but often results in requiring me to start over. 

I originally had this issue, or a similar one, reported in "Android - Bitwarden does not lock after the Vault Timeout duration passes. #1196" but have only recently been noticing it again after it was fixed there. 

## Steps To Reproduce

Bitwarden set to lock after 15 minutes, unlock with pin. 

## Expected Result

Vault should lock after 15 minutes of inactivity

## Actual Result

Erratically, vault is not locking. 

## Environment

- Device:  Samsung Galaxy S10e 
- Operating system: Android 11
- Build Version (go to "Settings" → "About" in the app): Version: 2.10.1 (3585)
- Is this a Beta release? [Y/N] N

**Comment by mportune-bw** [comment]
@rsngfrce This is fixed in the current beta, and we're hoping to get it into production this week.
