### ISSUE TITLE
Unable to log in using SSO

### ISSUE THREAD

**Issue by LeGEC** [bitwarden/mobile#1474]
## Describe the Bug

Trying to log in from the android app through "Enterprise Single Sign-On" fails

## Steps To Reproduce

1. launch the app, log out if necessary
2. click the "Enterprise Single Sign-On" button
3. enter credentials

## Expected Result

succesful login

## Actual Result

a dialog box appears saying "Currently unable to login with SSO"

## Environment

seen on Android phone, bug found in the Core module in the source code (so should affect all mobile platform)

**Comment by cscharf** [comment]
Thank you @LeGEC , our QA team is validating now and we'll get that PR merged for testing shortly if we're able to reproduce (which I'm sure we will be). The RCA and PR is much appreciated!

**Comment by cscharf** [comment]
We've validated this is an issue on iOS, working on Android reproduction now. Fix has been merged and will be validated soon.

**Comment by g1forfun** [comment]
Hi cscharf, any ETA on when this fix will be implemented on the iOS application? With SSO login, Android works fine for our users, but iOS does not.

**Comment by cscharf** [comment]
Hi @g1forfun , the fix for iOS is currently in Beta and we'll be working to get that into review with Apple shortly.

**Comment by g1forfun** [comment]
> 
> 
> Hi @g1forfun , the fix for iOS is currently in Beta and we'll be working to get that into review with Apple shortly.

You the man, thank you sir!
