### ISSUE TITLE
autofill works on second attempt on android 10

### ISSUE THREAD

**Issue by ruzko** [bitwarden/mobile#1478]
## Describe the Bug
autofill credentials on any website or app works only on second attempt.

## Steps To Reproduce

1. Go to any website or app
2. Click on relevant item in vault for autofill
3. Bitwarden then switches out of view, but no credentials are being autofilled.
4. Repeat steps 2 and 3 within a reasonable timeframe, and succeed at autofilling.

## Expected Result
Bitwarden autofills credentials properly the first time it is asked to do so.

## Actual Result
Bitwarden autofills credentials the second time it is asked to do so.

## Environment

- Device: motorola moto g8 plus
- Operating system: android 10
- Build Version: (of BW or android?) BW Versjon: 2.11.1 (3605)
- Is this a Beta release? [N]

**Comment by SergeantConfused** [comment]
Hi @ruzko,

If this is happening on all applications and all sites through all browsers, I recommend you start with a fresh installation. Please uninstall Bitwarden off your Android device, turn your device off and back on, reinstall Bitwarden from the Google Play Store, activate all your autofill services like so: https://bitwarden.com/help/article/auto-fill-android/ and test that again.
If you continue to encounter this behaviour, please get in touch with us using this form: https://bitwarden.com/contact/ so we would continue troubleshooting this, as I am unable to reproduce this behaviour.

Thank you in advance,
