### ISSUE TITLE
encryptionexport  licensing iOS?

### ISSUE THREAD

**Issue by petervnv** [bitwarden/mobile#148]
Hi,
I noticed in the info.plist file that you marked the app as needing export compliance docs from the BIS:

<key>ITSAppUsesNonExemptEncryption</key>
<true/>

However, you state on the website that bitwarden uses only CommonCrypto API in iOS https://help.bitwarden.com/article/what-encryption-is-used/

According to recent changes in Apple and US policy, if you're only using iOS crypto than your app qualifies now as exempt. https://stackoverflow.com/questions/2135081/does-my-application-contain-encryption/40391664#40391664

So my question is why the export compliance key in info.plist? Does bitwarden use anything more than CommonCrypto in the iOS app?

Cheers,
Peter

**Comment by kspearrin** [comment]
We weren't aware of the policy change. We only use CommonCrypto so I suppose we can remove this. When we first launched the app last, this wasn't the case. We'll look into it more.

**Comment by kspearrin** [comment]
I found the following docs when attempting to contact apple support about this:

![screen shot 2017-10-14 at 11 35 27 am](https://user-images.githubusercontent.com/1190944/31576954-e6d9d9f2-b0d3-11e7-8b37-4ec104177059.png)

Seems we still need it?

**Comment by petervnv** [comment]
Hmm, yeah that's pretty confusing and seems to contradict the info on stackoverflow. Welcome to bureaucracy hell.
I guess the question is what is BIS approval? They no longer allow the "encryption registration" option on SNAP-R, so it seems you just need to send them an annual report but no longer need to register:

https://stackoverflow.com/questions/2135081/does-my-application-contain-encryption/40391664#40391664
"Specifically, they note:

    Encryption Registrations no longer required – some of the information from the registration now goes into the Supp. No. 8 to Part 742 report.

This means you may need to send an annual report to BIS, but you don't need to register and you can note when submitting your app that it is exempt."
