### ISSUE TITLE
No Autofill with Tumblr (and other apps) 

### ISSUE THREAD

**Issue by PascalDk** [bitwarden/mobile#1488]
I just installed Tumblr on my phone, the Autofill doesn't work at all.

Expected normal behavior where a pop-up suggest Autofill : not happening at all. No pop-up. 

Forcing Autofill with the notification-tile : it shows the right credentials, but when I select it... it still doesn't fill nothing.

Have to manually open Bitwarden, search for Tumblr, copy email, switch app, paste email, switch app, copy password, switch app, paste password... Wich is not the purpose of Bitwarden I guess ^^

This issue is with Tumblr, but I already experienced the same issue with other apps or website 😐

**Comment by Greenderella** [comment]
Hi @PascalDk 

The team is aware that some applications or mobile sites aren't been autofilled by our mobile app. This is something we are actively working on, so if you could please follow this link and complete the form: https://github.com/bitwarden/mobile/issues/1389 that would help us a lot.

**Comment by PascalDk** [comment]
Yep will do.
Cool to see that they know and have a dedicated effort about that.

Thx for letting me know.
