### ISSUE TITLE
Pincode screen on Android doesn't pop up keyboard 

### ISSUE THREAD

**Issue by rggjan** [bitwarden/mobile#149]
When bitwarden on Android is opened and asks for the four digits Pincode, the input field for the code is not selected and the keyboard not popped out. One has to clock on the screen first to get the keyboard.

It would be nice to have the keyboard automatically, since there is no other action than entering the code for the user to do anyway...

**Comment by kspearrin** [comment]
This doesn't seem to happen on every device.

**Comment by rggjan** [comment]
I'm using a galaxy s7 edge (SM-G935F), Android 7.0
Happy to test if I can help.

**Comment by Primokorn** [comment]
Same behaviour on my side with a Nexus 5 running Android 7.1.2.
Latest stable build.
It's the device of my wife so let me know if you need a log.

**Comment by mjdurham** [comment]
For me the keyboard will pop up when clicking on the app icon, but when I try to auto-fill from the notification service it never loads until I tap on the screen.

**Comment by jerryn70** [comment]
Same issue on moto x play naugat 7.1

**Comment by kspearrin** [comment]
I just patched this in the current build which is now available on the Google Play beta program. Can you try it there and let me know if it's resolved?

**Comment by mjdurham** [comment]
It works for me! The pin keyboard now pops out every time

**Comment by rggjan** [comment]
seems to work for me as well...
