### ISSUE TITLE
Option to enter API URI

### ISSUE THREAD

**Issue by matt-h** [bitwarden/mobile#15]
An option to change the API URI to something custom besides https://api.bitwarden.com/ on the login screen.

Any small settings button to change these parameters before logging in would work.

**Comment by kspearrin** [comment]
We definitely plan to add this when we introduce enterprise editions in the distant future, however, we can probably whip something together for the folks that want to stand up their own instances in the meantime. I'll keep this open for our backlog.

**Comment by graywolf336** [comment]
👍 this would be an awesome addition.

**Comment by Alexx-G** [comment]
Thanks for your effort, bitwarden UX is quite smooth across different platforms.

However, currently I can't easily use self-hosted feature with mobile apps (without getting a developer account for iOS what seems like an overhead for me).
How likely is that you're going to close this issue soon?

**Comment by kspearrin** [comment]
It was done in he last release.
