### ISSUE TITLE
Crash on iOS 15 Beta 5 & 6

### ISSUE THREAD

**Issue by Oxin92o** [bitwarden/mobile#1506]
Latest App Store Bitwarden version.
Since iOS 15 Beta 5 & iPadOS Beta 5, Bitwarden APP always crashes, and AutoFill doesn't work.

Yesterday updated to Beta 6, the problem still exists.

**Comment by djsmith85** [comment]
Hi @Oxin92o this has already been reported and is handled under #1493.
