### ISSUE TITLE
Add support for Android Oreo (8.0) Autofill Framework

### ISSUE THREAD

**Issue by meffect** [bitwarden/mobile#151]
This feature is awesome from what little I've used: Android Oreo (8.0) Autofill Framework

[Developer Documentation Link](https://developer.android.com/guide/topics/text/autofill.html) 

### Screen shot from my phone:
![screenshot_20171025-012521](https://user-images.githubusercontent.com/1799758/31988533-4b3dc856-b924-11e7-914c-3c4080db5ccb.png)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/mobile/issues/57
