### ISSUE TITLE
Do not memorize new account creation (Epic Game) 

### ISSUE THREAD

**Issue by PascalDk** [bitwarden/mobile#1518]
Another website where Bitwarden is blind when creating an account : epicgames.com

The app sees the text field of the form to create a new account, but do not memorize what has been filled up (login, username and password)

So I have a new account... but already lost my credentials 😑😁

**Comment by eliykat** [comment]
Hi @PascalDk, if you generated the password using Bitwarden, then you may be able to retrieve it by checking the [password generator history](https://bitwarden.com/help/article/product-faqs/#q-i-forgot-to-save-a-generated-password-can-i-view-the-history-of-generated-passwords) feature. In general, I recommend creating the Bitwarden login item first, then using autofill to insert those details into the registration form.

**Comment by eliykat** [comment]
I've just double checked and unfortunately our iOS app does not have the feature to recognise & save new logins. This feature is available on Android and the browser extension, but Apple does not give us access to these permissions to do it on iOS.

**Comment by PascalDk** [comment]
Yup, finally my conclusion too...

I'm not sure if it's a feature or a workaround thou ^^

**Comment by PascalDk** [comment]
> I've just double checked and unfortunately our iOS app does not have the feature to recognise & save new logins. This feature is available on Android and the browser extension, but Apple does not give us access to these permissions to do it on iOS.

Yup, there's a reason why I'm not using Apple products..
