### ISSUE TITLE
[Feature Request] Remember search input when switching from Favorites to My Vault tab (Android).

### ISSUE THREAD

**Issue by kendokan** [bitwarden/mobile#155]
When BW can't automatically locate the login and I have to search, I usually forget that it defaults to the Favorite tab and just key in my search. When my search yields no results because the site isn't in my Favorites, I then smack my forehead and switch to the My Vault tab, where I have to key in my search a second time. This is annoying because I expect whatever I type into the search input should stay there until I explicitly dismiss it.

**Comment by LivingWithHippos** [comment]
Yeah it's just like [this issue for the browser extension,](https://github.com/bitwarden/browser/issues/104) and I can say that now It works really well, should definitely be added to the mobile app

**Comment by kspearrin** [comment]
Favorites was removed so this is no longer needed.
