### ISSUE TITLE
Add FaceID for iPhone X

### ISSUE THREAD

**Issue by jamby** [bitwarden/mobile#158]
Please add the ability to use FaceID on new iPhone X. Especially since TouchID won't work on it any longer.

**Comment by jamby** [comment]
Apparently it already works! Cool.

**Comment by kspearrin** [comment]
Magic! Not really sure how. Maybe it just works off the same APIs as touch id.

**Comment by jamby** [comment]
@kspearrin Well, it could potentially use a UI update, since it still shows the TouchID stuff, but it works, and that's all I care about. 😄
