### ISSUE TITLE
Issues with logging into nookal.com site on android phone.

### ISSUE THREAD

**Issue by nuvnivek** [bitwarden/mobile#1584]
### Steps To Reproduce

Just select login, and autofill.

### Expected Result

Login ID and Password to be filled normally.

### Actual Result

Login ID is filled in the company ID.
Password filled in the Login field.

### Operating System

Android

### Build Version

2.13.0(3828)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
