### ISSUE TITLE
Auto fill not working properly on some apps

### ISSUE THREAD

**Issue by jerryn70** [bitwarden/mobile#159]
When I click on the matching result bitwarden is not filling the password fields. But then if I click username box and then click again the password box it will autofil.

Steps : 

1, Open Myntra app 
2, Clicked password field
3, Bitwarden notification shows
4, Typed pin and shows correct matching result
5, Clicked matching result
6, Nothing happens. 
7, Clicked username name field and then again clicked password field.
8, It got auto filled .

Auto fill method : password field focused
Android version 7.1.1
Bitwarden version : 1.12.1

Apps that I found this issue 

1, https://play.google.com/store/apps/details?id=com.myntra.android

2, https://play.google.com/store/apps/details?id=com.flipkart.android

**Comment by jerryn70** [comment]
This same issue is occurring on some other apps and websites also. Early this apps and websites were worked fine with autofil. I think this issues started from the latest Bitwarden version.

**Comment by kspearrin** [comment]
Not sure whats going on here, but it worked just fine for me. See

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/1190944/32407360-15fb8d9e-c15e-11e7-9ac9-da255cb68c9b.gif)
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/1190944/32407361-160b0d6e-c15e-11e7-942f-429544a23cc4.gif)

**Comment by jerryn70** [comment]
Well keep this issue open for 2 days. I will continue my  investigation and report you.

**Comment by jerryn70** [comment]
I have uninstalled and reinstalled Bitwarden still iam facing this issue. So I decided to record a video to show you. But whenever I record a video using screen recorder app , autofil is working. If I stop screen recording then autofil will not work.  
So I will shoot a video using another phone an show you. 

If you tested this apps with screen recorder ON then pls stop it and try again

**Comment by jerryn70** [comment]
https://www.dropbox.com/s/tq5ppm1fan7gg7z/WP_20171106_002.mp4?dl=0

https://www.dropbox.com/s/1vgoho9g97ul5cy/WP_20171106_003.mp4?dl=0

**Comment by kspearrin** [comment]
Very weird. Let me try with PIN enabled.

**Comment by jerryn70** [comment]
Not even showing Bitwarden autofil notification for this app https://play.google.com/store/apps/details?id=in.amazon.mShop.android.shopping

**Comment by kspearrin** [comment]
I can reproduce the Amazon app issue. I'll have to look into that one more. I turned on PIN and it didn't make any difference for the others. Still worked correctly. Can you try some fot he other autofill modes to see if they are also affected?

**Comment by Silver0066** [comment]
It does not work for me.  Autofill does not even pop up with any sign in app.  
Is this a known bug, or maybe it doesn't work on a Samsung S7.  Lastpass works just fine.

I would like to replace Lastpass with Bitwarden, but not if the autofill is not working on android.  It works great on the PC's.

**Comment by kspearrin** [comment]
@Silver0066 please see https://help.bitwarden.com/article/auto-fill-android/

**Comment by Silver0066** [comment]
Hi Kyle,

 

I already looked at that and everything is as suggested in the article.  I am using Chrome on my android.  Do you have any other suggestions?

**Comment by kspearrin** [comment]
Try restarting the device?

**Comment by Silver0066** [comment]
I just restarted the device.  No change.  The icon does not even show up when I click on password or username….just the keyboard.

**Comment by kspearrin** [comment]
Is this on a website in Chrome browser? What about when viewing a login form in a native app?

**Comment by Silver0066** [comment]
It is on a login form in Chrome browser.  I am not sure what you mean by a “native app”.

**Comment by kspearrin** [comment]
I mean an app on your phone that has a login form that is not a webpage.

**Comment by Silver0066** [comment]
OK, thanks.  I tried it on a native app…Starbucks.  Still no change and no icon popup.

**Comment by Sn1cket** [comment]
Hi, I am having a similar problem with some apps, but with the Android 8 Autofill Service.

Auto fill method : password field focused
Android version 8.0.0 (Oneplus OxygenOS 5.0.1)
Bitwarden version : 1.14.1 (1249)

Specific in these three apps I don't even get a popup to autofill with bitwarden:
- Netflix (com.netflix.mediaclient)
- QuickCheck (at.spardat.quickcheck)
- League Friends (com.riotgames.mobile.leagueconnect)

Should the autofill service also work for mobile browsers? 
Because I tried three different browsers (Chrome, Firefox, Dolphin) and in none of them the autofill popup appeared.

**Comment by kspearrin** [comment]
@Sn1cket 

> Auto fill method : password field focused

This setting only works for the accessibility service. It does not apply to android 8 autofill.

Android 8 autofill still has limited support and doesn't work in web browsers (except firefox focus). Google is suppose to be improving it over time.

**Comment by Primokorn** [comment]
@kspearrin I no longer get the notification when selecting a password field with Firefox Focus/Klar.
I don't know if it's related to an update of bitwarden or Focus/Klar.

**Comment by kspearrin** [comment]
@Primokorn We haven't pushed an update for a few weeks now so nothing changed here.

**Comment by Primokorn** [comment]
@kspearrin Then Mozilla has changed something which brokes bitwarden's detection. Could you have a look?
Do you want me to send you a log?

**Comment by kspearrin** [comment]
Just tested accessibility service in focus and it worked fine on github login page?

**Comment by Primokorn** [comment]
[Here is a comparison](https://ncloud.zaclys.com/index.php/s/4mhIOCIboyaFsFQ) between Firefox Klar and my Chromium based browser (see the notification).

**Comment by kspearrin** [comment]
I think Klar is only supported in the latest beta. I am not sure if that made it to production yet since it was recently requested we add support for it vs focus (they have different package names).

**Comment by kspearrin** [comment]
Nevermind. I am able to reproduce this on Focus this morning using the "focus password field" option.

**Comment by Primokorn** [comment]
The problem is still there with Firefox Klar (org.mozilla.klar v4.0.2)
A new app where auto-fill doesn't work: Via browser (mark.via.gp v3.3.2)
Tested with bitwarden 1.15.2 - Scan when password field focused - Android Oreo 8.1.0

**Comment by kspearrin** [comment]
@Primokorn ref via, see: https://community.bitwarden.com/t/add-via-browser-support/561/2?u=kspearrin

**Comment by jeroen7s** [comment]
any other android browsers that support android oreo autofill? :)

**Comment by Primokorn** [comment]
@jeroen7s [Bromite](https://forum.xda-developers.com/android/apps-games/app-bromite-chromium-plus-adblocking-t3687258).

**Comment by jeroen7s** [comment]
also bromite needs to be added to the supported browser list for legacy accessibility autofill, since bitwarden doesn't seem to detect it is a browser, but treats it as a regular app

**Comment by Primokorn** [comment]
@kspearrin 
• [Bromite browser](https://forum.xda-developers.com/android/apps-games/app-bromite-chromium-plus-adblocking-t3687258)  
When I press the notification to find my credentials for a given website, Bitwarden doesn't use the URI to suggest credentials. I have to search them manually. Bitwarden searches credentials for **org.bromite.bromite** (app package name)  
I thought it was a limitation of Bitwarden... until I tried Brave...  

• [Brave browser](https://play.google.com/store/apps/details?id=com.brave.browser)  
This browser has the same base as Bromite (Chromium) but Bitwarden suggests me credentials based on the URI.  

What's the problem with Bromite? Is it something that should be improved on your side or on Bromite app?  
Thanks.

**Comment by kspearrin** [comment]
@Primokorn I have to add support for each browser manually. How do I download Bromite? I see lots of apks on their releases page. Not sure which one I need https://github.com/bromite/bromite/releases

**Comment by jeroen7s** [comment]
if you have a phone from the last 3 years, you'd best use ARM64 (64 bit) and ModernChrome
without the Modern is for pre-lolipop android (before android 5.0)
x86 is for the rare devices that have an intel chip (mostly some older ASUS zenphones i think)
so you probably need this one https://github.com/bromite/bromite/releases/download/67.0.3396.72/arm64_ChromeModernPublic.apk

**Comment by jeroen7s** [comment]
omn bromite.org it's more clear (kinda)
there you have checkboxes for which architecture and android version you have above the download button

**Comment by Primokorn** [comment]
@kspearrin To give additional information to @jeroen7s's answer.  
AFAIR you have a Nexus 5X so download *arm64_ChromeModernPublic.apk**  
[More technical details here](https://chromium.googlesource.com/chromium/src/+/lkcr/docs/android_build_instructions.md#Multiple-Chrome-APK-Targets

**Comment by kspearrin** [comment]
Added https://github.com/bitwarden/mobile/commit/b5277e89d56f17e0e5759cb6870feda5abae15a7

**Comment by kspearrin** [comment]
I pushed the update to the beta channel on play store.

**Comment by Primokorn** [comment]
@kspearrin Thanks. It works flawlessly :+1:

**Comment by csagan5** [comment]
> How do I download Bromite? I see lots of apks on their releases page. Not sure which one I need https://github.com/bromite/bromite/releases

On the [official website](https://www.bromite.org/) you should get the right combination highlighted in green; this is done via javascript by checking the browser's reported CPU type and Android version.

Unfortunately it was not possible to publish it on Play Store, the F-Droid build requires more work and XDA Labs app does not support multi-arch/sdk (sigh), so for a lack of better delivery platform I thought to leave the situation as is for now (_à la_ [OpenGapps](https://opengapps.org/)), with the official website offering download links to the Github releases.

**Comment by Primokorn** [comment]
@kspearrin That's weird. Some Chromium based browsers don't have to be added manually.
Legacy autofill service is working while you didn't include this browser: https://forum.xda-developers.com/android/apps-games/app-kiwi-browser-chromium-adblock-caf-t3797252

**Comment by kspearrin** [comment]
@Primokorn I added kiwi browser a couple of days ago

**Comment by Primokorn** [comment]
@kspearrin oh sorry, just found the [commit](https://github.com/bitwarden/mobile/commit/ac027ee3a0516446434f78e9b9a71b1fbb89e920)

**Comment by csagan5** [comment]
I am still puzzled on why Bitwarden works correctly on Chrome but not on Chromium/Bromite (no Sync login needed). Has anyone done some research on this? The package names seem all covered by Bitwarden.

See also my [comment here](https://github.com/bitwarden/mobile/issues/159).

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
