### ISSUE TITLE
Android - Can't scan TOTP : View is "streched"

### ISSUE THREAD

**Issue by christ-off** [bitwarden/mobile#1590]
### Steps To Reproduce

1. Android 11
2. On Samsung A52s 5G up to date
3. Try to scan to add TOTP
4. View is reduced by 2 times in width (only)

### Expected Result

A scan of the QRCode

### Actual Result

App cannot scan 
and crashs on the second try

### Screenshots or Videos

I can't make a screen shot -> The says within one second that it can't recognize the QRCode

### Additional Context

I can scan using FreeOTP+

### Operating System

Android

### Operating System Version

11

### Device

Samsung A52s 5G

### Build Version

2.13.0(382)9

### Beta

- [ ] Using a pre-release version of the application.

**Comment by eliykat** [comment]
Hi @christ-off, this looks like the same issue reported here: https://github.com/bitwarden/mobile/issues/1130. I'll close this as a duplicate, but please post in that thread with any extra information.

**Comment by christ-off** [comment]
Thank you @eliykat 
You are absolutely right : this is a duplicate

**Comment by rvt0001** [comment]
I resolved this issue on my Samsung android tablet by changing the _**auto-rotate**_ setting to **_portrait_**.
