### ISSUE TITLE
iOS Update - All Data Gone Except Names

### ISSUE THREAD

**Issue by ryanwahle** [bitwarden/mobile#160]
So I just updated to the latest iOS app and all my data except for the name of the password entry is displayed. 

I do not believe at this point that the data is lost, as the web app still shows all passwords and other info I've saved. Another reason is that after I open the app and select a password item to view, the table view is shown with only one row (the Name field under Item Information header). 

No other table view rows are drawn on the screen and the height of the row is smaller than the name label as well as the name data. 

Screen shot below. This affects all password items.

 https://pasteboard.co/GS3ief3.png

**Comment by kspearrin** [comment]
Do a sync from Settings.

**Comment by ryanwahle** [comment]
Damnit. Yeah, that worked.  

Well, hopefully I can redeem myself here with a real big report. :-)

So I hadn't done the sync in the past because the app is reporting that it was synced and even shows the current date and time (minus a few seconds of course).

I had assumed it was synced and did not want to risk sending back blank data just in case it wasn't just a graphic error on the app. 

However, it clearly wasn't actually synced since I did click the sync button as you requested and it now displays everything as normal. 

I'm going to leave this open, but let me know if I should close and file new report on wrong sync date. 

If you already are aware of this issue, please close this issue.

Great app and thanks for your dedication and time commitment to us.

**Comment by kspearrin** [comment]
Thanks. We're aware of this issue.

**Comment by ryanwahle** [comment]
Right on. Closing this out.
