### ISSUE TITLE
Sometimes iOS is crashing/rebooting when the Bitwarden app is opening

### ISSUE THREAD

**Issue by v1kTim** [bitwarden/mobile#1604]
### Steps To Reproduce

I cannot reproduce it, unfortunately.
Has only occurred twice.

### Expected Result

N/A.

### Actual Result

I have experienced only twice:
When I opening the Bitwarden app on my iPhone, then iOS is crashing/rebooting immediately without any error message.

I'm using a self-hosted Bitwareden server instance with well configured x.509 SSL/TLS certificate.
I'm using the Face ID for unlocking the Bitwarden app.

I can provide more logs/analytics data from my iPhone if you can tell me what debug file you needed...

### Operating System

iOS

### Operating System Version

15.0.2

### Device

iPhone 11 (MWMA2ZD/A)

### Build Version

v2.13.0 (929)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by clayadams5226** [comment]
hey @v1kTim this issue should be resolved with the latest version available on the app store. Can you give it a try and let me know if you're still experiencing the issue?
