### ISSUE TITLE
Auto-fill link covers button in oi-safe making it impossible to confirm dialog

### ISSUE THREAD

**Issue by brianmay** [bitwarden/mobile#1619]
### Steps To Reproduce

1. Install oi-safe. 
2. Go through oi-safe configuration.
3. Backup database: ... -> Password file -> Backup.
4. Save to default location of <sdcard>/Downloads/oisafe.xml
5. Restore database: ... -> Password file -> Restore.
6. Select the file you just saved.
7. Try to enter password.
8. Notice that it is not possible to click the Restore button to continue, because it is hidden under the "Auto-fill with Bitwarden"
9. If you click the "Auto-fill with Bitwarden" you can briefly see the button, but there isn't enough time to click on it.
10. Unlike it some apps, trying to push the tick button in the on screen keyboard doesn't activate the button.

I have had this happen on 2 different mobile phones.

### Expected Result

There should be some sort of gesture or something that makes it possible to move or close the "Auto-fill with Bitwarden" message out of the way, so you can reach the button.

### Actual Result

It is not possible to move or close the "Auto-fill with Bitwarden" prompt. It is not possible to continue and restore a backup as a result.

### Screenshots or Videos

![Screenshot_20211029-163008](https://user-images.githubusercontent.com/112729/139382691-40c70f4c-92de-4367-abb9-4546bda51991.png)

### Additional Context

My guess is it might be possible to disable the auto-fill temporarily to get this to work. But this shouldn't be required.

### Operating System

Android

### Operating System Version

11 and 12

### Device

Samsung Galaxy Note 10+ 5G, Pixel 6 Pro

### Build Version

2.14.0 (3977)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by skjaeve** [comment]
Experiencing a similar issue when entering pin code in Teams and Outlook apps. Overlay obscures "submit" button. Not critical in this case, since "Enter" on keyboard also works, but annoying.

Device: Mi A2, Android 10
App version: 2.14.2

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by brianmay** [comment]
That referenced bug seems to be more about auto-fill problems, i.e. auto fill not working.

This issue isn't a problem with auto fill not working, so the referenced form doesn't seem to be appropriate. The autofill works fine.

It is the next step that fails.
