### ISSUE TITLE
Choosing an entry from the vault does not populate form fields in Firefox 93.2.0

### ISSUE THREAD

**Issue by kaysond** [bitwarden/mobile#1623]
### Steps To Reproduce

1. Open Firefox for Android 93.2.0
2. Access a website that requires login (I used github)
3. When the autofill popup appears, choose "Auto-fill with Bitwarden" (doesn't matter if vault is locked or not)
4. Choose an entry

### Expected Result

Form fields should properly be auto-filled

### Actual Result

Form fields don't get populated at all

### Additional Context

The password auto-fills just fine if you pick the entry directly from the popup in browser. Also worth noting that this bug does not happen in Chrome, so it's something related to Firefox (see 14633 linked below).

Related: https://github.com/mozilla-mobile/fenix/issues/14633
and probably: https://github.com/bitwarden/mobile/pull/1592 (which fixed another FF-specific issue)

This issue has been around for a long time - I'll buy pizza and beer for the person/team who resolves it. 🍕 🍻 

### Operating System

Android

### Operating System Version

Android 9

### Device

Huawei Mate 10 Pro

### Build Version

2.14.2 (4005)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vachan-maker** [comment]
Yeah I am also facing the same issue on firefox.

**Comment by Udayanithig** [comment]
I'm also facing this issue.

**Comment by kaysond** [comment]
@makotokato any chance your debug in #1592 gives you an idea of why this particular behavior is still not working?

**Comment by makotokato** [comment]
@kaysond 
I guess that this is same issue as https://bugzilla.mozilla.org/show_bug.cgi?id=1693152. But I don't debut it yet, so I will look it.

**Comment by kaysond** [comment]
This was indeed a problem with FF thats fixed as of 102.2.0
