### ISSUE TITLE
iOS share sheet button not working

### ISSUE THREAD

**Issue by curious-otter-byte** [bitwarden/mobile#1624]
### Steps To Reproduce

1. go to “share” button in mobile Safari
2. Tap on Bitwarden button/icon
3. Nothing happens

App extension button within the app also does nothing

### Expected Result

Bitwarden autofill list should appear

### Actual Result

Nothing happens

### Screenshots or Videos

![D3AF99F9-E504-456B-BB54-A3CECDB7CDE2](https://user-images.githubusercontent.com/92382118/139665557-4b63d3d1-3178-4b5b-926d-5389b8fdc6ea.jpeg)

### Operating System

iOS

### Operating System Version

14.8 (18H17)

### Device

iPhone Xʀ

### Build Version

2.14.2 (1105)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by EmnaX** [comment]
Came here to report the same issue. Happening to me on my iPhone as well.
iOS: 15.1 (19B74)
Device: iPhone 13 Pro Max (MLKG3VC/A, A2641)
Build Version: 2.14.0 (1077) and 2.14.2 (1105)

**Comment by chadlipscomb** [comment]
iPad as well.

iPadOS 15.1
iPad Pro (11-inch) (2nd generation)
MXDC2LL/A

**Comment by jason-wisnieski** [comment]
Ditto - iOS 15.1 on iPhone X, Bitwarden 2.14.2 (1105)

This feature is what's bringing me here from 1Password, too. Ah, cruel fates!

**Comment by BerlinBased** [comment]
Same issue on my iPad Pro (5th) and iOS 15.1, no reaction at app extension button, so it can not be activated!

**Comment by jlf0dev** [comment]
Hi @BerlinBased, can you check if the fix found in #1635 also solves your problem?
Thanks!

**Comment by curious-otter-byte** [comment]
> Hi @BerlinBased, can you check if the fix found in #1635 also solves your problem? Thanks!

The new version of Bitwarden for iOS corrects the issue. Thank you!

**Comment by BerlinBased** [comment]
Hi!

I checked and everything is fine now!

Thank you!
