### ISSUE TITLE
Cannot add custom secure note field using iOS mobile app

### ISSUE THREAD

**Issue by CodingMarkus** [bitwarden/mobile#163]
Both, the website and the Firefox plugin allow me to add custom secure note fields since the last update. The iOS app also has been updated but it doesn't seem to add that option. Has it been forgotten?

bitwarden App for iOS Version 1.12.2 (23)

**Comment by kspearrin** [comment]
No, we just have not added it yet. For now only existing custom field values can only be modified in the mobile apps.

**Comment by kspearrin** [comment]
Merging https://github.com/bitwarden/mobile/issues/261
