### ISSUE TITLE
Favicons are missing on Android app

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/mobile#1640]
### Steps To Reproduce

1. Login to Android app and check the vault

### Expected Result

Favicons show up

### Actual Result

The icon is blank

### Operating System

Android

### Operating System Version

11

### Build Version

2.14.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
There has been a vivid community thread which discusses this topic here: https://community.bitwarden.com/t/android-app-no-icons-for-logins/34256

One possible issue seems to be expired certificates on self-hosted instances.

**Comment by sso-bitwarden** [comment]
This report is for the cloud

**Comment by ow0x** [comment]
when this fix will be available on play store as app update?

**Comment by tgreer-bw** [comment]
@ow0x yep! The beta builds 4092+ have the fix in it currently.

**Comment by ow0x** [comment]
> @ow0x yep! The beta builds 4092+ have the fix in it currently.

I was referring stable builds, not beta versions.

**Comment by tgreer-bw** [comment]
@ow0x no worries, the updated apps will be released on the stable channel in the Play Store soon.
