### ISSUE TITLE
Android 12 change in lifecycle autofill bug with Draw Over/Accessibility Quick Tile

### ISSUE THREAD

**Issue by mehmooda** [bitwarden/mobile#1645]
### Steps To Reproduce

1. Open Bitwarden from launcher
2. Press back
3. Go to website/app with autofill
4. Click on either Auto-fill with Bitwarden pop over or Autofill Quick Tile in notification bar.

### Expected Result

Bitwarden should open with "Items for ..." page allowing you to select the credential to auto-fill.

### Actual Result

Bitwarden loads "My Vault" page not allowing you to select an item to auto-fill

### Additional Context

Autofill from IME is unaffected

If you use the task manager to swipe the previously launched bitwarden app close. Then the quick tile works. I suspect its an interaction with the lifecycle changes in [Android 12](https://developer.android.com/about/versions/12/behavior-changes-all#activity-lifecycle)

### Operating System

Android

### Operating System Version

12

### Device

Pixel 6 Pro and Pixel 4 XL

### Build Version

2.14.2 (4005)

### Beta

- [X] Using a pre-release version of the application.

**Comment by frigi83** [comment]
Same problem with a Samsung Galaxy S21 with Android 12

**Comment by nathan-knight** [comment]
I'm also having this issue on my Pixel 3 XL running Android 12.

It doesn't always bring you to "My Vault", it brings you to wherever you were last in the Bitwarden app (for instance, navigate to settings and that is what will appear). This also happened to someone I just introduced to Bitwarden and it was very frustrating for them because they tried several times but could not get it to bring up the correct menu.

Killing the app from the app switcher resolves it for me as well but is not ideal.

App build 2.14.2

**Comment by fedemkr** [comment]
I was able to reproduce this, I'll take a look, thanks for the report and the details

**Comment by jlf0dev** [comment]
> I was able to reproduce this, I'll take a look, thanks for the report and the details

@fedemkr This might be related to the work I was doing [here](https://github.com/bitwarden/mobile/pull/1602), but i'm not sure if I was targeting Android 12. I would check if those changes fix the issue.

**Comment by frigi83** [comment]
Today I have received the update in the Play Store with the version [v2.15.0](https://github.com/bitwarden/mobile/tree/v2.15.0) (4125), after the update (#1673) the problem still there as described by @nathan-knight 

I have also tried to reinstall BW (and between some reboot), but nothing.

**Comment by jlf0dev** [comment]
Hi @frigi83, unfortunately #1673 isn't included with 2.15.0. This gives us some additional time to verify the fix and make sure it didn't break anything else. I apologize for the wait, but should be included in the next release!
