### ISSUE TITLE
Support for Username window followed by Password window

### ISSUE THREAD

**Issue by Coffmans** [bitwarden/mobile#165]
I apologize for the weird title of this post. I am a recent convert from LastPass and my go-to browser on my Note 4 is Dolphin. One of the reason for conversion is the need to have LastPass Premium in order to use LastPass in Dolphin. When browsing to a number of sites w/in Dolphin, BitWarden is able to provide the auto-fill feature to allow me to log into site. This is awesome, no doubt about it. But I have found some sites where BitWarden is not able to auto-fill. 

An example is bing.com. I open Dolphin, navigate to bing.com, click sign in. The first window to appear is the username window. No prompt for auto-fill from BitWarden. I enter the username and click the next button, where I am taken to a window for the password. Again, no prompt for auto-fill from BitWarden. I am not sure if the flow of the site (username window, next, password window) is a problem, or if there is a different issues at play. 

I wanted to check if this issue might be a known issue. If so, is there any recommended workaround, short of going to the BitWarden app and performing a copy/paste?

**Comment by kspearrin** [comment]
As long as a password field appears on screen the autofill service should pick it up. Maybe dolphin is not sending any window update events for us to refresh. Does anything change if you focus the password field?

**Comment by Coffmans** [comment]
Excellent point. In doing a quick test, the auto-fill logic does not work when I put focus on the username field. But the auto-fill logic does work if I put focus on the password field. Although it would be nice to have the same for the username, the auto-fill for password is more than what is offered with the standard LastPass.

**Comment by kspearrin** [comment]
Unfortunately we can't really make any determinations on a username fields vs regular fields when it is not accompanied with a password field.

**Comment by Coffmans** [comment]
Understandable. Even with just password, it is kicking the crap out of LastPass. Thanks for your help!
