### ISSUE TITLE
iOS keyboard AutoFill disregards URI

### ISSUE THREAD

**Issue by bobfatherx** [bitwarden/mobile#1686]
### Steps To Reproduce

1. Enable Bitwarden AutoFill in Settings
2. Configure subdomains (e.g., site1.myFQDN.com, site2.myFQDN.com, etc.)
3. Create Bitwarden login and password entries for each subdomain, enter a URI, and set URI match to ‘starts with’
4. Navigate to site1, site2, and inspect the keyboard AutoFill suggestion that appears to the left of the key that invokes BitWarden’s pop up

### Expected Result

AutoFill suggestion should use the URI match to suggest the matching login credentials. 

### Actual Result

AutoFill suggestion ignores URI and suggests the login credentials of the first alphabetical Bitwarden item with a matching host. However, clicking the key invokes the Bitwarden pop up that properly matches the subdomain. See photo examples. 

### Screenshots or Videos

Keyboard AutoFill displaying bw.FQDN.space instead of blueiris.FQDN.space because in the vault, accordingly, the items are named ‘Home - Bitwarden’ and ‘Home - Blue Iris’
![](https://i.imgur.com/NeaHkHl.jpg)

Clicking the Bitwarden key pops up the correct site, as does using the iOS share sheet (thanks for fixing the share sheet access in the recent update!)
![](https://i.imgur.com/PoyIwvr.jpg)

### Operating System

iOS

### Operating System Version

15.1

### Device

iPad, iPhone

### Build Version

Version: 2.15.0 (1225)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by nicomerl** [comment]
Hello, today issue still exists. I can confirm what @Gerardv514 Said.

With the new iOS 18 App „Passwords“ URI Matching works exactly as it should. I added 2 different Passwords for 2 IPs with Port:
1.2.3.4:2000
1.2.3.4:3000

The iOS Passwords-App Matches the exakt URI. The Bitwarden App Matches only the IP. Please fix this Issue…

**Comment by SergeantConfused** [comment]
Hello @Gerardv514,

> [@SergeantConfused](https://github.com/SergeantConfused) this makes no sense since apples’ built in keychain has the ability to utilize subdomains.
> 
> I switched my autofill iOS option from bitwarden to keychain in iOS settings. The iOS keyboard can properly detect and match each separate sub domain.
> 
> I’m also pretty sure at one point i never had an issue with this when I first started using bitwarden.
> 
> Where does the limitation then fall?

I have raised this internally, and it's being explored.


All the best,

**Comment by Gerardv514** [comment]
> Hello [@Gerardv514](https://github.com/Gerardv514),
> 
> > [@SergeantConfused](https://github.com/SergeantConfused) this makes no sense since apples’ built in keychain has the ability to utilize subdomains.
> > I switched my autofill iOS option from bitwarden to keychain in iOS settings. The iOS keyboard can properly detect and match each separate sub domain.
> > I’m also pretty sure at one point i never had an issue with this when I first started using bitwarden.
> > Where does the limitation then fall?
> 
> I have raised this internally, and it's being explored.
> 
> All the best,

I appreciate that.

Additionally, if Apple and Bitwarden are both part of the FIDO Alliance, bring this up at a meeting and somehow see if we can jive it all out between the two companies. There has to be some partnership between the two.

Thank you for your time and assistance.
