### ISSUE TITLE
Name field is not prioritized in search results

### ISSUE THREAD

**Issue by jonschlu** [bitwarden/mobile#1687]
### Steps To Reproduce

Searching for items in any part of the iOS app

### Expected Result

When searching for an item, the value from the "name" field should be prioritized and always at the top of the results. If I have one login with the name "Yahoo" in my vault, this entry should be at the very top of the results search results when I search for "Yahoo". This is how it works in the browser extension.

### Actual Result

Results are sorted alphabetically based on both the field "username" and "name". 

If I would search for "Yahoo" in my vault and my email was aaron[at]yahoo.com, all my logins where the username is my e-mail address would be above my login named "Yahoo".

### Operating System

iOS

### Operating System Version

iOS 15.1

### Device

iPhone 12 Pro

### Build Version

2.15.0 (1225)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by novocaiin** [comment]
Same issue on Android.

**Comment by sawft99** [comment]
Yeap. About to put in a bug report but found this. Still the same on Android 12.
