### ISSUE TITLE
Android 12 Markup App crashing when Bitwarden is selected as auto-filling service

### ISSUE THREAD

**Issue by TheDuffman85** [bitwarden/mobile#1688]
### Steps To Reproduce

1. Set system language to German
2. Set Bitwarden as auto-filling service
3. Make a screenshot
4. Click on the edit icon
5. Save the screenshot

Clicking the save button will crash the Markup App (System App). The screenshot will be lost after the crash, but there will be a corrupted file in the gallery. 

### Expected Result

Saving the screenshot without crashing the Markup App.

### Actual Result

The Markup App (System App) crashes with an UnknownFormatConversionExcpection. This only happens when Bitwarden is selected as auto-filling service. I'm not sure if Bitwarden is causing this exception or if it's a bug within Android. But it's definitively somehow related. If other Apps are selected as auto-filling service the Markup App doesn't crash. A user on Reddit suggest the crash is only happening if the system language is German and Bitwarden is selected as auto-fill service. I did not validate if the system language is really involved. 

If Bitwarden is not selected as auto-filling service Android Markup App is working just fine!

### Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/9296618/145986647-7f4aea1f-f07b-4c24-bc5e-c61e3c46da9c.png)
![grafik](https://user-images.githubusercontent.com/9296618/145986656-5ab22ad1-d614-4586-8484-c52b8f96b4e3.png)

![grafik](https://user-images.githubusercontent.com/9296618/145984487-1946713a-e4a4-4caf-8434-c502dba68a7c.png)
![grafik](https://user-images.githubusercontent.com/9296618/145984507-5bf70fb2-34eb-4a11-a9fa-29ceb0a51df8.png)

### Additional Context

Here is another description of this problem from a [Reddit](
https://www.reddit.com/r/GooglePixel/comments/qe1dh0/markup_broken_after_android_12_update_pixel_5/hipa4qu/?utm_source=share&utm_medium=web2x&context=3) user.

> Bahiilein - 1 mo. ago

> I` think I've found what causes the problem. It seems to be a combination of the German system language and giving an app full accessibility service for auto-filling (usually a password manager).

> Either turning off the accessibility or switching system language to something different than German fixes the issue for me. So it sucks either way.

> Android autofill framework doesn't break Markup but unfortunately not every app/service is compatible with it.

### Operating System

Android

### Operating System Version

12.0

### Device

Pixel 6 Pro

### Build Version

2.15.0 (4125)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Holadiodoingit** [comment]
Same here (inkluding Language, Device, Operating System Version)

**Comment by julian-klode** [comment]
Works fine here, same Bitwarden version, Pixel 6, German, December patch. I remember this being an issue on Android 12 beta (on the Pixel 4a), but can't say I noticed on stable (which I setup fresh, not restoring system settings, only apps).

**Comment by TheDuffman85** [comment]
My device is a Pixel 6 Pro also with December patch. Maybe it's a specific problem with Pixel 6 **Pro**? Or maybe there is another factor involved.

**Comment by ChristianCiach** [comment]
Still an issue with the February patch for my Pixel 6 Pro set to german. Switching the system language to English doesn't fix the issue for me, but I didn't attempt a reboot afterwards.

**Comment by TheDuffman85** [comment]
Yes, same for me. Also I can reproduce this bug in Android Emulator with API level 31. So it seams it is related to Android 12 in general and not only Pixel 6 Pro.

**Comment by TheDuffman85** [comment]
Hi @fedemkr,

thank you for your feedback. I tested a bit and I think I figured out, how to reliably reproduce this bug in the emulator. 



This is the setup of my emulator:
![2022-02-17 13_51_29-bitwarden-mobile - Microsoft Visual Studio](https://user-images.githubusercontent.com/9296618/154487033-3ccf14a0-236f-4593-98e5-b94393dd892b.png)

0. I opened a safe in Bitwarden. I'm not sure if this is crucial.

1. You need to set the language to German. 

2. Set Bitwarden as auto-fill service. 
![2022-02-17 13_50_35-bitwarden-mobile - Microsoft Visual Studio](https://user-images.githubusercontent.com/9296618/154487170-aa1efea7-842c-41eb-b711-4d47fd06a83b.png)

3. Set Bitwarden as Accessibility (I think this is key to reproduce this bug in emulator)
![2022-02-17 13_49_54-bitwarden-mobile - Microsoft Visual Studio](https://user-images.githubusercontent.com/9296618/154487358-36a8a4ab-9a3c-422f-aa22-e3f80624721b.png)

4. Take a screenshot from the app switcher and click on the edit icon
![2022-02-17 13_47_07-bitwarden-mobile - Microsoft Visual Studio](https://user-images.githubusercontent.com/9296618/154487533-0c0e7ada-f04b-4892-8466-61bb492ae17a.png)

5. Crop the screenshot
![2022-02-17 13_47_47-bitwarden-mobile - Microsoft Visual Studio](https://user-images.githubusercontent.com/9296618/154487690-a9e54114-2ee0-40dd-b636-470f02f40c01.png)

6. Click on annotate and draw something
![2022-02-17 13_48_01-bitwarden-mobile - Microsoft Visual Studio](https://user-images.githubusercontent.com/9296618/154487802-af14fc24-9673-4012-94aa-e1030711fb7a.png)

7. Go back to crop. This is where the markup app will crash in the emulator. On the Pixel 6 Pro it will crash when you click on save. The dialog indicating that the app crashed will only show sometimes. 
![2022-02-17 13_35_26-bitwarden-mobile - Microsoft Visual Studio](https://user-images.githubusercontent.com/9296618/154488068-cb15c18b-c3b2-403c-b4f9-b598b2e0aa89.png)

![2022-02-17 13_46_33-bitwarden-mobile - Microsoft Visual Studio](https://user-images.githubusercontent.com/9296618/154488240-dbbb568b-15eb-41f7-a0de-9c18f08b86da.png)

**Comment by fedemkr** [comment]
Hi @TheDuffman85 thank you so much for all the details!!! I'll try it as soon as I can and see what is happening 😄

**Comment by TheDuffman85** [comment]
Seems to be fixed with March update for Pixel 6 Pro. So it maybe was an Android 12 issue after all.
