### ISSUE TITLE
Search for sites

### ISSUE THREAD

**Issue by nlowe** [bitwarden/mobile#17]
It appears that the ability to search for a site / account does not exist in the mobile client. [keepassdroid](https://play.google.com/store/apps/details?id=com.android.keepass&hl=en) supports this.

**Comment by kspearrin** [comment]
![capture](https://cloud.githubusercontent.com/assets/1190944/20645635/15269f74-b432-11e6-8eb3-09cfb9f05d5c.PNG)

Use the search input at the top of the listing on the vault screen.

**Comment by nlowe** [comment]
I don't see that input (Android 1.1.0 (8))

**Comment by kspearrin** [comment]
That is odd. I had someone report this same thing a few months ago. What kind of device are you using? What OS version?

**Comment by nlowe** [comment]
Nexus 5x w/ latest stock (7.0 or 7.0.1). I see the search bar on my tablet
(Nvidia shield w/ an old build of CM 12.1).

**Comment by kspearrin** [comment]
I have no idea. I'll have to investigate the search bar control that is being used to see if there are some conditionals in there for some reason.

**Comment by nlowe** [comment]
May be an Android 7 issue. I can also see the search input on my work phone (Samsung Galaxy S7 / Android 6.0.1)

**Comment by kspearrin** [comment]
Looks like this is related to a known bug in Xamarin Forms and/or Android related to Android 7. Not much I can really do until it is patched on their side. see https://bugzilla.xamarin.com/show_bug.cgi?id=43975

Sorry :(

**Comment by nlowe** [comment]
FYI Seems to be resolved. Not sure if it was 7.1 or 7.1.1 that fixed it.

**Comment by kspearrin** [comment]
Great. Thanks for the follow up.
