### ISSUE TITLE
App generating OTP codes?

### ISSUE THREAD

**Issue by CliffordD** [bitwarden/mobile#170]
Could the app be used to generate OTP using the TOTP key stored in the vault?  Maybe even auto-completing the code For example on a WordPress login form, auto complete the username, password and OTP to allow easier access?

**Comment by kspearrin** [comment]
The apps already generate TOTP codes and copy to them to the clipboard when autofilling. It requires a premium membership.

**Comment by CliffordD** [comment]
I can't seem to get that feature to work.  Maybe I am doing something wrong?

1) Go to the website I want to log into
2) Tap on the bitwarden icon in the event notification area
3) Tap on the item matching the website I want to log into
4) It automatically fills out the username and password, but not the OTP

**Comment by kspearrin** [comment]
It does not fill the OTP. It copies to your clipboard.

**Comment by CliffordD** [comment]
Is there a reason why it can't auto-fill this field if it has the OTP copied?

**Comment by kspearrin** [comment]
OTP codes are usually collected on the page after username/password and therefore would not be part of the autofill process.

**Comment by CliffordD** [comment]
That is a shame, this feature would be such a time saver for me :(

**Comment by CliffordD** [comment]
Sorry, don't mean to be so negative.  Really love the app being able to do this and not having to reply on switching to another app to get the OTP.  Just having this feature would be the icing on the cake so to speak. Thanks for developing this amazing app :)

**Comment by bartimaeus** [comment]
Is the website the only place that currently shows the OTP codes?

**Comment by CliffordD** [comment]
The app and browser plugin display the OTP and copy it to the clipboard.  But I feel this is not very intuitive and would be better auto-filled like the username and password are.

**Comment by bartimaeus** [comment]
I guess I just don't see the code showing up in the browser plugin. Maybe it takes some time to sync.

**Comment by CliffordD** [comment]
Have you entered the Authenticator Key (TOTP) to the entry in My Vault?

**Comment by bartimaeus** [comment]
Yes, I scanned a QR code on the mobile app. I am able to view the codes in My Vault, but that is almost as the same as using Google Authenticator on my phone.

**Comment by CliffordD** [comment]
![otp](https://user-images.githubusercontent.com/8769092/33343272-9135f496-d47c-11e7-9674-f709d7091feb.png)

If you Auto-fill the page with the matching entry, it copied the OTP to the clipboard which can then be pasted into the OTP field on the form.

**Comment by bartimaeus** [comment]
Is that your browser extension? I don't see that in either the mobile app or the browser extension. However, I do see it on vault.bitwarden.com. I wonder if it is a syncing issue and I should remove and then do the TOTP setup again.

**Comment by kspearrin** [comment]
@bartimaeus Log out and back in if you just purchased premium.

**Comment by bartimaeus** [comment]
Should have tried that :) Thanks @kspearrin! That did the trick.

**Comment by CliffordD** [comment]
Yes, that's my extension in Chrome.  I am running the Google Authenticator Wordpress plugin for Two factor authentication.

![wordpress_login](https://user-images.githubusercontent.com/8769092/33343475-55545318-d47d-11e7-93ba-3f50614dd3c2.png)
 
NB : You need to purchase premium to use this option, which I assume you have?

**Comment by bartimaeus** [comment]
Thanks @CliffordD

**Comment by CliffordD** [comment]
Glad you got it working :)  It is a great feature to have.

My wishlist/feature request is to have this field auto-completed rather than having that extra step of having to paste the code into the field manually.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
