### ISSUE TITLE
iOS App crashes when trying to re-open after certain amount of time and when using dark mode. 

### ISSUE THREAD

**Issue by Krychaz** [bitwarden/mobile#1706]
### Steps To Reproduce

1. Go to Bitwarden App and make sure dark mode is enabled 
2. Login
3. Go back to to the iOS homescreen 
4. Try to open Bitwarden app after some time

### Expected Result

Expected result is that the app is still usable and you can interact with it

### Actual Result

App crashes and forced authentication 

### Additional Context

Problem is apparently not seen when using the default light theme 

### Operating System

iOS

### Operating System Version

15.2

### Device

Iphone 13 Mini

### Build Version

2.15.0(1225)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by chrsve** [comment]
I think this might be connected to "unlock with face ID"... when I disabled that feature and use my master password to authenticate there is no more crashing. It has been stable for over a week now. I also remember increasing my logout time limit a bit but I do not think that is affecting the behaviour.
