### ISSUE TITLE
iOS App Crashes on Launch, But Works on Second Attempt  Bitwarden 2.15.0 (1225), iOS 15.2.

### ISSUE THREAD

**Issue by Stickyhavr** [bitwarden/mobile#1711]
### Steps To Reproduce

1. Go to Bitwarden app on the iPhone Home Screen.
2. Click on the app.
3. App crashes (at least once out of 10 times).
4. Click on app again, it works fine.

### Expected Result

The Bitwarden app should open the first time, every time.

### Actual Result

Different users are reporting different frequency, but everyone who has experienced it seems to agree that at least 1 in every 10 app launches, Bitwarden will crash immediately. But tapping it again does start the app as expected.

### Additional Context

Bitwarden iOS app often crashes immediately when you open it but works fine the second time you open it.

Since the latest release in the App Store 2.15.0 (1225), several people have experienced this bug. A few people have mentioned it on the subreddit: https://reddit.com/r/Bitwarden/comments/rv8fc1/need_to_double_tap_to_open_in_ios/
Also, this may be the root cause of issue #1636 (which I found when searching to see if this had been reported already, I don't think it has).

I never experienced this prior to the latest release. It is hard to reproduce though because opening the app over and over again seems to work every time. Only in natural usage, using various other apps and then coming back to Bitwarden, seems to make it happen. Perhaps a memory issue? Not sure, but at least it's reported now.

### Operating System

iOS

### Operating System Version

15.2

### Device

iPhone 13, iPhone 13 Pro, iPhone 6S+, 

### Build Version

2.15.0 (1225)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Ayitaka** [comment]
I second this bug report.

iPhone XS Max

iOS 15.1

Bitwarden Mobile Version: 2.15.0 (1225)

Click app, immediately crashes before showing anything. Only happens when opening app, not for autofill within Safari. Opening it second time always works. Likely that the app is open already but in background mode when this happens since I rarely manually close the app.

**Comment by bez820** [comment]
+1 to this report

iPhone 11 - IOS 15.1
iPad Pro 10.5 - IOS 14.8.1

Bitwarden mobile version: 2.15.0

I’ve noticed to this seem to happen more when coming back to bitwarden later on. 

1. Open Bitwarden and login
2. Switch to bunch other iOS apps while waiting 15-30 minutes 
3. Open Bitwarden from home screen should the now crash

**Comment by MTShipp** [comment]
I posted a poll on the Reddit sub and the anecdotal responses are 7% of 305 respondents have this happen every time.

**Comment by vvolkgang** [comment]
Hey everyone, just wanted to let you know our next release (currently in testing) will include #1700 and #1707 that should fix this. This was extremely difficult to debug, thanks for all the info you shared it helped us get to the bottom of it, closing this for now but let me know if it happens again after the next release!
