### ISSUE TITLE
Error when creating notes or creating a custom URI

### ISSUE THREAD

**Issue by Mikau28** [bitwarden/mobile#1716]
### Steps To Reproduce

1. Go to secure notes in the iOS mobile app
2. Fill out note, click save

### Expected Result

A note should be saved. 

### Actual Result

Unexpected server error message. Same for saving URLs for websites. 

### Screenshots or Videos

![Uploading AAE66B9B-6743-4409-BED9-C6169A1E3DA6.png…]()

### Additional Context

Besides the auto fill feature this renders the app useless. Hopefully this is something on my end I can enable a setting. 

### Operating System

iOS

### Operating System Version

15.2

### Build Version

2.15

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Mikau28** [comment]
![image](https://user-images.githubusercontent.com/40307312/148976292-40eea206-46c7-45c3-947f-6f258182b8eb.png)

**Comment by fedemkr** [comment]
Hi, are you using a self-hosted instance or special config on the app Settings? Just to check which server you are pointing to

**Comment by Mikau28** [comment]
> Hi, are you using a self-hosted instance or special config on the app Settings? Just to check which server you are pointing to

Where do I find those settings? I don't use a self hosted setup, so whatever default points to is what I use.

**Comment by Mikau28** [comment]
I resolved this issue. If anyone runs into this issue. Log out before you try uninstalling. It seems to hold onto stagnant data between installs.
