### ISSUE TITLE
Password saving only opens app

### ISSUE THREAD

**Issue by traffic-light** [bitwarden/mobile#1736]
### Steps To Reproduce

When the app is open in the background:
1. Go to a website login form
2. Fill in credentials
3. Press login
4. (bitwarden save prompt appears at the bottom of the screen)
5. Press save

### Expected Result

After pressing save a form with all the credentials filled out in the inlog form (and of course the website, website name etc)

### Actual Result

The last opened screen in the app. for example when a vault was the last screen this will popup.

### Additional Context

I only got this working _(Expected Result)_ when the app was closed and i had to fill in the masterpassword.

(I couldn't find this issue in the issue list. I'm sorry when this is a double post)

### Operating System

Android

### Operating System Version

11

### Device

nokia 4,2

### Build Version

2.15.0 (4125)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by traffic-light** [comment]
With the current, newer version, this problem is solved!
Versie: 2.16.1 (4306)

**Comment by lucamp** [comment]
Same issue on new version 2022.8.0 (4911)
Android 10
