### ISSUE TITLE
Creating folders from iOS is broken

### ISSUE THREAD

**Issue by papertigers** [bitwarden/mobile#174]
The first line was from the iOS app which 404'd while the second line is from the firefox extension.  It looks like the iOS app is missing a slash in the endpoint.

```
10.0.1.1 - - [19/Nov/2017:23:49:32 +0000] "POST /apifolders HTTP/1.1" 404 18 0.0013
10.0.1.1 - - [20/Nov/2017:03:21:19 +0000] "POST /api/folders HTTP/1.1" 200 214 0.2575
```

**Comment by kspearrin** [comment]
Fixed for next version. Thanks.
