### ISSUE TITLE
iOS 15.4 app crashes on scroll

### ISSUE THREAD

**Issue by trparky** [bitwarden/mobile#1745]
### Steps To Reproduce

1. Upgrade to iOS 15.4 Public Beta.
2. Open iOS app.
3. Attempt to scroll.
4. Watch it crash back to the home screen.

### Expected Result

Well, it would be kind of obvious that the app wouldn't crash; right?

### Actual Result

App crashes instead of the app properly working.

### Operating System

iOS

### Operating System Version

15.4

### Device

iPhone 13 Pro

### Build Version

2.15.0 (1225)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

Thanks for reaching out and sorry to hear about the trouble you are having. Please remember that beta versions of mobile operating systems are not targeted for official support. Using said versions may or may not lead to decreased functionality and are to be used at your own risk.
​
Regardless, we are going to take note of the issue and see if further beta releases improve this further.

In the meantime, you can still access Bitwarden in your mobile browser at https://vault.bitwarden.com/#/, or you can check out Apple's support article on uninstalling the beta software: https://support.apple.com/en-us/HT203282

Let us know if there is anything else we can do for you.

**Comment by trparky** [comment]
Yeah I get it, but I thought that this was the whole point of beta testing new software; to find bugs before the public is affected by them.

**Comment by Chandler-Lu** [comment]
On iOS 15.4 Dev Beta 2 and Bitwarden 2.16.1, when scroll to bottom in setting tab, the app will crash.

**Comment by retoocs007** [comment]
Same on iOS 15.4 public beta 2. App version is 2.16.1
On My Vault page it scrolls fine until 21st favorite. On half (text) of 22nd favorite it crashes.

**Comment by trparky** [comment]
[BitwardeniOS-2022-02-16-150059.log](https://github.com/bitwarden/mobile/files/8083377/BitwardeniOS-2022-02-16-150059.log)
[BitwardeniOS-2022-02-16-150447.log](https://github.com/bitwarden/mobile/files/8083378/BitwardeniOS-2022-02-16-150447.log)
[BitwardeniOS-2022-02-16-150516.log](https://github.com/bitwarden/mobile/files/8083379/BitwardeniOS-2022-02-16-150516.log)
Here are some crash stack trace data.

**Comment by mportune-bw** [comment]
Sorry for the delay everyone, looking at this as soon as my phone is finished downloading 15.4...

**Comment by nasiralamreeki** [comment]
15.4 is now in RC and will release to public next week meaning this critical bug will roll out to most iOS users as most Bitwarden iOS users are now automatically updating

**Comment by trparky** [comment]
Yeah, this is definitely a showstopping bug here. Even on the RC this bug still exists and will impact a lot of people once iOS 15.4 is released and suffice it to say, and I really don't like saying this, but after all the issues with the Chrome extension BitWarden doesn't need any more bad publicity.

I was reporting this issue long ago so that this issue could have been addressed almost a month ago but now that we're a week away from release, now developers have to scramble to find and fix the issue whereas if my initial bug report had been taken more seriously back then, developers would not be running around like their hair is on fire.

**Comment by nasiralamreeki** [comment]
As a developer myself and a brand new Bitwarden user (premium) I am hoping this isn't the state of things 😬 it's definitely not the best first impression so far

**Comment by nasiralamreeki** [comment]
> Yeah, this is definitely a showstopping bug here. Even on the RC this bug still exists and will impact a lot of people once iOS 15.4 is released and suffice it to say, and I really don't like saying this, but after all the issues with the Chrome extension BitWarden doesn't need any more bad publicity.
> 
> 
> 
> I was reporting this issue long ago so that this issue could have been addressed almost a month ago but now that we're a week away from the release of iOS 15.4, now developers have to scramble to find and fix the issue whereas if my initial bug report had been taken more seriously back then, developers would not be running around like their hair is on fire.
> 
> 
> 
> But excuse me for trying to help out. It really makes me think that input like is appreciated. /s

As a developer myself and a brand new Bitwarden user (premium) I am hoping this isn't the state of things 😬 it's definitely not the best first impression so far.

**Comment by trparky** [comment]
> > Yeah, this is definitely a showstopping bug here. Even on the RC this bug still exists and will impact a lot of people once iOS 15.4 is released and suffice it to say, and I really don't like saying this, but after all the issues with the Chrome extension BitWarden doesn't need any more bad publicity.
> > I was reporting this issue long ago so that this issue could have been addressed almost a month ago but now that we're a week away from the release of iOS 15.4, now developers have to scramble to find and fix the issue whereas if my initial bug report had been taken more seriously back then, developers would not be running around like their hair is on fire.
> > But excuse me for trying to help out. It really makes me think that input like is appreciated. /s
> 
> As a developer myself and a brand new Bitwarden user (premium) I am hoping this isn't the state of things 😬 it's definitely not the best first impression so far.

Exactly. I filed the initial bug report and was instantly told...
> Please remember that beta versions of mobile operating systems are not targeted for official support. Using said versions may or may not lead to decreased functionality and are to be used at your own risk.

OK, cool. But isn't that the point of beta testing? To find the bugs before the general public has to deal with them. I don't know about you but that blasé attitude about my bug report really made me think my input meant jack shit.

**Comment by vvolkgang** [comment]
Hi! Quick update, just wanted to let you know the team is actively trying to solve this. Thanks for all the reports!

**Comment by vvolkgang** [comment]
@trparky, we do appreciate the report and your feedback and it’s unfortunate that you’ve taken such offense to our response. I agree we can certainly do better at how we communicate during our first response, however our customer success team, in helping us triage issues as they come in, respond with our official stance on support for beta platforms/software, as well as provide some first response help just in case users are stuck and need other means to access their vault, not necessarily for the reporter but for everyone else that has the same problem and comes looking for solutions. In this instance we could have done better and we will communicate with the team accordingly as we’re always looking to improve our processes and communication internally and externally with our community. I personally checked this as soon as I saw your comment on Reddit and made sure we planned for it internally.

As with most Beta related issues on our mobile client, it's down to something Xamarin or Xamarin Forms needs to improve or address during public Beta cycles of target platforms, and previously they've fixed these kinds of issues prior to the final public release (while we’ve unnecessarily spun our wheels and burned many hours trying to find fixes in the meantime). This has, at least to now, created some natural pause when reports of issues come through for users of beta platforms.

While this is definitely an issue within Xamarin forms, we're not waiting for a fix to come through, the team is working on workarounds for the time being and we'll update this as soon as we can.

Thanks again to everyone who submitted debug info, it helped us a lot pinpointing the issue!

**Comment by Tataru-Taru** [comment]
This might be a side effect of the scrolling issue. But it seems that organisations are missing, you can see the small gap at the bottom where it would be, just before the app crashes.

**Comment by vvolkgang** [comment]
Issue closed automatically due to being to the PR fixing it, reopening until the fix is deployed.

Apple just released 15.4 ahead of schedule, we're releasing an hotfix today.

**Comment by mportune-bw** [comment]
Everyone, we're still waiting for Apple to approve the update, but in the meantime our just-released TestFlight beta includes this fix plus the new multi-account feature: 

https://testflight.apple.com/join/595lFH7U

**Comment by trparky** [comment]
Very good, I just downloaded the TestFlight version and I can (happily) report that the app no longer crashes.

**Comment by nasiralamreeki** [comment]
@mportune-bw in the future might be a good idea for your team to test on iOS betas and get fixes like this out before the next release. As a brand new user and premium customer this isn't a great look.

**Comment by trparky** [comment]
> @mportune-bw in the future might be a good idea for your team to test on iOS betas and get fixes like this out before the next release. As a brand new user and premium customer this isn't a great look.

That's what I was saying too. This whole fiasco could've been avoided had Bitwarden taken the time to test on the public betas of iOS 15.4. That is, after all, why Apple releases public beta versions. So that situations like this can be avoided.

**Comment by vvolkgang** [comment]
Closing the ticket as the issue is now fixed, thanks again for the report!
