### ISSUE TITLE
Sometimes "Password Generator" screen bottom gets truncated if Android system's font size is set to larger than default

### ISSUE THREAD

**Issue by ElTopo** [bitwarden/mobile#1770]
### Steps To Reproduce

1. Go to Android system Setttings / Display / Advanced / Font size, set font size to larger than default, for example, "Largest"
2. Open Bitwarden app, tap on "Generator" button, change type to "Password"
3. Scroll to screen bottom

Sometimes the "Minimum Special" portion gets truncated off and only partially visible.

Here's a screenshot:
![photo_2022-02-11_10-52-55](https://user-images.githubusercontent.com/217195/153652164-e81c5e3c-578d-4026-8b00-26cf6908f673.jpg)

### Expected Result

"Minimum Special" portion should be fully visible even if user uses a large font size.

### Actual Result

"Minimum Special" portion sometimes gets truncated (not always, but it happens when user opens Bitwarden app first time after closing it).

### Operating System

Android

### Operating System Version

Android 12, Android 11, Android 10.

### Device

This happens on all my phones, including Essential Phone PH-1, Google Pixel 2, Moto g7 play..

### Build Version

Version: 2.16.1 (4306)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by mportune-bw** [comment]
@fedemkr We have history with this XF bug affecting off-screen drawing (see https://app.asana.com/0/1166330464508357/1200531933783245).  Curious if you have any thoughts on a better way to handle it, or if you can just fix XF :)

**Comment by fedemkr** [comment]
There is an internal issue with the Xamarin Forms library but I've introduced a workaround to fix this. However, we should keep track of the Xamarin PR: [Make sure ScrollViewRenderer on Android is resolving layout changes](https://github.com/xamarin/Xamarin.Forms/pull/15076) that may fix this without the need of the workaround when it gets released.
