### ISSUE TITLE
[Feature Request] Add option to opt-out from HockeyApp crash reporting

### ISSUE THREAD

**Issue by pzmarzly** [bitwarden/mobile#178]
Or at least, ShouldAutoUploadCrashes() could also use "Disable Analytics" setting.

Thankfully, the report [doesn't contain that much information](https://github.com/bitstadium/HockeySDK-Android/blob/master/hockeysdk/src/main/java/net/hockeyapp/android/objects/CrashDetails.java#L24) but I can imagine someone may want to have no outgoing Internet traffic to any server except bitwarden.

**Comment by Primokorn** [comment]
HockeyApp appears in this privacy report:  
https://reports.exodus-privacy.eu.org/reports/391/  
https://reports.exodus-privacy.eu.org/trackers/26/  

@kspearrin Please consider adding an opt-out option like you did with Google analytics.

**Comment by kspearrin** [comment]
F-Droid build will not hack HockeyApp. Coming soon.
