### ISSUE TITLE
Wrong detection of domain: "Items for —" (em dash)

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/mobile#1794]
### Steps To Reproduce

2. Go to a website to access to your account
3. Click on the credentials fields then select Bitwarden to fill in the data

### Expected Result

Bitwarden should suggest the credentials for the selected domain

### Actual Result

Bitwarden shows no item for — (em dash)
I have a similar issue on another Android device where Bitwarden says "No results in vault for com.vivaldi.browser" - Vivaldi browser is the web browser I'm using.
Another user has the same issue: https://community.bitwarden.com/t/vivaldi-android-url-possible-bug/7944/2

### Screenshots or Videos

Not allowed in Bitwarden

### Additional Context

The problem happens with Vivaldi browser and apps (tested with the official Github for example)

### Operating System

Android

### Operating System Version

11

### Device

OnePlus 3T / Redmi Not 7

### Build Version

2.16.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Collectathon** [comment]
I can confirm this is the same for me as well with the Vivaldi browser (use Firefox shouldn't be the remedy, GeckoView still sucks on Android).

### Operating System

Android

### Operating System Version

12

### Device

POCO X3 Pro

### Build Version

2.16.2 (4334)

**Comment by Primokorn** [comment]
What happened to the support of Bitwarden? It was perfect when Kyle was there. He was responsive...

**Comment by vvolkgang** [comment]
Sorry for the delay @Primokorn, we are making efforts to squash autofill related issues, we were unable to reproduce this but are still trying with different devices. I'll get back to you as soon as we can reproduce / fix it. Thanks for the report!

**Comment by Primokorn** [comment]
@vvolkgang OK, I understand.
All auto-fill services are turned on.

I recently received an update of Vivaldi. Now I have v5.1.2567.52 and I can no longer reproduce.
I had this issue on 2 Android devices and it works fine today.

@Collectathon Do you still have this problem?

**Comment by Collectathon** [comment]
@Primokorn No, the latest update to Vivaldi seems to have fix this issue.

**Comment by Primokorn** [comment]
Good, then I close the issue.
