### ISSUE TITLE
Notifications for username & password

### ISSUE THREAD

**Issue by nlowe** [bitwarden/mobile#18]
The [keepassdroid](https://play.google.com/store/apps/details?id=com.android.keepass&hl=en) client spawns a notification for the username and a notification for the password when viewing an account / site entry. This allows the user to copy the username and password individually from the notification bar without having to switch app contexts. The notifications disappear after a few seconds or immediately if the database is locked or the app is suspended / closed.

**Comment by kspearrin** [comment]
This will be supported with #1 .

Closing as a duplicate.

**Comment by nlowe** [comment]
Thanks for the clarification, I wasn't sure if #1 covered this or not.

**Comment by kspearrin** [comment]
@nlowe I am using the keepassdroid app and I cannot find the functionality that you have described here. How do I get it to work? I do not see an accessibility service to enable this like some others.

**Comment by nlowe** [comment]
It seems to be a default setting, or something you can't turn off (I
couldn't find anything in the settings menu for it). After tapping an
entry, a notification is created for the username and password:

**Comment by nlowe** [comment]
It seems to be a default setting, or something you can't turn off (I couldn't find anything in the settings menu for it). After tapping an entry, a notification is created for the username and password:

![screenshot_20161219-080647](https://cloud.githubusercontent.com/assets/794251/21314116/4b89cf26-c5c3-11e6-8c65-e0a6daaf901f.png)

**Comment by nlowe** [comment]
Yeah, seems to be enabled for everything, see: https://github.com/bpellin/keepassdroid/blob/master/app/src/main/java/com/keepassdroid/EntryActivity.java#L170-L182

**Comment by kspearrin** [comment]
I see. I originally interpreted your description of this issue differently. This would be pretty easy to add.

**Comment by edsimpsons83** [comment]
Any update on this?
