### ISSUE TITLE
Pin code visible

### ISSUE THREAD

**Issue by rggjan** [bitwarden/mobile#180]
With the latest version on Android, the pin code unlock is buggy: While it shows "dots" on top, it also shows the pincode in plaintext below, which is not very secure (this happens with the "set pin" screen, as in the screenshot, as well as when actually unlocking):

![img_7575](https://user-images.githubusercontent.com/128554/33116627-cad5198c-cf65-11e7-93f4-013ff4b04de9.JPG)

**Comment by kspearrin** [comment]
That's weird. What version of Android? Also, what version of bitwarden (Settings -> About)?

**Comment by rggjan** [comment]
bitwarden 1.12.1 (1031)
Android 7.0 on Samsung Galaxy S7 edge

Happy to test / help debug on my phone

**Comment by rggjan** [comment]
Also, this didn't happen with older versions, as far as I can remember...

**Comment by kspearrin** [comment]
1.12.1 has been out for a few weeks so it is not that new. Did this just start happening?

**Comment by rggjan** [comment]
I didn't remember any specific action from my side that would have triggered this behaviour.

Also, the problem exists for some time, I just didn't report it sooner. So it could still be an issue with the latest version...

**Comment by oshank** [comment]
Same issue with me, it's been happening for a few weeks, but I was waiting for an update. Just updated to 1.13.0 on Android 6.0 LG G4 and it is still occurring.

**Comment by kspearrin** [comment]
I just patched this in the current build which is now available on the Google Play beta program. Can you try it there and let me know if it's resolved?

**Comment by oshank** [comment]
I'm unsure how to join the Beta program. If you could point me in the right direction, that would be great!

**Comment by kspearrin** [comment]
https://play.google.com/apps/testing/com.x8bit.bitwarden

**Comment by oshank** [comment]
Yes, this issue has been resolved for me.

**Comment by rggjan** [comment]
I can confirm this is fixed.
