### ISSUE TITLE
Unable to toggle Always Scan to off

### ISSUE THREAD

**Issue by ieno** [bitwarden/mobile#182]
Whenever I try to turn off the Always Scan option, it always resets back to the on setting as soon as I reopen the features page.

Steps:
1. Navigate to Settings - Features
2. Under Auto-fill Service disable Always Scan
3. Exit out of the features page
4. Reopen features page
5. Always Scan toggle is back to enabled

Nokia 8
Android 7.1.1
bitwarden 1.12.1 (1031)

**Comment by kspearrin** [comment]
Did you enable one of the other settings? One of them has to be on.

**Comment by ieno** [comment]
Ah, no I did not. Why can't it be disabled entirely, if I may ask?

**Comment by kspearrin** [comment]
Because you need 1 of the 3 settings for it to work. If you dont want to use it at all, then disable the autofill service from accessibility settings.

**Comment by ieno** [comment]
Aha, thanks for the clarification! Even when disabling it from accessibility, one of the toggles still has to be on though? I find this all a bit counter-intuitive, but I'll close this off. Cheers!
