### ISSUE TITLE
Microsoft Tracker in F-droid app version

### ISSUE THREAD

**Issue by minimalist-on-github** [bitwarden/mobile#1828]
### Steps To Reproduce

1. Open trackers analyser, such as Aurora Warden.
2. Scan app for trackers.
3. You will see that Bitwarden has tracker called ''Microsoft Appcenter Crashes''

### Expected Result

I think that F-droid version shouldn't contain any trackers.

### Actual Result

There's a tracker.

### Screenshots or Videos

![IMG_20220306_213252](https://user-images.githubusercontent.com/101062623/156937093-037035ce-aa4b-4461-97fb-a9148b2ab22c.jpg)

### Additional Context

Open-source app in F-droid shouldn't contain any trackers! I think it is a bug, not security issue. Bitwarden team should remove this tracker as soon as possible.

### Operating System

Android

### Operating System Version

11 RKQ1.200826.002

### Device

POCO X3 NFC

### Build Version

Version: 2.16.2 (4334)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by kspearrin** [comment]
Looks like something in our CI build is not properly removing App Center packages. Perhaps some package name has changed over time and we haven't updated CI accordingly?

@mportune-bw @joseph-flinn

**Comment by fedemkr** [comment]
@joseph-flinn the package `Microsoft.AppCenter.Crashes` was added in `Core.csproj` as well, so we'd need to remove it from there as well (right now it's only removing it from `App.csproj`)
I can do it if you need me to.

**Comment by ralyodio** [comment]
this is horrific. i thought bitwarden were the good guys, apparently not.
