### ISSUE TITLE
Increase view page copy button tap area

### ISSUE THREAD

**Issue by apastuszak** [bitwarden/mobile#184]
The copy button for username works. For password nothing happens.

**Comment by kspearrin** [comment]
There are multiple copy buttons. Which one ?

**Comment by apastuszak** [comment]
Under View Item.

**Comment by kspearrin** [comment]
I just tried it on Android and it works fine?

**Comment by kspearrin** [comment]
Whoops. Saw you said iOS in title. Just tested iOS as well and all good there too... ?

**Comment by apastuszak** [comment]
If I click on the 3 dots and choose 'Copy Password', that works.  But if I
click on item to open it up and click on the username, I get a popup across
the bottom telling me the username was copied and the username line
"bilnks."  If I click on password, the line "blinks," I get no message that
the password was copied, and the paste buffer is empty when I try and paste
the password.  Clicking on the eye works.  I click on that and I can see
the password.  But the copy icon next to it doesn't seem to work for me.
If this is not a bug, close this and I will file a support request instead.

**Comment by kspearrin** [comment]
@apastuszak It sounds like you are missing the copy button with your, which is why it is blinking instead. Perhaps we need to make the button tap surface larger.

**Comment by apastuszak** [comment]
I got it working now.  Needed to click a little more to the left.  I 
think this needs to be chocked up to user error.

Though it would be nice if the contact area extended to the right edge 
of the screen.

**Comment by kspearrin** [comment]
We'll look into making the tap area larger.

**Comment by kspearrin** [comment]
Fixed next release.
