### ISSUE TITLE
Android Firefox login - 2FA token invalid

### ISSUE THREAD

**Issue by ryanjoachim** [bitwarden/mobile#186]
Added the Bitwarden addon to Firefox. Opened it up, logged in, and was prompted for my 2FA code from Google Authenticator.

Tried it several times with different codes, and also tried with a backup code with no success. Each time got a "two-factor token is invalid" error.

The time is synced in the authenticator app, and other codes work for other apps.

Moto Force Z with the latest version (7.1.1) and the latest version of Firefox from the Play Store.

**Comment by kspearrin** [comment]
How about logging into the web vault?

**Comment by ryanjoachim** [comment]
I am logged in to the vault with the app as well as in the browser.

**Comment by ryanjoachim** [comment]
Ignore me. Totally user error.
