### ISSUE TITLE
App keeps asking for 2FA even though I've checked the "remember me" checkbox.

### ISSUE THREAD

**Issue by thericle** [bitwarden/mobile#1860]
### Steps To Reproduce

1. Log in with my password.
2. Fill in the TOTP, checking the "remember me" box.
3. Log-out
4. Try to log in again.

### Expected Result

I'd expect that I wouldn't need a TOTP again.

### Actual Result

It asks for a TOTP again.

### Additional Context

It keeps asking me for 2FA every time I log out.

### Operating System

Android

### Operating System Version

MIUI Global 12.5.6

### Device

Xiaomi Redmi Note 8 Pro

### Build Version

2.16.2 (4334)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Closing this now, as it was addressed with #1921
