### ISSUE TITLE
(Android) Bitwarden vault not locking upon locking the phone.

### ISSUE THREAD

**Issue by nahcos** [bitwarden/mobile#1867]
### Steps To Reproduce

1. Go to Settings and make sure that Vault Timeout is set to anything but Immediately. I set it up to 15 minutes.
2. Vault timeout action is set to Lock.
3. Unlock with biometrics is disabled. 
4. Unlock with PIN is enabled.

### Expected Result

Based on the settings above, the expected behaviour was for the vault to remain unlocked for 15 minutes, as long the phone does not get locked within this time. Should the phone get locked however, the vault is expected to get locked regardless of the set timeout (condition set in settings #2 above) - but it does NOT.

### Actual Result

Upon locking & unlocking the phone, the vault remains unlocked and it can be accessed without requiring the PIN. Assume that locking, unlocking and accessing the vault take place within the set timeout (15 minute, in my case)
The described behaviour (bug) is consistent across three different Android devices: Samsung S20 (Android 10), Samsung S8 (Android 10) and Samsung A5 (Android 8) 

All phones are also locked by PIN (Android)

### Screenshots or Videos

N/A

### Additional Context

Bitwarden was installed from Aurora Droid Store - Bitwarden repository. 

### Operating System

Android

### Operating System Version

Android 10

### Device

Samsung Galaxy S20 (SM-G980F)

### Build Version

2.17.0 (4526)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by jlf0dev** [comment]
Hi @nahcos, thanks for the report! Unfortunately we're stuck here by platform restrictions on iOS that don't allow us to check when the screen locks. I'd rather maintain the same functionality between platforms, so I'm going to close this for now. If you have ideas though feel free to reach out and I can re-open this.
