### ISSUE TITLE
iPadOS: Wheel Pickers Dead

### ISSUE THREAD

**Issue by adrianschlatter** [bitwarden/mobile#1872]
### Steps To Reproduce

1. Open Bitwarden App on iPad
2. Tap "+" in upper right corner to create new entry
3. Tap "Type" field => wheel picker appears
4. Turn wheel picker to select something different than what was already selected
5. Try to select it

### Expected Result

New type is selected, wheel picker closes, new type is shown in type field.

### Actual Result

Wheel picker does not close. When closed "manually" (by tapping somewhere in the background), entry is not selected and is not shown in type field.

### Screenshots or Videos

<img width="534" alt="image" src="https://user-images.githubusercontent.com/10478149/161610575-4b002dff-fde8-4de7-9531-987123146bf0.png">

### Additional Context

The same behavior is observed in other fields using wheel pickers such as:

* New entry => Folder
* Settings => Options => Design
* Settings => Options => Clear Clipboard ("Zwischenablage leeren" in German)

I suspect it happens with every wheel picker Bitwarden tries to use.

### Operating System

iOS

### Operating System Version

iPadOS 15.3.1

### Device

iPad Pro (11")

### Build Version

2.17.0 (1626)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by yashwalter12** [comment]
Hello @adrianschlatter  On the iPad when we tried it, it is picking the type we are choosing. If it is still happening could you add some more details.
1. Whether it happens when you change the existing selection of type
2. Did you select the type and clicked outside of the wheel picker or clicked on done

**Comment by adrianschlatter** [comment]
Thanks for looking into this! Regarding:

0. Yes, it still happens 
1. As opposed to selecting the same value that was already there? The question confuses me somewhat. Yes, it happens when I try to change the selection
2. Done button? What done button?

**Comment by knhash** [comment]
> I suspect it happens with every wheel picker Bitwarden tries to use.
Can confirm. Happens to me in the Generator tab, unable to choose Passphrase option in the wheel picker.

**Comment by aj-bw** [comment]
Hi @adrianschlatter and @knhash,

This is related to using the floating keyboard on iPad ( the small version of the keyboard you can drag around ) - https://support.apple.com/en-us/HT210758 . When you are using the floating keyboard, the wheel picker menu "pops out" versus spawning at the bottom half of the screen. However, in testing when I used the floating keyboard I still see a Done button present in a banner along the bottom right of the screen. Will attach a screenshot below.

I verified this across multiple iPads, iPad OS and Bitwarden app versions. I will close the issue, if the issue were to persist please do not hesitate to respond to this thread, or contact our support team using our [Contact page](https://bitwarden.com/contact)[.](https://bitwarden.com/contact.) You can include a link to this issue in the message content.

![IMG_32CE25BAFABE-1](https://user-images.githubusercontent.com/81774843/185953769-8203b724-6556-4e5e-a5ab-bb3cb1ce4e7f.jpeg)
