### ISSUE TITLE
Cannot save new login if personal ownership is disabled

### ISSUE THREAD

**Issue by YPPLz5vcO8VCKylaX1IodY5acM1LTk01YYwuqRR** [bitwarden/mobile#1874]
### Steps To Reproduce

1. disable personal ownership in the organization policy
2. go to any site (cnn.com) in mobile Safari and try to create new login using Bitwarden extension

### Expected Result

Login saved

### Actual Result

Extension hands on saving new login
New login is not saved

### Additional Context

Extension does not offer to set the collection for the new login and it is mandatory when personal ownership is disabled. 

Proposed Solution(s):
1. Add the ability to select collections for the new item
2. Add the ability to define default collection for the new items (per organization, for the person or both).  This collection should be applied to new items by default if not specified otherwise.

### Operating System

iOS

### Operating System Version

15.4.1

### Device

iPhone 13 Pro Max

### Build Version

12.17.0 (1626)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by micahblut** [comment]
Hello all, this item has been resolved in the new native apps. These apps are currently in [open beta](https://community.bitwarden.com/t/about-the-beta-program/39185), and will be generally available soon.

**Comment by Gerardv514** [comment]
@micahblut is this still a work in progress? I just tested this on the native app and we receive an error stating due to an organizational policy you cannot save to personal vault. We don't have personal vault turned on since personal ownership is disabled.

**Comment by micahblut** [comment]
@Gerardv514 can you clarify which of the native apps you are testing on?

When I test this flow, I see a message at the top of the item creation form informing me that an organization policy affects my ownership options. When I try to save without selecting a collection, I see a message that I need to select a collection. When I select a collection and save, the item is saved.

https://github.com/user-attachments/assets/b86708f1-573d-4822-90c2-6b4a952842d1

**Comment by Gerardv514** [comment]
Testing in iOS iPhone 14 Pro native app 2024.7.0 (1194). 

Looking at your video, is that iOS? It appears very different.

**Comment by micahblut** [comment]
> Testing in iOS iPhone 14 Pro native app 2024.7.0 (1194).
> 
> Looking at your video, is that iOS? It appears very different.

Yes, this is iOS. Here are instructions for getting the iOS beta: [https://community.bitwarden.com/t/about-the-beta-program/39185](https://community.bitwarden.com/t/about-the-beta-program/39185 )
