### ISSUE TITLE
"Sync Failed" experience is poor

### ISSUE THREAD

**Issue by snarkywolverine** [bitwarden/mobile#1883]
### Steps To Reproduce

For some reason, my device can't sync with the server.  I've seen on Reddit that uninstall/reinstall is a good way to solve this (which I haven't yet tried).

The issue I have is twofold:

(1) When I do a pulldown from the top (to force a sync), there's no status indication at all.  In an earlier version, it said "Sync Complete", which is wrong; now, there's no progress or failure notification.  The app should tell me somehow (popup text is the easiest, though a banner of some kind would be better) that the latest attempt to sync has failed.

(2) The entirety of the debugging information is "Sync failed".  Nothing about connection to the server, or invalid certificates, or anything... just 'failed'.  A little more context would be helpful -- give me a clue if I should be restarting the app or reinstalling or ... something.

### Expected Result

See above.  I expect to see the failure on the main page, and would like additional logs to be visible from ... somewhere.

### Actual Result

"Sync Failed"

### Operating System

Android

### Operating System Version

12

### Device

Galaxy A32 5G

### Build Version

2.17.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by yashwalter12** [comment]
Hello @snarkywolverine  This is working as intended. The sync doesn't show up any notification when you pull down from the top. If you feel like this behavior should be different you are welcome to open a feature request.

This issue will now be closed. Thanks!
