### ISSUE TITLE
Newest beta Bitwarden now wont load

### ISSUE THREAD

**Issue by BigNickBurgess** [bitwarden/mobile#189]
Updated to the latest beta this morning and afterwards bitwarden just sits on the bitwarden logo now.

I cleared the cache and storage and re-logged in (it let me) but after that opening the app again just sits on the bitwarden logo again.

Autofill shows as Vault locked and clicking this to unlock just sits on an empty screen as though its trying to load bitwarden,

Samsung Galaxy S8 Oreo beta 3 (and hotfix)

**Comment by kspearrin** [comment]
Hi, should be fixed now with updated build 1119. Sorry!
