### ISSUE TITLE
Bitwarden mobile autofills in twitter search bar

### ISSUE THREAD

**Issue by lY3u3cERdXvdBQe6oxYQsizF6MAu7yBOZK7knMs** [bitwarden/mobile#1897]
### Steps To Reproduce

1. Go to the Twitter app
2. Click on search tab 
3. click search field 
4. Start typing

### Expected Result

I expected the bit warden app to recognize this as a text field. Not a form.

### Actual Result

It offered to autofill saved passwords and or store them for me.

### Additional Context

OS android 12

 Grammarly keyboard

Apps installed trough google play

### Operating System

Android

### Operating System Version

12

### Device

Samsung Galaxy A51

### Build Version

2.18.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by quantumfallout** [comment]
This issue still exists in 2024.6.1-beta (11139)

**Comment by vvolkgang** [comment]
@quantumfallout can you test the most recent update and if that's still happening, create a new report in [bitwarden/android](https://github.com/bitwarden/android) please?
