### ISSUE TITLE
Can't press top bar buttons in portrait mode

### ISSUE THREAD

**Issue by d1RToW9x1IOJeSnhge4nfwcDQalLkaowJBEAZOh** [bitwarden/mobile#1899]
### Steps To Reproduce

1. Open the app
2. Click on any button in the top bar
3. Observe that nothing happens
4. Rotate the phone to get it into landscape mode
5. Do step 2
6. Observe that it works as expected 

### Expected Result

Button presses should work irrespective of the orientation

### Actual Result

Button presses in the top bar don't work in portrait mode

### Screenshots or Videos

Bitwarden doesn't allow taking screenshots/videos, so I can't add anything here.

### Operating System

Android

### Operating System Version

10

### Device

Xiaomi POCO F1

### Build Version

12.0.3.0 MIUI

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hello everyone,

Please try reproducing the issue with the beta version of the native app. The beta program can be joined and the app downloaded from [here](https://community.bitwarden.com/t/about-the-beta-program/39185).

Recent updates have been made in the native builds, so it would be helpful to check if the issue still occurs with the latest version. 

Thank you for your cooperation, and looking forward to the feedback!
