### ISSUE TITLE
Account Switching Not Possible When Current Vault is Unlocked

### ISSUE THREAD

**Issue by dohlin** [bitwarden/mobile#1900]
### Steps To Reproduce

1. Add 2+ accounts to BW Android mobile app (unsure about iOS)
2. Ensure the account that is currently selected is unlocked (we'll call this account #1)
3. Use Chrome (or another app) to find a login page and use the BW pop-up to start the auto fill activity
4. BW's auto fill activity redirect does not provide any way to switch to account #2 to pull creds from there
5. All accounts (or at least the currently selected account in the main BW app) must be locked or account switching during autofill on Android is not possible without the lengthy bypass steps I laid out in the other post I made further explaining this issue here: https://community.bitwarden.com/t/mobile-app-allow-account-switching-ability-during-autofill/41028/5

Hopefully that all makes sense.

### Expected Result

One should be able to change BW accounts from any auto fill screen I would think.  This seems like a bug or at least unintended behavior to me.

### Actual Result

Per above, to switch accounts you must:

- cancel the autofill action
- close the browser (or other app)
- open & unlock the BW main app
- use the account switcher to open & authenticate to the account that contains the creds you’re actually trying to fill
- close the BW app
- re-open the browser window
- re-trigger the autofill action
- select the appropriate cred
- bonus points if you’re like me and 90% of your autofills come from one account, then you can do all of this over again to switch back to your “primary” BW account so it’s most likely on the right account for your next autofill

### Operating System

Android

### Device

Galaxy S22 Ultra

### Build Version

2.18.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by fedemkr** [comment]
Hi @dohlin thank you very much for your report. Currently we are working on enabling Account Switching on Autofill on both Android and iOS so you will be able to use it soon.
