### ISSUE TITLE
iOS: broken/missing character displays for linked and boolean custom fields

### ISSUE THREAD

**Issue by patrickhlauke** [bitwarden/mobile#1903]
### Steps To Reproduce

1. Go to view a cipher/item with custom fields for "Linked" and "Boolean"

### Expected Result

Linked custom field to show the linked icon (the chain/link glyph), and for the boolean to show a checkbox-like icon

### Actual Result

The icons show up as broken/unknown glyph

### Screenshots or Videos

<img width="375" alt="cropped screenshot of custom fields in a cipher, showing the 'box with a question mark' unknown glyph icon for a linked and a boolean custom field" src="https://user-images.githubusercontent.com/895831/167794428-3e16645d-cfee-4d33-a6e4-fb3b951048b9.png">

### Operating System

iOS

### Operating System Version

15.4.1

### Device

iPhone SE (2020)

### Build Version

2.18.0 (1672)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by junyuan-z** [comment]
i was trying to fix this problem but it seems this bug does not exist anymore at least on the master branch.

**Comment by junyuan-z** [comment]
it is fixed by: https://github.com/bitwarden/mobile/commit/8168089591f5c6081cde81a5515a21f2abce6363

**Comment by patrickhlauke** [comment]
Excellent news. I'll close this once I can verify it (next release?)

**Comment by patrickhlauke** [comment]
Any idea when the fixed version will be released?

**Comment by fedemkr** [comment]
It should have been fixed by version 2022.6.0, which version do you have @patrickhlauke? Are you still experiencing the issue?

**Comment by patrickhlauke** [comment]
hah, when I checked this morning, it was still showing as a broken glyph.  checking now though, it's fixed. must have only received the update at some point during the day.

confirming that it's looking good. closing the issue.

<img width="375" alt="Screenshot 2022-07-08 at 23 07 04" src="https://user-images.githubusercontent.com/895831/178076343-577e4ecf-93d7-4e9d-8fe9-66b1ec0c37a0.png">

**Comment by patrickhlauke** [comment]
warning though that i'll be posting a follow-up issue, as the screen-reader output of the "Some boolean" is still not accessible...but that's for another day :)

**Comment by patrickhlauke** [comment]
oh, also it seems that it shows the ticked checkbox there, even though my entry has an unticked checkbox. some more refactoring needed, again will post as separate issue...
