### ISSUE TITLE
iOS 12.5.5 Blank screen for password history

### ISSUE THREAD

**Issue by june8-o** [bitwarden/mobile#1904]
### Steps To Reproduce

1. Go to Account
2. Click on any account
3. Scroll down to bottom
4. Click onto a count of password changed

### Expected Result

Password history.

### Actual Result

Blank screen.

### Operating System

iOS

### Operating System Version

12.5.5

### Device

iPhone6

### Build Version

1.18.0 (1672)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Umiamz** [comment]
I can confirm the same issue - iPhone 13 Pro Max running iOS 15.4.1.

**Comment by martinorob** [comment]
Same issue here iPhone 12 Pro iOS 15.4.1

**Comment by kalGITHUB** [comment]
Same issue here. iPhone 13 Pro on iOS 15.4.1.

App version 2.18.0

Uninstalled and reinstalled didn’t solve the issue.
![4DD66049-B0ED-4F6D-964C-33D9FB9F93DB](https://user-images.githubusercontent.com/57609475/168489279-d2b86e65-1e2b-4ba7-8945-09c6ee6a09bc.png)

**Comment by MingMZ** [comment]
Came here to report same issue

Bitwarden Version 1.18.0 (1672) on iOS 15.5.
