### ISSUE TITLE
Chrome Web - Copying from a hidden file while in Edit Mode does not work

### ISSUE THREAD

**Issue by JaPossert** [bitwarden/mobile#1911]
### Steps To Reproduce

1. Open bitwarden in google chrome 
2. open a password file
3. Click on 'view' 
4. Click on "edit" 
5. Hidden password does not copy, not even the dots that it copies when in view mode that are not visible.

### Expected Result

I would expect to either see a string of dots as I do when the password is hidden in view mode
 or, that is my preference, to copy the password while it is hideen (as occurs when just clicking on the password button when seeing a password file.
It would be ideal to have an (advanced) setting where one can choose if one just copies a string of dots or the actual password (this could be the default for easier onboarding of users).

### Actual Result

no copying occurs at all

### Additional Context

the operating system in this case is Windows 10, Google Chrome latest version as of time of writing (not Android as mandatorily indicated below
I suggest to remove this as a mandatory option or even better to include Chrome and all the other modes of opening

### Operating System

Android

### Build Version

Version: 1.58.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by chewiebug** [comment]
@JaPossert I suspect, you should create your issue in the https://github.com/bitwarden/clients project. That's for all clients except the android one.

**Comment by JaPossert** [comment]
Thank you @chewiebug  
Just republished it here:
https://github.com/bitwarden/clients/issues/4133

**Comment by djsmith85** [comment]
Closing this in favor of https://github.com/bitwarden/clients/issues/4133
