### ISSUE TITLE
Android Brave/Chrome support

### ISSUE THREAD

**Issue by fredgolightly** [bitwarden/mobile#195]
Will Bitwarden be updated to support these browsers for web-based logins via the new autofil api or is this something the browser has to allow for?

**Comment by gsora** [comment]
Sadly Google has to update AutoFill API. Right now it doesn't work with any text input view except native Android ones.

**Comment by kspearrin** [comment]
We already have support. It requires Google to release updates to the Autofill Framework to work on  websites/webviews.
