### ISSUE TITLE
Does the mobile app (iOS) support self-signed certs?

### ISSUE THREAD

**Issue by Jc2k** [bitwarden/mobile#196]
I've deployed bitwarden on my LAN. I don't plan to expose it publicly. So LetsEncrypt isn't really an option when using HTTP challenges (although I could probably do something with DNS if that was an option).

The web vault and the the browser extensions are working, but the iOS app is rejecting my attempts to log in.

I can access the web vault on my iOS device.

tcpdump shows the app is trying to connect to :443 on the VM, but its not showing up in the nginx logs.

Best guess is self-signed cert is silently failing to validate. Can the mobile apps support self-signed self-hosted deployments?

**Comment by kspearrin** [comment]
Yes, but you need to install your cert on the device so that it will trust it.
