### ISSUE TITLE
Android app doesn't log out properly when I change my master password in the web vault

### ISSUE THREAD

**Issue by jikamens** [bitwarden/mobile#1960]
### Steps To Reproduce

1. Ensure that you are logged into the Android app but it's locked, and biometric unlock is enabled.
2. Change your master password in the web vault.
3. Open the Android app.
4. It puts up a master password prompt but then a moment pops up the fingerprint reader.
5. Give your fingerprint to the fingerprint reader.
6. The app says it has unlocked your vault but the vault is empty, i.e., you get a blank "My Vault" screen.

### Expected Result

Android app should be logged out when you change your password password, forcing you to log in again.

### Actual Result

Android app thinks it's logged in when it actually isn't.

### Operating System

Android

### Operating System Version

Android 13 beta

### Device

Pixel 6

### Build Version

2022.05.0 (4636)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by bnagawiecki** [comment]
Hey @jikamens, 

Thanks for submitting this issue!

I have attempted to replicate this, but have not been able to. Can you re-test on the latest app, and let us know if it's still occurring for you? If it is, any additional information to assist in replicating would be appreciated.

**Comment by jikamens** [comment]
I am not seeing this anymore.
