### ISSUE TITLE
Auto-fill not launching [iOS]

### ISSUE THREAD

**Issue by bjafl** [bitwarden/mobile#1996]
### Steps To Reproduce

1. Go to any website login form and click on the password field to bring up the on screen keyboard.
2. Click on the password auto fill button on the iPhone keyboard.

### Expected Result

Launching the Bitwarden auto-fill window.

### Actual Result

Screen flashes briefly. Have experienced getting a glimpse of the bitwarden splash screen.

Auto fill window is not launched. 

### Screenshots or Videos

https://user-images.githubusercontent.com/34428001/179428809-a957a794-3d13-42bf-bfbd-e10fada1e865.MOV

### Additional Context

Auto fill and extension enabled in iOS settings. Auto fill functionality has worked on my device until recently.

### Operating System

iOS

### Operating System Version

15.5

### Device

iPhone 11

### Build Version

Versjon: 2022.6.1 (1895)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by mallegrini** [comment]
+1

**Comment by mhoerche** [comment]
It works!
Thank you!

Von meinem iPhone gesendet

**Comment by bjafl** [comment]
Yes, it works now! 🎉 Thank you 🙏

**Comment by jonyskids** [comment]
iPad updated to 17.4.1 Bitwarden no longer comes up?
