### ISSUE TITLE
iOS: Account switcher UI gets cut off on iPhone 13

### ISSUE THREAD

**Issue by WUVjKRkSHfvyhZCMkJDrzWjXHFvxNdXb3IgQ8Y5** [bitwarden/mobile#2003]
### Steps To Reproduce

Tap on the account switcher on the auto-fill screen. You'll see that the UI gets cut off on the right hand side. Screenshot attached below:

![v](https://user-images.githubusercontent.com/7050515/180364268-e9dc5d6a-6c88-439d-8246-cabdecc7f7ef.PNG)

### Operating System

iOS

### Operating System Version

15.6

### Device

iPhone 13

### Build Version

2022.6.2 (1951)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hello,

Please try reproducing the issue with the beta version of the native app. The beta program can be joined, and the app downloaded from here: https://community.bitwarden.com/t/about-the-beta-program/39185

Recent updates have been made in the beta builds, so it would be helpful to check if the issue still occurs with the latest version.

Thank you for your cooperation, and looking forward to the feedback!
