### ISSUE TITLE
iOS app does not seem to return items when saved with special characters such as tilde

### ISSUE THREAD

**Issue by martincoco** [bitwarden/mobile#2008]
### Steps To Reproduce

When searching in the iOS app, for example, the word "debito", I don't get any results if the item is "débito". 

### Expected Result

While behavior is technically correct, as they are indeed different words, the Chrome version, for example, does return items regardless if I search for "debito" or "débito". It would be nice that the iOS client shared the same behavior as the Chrome app, as it makes it easier to find results, especially if you're on mobile, where typing tildes or special characters is harder.

### Actual Result

No results are returned when looking for "debito" if item is saved as "débito".

### Operating System

iOS

### Device

iPhone 13 Pro

### Build Version

2022.6.1 (1895)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by dbosompem** [comment]
Hi @martincoco , thank you for pointing this out. We'd try and reproduce this from our end to confirm. A PR to resolve this issue is also welcome by anyone who would want to contribute.

**Comment by Rlcolli4** [comment]
Hey! So I saw that this has been closed but I think I found an issue that may still be around from this (unless the behavior is not intended) but some special characters still break the search. For instance, a tildy in the name of an item doesn’t show up when searched for.
![Uploading 35272F91-22A9-42B1-8014-A38BFBBE06C8.jpeg…]()

**Comment by Rlcolli4** [comment]
(I tried uploading these with the original comment but they didn't go through, so here are some screenshots from my device as an example)
![IMG-0756](https://user-images.githubusercontent.com/12074293/216658680-e3d14c90-ce9d-4ac1-928c-040daeaa05a9.jpg)
![IMG-0757](https://user-images.githubusercontent.com/12074293/216658691-3c6183fa-465e-4d8b-814d-ddaa6b215e4a.jpg)
