### ISSUE TITLE
Android: Label of terms of service and privacy policy switch is too close to the actual switch in the sign-up screen

### ISSUE THREAD

**Issue by waldyrious** [bitwarden/mobile#2009]
### Steps To Reproduce

1. Install the app
2. Open it for the first time
3. Click the "Create Account" option
4. Toggle the switch labeled "By activating this switch you agree to the following: Terms of Service, Privacy Policy"

### Expected Result

There should be a comfortable visual gap between the switch control and its label

### Actual Result

The switch control almost overlaps the label.

### Screenshots or Videos

![20220724_161937](https://user-images.githubusercontent.com/478237/180654269-a2391aeb-0ee7-44b9-ae36-23fa631b8a40.jpg)

### Operating System

Android

### Build Version

Version: 2022.6.2 (4851)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Closing this, as this was solved with https://github.com/bitwarden/mobile/pull/2021, thanks to @deividt !

This will be included in the upcoming release.
