### ISSUE TITLE
 In the vertical screen position, the top bar of the application does not react. 

### ISSUE THREAD

**Issue by mont4rdy** [bitwarden/mobile#2019]
### Steps To Reproduce

1. Put the screen of the smartphone in vertical position
2. Try to click on the search bar at the top

### Expected Result

Make a research. 

### Actual Result

When the Android phone is in the vertical screen position, the top bar of the application does not react. 
So it is not possible to click on the search utility, unless you switch the screen to horizontal position. 

### Additional Context

This bug has existed for months. You advised me on the play store to report this bug here.

### Operating System

Android

### Operating System Version

MIUI Global 12.0.4 Stable. 

### Device

Android Xiaomi RedMi Note 8 Pro

### Build Version

Android 10 QP1A. 190711.020

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vphan916** [comment]
Hi @mont4rdy!  Hope all is well.  Can you download the latest version and let us know if this problem persists?

**Comment by mont4rdy** [comment]
Thanks. Unfortunately, this problem persists.

**Comment by Larry-Sussman** [comment]
@mont4rdy sorry to hear that! There is an open (duplicate) issue with some workarounds available here:
https://github.com/bitwarden/mobile/issues/1899#issuecomment-1185230942

We're aware of this issue and are working to fix it. Thank you!
