### ISSUE TITLE
iOS requires entering Master Password every time

### ISSUE THREAD

**Issue by rjboczar** [bitwarden/mobile#2049]
### Steps To Reproduce

1. Install Bitwarden.
2. Sign in.
3. Enable Autofill in General -> Passwords.
4. Open Safari or an app with a login.
5. Click the autofill button to attempt to fill in the password.

### Expected Result

If logged in to Bitwarden and not timed out, the username and password should autofill. I shouldn't have to enter the master password for every login.

### Actual Result

The master password prompt comes up. If the master password is entered, the credentials are correctly filled in.

### Screenshots or Videos

This video shows me opening the Bitwarden app, unlocking the vault (timeout is set to lock at 4 hours), opening Safari, and opening github.com and icloud.com in tabs. I am asked to provide the master password for both.

https://user-images.githubusercontent.com/7197136/187053723-8e78a82a-465e-47fd-acc5-f0bd64ce8707.mp4

### Additional Context

Up until a week or two ago it would work correctly until Bitwarden would timeout. Tried allowing PIN, changing vault timer, enabling/re-enabling Passwords autofill + browser extension; none worked.

As an aside, the help page (https://bitwarden.com/help/auto-fill-ios/) seems to imply only one autofill method should be used (password Autofill vs browser). However, it seems like the Safari extension may be "stuck:" even after Bitwarden is un/reinstalled: both the Safari Bitwarden prompt and the keyboard Bitwarden prompt come up in Safari, and both require the master password.

### Operating System

iOS

### Operating System Version

15.6.1, also the previous one (updated to try to fix)

### Device

iPhone 12

### Build Version

2022.8.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by jordangeorge** [comment]
> Your issue appears to be describing the expected behavior of the software. iOS appears to limit our ability to have your vault remain unlocked for that prompt

I recently transitioned from LastPass to Bitwarden and this was not an issue with LastPass. Kind of disappointed that I did that without testing out this feature. My master password is usually long and complicated so this is a pain point. I have a "master password" to get into my phone so I don't love entering the Bitwarden master password in every time. Might look into other products as well.
