### ISSUE TITLE
[bug] bitwarden sometimes fails to display when clicking the `password` button on top of the keyboard

### ISSUE THREAD

**Issue by andylizf** [bitwarden/mobile#2058]
### Steps To Reproduce

The problem is, that it just occurs sometimes, even rarely.
1. Go to Settings on iOS
2. Log in an Apple ID
3. Click the `password` button on top of the keyboard

### Expected Result

The interface of Bitwarden passwords auto-filling pops up.

### Actual Result

The iOS default interface of the password auto-filling pops up.

### Operating System

iOS

### Operating System Version

15.5 (19F77)

### Device

iPhone Xs

### Build Version

2022.8.0 (2011)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by THEOCKID** [comment]
please give more details: what apps does this happen in? (or had happened in for you?).  how about a list of apps installed?  Browser used? etc.
