### ISSUE TITLE
Android 13 Yubikey login not working

### ISSUE THREAD

**Issue by varunyellina** [bitwarden/mobile#2060]
### Steps To Reproduce

1. Install Bitwarden on Freshly formatted Android 13 on Pixel 4a.
2. Try to login to Bitwarden
3. 2 Step login takes you to FIDO2 Webauth in a webview
4. Buttons pressed: Authenticate WebAuthn > Get Started > Use security key with USB > Tap the blinking gold disc ✅> Return to App

### Expected Result

It should log me in. This was not an issue on Android 12.

### Actual Result

1. Bitwarden app now shows "An error has occurred". Tap OK.
2. Tap "Try Again", but same issue again and again.

### Screenshots or Videos

![Screenshot_20220904-152503.png](https://user-images.githubusercontent.com/1850730/188309645-d8fae29f-c825-4524-9a18-595660fd6070.png)

### Operating System

Android

### Operating System Version

13

### Device

Google Pixel 4a

### Build Version

2022.8.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by varunyellina** [comment]
I was able to login to the apps using the same Yubikey on Android 13:

1. 1Password
2. Github Mobile

**Comment by vphan916** [comment]
Hi @varunyellina, thanks for submitting this ticket.  Unfortunately, we are unable to reproduce this.  Can you update to the latest version of our mobile app and let us know if this problem persist?  Thank you!

**Comment by varunyellina** [comment]
I was using the latest version of the app. The issue seems to be with your migration of existing keys from FIDO.

<img width="370" alt="Screenshot 2022-10-04 at 1 21 48 PM" src="https://user-images.githubusercontent.com/1850730/193767186-48e1d07f-2f34-446e-ade2-180b028b733c.png">

All keys with the tag "**Migrated from FIDO**" were unusable on the mobile app. I had to remove the keys and add them back to my account. They're working now.

**Comment by varunyellina** [comment]
Apparently this issue is not specific to Android 13. See here on [Reddit](https://www.reddit.com/r/Bitwarden/comments/wqihfm/comment/iqyh9xu/?utm_source=share&utm_medium=web2x&context=3)
