### ISSUE TITLE
Bitwarden name in Persian

### ISSUE THREAD

**Issue by xmha97** [bitwarden/mobile#2061]
### Steps To Reproduce

1. Change my phone language to Persian
2. Install Bitwarden (from Play Store)

### Expected Result

See Bitwarden app name shown in Persian (not English)
Bitwarden app name in Persian is:
"بیتواردن"

https://fa.m.wikipedia.org/wiki/%D8%A8%DB%8C%D8%AA%E2%80%8C%D9%88%D8%A7%D8%B1%D8%AF%D9%86

### Actual Result

See Bitwarden app name shown in English (not Persian)

### Screenshots or Videos

![IMG_۲۰۲۲۰۹۰۴_۱۶۴۹۰۴](https://user-images.githubusercontent.com/23485114/188313607-7a4d8499-b8cb-46ad-b989-8010dadafa98.jpg)

### Additional Context

If you want to serve the people of the world, you need to pay attention to their language.

### Operating System

Android

### Operating System Version

12

### Device

Xiaomi 11T

### Build Version

2022.8.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Hi @xmha97 thank you for your report.

We use a translation tool called Crowdin to help manage our localization efforts across many different languages. Our translations can only be updated using Crowdin.

If you are interested in helping translate a Bitwarden client into another language (or make a translation correction), please register an account at Crowdin and join our project here: https://crowdin.com/project/bitwarden-mobile

If the language that you are interested in translating is not already listed, create a new account on Crowdin, join the project, and contact one of project managers.

You can read Crowdin's getting started guide for translators here: https://support.crowdin.com/crowdin-intro/

If the translations on Crowdin do not match the translations on Github, please let us know and we will investigate.

**Comment by djsmith85** [comment]
The specific translation can be found here: https://crowdin.com/translate/bitwarden-mobile/45/en-fa#1237.

The current translation has more up-votes, that's why we currently display "Bitwarden".

**Comment by xmha97** [comment]
Please reopen this issue.
Crowdin won't let me change the app name.

```
App name. Shouldn't ever change.
```
![IMG_20221128_233856_730.jpg](https://user-images.githubusercontent.com/23485114/204371924-ff3b64f6-efab-4b5c-b029-f3639cccec83.jpg)

**Comment by djsmith85** [comment]
Hi @xmha97,

as per your screenshot, Crowdin has accepted your translation.
As stated before, the currently from our Crowdin-community approved translation, has more upvotes. You can up-/down vote on existing translations and if the community agrees on a "better" translation then that is the one which will be used.

> App name. Shouldn't ever change.
is a description for the translation  so translators have more context in which situations this is used.

I'll take your feedback back to the team, to possibly remove the `Shouldn't ever change.` from the description.

Kind regards,
Daniel
