### ISSUE TITLE
Android App not display TOTP codes on home screen

### ISSUE THREAD

**Issue by marcqw** [bitwarden/mobile#2070]
### Steps To Reproduce

1. Go to Home screen "my vault"

I don't have that (from bitwarden doc)

![image](https://user-images.githubusercontent.com/19610243/190130146-242cae6e-ef81-484e-84b0-ee5ddb1a7a23.png)

### Expected Result

I want to show a quick access totp codes.

### Actual Result

My screen start with Types menu

### Operating System

Android

### Build Version

2022.8.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by dwbit** [comment]
Hey @marcqw, this functionality will be available once the upgrade to 2022.9.0 is available on your device (currently in the process of rolling out to the Google Play store).

**Comment by marcqw** [comment]
thank for you're help :)
