### ISSUE TITLE
[French Translation] Missing + Wrongly translated

### ISSUE THREAD

**Issue by LapinFou** [bitwarden/mobile#2072]
### Steps To Reproduce

Hi folks,

Just some easy fixes. Some French translations are either missing or wrong.

### Expected Result

In the parameters tab:

- **Autoriser la capture d'écran**
- **Soumettre le journal de crash**

When using the auto-filling from any apps or websites

- **Élément correspondant** (in English → "Matching item")

By the way, "**vault** & **vaults**" could be translated as "**coffre** & **coffres**" and "**Send**" could be translated as "**Partage**".

### Actual Result

In the parameters tab:

- **Allow screen capture**
- **Submit crash logs**

When using the auto-filling from any apps or websites

- **Aucun élément correspondant** (in English → "No matching item") The translation is the exact opposite of the real meaning. 😅

### Operating System

Android

### Operating System Version

Adnroid 13

### Device

Pixel 6

### Build Version

TP1A.220905.004

**Comment by djsmith85** [comment]
Hi @LapinFou,

We use a translation tool called Crowdin to help manage our localization efforts across many different languages. Our translations can only be updated using Crowdin, so this issue will be closed.

If you are interested in helping translate a Bitwarden client into another language (or make a translation correction), please register an account at Crowdin and join our project here: https://crowdin.com/project/bitwarden-mobile

If the language that you are interested in translating is not already listed, create a new account on Crowdin, join the project, and contact the project managers.

You can read Crowdin's getting started guide for translators here: https://support.crowdin.com/crowdin-intro/

If the translations on Crowdin do not match the translations on Github, please let us know and we will investigate.

For any further questions about contributing, please check out our [Contributing Guidelines]https://contributing.bitwarden.com/contributing/

**Comment by LapinFou** [comment]
@djsmith85 
OK. Thanks for the reply, I will check Crowdin .
Is it safe to link my Github account with Crowdin?
