### ISSUE TITLE
Font size seems to vary when changing resolution from WQHD+ down to HD+ or vice-versa

### ISSUE THREAD

**Issue by jhankins2** [bitwarden/mobile#2083]
### Steps To Reproduce

Problem on Android. May be related to "[PS-191] Improve support for larger fonts Android #2053" but is still present in 2022.8.0(4911).

I changed my resolution in my phone (Samsung Galaxy S22 Ultra) settings from WQHD+ down to HD+, and the font in the Bitwarden is tiny. If I change the resolution back, it goes back to normal. If I scale the font in system settings, it doesn't seem to be scaling the same way as it does for other apps.

Deleting bitwarden data and signing my account back in seems to correct it. If, at this point, I change the display resolution back up to WQHD+, the bitwarden font is huge, and the same scaling issue exists.

### Expected Result

Bitwarden app font should scale with resolution and/or font change in the same way other apps do.

### Actual Result

Font scaling in bitwarden app seems to be affected by changing the display resoltion from whatever it was when the app was first installed/signed in in a way that causes font size to be much larger or smaller than expected, after the resolution has been changed.

### Operating System

Android

### Operating System Version

Android 12

### Device

Samsung Galaxy S22 Ultra

### Build Version

2022.8.0(4911)

### Beta

- [ ] Using a pre-release version of the application.

[PS-191]: https://bitwarden.atlassian.net/browse/PS-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by super-sonicX** [comment]
Having this same issue, Samsung galaxy S22 Ultra

**Comment by djsmith85** [comment]
Hi @jhankins2 and @super-sonicX the changes made with https://github.com/bitwarden/mobile/pull/2053 have not been released yet. These are planned for the 2022.10 release. 

You could also signup/try out beta release for our mobile clients. Instructions can be found [here](https://community.bitwarden.com/t/join-the-beta-program/39185)

I'm going to close this now, but feel free to comment/re-open if this continues to be an issue using the 2022.10 release.

**Comment by GiorgioMendieta** [comment]
I'm having a similar bug on a Galaxy Note 20 Ultra. Bitwarden changes the dpi randomly, sometimes the font is really tiny, other times it's really big.

I'm currently investigating the steps to reproduce the bug.

**Comment by Raphisu** [comment]
Hi! This is still happenning to me on a S23 ultra and bitwarden 2023.10.0 (8257) when changing to WQHD+. Large font and tiny icons.
Any info details needed?

**Comment by douglasparker** [comment]
This is still an issue on Samsung and Pixel devices.

**Comment by bkmeneguello** [comment]
@djsmith85 this issue is still happening S23 Ultra with the same issue, app version: 2024.2.0 (9000)
![Screenshot_20240223_223345.jpg](https://github.com/bitwarden/mobile/assets/1322552/e2e202d5-88ab-4245-859d-7ce0183989a7)
