### ISSUE TITLE
One-time key from YubiKey NFC not written to input during 2FA from iPhone AutoFill Passwords

### ISSUE THREAD

**Issue by YBRCPtSXmwloooFv9E1239PpOLeSh1Wp1LnJ36T** [bitwarden/mobile#2085]
### Steps To Reproduce

1. Go to a mobile app with 2FA 
2. Tap on Password field
3. Tap on Password button 
4. Log in to Bitwarden after redirect
5. Scan YubiKey

### Expected Result

Generate one-time key, and Continue option to turn opaque.

### Actual Result

iPhone notification "Firefox NFC Tag: Open in Firefox" appears.

### Screenshots or Videos

The keyboard and Passwords button are not captured by the screenshot tool. 
![97FDFB01-444F-4732-8659-1050E0DE34E1_1_201_a](https://user-images.githubusercontent.com/58127651/191149654-01df626f-8a68-4bd2-9d37-775904afa2b8.jpeg)
![18960183-FD66-4386-948D-CF1CAA487361_1_201_a](https://user-images.githubusercontent.com/58127651/191149676-a102581d-e01a-4c68-8c58-594427817e7e.jpeg)
![4D7DED4E-1EDE-4E12-AFB4-7967800BE8EC_1_102_o](https://user-images.githubusercontent.com/58127651/191149699-9fbfbeb7-c8f3-41b1-9d4b-3cf9b54b796a.jpeg)
![20615408-88F4-4F20-9AB6-352A71FD0A70_1_102_o](https://user-images.githubusercontent.com/58127651/191149713-86f78832-2aa0-49c2-bdb0-efe24d2760de.jpeg)

### Operating System

iOS

### Operating System Version

15.6.1

### Device

iPhone SE

### Build Version

19G82

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hello,

Please try reproducing the issue with the beta version of the native app. The beta program can be joined, and the app downloaded from here: https://community.bitwarden.com/t/about-the-beta-program/39185

Recent updates have been made in the beta builds, so it would be helpful to check if the issue still occurs with the latest version.

Thank you for your cooperation, and looking forward to the feedback!
