### ISSUE TITLE
Icon requests are made even when `Show website icons` is disabled

### ISSUE THREAD

**Issue by yfBmF4ZEPulAk8wtMa3x7SGlXJrONqcmflcwQXS** [bitwarden/mobile#2087]
### Steps To Reproduce

1. Disable the `Show website icons` option in the mobile app
2. Tail your reverse proxy logs
3. Scroll through login entries that would have shown icons if the `Show website icons` option were enabled
4. Observe that the reverse proxy logs show that icon requests are being made, even though no icons are actually displayed in the app

### Expected Result

No icon requests are observed

### Actual Result

Icon requests are observed despite no icons actually being displayed in the app

### Additional Context

This issue seems to be specific to the mobile client. It's most easily observed with a self-hosted server, though I expect the same issue is present when using Bitwarden-hosted servers.

### Operating System

Android

### Build Version

2022.9.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hello,

Please try reproducing the issue with the beta version of the native app. The beta program can be joined, and the app downloaded from here: https://community.bitwarden.com/t/about-the-beta-program/39185

Recent updates have been made in the beta builds, so it would be helpful to check if the issue still occurs with the latest version.

Thank you for your cooperation, and looking forward to the feedback!
