### ISSUE TITLE
Bug log in

### ISSUE THREAD

**Issue by G4M37R0N** [bitwarden/mobile#2091]
### Steps To Reproduce

1. Go to 'Bitwarden App'
2. Click on 'Authenticate'
3. Wait until 'kicks you out'

### Expected Result

To open password vault and password generato

### Actual Result

Kick out of the app

### Operating System

Android

### Operating System Version

Android 10

### Device

Xiaomi Redmi 9C NFC

### Build Version

2022.09.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by cslucian** [comment]
Hello,

What is you device set language? it seems to be a bug with other languages except English.

**Comment by G4M37R0N** [comment]
Romanian

**Comment by cslucian** [comment]
See #2086 it reports the same issue.

**Comment by djsmith85** [comment]
Hi @G4M37R0N thank you for your report.

As @cslucian already mentioned, this is being tracked with #2086.

Please add your information there as the other issue currently only mentions issues on IOS. 

Closing this now as duplicate

**Comment by G4M37R0N** [comment]
My language is Romanian

joi, 22 sept. 2022, 10:34 Sorin Cristil ***@***.***> a scris:
