### ISSUE TITLE
Verification Codes doesn't respect the `Show website icons` setting

### ISSUE THREAD

**Issue by jjlin** [bitwarden/mobile#2094]
### Steps To Reproduce

1. Disable the `Show website icons` option in the mobile app
2. Go to the `Verification Codes` section
3. Observe that website icons are shown despite the option being disabled

### Expected Result

No website icons are shown in the `Verification Codes` section when the `Show website icons` option is disabled

### Actual Result

Website icons are shown regardless of how the option is set

### Operating System

Android

### Build Version

2022.9.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Hi @jjlin I assume this is likely going to be the same cause as https://github.com/bitwarden/mobile/issues/2087.

I'll close this but will add the information for QA to verify that the icons are also not shown on the verification codes page, when `Show website icons` is disabled.
