### ISSUE TITLE
Accessability Auto fill not always showing

### ISSUE THREAD

**Issue by BigNickBurgess** [bitwarden/mobile#211]
I have been trialling running the Autofill API and Autofill Accessibility services alongside each other to cover all bases (until google/firefox sort browser support out) but have noticed that the Accessibility service set to persist notification keeps disappearing.  It does occasionally re-appear by itself but other times I have to go into the app before it shows up again.

Not a deal breaker as I have the FF extension installed anyway to cover browser but an annoyance when I was tryign to run both.  Didn't try it on its own but I cant see that it was affected by the Oreo autofill API.

Galaxy S8 Oreo beta 4.

**Comment by kspearrin** [comment]
Can you re-create a way to reliably reproduce it?

**Comment by BigNickBurgess** [comment]
Ok just had another play.

Seems to be when you go back into the bitwarden app it clears the notification (I'm sure i never used to?).  If you then do anything else (open an app/settings) the notification then shows again but if you don't go into another app the notification never shows so it looks like its stopped running.  Even locking/unlocking my phone didnt re-trigger it.

So it will work fine if you need the autofill but this behaviour does make it look like bitwarden has stopped running if the last thing you've done is use the App.

**Comment by kspearrin** [comment]
I believe this is how it has always worked.

**Comment by BigNickBurgess** [comment]
If that's the case then ignore this.  I just don't remember it disappearing like that.
