### ISSUE TITLE
Auto-fill via accessibility cannot be activated on android 13 when bitwarden is sideloaded

### ISSUE THREAD

**Issue by septem9er** [bitwarden/mobile#2128]
### Steps To Reproduce

1. Go to android settings -> accessibility
2. Click on Bitwarden to enable it

### Expected Result

The accessibility service is activated.

### Actual Result

Bitwarden accessibility service cannot be activated. It is grayed out and when tapping on it an error message appears. (See screenshots)

### Screenshots or Videos

![1](https://user-images.githubusercontent.com/33379902/195343824-ea25c18b-9d9f-42d8-9a98-6e6476417a1c.png)
![2](https://user-images.githubusercontent.com/33379902/195343831-d752452d-73e7-491d-9e09-812f07a10564.png)

### Additional Context

I think this behavior started with the upgrade to Android 13, but I am not sure.
I do have a work profile via the app shelter. Bitwarden is not in the work profile, but maybe it somehow a security thing for the work profile.

### Operating System

Android

### Operating System Version

Android 13, Costume ROM: Graphenos, Buildnumber: TP1A.221005.002.2022100300

### Device

Google Pixel 6

### Build Version

Version: 2022.9.1 (5047) (via your F-Droid Repository)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by lusanagi** [comment]
I can also confirm it's an android 13-14 thing:
I have a lenovo tablet with zui (android 14) as well with a Poco F5 on miui (android 13), both official, and on both the accessibily option was greyed out until I followed the instructions given here.

This issue should not be closed as it is android wide "feature" (andno other app I've installed has had this issue)
