### ISSUE TITLE
Auto-fill via accessibility cannot be activated on android 13 when bitwarden is sideloaded

### ISSUE THREAD

**Issue by septem9er** [bitwarden/mobile#2128]
### Steps To Reproduce

1. Go to android settings -> accessibility
2. Click on Bitwarden to enable it

### Expected Result

The accessibility service is activated.

### Actual Result

Bitwarden accessibility service cannot be activated. It is grayed out and when tapping on it an error message appears. (See screenshots)

### Screenshots or Videos

![1](https://user-images.githubusercontent.com/33379902/195343824-ea25c18b-9d9f-42d8-9a98-6e6476417a1c.png)
![2](https://user-images.githubusercontent.com/33379902/195343831-d752452d-73e7-491d-9e09-812f07a10564.png)

### Additional Context

I think this behavior started with the upgrade to Android 13, but I am not sure.
I do have a work profile via the app shelter. Bitwarden is not in the work profile, but maybe it somehow a security thing for the work profile.

### Operating System

Android

### Operating System Version

Android 13, Costume ROM: Graphenos, Buildnumber: TP1A.221005.002.2022100300

### Device

Google Pixel 6

### Build Version

Version: 2022.9.1 (5047) (via your F-Droid Repository)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by septem9er** [comment]
Hey,
the graphenos community guided me to the solution:
[Android 13 put in new restrictions for accessibility service (for sideloaded apps)](https://www.androidpolice.com/android-13-blocks-accessibility-services-sideloaded-apps/) 

I leave this open as an issue for the docs:
The app and/or the website should explain this.

You first have to enable this in Settings --> Apps --> Bitwarden --> Vertical dots --> allow restricted settings.

**Comment by THEOCKID** [comment]
Just wondering... why sideload BW?  Why not just install from Play store?

**Comment by tangowithfoxtrot** [comment]
Hey, @septem9er.

Thanks for reporting and providing [a workaround](https://github.com/bitwarden/mobile/issues/2128#issuecomment-1276184230) for this on your ROM! We'll close this, since it seems to be a security-hardening measure specific to GrapheneOS, but this issue will remain viewable for anyone else's reference.

Thanks again!

**Comment by TheEccentricConnisure** [comment]
I have also faced the same issue on my oppo Reno 6. And I was able to use the same workaround as mentioned [here](https://github.com/bitwarden/mobile/issues/2128#issuecomment-1276184230) to fix the issue

**Comment by septem9er** [comment]
> We'll close this, since it seems to be a security-hardening measure specific to GrapheneOS, but this issue will remain viewable for anyone else's reference.

Hey,
as mentioned in the link in my last post, this actually is a feature of Android > 13. It is not grapheneOS specific.

So if that's why you closed the issue, I'd ask you to reconsider this decision.

It does only affect people that don't install the app via the play store, but I think that's still a significant user group for your app. After all you even have your own f-droid repo to distribute your app outside of the google play store.

It seems like some other users who stumbled upon that problem found this issue. However, I think it isn't very user friendly to expect the users to find the solution themselves in a closed github issue.

My best idea for a solution would be the following:
Check if the app was not installed via the google play store and if the android version is > 13. If so, when trying to enable the auto-fill in via accessibility service from your app, display an info somewhere either explaining directly what to do to enable it or link to your auto-fill in FAQs and explain it there.

For reference, the full steps to enable auto-fill in for bitwarden when the app wasn't installed via the google play store are actually as follows:
1. Open the android accessibility settings
2. Click an bitwarden (this is necessary!), the pop-up appears
3. Open the android app settings of bitwarden (settings -> apps -> bitwarden)
4. Press on the vertical dot's (not there if you haven't done 2. step)
5. Allow restricted settings
6. Go back to the android accessibility settings. Now you can enable bitwarden.

**This has to be done after every update**. This does include step too, you have to see the pop-up first.
