### ISSUE TITLE
Crash on click generate a password

### ISSUE THREAD

**Issue by abda11ah** [bitwarden/mobile#2149]
### Steps To Reproduce

1. Go to pcloud app and click on create an account
2. Fill an email adress and try to create a new entry on bitwarden
3. Click on the circle arrow to generate a new password
4. Crash

### Expected Result

Generator opens and asks for password length, type, characters etc.

### Actual Result

Crash

Crash URL
https://bin.kv2.dev/~63557f09e599576ea02af9d7

### Operating System

Android

### Operating System Version

Android 13 (ricedroid)

### Device

Redmi 8 4GB/64GB

### Build Version

2022.10 (5247)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by THEOCKID** [comment]
was happening to me today too, same situation as above but on Android 12 (samsung S22 ultra).  Create new login entry, generate pw and pow, crash.

**Comment by patrickHD** [comment]
Also having this issue. Galaxy S21 Ultra, Android 12, app version: 2022.10.0 (5247).

Create entry -> tap generate button -> crash. Happens on any site, but not when opening the app, a
