### ISSUE TITLE
Oreo Autofill and Firefox Focus browser

### ISSUE THREAD

**Issue by BigNickBurgess** [bitwarden/mobile#216]
I saw on the LastPass beta G+ that they are saying Firefox focus works with autofill.  Tried it on bitwarden both clicking in the field and pressing and holding and selecting the 'auto-fill' option and never received a bitwarden suggestion or login prompt.

LastPass Beta does work here however (when presseing and holding and selecting auto-fill) so not sure if its something that could be implemented with Bitwarden?

**Comment by kspearrin** [comment]
Though it does looks like Focus is sending autofill events now, I do not see it sending enough information about a webpage to determine what fields to autofill or the URL of the current website.

Is it working in LastPass? Can you actually autofill a website?

**Comment by BigNickBurgess** [comment]
Yes you can autofill as normal in focus in LastPass beta.

**Comment by kspearrin** [comment]
I am testing LastPass beta in Firefox Focus for github.com and it just tells me "LastPass is not able to autofill for this app"... ?

**Comment by BigNickBurgess** [comment]
![screenshot_firefox focus_20171220-154434](https://user-images.githubusercontent.com/31211392/34215355-ff3fcc9c-e59c-11e7-8a9c-eaf5f14eb1a2.jpg)

Im using:
LastPass Password Manager Beta (unreleased) 4.3.1401
Firefox Focus 4.0.1

Definitely autofills for me using Oreo API

**Comment by BigNickBurgess** [comment]
Just tried github and no that doesn't work.  Same message for me.

**Comment by kspearrin** [comment]
Ok great. That helps.

The latest bitwarden beta on Android (build 1193) now supports web browser autofill (where the browser also supports it). Give it a try and let me know how it works. I have only seen this working in Firefox focus, however, and it only will work on websites that send proper password hints for input fields (i.e. not GitHub).

**Comment by BigNickBurgess** [comment]
Ok will try it out now.  As an adendum, a very useful feature to add on the auto fill screen in bitwarden would be a permanant link to the Autofill API settings page regardless of enabled/disabled.  Makes switching between LastPass and Bitwarden much easier or if you want to turn it off quickly.

**Comment by kspearrin** [comment]
Yes, I noticed that as well. I'll look into it.

**Comment by BigNickBurgess** [comment]
Yep works great now thanks.

**Comment by quthla** [comment]
Dropdown is not showing for me. In Facebook App it is but not in Firefox Klar 4.0.1 using latest Bitwarden from Play Store.

**Comment by BigNickBurgess** [comment]
This will only work in Firefox focus if the site is built to send proper password hints as stated above.  Try it on Amazon and numerous other sites and it works fine.

**Comment by quthla** [comment]
https://play.google.com/store/apps/details?id=org.mozilla.klar
https://play.google.com/store/apps/details?id=org.mozi go Mozilla

Firefox Klar is the local version of Firefox Focus in my country but for some reason it's only working with Focus. 

How is this possible? They seem identical.

**Comment by kspearrin** [comment]
@quthla I have to add each supported browser to a whitelist. org.mozilla.klar was not on that list. I will add it for next version.

**Comment by quthla** [comment]
Ok it needs to be added to Bitwarden code. 

@kspearrin can you do that?
