### ISSUE TITLE
Bitwarden doesn't support iOS Firefox 10.4 (8288)

### ISSUE THREAD

**Issue by PolywickStudio** [bitwarden/mobile#218]
Bitwarden does not integrate with iOS FireFox 10.4 (8288)

Is there a way for FireFox iOS to add Bitwarden as a plugin?

**Comment by kspearrin** [comment]
Bitwarden is already supported in Firefox iOS. Just open the share menu to autofill with the bitwarden app extension the same way you do in Safari and Chrome on iOS.

**Comment by PolywickStudio** [comment]
Ok got it. Ticket closed.
