### ISSUE TITLE
Android app ignores locking timeout instuctions

### ISSUE THREAD

**Issue by VakHub** [bitwarden/mobile#2182]
### Steps To Reproduce

Settings > Security > Vault timeout. Choose time to lock the app (for example 4 hours). 
Close the app, lock/unlock the device and try logging in on random website, bitwarden will be locked and will be needed to unlock again.

### Expected Result

When I set the timeout on 4 hours, I want it to be unlocked the entire time instead of being locked after my phone gets locked/unlocked.

### Actual Result

Bitwarden gets locked in a few minutes whenever I lock my device instead of my timeout instruction of 4 hours 

### Operating System

Android

### Operating System Version

One UI 4.1 October Security Patch 

### Device

Samsung Galaxy A52s

### Build Version

Version: 2022.10.0 (5247)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by RuthlessRuler** [comment]
Can reproduce the same.

**Comment by vinnyperella** [comment]
Same issue here it prompts for my PIN every time I close and reopen the app. Version 2022.11.0 on Android.

**Comment by vinnyperella** [comment]
I just updated to the latest version 2023.01.0 and this is still an issue it asks for my master password anytime I close the app regardless of lock settings. Thus is very very annoying.

**Comment by shrimprugbysnowowl** [comment]
> 

I'm running v2023.1.0 and have it set to unlock with a PIN, but it still asks for my Master Password each time.

**Comment by nkm8** [comment]
Issue still persists in v2023.2.0 - and I have tried all of the available vault timeout options. Even custom with a really long duration results in the vault locking very quickly. 

This is frustrating because autofill on Android works poorly for me when Bitwarden is locked.

**Comment by 2fst4u** [comment]
Enabling accessibility for bitwarden did not resolve the issue for me.

**Comment by shrimprugbysnowowl** [comment]
> I played around with this issue a bit more. I was really perplexed because the timeout options recently worked fine for me.
> 
> I found that the vault timeout setting only works when the Bitwarden accessibility service is enabled. You can test this behavior:
> 
> 1. Disable accessibility service
> 2. Set vault timeout to never
> 3. Force close Bitwarden
> 4. Reopen Bitwarden
> 5. See prompt to unlock vault
> 
> If you repeat these steps with the accessibility service enabled, you will no longer be promoted to unlock the vault (correct behavior).
> 
> I need the accessibility service to be disabled due to a bug in Gmail where the toast prompts never disappear while any accessibility service is enabled.

By George, I think you've done it!  This resolves my issue, but it appears that others experiencing the same or a similar issue are still having the problem, so I can leave this open.

**Comment by shrimprugbysnowowl** [comment]
> Enabling accessibility for bitwarden did not resolve the issue for me.

Enable accessibility then disable and reenable your PIN. Accepting the prompt that is titled "Unlock with PIN code" worked for me.

**Comment by 2fst4u** [comment]
> > Enabling accessibility for bitwarden did not resolve the issue for me.
> 
> Enable accessibility then disable and reenable your PIN. Accepting the prompt that is titled "Unlock with PIN code" worked for me.

Still no change for me.

**Comment by divya-pai** [comment]
I can reproduce this bug if app is removed from recents or force closed. Not sure if that is expected?

**Comment by colleenmason** [comment]
Also having this issue in ios. specifically if I set vault timeout to "never", leave settings and return (not even leaving the app just go to main screen and back into settings) the timeout has reverted to "15 minutes"

**Comment by rogerfar** [comment]
Tried it in android again and the setting is just ignored.

**Comment by colleenmason** [comment]
I cried to the bitwarden twitter and they suggested uninstall/reinstall the app. That actually worked for me! Again I'm on ios so I don't know if it'll help on Android but I figured I'd report my success fingers crossed for y'all

**Comment by vinnyperella** [comment]
This is still an issue for me as well has not been fixed in all of the releases since the issue was reported.

**Comment by RuthlessRuler** [comment]
Same. It hasn't been resolved for me too. Either we need to create a new issue or @VakHub pleaee re-open this issue

**Comment by dany2007** [comment]
The issue is also present on my phone (Poco F4) with all the battery saving options disabled. This has been a problem since i started using bitwarden a few months ago.

**Comment by SlimGary** [comment]
Same here, Xiaomi 13 and pixel 7, all battery saving options disabled
