### ISSUE TITLE
Simplify Auto Fill menu

### ISSUE THREAD

**Issue by Noah-Huppert** [bitwarden/mobile#221]
In the browser you can auto fill inputs by right clicking and selecting bitwarden > auto fill > and then clicking on the site you want.  

It would be nice if the "auto fill" menu option did not exist. And instead the sites you could auto fill with were just 1 menu deep, in the bitwarden menu. And not behind the "auto fill" menu.  

This would simplify the auto fill process, because you wouldn't have to go so deep in the menus.  

The reason I suggest this change is because the bitwarden menu never contains any other sub menus other than the "auto fill" item. And it seems a bit redundant. Compared to just showing all the sites it could auto fill.

**Comment by kspearrin** [comment]
This is the mobile app's repo, not the browser extension. I also think we are already tracking this in the browser repo as well.

**Comment by Noah-Huppert** [comment]
You are indeed correct on both accounts. Sorry for not realizing I was in the mobile repo. 

Tracking in [browser #137](https://github.com/bitwarden/browser/issues/137).
