### ISSUE TITLE
iPhone App offline usage not possible - Can't open vault

### ISSUE THREAD

**Issue by netcrystals** [bitwarden/mobile#2210]
### Steps To Reproduce

Bitwarden iPhone App Version 2022.10.0 (2347)
Disable connection to Bitwarden server (disconnect mobile connection and/or wlan)
Open iPhone App
Enter Master key
No connection possible 

### Expected Result

I expected that if the iPhone app can not connect to the Bitwarden server, the local vault can still be opened.

### Actual Result

I entered the master key but there was no data available. No vault, no passwords, nothing.

### Additional Context

In german version I entered
Einstellungen (Settings)
-Tresor-timeout (vault timeout) --> Niemals (never)
-Aktion bei Tresor-timrout (action if vault-timeout) --> Sperren (Lock)
-Mit Touch ID entsperren (unlock with touch ID) --> Ein (On)

When the iPhone app can not connect with the Bitwarden server, I have to enter master password but can not even unlock with fingerprint. If I enter master password, I see nothing.

### Operating System

iOS

### Operating System Version

15.7.1

### Device

iPhone 7

### Build Version

15.7.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by RezzZ** [comment]
I have exactly the same issue. I use vaultwarden on my unraid machine, I use swag as a proxy but online LAN access is allowed so when I'm away there is no access to my vaultwarden. I would have expected that I could still access my stored passwords in the app but the login cannot connect so I cannot access any passwords. Is this a setting we are missing?

**Comment by netcrystals** [comment]
You have to update to newest bitwarden version. Now everything works.

**Comment by RezzZ** [comment]
> You have to update to newest bitwarden version. Now everything works.

i installed it a few days ago so that shouldn't be the issue... perhaps I need to look into my settings again when I have a connection with the server. Perhaps autologoff is enabled or something. Both ios and chrome app ask to login while i should have an offline copy for access available...

**Comment by djsmith85** [comment]
@netcrystals: Thank you for reporting back.
@RezzZ: Please seek support on the [Vaultwarden community](https://github.com/dani-garcia/vaultwarden), as this is related to your setup.

Closing this now, as the issue seems to be resolved.
