### ISSUE TITLE
Why bitwarden have app installation permission on Oreo?

### ISSUE THREAD

**Issue by vinaooo** [bitwarden/mobile#222]
If you go to settings, apps, special access, install unknown apps, bitwarden are listed here, but why?

**Comment by kspearrin** [comment]
Not sure. Maybe it has something to do with the autofill framework?

**Comment by vinaooo** [comment]
I think not, other apps with this permission are Chrome, Files go, Gmail and Drive

**Comment by vinaooo** [comment]
This is a new option instead the old 'Unknown sources'

**Comment by kspearrin** [comment]
I don't know why it is listed there, but from what I see it is not enabled and set to "Not allowed", so this permission is not granted.

**Comment by vinaooo** [comment]
Yep, maybe something related to attachment feature
