### ISSUE TITLE
Support offline mode

### ISSUE THREAD

**Issue by xmha97** [bitwarden/mobile#2229]
### Steps To Reproduce

1. Try to add a new login
2. Get an error

### Expected Result

Add my login and sync later

### Actual Result

I can't add login/password on offline mode.

### Screenshots or Videos

![Screenshot_2022-12-08-19-59-18-496_com x8bit bitwarden](https://user-images.githubusercontent.com/23485114/206510822-9037a459-b214-43fb-afdf-332850540fcb.jpg)

### Additional Context

If this app does not work offline, I will uninstall it. Excuse me for this

### Operating System

Android

### Operating System Version

12

### Build Version

2022.10.1

### Beta

- [X] Using a pre-release version of the application.

**Comment by edwardgalligan** [comment]
@dwbit is this feature still on the roadmap? Is there a publicly published roadmap for users requesting this to find?
