### ISSUE TITLE
Add option to send bitwarden 2fa code by mail

### ISSUE THREAD

**Issue by vinaooo** [bitwarden/mobile#224]
Add an option to send bitwarden 2fa codes by mail on bitwarden login.
Without this users need to use a computer or another way to store this codes like other apps or a backup code

Or maybe allow a 'secure device's on web site to not ask for 2fa codes

**Comment by kspearrin** [comment]
https://help.bitwarden.com/article/setup-two-step-login-email/

**Comment by vinaooo** [comment]
Sorry, my mistake

Thank you
