### ISSUE TITLE
Autofill doesn't work in Vanadium (Chrome)

### ISSUE THREAD

**Issue by Morpheus0x** [bitwarden/mobile#2240]
### Steps To Reproduce

1. Open Vanadium Browser (GrapheneOS Chrome fork)
2. Go to any login page, e.g. github
3. Clicking on either username or password field doesn't show the Autofill
4. Clicking on the Auto-fill tile from quick settings (notifications drop-down) produces toast message "No password fields detected" and switches to bitwarden app

### Expected Result

The bitwarden autofill option should pop up, allowing the user to choose what saved username and password should be filled in

### Actual Result

Nothing shows up

### Additional Context

Vanadium 108.0
Bitwarden 2022.11.0 (was working in 2022.10.0)

### Operating System

Android

### Operating System Version

Android 13 (latest GrapheneOS)

### Device

Pixel 6 & Pixel 5

### Build Version

2022.11.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Hi @Morpheus0x, thank you for your report. 

This has been fixed by a community contribution via https://github.com/bitwarden/mobile/pull/2199.

The changes will be included in an upcoming release.

**Comment by Enlinks** [comment]
I wanted to report that this still is not work after Bitwardens https://github.com/bitwarden/mobile/pull/2199.

I've tested this on my normal phone running Vanadium in compatibility mode [commit](https://github.com/GrapheneOS/Vanadium/commit/fd37911a5e927298cefbb77e7460ef76219e7280) and also my test phone that I formatted to get the non--compatibility mode Vanadium.

```
version 109.0.5414.86

app.vanadium.browser
versionCode 541408633

targetSdk 33
minSdk 29

Installed: Jan 1, 2009; 12:00 AM
```
```
version 2023.1.0

com.x8bit.bitwarden
versionCode 5786

targetSdk 33
minSdk 21

Installed: Jan 22, 2023; 8:53 PM

**Comment by thestinger** [comment]
Bitwarden needs to ship a release with the change if they haven't done that yet.

**Comment by Enlinks** [comment]
@thestinger I have the release they added it, its in my above output.

```
version 2023.1.0

com.x8bit.bitwarden
versionCode 5786

targetSdk 33
minSdk 21

Installed: Jan 22, 2023; 8:53 PM
