### ISSUE TITLE
Crash on splash screen, crash dump file can't be created

### ISSUE THREAD

**Issue by sandrc** [bitwarden/mobile#225]
The app (v1.13) is crashing while on the splash screen. The logcat shows that it was unable to create a dump file. I already gave it storage permission. Attached is the relevant section.
Xperia XZ, Stock Nougat 7.1.2 with MicroG
![screenshot_20171226-165048](https://user-images.githubusercontent.com/16916521/34358044-3c404346-ea5d-11e7-993f-5eb950a2c64c.png)
![screenshot_20171226-165114](https://user-images.githubusercontent.com/16916521/34358049-3f5de614-ea5d-11e7-8a92-34f9bae453ef.png)

**Comment by kspearrin** [comment]
I have no idea. Is there more to the log you can send to me at support@bitwarden.com ?

**Comment by kspearrin** [comment]
Closing since no reply.
