### ISSUE TITLE
Notion icon is broken in vault 

### ISSUE THREAD

**Issue by polygonica** [bitwarden/mobile#2251]
### Steps To Reproduce

1. Add a vault entry
2. Add URL notion.so

### Expected Result

1. Notion icon loads

### Actual Result

2. No icon loads -- only placeholder globe

### Additional Context

This is likely due to the Notion website naming their favicon something else. Bitwarden should load it if browsers can.

### Operating System

Android

### Operating System Version

13

### Device

Pixel 7 Pro

### Build Version

Version: 2022.11.0 (5580)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by HEJOK254** [comment]
Changing the URL from "notion.so" to "http://notion.so" or "https://notion.so" so that it includes the HTTP/HTTPS protocol seems to fix the issue for me.

Could you confirm if this fixes the issue?

**Comment by djsmith85** [comment]
@polygonica 

> Changing the URL from "notion.so" to "http://notion.so" or "https://notion.so" so that it includes the HTTP/HTTPS protocol seems to fix the issue for me.
> 
> Could you confirm if this fixes the issue?
