### ISSUE TITLE
Add Lemur Browser

### ISSUE THREAD

**Issue by Kevinlinpr** [bitwarden/mobile#2260]
### Steps To Reproduce

Hello👋, I am the developer of Lemur Browser.
Lemur Browser is the mobile browser support Chrome and Edge extensions, build from chromium.
You can find the latest version on [lemurbrowser.com](lemurbrowser.com) or the [Google play](https://play.google.com/store/apps/details?id=com.lemurbrowser.exts)

### Expected Result

Add the Lemur Browser into Bitwarden whitelist 

### Actual Result

Lemur browser cannot use bitwarden normally

### Operating System

Android

### Build Version

latest version

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Kevinlinpr** [comment]
I wrote this issue to obtain the consent of the original author of bitwarden. If the author agrees, I will submit a corresponding pull request

**Comment by qiaoyun680** [comment]
应该直接提pr等合并就可以了 参考下面这个https://github.com/bitwarden/mobile/pull/2142

**Comment by Kevinlinpr** [comment]
[PR](https://github.com/bitwarden/mobile/pull/2262)
