### ISSUE TITLE
Link in README is broken

### ISSUE THREAD

**Issue by maxwowo** [bitwarden/mobile#2263]
### Steps To Reproduce

1. Go to README.md
2. Click on the [Mobile section](https://contributing.bitwarden.com/mobile/) link under the `Build/Run` section
3. Navigate to the newly-opened tab

### Expected Result

Page should load with relevant information

### Actual Result

Page not found

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/40416283/209500059-c810f2ac-ee20-4b14-8155-b4cd5920eb2d.png)

### Operating System

iOS

### Build Version

N/A

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
@maxwowo Thank you for your report. The linked PR fixes the broken link to point to https://contributing.bitwarden.com/getting-started/clients/mobile/
