### ISSUE TITLE
Bitwarden FDroid repository does not support index-v2

### ISSUE THREAD

**Issue by Valeryan24** [bitwarden/mobile#2268]
### Steps To Reproduce

Hi, I added the Bitwarden repo on FDroid (Samsung Galaxy S22+ and Android 13) :
https://mobileapp.bitwarden.com/fdroid/repo

It worked well since a few days and the new alpha version 1.16 of FDroid.

### Expected Result

Present and download updated versions of Bitwarden mobile app on FDroid.

### Actual Result

Now, when updating applications, an error during update occurs, with message :
"No file found for https://mobileapp.bitwarden.com/fdroid"
The "/repo" at the end of the address has been removed.

It seems that Bitwarden repo does not support index-v2: https://mobileapp.bitwarden.com/fdroid/repo/entry.jar is 404.

https://gitlab.com/fdroid/fdroidclient/-/issues/2502

### Operating System

Android

### Operating System Version

13

### Device

Samsung Galaxy S22+

### Build Version

2022.11.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by mp-bw** [comment]
@Valeryan24 Thanks for the heads up.  I've commented on the issue at gitlab but I'll ask here as well: Do you know if there a timeline on continued index-v1 support?

**Comment by mp-bw** [comment]
@Valeryan24 While we didn't implement index-v2 (at least not yet) the url has been updated and appears to be working on both 1.15 and 1.16-alpha F-Droid clients (I had to remove and re-add the Bitwarden repo to get the updated url). Can you confirm things are working on your end as well?

**Comment by Valeryan24** [comment]
Hi, yes I confirm it works well now with FDroid 1.16-alpha2 :

I added the repo again, no more error message on updating, and I could well upgrade to Bitwarden mobile app version 2023.1.0

Thanks for your quick solving !
