### ISSUE TITLE
Self-hosted Bitwarden, error with custom server URL

### ISSUE THREAD

**Issue by DimitriDR** [bitwarden/mobile#2273]
### Steps To Reproduce

0. **Use a self hosted instance**
1. Go to the gear icon
2. Enter a custom server URL (only): I wrote "https://vault.mydomainname.tld"
3. Save
4. Profit of the error

### Expected Result

No error.

### Actual Result

A first popup appears (see screenshot) and when I entered my e-mail address, I got a second popup (same error).

### Screenshots or Videos

![IMG_0236](https://user-images.githubusercontent.com/56969769/210178027-fa027de5-ee6f-4809-9f9c-8a750ad1461b.PNG)

_Translation (approx): We weren't able to proceed your request. Please retry or contact us._

### Operating System

iOS

### Operating System Version

iOS 16.2

### Device

iPhone XS & iPhone 14 Pro

### Build Version

2022.11.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Hi @DimitriDR and thank you for your report.

You mention that you are self-hosting. Could you please provide more information about your Bitwarden server installation?

Depending on your installed version ->
![image](https://user-images.githubusercontent.com/2670567/210238269-6449e869-b17c-4657-85d3-d3457c817429.png)

More information on this can be found on our [help-site](https://bitwarden.com/help/)

**Comment by DimitriDR** [comment]
Hi,

You're right... my server wasn't up to date 😜 

Sorry.
