### ISSUE TITLE
Android language bug

### ISSUE THREAD

**Issue by zhtw2013** [bitwarden/mobile#228]
Simplified Chinese was mistakenly displayed in the traditional Chinese system(Android)
![qaq](https://user-images.githubusercontent.com/9501406/34371364-826303ea-eb07-11e7-92b3-bf8f91376ace.png)

**Comment by kspearrin** [comment]
I can't seem to reproduce it. What language setting are you using on your device? This is the current logic:

```
            if(androidLanguage.StartsWith("zh"))
            {
                if(androidLanguage.Contains("Hant"))
                {
                    netLanguage = "zh-Hant";
                }
                else
                {
                    netLanguage = "zh-Hans";
                }
            }
```

Basically we support `zh-Hant` (traditional). If that isn't the setting it always falls back to `zh-Hans` (simplified).

**Comment by kspearrin** [comment]
![image](https://user-images.githubusercontent.com/1190944/34393045-c49907da-eb1d-11e7-8af5-3c20497404a6.png)

These are the only two Chinese options I have on my test devices.

**Comment by zhtw2013** [comment]
My devices system language-  繁體中文(traditional chinese)

**Comment by kspearrin** [comment]
I tried all three of these on my device and they all returned the resource file for `zh-Hant`. Is that not correct?

![image](https://user-images.githubusercontent.com/1190944/34400786-bf11cbd6-eb62-11e7-9bff-6acb7240175d.png)

**Comment by zhtw2013** [comment]
That  is correct.
but...devices display Simplified Chinese...

Test two devices
Asus Zenfone3  繁體中文(台灣) (traditional chinese taiwan)
Xiaomi Redmi Note 4X-繁體中文(traditional chinese)

In google play comment
![002](https://user-images.githubusercontent.com/9501406/34402335-cae0c0ce-ebdb-11e7-97ca-a90ba0da0f8c.png)

I am not the first.....

**Comment by kspearrin** [comment]
This is weird. Are any of those devices rooted or  can you connect them to a PC to view logcat? There should be log messages that show debug output on what language is loaded by the app. Look for:


![image](https://user-images.githubusercontent.com/1190944/34412904-02e5a6ac-ebae-11e7-97ab-56510861afe7.png)

**Comment by zhtw2013** [comment]
this?
![screenshot_2017-12-28-23-45-06-157_com nolanlawson logcat](https://user-images.githubusercontent.com/9501406/34415432-a949de34-ec29-11e7-8825-fb47b5504c5b.png)


Maybe you can change languane name to zh-TW？
zh-Hant →zh-TW

**Comment by kspearrin** [comment]
Yes, but I need to see the one that says "Android Language:____"

**Comment by zhtw2013** [comment]
I found  my zenfonz3 have two chinese...

Chinese traditional(taiwan) and Chinese(taiwan)

In Chinese traditional(taiwan)   Display zh-Hant
But
In Chinese(taiwan) Display zh-Hans.....

Maybe the language code are different...

**Comment by kspearrin** [comment]
Can you please post the logcat output that shows `Android Language:____`?

**Comment by zhtw2013** [comment]
I am trying...

**Comment by zhtw2013** [comment]
![screenshot_2017-12-29-01-32-48-576_rs pedjaapps alogcatroot app](https://user-images.githubusercontent.com/9501406/34418326-6ddb35f0-ec38-11e7-89d6-ec68c31dd831.png)

Language_zh-TW

**Comment by kspearrin** [comment]
OK, great. Thanks. It seems android is handling that differently on different devices. I will add a fix for next version.

**Comment by zhtw2013** [comment]
Thanks for your help.
