### ISSUE TITLE
Unable to set password manually due to “Strong password” placeholder

### ISSUE THREAD

**Issue by Mattchine** [bitwarden/mobile#2291]
### Steps To Reproduce

1. Go to iOS app
2. Click on plus sign or any credential
3. Type password manually

### Expected Result

1. Password should follow input
2. Password should be able to be revealed while typing

### Actual Result

1. Only first character is set to password
2. Unable to reveal password while typing

### Screenshots or Videos

https://user-images.githubusercontent.com/99385254/212131160-b9508567-ceaf-4837-8b29-0b92aa4ba4eb.MOV

### Additional Context

I was actually also typing in the video. But the recorder didn’t record the keyboard.

### Operating System

iOS

### Operating System Version

15.6.1

### Device

iPhone XR

### Build Version

2022.11.0 (2680)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by dwbit** [comment]
Hey @Mattchine I can't reproduce this on my device, can you reinstall the latest version as you are using an outdated one.

**Comment by Mattchine** [comment]
> Hey @Mattchine I can't reproduce this on my device, can you reinstall the latest version as you are using an outdated one. 

I couldn't update app so I reinstalled it manually. It didn't solve the issue.

However, the issue disappear after upgrading to iOS 16.2 (latest).

Thank you :)
