### ISSUE TITLE
Icons (eye or crossed out eyes) wrong for hidden, custom fields.

### ISSUE THREAD

**Issue by lbarnette** [bitwarden/mobile#2300]
### Steps To Reproduce

1. Go to any item with a hidden, custom field.
2. Note that when a hidden, custom field’s characters are blanked out, the eyeball icon has a line through it. Whereas, a similarly hidden password in the default, upper field’s eye icon does NOT have a line through it.

### Expected Result

1. Go to any item with a hidden, custom field.
2. The hidden, custom field item should have a plain eye icon to the right of the blanked out characters.
3. Clicking on the icon should change it to a crossed out eye icon when the hidden text becomes legible.

### Actual Result

Clicking on the crossed our eye icon changes it to the normal eye icon when the password becomes legible. This is the opposite of the desired result, and is inconsistent with the desktop application and browser plugins.

### Screenshots or Videos

![7D9299B0-7897-4FC6-88CC-7C42FFD1CE89](https://user-images.githubusercontent.com/82415786/212756772-365d1be0-7220-4da7-be42-25675cb5bb9f.jpeg)

### Additional Context

Although I produced this bug on IOS, Reddit users with Android mobile phones state that they show the same, reproducible bug.

### Operating System

Android, iOS

### Operating System Version

16.2

### Device

iPhone 8 Plus

### Build Version

Version: 2023.1.0 (2886)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by mhmatthewhugley** [comment]
Can confirm this is a issue on Android version 2022.11.0

**Comment by Snowpop** [comment]
Can repro (Version: 2022.11.0 (5580))

**Comment by PlagueCze** [comment]
Can reproduce. Android app version 2023.1.0 (5786).
![Screenshot_20230117-075755](https://user-images.githubusercontent.com/17255105/212830819-2aea376a-a7c8-44a1-8673-c21facd0fce8.jpg)
