### ISSUE TITLE
iOS/Android Apps Don’t Retain Settings on Log Out

### ISSUE THREAD

**Issue by QuantHead** [bitwarden/mobile#2301]
Update: Android users also reporting this bug on Bitwarden Community forums so I have updated bug title. This appears to be a clearly identifiable bug. See: [https://community.bitwarden.com/t/ios-android-apps-don-t-retain-settings-after-log-out/48931/1](https://community.bitwarden.com/t/ios-android-apps-don-t-retain-settings-after-log-out/48931/1) 

Bug: iOS/Android Apps Don’t Retain Settings on Log Out

### Steps To Reproduce

Product: iOS Bitwarden app.  
Platform: Latest version of Bitwarden app on latest version of iOS.  

Issue: When you Log Out, all settings you customized (e.g clear clipboard, Face ID, Vault Timeout and Vault Action, Sync Refresh, etc.) revert to default when you sign back in.  This does not occur with Lock.  This also occurred in the last version of Bitwarden.  

Very easy to reproduce.  I just tried it again as I was typing this bug report and was able to reproduce once again.  

### Expected Result

Expectation: App should retain customized settings when you Log Out and log back in.  

### Actual Result

Settings not retained. 

### Operating System

iOS

### Operating System Version

iOS 16.2 / Bitwarden 2023.1 version.

### Device

iPhone 12

### Build Version

16.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by rjack1201** [comment]
I'm also experiencing this issue on 2023.1.0 on Android 13

**Comment by QuantHead** [comment]
@mp-bw Thanks for resolving!  Confirmed this is working with 2023.3.0 release.
