### ISSUE TITLE
iOS - Sync Failed on vault with 6k+ items

### ISSUE THREAD

**Issue by johnduprey** [bitwarden/mobile#2308]
### Steps To Reproduce

1. Have over 6,000 items (in my case 6657) combined in Personal and Org vaults
2. Attempt to synchronize the iOS app with vault from Settings > Sync

### Expected Result

Sync should succeeed

### Actual Result

- Receive Sync Failed alert
- Device console reports `BitwardeniOS(HangTracer)[63814] <Notice>: Hang detected: 1.01s (always-on hang reporting)`

### Operating System

iOS

### Operating System Version

16.2

### Device

iPhone 13

### Build Version

2023.1.0 (2886)

### Beta

- [x] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! The Bitwarden team is constantly looking to improve the experience for larger vault accounts. 

We have an issue open to track improvements made for the browser extension (https://github.com/bitwarden/clients/issues/1597), so I will keep this issue open in order to track changes for changes in the mobile application.

If you wish to add any information/screenshot/recording or so, please do it here and our engineering team will review it.

Thanks!

**Comment by johnduprey** [comment]
@Greenderella Thanks for following up. While I believe that the sync issue may be related to the performance problem reported for the other platforms, this one is different as it will not sync anything at all. I can get it to pull in just my personal vault if I remove access to the organization collections, so there's a direct correlation to the Sync Failed message and the vault size. 

I've attached some screenshots of a fresh login to the org account. 

![image](https://user-images.githubusercontent.com/15741649/216171684-680467ac-a851-4130-ae9c-1826f20dca65.png) ![image](https://user-images.githubusercontent.com/15741649/216171708-d59abaae-c2ca-4795-9fce-c0a6204a1970.png)

**Comment by johnduprey** [comment]
I had one of my colleagues test on Android and we get the same result there.

**Comment by johnduprey** [comment]
Removing roughly 500 passwords from the Organization vault now allows my device to sync again. I'm thinking the limit is somewhere between 6300-6700 items before we experience sync failures.

**Comment by Greenderella** [comment]
Hi @johnduprey, some changes have been introduced in the last month to improve the performance and general function of larger vault. We have tested this report with a 5k and 15k vault and both the login and sync function work as expected. Could you please corroborate this?

**Comment by Greenderella** [comment]
Good to know!

Regarding the autofill issue, I'm able to reproduce this while trying to autofill GitHub with 1000 items saved for it, and autofill fails every time unless you tap on the last used entry that gets offered while the Vault is unlocked:

![image](https://github.com/bitwarden/mobile/assets/5418577/db6ade3b-2082-4b3d-897f-b9782322f70b)

I will close this issue as I have generated a new one for the autofill action (https://github.com/bitwarden/mobile/issues/2645), that way we can keep a better track of the reports.

Thanks!
