### ISSUE TITLE
App auto fill does't switch back to app

### ISSUE THREAD

**Issue by Noah-Huppert** [bitwarden/mobile#231]
Android: 8.1  
Device: Pixel 2

When I use the app fill notification to fill an application. The BitWarden app will not switch back to the application I was originally trying to fill.  

Steps to reproduce:

0. Have the persistent fill notification enabled, as well as the accessibility service
1. Open any application (for example TD Bank)
2. Click the Bitwarden fill notification 
3. Observe as you are taken to your vault and shown relevant site matches
4. Click on a site
5. Click "OK" on the window warning your of an inexact match
6. Observe as you are taken back to the general vault screen, but not to the application you were just trying to fill

Let me know if you require an additional details or would like me to carry out any debugging steps.

**Comment by kspearrin** [comment]
Tested this exact scenario in TD Bank app on my Nexus 5X and was not able to reproduce it so I am not sure where the problem is. It seems the Pixel devices have had a lot of inconsistencies with accessibility services these days.

**Comment by Noah-Huppert** [comment]
Hi kspearrin,

Are there any logs I can send over? Or a screen recording? This issue occurs with every single app and on every single webpage (with Firefox).

**Comment by kspearrin** [comment]
How are you seeing this on Firefox? Firefox doesn't support accessibility services. I suppose a screen recording will help make sure I doing exactly what you are.

**Comment by Noah-Huppert** [comment]
So it turns out I can't really record my screen. B/c at least with the screen recorder I use, the Bitwarden window appears as a black square covering the entire screen.

Is this part of some anti screenshot measure?

**Comment by kspearrin** [comment]
@Noah-Huppert Ah yes, screenshots/recording are disabled in the app. Forgot about that.

**Comment by Noah-Huppert** [comment]
I whipped out my old Moto to take a video, but now I can't reproduce the issue. I'll record one when it starts happening again.

**Comment by Noah-Huppert** [comment]
This issue is still occurring every once and a while. The biggest problem is I can't screen capture. So it makes trying to record every use of the app, to catch the bug, not realistic.  

Do you think a slideshow of pictures, simulating the behavior of the app while the bug is occuring would be of any use?  

I struggling to think of what kind of information would be useful for debugging what sounds like a pretty obscure bug.

**Comment by Noah-Huppert** [comment]
This issue is still occurring every once and a while. The biggest problem is I can't screen capture. So it makes trying to record every use of the app, to catch the bug, not realistic.  

Do you think a slideshow of pictures, simulating the behavior of the app while the bug is occuring would be of any use?  

I struggling to think of what kind of information would be useful for debugging what sounds like a pretty obscure bug.

**Comment by Noah-Huppert** [comment]
This issue is still occurring every once and a while. The biggest problem is I can't screen capture. So it makes trying to record every use of the app, to catch the bug, not realistic.  

Do you think a slideshow of pictures, simulating the behavior of the app while the bug is occuring would be of any use?  

I struggling to think of what kind of information would be useful for debugging what sounds like a pretty obscure bug.

**Comment by kspearrin** [comment]
What browser are you using? You mentioned Firefox before but autofilling isnt supported in Firefox.

**Comment by Noah-Huppert** [comment]
I am using Firefox. But this issue occurs with all apps. Like the TD Bank app.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
