### ISSUE TITLE
Autofill is entering the password into the email address field in PayPal.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#2315]
### Steps To Reproduce

1. Navigate to (https://www.paypal.com/us/home).
2. Tap on (Log In).
3. Tap on the email address field.
4. Autofill your credentials from Bitwarden.

### Expected Result

Bitwarden should enter the email address into the email address field.

### Actual Result

Bitwarden enters the password into the email address field.

### Screenshots or Videos

N/A.

### Additional Context

https://github.com/bitwarden/mobile/issues/1389#issuecomment-1399327956

### Operating System

Android, iOS

### Build Version

2023.1.0.

### Beta

- [ ] Using a pre-release version of the application.

**Comment by aj-rosado** [comment]
Solved with https://github.com/bitwarden/mobile/pull/2331
