### ISSUE TITLE
 Autofill is entering the password into the email address field in Outlook and Microsoft.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#2316]
### Steps To Reproduce

1. Navigate to (https://outlook.live.com/owa/).
2. Click on (Sign in).
3. Tap on the email address field.
4. Autofill your credentials from Bitwarden.

### Expected Result

Bitwarden should enter the email address into the email address field.

### Actual Result

Bitwarden enters the password into the email address field.

### Screenshots or Videos

N/A.

### Additional Context

Reproduced in Chrome 109.0 with Inline Autofill on Android 12 on a Samsung Note10+.

### Operating System

Android, iOS

### Build Version

2023.1.0.

### Beta

- [ ] Using a pre-release version of the application.

**Comment by aj-rosado** [comment]
Solved with https://github.com/bitwarden/mobile/pull/2331

**Comment by larena1** [comment]
Why are you closing this? It's still filling the password into the username field in Brave and Chrome on Android. Your PR unfortunately did not change anything.

**Comment by larena1** [comment]
@aj-rosado it's not much of a surprise either as the field's id is `i0116` which is not covered by your PR.

Can you maybe properly fix this?
