### ISSUE TITLE
Autofill not prompting on RedHat login field, but does on password field.

### ISSUE THREAD

**Issue by djchateau** [bitwarden/mobile#2317]
### 
1. Open mobile browser.
2. Navigate to https://redhat.com.
3. Tap Login.
5. Tap on **Redhat login or email** field.
6. Enter a username of any kind.
7. Tap the password field.

### Expected Result

Tapping the username field should show the auto-fill options or show inline autofill when tapping on the username field.

### Actual Result

Auto-fill doesn't present itself, however if you enter a login manually and tap on the password field, autofill will prompt and update the username with the correct username and fill in the password field correctly.

### Operating System

Android

### Operating System Version

13

### Device

Google Pixel 6

### Build Version

2023.1.0 (5786)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by aj-rosado** [comment]
Solved with https://github.com/bitwarden/mobile/pull/2331
