### ISSUE TITLE
Bitwarden does not recognize that there is a credential field and does not offer to autofill at AOL.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#2319]
### Steps To Reproduce

1. Navigate to (https://login.aol.com/).
2. Tap on the email address field.

### Expected Result

Bitwarden should prompt to perform autofill.

### Actual Result

No autofill prompt is displayed.

### Screenshots or Videos

N/A.

### Additional Context

Reproduced in Chrome 109.0 on Android 12 on a Samsung Note10+.

### Operating System

Android, iOS

### Build Version

2023.1.0.

### Beta

- [ ] Using a pre-release version of the application.

**Comment by aj-rosado** [comment]
Solved with https://github.com/bitwarden/mobile/pull/2331
