### ISSUE TITLE
Search should search all entries not just the favourites

### ISSUE THREAD

**Issue by jyavenard** [bitwarden/mobile#232]
On the mobile app, the first and default screen shows is of the favourite. If you perform a search there, it only search in the favourites.

To perform a search everywhere you need to switch to "My Vault" and then retype the search.

This is an unnecessary and non-intuitive behaviour. The favourite screen would typically contains few entries, making the search unnecessary there. Performing a search in that screen will typically yield no results (as it wouldn't be in the favourites)

Ideally a search should be performed in all entries, even if performed in the favourites screen. The results found in the favourites could be placed on top

**Comment by kspearrin** [comment]
This is no longer an issue in the next version (currently in beta) since the favorites tab was removed altogether and combined into the "My Vault" listing.

**Comment by jyavenard** [comment]
Just updated, much better that way thanks.
