### ISSUE TITLE
Android app from F-Droid disables Notifications permission

### ISSUE THREAD

**Issue by lazytownfan** [bitwarden/mobile#2320]
### Steps To Reproduce

1. Install Bitwarden on Android via the F-Droid [repo](https://mobileapp.bitwarden.com/fdroid/) - I did this via [Droid-ify](https://f-droid.org/en/packages/com.looker.droidify/).
2. Hold the Bitwarden icon and tap on "App Info".
3. Tap "Notifications".
4. Tap on the switch for "All Bitwarden notifications"

### Expected Result

I should be able to toggle the "All Bitwarden notifications" on and off.

### Actual Result

The "All Bitwarden notifications" stays off, as if it's permanently toggled off.

### Screenshots or Videos

![UGJNDiK](https://user-images.githubusercontent.com/93500165/213962234-174073d9-c5a8-47da-abd9-750687fe1bc4.png)

### Additional Context

This issue was [mentioned](https://discuss.grapheneos.org/d/3032-cannot-enable-notifications-on-bitwarden-on-pixel-4a) on the GrapheneOS Forum.

I discovered this because I was trying to use the [log in with device](https://bitwarden.com/help/log-in-with-device/) feature on GrapheneOS (without Google Play Services).

### Operating System

Android

### Operating System Version

GrapheneOS build version TQ1A.230105.001.2023011000

### Device

Google Pixel 4a

### Build Version

2023.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hello there, 

Fdroid version does not have Google Play Services, or push notification ability.

**Comment by dwbit** [comment]
@lazytownfan you can read more about the F-Droid release functionality [here](https://bitwarden.com/help/security-faqs/#q-what-third-party-services,-libraries-or-identifiers-are-used-in-my-bitwarden-account).

**Comment by lazytownfan** [comment]
Thank you for the info.

Due to this, I think that there should be a conditional warning that appears when a user tries to activate "log in with device" in the F-Droid version; or at least state this more clearly in the documentation [page](https://bitwarden.com/help/log-in-with-device/) for this feature.

**Comment by onnyyonn** [comment]
There are alternatives to Firebase Cloud Messaging, such as [UnifiedPush](https://f-droid.org/en/2022/12/18/unifiedpush.html). Is there a possibility that the F-droid version supports it in the future?
