### ISSUE TITLE
Android app from F-Droid disables Notifications permission

### ISSUE THREAD

**Issue by lazytownfan** [bitwarden/mobile#2320]
### Steps To Reproduce

1. Install Bitwarden on Android via the F-Droid [repo](https://mobileapp.bitwarden.com/fdroid/) - I did this via [Droid-ify](https://f-droid.org/en/packages/com.looker.droidify/).
2. Hold the Bitwarden icon and tap on "App Info".
3. Tap "Notifications".
4. Tap on the switch for "All Bitwarden notifications"

### Expected Result

I should be able to toggle the "All Bitwarden notifications" on and off.

### Actual Result

The "All Bitwarden notifications" stays off, as if it's permanently toggled off.

### Screenshots or Videos

![UGJNDiK](https://user-images.githubusercontent.com/93500165/213962234-174073d9-c5a8-47da-abd9-750687fe1bc4.png)

### Additional Context

This issue was [mentioned](https://discuss.grapheneos.org/d/3032-cannot-enable-notifications-on-bitwarden-on-pixel-4a) on the GrapheneOS Forum.

I discovered this because I was trying to use the [log in with device](https://bitwarden.com/help/log-in-with-device/) feature on GrapheneOS (without Google Play Services).

### Operating System

Android

### Operating System Version

GrapheneOS build version TQ1A.230105.001.2023011000

### Device

Google Pixel 4a

### Build Version

2023.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by ElSamhaa** [comment]
Can we get a UnifiedPush support for the fdroid version please?

**Comment by NicholasFlamy** [comment]
> Hello there,
> 
> Fdroid version does not have Google Play Services, or push notification ability.

Does the GitHub release apk have Firebase Cloud Messaging?
