### ISSUE TITLE
Can't scan QR codes

### ISSUE THREAD

**Issue by Harvsch** [bitwarden/mobile#2350]
### Steps To Reproduce

Scan QR code 

### Expected Result

A clear undistorted image

### Actual Result

I have difficulty scanning QR codes in Bitwarden on my Samsung A71 phone. The image is strangely distorted and sometimes cannot be read by the program.
2FAS does not exhibit the same distortion and does not have difficulty reading the codes. The problem is worst with sites that produce a smaller code image. The QR image also appears larger on the phone's display with 2FAS than with Bitwarden.

### Operating System

Android

### Operating System Version

Android 13

### Device

Samsung SM-A71 5G

### Build Version

2023.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

This issue appears to be duplicated from this one: https://github.com/bitwarden/mobile/issues/1130

I will proceed to close this one. If you wish to add any further information/screenshots/recordings etc., please feel free to do so here: https://github.com/bitwarden/mobile/issues/1130  - our engineering team will be happy to review these.
