### ISSUE TITLE
Issue enabling autofill and pasword filled into username field

### ISSUE THREAD

**Issue by leowankerddd** [bitwarden/mobile#2363]
TWO YEARS LATER and it Still doesn't work!  Bit warden please fix auto fill on android already you know that it's broken for 2 years now. My keypass android password manager works fine so this is absolutely your fault and your fault only.

Autofilling usernames only will not be possible on Android. We don't have any way of detecting a username field if it is not accompanied by a password field.

_Originally posted by @clayadams5226 in https://github.com/bitwarden/mobile/issues/1173#issuecomment-752319676_

**Comment by djsmith85** [comment]
Hi @leowankerddd,

I have moved your title into your comment, as it's non-descriptive of the issue and won't help anyone searching for it.

We recently made some improvements to the username field detection, which will be available as of 2023.2 (https://github.com/bitwarden/mobile/pull/2331)

For general information around Autofill on Android and the different ways to configure it, please have a look at our help article [here](https://bitwarden.com/help/auto-fill-android/).

If this is still an issue, then please get in touch with [support](https://bitwarden.com/contact/) as suggested by @dbosompem.

Closing this now.

**Comment by larena1** [comment]
@djsmith85 please read my comments in the mentioned PR. The fix is not working as it's still filling the password into the username field on Microsoft and Google and probably lots of others login forms which username field's id is not among those that were introduced in the PR.

Please kindly fix this properly after years.

@aj-rosado

**Comment by larena1** [comment]
@leowankerddd

https://github.com/bitwarden/mobile/suites/10909922347/artifacts/551261135

Can you try this APK and see if it fixed your issue? It's from the automated build pipeline and included the fix mentioned. It finally stopped Bitwarden from filling the password into the username field on PayPal but still does so on Google and Microsoft for me.

**Comment by leowankerddd** [comment]
@larena1  I am going to try tech support first. I have 2 Android devices, phone & tablet, both Samsung.
My other password manager, Keepass2Android, does autofill properly in browsers & apps. Bitwarden just doesn't offer to fill in anything in places where Keepass2Android does. It's like Bitwarden isn't really there at all. I have read all of the help files and tips. Even turned on the Accessibility feature to no avail.

I will probably first make a short video capture of the situation to better communicate what is going on. I will record the screen with myself trying to get Bitwarden to pop up, and demonstrate how Keepass2Android works in those same places.
If I go to Twitter.com and try and log in when I tap on the login box and keepass to Android is my default autofill provider it shows a button letting me tap on it and choose the proper ID and password and it fills it in.
When Bitwarden is the default autofill provider no opportunity to choose a user ID is available.

I have been entering servers and passwords into the Bitwarden client with the hope that I could one day switch to Bitwarden but I can't if I can't get autofill to work.

As I said I'll make a brief video demonstrating what is happening on my device so that if somebody in tech support wants to actually observe specifically what is happening on my device they can.

**Comment by larena1** [comment]
@leowankerddd don't even bother contacting their support. They're aware of the issues for years and there have been countless issues and comments here regarding that but they don't care.

They even just released the new version which supposedly fixed the Microsoft login issue but it doesn't. I reported that days ago and never got any reply. Unfortunately the Bitwarden team is nothing but ignorant and unprofessional.

**Comment by leowankerddd** [comment]
Somehow, after muddling around, I made a little progress. Walmart website now offers Bitwarden autofill, only it ALWAYS enters the PASSWORD in the LOGIN field! Same for Amazon.com. These two websites are looking for the e-mail address or user ID only not both the user ID and password on one screen. This may be why Bitwarden is failing on these websites. Frustrating. KeePass2Android can handle these with no problems.

**Comment by larena1** [comment]
Yeah I reported that weeks ago in https://github.com/bitwarden/mobile/pull/2331. The logic that was introduced is totally unreliable as it requires the username field to have a specific id but nobody cared. It's the same also on Google and Microsoft.

https://github.com/bitwarden/mobile/pull/2367 that is my PR that's supposed to properly fix this but it's not been picked up yet.
