### ISSUE TITLE
iOS: Tools, ugly margins

### ISSUE THREAD

**Issue by oldrich-s** [bitwarden/mobile#237]
The margins between the text and the horizontal lines in the Tools section of the iOS app on iPhone 6 and the latest iOS look ugly:

![image-1 1](https://user-images.githubusercontent.com/37391/34510562-308642a0-f055-11e7-82f0-1fd87d22bae2.jpg)

**Comment by kspearrin** [comment]
Yes, we're aware of this one and working on a solution at the moment.

**Comment by kspearrin** [comment]
Is this any better now?

**Comment by czb** [comment]
app was updated yesterday and no, still no bottom margins for some of the items.

**Comment by kspearrin** [comment]
This screen is gone in next version. Closing.
