### ISSUE TITLE
generating Firefox relay address set to block

### ISSUE THREAD

**Issue by ButlerJoseph** [bitwarden/mobile#2375]
### Steps To Reproduce

1. Go to 'generator'
2. Click on 'forwarded email alias'
3. Select service 'firefox relay'
4. Click on 'generate username.'

### Expected Result

A new Firefox relay address is created which is set to block emails set to none.

### Actual Result

A new Firefox relay address is created which is set to block emails set to all.

### Operating System

Android

### Operating System Version

13

### Build Version

2023.1.0 (5786)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @ButlerJoseph ,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by jwhitlock** [comment]
We've been able to reproduce this on the Firefox Relay side. If you generate a Relay Address with an empty JSON body, then the address has `enabled:true`, and Block is set to None. 

The `POST` from the Bitwarden Android client appears to send a JSON body based on the request size. We do not log the body of the `POST`, so we can't see what is being sent by Bitwarden. It may be sending `enabled: false` or some other value that we're interpreting as False. Explicitly sending `{"enabled": true}` will work.

The Bitwarden website correctly generates addresses with Block set to None.
