### ISSUE TITLE
Chaning KDF to Argon2id causes Android app to crash

### ISSUE THREAD

**Issue by akvadrako** [bitwarden/mobile#2382]
### Steps To Reproduce

1. On the web UI, change KDF to Argon2id.
2. Use the defaults or something more conservative like 19 MB / 2 iter / 1 parallel 
3. Try to login using Android app.
4. App Crashes

### Expected Result

The app does not crash.

### Actual Result

It crashes.

### Operating System

Android

### Operating System Version

13

### Device

Pixel 4a

### Build Version

2023.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by mderazon** [comment]
I am on version `2023.2.0` and Bitwarden Android doesn't sign in
Getting this:
![WhatsApp Image 2023-03-05 at 18 11 52](https://user-images.githubusercontent.com/717076/222978054-a079f0ce-8c25-428a-a3da-26af77248191.jpeg)
