### ISSUE TITLE
iOS password autofill doesn't work with Argon2id

### ISSUE THREAD

**Issue by bobokapi** [bitwarden/mobile#2383]
### Steps To Reproduce

1. Change KDF to Argon2id.
2. Enable password autofill.
3. Go to any website or app and try to autofill a password.
4. Type in master password and hit enter.

### Expected Result

Password is autofilled.

### Actual Result

Bitwarden autofill quits, but doesn't autofill the password. When I try to click on autofill again - it again prompts me to enter my master password, and again it quits without autofilling the password.

### Additional Context

When I change the KDF back to PBKDF2, then password autofill works again.

### Operating System

iOS

### Operating System Version

iOS 16.2

### Device

iPhone 12 Pro and iPhone 14 (tried on both and had the same issue)

### Build Version

2023.2.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by bobokapi** [comment]
@quexten FYI

**Comment by quexten** [comment]
Do you have the memory setting set to > 64MiB?

**Comment by bobokapi** [comment]
Yes, I had it set to 256 MiB or 512 MiB IIRC. When I changed back to the default setting, it worked. I didn't realize that was the problem because it worked when I logged in to the app, but didn't work for autofill. Do you know why the memory parameter needs to be set lower for autofill to work?

**Comment by kspearrin** [comment]
I believe iOS Extensions have limited memory available from the OS and crash when that is exceeded.

**Comment by quexten** [comment]
Yes. On some other password managers there is a warning above 64 MiB. In the forums users tested up to 80MiB without issues, but I guess that also depends on the size of the database. It does not happen when biometrics are used.

Maybe there should be a warning on iOS when logging in (or auto-filling) and having > 64MiB, such as: "Warning: Due to restrictions on iOS, auto-fill does not work reliably for argon2 memory configurations above 64MB"

**Comment by bobokapi** [comment]
Thanks for the information. I'll close this issue. I agree that having a warning when logging in on iOS with >64 MiB would be helpful.

**Comment by arderyp** [comment]
I am having this issue on latest iOS with argon2 memory set to 64.

The issue only started happening maybe since iOS 16

Sometimes it works despite the warning, sometimes it doesn't
