### ISSUE TITLE
copy does not work anymore

### ISSUE THREAD

**Issue by pimpampoum2** [bitwarden/mobile#2384]
### Steps To Reproduce

4. Click on '...'

### Expected Result

1 Go to bitwarden 
2 click on copy

### Actual Result

 a few does ago Xiaomi updated the system Miui13 to Miui 14 in my redmi lite 11. Since that date I noticed that the copy function does not work anymore

### Operating System

Android

### Operating System Version

android 13 TRQ1.220829.002

### Device

redmi 11 Lite 5Gne

### Build Version

  Mui 14.04

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @pimpampoum2,

Thank you for this report. I am unable to reproduce this behaviour in testing; Could you please create a ticket about this (https://bitwarden.com/contact/) and include a link to this GitHub report, so we'll troubleshoot this together?

In your ticket, could you please mention which keyboard you are using, and if you have a clipboard manager installed on your device?


Thank you in advance,
