### ISSUE TITLE
Master password re-prompt bypass when use gboard inline auto fill

### ISSUE THREAD

**Issue by singer233** [bitwarden/mobile#2387]
### Steps To Reproduce

1. Have a Login item with Master password re-prompt on
2. Go to the website that trigger inline auto fill  
3. Select the Matching items that have Master password re-prompt on (in this step it will ask Master password again)
4. don't enter it, instead click the search button at the top right
5. search the same item, let it show in the result
6. tap the item with Master password re-prompt on
7. click Auto-fill
8. the password has been auto filled 

### Expected Result

either items that have Master password re-prompt on turned on do not ask Master password when inline auto fill 
or the result of  search will also ask for Master password when auto fill

### Actual Result

the password has been auto filled  without Master Password

### Screenshots or Videos

https://user-images.githubusercontent.com/49394090/220295225-b125b67f-97c1-4e0d-9e58-41b26370b0c3.mp4

### Operating System

Android

### Operating System Version

13

### Build Version

2023.2.0(5994)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. However seeing as you have video of the issue appearing I will pass this to QA for more advance testing.

**Comment by joshtrichards** [comment]
Reproduced. The key step seems to be performing the manual search versus using the initially provided matching items list.

Also on Android 13 though I suspect that'll turn out to be irrelevant.

**Comment by lahma0** [comment]
Was this ever looked into and/or fixed?

**Comment by singer233** [comment]
From my experience it is fixed.
Thanks to the dev team

Jordan Johnson ***@***.***> 于 2024年4月11日周四 16:56写道：
