### ISSUE TITLE
Android instructions no longer valid

### ISSUE THREAD

**Issue by jidanni** [bitwarden/mobile#2403]
### Steps To Reproduce

On Android follow the instructions on https://bitwarden.com/help/disable-browser-autofill/

### Expected Result

You will be able to reach the password manager.

### Actual Result

The webpage at chrome://settings/passwords might be temporarily down or it may have moved permanently to a new web address.

### Additional Context

https://support.google.com/chrome/answer/95606 mention s the current correct way to get to the password manager. So your article needs to be rewritten to take that into account for android.
https://bugs.chromium.org/p/chromium/issues/detail?id=1421731 shows that one cannot get there anymore via a URI, even if hand typed.

### Operating System

Android

### Operating System Version

Current Chrome Dev

### Build Version

I'm talking about  your current help page

### Beta

- [ ] Using a pre-release version of the application.

**Comment by jidanni** [comment]
Also as we see in https://support.google.com/chrome/answer/95606 if you have previously saved a password, it is still going to prompt you about filling it in, no matter what buttons you use to turn it off!

**Comment by SergeantConfused** [comment]
Hi @jidanni,

Thank you for this report. I imagine that we could have been clearer, but that guide is tailored to desktop browsers, not mobile ones; Based on the screenshots within it. If you'd like us to create a similar guide for mobile browsers, or if you have any other suggestions to any other Help Centre article, please feel free to use the (Make a Suggestion to this Article) button at the bottom of each article.

We use GitHub issues as a place to track bugs and other development related issues; I am going to close this report now.

I thank you in advance for your understanding,
