### ISSUE TITLE
ios cant sync and cant login after reinstalling

### ISSUE THREAD

**Issue by FritsOV** [bitwarden/mobile#2405]
### Steps To Reproduce

I dont know if it can be reproduces on your side.
 

### Expected Result

I run vaultwarden local as an Homeassistant add on. 
on a pc i bitwarden is working as expected. No problems to sync no problems logging in. 
On my iPhone13 everything worked fine until  23-2-2023. after this date there was no way to 
sync the iPhone with the vault. 
I tried logging in and out of the app several times but that didnt solve the problem. 
I deleted the app from my phone and reinstalled several times but that didnt solve the problem
Now, after last delete off the app, i cant login with the error "username or password is incorrect. Try again. 
The username is correct and the password also. Yes i tripple checked everything.  On 
THe ios app opened with face recognition. 
After more tries i dont get the wrong username and password anymore.
On ios i cant get in. on startup and after filling in the username it stays loading and ends with a time out request. 
i double checked the settings and they are all the same.
Logging in from a windows machine is no problem. even after several times logging out en in i cant reproduce the problem on the windows machine. 

i took an old android phone and installed bitwarden and here also the same problem. login error with  username or 
password is incorrect. Impossible! i checked three times and tried more than once. 
[edit edit]  after investigating i saw i forgot the url in the setup from the app. after filling in the url the android connects directly to the vault and can sync with no problem. 
logfile on server gives me for log on with android:

[2023-03-06 23:22:32.536][response][INFO] (prelogin) POST /api/accounts/prelogin => 200 OK
[2023-03-06 23:22:32.980][request][INFO] POST /identity/connect/token
[2023-03-06 23:22:33.044][vaultwarden::api::identity][INFO] User XXXXXXXXXl logged in successfully. IP: 192.168.1.68
[2023-03-06 23:22:33.044][response][INFO] (login) POST /identity/connect/token => 200 OK
[2023-03-06 23:22:33.187][request][INFO] GET /api/sync
[2023-03-06 23:22:33.190][response][INFO] (sync) GET /api/sync?<data..> => 200 OK

Current version: 0.19.0  running as addon in Home assistant 

How to resolve this problem?

### Actual Result

actual result is:
On windows machines (win10 and win11) running edge there is no problem.
Sync is okay and can logout and login

Actual result on ios cant login, wrong password or username
actual result on android -> same as ios

### Operating System

Android, iOS

### Operating System Version

ios 16.1.2 and android 12

### Build Version

app version cannot see // Current version: 0.19.0  running as addon in Home assistant 

### Beta

- [ ] Using a pre-release version of the application.

**Comment by TroyBW** [comment]
Hi there,

This appears an issue regarding Vaultwarden. Vaultwarden is a project independent of Bitwarden, and we are unable to provide support for it. Please contact Vaultwarden support for further assistance: https://github.com/dani-garcia/vaultwarden#get-in-touch

The issue here will be closed.
