### ISSUE TITLE
Auto-fill occasionally searches for the browser rather than the site on Android.

### ISSUE THREAD

**Issue by ryanpcmcquen** [bitwarden/mobile#242]
Instead of searching for the site you are currently on. This makes using bitwarden on Android quite a bit more frustrating.

For example, it will search for `com.brave.browser` when using Brave.

**Comment by kspearrin** [comment]
I'm not able to reproduce . We've always support brave properly since day 1.

**Comment by ryanpcmcquen** [comment]
Strange, I restarted my phone and now all is working well. Konpai!

**Comment by ryanpcmcquen** [comment]
Still reproducing this often (not every time). It has happened on two different phones running Android 7.x. Is this improved in Android 8.x?

**Comment by kspearrin** [comment]
I've seen this happen on occasion with Chrome. It seems to occur if I open the notification very quickly while the page is still loading. Can you confirm the same?

**Comment by ryanpcmcquen** [comment]
No, it also happens even after the page has fully loaded.

**Comment by andrebrait** [comment]
This is exactly the same as #310

**Comment by ryanpcmcquen** [comment]
I'm on Android 8.x now and the issue still persists.

**Comment by rcdailey** [comment]
I'm seeing this issue on stable chrome on Android 8.1

**Comment by ryanpcmcquen** [comment]
Happens on all browsers.

**Comment by ryanpcmcquen** [comment]
Also happens on Android 9.x.

**Comment by quthla** [comment]
I also have this issue often. In Chrome but also in Firefox Klar. 

Is Bitwarden still being worked on or has development stopped?

**Comment by Crocmagnon** [comment]
I also experienced this once with Firefox on iOS. The password that was offered was for firefox.com

**Comment by IulianDita** [comment]
I noticed that this happens most often (yet not always) when none of the username or password fields are selected. If I tap in either of them, Bitwarden can identify the website correctly.

**Comment by OEssHRERLr770rGGLOH0** [comment]
It happens on every website which makes Bitwarden unusable with Chrome. 

Chrome 76.0.3809.89
Android 9; Pixel Build/PQ3A.190801.002

**Comment by johndonuk** [comment]
This happens every time since a recent system update on my Pixel 2. Instead of the URL it searches for com.android.chrome. Chrome 76.0.3809.111 Android 9; Pixel 2 Build/PQ3A 190801.002.

**Comment by kspearrin** [comment]
@johndonuk This is a known bug in latest versions of Chrome. See https://github.com/bitwarden/mobile/issues/562

**Comment by phpones-br** [comment]
Happens with my Chrome on Pixel 3 every time on every site. Android 9 and now Android 10 also. Is there a workaround or something? Only way I can use bitwarden is if I go manually to my vault and search for the site :(

> @johndonuk This is a known bug in latest versions of Chrome. See #562
Users say that other password managers don't have this problem, only Bitwarden.

**Comment by johndonuk** [comment]
Since Chrome 77.0 the problem has been resolved for me.

**Comment by phpones-br** [comment]
Confirmed to work with Chrome 77. 
But since some sites (login.yahoo.com for example) don't work at all with autofill framwork, I had to enable both autofill framework + autofill acessibility, so the issue of this ticket doesn't become so problematic anyway...

**Comment by OEssHRERLr770rGGLOH0** [comment]
> Since Chrome 77.0 the problem has been resolved for me.

Same here.

**Comment by Muurtegel** [comment]
I just installed Bitwarden on an Android device with Chrome 79.0.3945.93 and I run into the same issue. Sometimes it works perfectly fine, other times it says it can't find items for com.android.chrome.

Any ideas on how to solve this?

**Comment by dohlin** [comment]
What are the chances of this actually getting looked at and fixed?  I adore Bitwarden the privacy aspects it supports especially being able to self-host...but man this issue is annoying!!  And it's been going on for a while now!

**Comment by tapufd** [comment]
I'm using the latest version of Bitwarden and Edge (chrome-based) on my Android, but the autofill function doesn't work and has never worked for me. When I try to autofill a website, it opens Bitwarden app and mentions: there are no items in your vault for <domain.something>.
What I see is that only the domain-part is used in Bitwarden... some examples:
* site = test1.domain.local -> Bitwarden searches on "domain.local"
* site = test2.domain.local -> Bitwarden searches on "domain.local"
* site = test3.other.ext -> Bitwarden searches on "other.ext"
For me it looks like that the url from Edge is not passed through to Bitwarden in a good way.
Please have a look please!
Br, T

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
