### ISSUE TITLE
Android app instantly crashes.

### ISSUE THREAD

**Issue by vixpr** [bitwarden/mobile#2424]
### Steps To Reproduce

Open the Android app.

### Expected Result

I'll login and be able to see my passwords or whatever.

### Actual Result

App crashes.

### Screenshots or Videos

![Screenshot_2023-03-22-23-10-49-540_com mi android globallauncher-edit](https://user-images.githubusercontent.com/71558811/227026463-b0474025-1732-4aa9-941b-4a6cd2271153.jpg)

### Operating System

Android

### Operating System Version

13

### Device

Poco X3 Pro

### Build Version

2023.3.0

### Beta

- [x] Using a pre-release version of the application.

**Comment by aleks01100001** [comment]
by me the issue was solved by clearing the data

**Comment by kouhe3** [comment]
same here. 😢

**Comment by sp1cyf0x** [comment]
Here is the crash log on my Poco X3 NFC (non-Pro) running LineageOS microG.
[bitwarden.log](https://github.com/bitwarden/mobile/files/11047509/bitwarden.log)

**Comment by bentolor** [comment]
I think I share the problem @gxtu mentions due to the stack trace I receive on crash documented in #2429

**Comment by mp-bw** [comment]
Apologies for the inconvenience everyone. `2023.3.1` will be released shortly, and it should work without having to clear any existing data.
