### ISSUE TITLE
iPadOS version instantly crashes on start

### ISSUE THREAD

**Issue by Inrumpo** [bitwarden/mobile#2425]
### Steps To Reproduce

1. Open the app.
2. It crashes. 

100% reproducible on my end. 

### Expected Result

The app shouldnˋt crash. 

### Actual Result

The app flashes a a Bitwarden logo for a fraction of a second and then crashes.

### Additional Context

Might be connected to the just released version 2023.3.0.

### Operating System

iOS

### Operating System Version

iPadOS 16.3.1

### Device

iPad Pro 10.5

### Build Version

2023.3.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by TheJulianJES** [comment]
Just got the update on an iPhone 12 Pro running iOS 16.4 RC (1). So it looks like not only iPads are affected.

**Comment by smcue** [comment]
Same issue on iOS 16.4 RC. Hopefully we see a hotfix soon.

**Comment by hduelme** [comment]
Same problem on iOS 16.3.1

**Comment by PTRFRLL** [comment]
Confirming 2023.3.0 crashes on iOS 16.3.1 whereas 2023.2.0 does not.

**Comment by flowent59** [comment]
Same problem for me on ios 16.3.1

**Comment by ysnr777** [comment]
Same problem on iOS 16.3.1. After reinstalling the app, the problem is resolved and can be used normally.

**Comment by rusty1281** [comment]
Can confirm this. iPhone 11 (latest iOS).

**Comment by rusty1281** [comment]
> Same problem on iOS 16.3.1. After reinstalling the app, the problem is resolved and can be used normally.

Same here

**Comment by mzaferyahsi** [comment]
> Same problem on iOS 16.3.1. After reinstalling the app, the problem is resolved and can be used normally.

Same here..

**Comment by griswoct** [comment]
I'm having the same issue with 2023.3.0 on iOS 16.3.1

**Comment by mp-bw** [comment]
Apologies for the inconvenience everyone. `2023.3.1` will be released shortly, and it should work without having to clear any existing data.
