### ISSUE TITLE
Vault timeout option 'Never' will not persist in version 2023.3.0 on iOS

### ISSUE THREAD

**Issue by ryanpcmcquen** [bitwarden/mobile#2426]
### Steps To Reproduce

1. Go to 'Settings'
2. Click on 'Vault timeout'
3. Click on 'Never'
4. Confirm with 'Yes'
5. Switch to another tab in Bitwarden or exit the program, observe that the option has reverted to '15 minutes'

### Expected Result

'Never' option for 'Vault timeout' would persist.

### Actual Result

'Vault timeout' reverts to '15 minutes'.

### Screenshots or Videos

Video example:

https://user-images.githubusercontent.com/772937/227091623-e6f4a22f-7b10-424d-874a-1467ea409737.MOV

### Operating System

iOS

### Operating System Version

16.3.1

### Device

iPhone SE 2020

### Build Version

Version: 2023.3.0 (3170)

**Comment by lyaaz** [comment]
Same behavior on android v2023.3.0.

**Comment by techbot2342** [comment]
Happening on Android as well. 

Version: 2023.3.0 (6070)

**Comment by Rokcy98** [comment]
Yes

**Comment by omar-mohy** [comment]
The issue still persists on 2023.3.1

**Comment by ryanpcmcquen** [comment]
This has resurfaced, as the 'Never' option is no longer respected on iOS Bitwarden version 2023.9.1.

**Comment by henrikx** [comment]
> This has resurfaced, as the 'Never' option is no longer respected on iOS Bitwarden version 2023.9.1.

Can confirm. Even though I have it set to «Never» it asks again for TouchID or master password every time the app restarts,
