### ISSUE TITLE
Fdroid repo hash not matching

### ISSUE THREAD

**Issue by aaron-watts** [bitwarden/mobile#2428]
### Steps To Reproduce

1. Update in F Droid

### Expected Result

Update to install

### Actual Result

Error, see screenshots

### Screenshots or Videos

![Screenshot_20230323-083904](https://user-images.githubusercontent.com/65028208/227148591-9711f3c2-4c66-4d1b-ae5a-7fe62aef6df9.png)
![Screenshot_20230323-083851](https://user-images.githubusercontent.com/65028208/227148609-529c5ce1-b467-4eed-845d-533bfbe2950e.png)

### Operating System

Android

### Operating System Version

12

### Device

Fairphone 4

### Build Version

2023.2.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by tbshfr** [comment]
Got the same issue, was able to update to 2023.3.0 without problems. 2023.3.1 can't be validated and for that reason I am unable to update.

**Comment by NukeManDan** [comment]
Same as above, double checked repo information to be sure on fdroid to match that given here https://mobileapp.bitwarden.com/fdroid/

It does indeed match at a glance at least. So the fingerprint at least seems correct.

**Comment by dwbit** [comment]
Thanks all, the team is tracking this one

**Comment by vvolkgang** [comment]
@aaron-watts this should be fixed, can you refresh your F-Droid repos and retest please?

**Comment by NukeManDan** [comment]
Fixed for me - thanks!

**Comment by aaron-watts** [comment]
Update worked this time 👍

**Comment by Sanjay451** [comment]
I facing this issue right now. I tried to update the app using driod-ify, since then I am unable to update. Not able to update from f-droid and droid-ify right now.

Can someone help me?
