### ISSUE TITLE
IOS version 6.17 crashed on launch

### ISSUE THREAD

**Issue by Saga3596** [bitwarden/mobile#2437]
### Steps To Reproduce

Running IOS 16.3.1 - after updating to Bitwarden 6.17. App crashes on launch. 

### Expected Result

Expected app to launch

### Actual Result

Crashes on launch

### Operating System

iOS

### Operating System Version

16.3.1 

### Device

Iphone XR

### Build Version

16.3.1 

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Hi @Saga3596 and thank you for your report.

This has previously been reported with https://github.com/bitwarden/mobile/issues/2425 and a fix was made with https://github.com/bitwarden/mobile/pull/2430.

`2023.3.1` has been released to the stores and should be available soon.
