### ISSUE TITLE
Bitwarden vault timeout "Never" option is not working in Android 

### ISSUE THREAD

**Issue by rrha** [bitwarden/mobile#2441]
### Steps To Reproduce

1.Set vault timeout to "Never" in "Settings" window 
2.Switch to another window "My Vault" or "Generator" or "Send"
3. Switch back to "Setting" window
4. Look at vault timeout it switches back to 15 minutes.

### Expected Result

"Never" option in vault timeout is not working 

### Actual Result

"Never" option in vault timeout is not working 

### Screenshots or Videos

"Never" option in vault timeout is not working 

### Additional Context

Even when i exist the app and try to use auto fill it asks for my master password everytime.

### Operating System

Android

### Operating System Version

Android 12

### Device

Poco M3 4/64 GB

### Build Version

Version: 2023.3.1 (6079)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by hkaancaliskan** [comment]
still relevant with 2023.3.2 on A52 Android 13
@mp-bw
