### ISSUE TITLE
[Bug] Bitwarden for iOS logs out of my account before "Vault timeout" expires

### ISSUE THREAD

**Issue by MahdiNazemi** [bitwarden/mobile#2444]
### Steps To Reproduce

1. Set "Vault timeout" to "4 hours"
2. Set "Vault timeout action" to "Log out"
3. Set "Unlock with Face ID" to "On"
4. Quit Bitwarden from the App Switcher
5. Reopen Bitwarden

### Expected Result

Bitwarden is expected to unlock my vault with Face ID.

### Actual Result

Sometimes Bitwarden asks me to enter my master password and TOTP key.

### Operating System

iOS

### Operating System Version

16.3.1

### Device

iPhone XS

### Build Version

2023.3.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by JensSpanier** [comment]
Also choosing „never“ at Vault timeout gets reset to 15 minutes all the time.

**Comment by vcadieux** [comment]
Same here, the “never” for vault expiration options does save. Will reset back to 15 minutes as soon as you leave the setting page

**Comment by SergeantConfused** [comment]
Hi @MahdiNazemi,

Thank you for your report. Once you remove the Bitwarden Client from the App Switcher, you essentially quit the application completely; Similarly to quitting the desktop client or the browser extension (https://bitwarden.com/help/vault-timeout/), this would cause the Vault Timeout Action to be performed, regardless if the Vault Timeout had actually elapsed, and this is the intended behaviour.

With regard to @JensSpanier and @vcadieux, we are aware of this and are working to address it; More details in the links below.
https://github.com/bitwarden/mobile/issues/2426
https://github.com/bitwarden/mobile/issues/2441

If anyone has any further questions, please feel free to get in touch (https://bitwarden.com/help/) with us via the Contact form.

We use GitHub issues as a place to track bugs and other development related issues; This issue will be now closed.


Thank you,

**Comment by MahdiNazemi** [comment]
@SergeantConfused, thank you for the explanation. It would be nice to add an option to let the user choose whether they like to log out of their vault on quit or not.

Keeping the user logged in even after closing the app from the app switcher (and before the timeout expiration) would be consistent with LastPass and, therefore, more familiar for users planning to switch.

**Comment by MahdiNazemi** [comment]
> ... Similarly to quitting the desktop client or the browser extension (https://bitwarden.com/help/vault-timeout/), this would cause the Vault Timeout Action to be performed, regardless if the Vault Timeout had actually elapsed, and this is the intended behaviour.

@SergeantConfused, I just experienced the opposite of what you describe as the intended behavior. After closing the app in the App Switcher, I could unlock my vault with Face ID. That is why I mentioned in the original bug report that I _sometimes_ get the login screen.

Please follow the reproduction steps and compare your experience with what you describe as the intended behavior. I would happily share a screen recording if reproducing my setup is difficult for you.
