### ISSUE TITLE
The ellipsis (3 dots) button next to each vault item within the search results does not work and does nothing.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#2446]
### Steps To Reproduce

1. Open your Bitwarden mobile (Android) client.
2. Navigate to the (Vaults) menu and search for a vault item.
3. Tap on the ellipsis next to one of the vault items from the results.

### Expected Result

A menu allowing you to view, edit, copy the password and perform other functions, should appear.

### Actual Result

The phone vibrates, but no menu is shown.

### Screenshots or Videos

N/A.

### Additional Context

This is working as expected in version 2023.2.0 (5944) on Android 13 (different phone).

### Operating System

Android

### Operating System Version

Android 12.

### Device

Samsung Note10+.

### Build Version

2023.3.1 (6079).

### Beta

- [ ] Using a pre-release version of the application.

**Comment by BabyOilJohnson** [comment]
Same issue here too, can't edit or copy because of this bug.

**Comment by thetrashcanhero** [comment]
Came here to report this same issue. 
OS: GrapheneOS
Bitwarden Version: 2023.3.1

**Comment by vvolkgang** [comment]
Thanks for the reports! Are you able to edit by tapping an item and then using the `Edit` button at the top?

**Comment by thetrashcanhero** [comment]
> Thanks for the reports! Are you able to edit by tapping an item and then using the `Edit` button?

For myself I can edit an item by logging into the app, tapping an item and tapping edit. No problems there.
The  issue with the 3 dots is, you go to a website, tap username or password field, tap autofill with bitwarden and from the item tapping the 3 dots does nothing, I just downloaded version 2023.3.2 today and the problem still exists.

**Comment by az3tmd** [comment]
I confirm that it behaves the same as above with the last version.  
Huawei P30 Lite with Android 10, romanian language.

**Comment by fastuser** [comment]
Still broken.

**Comment by az3tmd** [comment]
Exact!  Bitwarden are you doing something about this?

**Comment by weirdcrap** [comment]
This is definitely not fixed.

**Comment by fedemkr** [comment]
Hi everyone, thanks for the reports and just to clarify a fix (#2460) has been done for this issue and will be part of the next release of the application.

**Comment by az3tmd** [comment]
> tp0

When?
