### ISSUE TITLE
[Bug] Bitwarden asks for master password on Safari auto-fill even if logged in to vault

### ISSUE THREAD

**Issue by MahdiNazemi** [bitwarden/mobile#2467]
### Steps To Reproduce

1. Remove Bitwarden if it is already installed on your device
2. Install Bitwarden
3. Select Bitwarden for auto-fill in iOS Settings
4. Log in to your vault
5. Use Safari to navigate to a website where you have a Bitwarden entry for
6. Auto-fill with Bitwarden

### Expected Result

Bitwarden is expected to auto-fill the password since the user is already logged in to their vault.

### Actual Result

Bitwarden requires the user to log in.

### Screenshots or Videos

![IMG_3747](https://user-images.githubusercontent.com/11276349/230785439-cb5790d0-e626-4a3a-92ba-5981ba62fc26.PNG)
![IMG_3748](https://user-images.githubusercontent.com/11276349/230785444-cc807ea1-7fe6-49dd-94b3-1be6217c4ce9.PNG)

### Operating System

iOS

### Operating System Version

16.4.1

### Device

iPhone XS

### Build Version

2023.3.2

### Beta

- [ ] Using a pre-release version of the application.

Update 1
---------

After logging in and out a few times, I got the following message, which is reasonable. I am still confused about why I was asked to log in to my vault during auto-fill, as shown in the original screenshots.

![IMG_3751](https://user-images.githubusercontent.com/11276349/230786090-9f1c9972-8573-4d55-ae03-8a6abacf0c6a.PNG)

**Comment by SergeantConfused** [comment]
Hi @MahdiNazemi,

Thank you for your report. Your issue appears to be describing the intended behaviour of the software; The Auto-Fill function on iOS operates somewhat separately from the main iOS client and that is why you'd need to unlock it when performing Auto-Fill, even if the main client is unlocked. You can also see this behaviour if you Auto-Fill the email address and then attempt to Auto-Fill the password as a separation action (on a different webpage, for example) a few seconds later.

We use GitHub issues as a place to track bugs and other development related issues; This issue will now be closed. 


Thank you again,
