### ISSUE TITLE
iOS app crashing on startup

### ISSUE THREAD

**Issue by allddd** [bitwarden/mobile#2478]
### Steps To Reproduce

1. Launch the app and open any login/secure note.

2. Close the app fully by swiping it up without closing the login/secure note window first.

3. Wait a little, as you would if you just wanted to copy something.
The longer it stays closed, the more likely it is to crash on startup.

4. Launch the app.

### Expected Result

The app opens without any problems and displays either the last opened login/secure note or the main screen.

### Actual Result

The app is launched and displays the last opened item for a split second.
After that, regardless of whether you press something or not, the app crashes completely.

You will then have to launch it again, it lands on the main screen and works fine.

### Additional Context

This is not related to the current app/iOS version, but is a long-standing problem.
I have experienced it on two different phones (Iphone X and 14 Pro), both iOS 15 and 16, and with all previous versions of the app since I started using Bitwarden (about a year ago).

When you try to recreate it, you should leave it closed for a while. The longer it stays closed, the more likely it is to crash on startup.

### Operating System

iOS

### Operating System Version

16.4.1

### Device

Iphone 14 Pro

### Build Version

2023.3.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by allddd** [comment]
@SergeantConfused 

> 1. What is your Vault Timeout set to?

Immediately

> 2. What is your Vault Timeout Action set to?

Lock

> 3. How do you typically unlock the application? Master password, PIN, biometrics?

Biometrics

> 4. Does your phone lock during the waiting period? i.e. after you swipe the application up and before you open it anew?

I would say yes, but not with 100% certainty.
It usually gets locked because few hours/days can pass between closing the application and opening it again.

> 5. Into how many Bitwarden accounts is your client logged into?

Only 1

> 6. To what language(s) are your phone interface and Bitwarden interface set to?

Both are in english

**Comment by Greenderella** [comment]
Hi there,

We have attempted to reproduce your issue and were unable to do so. We use GitHub issues as a place to track bugs and other development related issues.

Will you first try uninstalling the application, resetting your device (Power Off/On) and re-installing? If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by allddd** [comment]
Hi,
well that is very strange.

It still happens constantly and rebooting/reinstalling certainly won't help a problem that's been going on for over a year.
The phone has been rebooted multiple times and the app has also been reinstalled multiple times as the issue has occurred on multiple devices.

I also reinstalled it already as the bug (2023.3.0) broke the app recently.

I will gladly provide a video of it if you reopen the issue, this problem is very irritating.

**Comment by SergeantConfused** [comment]
Hi @allddd,

Thank you for following up on this. I took another look at this and was able to finally reproduce it on iOS 16.6.1 with Bitwarden 2023.8.0; I am going to open this ticket and raise this matter internally; The reproduction steps that I am using are detailed below.

1. Create a new Bitwarden account.
2. Create a single Login-type vault items and call it (Test) and leave it empty.
3. Log into this Bitwarden account via the iOS client.
4. Set the (Vault Timeout) to (Immediately).
5. Set the (Vault Timeout Action) to (Lock).
6. Activate (Unlock with Touch ID).
7. Close Bitwarden by swiping it up from the App Switcher.
8. Open Bitwarden anew and tap on Logins > Test.
9. Press on the Home button.
10. Open the Task Switcher and swipe Bitwarden up to close it.
11. Attempt to open Bitwarden again; At this point, it crashes.

**Comment by allddd** [comment]
Hi @SergeantConfused 

Thanks for reopening. The problem still persists on several devices I have used recently, the steps above describe it well.
One small note is that in my case it does not matter what type of vault item it is, it crashes anyway.

**Comment by jcbvm** [comment]
I’m encountering the same issue, it most often happens when you have avail item open. Then switch to another app and return, the app will crash.

**Comment by larrymcj** [comment]
Same thing here. This happens when using any one of three Bitwarden accounts. Most often, Bitwarden crashes about one second after I open it. Reopening it right away usually allows it to stay open.

**Comment by kohei-noda-qcrg** [comment]
I have the same issue on iPad Air 3 with iPad OS 16.6.
2023.8.0 (4566) is the version of BitWarden.

Furthermore, in my case, the app crashes on any card and identity.

**Comment by Nevamex** [comment]
I have the same problem with my iPhone 12 Mini running iOS 16.6. Switching to another app while leaving a vault item open in the Bitwarden app makes Bitwarden crash on reopen.

**Comment by PixelEnvision** [comment]
Same crash here, happening for a while even with the latest update.

My steps to reproduce (every time)

1. Open Bitwarden with FaceID
2. Open any vault item
3. Swipe up and send Bitwarden to the background
4. Re-open Bitwarden with FaceID =< CRASH

Device is iPhone 13 Pro Max with iOS 16.x

Note: if the Bitwarden is on the main UI, it doesn't crash when re-opened.

**Comment by zahtec** [comment]
Experiencing precisely the same issue.

1. Unlock Bitwarden with FaceID
2. Edit/open any vault item
3. Navigate away from Bitwarden and allow the vault timeout to auto-lock the vault.
4. Re-open Bitwarden with FaceID; immediate crash.

**Comment by jcbvm** [comment]
I’m also encountering the issue when not using Face ID, or when setting the time out to 1 minute or above. So it does not seem to be related with the settings.

**Comment by gewdvibes** [comment]
I've been having this same issue for quite a while(at least a few months).

- happened on iOS 16 and now iOS 17 still happening 
- unlocked with biometrics (faceid)
- timeout set to 5 mins
- timeout action set to lock

1. Open Bitwarden 
2. Do anything(seems like it just has to be open)
3. Wait for it to lock
4. Come back after some time
5. Unlock app with faceid
6. Crashes immediately upon unlock

It doesn't matter whether I have a vault item open or not it still crashes when I come back to it every time. The locking doesn't seem to be the problem as I tried setting it to immediate lock and when I do that and try different scenarios it never crashes if I just leave the app and come back a few seconds later to unlock it. But if I wait a normal amount of time like maybe an hour or two, when I come back it will crash every time

**Comment by orchunchun** [comment]
+1，i have the same issue on iOS

But it seems Android is not affected.

**Comment by gewdvibes** [comment]
I saw a fix got merged. Has this update gone out yet? I'm still getting the same crashing. Seems a little less frequent but that could just be placebo. It's definitely still happening though

**Comment by PixelEnvision** [comment]
Just tried, and it's still happening for me too...

**Comment by djsmith85** [comment]
The changes made on the [linked Pull Request](https://github.com/bitwarden/mobile/pull/2813) have been merged and will be included in the upcoming `2023.10`-release.

**Comment by gewdvibes** [comment]
FYI newest update is still crashing with same behavior. iOS 17.1, iPhone 15 Pro

**Comment by hazardousthingy** [comment]
> FYI newest update is still crashing with same behavior. iOS 17.1, iPhone 15 Pro

I can confirm, still crashing on iOS 17.1, iPhone 13 Pro.

**Comment by Greenderella** [comment]
Please try uninstalling the application first, resetting your device (Power Off/On) and re-installing. If the issue persists, please contact support using the form available on the right side of our Help Center: https://bitwarden.com/help/

**Comment by Clauber** [comment]
I have the same issue, but it actually breaks when I try to save something

**Comment by boydthomson** [comment]
Experiencing same with iOS 17.2.1 on iPhone 13.  Shame as I finally cancelled LastPass for Bitwarden.

**Comment by SergeantConfused** [comment]
Hello @gewdvibes, @hazardousthingy, @Clauber, and @boydthomson,

1. Could you please specify the exact versions of iOS and Bitwarden that you currently are using and are experiencing this with?
2. Could you please detail the [KDF Settings](https://bitwarden.com/help/kdf-algorithms/) that you have set for your accounts?
3. Are your iOS clients logged into [more than one](https://bitwarden.com/help/account-switching/) Bitwarden account?
4. Could you please share clear and detailed reproduction steps?


Thank you in advance,

**Comment by larrymcj** [comment]
As the OP, I’ll add my comments here also, as Bitwarden is again crashing occasionally at startup. The frequency is less now, probably one in 10-15 times I open it.

iOS version: 17.2.1
iPhone 15 Pro Max: (though this also occurred on a previous iPhone 14 Pro.
Bitwarden version: 12.0 (5688)
Number of accounts logged into: 3
KDF Settings: PBKDF2 for all three accounts. Two are set for 600,000 and one is set to 100,000
Detailed steps to replicate: tap the Bitwarden home screen icon, it flashes once, then crashes.

Larry McJunkin
