### ISSUE TITLE
[Feature Request] Let the app autofill form's details

### ISSUE THREAD

**Issue by raghavdua1995** [bitwarden/mobile#249]
User should be able to use bitwarden app for autofilling details other than username and password like name, dob, age, etc.
This is a feature which is already there in lastpass and can be implemented not only in mobile apps but also in web browser extensions.

**Comment by BigNickBurgess** [comment]
This is actually already there.  Add a new item and select identity.  On browsers you then get the 'Identity' options shown in the tab section to autofill.

As an addendum to this though can the different types of saved info be separated out from the main Vault in some way?

So we'd then have the same headings as under the new item options.
Login
Card
Identity
Secure Note 

LastPass currently does this via a hamburger menu on their Android App.  Cant remember how their browser extension handles it.  I dont like having a separate folder called form fills (one i made) alongside all my logins.

**Comment by raghavdua1995** [comment]
Yup you are right, it is there. However identities should be separated from passwords and username directory. It would be nice to have a seperate section to manage identities in the tools tab of the app.

**Comment by kspearrin** [comment]
Browser and mobile (Android 8.0+) both have the ability to autofill identity information.

**Comment by djbrown** [comment]
as stated in the [documentation](https://bitwarden.com/help/article/auto-fill-card-id/):

> Currently, Autofill for Cards & Identities is **only available for Browser Extensions**. Mobile platforms including Android and iOS do not currently support this type of auto-fill function.

@kspearrin has there been a regression? why ist this request marked as fixed? os there a new issue?
