### ISSUE TITLE
Android: support screen ration 18.5 by 9

### ISSUE THREAD

**Issue by ChesterCloud** [bitwarden/mobile#250]
I would like to mention that new version of bitwarden app for android doesn't support screen ration 18.5 by 9 which is used on Samsung Galaxy S8 display. I know that Samsung Experience 8.1 offers to make app work in full screen. But in Settings - Display - Full screen apps under bitwarden app written "This app may not work properly in full screen" which mean this app is not optimized to new screen ration standards. For example lastpass client is optimized to work in 18.5 by 9 screen ration and under the same settings menu under lastpass client written that "This app is optimized to run in full screen". Please fix this for your client.

And some recommendation about design:
1) Please make "+" icon in the circle a little bit thinner.
2) Please make three dot buttons next to password accounts a little bit smaller and thinner also.
3) if it possible underline active menu icons on the bottom with the blue color.

**Comment by Livven** [comment]
FWIW the app seems to run and look perfectly fine even in 18.5:9 mode. Seems to be purely a manifest/declaration issue, not sure what mechanism Samsung uses to determine aspect ratio support.

**Comment by kspearrin** [comment]
This should be fixed in the latest play store beta. Can you try and confirm?
