### ISSUE TITLE
Scrolling is laggy when Bitwarden is enabled in accessibility settings

### ISSUE THREAD

**Issue by gorditogr** [bitwarden/mobile#252]
I have two phones, Oneplus 3 and Xiaomi Mi A1, both on official Oreo releases. Behavior is exactly the same on both phones.

When i enable Bitwarden in accessibility settings scrolling gets laggy for many apps. More obviously on default launchers swiping up to open app drawers. Other apps enabled in accessibility settings dont give me issues

Here's a video to demonstrate the issue

https://www.youtube.com/watch?v=Ve3ByrIU3Ks

**Comment by kspearrin** [comment]
Can you try another launcher app like Nova maybe and see if it changes? Also there are some other accessibility options available under Settings -> Options. Try some of those to see if anything changes.

**Comment by gorditogr** [comment]
Nova works fine

**Comment by gorditogr** [comment]
I tried many options, the result is the same when enabled in accessibility, opening app drawer on stock launcher is laggy on both phones.
Nova seems to be working fine, i didint really check any other apps

**Comment by jeroen7s** [comment]
@gorditogr did you try the "persistent notification" option instead of the default "always scan"? that should prevent this issue

**Comment by gorditogr** [comment]
No, it doesnt.

**Comment by gorditogr** [comment]
@kspearrin 
Lastpass does the exact same lag but only when i enable the "Search for password fields in other apps" options.

**Comment by kspearrin** [comment]
It seems a lot of people that have this issue are on oneplus devices.

@eskela123 can you try nova launcher and see if that helps in your situation as well? I think it's the default oneplus launcher app that is conflicting.

**Comment by eskela123** [comment]
I actually use Pixel Launcher, Resurrection Remix offers 2 or 3 launchers (not sure which one I installed manually). I did my tests:
Pixel Launcher - laggy
Google Now launcher - laggy

Trebuchet launcher (so that's default OnePlus launcher, or more accurately Cyanogen OS launcher or ex LineageOS launcher, but I might be confused) - not laggy
Nova Launcher - freshly installed, not laggy

**Comment by kspearrin** [comment]
@eskela123 Would you be able to work with me in our live chatroom to try and debug these other launchers more? Feel free to ping me at https://gitter.im/bitwarden/Lobby

**Comment by kspearrin** [comment]
Resolved in latest beta on Google Play thanks to @eskela123
