### ISSUE TITLE
The Options menu under Settings is inaccessible when the application language is set to Turkish.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#2534]
### Steps To Reproduce

1. Open your Bitwarden Android client.
2. Navigate to Settings > Options and change the UI language to Turkish.
3. Close the Bitwarden Android client.
4. Open the Bitwarden Android client.
5. Attempt to navigate to Settings > Options.

### Expected Result

To be able to open the Options menu.

### Actual Result

Tapping the Options button under the Settings menu does not open the Options menu, but the button responds graphically to indicate that it has been pressed.

### Screenshots or Videos

Internal.

### Additional Context

N/A.

### Operating System

Android

### Operating System Version

12

### Device

Samsung Note10+

### Build Version

2023.4.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Thanks for the report @SergeantConfused

If anybody else wishes to add any further information/screenshots/recordings or maybe found out another language affected by this issue, please feel free to add the information here - Bitwarden's engineering team will be happy to review it.
