### ISSUE TITLE
Strange margins for the tools on ipad

### ISSUE THREAD

**Issue by Jacalz** [bitwarden/mobile#256]
The app on iPad has very strange margins in the toolbar:
![11_A27_E46-644_F-44_B2-83_FD-40_AE2_D2726_AD.png](https://s14.postimg.org/5cof79lg1/11_A27_E46-644_F-44_B2-83_FD-40_AE2_D2726_AD.png)
The icons at the bottom are very close to the bottom of the screen...

**Comment by kspearrin** [comment]
Thanks. What iPad model is this?

**Comment by Jacalz** [comment]
It is on an iPad Air 2

**Comment by kspearrin** [comment]
Thanks. I will need to test on a simulator.

**Comment by Jacalz** [comment]
Great, just tell me if you need anythig tested or something 🙂

**Comment by kspearrin** [comment]
Fixed in next release with https://github.com/bitwarden/mobile/commit/5a3d86a12a216383c5b0326119c18babfab102f2
