### ISSUE TITLE
Sends not syncing automatically on mobile

### ISSUE THREAD

**Issue by quexten** [bitwarden/mobile#2571]
### Steps To Reproduce

1. Sign into Bitwarden on a mobile device and go to the Sends tab
2. Sign into Bitwarden on another device and create a send

### Expected Result

The send should appear after a few seconds.

### Actual Result

The send only appears when manually doing a full sync of the vault.

### Additional Context

As far as I can tell this is due to 
```
SyncSendCreate = 12,
SyncSendUpdate = 13,
SyncSendDelete = 14,
```

not being implemented here: https://github.com/bitwarden/mobile/blob/98705e443f321411dd3b7c8d54581fe4462cc3c5/src/App/Services/PushNotificationListenerService.cs#L76-L162

### Operating System

Android, iOS

### Device

iPad Pro 2020, Xiaomi Mi9T-Pro

### Build Version

2023.5.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @quexten ,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
