### ISSUE TITLE
"We were unable to process your request. Please try again or contact us. " on Self-Host

### ISSUE THREAD

**Issue by ivanskodje** [bitwarden/mobile#2591]
### Steps To Reproduce

1. Start Bitwarden
2. Select "Self Hosted"
3. Enter secure https url to self-host
4. Enter valid email address
5. Continue
6. Message appears: "We were unable to process your request. Please try again or contact us. "

Error message appears whenever we have a **valid** email. If i enter a nonsense email, it does not pop the error.
Even if it says they were unable to process the request, it still continues and allows me to try and login. 
Login fails no matter what at this point.

Please let me know if there is any hidden debug features I can turn on to help debug and find solution to this.

### Expected Result

No error message.

### Actual Result

Error message.

### Additional Context

Hosting Vaultwarden via CapRover on a private server. Ports and open (80, 443), and there are no firewall settings interfering. Web version works like a charm, so does browser extensions. 

### Operating System

Android

### Operating System Version

Android 12, One UI 4.1

### Device

Samsung Galaxy Note 10+

### Build Version

SP1A.210812.016.N975FXXS8HWC3

### Beta

- [ ] Using a pre-release version of the application.

**Comment by MarsCandyBars** [comment]
Hi there,

Thank you for the report but this appears to be hosted with Vaultwarden which is a separate application from Bitwarden that we do not provide support for.

You can find the contact information for Vaultwarden here: https://github.com/dani-garcia/vaultwarden#get-in-touch

**Comment by ivanskodje** [comment]
I am sorry, I was not aware that self-host option available in the mobile application was not part of the mobile application.
