### ISSUE TITLE
No icons inside android app

### ISSUE THREAD

**Issue by mikegwald** [bitwarden/mobile#2598]
### Steps To Reproduce

Open app look at logins .
No icons are shown just blank space to the left of each login

### Expected Result

Show basic icon

### Actual Result

No icons shown at all

### Additional Context

No icons inside app 

### Operating System

Android

### Operating System Version

13 STABLE  and 14 BETA 3.1 

### Device

Pixel 7 

### Build Version

2023.5.0 6330

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Tipoff4317** [comment]
https://www.reddit.com/r/Bitwarden/comments/14qnw6n/webapp_icons_disappeared/

Seems only some people are experiencing this problem.  Some suggested it started when they switch to using Argon2id.

**Comment by mikegwald** [comment]
I never switched to anything I am coming in as a brand new account with default settings and have it installed on four completely different Android devices and none of them have icons . The only thing that shows icons is the chrome web extension.

**Comment by stephenglass** [comment]
It's not just Android devices. I'm on iOS and app icons have never appeared for me. I didn't even know app icons was a feature outside of web vault.

**Comment by mikegwald** [comment]
Yeah it's a real shame this basic feature is completely broken and not a top priority for the developers. It has been over a month and not really any official update or real acknowledgement from bitwarden. I can not take this app seriously any more and has left a very bad impression on me . I have decided to delete my vault and take me business over to 1password. Best of luck to you all but I have lost confidence in the bitwarden brand over this .

**Comment by lunax28** [comment]
Same for me but on iOS (16.5.1). I can't recall precisely since when, but for a month or so on the app the icons have disappeared. They were helpful as you could spot things faster / easier. It was a nice touch. Tried uninstalling the app with no luck. Hope they fix it soon.
On the website everything looks fine.

**Comment by don-dolarson** [comment]
Same here, no icons. Fresh start. Android 13, LineageOS. Bitwarden 23.5.0 from F-Droid. It works on my other phone however, running Android 8.1 OxygenOS. Same version of Bitwarden but downloaded from Play Store.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Banyal28** [comment]
it takes too long and it was reported several months ago but still we have the same problem. very disappointed 😠

https://github.com/bitwarden/clients/issues/5536

**Comment by don-dolarson** [comment]
Still not working in the latest release 23.7.0

**Comment by mikegwald** [comment]
I have also tried  23.7.0 on two devices one android and one iOS and confirm still does not work .

**Comment by testtestar** [comment]
Same here and that it has been like this for quite some time now, almost 2 months IOS 16 not beta with last Bitwarden official update

**Comment by Erd89** [comment]
Same on ios

**Comment by lunax28** [comment]
After the latest update something's changed server side and now I see them! Thank you
