### ISSUE TITLE
Yubikey login not working on pixel fold

### ISSUE THREAD

**Issue by 6dDODn7lbeYglYfY7bP5NCJqT3OKiONr7vJoNZm** [bitwarden/mobile#2600]
### Steps To Reproduce

1. Add yubikeys using the web interface on chrome macos. I added both a Yubikey ~~NEO~~5 NFC and Yubikey 4C
2. try to login to bitwarden on pixel fold using Yubikey as 2FA. tried:
    * 5 NFC over USB
    * 5 NFC over NFC
    * 4C over USB

### Expected Result

Successful login

### Actual Result

Generic error message and login failure

### Operating System

Android

### Operating System Version

13

### Device

Pixel Fold

### Build Version

2023.5.0 (6330)

### Beta

- [ ] Using a pre-release version of the application.

edit: it's a Yubikey 5 NFC, not a NEO

**Comment by Greenderella** [comment]
Hello,

Please try reproducing the issue with the beta version of the native app. The beta program can be joined, and the app downloaded from here: https://community.bitwarden.com/t/about-the-beta-program/39185

Recent updates have been made in the beta builds, so it would be helpful to check if the issue still occurs with the latest version.

Thank you for your cooperation, and looking forward to the feedback!
