### ISSUE TITLE
Specific web page hangs when Bitwarden accessability service is enabled on Chrome.

### ISSUE THREAD

**Issue by Hampster82** [bitwarden/mobile#262]
Basically, as long as the Bitwarden accessability service is enabled on Android, Chrome will hang when I open this specific web page. There are no password fields there and changing the scan setting doesn't have any effect. Lastpass had what I assume to be the same problem last I used it, at least it behaves exactly the same. I've only tested Bitwarden on OnePlus 3T, but the same Lastpass problem was also tested on Nexus 5X in addition to OP3T.

The web page in question is this.
http://www.rpgamers.net/radio/request

I haven't seen the issue in any other page. Does the page do something unusual, is it coded badly or something? Any ideas? In case it's something that's out of your control, maybe you might have an idea how to fix it on their end if it is something unusual they are doing, I could report it to them as well.

**Comment by kspearrin** [comment]
I think it's just the nature of this page containing a huge HTML input list. The accessibility service isn't very performant at parsing pages so when you give it a huge page to parse it hangs up.

**Comment by Hampster82** [comment]
Ah, that's unfortunate. I'm curious though, if my scan setting is to 'scan when password field is focused', shouldn't that mean that it won't parse the page? Or am I mixing scanning and parsing together when they are not the same?

**Comment by kspearrin** [comment]
I would think a "no scan" option would make things better, but I am not sure what Android still may be doing under the hood to build a accessibility node tree that would be representative of that webpage. The tree would be quite large due to the amount of fields presented on that page.

**Comment by Hampster82** [comment]
Alrighty. I'm closing this since it's not a bug, thanks for taking a look.
