### ISSUE TITLE
Brave Browser (Android) crashes on search bars when autofill is enabled.

### ISSUE THREAD

**Issue by anxiouslelimo** [bitwarden/mobile#2627]
### Steps To Reproduce

1. Go to 'www.google.com/www.search.brave.com'
2. Click on 'turn search settings history off on google/navigate to opened website on brave'
3. Go back to  'search page'
4. Click on 'search bar'

### Expected Result

Should be able to search

### Actual Result

Browser crashes. 

### Additional Context

https://github.com/brave/brave-browser/issues/31699#issuecomment-1641634437

### Operating System

Android

### Operating System Version

11

### Device

Galaxy M30s

### Build Version

2023.7.0 (6781)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Adedamola-Aina** [comment]
Hi @anxiouslelimo 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration, also you never mentioned how bitwarden is affected or could be the reason this is happening. 

We use GitHub issues as a place to track bugs and other development related issues.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/).

The issue here will be closed.

Thanks!

**Comment by anxiouslelimo** [comment]
Bitwarden autofill is causing the issue for me. Turned autofill and inline fill off. Brave does not crash. 

https://community.brave.com/t/brave-crashes-when-search-bar-is-clicked/463700
https://community.brave.com/t/brave-crashes-when-search-bar-is-clicked-round-two/484607/16
https://community.brave.com/t/brave-crash-after-when-trying-new-google-search/462608/22

**Comment by amit-katyal** [comment]
> Hi @anxiouslelimo 
> 
> I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration, also you never mentioned how bitwarden is affected or could be the reason this is happening. 
> 
> We use GitHub issues as a place to track bugs and other development related issues.
> 
> Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/).
> 
> The issue here will be closed.
> 
> Thanks!

Even I can vouch for this, I faced similar crash in brave browser when performing search using Duckduckgo or Bing search engine. Turning off bitwarden autofill fixed it for me.

**Comment by idkw** [comment]
I have bien having the same issue for months. Can this be looked into ?
