### ISSUE TITLE
CPU usage is @ 8% in the background [auto fill]

### ISSUE THREAD

**Issue by xs1vr** [bitwarden/mobile#2631]
### Steps To Reproduce

1. Go to Bitwarden
2. Enable all of the auto fill options (i didn't test which one specifically causes this 'issue')
3. Open termux and write (if rooted) `su -c top`
4. Move the `top` table to the right with > arrow, once you're there wait a few seconds for everything to normalize, once it normalizes start 'spamming' the < > arrows so the manifest changes - you'll notice Bitwarden is using 8-9% of the CPU.

### Expected Result

Battery is not used as much

### Actual Result

The battery usage is the same as if you had running `top` shell command all the time in the background which is not good.

### Operating System

Android

### Operating System Version

13

### Device

Poco X3 NFC

### Build Version

version 2023.7.0  com.x8bit.bitwarden versionCode 6781  targetSdk 33 minSdk 21  Installed: Jul 19, 2023; 21:08

### Beta

- [ ] Using a pre-release version of the application.

**Comment by mpbw2** [comment]
Hi @xs1vr , in the app's autofill settings can you disable the `Use Accessibility` option and see if the high CPU usage continues?

**Comment by xs1vr** [comment]
> Hi @xs1vr , in the app's autofill settings can you disable the `Use Accessibility` option and see if the high CPU usage continues?

Hello,

yes - the issue is no longer persistent when `Use accessibility` is disabled. sorry for not verifying this earlier by myself.

**Comment by mpbw2** [comment]
@xs1vr No worries, appreciate the confirmation.  This is fairly typical when using Accessibility services as it requires constant polling and parsing of the screen contents.  We're routinely making improvements to our standard Autofill implementation in the hopes that one day users won't need to augment it with the use of Accessibility services anymore.  Have you tried using recent versions of the app without enabling `Use Accessibility`?

**Comment by xs1vr** [comment]
> @xs1vr No worries, appreciate the confirmation. This is fairly typical when using Accessibility services as it requires constant polling and parsing of the screen contents. We're routinely making improvements to our standard Autofill implementation in the hopes that one day users won't need to augment it with the use of Accessibility services anymore. Have you tried using recent versions of the app without enabling `Use Accessibility`?

I've always been using `Use Accessibility` and I understand why it uses a bit more battery. What have I noticed though is that phones without gms (google services) do much better with just 'Use draw-over` as the option looks a bit better there / more reliable per se?

**Comment by mpbw2** [comment]
`Use draw-over` isn't used when `Use Accessibility` is enabled.  Are you perhaps referring to the Autofill popup when inline autofill is disabled or unavailable?  It's visibly similar to the draw-over popup and tracks more reliably as it's part of the standard Autofill.  (Hint: If the logo shield in the popup is blue, it's using standard Autofill.  If the shield is black and white, it's using the accessibility draw-over)

**Comment by xs1vr** [comment]
> `Use draw-over` isn't used when `Use Accessibility` is disabled. Are you perhaps referring to the Autofill popup when inline autofill is disabled or unavailable? It's visibly similar to the draw-over popup and tracks more reliably as it's part of the standard Autofill. (Hint: If the logo shield in the popup is blue, it's using standard Autofill. If the shield is black and white, it's using the accessibility draw-over)
> 
> Edit: meant to say "when `Use Accessibility` is _disabled_"

You're right, it's disabled. 
I won't use `Use accessibility` anymore, I'll stick to the default auto fill that appears in the Gboard, thanks!
