### ISSUE TITLE
Search on iOS app does not return results like the browser extension does

### ISSUE THREAD

**Issue by imthenachoman** [bitwarden/mobile#2644]
### Steps To Reproduce

1. Create a new credit card item with the name `cc - blah - something`
2. In BW web or browser extension, search for `cc something` and you'll see the item
3. In BW iOS, search for `cc s` and it'll tell you there are no matching items

### Expected Result

I would expect the search results between browser extension and iOS app to match.

### Actual Result

On the iOS app, as soon as I type `cc s`, it shows no results.

### Screenshots or Videos

Screenshot of search result on iOS:

![IMG_3749](https://github.com/bitwarden/mobile/assets/83817/2acbff35-4728-499c-a767-0fe253e18a3c)

Screenshot of search result on web:

![image](https://github.com/bitwarden/mobile/assets/83817/60952bd0-86bc-48e1-b9bb-90ac5ee115b3)

### Additional Context

I have a login where the name is something like `cc - something`.

In my browser extension, if I enter `cc something` or even `cc some` it will show this item.

But on the iOS app, as soon as I type `cc s`, it shows no results.

If I search for `cc` or `something` it shows the results, but it also shows a slew of other things that aren’t what I am looking for.

I would expect the search results between browser extension and iOS app to match.

### Operating System

iOS

### Operating System Version

16.5.1

### Device

iPhone 13 Pro

### Build Version

2023.7.0 (3881)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by imthenachoman** [comment]
Are you telling me someone actually made a decision to have a different search experience on mobile vs. web? Does BitWarden not have a UI/UX engineer because this is an absolute absurd decision. Everyone knows that you want a consistent experience across mediums/platforms. I'll post to the forums.
