### ISSUE TITLE
Search Vault - Android

### ISSUE THREAD

**Issue by rtloeffler** [bitwarden/mobile#265]
- Device: Samsung Galaxy S8
- Android: 7.0
- App V: 1.14.1

Issue: Clicking on SEARCH icon produces a blank screen and a spinning "loading" icon that never finishes loading. 

Expected: Click on Search and be able to type my search keyword.

**Comment by kspearrin** [comment]
Hm. Sounds like there may be some item that breaks the listing of all items. Are you using folders? Can you click through each folder and see if there is one that does the same thing?

**Comment by rtloeffler** [comment]
Good call, I had a blank item in a NON folder (was imported from SafeinCloud) and that seemed to break the search, as soon as i deleted the item it started working again.

**Comment by kspearrin** [comment]
Any way to reproduce it so that we can do a fix? What type of item was it? Did it have a name field value at least?

**Comment by rtloeffler** [comment]
The only way to reproduce is for me to reimport the data. The Name field is blank when reviewing the item. See attachments (screenshots from web version, however android version has the same results)
![screen shot 2018-01-25 at 11 08 12 am](https://user-images.githubusercontent.com/8787209/35407285-464857fa-01c0-11e8-9a7d-785a877c81f6.png)
![screen shot 2018-01-25 at 11 08 09 am](https://user-images.githubusercontent.com/8787209/35407286-4661f8cc-01c0-11e8-9c7c-a1b5cc02e231.png)

**Comment by kspearrin** [comment]
Do you know the row it's coming from in your SIC import? The importer shouldn't allow a completely blank item like that.

**Comment by rtloeffler** [comment]
I did locate the one in SIC that was empty: Here is the line
`<card symbol="key" color="gray" template="false" star="false" id="1456838854" title="" time_stamp="1516910384500"><field name="Login" type="login"></field><field name="Password" type="password"></field></card>`

**Comment by kspearrin** [comment]
Thanks!

**Comment by kspearrin** [comment]
Fixed for next release.
