### ISSUE TITLE
Autofill on Samsung Internet Browser stopped working on all devices

### ISSUE THREAD

**Issue by SgtChrischi** [bitwarden/mobile#2658]
### Steps To Reproduce

1. Install Samsung Internet Browser (Beta).
2. Install Bitwarden and set it up
3. Visit any website and try to login.

### Expected Result

The autofill works and shows bitwarden content.

### Actual Result

The autofill does not work and does not show bitwarden content.

### Additional Context

Since a few days the Bitwarden Autofill stopped working with the Samsung Internet Browser. Both with the normal version and with the beta version. It always worked without any problems and now it doesn't work on any of the mentioned devices anymore. It still works with all other apps and browsers, only "Samsung Internet" and "Samsung Internet Beta" are affected. Various settings of the autofill in Bitwarden were tested.

### Operating System

Android

### Operating System Version

Android 12/One UI4.1 & Android 13/OneUI 5.1

### Device

Galaxy S10+, Galaxy Tab S8+, Galaxy S23 Ultra

### Build Version

2023.7.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by hoo84** [comment]
This worked for me, thank you !
