### ISSUE TITLE
Add support for Duck Duck Go Browser

### ISSUE THREAD

**Issue by BigNickBurgess** [bitwarden/mobile#267]
Can support be added for

https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android

It now supports Oreo autofill too.

**Comment by kspearrin** [comment]
Added oreo and accessibility autofill support in latest beta.

**Comment by BigNickBurgess** [comment]
Thanks, Duckduck is working fine.  I cant seem to get Firefox focus working however? Was trying to compare the apps and get no autofill prompt anymore.  Has anything changed this end or have mozilla broken it?

**Comment by kspearrin** [comment]
Mozilla did seem to change something. 1308 is now available with support on both.

**Comment by pb1051** [comment]
I still have issues with Duck Duck Go.
