### ISSUE TITLE
Bitwarden iPhone App not finding passwords for some internal sites

### ISSUE THREAD

**Issue by pbarolat** [bitwarden/mobile#2716]
### Steps To Reproduce

1) Open up Bitwarden app
2) Go to search
3) Enter "portainer.barolat"
![IMG_6031](https://github.com/bitwarden/mobile/assets/27367121/7a889e36-505d-4d30-8d99-b11ae126863a)

4) Click the three dots to the right of the entry "portainer.barolat"
![IMG_6032](https://github.com/bitwarden/mobile/assets/27367121/6ff9ece5-8816-4f11-aecd-49e09c0617ca)

5) Select "Launch"
6) Either Chrome or Safari will open up
![IMG_6028](https://github.com/bitwarden/mobile/assets/27367121/0932772c-84ae-4954-b582-8a6a7c7b4410)
7) In the browser select the password field
8) Select "Passwords" to open up Bitwarden to auto fill
9) Authenticate using Face ID (I have this feature enabled)
10) The following screen appears, indicating that an entry for this site does not exist
![IMG_6029](https://github.com/bitwarden/mobile/assets/27367121/2dae5754-a3bb-489c-b85e-34047718cfd0)

This issue does not happen with all internal sites.  

Bitwarden will populate the following internal sites:

https://router.barolat:9090/
http://blueiris.barolat:83/
http://influxdb.barolat:8086/
http://homeassistant:8123/

Bitwarden will not populate the following internal sites:

http://grafana.barolat:3003/
https://portainer.barolat:9443/

Here are screenshots of the two non-working entries:

![IMG_6034](https://github.com/bitwarden/mobile/assets/27367121/299fbb8c-8628-4dc9-a07e-6089db4d49ae)
![IMG_6035](https://github.com/bitwarden/mobile/assets/27367121/c46d57e2-752e-4ad9-998c-7288d35d44c8)

This issue does *not* happen on the browser extension, as you can see in the following screenshot. 

![Portainer - Bitwarden](https://github.com/bitwarden/mobile/assets/27367121/f896b31a-ed89-4553-8eac-96c3ca979e1a)

### Expected Result

At step 10, Bitwarden should show an entry for the appropriate internal website

### Actual Result

At step 10, Bitwarden does *NOT* show an entry for the appropriate internal website.  In the steps above, the website was launched directly from Bitwarden so Bitwarden does have the entry.  Also, I have tried manually typing in the website and the issue still happens.  The issue happens using either Safari or Chrome

### Screenshots or Videos

I made a video of the problem on my iPhone but it is too large for Githhub.  You can find it on iCloud here:

https://share.icloud.com/photos/0c0Tx_YJOvxS_eRa8s620Suwg

### Additional Context

Troubleshooting steps so far:

1) Reinstall Bitwarden iOS App
2) Remove Bitwarden as an option to fill in passwords (under Settings -> Passwords) and then re-adding it
3) Removing Keychain as an option to fill in passwords (under Settings -> Passwords) and attempting to use Bitwarden to log into the internal site.

I am running an internal DNS server which allows me to create the DNS entries for the internal sites mentioned in this post.

I am running a self-hosted server on Docker.  Here are the details:

Digest: sha256:8040174b601984a687aa429464a02392ae1638887ef261d9563c4d4ecb9cb88f
Status: Image is up to date for bitwarden/setup:2023.7.2
docker.io/bitwarden/setup:2023.7.2

Bitwarden is up and running!
===================================================

### Operating System

iOS

### Operating System Version

16.6

### Device

iPhone X

### Build Version

2023.7.0 (3881)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Although you are able to autofill other internal sites without adjusting the match detection, please attempt adjusting the match detection to see if it resolves the issue. (https://bitwarden.com/help/uri-match-detection/#match-detection-options)

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/  

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
