### ISSUE TITLE
Self hosted - Problem connecting server - Android

### ISSUE THREAD

**Issue by scifire91** [bitwarden/mobile#272]
Hey,

just installed bitwarden docker in our environment. All works fine expect the Android app won´t connect to our instance. Browser in Android works also fine.
In the app when i try to login there comes instant an error message: `There is a problem connecting to the server.`
We use a valid trusted wildcard cert.
Server is behind a firewall with 80&443 open.
OS is Ubuntu 16.04 with no local iptables. 
In the docker nginx log i found this entry 
`2018/01/29 15:37:06 [error] 11#11: ocsp.digicert.com could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.digicert.com, certificate: "/etc/ssl/vault.example.com/certificate.crt" `
Of course domain is not example.com ;-)

any other information needed?
Don´t know what i do wrong....

**Comment by kspearrin** [comment]
Can you send your domain to support@bitwarden.com so we can look?

**Comment by kspearrin** [comment]
Your cert has trust issues. This is why it fails. See https://www.digicert.com/help/

**Comment by scifire91** [comment]
@kspearrin thanks, i figured out how to fix this.
could it be that in the how to is something wrong? I´ve done [this](https://help.bitwarden.com/article/install-on-premise/) step by step.
I have the certificate and also the ca.crt in the folder but nginx won´t use the ca.crt. I have to create a bundle.crt which includes certificate.crt und ca.crt, rename this and now it works.

**Comment by kspearrin** [comment]
What type of cert are you using? Our installer only generates LE certs. Other than that you have to provide your own proper cert. Which configuration did you choose during set up? This determines how your nginx config file gets generated.

**Comment by scifire91** [comment]
We use a wildcard cert from digicert. Most CAs give you a separate cert file and ca cert file. Letsencrypt give you also a cert.csr but also a fullchain.pem which is a bundle of ca cert and cert.
So i would recommend you to add this step to the help page:
Create a bundle of Cert and CA cert if it´s not.
`cat certificate.crt ca.crt >>bundle.crt`

**Comment by kspearrin** [comment]
Which cert option did you choose during install? This is the login used:

            var sslPath = LetsEncrypt ? $"/etc/letsencrypt/live/{Domain}" :
                SelfSignedSsl ? $"/etc/ssl/self/{Domain}" : $"/etc/ssl/{Domain}";
            var certFile = LetsEncrypt ? "fullchain.pem" : "certificate.crt";
            var keyFile = LetsEncrypt ? "privkey.pem" : "private.key";
            var caFile = LetsEncrypt ? "fullchain.pem" : "ca.crt";

**Comment by scifire91** [comment]
During install i used "Use existing cert" 
Problem is that nginx can´t use a cert File and a different ca file (as far as i know)

**Comment by kspearrin** [comment]
I am still a bit confused as to what needs to be changed though?

**Comment by scifire91** [comment]
The [Install on Premise](https://help.bitwarden.com/article/install-on-premise/) instruction is not complete.
If you use a single file certificate and a single file CA certificate (certificate.crt & ca.crt) it won´t work. nginx can handle this only in a bundle.
So i need to create this bundle manual as i wrote above or you add some magic in docker which do this for me.

**Comment by kspearrin** [comment]
So after you create the bundle.crt what do you do with it? the nginx config is not looking for a file called bundle.crt

**Comment by scifire91** [comment]
rename it to certificate.crt that nginx use it ;-)

**Comment by kspearrin** [comment]
Sorry I am not an expert on SSL certs, so to be clear:

1. You received a `certificate.crt`, and `ca.crt` from your SSL provider.
2. You run `cat certificate.crt ca.crt >>bundle.crt` you create a new `bundle.crt`. 
3. In bitwarden's ssl folder for your domain you replace original `certificate.crt` with `bundle.crt` (renamed to `certificate.crt` so it can still be read)?

**Comment by kspearrin** [comment]
In the end you have the following files in SSL folder:

- `certificate.crt` (`bundle.crt` renamed)
- `private.key`
- `ca.crt`

**Comment by scifire91** [comment]
Exactly :) 
A little hint to this would be nice in the help page.

**Comment by kspearrin** [comment]
Updated here: https://help.bitwarden.com/article/install-on-premise/#install-bitwarden


> certificate.crt (required). If not done so already, you may need to bundle your primary certificate with any intermediate certificates provided by the CA or else you will receive SSL trust errors. ex. cat domain.crt ca.crt >> certificate.crt. See here for more information.

**Comment by scifire91** [comment]
Nice, i think that will help future installations
