### ISSUE TITLE
[Bug] High Battery Use - Android App

### ISSUE THREAD

**Issue by Daptonic** [bitwarden/mobile#273]
The last few days I have noticed that Bitwarden has accounted for nearly 15% of my battery use. 

I spent some time in Facebook or Instagram, but those apps were already connected/configured so no password forms were presented.

I didn't take a screenshot at the time, but I'll do so later today when it inevitably climbs. It is already the only app registering battery use (2%), while my phone has been idle for the last 2 hours.

**Comment by kspearrin** [comment]
This is likely the autofill accessibility service. Open Settings -> Options and use some of the battery saving options.
