### ISSUE TITLE
iOS apps crash after submitting a master password (only for entries that have Master Password Reprompt)

### ISSUE THREAD

**Issue by konstantin-f13** [bitwarden/mobile#2733]
### Steps To Reproduce

1. Open any entry that has Master Password Reprompt.
2. Click on 'Edit' or a watch button on hidden fields (an eye icon), or "Delete". 
3. Type a master password (either correct or incorrect) as requested.
4. Click on 'Submit'.

### Expected Result

Expected results depend on the action of the step 2 (Steps To Reproduce) - screen for editing is displayed/hidden value is displayed/list of items in folder after deletion of item is displayed. Most importantly, the app doesn't crash.

### Actual Result

App crashes.

### Additional Context

Everything has worked correctly till today when I updated iOS apps on iPhones and an iPad to version 2023.8.0. Interestingly, I can still copy passwords protected by the master password without crashes after inputting a master password. Logging out, reinstallation, logging in again - doesn't help. At the same time, web and desktop app works without issues.

### Operating System

iOS

### Operating System Version

iOS 16.6 (iPhone 8, iPhone 13), iOS 15.7.8 (iPad Air 2)

### Device

iPhone 8, iPhone 13, iPad Air 2

### Build Version

2023.8.0 (4566)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by konstantin-f13** [comment]
Used KDF algorithm - PBKDF2 SHA256, KDF iterations - 600000.
Server - EU.

**Comment by jtodddd** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by aikideshi** [comment]
Yup. Haven't been able to use bitwarden for the past couple days. Still can't. Had to be near a PC and manually type in passwords from PC whenever I need to login at the moment. So forced to look into other password managers as I'm stuck. Any ETA on a fix? Thanks

**Comment by konstantin-f13** [comment]
Hi there.

I would like to add, that after I reported the bug, I switched the key derivation function from PBKDF2 to Argon2 with default settings in order to check if the bug is reproduced with these settings. However, it didn’t help and I still experience the same problems - in some cases it's a crash and in some cases it's absolute no action – for example, after submitting a master password in order to watch the hidden values in secure notes.

Could we know the ETA on a fix? This bug has substantially limited the use of the iOS apps because most of my entries have Master Password Reprompt.

**Comment by konstantin-f13** [comment]
After updating a desktop app on Windows 10 to version 2023.8.2 I now cannot view or edit any reprompt requiring entries here as well. Plz fix the bug:)

**Comment by aikideshi** [comment]
Same here. Doesn't work for me on Windows as well. Will this be fixed soon?

**Comment by liqfx** [comment]
Just adding to this that I’m experiencing this as-well on iOS.

**Comment by weedy** [comment]
I'm on Android and updated a couple hours ago.

Same thing, anything with Reprompt turned on crashes everything. I had to load the website to get to my things, or turn off Reprompt.

**Comment by konstantin-f13** [comment]
As mentioned in a [comment](https://github.com/bitwarden/clients/issues/6176#issuecomment-1703848868) in a similar bug report, we can bypass this bug and get access to our entries by the following:

When you are already in your vault opened with the help of the PIN:
1. turn off PIN code option for logging into the app.
2. lock the vault and unlock it with a Master Passoword.
3. open/edit/copy protected entries or fields with Master Password Reprompt.

This solution actually discouraged me from temporary migration to another password manager. I have tested this on Desktop (windows 11) and iOS (iPhones 8 & 13).

**Comment by Mihier-Roy** [comment]
Wanted to add that I'm facing the same problem on Android: Version: 2023.8.0 (7466)

**Comment by aikideshi** [comment]
Can't even log in because it crashes after I key in password. So currently
totally unusable for me

**Comment by liqfx** [comment]
Yea this needs to be addressed urgently at the moment can’t auto fill half my passwords when on mobile.

**Comment by ManassesM** [comment]
I was able to reproduce it on Android 13 as well.

**Comment by aikideshi** [comment]
Still stranded, still can't get access to my passwords. Is there any update
on this? Thanks

**Comment by nitrocode** [comment]
For what it's worth, you can downgrade (Android only probably) to [v2023.7.0](https://github.com/bitwarden/mobile/releases/tag/v2023.7.0) and it no longer crashes on creds with password reprompt. I'll keep my version pinned by disabling auto updates until the next release.

**Comment by meilluer** [comment]
> ### Steps To Reproduce
> 1. Open any entry that has Master Password Reprompt.
> 2. Click on 'Edit' or a watch button on hidden fields (an eye icon), or "Delete".
> 3. Type a master password (either correct or incorrect) as requested.
> 4. Click on 'Submit'.
> 
> ### Expected Result
> Expected results depend on the action of the step 2 (Steps To Reproduce) - screen for editing is displayed/hidden value is displayed/list of items in folder after deletion of item is displayed. Most importantly, the app doesn't crash.
> 
> ### Actual Result
> App crashes.
> 
> ### Screenshots or Videos
> _No response_
> 
> ### Additional Context
> Everything has worked correctly till today when I updated iOS apps on iPhones and an iPad to version 2023.8.0. Interestingly, I can still copy passwords protected by the master password without crashes after inputting a master password. Logging out, reinstallation, logging in again - doesn't help. At the same time, web and desktop app works without issues.
> 
> ### Operating System
> iOS
> 
> ### Operating System Version
> iOS 16.6 (iPhone 8, iPhone 13), iOS 15.7.8 (iPad Air 2)
> 
> ### Device
> iPhone 8, iPhone 13, iPad Air 2
> 
> ### Build Version
> 2023.8.0 (4566)
> 
> ### Beta
> * [ ]  Using a pre-release version of the application.

Here a temporary fix https://www.reddit.com/r/Bitwarden/comments/164eg71/comment/jznf5oj
