### ISSUE TITLE
Attempting "Log in with device" on iOS fails, spams alert modals, requires closing app to recover

### ISSUE THREAD

**Issue by nlawalker** [bitwarden/mobile#2739]
### Steps To Reproduce

1. Log in to Bitwarden on Windows desktop
2. Open Bitwarden on iOS, select username and tap "Continue", then tap "Log in with device"
3. Click "Confirm login" in Bitwarden on Windows desktop

### Expected Result

Successful login

### Actual Result

App repeatedly spams "We were unable to process your request. Please try again or contact us" alert modals forever. Have to close the app to recover.

### Additional Context

Windows desktop version 2023.8.2

### Operating System

iOS

### Operating System Version

16.6

### Device

iPhone XR

### Build Version

2023.7.0 (3881)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by sammbw** [comment]
Hello again,

I managed to resolve this on my end by testing the latest updates to the iOS app, and Bitwarden desktop app - I do not see the same issue now.

Could you test the 2023.8.3 Bitwarden desktop app, and the 2023.8.0 Bitwarden iOS app together for me?
