### ISSUE TITLE
[Feature request] Cleanup Accessibility options

### ISSUE THREAD

**Issue by BigNickBurgess** [bitwarden/mobile#274]
Currently if you are on Oreo with the oreo auto fill turned on under 'Cog- > Options' the accessibility settings remain toggleable and one must always be active (no idea if it still runs any code or not).  

Turning them all off results in 'Always scan' being toggled on when you go back to the options.

Also can a permanent link be added for the Oreo autofill settings as it has been for the accessibility settings?  This is just handy.

**Comment by kspearrin** [comment]
These settings are for the accessibility service, as defined by their header under options. They have no effect unless you have enabled the accessibility service.

Not sure what you mean by a permanent link. We link to it from the Tools page for autofill if you do not have it enabled yet.

**Comment by BigNickBurgess** [comment]
It just seems odd you cant turn off all the accessibility settings if you want making it seem like something is running.

I just meant have a link to it even if you have it enabled a the accessibility version has.
