### ISSUE TITLE
App crashes after re-entering master password 

### ISSUE THREAD

**Issue by mnjsahay** [bitwarden/mobile#2753]
### Steps To Reproduce

1. Enable biometrics authentication
2. Create a login and in that login tick box for  master password re-prompt
3. close and then open app via  biometrics(finger)
4. Open login and try to see and password , it will try to reauthenticate , enter master password. app will crash

### Expected Result

app should not crash

### Actual Result

app crashed

### Operating System

Android

### Device

Samsung galaxy s20 5g fe

### Build Version

2023.8.0(7466)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by equetzal** [comment]
> Hi there!
> 
> This seems to have previously been reported with #2733 and a fix has been issued with #2713 which will be included in the next release (2023.9)
>  
> This issue will now be closed.
> 
> Thanks!
> 
> 

How does the update propagates? 
Is it immediate or is through the playstore release process?
