### ISSUE TITLE
iOS app crashes when attempting to access an item with master password re-prompt

### ISSUE THREAD

**Issue by aim2120** [bitwarden/mobile#2754]
### Steps To Reproduce

1. Tap an existing Login item that requires a master password re-prompt (or create a new item that requires it).
2. Attempt to view the item's password field.
3. Enter the master password, click "Submit".

### Expected Result

The item's password is shown and the app does not crash.

### Actual Result

The app crashes when "Submit" it tapped.

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/14299642/e27a9227-09dc-410c-80bb-8821f0ad7319

### Additional Context

I've reproduced this on multiple devices.

### Operating System

iOS

### Operating System Version

16.6.1

### Device

iPhone SE

### Build Version

Version: 2023.8.0 (4566)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Hi @aim2120 

This seems to have previously been reported with https://github.com/bitwarden/mobile/issues/2733 and a fix has been issued with https://github.com/bitwarden/mobile/pull/2713 which will be included in the next release (2023.9)

This issue will now be closed.

Thanks!
