### ISSUE TITLE
Android App crashes when attempting to View/Copy passwords protected by "Reprompt master password"

### ISSUE THREAD

**Issue by Universal-Igloo** [bitwarden/mobile#2755]
### Steps To Reproduce

(This bug is currently reproduced on the Chrome extension, MacOS desktop client & Android app. Everything used to work perfectly till now for as long as I can remember.)

1. Go to the card for whichever password you have enabled "Reprompt Master Password" for
2. Click on either view or copy Password field
3. Enter the Master password 
4. click ok

### Expected Result

1. It should accept the Master Password or Tell you that it is incorrect
2. The password should be copied or viewable

### Actual Result

The android app crashes

### Operating System

Android

### Operating System Version

13

### Device

Google Pixel 4a

### Build Version

2023.8.0 (7466)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Hi @Universal-Igloo

This seems to have previously been reported with https://github.com/bitwarden/mobile/issues/2733 and a fix has been issued with https://github.com/bitwarden/mobile/pull/2713 which will be included in the next release (2023.9)

This issue will now be closed.

Thanks!
