### ISSUE TITLE
Changing the master password using the app ONLY.

### ISSUE THREAD

**Issue by Salah-Asmar** [bitwarden/mobile#276]
Hello,

Is there anyway to change the master password using the application, without the need of opening the web  page (vault.bitwarden.com).

I mean, No need to open the website.

Regards

**Comment by kspearrin** [comment]
No, this is only available in the website at this time.

**Comment by Salah-Asmar** [comment]
Honestly, It's annoying... I hope you that it will be changed in the near future.

I'm a really big fan of the app 👍
