### ISSUE TITLE
Android app does not require password after changing fingerprints

### ISSUE THREAD

**Issue by cannedshrimp** [bitwarden/mobile#278]
I changed the fingerprints on my device and was able to log into Bitwarden with the new finger prints. Is it possible to make Bitwarden require a password after fingerprints change on the device? This seems like it would be much more secure.

**Comment by kspearrin** [comment]
I am not aware of a way to detect something like this. Do you know?

**Comment by kspearrin** [comment]
Not currently. 2FA only occurs on log in, not unlocks. We are tracking this in another issue already, however.

**Comment by cannedshrimp** [comment]
Okay great. Thanks for the quick response!

**Comment by cannedshrimp** [comment]
FYI... I am not aware of how they do it, but the Chase mobile banking app is able to detect changes to Android finger print settings. I was unable to screenshot the alert because of their security settings, but it is probably worth keeping an eye out for how Bitwarden might achieve this!
