### ISSUE TITLE
[Feature request] Allow few records to be available offline

### ISSUE THREAD

**Issue by ajithijk** [bitwarden/mobile#279]
My request may not go fully with the vision behind the product, but I think if there is a feature that allows a record or a particular field to he available offline it would be great.  A particular use case may be the availability of credit card pin or tele-banking pin . Users can always be confident that the important info is always available with them even if internet is not available. We can use keepass for offline storage but since users are comfortable with bitwarden why use another tool for offline availability.

**Comment by taodailOryx** [comment]
@ajithijk It does work offline though..? If you turn on airplane mode, you can still open your vault. It does take ages trying to sync before unlocking if it thinks there is internet access, which is why it should behave like Safe in Cloud (unlock first, then try to sync).

**Comment by kspearrin** [comment]
The app will function in read-only mode while offline. As long as you are logged in before going offline you can still access everything.

**Comment by ajithijk** [comment]
Thank you for that info. I was trying  to login without internet access after logout and was saying network connection error. One question though, where is the local copy of the data stored once I logged in and in what format that is available in my phone ?

**Comment by kspearrin** [comment]
See https://help.bitwarden.com/article/where-is-data-stored-computer/

It's in a SQLite database.

**Comment by ajithijk** [comment]
Thank you for the update. Is it possible to make the local login possible even if the user have logged out and internet access is not available(similar to what taodailOryx said above). Do this cause any security issue or affect functionality of the app ? There could be instances when a user have logged out from bitwarden and  have no internet availability to get his important data that he have stored to view them locally.

**Comment by kspearrin** [comment]
This is what app locking is for under Settings, which works offline.
