### ISSUE TITLE
Crash when trying to export vault on iOS or android

### ISSUE THREAD

**Issue by LoossSS** [bitwarden/mobile#2793]
### Steps To Reproduce

1. Go to iOS or android app, in the settings menu
2. Click on export vault, use the default json export
3. Type in master password
4. Click on export vault in the popup
=> the app crashes

### Expected Result

The app doesn't crash. The vault is exported in json format

### Actual Result

The app crashes

### Additional Context

I'm using french language. Don't think that's the issue.
I'm self hosted, with server up to date.
I've seen few reports of the same bug on Reddit since beginning September.

### Operating System

Android, iOS

### Operating System Version

iOS 16.6.1 ; Android 11

### Device

iPhone 12 pro ; Samsung A40

### Build Version

2023.9.1 (4890) ; 2023.8.0 (7466)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by LoossSS** [comment]
Some other contexts, found on reddit:

https://reddit.com/r/Bitwarden/s/jLmYumm7Ok
https://reddit.com/r/Bitwarden/s/7URo1CPdDQ

**Comment by SaabirahMohamed** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
