### ISSUE TITLE
Target UWP App

### ISSUE THREAD

**Issue by steskalja** [bitwarden/mobile#281]
Will you be targeting a native uwp app? Since this is already build with xamarin.

**Comment by kspearrin** [comment]
We already target UWP in this project, but there are no plans to release it anymore since we have native desktop apps coming out soon which will provide a much better experience on Windows.

**Comment by copytime** [comment]
Native desktop app is great. But it only runs in windows desktop version. Any plans for Windows 10 mobile users ?

**Comment by kspearrin** [comment]
@copytime No, sorry.

**Comment by PrplHaz4** [comment]
@copytime see this fork/app - obviously not as good as an officially supported client but is open source still...

https://github.com/alistair23/bytewarden-windows
