### ISSUE TITLE
Timeout option "never" doesn't work in 2023.9.1

### ISSUE THREAD

**Issue by KweezyCode** [bitwarden/mobile#2815]
### Steps To Reproduce

Set timeout to "never", then relaunch app

### Expected Result

auto login to bitwarden app without requiring master password

### Actual Result

still requires master password

### Operating System

Android

### Operating System Version

Android 11

### Device

Asus ZenFone 7

### Build Version

2023.9.1 F-droid

### Beta

- [ ] Using a pre-release version of the application.

**Comment by KweezyCode** [comment]
i moved to 2023.8.1 and now everything works fine, but it is not a solution of the problem

**Comment by trmartin4** [comment]
Hi @KweezyCode.  I wanted to let you know that this behavior was also reported [here](https://github.com/bitwarden/mobile/issues/2787).  I've updated this thread to indicate that we are currently working on this issue and plan to include it in the next major release.

Thank you for your patience and for your support of Bitwarden by reporting the problem.
