### ISSUE TITLE
Incorrect Text Display on Screen Readers - Bitwarden for Android

### ISSUE THREAD

**Issue by RafaelFernandesBR** [bitwarden/mobile#2817]
### Steps To Reproduce

1. Open the Bitwarden app.
2. Navigate through the folders and items on the screen using a screen reader.
3. Notice that occasionally, the incorrect text ", ItemNameLabel, ItemCountLabel" is read by the screen reader instead of the item or folder name.

### Expected Result

items and folders are read with the correct name for the screen reader.

### Actual Result

Items and folders sometimes have the words ", ItemNameLabel, ItemCountLabel" instead of their names.

### Screenshots or Videos

NA

### Additional Context

Hello, I'd like to report some accessibility issues I've encountered with the Bitwarden app for Android, which have been persisting for about a month now.

When using screen readers like TalkBack or Jieshu, there are instances where the text for a folder or item within the app is not displayed correctly. Instead of the screen reader announcing, for example, "contas bancárias" (bank accounts), it reads the following text: ", ItemNameLabel, ItemCountLabel."

### Operating System

Android

### Operating System Version

android 13

### Device

xiaomi redmi note 10S

### Build Version

2023.9.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by RafaelFernandesBR** [comment]
Hello, any predictions for a fix for this bug?
