### ISSUE TITLE
Android 14 - Bitwarden autofill cannot be enabled.

### ISSUE THREAD

**Issue by yurividal** [bitwarden/mobile#2826]
### Steps To Reproduce

Open bitwarden, go to settings, auto-fill service. Try to enable auto-fill service. The button goes back to off.

If you go in the Amdroid security settings, Bitwarden doesn't have the option to enable autofill, while 1password and dashlane have the option.

### Expected Result

Bitwarden should allow turning on autofill service.

### Actual Result

Unable to use native android autofill service with bitwarden on Android 14.

### Screenshots or Videos

![IMG-20231015-WA0014](https://github.com/bitwarden/mobile/assets/8555749/6b064078-f5c9-4021-8e8c-2dc8e14e2d4d)
![Screenshot_20231015_141743_Settings](https://github.com/bitwarden/mobile/assets/8555749/bbf2edcd-765f-41c6-994f-4ffaf13bc352)

### Additional Context

Samsung Galaxy S23 running Android 14 (OneUI 6)

### Operating System

Android

### Operating System Version

14

### Device

Galaxy S23

### Build Version

Version: 2023.9.2 (8002)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by mrjlturner** [comment]
The issue persists with OneUI 6.1.1 on Android 14. I have been trying to fix this on my Samsung Galaxy Tab S10+. It was making me crazy. I am glad that I am not the only one that has seen this issue. Hopefully someone finds a solution?
