### ISSUE TITLE
App Locker bug

### ISSUE THREAD

**Issue by ArtexJay** [bitwarden/mobile#283]
I think it's a bug, when I'm on my app locker about to unlock the app, Bitwarden pops in trying to recommend me one of my passwords from another app or website. Is there a way to disable autofill when on app lockers.

Edit: here is a screenshot ![inkedscreenshot_20180214-200404_li_moment](https://user-images.githubusercontent.com/32932497/36236437-08674c02-11c4-11e8-8309-702affb465ed.jpg)

**Comment by kspearrin** [comment]
Sorry. I don’t know a lot about android. What is an app locker and how does it work?

**Comment by ArtexJay** [comment]
An app locker is a layer of security on android where, you need to give your password to unlock and use an app. If you do not have the password one will not be able to use the app at all.

**Comment by ArtexJay** [comment]
On my phone which is running Oneplus 3T, android 8,  Settings >security & lock screen > app locker (On my phone app locker is under privacy in security & lock screen)

**Comment by kspearrin** [comment]
I'm not seeing app locker anywhere on my Nexus 5X with Android 8.1. Is this something that is suppose to be on all Android devices?

**Comment by ElTopo** [comment]
@ArtexJay it's not built into Android, either you or your phone vendor (i.e., oneplus) installed it.

**Comment by fingerwarrior** [comment]
It's an OEM feature (in this case, oxygenOS by OnePlus), not in AOSP

**Comment by kspearrin** [comment]
All someone needs to do is tell me the package name of this App Locker app and I can add it to the list of packages to ignore for autofill.

**Comment by fingerwarrior** [comment]
com.oneplus.applocker thanks for the prompt reply

**Comment by ArtexJay** [comment]
My bad 😅 thought it was a built it thing but it wasnt.

**Comment by EpIcInCoGnItO** [comment]
> 
> 
> All someone needs to do is tell me the package name of this App Locker app and I can add it to the list of packages to ignore for autofill.

Mate, I already posted on Reddit for this. This package name has not been added to the blacklist yet and its driving me crazy. Thank you.

**Comment by kspearrin** [comment]
I just added build 1653 to the beta track on Google Play with `com.oneplus.applocker` on the ignore list. Can you give it a try?
https://play.google.com/apps/testing/com.x8bit.bitwarden

**Comment by EpIcInCoGnItO** [comment]
Kyle,

Thanks a tonne. This seems to work for me.. When will you add this to the
public repo?

**Comment by kspearrin** [comment]
No ETA on release at the moment.

**Comment by kspearrin** [comment]
Thanks for checking.
