### ISSUE TITLE
Bitwarden Crashing Issue on iPhone 13 and iPad Air 13: Seeking Solutions

### ISSUE THREAD

**Issue by SchneiderSam** [bitwarden/mobile#2839]
### Steps To Reproduce

Hello Bitwarden Community,

I'm reaching out today to discuss a recurrent issue I've been experiencing with Bitwarden on my iPhone 13 and iPad Air 13, and I'm curious if any of you have faced a similar problem.

The issue typically arises when I have two apps open simultaneously. Here's a breakdown of what happens:

I have both Bitwarden and another app (where I need to log in) open.
I switch to Bitwarden in the background to retrieve my login credentials.
I then switch back to the other app.
Upon returning to Bitwarden, the app crashes, but interestingly, only the first time.
On subsequent tries, Bitwarden remains stable and doesn't crash.
This problem doesn't seem to occur consistently, making it a bit challenging to replicate at will. However, I've primarily noticed it on my iPhone 13 Pro and iPad Air 13. Has anyone else faced a similar issue with these devices or any other?

I deeply appreciate any insights, solutions, or workarounds the community can provide. As a dedicated user, I'm eager to find a resolution to this inconvenience.

Thank you in advance for your assistance and shared experiences.

Best regards, Samuel

### Expected Result

Bitwarden not crashing

### Actual Result

Bitwarden is crashing

### Operating System

iOS

### Build Version

Version 2023.9.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by bjacksonbit** [comment]
I can confirm that the engineering team is aware of this bug, and is working to fix it on our next release (https://github.com/bitwarden/mobile/pull/2778). 

​My recommendation at present is to set your vault timeout to 'lock' and enable TouchID/FaceID.  This will let you quickly unlock the vault each time you are requested.

I apologize for the inconvenience.
