### ISSUE TITLE
Cannot save item to collections when ‘Remove Individual Vault’ is selected and person is set as a user of an org, from iOS share sheet only

### ISSUE THREAD

**Issue by Gerardv514** [bitwarden/mobile#2842]
### Steps To Reproduce

1. Go to 'iOS Safari browser, and go to a web page with a login'
2. Click on 'the iOS share sheet and then select bitwarden so that we can add this webpage login to Bitwarden as a vault item.’
3. Complete name, user name, password and uri then try and save. 

### Expected Result

As a user of the organization, there’s no option to choose which collection this item should be saved to, even when the user has permissions to collections. 

A user of the org can view all collections when going directly to the Bitwarden iOS app. Collections even show for the user in the desktop browser extension.

Collections just do not show through mobile browser, then share sheet, then click on bitwarden app. 

### Actual Result

App just spins on saving and does nothing. You need to force close the app. You can never save an item this way. 

### Operating System

iOS

### Operating System Version

17

### Device

iPhone 14 Pro

### Build Version

2023.9.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Gerardv514** [comment]
@djsmith85 Daniel, thanks for your response earlier. Please see this issue that I have created. 

Additionally the below issue 1874 issue, which was reported April 2022, maybe the same. 

https://github.com/bitwarden/mobile/issues/1874

**Comment by SergeantConfused** [comment]
Hi @Gerardv514,

Thank you for your report. I was able to reproduce this behaviour and I have flagged it to our Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by Gerardv514** [comment]
> Hi @Gerardv514,
> 
> Thank you for your report. After reviewing the link above, I decided to close this one as it's a duplicate of the report you've mentioned (#1874), in order to consolidate this matter into a single GitHub thread.
> 
> If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.
> 
> This issue will now be closed.
> 
> Thank you again,

Thank you, is it possible to move/merge my initial report from here to #1874, so that the team has a better breakdown on what steps are needed to see this issue?
