### ISSUE TITLE
Allow screen capture not enforced in iOS

### ISSUE THREAD

**Issue by Eagleshot** [bitwarden/mobile#2854]
### Steps To Reproduce

1. Go to Settings -> Other -> Allow screen capture
2. Make sure this setting is turned off (default position)
3. Take a screenshot, record the screen or share the screen (e.g. in a video call)
4. Review the screenshot, recording or look at the shared screen

### Expected Result

The passwords and other sensitive should be hidden when recording or sharing the screen on iOS in order to prevent them from accidentally being shared like it is done on Android.

### Actual Result

Passwords and sensitive data can be seen in screenshots, screen recordings as well when sharing the screen on iOS and iPadOS. 

### Additional Context

It looks like this feature is only implemented on Android and not iOS/iPadOS (see: https://community.bitwarden.com/t/option-to-allow-screen-capture-on-the-android-app/41393) which doesn't make any sense. In addition this creates a sense of false security.

### Operating System

iOS

### Operating System Version

iOS 17.0.3

### Build Version

2023.10.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by TroyBW** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by SergeantConfused** [comment]
Hi @Eagleshot,

I wanted to follow up and ask you still see that option in the Bitwarden iOS client that you are using? 

To be clear, that function is available only for Android and we've addresses this report [here](https://github.com/bitwarden/mobile/pull/2873).


Thank you in advance,

**Comment by Eagleshot** [comment]
Thank you for the fix, the option now no longer shows up in the app on iOS.
