### ISSUE TITLE
Pin keyboard won't pop up on application launch

### ISSUE THREAD

**Issue by 1mzeZMSU51pO85SSifG968huDlep2nAsJVqHTcZ** [bitwarden/mobile#2866]
### Steps To Reproduce

1. Enable "Unlock with PIN code" in account security settings
2. Ensure that the application is not running 
3. Launch the application (I can reproduce this bug by opening Bitwarden using the autofill button on Gboard as well as launching normally)

### Expected Result

"Verify PIN" activity starts. Pin keyboard slides up from the bottom, prompting me to enter the pin.

### Actual Result

"Verify PIN" activity starts. No keyboard is present, however. I have to stretch my finger to the top of the screen to tap the PIN EditText to make the keyboard appear.

### Screenshots or Videos

Self explanatory?

### Additional Context

This problem becomes obnoxious if you set session timeout to "immediately"

### Operating System

Android

### Operating System Version

Android 14 UP1A.231105.003

### Device

Pixel 7

### Build Version

2023.10.0 (8257)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by micahblut** [comment]
Confirmed that in the native app, the PIN field is never focused automatically.
