### ISSUE TITLE
Cannot connect using IPv6-only

### ISSUE THREAD

**Issue by aentwist** [bitwarden/mobile#2889]
### Steps To Reproduce

1. [self-hosted] use ipv6 only
2. log in

### Expected Result

works via app

### Actual Result

`Exception message: Unable to resolve host "vault.example.com": No address associated with hostname`

### Additional Context

I am self hosting and using an IPv6-only setup on the level of there is no A record for the domain, only a AAAA record. I just recently switched and before that I had no problems with the app.

I've had great success on my computer but not my phone. So I believe it is not a server issue.

I have logged in through my phone's web browser. The Access Point Name has APN protocol IPv4/IPv6. So I believe it is not an Android issue.

Can you confirm the known level of IPv6 support? I would like to get some more information before I go [sideloading](https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=bitwarden) to check for regressions or investigating more annoying potential issues like a User-Agent problem.

The only workaround seems to be using the web interface on my phone, but it does not use responsive design (why should it, there is an app) so the whole experience has become quite painful...

### Operating System

Android

### Operating System Version

Android 13

### Device

Pixel 4a

### Build Version

2023.10.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hello there, 

The Bitwarden self-hosted instance does support IPv6. Due to a limitation in Docker, you will not see the IPv6 addresses of connecting traffic inside the container logs - this is due to IPv4 traffic being directly NATed into the container network, while IPv6 traffic is handled by a userland proxy process on the host OS.

In order to see IPv6 addresses inside the container logs, you need to run a separate reverse proxy on the host OS listening on both v4 and v6 or just v6, and pass traffic into the Docker environment on v4-only with headers for the real client IPs. If you do not need to log the real client addresses in the containers, the default setup should be working on v4 and v6.

**Comment by aentwist** [comment]
Please reopen this

**Comment by StarRainNight** [comment]
ios app have same problem, please reopen.

**Comment by aentwist** [comment]
I tried to reproduce this but am having trouble. It's a weird issue to begin with. I think my VPN was interacting with the networking at the time. Although I was aware of that (no VPN supports IPv6 right now) and tried to be careful, I must have messed it up somehow when I was originally verifying this issue. @StarRainNight if you are serious then you should provide details. Otherwise despite the disappointing response to this issue it deserves to stay closed, in my current opinion.

**Comment by StarRainNight** [comment]
> I tried to reproduce this but am having trouble. It's a weird issue to begin with. I think my VPN was interacting with the networking at the time. Although I was aware of that (no VPN supports IPv6 right now) and tried to be careful, I must have messed it up somehow when I was originally verifying this issue. @StarRainNight if you are serious then you should provide details. Otherwise despite the disappointing response to this issue it deserves to stay closed, in my current opinion.

Sorry, it is my mistake. ios app can work well under ipv6.
The problem I encountered before was that network permissions were not set correctly.
Thanks for your replay.
