### ISSUE TITLE
Master password is displayed while typing it in landscape mode on Android

### ISSUE THREAD

**Issue by thibaut-decherit** [bitwarden/mobile#289]
Only occurs while the google keyboard is open to type in the master password field. The field goes "fullscreen" with the keyboard below it and `p@ssword` is displayed instead of `********`.

Master password is correctly hidden when viewing the login page in landscape mode.

**Comment by kspearrin** [comment]
Sounds more like a Google Keyboard bug to me. What happens on other apps that have password fields?

**Comment by thibaut-decherit** [comment]
Tested it on multiple apps in landscape mode : 
- ProtonMail
- Dropbox
- Evernote
- LastPass

Didn't encounter the bug on any of them.
In landscape mode, ProtonMail and LastPass password field behaves like bitwarden's (tie field goes "fullscreen" with the keyboard below it) **but** password is correctly hidden.

You can see screenshots of my tests here : [https://imgur.com/a/uaP3I](https://imgur.com/a/uaP3I)
(except LastPass, the app blocks screenshots like bitwarden does)

**Comment by n21brown** [comment]
Same thing happens using stock keyboard on Galaxy Note 8 on Android N. Password is visible in landscape but when rotated back to portrait password is masked

**Comment by patrickvale** [comment]
Just to add that I have just experienced this on a OnePlus 3, running BitWarden 1.18.1 (1500) and Android 7.1.1 with Gboard as the keyboard.
Signing in to evernote with the phone in landscape orientation, I have the option to either show or hide the password (the eye with a diagonal line through it).

The interesting thing about Bitwarden is that when you go landscape with the focus in the Master password field, it becomes a 'full screen' text input as described above - something I've not seen before when logging into an app. Also there is no 'eye' to click and show or hide the password.

**Comment by thibaut-decherit** [comment]
Bug is still present at least on Android, tested on 3 devices (Android 4, 8 and 9)

**Comment by kspearrin** [comment]
Should be fixed in v2.0.
