### ISSUE TITLE
Passkey autofill does not work on iPad

### ISSUE THREAD

**Issue by unikitty37** [bitwarden/mobile#2904]
### Steps To Reproduce

1. Create an account on gitlab.com on a desktop or laptop, and configure a passkey for it in Bitwarden.
2. On iPadOS, set up Bitwarden; in Settings > Passwords > Password Options, set "Use passwords and passkeys from: Bitwarden" and disable all other options.
3. Go to https://about.bitlab.com and click Sign In.
4. Tap the key icon and choose the saved password in Bitwarden; tap Sign In.

### Expected Result

When prompted for the passkey, I get Bitwarden as an option.

### Actual Result

When prompted for the passkey, I only get options for a hardware security key, or an iPhone, iPad or Android device. There is no way to use the passkey saved in Bitwarden.

### Screenshots or Videos

![7D750804-65E4-4B57-B75F-6ADCC5D4C84A_1_201_a](https://github.com/bitwarden/mobile/assets/139183/f68c6303-c206-461c-8390-5963edd76102)

### Additional Context

This does not work if, instead of using the built-in autofill, I use the Share icon and select Bitwarden.

The only way to have working Passkey support on iPad appears to be to leave iCloud Keychain enabled and let it store them. This is not usable, as every time I need to save a password, I now have an extra prompt asking me where it should be saved rather than it just saving to Bitwarden, as iPadOS does not allow separate settings for passwords and passkeys.

### Operating System

iOS

### Operating System Version

17.2

### Device

iPad Pro (11", 3rd Generation)

### Build Version

2023.12.0 (5688)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hello there,

Passkeys are currently available on our web extension. Mobile and iPad support will be coming in the future.

**Comment by dancojocaru2000** [comment]
Would it not make sense to keep the issue open, since it's something that's "coming in the future"?

**Comment by gerardbosch** [comment]
> Hello there,
> 
> Passkeys are currently available on our web extension. Mobile and iPad support will be coming in the future.

Hi @Krychaz, may I ask whether there is a public roadmap or backlog to keep an eye on this upcoming feature (passkey support for mobile)? Thanks.

_Related to_: https://github.com/bitwarden/mobile/issues/2972
