### ISSUE TITLE
iOS Autofill Automatically Closes Keyboard

### ISSUE THREAD

**Issue by BEaXt7f97** [bitwarden/mobile#2907]
### Steps To Reproduce

1. Go to any app/browser
2. Click on any text field (ie. Email / Password) and press the field for the pop-up AutoFill menu 
3. Click on Passwords
4. Click on verify your FaceID/Password (if activated) and it'll prompt you to "AutoFill Passwords"
5. There is no passwords, so click on the Search tab
6. Keyboard will try to open, and automatically close creating a bootloop of this issue.

Yes the iOS Passwords is selected to Bitwarden in iOS settings. 

### Expected Result

Being able to autofill emails / usernames / passwords

### Actual Result

Cannot autofill.

### Operating System

iOS

### Operating System Version

17.2

### Device

iPhone 12

### Build Version

21C62

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hello,

Thank you for reporting this. I tested this on iOS 17.2 with Safari and Bitwarden 2023.12.0 and I was able to search for a vault item through the Auto-Fill flow using the keyboard. I'd recommend proceeding with a fresh new installation; Please uninstall Bitwarden off your iOS device, turn your device off (long press) and back on, install Bitwarden anew from the Apple App Store, and check if that helps.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
