### ISSUE TITLE
Android/Firefox add-on: Unable to auto-fill

### ISSUE THREAD

**Issue by mrichtarsky** [bitwarden/mobile#2910]
### Steps To Reproduce

1. In Firefox Mobile: Navigate to website
2. Bitwarden Add-on -> Tap on Login item

### Expected Result

Login is filled in

### Actual Result

Message: "Unable to auto-fill the selected item on this page."

### Additional Context

- It works again when reinstalling the extension. But after a browser restart it is broken again.
- This worked fine on the same device/browser in the past (I would guess a couple months ago)
- Additionally, when syncing the vault, the error is "Syncing failed"
- The Bitwarden Android app is still able to autofill some field
- I'm also using the Firefox add-ons for macOS and Windows, these work fine as well

### Operating System

Android

### Operating System Version

14

### Device

Samsung Galaxy A54 5G

### Build Version

2023.12.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi,

Thank you for your report. I understand that you are using the Bitwarden browser extension within your mobile Firefox browser; Please bear in mind that that client is designed for desktop environments (https://bitwarden.com/help/product-faqs/#q-does-bitwarden-manage-the-firefox-browser-extension-on-android-mobile) and browsers, and on Android you should use our dedicated Android client (https://bitwarden.com/help/getting-started-mobile/).

If you wish, you can continue using that client in the mobile Firefox browser, but you'd be doing so at your own risk as some of its functions may not operate as expected in a mobile environment.

Thank you.
