### ISSUE TITLE
Certification error with the SSL cert isssued by ZeroSSL 

### ISSUE THREAD

**Issue by zen010101** [bitwarden/mobile#2911]
### Steps To Reproduce

self-host using docker and issed a new ssl cert for it using the acme.sh with the ZeroSSL server:
acme.sh --server ZeroSSL --issue -d dns_dp -d *.example.com

then login on the android with the Bitwarden app which version is 22023.12.0(8588). it will display an error message after click the Next button which will let me input the self-host server address:

**java.security.cert.CertPathValidatiorException: Trust anchor for certification path not found.**

then I change a new cert issued by Let's encrypt , all things work well.

### Expected Result

let me input the self-host server address

### Actual Result

java.security.cert.CertPathValidatiorException: Trust anchor for certification path not found.

### Operating System

Android

### Device

Xiaomi 10 Ultra

### Build Version

2023.12.0(8588)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
This indicates that your device is missing some certificate files. Please follow the steps here: https://community.bitwarden.com/t/android-client-login-bitwarden-https-cert-problem/12132 to download the missing certificate files, and then follow the instructions here: https://support.google.com/pixelphone/answer/2844832?hl=en  to upload those files to your device.

Please note that if you're self-hosting your own Bitwarden server, you'll need to supply the certificates you're using and not use the ones for our web vault. Also note that the procedure to upload the certificate files to your device may be slightly different from the guide above and will depend on the make and model of your Android device.

More information here: [https://bitwarden.com/help/certificates/#trust-a-self-signed-certificate](https://bitwarden.com/help/article/certificates/#trust-a-self-signed-certificate)

**Comment by zen010101** [comment]
but, when I browse my self-host web site with the same cert, the Edge and other browsers are all no problem. why only bitwarden client meets errors.

**Comment by Krychaz** [comment]
As explained in the links above, the web vault has the SSL certificate when you access it via the web. However the apps do not have this ability, they need a certificate file in order to work properly.

**Comment by zen010101** [comment]
It doesn't work following the steps gived by the site you mentioned.
Finally, I downloaded the cert from official site:
https://letsencrypt.org/certs/lets-encrypt-r4.pem and installed to my phone
successfully.

Krystian Kan ***@***.***> 于2023年12月22日周五 17:55写道：
