### ISSUE TITLE
Bitwarden acts abnormally when typing anywhere in Geometry Dash

### ISSUE THREAD

**Issue by EMREOYUN** [bitwarden/mobile#2914]
### Steps To Reproduce

1. Enable Bitwarden on an Android Device
2. Launch Geometry Dash (v2.2.13)
3. Try typing on any text boxes

### Expected Result

Bitwarden should not appear because none of these text boxes are password fields except login screen.

### Actual Result

Bitwarden tries to appear every single text area and sometimes completely blocks the ability to write due to countless appearences.

### Screenshots or Videos

[Video](https://youtu.be/L88tBcdUx4w)

### Additional Context

Game can be found in [Google Play Store](https://play.google.com/store/apps/details?id=com.robtopx.geometryjump)

### Operating System

Android

### Operating System Version

Android 13 / MIUI 14.0.3 Global

### Device

Redmi Note 11

### Build Version

2023.12.0 (8588)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @EMREOYUN,

Thank you for your report. Could you please include a screenshot that shows where and how Bitwarden is appearing in that game?


Thank you in advance,

**Comment by EMREOYUN** [comment]
> Hi @EMREOYUN,
> 
> Thank you for your report. Could you please include a screenshot that shows where and how Bitwarden is appearing in that game?
> 
> 
> Thank you in advance,

@SergeantConfused Added the video link in the original report in advance.

**Comment by SergeantConfused** [comment]
Hi @EMREOYUN,

Thank you. Is there an equivalent menu in the [free version](https://play.google.com/store/apps/details?id=com.robtopx.geometryjumplite) of that game?


Thank you in advance,

**Comment by EMREOYUN** [comment]
> Hi @EMREOYUN,
> 
> Thank you. Is there an equivalent menu in the [free version](https://play.google.com/store/apps/details?id=com.robtopx.geometryjumplite) of that game?
> 
> 
> Thank you in advance,
> 

@SergeantConfused Negative. However, there is [another side version of the game](https://play.google.com/store/apps/details?id=com.robtopx.geometrydashworld) which does exact same thing as the paid one. The exact menu shown in the video is disabled in this game. However, pressing the cog icon in main menu, going "Account" menu, and going "Log In" screen, the exact same bug happens as described in the report.

**Comment by SergeantConfused** [comment]
Hi @EMREOYUN,

Thank you. I tested this on a Samsung Device running Android 12 with Samsung Keyboard and Gboard, and in both cases I received the Bitwarden [Inline Auto-Fill prompt](https://bitwarden.com/help/auto-fill-android/#inline-autofill), and I did not encounter the [Accessibility Service Auto-Fill prompt](https://bitwarden.com/help/auto-fill-android/#accessibility) as shown in your video. I suspect that this is unique to your particular setup.

I recommend that you first test this by using a different keyboard, such as Gboard, and checking if that affects the behaviour; If that does not, please keep Gboard installed and set as the default keyboard and uninstall Bitwarden off your Android device, turn your device off (long press) and back on, install Bitwarden anew from the Google Play Store, and test that once more. Please remember to activate all your [Auto-Fill services](https://bitwarden.com/help/auto-fill-android/#).

If the steps above do not assist, please feel free to create a [support ticket](https://bitwarden.com/help/) and include a link to this GitHub report so we'd proceed in troubleshooting this.

We use GitHub to track bugs and other development related matters, and this GitHub report will be closed at this point; I thank you in advance for your understanding.

All the best,
