### ISSUE TITLE
error message after PBKDF2 iterations change

### ISSUE THREAD

**Issue by corey851** [bitwarden/mobile#2931]
### Steps To Reproduce

Probably a one-off but reporting anyway...  
I changed the PBKDF2 iterations on my vault as recommended (on the web site, of course).  
Knowing I have to re-login everywhere, I went to re-login on my iPhone.  

### Expected Result

success and a feeling of satisfaction

### Actual Result

"An error has occurred.  One or more URLs saved in the Settings are incorrect  Please revise it and try to log in again."

Multiple login attempts including closing and reopening app produced the same message. 

### Screenshots or Videos

![BW-URL-error](https://github.com/bitwarden/mobile/assets/13644947/05b97d36-c33f-45f5-ae57-7fd0c15c4167)

### Additional Context

I am up and running fine after removing the Bitwarden app and reinstalling it.  Login went fine this time.  
Not sure if the build version was the same as what it is now (shown below).  But I have App Updates enabled so it probably was. 

### Operating System

iOS

### Operating System Version

iOS 17.1.2

### Device

iPhone SE 2

### Build Version

2023.12.0 (5688)   

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @corey851,

Thank you for this report. That message is unrelated to the change performed to your account's KDF settings. If you encounter this, please return to the email address field and tap on (Logging in on:) and select the server that you'd like to log into, and then proceed and enter your master password; We are aware of this behaviour and are working to address it in an upcoming release.

At this stage, I will proceed and close this GitHub report as it's not strictly related to the KDF settings.


Thank you again,
