### ISSUE TITLE
cannot log into mobile (Android) app: error message "One or more URLs saved in the settings are incorrect"

### ISSUE THREAD

**Issue by bayesfactor** [bitwarden/mobile#2938]
### Steps To Reproduce

1. Go to login screen of Android app
2. Try to log in with username (email) and master password
3. When master password is entered, get the error message:
`
an error has occurred. One or more URLs saved in the settings are incorrect. Please revise it and try to log in again
`

According to [this](https://community.bitwarden.com/t/login-problems-and-popup-message-android/60958) "solution", it should be possible to select the "Not you?" option, return to the login page, and select bitwarden.com (I am logging in from the US). However, when trying that, I get the same error message.

### Expected Result

After entering master password, I expect to see an authenticator (2FA) prompt.

### Actual Result

Rather than prompting for 2FA code, we get the error message
`
an error has occurred. One or more URLs saved in the settings are incorrect. Please revise it and try to log in again
`

### Screenshots or Videos

There is some discussion of this bug in the forum, but I do not see this issue logged in GitHub.
https://community.bitwarden.com/t/login-problems-and-popup-message-android/60958

### Additional Context

This happens after the 2nd login attempt on a fresh install of the app on Android.

### Operating System

Android

### Operating System Version

Samsung Galaxy Note 9; Android v10

### Device

Samsung Galaxy

### Build Version

2023.12.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there!

Thank you for your report - this issue has been addressed in 2024.1.0, can you try updating your app to ensure it's been resolved as expected? If you don't see the update available, try uninstalling then re-installing the app.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!
