### ISSUE TITLE
login with device fingerprint phrases dont match between firefox extension and android app

### ISSUE THREAD

**Issue by kinghat** [bitwarden/mobile#2940]
### Steps To Reproduce

try to login with device on firefox(flatpak) extension in linux desktop
go to notification or unlocked vault on android app

### Expected Result

the fingerprint phrases should be matching

### Actual Result

fingerprint phrases dont match

### Additional Context

i didnt see any issues about it here but there is a community post about it from last year: https://community.bitwarden.com/t/login-to-web-using-device-is-impossible-because-fingerprint-phrases-dont-match/49770

### Operating System

Android

### Operating System Version

14 graphene os

### Device

pixel 6a 

### Build Version

2023.12.0 (8588)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by kinghat** [comment]
> The Flatpak version of Bitwarden is community-managed and is not officially supported by Bitwarden. Please install the Firefox extension from the official Bitwarden downloads page: https://bitwarden.com/download/

this is for the bitwarden firefox browser extension, installed via the mozilla addon store which the bitwarden site directs you to, that happens to be running in firefox which is a flatpak. not the flatpak version of bitwarden desktop.

> We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
> 
> You can include a link to this issue in the message content.

the public shouldnt be opening mobile bug reports in this repo? i dont know if this is a mobile or firefox browser extension issue tbf.

> Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

i posted a link to the year old community discussion about this issue in the report.

**Comment by Krychaz** [comment]
Hello there @kinghat 

Apologies for the delay and initial confusion. I understand that you are using the Bitwarden browser extension within your mobile Firefox browser; Please bear in mind that that client is designed for desktop environments (https://bitwarden.com/help/product-faqs/#q-does-bitwarden-manage-the-firefox-browser-extension-on-android-mobile) and browsers, and on Android you should use our dedicated Android client (https://bitwarden.com/help/getting-started-mobile/).

If you wish, you can continue using that client in the mobile Firefox browser, but you'd be doing so at your own risk as some of its functions may not operate as expected in a mobile environment.

**Comment by kinghat** [comment]
> Hello there @kinghat
> 
> Apologies for the delay and initial confusion. I understand that you are using the Bitwarden browser extension within your mobile Firefox browser; Please bear in mind that that client is designed for desktop environments (https://bitwarden.com/help/product-faqs/#q-does-bitwarden-manage-the-firefox-browser-extension-on-android-mobile) and browsers, and on Android you should use our dedicated Android client (https://bitwarden.com/help/getting-started-mobile/).
> 
> If you wish, you can continue using that client in the mobile Firefox browser, but you'd be doing so at your own risk as some of its functions may not operate as expected in a mobile environment.

thanks for the reply! this is about bitwardens firefox desktop extension and the mobile android app. not the bitwarden browser extension running in the firefox mobile context.

**Comment by kinghat** [comment]
this is still an issue.
