### ISSUE TITLE
App Shows up as suggestion in Termux (official termux and termux money)

### ISSUE THREAD

**Issue by warmoans** [bitwarden/mobile#2943]
### Steps To Reproduce

Have bitwarden auto fill enabled.
Open termux.

### Expected Result

The app is not suggested in Gboard when using Termux

### Actual Result

App is shown in Gboard auto fill in Termux app

### Screenshots or Videos

![Screenshot_20240117-203016](https://github.com/bitwarden/mobile/assets/37345461/dc6a0c51-7cda-4a83-a7ab-8f6c664f02b4)

### Operating System

Android

### Operating System Version

14

### Device

Pixel 7 Pro 

### Build Version

2024.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so, as Termux does not appear to be supported in Android 14 on my Pixel device. Can you confirm which version of Termux you are using, and where you installed it from?

**Comment by warmoans** [comment]
Ah 

> Hi there,
> 
> I attempted to reproduce your issue and was unable to do so, as Termux does not appear to be supported in Android 14 on my Pixel device. Can you confirm which version of Termux you are using, and where you installed it from?

The termux on the play store is several years old. The official termux is only released on GitHub/fdroid currently and Termux Monet is also only on GitHub. You can install either version on top of each other if you got both from GitHub. 

Anyways it happens with the latest releases for both versions.

https://github.com/termux/termux-app

https://github.com/KitsunedFox/termux-monet

**Comment by sammbw** [comment]
Hello @warmoans,

Thanks for confirming - I've just installed Termux from F-Droid and I'm unable to replicate this on my Pixel device, I do not see an inline prompt at all for Bitwarden using Gboard also. Is it possible you have vault item saved with the URI 1 value of **com.termux**?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by warmoans** [comment]
> Hello @warmoans,
> 
> Thanks for confirming - I've just installed Termux from F-Droid and I'm unable to replicate this on my Pixel device, I do not see an inline prompt at all for Bitwarden using Gboard also. Is it possible you have vault item saved with the URI 1 value of **com.termux**?
> 
> We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
> 
> You can include a link to this issue in the message content.
> 
> Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).
> 
> The issue here will be closed.
> 
> Thanks!

I don't have anything saved for Termux. I guess I'll go through your customer support at some point in the future.

**Comment by sphars** [comment]
I know this issue is already closed, but I also encountered this issue on my Pixel 8 (Android 14) with the latest available Termux app.

Thankfully the settings to ignore a URI worked. For anyone else who comes across this, add this as a blocked URI:

```
androidapp://com.termux
```

**Comment by ErwinP** [comment]
> I know this issue is already closed, but I also encountered this issue on my Pixel 8 (Android 14) with the latest available Termux app.
> 
> Thankfully the settings to ignore a URI worked. For anyone else who comes across this, add this as a blocked URI:
> 
> ```
> androidapp://com.termux
> ```
> 
> 

Thank you! I came here for the exact same reason and can confirm this works instantaneously.

**Comment by maphew** [comment]
It took me a bit to find the block option: you can't get there from the bitwarden control offered while in Termux.

1. Launch Bitwarden app
2. Settings >> Auto fill 
3. Scroll to bottom, as "Block Auto fill" menu item is below the fold.
