### ISSUE TITLE
App Shows up as suggestion in Termux (official termux and termux money)

### ISSUE THREAD

**Issue by warmoans** [bitwarden/mobile#2943]
### Steps To Reproduce

Have bitwarden auto fill enabled.
Open termux.

### Expected Result

The app is not suggested in Gboard when using Termux

### Actual Result

App is shown in Gboard auto fill in Termux app

### Screenshots or Videos

![Screenshot_20240117-203016](https://github.com/bitwarden/mobile/assets/37345461/dc6a0c51-7cda-4a83-a7ab-8f6c664f02b4)

### Operating System

Android

### Operating System Version

14

### Device

Pixel 7 Pro 

### Build Version

2024.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by jsddsfoh** [comment]
Hi there!
I was using autofill and now it's not working anymore.. So, how to get it working? I tried adding `androidapp://com.termux` as URI for the corresponding entry, but that didn't worked.
Any suggestions?
