### ISSUE TITLE
App crashing on IOS using a match detection

### ISSUE THREAD

**Issue by demonpig** [bitwarden/mobile#297]
Phone: IPhone 8 Plus

IOS: v11.2.6

Steps:
- Start app
- Click + button in top right to create new password
- Click Login
- Click gear icon in URI text box
- Click Match Detection
- Click Default (it should have a check mark next to it)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kspearrin** [comment]
Thanks. Fixed in next version
