### ISSUE TITLE
When we can use passkey via bitwarden mobile?

### ISSUE THREAD

**Issue by purofle** [bitwarden/mobile#2972]
Android 14 and iOS now fully support passkey applications, I have been able to use passkey via 1password on an android 14 device. When will bitwarden be able to do this too?

**Comment by cbbit** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. Passkeys support for mobile applications is planned for a future release.
​
For the latest information on new features and releases, make sure to check out our Release Notes here: https://bitwarden.com/help/releasenotes/

You may also have Release Announcements delivered straight to your inbox, by signing up here: https://bitwarden.com/help/releasenotes/#release-announcements

Thank you!
​
