### ISSUE TITLE
iOS - safari - no items bug

### ISSUE THREAD

**Issue by oldrich-s** [bitwarden/mobile#298]
Since the latest Bitwarden update, whenever I open Bitwarden in Safari for a certain web page, I get "There are no items in your vault for this website. Tap to add one". I am sure there are items for that website...

EDIT: The same goes for Chrome on iOS.

EDIT 2: Reinstalling the app seems to help.

PS: Can't you pls share the login between the main Bitwarden app and the Safari add-on? It is very irritating to have to give password every time - the Safari add-on does not remember password at all.

**Comment by kspearrin** [comment]
Are you using a self hosted server?

**Comment by lycheng-rex** [comment]
I have the same issue when using safari and firefox, and I solved it by reinstalling the app as well. So every time when I need to get access to the latest vault on safari or firefox, if updating, I have to reinstall app. 
PS: I’m not using a self hosted server.

**Comment by kspearrin** [comment]
This only happens after updating?

**Comment by lycheng-rex** [comment]
Yes. Actually I’m a new user to Bitwarden for 2 days. So far, I reinstalled app once and found it never happened again...?! But I’m sure that the first time installation always failed to show the new vault in safari and firefox.

**Comment by kspearrin** [comment]
Could you try setting a different lock option and see if that helps? We had someone email us with a similar problem and they mentioned that changing their lock options from Never to 15 minutes made the problem go away.

**Comment by lycheng-rex** [comment]
I will give it a try if that happens again. 

By the way, my first-time installation used lock option NEVER, causing that issue. And for the second installation, I do not change default lock option, which is15 minute and _everything goes well so far_. But now, I see your suggestion and I want to change lock option to NEVER again to see whether this causes the problem. lol

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
