### ISSUE TITLE
Android - Potential data access when app locks

### ISSUE THREAD

**Issue by JetSetDoritos** [bitwarden/mobile#302]
The entry options menu can persist even after the app locks.

Steps to reproduce: My app is set to lock immediately and unlock with fingerprint.
1. In the app press the three dots to the right of any entry to bring up options for that entry.
2. Lock your phones screen.
3. Unlock your phone.
4. You will see the options for that entry still open behind the "Use your fingerprint to verify" dialogue.  
5. Press cancel, and the entry is fully accessible by pressing "View", despite the app being locked.

Occurs about 9/10 times, occasionally menu does not persist.

Running app version 1.15.2 on Google Pixel 1 with Android 8.1 (April 5th patch)

Update: It also happens if you switch away from the app and switch back, rather than locking the screen.

**Comment by kspearrin** [comment]
Thanks, I can reproduce it.

**Comment by CameronTurner** [comment]
This appears to be fixed, is it?

**Comment by mportune-bw** [comment]
Fixed in #857
