### ISSUE TITLE
Hitting "generate password" twice very fast opens the window twice, which gets confusing

### ISSUE THREAD

**Issue by rggjan** [bitwarden/mobile#303]
I just accidentally clicked the "generate password button" twice on the iPhone app (the circled arrow). What happens:

1. The window pops up twice
2. Clicking "Select" or "Cancel" is not working
3. You have to click "Cancel" or "Select" really fast a few times to get back to the previous screen

This should be fixed...

**Comment by kspearrin** [comment]
Should be fixed in v2.0.
