### ISSUE TITLE
Bitwarden treats google translate input field as password.

### ISSUE THREAD

**Issue by smirnov** [bitwarden/mobile#306]
Every time I start typing in Google Translate window, Bitwarden offers to autofill and suggests to save my input, since the dialogs popup sometimes it leads to unneeded attempt to save the input in BitWarden.
![photo_2018-04-24_17-36-59](https://user-images.githubusercontent.com/437645/39197951-1b74194e-47e6-11e8-9856-2f72d650735b.jpg)
![photo_2018-04-24_17-34-57](https://user-images.githubusercontent.com/437645/39197961-220db120-47e6-11e8-98a9-9708598f7a34.jpg)
![photo_2018-04-24_17-34-53](https://user-images.githubusercontent.com/437645/39197962-239fd98c-47e6-11e8-9e36-deb7e4c73876.jpg)

**Comment by kspearrin** [comment]
I am not able to reproduce. What language is your device set to?

**Comment by kspearrin** [comment]
Fixed next release.

**Comment by kspearrin** [comment]
Fix is in android beta channel now if you want to try it.

**Comment by smirnov** [comment]
Can confirm that it works as expected. That was a blazing quick fix for a pretty annoying bug. Thanks.
