### ISSUE TITLE
FaceID not working iPhone X

### ISSUE THREAD

**Issue by jmauss** [bitwarden/mobile#307]
Not sure why anything changed, but when I reinstalled Bitwarden today on my iPhone X, toggling the FaceID option forces me to enter my phone password instead of my face. When opening the app, I get "Enter iPhone passcode for 'Bitwarden'
Use Face ID to verify."

Anyone else?

**Comment by kspearrin** [comment]
We’ve had a few people report this lately. It worked fine before reinstalling?

**Comment by jmauss** [comment]
I last had it installed for a while and did a reset of my phone. I had it installed before and after the latest update with no issue. Not sure why a fresh install would cause this.

**Comment by kspearrin** [comment]
I don't have a iPhone X to test with so I am unsure what could be the problem, but it's definitely not just you.

**Comment by kspearrin** [comment]
Fixed in next version. Thanks.
