### ISSUE TITLE
The Quick Tiles in the Android notification shade do not do anything when tapped, and may cause Bitwarden to close unexpectedly.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#3070]
### Steps To Reproduce

1. Install Bitwarden 2024.2.1.
2. Activate the [Accessibility Service Auto-Fill](https://bitwarden.com/help/auto-fill-android/#accessibility).
3. Add the Bitwarden (Auto-Fill) tile to the notification shade.
4. Tap on the (Auto-Fill) quick tile in the notification shade. 

### Expected Result

For Bitwarden to attempt to perform Auto-Fill.

### Actual Result

Nothing happens, and the Bitwarden Android client may close unexpectedly.

### Screenshots or Videos

N/A

### Additional Context

1. This seems isolated to Android 14.
2. This is being worked on [here](https://github.com/bitwarden/mobile/pull/3069).

### Operating System

Android

### Operating System Version

14

### Device

Pixel 5

### Build Version

2024.2.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by HyknuF** [comment]
same here, since last update.  OnePlus 6, Android 14

**Comment by staticEndeavour** [comment]
Same. 
Pixel 7a
Android 14
Graphene OS
Fdroid build 2024.2.1

**Comment by bbretttt** [comment]
Also.
Sony Xperia 1 IV
14
2024.2.1

**Comment by techbot2342** [comment]
Same. 
Samsung S22 Ultra 
Android 14
Lastest build

**Comment by todaypp** [comment]
Same.
Galaxy S23
Android 14
2024.2.1
Details: [reddit comment](https://www.reddit.com/r/Bitwarden/comments/1bac4ti/comment/ku29gx8/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by Undisputed00x** [comment]
Same
Pixel 6 Pro
Android 14 QPR2
GrapheneOS
Bitwarden 2024.2.1

**Comment by matijaerceg** [comment]
Phew so glad to see this thread - I just jumped ship from LastPass and was thinking maybe I'd made a huge mistake since auto fill wasn't working whatsoever on my Pixel.. :D
