### ISSUE TITLE
Android quick access button does nothing and crashes

### ISSUE THREAD

**Issue by schang1146** [bitwarden/mobile#3073]
### Steps To Reproduce

1. Pull down on top toolbar on an Android device
2. Click Bitwarden icon
![image](https://github.com/bitwarden/mobile/assets/20074034/337d09e7-554c-466b-a528-ab93a706f60f)

### Expected Result

Bitwarden application opens

### Actual Result

Either nothing happens or get "Bitwarden keeps stopping" pop up.

### Screenshots or Videos

"Bitwarden keeps stopping" pop up:
![image](https://github.com/bitwarden/mobile/assets/20074034/ce081fb2-3ad1-4e6c-aba4-1dd0e8c7f84d)

### Additional Context

Opening the application normally (not from the quick access drop down toolbar) works.

### Operating System

Android

### Operating System Version

One UI version 6.0 / Android version 14

### Device

Galaxy S21 5G

### Build Version

2024.2.1 (9641)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/mobile/issues/3070

**Comment by schang1146** [comment]
Oop, sorry. Thought I searched thoroughly enough.
