### ISSUE TITLE
App started to crash after version 2024.2.1

### ISSUE THREAD

**Issue by Aerodymier** [bitwarden/mobile#3074]
### Steps To Reproduce

1. Open Chrome
2. Autofill anything with the "Auto-fill" button in the swipe menu
3. Bitwarden will crash randomly here and tell you something about enabling auto fill in accessibility settings, even though you already did
Here if you go to Android settings and search for the Bitwarden accessibility features, Android will tell that "this app does not function right" in the accessibility settings.
4. Accessibility settings will reset in the app and after turning it on, it works normally for some time

### Expected Result

Like before 2024.2.1 the app should not crash.

### Actual Result

App is crashing and the autofill in keyboard does not appear.

### Operating System

Android

### Operating System Version

Android 14

### Device

Samsung Galaxy S21 Ultra

### Build Version

2024.2.1 (9641)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by bjacksonbit** [comment]
Thank you for bringing this to our attention. We received reports about this behavior and are currently working on it internally; You can follow this topic via GitHub here (https://github.com/bitwarden/mobile/issues/3070), if you wish. For now, please consider using alternative Auto-Fill methods (https://bitwarden.com/help/auto-fill-android/).

I thank you in advance for your understanding.
