### ISSUE TITLE
Face ID unlock on iPhone X not working

### ISSUE THREAD

**Issue by CNpunkt** [bitwarden/mobile#309]
The unlock using Face ID is not working on my iPhone X.

Face ID unlock activated in the settings:
![img_7403](https://user-images.githubusercontent.com/16060613/39521903-c3eec148-4e10-11e8-8852-ae9e7060ec87.PNG)

When unlocking the app shows this screen and then asks for the unlock code:
![img_7404](https://user-images.githubusercontent.com/16060613/39521937-e795dc6c-4e10-11e8-88e6-e98bcb66241f.PNG)
![img_7405](https://user-images.githubusercontent.com/16060613/39521943-ea7176d0-4e10-11e8-975e-c0e633739125.PNG)

In the iPhone Face ID settings Bitwarden is not showing as an app which uses Face ID:
![img_7406](https://user-images.githubusercontent.com/16060613/39522010-330a17c6-4e11-11e8-9a86-dfadaf0386c2.PNG)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/mobile/issues/307
