### ISSUE TITLE
Validation Error when updating Fdroid Version

### ISSUE THREAD

**Issue by EvfHefJvAtE8zkv5FT2AVqevsHZriaIZywPUgvc** [bitwarden/mobile#3097]
### Steps To Reproduce

1. have the 2024.3.0 version of Bitwarden from the F-Droid repo installed
2. Use an fdroid client to update to the 2024.3.1 version of the app.
3. The update fails because of some key validation error.

### Expected Result

The app should update successfully like other apps. I have confirmed that other apps from fdroid seem to update just fine.

### Actual Result

The update fails due to us key validation error.

I use the droidify client and I get a notification with "Could not validate Bitwarden" and "Could not check integrity"

### Screenshots or Videos

I can provide a screenshot if necessary but I don't think it is in this case.

### Operating System

Android

### Operating System Version

Android 14

### Device

Google Pixel 8

### Build Version

2024.3.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Has anybody else experienced this "Your URL for downloading the apk responses with a 503 Response object too large" issue with the latest release?
