### ISSUE TITLE
Android cannot fill passwords in web pages in the edge browser

### ISSUE THREAD

**Issue by Shuai-S** [bitwarden/mobile#3100]
### Steps To Reproduce

I opened the following services
1. Autofill service selected Bitwarden
2. Use inline autofill
3. Open accessibility
4. Use Draw-Over

### Expected Result

I want to pop up the populated password service in the edge browser

### Actual Result

But the password service pops up without filling in.

### Operating System

Android

### Device

HUAWEI Mate 60 Pro

### Build Version

© Bitwarden Inc. 2015-2024  版本: 2024.3.0 (9799)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hello there, 

Can you confirm that the behaviour your are expecting is working as expected on other browsers? If so, would you be able to provide a recording?

**Comment by Shuai-S** [comment]
Hello.
I can use it normally on the Edge browser on MacOS, but on Android phones, I can't fill in the password in the browser, not only the Edge browser, but also in other browsers. I changed to another device XIAOMI 11 and I can't fill in the account password in the browser webpage.

**Comment by Shuai-S** [comment]
I tried restarting the device, resetting autofill, and this time it worked, and the password selection page popped up successfully.

**Comment by Shuai-S** [comment]
I have a new problem. In the MacOS browser, when I log in to some websites, Bitwarden will not prompt me to save the password, but some websites will prompt me to save the password. What is the reason for this? What do I need to do to solve it?

**Comment by Krychaz** [comment]
This sounds like a separate issue. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
