### ISSUE TITLE
auto fill not working in hyperos(MIUI)

### ISSUE THREAD

**Issue by imtipi** [bitwarden/mobile#3107]
### Steps To Reproduce

1. press auto fill on any apps

### Expected Result

detected what website you are in while using chrome,and what apps you are in(example:X)

### Actual Result

bitwarden always detected miui.systemui.plugin as app and filling not work even manually choose

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/27230181/54c8d66f-6910-4489-9013-b6ec6cc49ad9

### Additional Context

already saw some case like me
https://www.reddit.com/r/Bitwarden/comments/1ayu7bs/accessibility_does_not_work/

### Operating System

Android

### Operating System Version

HyperOS 1.0.21.0 (Android 14)

### Device

Xiaomi 14 PRO

### Build Version

2024.3.0(9799)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by joebnb** [comment]
same issue on hyper os
