### ISSUE TITLE
IOS App crashes when opening a login item with CustomFieldText holding characters "--"

### ISSUE THREAD

**Issue by Sasaxxxx** [bitwarden/mobile#3108]
### Steps To Reproduce

In IOS BW App (v 2004.2.1 (6741))
1. Create New Item 
2.  add Custom Field ->Text having characters --. fx: https://xn--vadi-ota.com
3. (make sure "--" is not automatically changed to a line while typing.)
4. Save this New Item 
6. open newly created item causes App to crash

### Expected Result

app should not crash

### Actual Result

when new Item in IOS App is selected to be open, BW App crashes  

### Screenshots or Videos

Created New Item in Desktop app
after sync with IOS App. Trying to open this Item on the IOS App cause App to chrash
![1](https://github.com/bitwarden/mobile/assets/132817930/4dc5b1b9-c31a-4418-96bb-e28cc47e60de)

### Operating System

iOS

### Device

IPhone 12 and Iphone SE - IOS v17.4.1

### Build Version

v 2004.2.1 (6741)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hello @Sasaxxxx,

Thank you for reporting this. I tested this on iOS 17.4.1 with Bitwarden 2024.2.1 by using a Text-type custom field and having its Name and Value set to "https://xn--vadi-ota.com", and opening/viewing that vault item in Bitwarden did not cause any unexpected behaviour. At this stage, I recommend that you proceed with a fresh new installation; Please uninstall Bitwarden off your iOS device, turn your device off (long press) and back on, install Bitwarden anew from the Apple App Store, and test that once more.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by jermanoid** [comment]
This is happening to me as well on app version 2024.4.0 (7272) even after a fresh re-install of the app. I'm using ios 17 on an iphone 14 pro, an ipad pro, and vision OS with the same problem. 

I have a login item with a custom text field that contained a "--". When attempting to load the entry on the iOS app, it crashed. I copied the entry to the notes field, and removed the custom text field, and refreshed. Then the login item is able to successfully load. 

For what it's worth, I'm running vault warden self hosted, so this may be a vault warden issue. I'm curious if @Sasaxxxx is connecting to bitwarden cloud, selfhosted, or vault warden.
