### ISSUE TITLE
IOS App crashes when opening a login item with CustomFieldText holding characters "--"

### ISSUE THREAD

**Issue by Sasaxxxx** [bitwarden/mobile#3108]
### Steps To Reproduce

In IOS BW App (v 2004.2.1 (6741))
1. Create New Item 
2.  add Custom Field ->Text having characters --. fx: https://xn--vadi-ota.com
3. (make sure "--" is not automatically changed to a line while typing.)
4. Save this New Item 
6. open newly created item causes App to crash

### Expected Result

app should not crash

### Actual Result

when new Item in IOS App is selected to be open, BW App crashes  

### Screenshots or Videos

Created New Item in Desktop app
after sync with IOS App. Trying to open this Item on the IOS App cause App to chrash
![1](https://github.com/bitwarden/mobile/assets/132817930/4dc5b1b9-c31a-4418-96bb-e28cc47e60de)

### Operating System

iOS

### Device

IPhone 12 and Iphone SE - IOS v17.4.1

### Build Version

v 2004.2.1 (6741)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

Please try reproducing the issue with the beta version of the native app. The beta program can be joined, and the app downloaded following these instructions: https://community.bitwarden.com/t/about-the-beta-program/39185

Given the recent updates to the beta builds, it would be beneficial to verify if the problem persists with the latest version.

Thanks for your assistance, and I eagerly await your feedback!
