### ISSUE TITLE
Mirror master password login UX from "browser"

### ISSUE THREAD

**Issue by begincalendar** [bitwarden/mobile#312]
What you don't get when authenticating with the "mobile" version of your vault (which you get with the "browser" version):

* "Eye" button to show/hide the master password.
* Password field is cleared after a failed login attempt.

Are these differences there for security reasons?

If not, I prefer the "browser" behaviour, primarily because I have a really long master password and accidentally mistyping one key (without being to able to rectify the mistake easily) is annoying (compared to the "browser").

Could we get the same authentication experience in "mobile" as in "browser" please?

**Comment by kspearrin** [comment]
There are plans to make the mobile app more in-line with the browser extension in more ways than one in the future. This will be one of them.

**Comment by kspearrin** [comment]
Available in v2.0
