### ISSUE TITLE
Repositories of the new Android and iOS apps

### ISSUE THREAD

**Issue by korpe1** [bitwarden/mobile#3129]
> Bitwarden just announced the new apps for Android and iOS on [Reddit post](https://www.reddit.com/r/Bitwarden/comments/1b32bbz/going_native_the_future_of_the_bitwarden_mobile/). Where are the repositories for the source code of them? I want to help in development and testing :)

_https://github.com/bitwarden/clients/issues/8316#issue-2182930962_

**Comment by sammbw** [comment]
Hi @korpe1,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a section for discussions and questions such as this: https://community.bitwarden.com/

If you are interested in contributing to Bitwarden, please read the contributing docs here: https://contributing.bitwarden.com/contributing/

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send ask questions or pop through suggestions to the community forum.

Thanks!

**Comment by korpe1** [comment]
> Hi @korpe1,
> 
> We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a section for discussions and questions such as this: https://community.bitwarden.com/
> 
> If you are interested in contributing to Bitwarden, please read the contributing docs here: https://contributing.bitwarden.com/contributing/
> 
> This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send ask questions or pop through suggestions to the community forum.
> 
> Thanks!

But I was told told that the new apps supposed be here. I can't see them, something is broken? That's why this is a bug report.

**Comment by sammbw** [comment]
Hello @korpe1 - they will be in this repository once they are released.

**Comment by korpe1** [comment]
> Hello @korpe1 - they will be in this repository once they are released.

Excellent, when that should happen?
