### ISSUE TITLE
App closes when I click on an item

### ISSUE THREAD

**Issue by nothing2obvi** [bitwarden/mobile#3130]
### Steps To Reproduce

1. Open app
2. Click to view item in vault
3. App closes

### Expected Result

App should not close

### Actual Result

App closes when clicking on an item

### Operating System

iOS

### Operating System Version

17.1.2

### Device

iPhone 11

### Build Version

2024.2.1 (6741)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by BBGhub** [comment]
Thank you for checking up on this. We received reports about this behavior and the Engineering department is looking into it to hopefully address this in a future release.

If you’d like, you can follow the relevant changes here (https://github.com/bitwarden/mobile/pull/2933).

I thank you in advance for your understanding and patience.

**Comment by nothing2obvi** [comment]
Thank you for the update!
