### ISSUE TITLE
Varnish cache missconfigured for hosting latest fdroid apk

### ISSUE THREAD

**Issue by DirkBaumeister** [bitwarden/mobile#3131]
### Steps To Reproduce

Hi,
when updating the bitwarden mobile app from 2024.3.0 to 2024.3.1 in fdroid I see a "Download failed!" notifcation. Other apps could be updated just fine.

I debugged the fdroid app a little and saw the issue:
Your URL for downloading the apk responses with a 503 Response object too large

You can see it here: https://mobileapp.bitwarden.com/fdroid/repo/com.x8bit.bitwarden-fdroid.apk

As stated here your varnish cache seems to be missconfigured.

Therefore no update of the bitwarden mobile app on android via fdroid is possible at the moment.

Thank you in advance!
Sincerely,
Dirk

### Expected Result

The update from bitwarden mobile version 2024.3.0 to 2024.3.1 should be installed.

### Actual Result

The download of the update shows a "Download failed!" notification and the update fails.

### Screenshots or Videos

<img width="626" alt="318257932-58e9b6fe-b8ea-4c3c-9849-413bc143ae4c" src="https://github.com/bitwarden/mobile/assets/16743298/8e81079d-4b5c-47ee-9770-623ddccf8c96">

### Operating System

Android

### Operating System Version

Any

### Build Version

2024.3.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by daniellbw** [comment]
Hi @DirkBaumeister ,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by DirkBaumeister** [comment]
> Hi @DirkBaumeister ,
> 
> I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below.
> 
> Thanks!

Thank you for your reply.
But actually I don't really understand how you can not reproduce it? The link provided above clearly states that the server (Hosted by bitwarden) cannot serve the latest apk because varnish complains that the file is too big.

But thanks anyway for escalating the issue!

Sincerely,
Dirk

**Comment by Krychaz** [comment]
Hello @DirkBaumeister 

I was able to reproduce your issue. All details have been passed to our engineering team.

**Comment by DirkBaumeister** [comment]
The problem seems to be fixed. I could download 2024.3.1 now sucessfully! Thank you for investigating it 😊
