### ISSUE TITLE
Using 'Pop out to a new window' stopped respecting auto lock

### ISSUE THREAD

**Issue by IOI-655321** [bitwarden/mobile#314]
I was doing something in my browser extension in firefox (v60) 1.26.6 and popped out the window so I didnt lose state when clicking away.  I noticed after about 30 mins when I opened another site my bitwarden extension showed active and a matched login.

I checked my lock settings and it was still set to 1 min, then noticed id left the popped out window open and it had remained logged in.  Is this expected behaviour or can it be made to respect the auto lock option?

**Comment by IOI-655321** [comment]
Just realized I opened this in mobile issues, can it be moved please?

**Comment by kspearrin** [comment]
Please re-open in the browser repo. We don't have the ability to move it.
