### ISSUE TITLE
Passkeys are not working correctly with Lowes.com, the Lowe's iOS app, and/or the v2024.3.3 BitWarden beta app

### ISSUE THREAD

**Issue by ZPNRG** [bitwarden/mobile#3140]
### Steps To Reproduce

Passkeys are not really working correctly for Lowes.com and/or the Lowe's iOS app. I do not know if the problem is with the Lowe's website backend, the Lowe's app (and/or backend), or the BitWarden iOS app (v2024.3.3, which is currently in beta).

Lowe's iOS app v24.4.2
Windows 10 v22H2 (Build 19045.4170)
Brave v1.64.116
BitWarden Chrome extension v2024.2.1

If I create a Passkey from Windows using Brave and save it to BitWarden (via the Chrome/Brave BitWarden extension), then I can log in and out of Lowes.com in Windows/Brave just fine using the Passkey. I can also log into the Lowe's iOS app fine using my Lowe's username/password. The app then bugs me about setting up a Passkey, which has already been done.

So, finally, I decided to set up a Passkey from the Lowe's iOS app and save it to my iOS BitWarden app, overwriting the Passkey that had already been created from Windows/Brave and stored in BitWarden (via the Chrome/Brave extension). I can then log into the Lowe's iOS app using the Passkey stored in BitWarden fine. However, if I then try to log into Lowes.com from Windows/Brave, my BitWarden Chrome/Brave extension says it doesn't have a Passkey for Lowes.com and I cannot fall-back to the username/password. So, I cannot log in.

After all of that, I went back and re-created the Passkey from Windows using Brave and saved it to BitWarden (via the Chrome/Brave BitWarden extension), overwriting the Passkey that had been created via the Lowe's iOS app. Then, I could again log in and out of Lowes.com in Windows/Brave just fine using the Passkey. I could also again log into the Lowe's iOS app fine using my Lowe's username/password. Sadly, again, the Lowe's iOS app then bugs me about setting up a Passkey, which has already been done.

### Expected Result

Should be able to create Passkey and save it using Windows/Brave/Chrome BitWarden extension and it work properly both on Windows/Brave and in the Lowe's iOS app.  Or create via the Lowe's iOS app and save it to BitWarden using the BitWarden iOS app and then it work (be recognized) properly on iOS and in Windows/Brave on Lowes.com.

### Actual Result

Described above.

### Operating System

iOS

### Operating System Version

17.4.1

### Device

iPhone 15 Pro Max

### Build Version

2024.3.3

### Beta

- [X] Using a pre-release version of the application.

**Comment by ZPNRG** [comment]
NOTE:  I did submit this feedback via the TestFlight feedback option, but having used many app in beta via TestFlight for almost 10 years, I've found that submitting feedback either doesn't work or is very flaky.  I have no idea if the submitted feedback was received or not.  So, I'm creating this ticket to make sure the issue I am seeing is documented.  The problem might not at all be on BitWarden's end.  It might be purely with the Lowes.com website and/or the Lowe's iOS app itself.  That I do not know.  But I'm reporting to you since the BitWarden iOS app with Passkeys support is in beta and I am testing it.

**Comment by SergeantConfused** [comment]
Hi @ZPNRG,

Thank you for this report. This matter has been escalated for further investigation; If you have any further information that you think may assist us, please feel free to post it below. 

Thank you again,

**Comment by micahblut** [comment]
@ZPNRG thank you for raising this issue here and in the testflight feedback! We've done some investigating and it looks like the issues lies in the implementation of passkeys between the Lowes app and website, which are using different RpIds when being set up. I suggest submitting some feedback to the role provider (Lowes) as I imagine this issue would be affecting users regardless of whether they are using Bitwarden or not.
