### ISSUE TITLE
Please support Via browser on  android

### ISSUE THREAD

**Issue by Hipd** [bitwarden/mobile#315]
https://play.google.com/store/apps/details?id=mark.via.gp&hl=en_US

Thank you!

**Comment by kspearrin** [comment]
It was added in latest beta, but probably wont work. See here: https://community.bitwarden.com/t/add-via-browser-support/561

**Comment by Hipd** [comment]
I've seen your reply in community and thanks for your try. But I don't know whether you have probe the settings as we could choose what to show at the top (title/domain/url). After I installed the latest beta in play store and make the top bar show domain or url, bitwarden could popup the autofill menu, however, these items do not match the domain. May you investigate it further?

**Comment by kspearrin** [comment]
Where do I turn that setting on in Via browser? If we can show the top domain bar then i should be able to make it work

**Comment by Hipd** [comment]
Settings→general→url box contents

Thanks!

**Comment by kspearrin** [comment]
I just tested this one the latest beta and it works fine... ?

**Comment by Hipd** [comment]
Android 8.0 + Bitwarden 1.16.2

With Autofill Framework Service, seemingly the pulldown menu items are matching the package name "mark.via.gp" instead of the website domain. Do I misunderstand this function? Is it a limitation of the android autofill sevice in web browser?

I tried Auto-fill Accessibility Service and it works fine.

![screenshot_20180522-105322__01](https://user-images.githubusercontent.com/6815562/40339887-07d260d8-5daf-11e8-8e3f-2cc85707b906.jpg)

**Comment by kspearrin** [comment]
I have added via to oreo autofill support in next version. beta will be updated soon

**Comment by Hipd** [comment]
Hey kyle, I've updated to the latest beta and it worked fine now. Love bitwarden and thank you!
