### ISSUE TITLE
Android: App scaling is too big on Samsung DeX

### ISSUE THREAD

**Issue by ungeskriptet** [bitwarden/mobile#3156]
### Steps To Reproduce

1. Connect Samsung device to a monitor wired or wirelessly
2. Launch Bitwarden App

### Expected Result

Bitwarden App Scales correctly and displays text and GUI elements in a reasonable size.

### Actual Result

GUI elements and Text are display way too big

### Screenshots or Videos

  ![Screenshot_20240415_101847](https://github.com/bitwarden/mobile/assets/40729975/bb0bd733-946a-4fc5-b4a2-f77a49429dd3)
![Screenshot_20240415_101742_Samsung DeX home](https://github.com/bitwarden/mobile/assets/40729975/959a9854-b6d2-42e2-b40f-302c219dba9f)

### Operating System

Android

### Operating System Version

One UI 6.1, Android 14

### Device

Samsung Galaxy S24 Ultra

### Build Version

2024.3.3 (10091) via F-Droid Repo

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hello @ungeskriptet,

Thank you for reporting this. I tested this on a Note10+ running Android 12 with Bitwarden 2024.4.0 whilst it was connected to an external 25" (2560*1440) monitor over USB-C, and the size of the text within the Bitwarden interface was similar to that within the Android Settings menu; In the Bitwarden Generator menu, I increased the password length to the maximum (128) and the password was shown within one line whilst the application was displayed on the entire screen. I recommend checking if there are any zoom or accessibility settings that are affecting this.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
