### ISSUE TITLE
iOS passkey list ignores auto-fill match detection setting

### ISSUE THREAD

**Issue by Janhouse** [bitwarden/mobile#3159]
### Steps To Reproduce

1. Add passkeys for multiple subdomains.
2. Set auto fill match rule to "Host".
3. Use the iOS passkey with Bitwarden

### Expected Result

It should respect passkey auto fill match setting.

### Actual Result

Observe both passkeys displayed in the list for all subdomains, ignoring the auto fill match setting.

### Operating System

iOS

### Build Version

7142

### Beta

- [X] Using a pre-release version of the application.

**Comment by micahblut** [comment]
@Janhouse thanks for testing out the iOS passkey beta! Passkeys do not use the login item URI (and therefor the URI match detection) for autofill. They have their own field, the rpId, that is used for matching.
