### ISSUE TITLE
[android] recent versions don't show "Auto-fill Service" notification

### ISSUE THREAD

**Issue by ElTopo** [bitwarden/mobile#316]
Recent versions don't show "bitwarden Auto-fill Service" in the notification area.
My current version: 1.16.2 (1419), installed from Google Play Store.
I have "Persist Notification" turned ON in "Options".

I have seen this problem on Android 5/6/7 devices.

**Comment by kspearrin** [comment]
Is the autofill service turned on under Android Settings -> Accessibility?

**Comment by ElTopo** [comment]
@kspearrin OK, that's indeed the problem, I don't know why it was turned off in Accessibility, I didn't do that and totally forgot to check it. It's also quite strange that the service was disabled on all my devices.

I wonder if the service was disabled, would bitwarden have asked me to re-enable it? not sure.

**Comment by kspearrin** [comment]
We do not ask the user to enable the service. Android does strange things to accessibility services sometimes.
