### ISSUE TITLE
Long passwords spill out of their container

### ISSUE THREAD

**Issue by maxrom** [bitwarden/mobile#317]
I noticed today after adding a 64 character password that it kind of spills out of the area meant to contain it.
This is on iOS.

![4c1e5ada-877c-4720-a7ff-95b6d5eed658](https://user-images.githubusercontent.com/8355771/40397249-92a246a6-5dff-11e8-9e2c-a26be9bc8695.png)

**Comment by beattheprose** [comment]
Hi! Is this still an issue?

**Comment by maxrom** [comment]
Actually, yes. I've since upgraded to premium and a long password is spilling over into the TOTP field now too.

**Comment by beattheprose** [comment]
Ok, I'm not able to produce the bug on my Android device, but I don't have access to a way to test on iOS at the moment. Perhaps someone else could help take a look at this?

**Comment by kspearrin** [comment]
Should be fixed in v2.0.
