### ISSUE TITLE
Password bypass with split screen

### ISSUE THREAD

**Issue by atomheartother** [bitwarden/mobile#319]
I would report this on HackerOne but you guys asked not to report flaws which require physical access to a device, so here I am.

# What
I found a way to bypass the password/fingerprint screen on Bitwarden Android, accessing the vault without authentication. I have not tested this on an iPhone. I have tested it on Android, and can reproduce this bug 100% of the time on the two devices I've tried it on.

# How
Steps to reproduce:
- Lock your vault
- Find an app with a login form, Bitwarden pops a notification telling you it can try to auto-fill
- Click the notification, you're taken to a "verify password" screen (or enter fingerprint)
- Enter split-screen mode (the button for this depends on your device). In most of my tests, at this point, the vault is unlocked. If it isn't:
- Expand the bitwarden screen to take up the whole screen again. The vault unlocks.

Tested on a OnePlus 3 in password mode. I also tested this on a Nokia 6 in fingerprint mode, and it worked when I pressed "Back" on bitwarden's login screen while in split screen mode, unlocking the vault.

# Details
I've tried to make this work without auto-fill (just opening Bitwarden and doing split screen) but it's finnicky. It works sometimes, but only if I previously unlocked the vault using the autofill method. If i close the bitwarden app and restart it, it doesn't work directly. The autofill method always works.

**Comment by kspearrin** [comment]
@atomheartother Thanks for the report. I was able to reproduce the issue.

**Comment by kspearrin** [comment]
This is fixed in the latest play store beta. Can you confirm?
