### ISSUE TITLE
Can't create/use passkeys with Android Firefox

### ISSUE THREAD

**Issue by luca992** [bitwarden/mobile#3193]
### Steps To Reproduce

1. Go to [webauthn.io](https://webauthn.io/)
2. Click "Register"

### Expected Result

Can create and save a passkey in bitwarden

### Actual Result

Bitwarden not available as an option to save the passkey

### Operating System

Android

### Device

Pixel 8 Pro

### Build Version

2024.4.1

### Beta

- [X] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software - passkey support is not available on Android yet.

This issue will now be closed. 

Thanks!

**Comment by luca992** [comment]
@sammbw it is supported on the beta on chrome as of today?

**Comment by sammbw** [comment]
@luca992 you are indeed correct - I'm reopening the issue!

**Comment by micahblut** [comment]
@luca992 thank you for reporting this issue and for testing out the beta! We're aware that passkeys are not working with Firefox and the current theory is that this is down to the Firefox browser's support for 3rd party passkey providers. 

Please check out https://bugzilla.mozilla.org/show_bug.cgi?id=1870436
