### ISSUE TITLE
Unable to set Bitwarden as Passkey Provider 

### ISSUE THREAD

**Issue by dupondje** [bitwarden/mobile#3199]
### Steps To Reproduce

1. Go to 'Auto-Fill'
2. Click on 'Passkey management '

This fails

### Expected Result

Bitwarden should be set as Passkey Provider.

### Actual Result

Error
![Screenshot_2024-04-26-21-05-53-739_com miui bugreport](https://github.com/bitwarden/mobile/assets/723195/d3ac1a5b-3bd0-47aa-90ba-a61b18c65893)

### Operating System

Android

### Operating System Version

Android 14 (HyperOS 1.0.1.0)

### Device

Poco F4 GT

### Build Version

© Bitwarden Inc. 2015-2024  Versie: 2024.4.1 (10283)

### Beta

- [X] Using a pre-release version of the application.

**Comment by Zoran-B** [comment]
Xiaomi 12 Pro with HyperOS v1.0.5.0 doesn't have "Passwords and accounts". When opening from Bitwarden, crashes.


> this workaround seems to work (even though it's for another app lol) https://1password.community/discussion/145306/i-cant-enable-autofill-in-hyperos
