### ISSUE TITLE
Autofill in browsers on Android P

### ISSUE THREAD

**Issue by szale9001** [bitwarden/mobile#320]
Android P, which is currently in Beta, now allows apps to take advantage of the Autofill framework in browsers without using a full Accessibility service. It requires that both the browsers and apps update things to take advantage of this. 

Currently, bitwarden autofill DOES work in android P, but only in apps. So, I wanted to post some info I found with regards to getting autofill working in browsers to since using the autofill framework is always going to be better than using the accessibility service. I hope it can be implemented!

https://blog.dashlane.com/android-p-autofill/
https://developer.android.com/preview/features/autofill#compat-mode

I'm signed up for the bitwarden Android beta and running Android P, so if you make any changes and would like some feedback, I would be happy to help.

**Comment by kspearrin** [comment]
Thanks for the info. Unfortunately we will have to wait until Xamarin releases support for android p before I can begin working on this.

**Comment by szale9001** [comment]
I understand. 

Also, I dl'ed Firefox focus, and I got an autofill prompt, so I think you're good there. Hoping you can get things working for chrome, when xamarin updates. And thanks for the app/service. Really enjoying it.

**Comment by fredgolightly** [comment]
9 is released in preview form - will this allow you guys to work on Android P autofil?
https://blog.xamarin.com/xamarin-android-9-0-p-preview/

**Comment by szale9001** [comment]
Just wanted to follow up on this. Is this possible with the xamarin P preview release? Or will you be waiting for stable channel?

**Comment by kspearrin** [comment]
Sounds like it is. I have not got around to installing the preview yet though.

**Comment by Mentis** [comment]
It was released: https://developer.xamarin.com/releases/android/xamarin.android_9/xamarin.android_9.0/

**Comment by szale9001** [comment]
Very exciting! Just fyi @kspearrin, looks like they moved the documentation here. It's not longer at the link the in the first post.

https://developer.android.com/reference/android/service/autofill/AutofillService#compatibility-mode

**Comment by kspearrin** [comment]
Thanks, I'll update soon and check it out.

**Comment by kspearrin** [comment]
Tried this out today following the instructions from their docs here:
https://developer.android.com/reference/android/service/autofill/AutofillService#compatibility-mode

I have compatibility mode set like:
```
<?xml version="1.0" encoding="utf-8" ?>
<autofill-service xmlns:android="http://schemas.android.com/apk/res/android">
  <compatibility-package android:name="com.android.chrome" android:maxLongVersionCode="1000000000"/>
  <compatibility-package android:name="com.opera.browser" android:maxLongVersionCode="1000000000"/>
</autofill-service>
```

Tried both Opera and Chrome, yet I get no `OnFillRequest` event in the autofill service...

**Comment by kspearrin** [comment]
Commit with updates: https://github.com/bitwarden/mobile/commit/4f0ea440784d01a815b563d54605aa9ed4ed8880

**Comment by szale9001** [comment]
Hmm, I'm honestly not really a programmer so I'm not sure why it wouldn't have worked. I tried searching github though but really only found this:
https://github.com/googlesamples/android-AutofillFramework/commit/03c9e1de1b1a30a020282415b81f9996a0e9dba2
Not sure if it might help, and it looks somewhat similar to what you did. That said, I would be happy to test a beta and report back (I'm in that channel on the Play Store and running Pie on a Pixel 2)

**Comment by kspearrin** [comment]
I'm not sure what could be wrong. Maybe I need to update to  Android Support libraries v28 as well, but those don't seem to be available for Xamarin yet.

**Comment by kspearrin** [comment]
If you want to try the dev build apks with the compat mode enabled on a device, you can download them from here: https://ci.appveyor.com/project/bitwarden/mobile/build/artifacts

I don't have a device that can run Android P, so I was only testing on a simulator. Maybe there is a difference?

**Comment by Mentis** [comment]
Actually it works for me in Chrome (took build 1515)! We just need to add more browsers now.

**Comment by Mentis** [comment]
I have Pixel XL and Android 9

**Comment by szale9001** [comment]
@kspearrin Yea, it actually worked for me as well (Pixel 2 with Android 9). That said, it stops working after 2 or 3 sites on my device. Restarting chrome seems to fix it though, so that might be a chrome issue (Chrome 69) vs a bitwarden issue

**Comment by kspearrin** [comment]
@szale9001 Where do you see this setting in Chrome? I can't find it on my simulator. Chrome 68

**Comment by szale9001** [comment]
Should be about to find it here:

chrome://flags/#enable-android-autofill-accessibility

Just set the flag to enabled and restart the browser.

**Comment by kspearrin** [comment]
@szale9001 Thanks, that fixed it! I guess default is off for whatever reason.

**Comment by szale9001** [comment]
Well because Google is Google, default means whatever they want (just to make it extra confusing). So default for Android 9, Pixel is probably enabled and default for your sim is probably off. Either way, glad it worked!

**Comment by kspearrin** [comment]
I added more support for other browsers in latest build

**Comment by fredgolightly** [comment]
This still isn't native support, is it? It's just enabling the acessability service which can cause lag and batter drain. AFAIK there's still not native web browser autofil api working

**Comment by kspearrin** [comment]
Not sure what you mean, but it's about as native as you can get with browsers.

**Comment by szale9001** [comment]
@fredgolightly In Android Pie they built in a way to allow the autofill API to access certain parts of the accessibility system on a per-app basis (mostly browsers). So while there might be a performance hit while using this autofill mode in those specific apps, it is nowhere near as bad as enabling the global Accessibility service.

**Comment by szale9001** [comment]
I think we are good with this now. Closing issue.

**Comment by szszoke** [comment]
The issue @szale9001 mentioned still happens to me. I'm running a OnePlus 6 on Pie. I enabled the accessibility flag explicitly in the browser. It still stops working after 2-3 sites and I have to restart Chrome to fix it.

**Comment by szale9001** [comment]
Yea, still happens. Unfortunately I think it is a chrome bug. I tried dashlane and 1password to see if they consistently threw autofill prompts and they seemed to have the same problem.

**Comment by PalmArchive** [comment]
Is this something that is being worked on?

**Comment by kspearrin** [comment]
No, since it was completed several months ago.

**Comment by PalmArchive** [comment]
I just updated to Pie on my S9 and Autofill just doesn't work in the browser.

**Comment by kspearrin** [comment]
Are you using a browser that is compatible with autofill ?

**Comment by PalmArchive** [comment]
I'm using chrome, and enabled chrome://flags/#enable-android-autofill-accessibility

**Comment by kspearrin** [comment]
Did you the Bitwarden  auto fill service?

**Comment by PalmArchive** [comment]
Yes. It works in apps.

**Comment by danielpo** [comment]
Same issue here, not working in Chrome 71 or Chrome beta. I tried setting the flag, auto fill in apps and Firefox works.

**Comment by ozolli** [comment]
Tested today the autofill framework on a Huawei Mate 10 Pro, Android 9 and Bitwarden or Dashlane with Chrome Bera or Firefox Beta.
Each of the 4 combinations has the same issue : It works on 1 or 2 sites then I have to restart the browser to make it work again. Looks like an Android 9 bug...
