### ISSUE TITLE
[Version 2024.4.0] Unlock with PIN function doesn't work anymore

### ISSUE THREAD

**Issue by lflaurflorin** [bitwarden/mobile#3203]
### Steps To Reproduce

1. Go to 'SETTINGS' (Bitwarden Android App)
2. Click on 'ACCOUNT SECURITY'
3. Scroll down to 'Unlock with PIN code'
4. Enable it and set a PIN

Opening the app and using the set up PIN won;t be recognized (PIN incorrect error)
This used to work in previous versions.

For the moment the Fingerprint option unlock still works, I am using it at the moment, 
but I think it is less secure than PIN. Hopefully the source of the bug can be identified.

Thank you for this wonderful product and service!

### Expected Result

The PIN that was set up was supposed to unlock the vault.

### Actual Result

The <PIN Incorrect> message is displayed, even if the correct PIN that was set up, is supplied top the app. Internet connection is also active.

### Additional Context

I tried the latest beta version in Android as of today.
I also tried the latest stable version as of today.
The issue appears in both versions.

### Operating System

Android

### Operating System Version

Android 14

### Device

Samsung Galaxy A53

### Build Version

Version 2024.4.1 (10283)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hello @lflaurflorin,

Thank you for reporting this. I tested this on Android 12 with Bitwarden 2024.4.0 (Google Play Store) by configuring a PIN (1234) and deactivating (Unlock with biometrics) and then dismissing Bitwarden from the background; Afterwards, I was able to unlock Bitwarden using the PIN (1234) as expected. I recommend that you try this out in a fresh new installation on the latest stable version; Please uninstall Bitwarden off your device, turn the phone off and back on, and then install Bitwarden anew from the Google Play Store.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by alexisshaw** [comment]
Hi,

I would like to report the same issue on my samsung S24 ultra with the same version.

**Comment by DunklerPhoenix** [comment]
I have the same problem under android

**Comment by pamperer562580892423** [comment]
@SergeantConfused Hi, I think something got mixed up here. I encountered the issue myself with the BETA (!) on Android 13. You seem to have tested it with the last release (2024.4.0) while @lflaurflorin wrote the problem occurred on 2024.4.1 = BETA, though didn't check the "pre-release/Beta" field...

The issue seems to be related to the beta...

I'm on a Fairphone 5 and still on Android 13. And this issue caused me deinstalling the beta more or less immediately.

**Comment by pamperer562580892423** [comment]
... but, there is also another open issue (https://github.com/bitwarden/mobile/issues/3214), where others (and me) describe the same issue, so this issue here maybe can remain as "closed" because it is a "duplicate"...
