### ISSUE TITLE
TOTP code can be viewed without entering the master password when 'Master password re-promt' is enabled

### ISSUE THREAD

**Issue by jonnykl** [bitwarden/mobile#3206]
### Steps To Reproduce

1. Enable 'Master password re-promt' for an item
2. Save the item
3. Open the item

### Expected Result

The TOTP code should not be visible until the master password has been re-entered.

### Actual Result

The TOTP code is shown without the need to re-enter the master password. But if you want to copy the TOTP code, you have to re-enter the master password. This makes no sense as the TOTP code is already visible at this point.

### Additional Context

I noticed the same behavior in the Chrome extension.

### Operating System

Android

### Operating System Version

Android 14 (Xiaomi HyperOS 1.0.3.0.UMOEUXM)

### Device

Xiaomi Redmi Note 12 Pro 5G

### Build Version

2024.4.0 (10172)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by micahblut** [comment]
@jonnykl thanks for reporting. We have a similar report [here](https://github.com/bitwarden/mobile/issues/2336) that we are tracking. I will go ahead and close this report.
