### ISSUE TITLE
Constant crashes using Android application.

### ISSUE THREAD

**Issue by ZwjZUXItuXES6lwrCxJppln1PLEt2F0AXylSZYk** [bitwarden/mobile#3207]
### Steps To Reproduce

1.	#### **Install the OS**

	#### **Fairphone FP4**

	*	https://fairphone-android-builds.ams3.digitaloceanspaces.com/FP4/A13/FP4-TP2D-factory.zip or
	*	https://calyxos.org/install/devices/FP4/linux/#run-device-flasher

	#### **Google Pixel 3**
	
	*	https://fairphone-android-builds.ams3.digitaloceanspaces.com/FP5/A13/FP5-TT4C-factory.zip or
	*	https://calyxos.org/install/devices/blueline/linux/#run-device-flasher

1.	#### **Install the Bitwarden AOSP package**

	*	https://www.apkmirror.com/apk/bitwarden-inc/bitwarden-password-manager/bitwarden-password-manager-2024-4-1-release/bitwarden-password-manager-2024-4-1-android-apk-download/ from https://play.google.com/store/apps/details?id=com.x8bit.bitwarden&hl=en&gl=US
	*	https://github.com/bitwarden/mobile/releases/download/v2024.4.0/com.x8bit.bitwarden-fdroid.apk from https://mobileapp.bitwarden.com/fdroid/repo/com.x8bit.bitwarden-fdroid.apk

	https://github.com/bitwarden/mobile/releases/download/v2024.4.0/Bitwarden.iOS.zip is unaffected, alongside the alternative clients:

	*	https://github.com/bitwarden/clients/releases/tag/web-v2024.4.1
	*	https://github.com/bitwarden/clients/releases/tag/desktop-v2024.4.1

	

1.	Login with the account identified by the fingerprint phrase `overuse-definite-poach-almanac-dorsal`.

### Expected Result

I expect to be able to utilize Bitwarden with the same speed I would any other account.

### Actual Result

I am informed every 5 seconds that Bitwarden has crashed.

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/42837531/41110354-d867-4b76-ad85-57826b5f0ea2

<details>

> ![image](https://github.com/bitwarden/mobile/assets/42837531/46349ed8-5dcb-47dd-a738-b24e72b996be) 

</details>

### Additional Context

I have +2056 vault entries, which appears to be the sole differentiator between my account (which is affected) and others' accounts, which aren't affected, even on the same device and installation. I've limited my https://vault.bitwarden.com/#/settings/security/security-keys to 5000 (the minimum available) yet this didn't modify the behaviour whatsoever. https://github.com/AChep/keyguard-app/releases/download/r20240417/androidApp-none-release.apk does not display this behaviour, although it struggles to synchronize my vault.

I've included a https://developer.android.com/studio/debug/bug-report#bugreport at , because https://source.android.com/docs/core/tests/debug/read-bug-reports#event-log indicates that it might be useful.

### Operating System

Android

### Operating System Version

`androidapp://com.android.settings` reports:

> ```txt
> FP5.TT4C.A.154.20240320
> ```

### Device

Fairphone FP5

### Build Version

https://github.com/bitwarden/mobile/releases/download/v2024.4.0/com.x8bit.bitwarden-fdroid.apk

### Beta

- [ ] Using a pre-release version of the application.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bitwarden/mobile/issues/3207#issue-2363251435

Because this was migrated by a mannequin rather than via the standard mechanism, I have lost the ability to modify the issue's content and close/reopen it.

However, we can close this as remediated now that the new client has been released – it completely remediates the problem for me.

It's like I've purchased a new phone.
