### ISSUE TITLE
Use of new API to use the autofill API with bitwarden

### ISSUE THREAD

**Issue by heubergen** [bitwarden/mobile#322]
See https://developer.apple.com/documentation/security/password_autofill/ (Integrate a Password Management App with Password AutoFill) and https://twitter.com/1Password/status/1003824297725460481

**Comment by kspearrin** [comment]
We will have to wait until Xamarin supports iOS 12.

**Comment by crenwick** [comment]
Adding this for documentation: Xamarin's iOS 12 support is now in preview, with [autofill listed as a supported feature](https://docs.microsoft.com/en-us/xamarin/ios/platform/introduction-to-ios12/index#autofill-credential-provider-extensions).

**Comment by Geczy** [comment]
@kspearrin any update? Xamarin supports autofill

**Comment by jwheeler91** [comment]
Looking forward to this too :D

**Comment by kspearrin** [comment]
@bearinsun I haven't started on it yet. Waiting on other apps to figure out the best ways to implement it for reference and then I'll have a look at what they did.

**Comment by tcelestino** [comment]
@kspearrin I've been reading about it here: https://www.macrumors.com/2018/09/17/password-managers-autofill-password-support/

**Comment by kspearrin** [comment]
Found this video explaining how it all works: https://developer.apple.com/videos/play/wwdc2018/721/

Seems relatively simple. I'll start working on this soon.

**Comment by Cantello** [comment]
Good to hear, Apple's implementation appears to be simple for the user... :-)
(subscribed to premium today to give small incentive to develop things like this)

**Comment by kspearrin** [comment]
I got the basics of it working this afternoon. Check it out:

![autofill](https://user-images.githubusercontent.com/1190944/45845141-47f2c480-bcf2-11e8-85b4-984345ff8daf.gif)

**Comment by jwheeler91** [comment]
Fantastic!

**Comment by MarcReckel** [comment]
Fantastic! i know no other dev who says "i'll start working ot it soon" just to have it done the following day or so :D

**Comment by kspearrin** [comment]
I finished building the autofill implementation this morning. It now works with the quick type bar too. Check it out:

![autofill2](https://user-images.githubusercontent.com/1190944/45893006-e422d700-bd97-11e8-9437-f2f485c231a2.gif)

This should be available in the next app release. Next week maybe?

**Comment by Geczy** [comment]
Woo 🎉 !! Looks great. Is there a beta version we can test with?
