### ISSUE TITLE
Doesn't work at all - Galaxy S5 - Firefox 6.0.1

### ISSUE THREAD

**Issue by RickkeeC** [bitwarden/mobile#323]
Neither the Android App or Firefox Extension works at all.  Visit any web page with login, nothing happens.  From the App, "cannot fill, copy password instead".  From Firefox Add-On, nothing.  Click on options three dots at the top, open Bitwarden, it takes me to View item.  Click on -> to go to website,   It opens the web page, but I only see non-relevant choices for search captured from something else.  Turned off suggestions, it still gives dopy suggestions, nothing happens for password.  Maybe its Bing search engine forcing choices?
Anyhow, LP subscription expired today and it doesn't look like this will work for my phone.  Disabled firefox password save option.  Nothing, nada, zip.  - 1.5 hours of my life, gone.  :(
-->

**Comment by kspearrin** [comment]
Could you provide an example website that isn’t working so I can check? Also not sure what Firefox version 6 is? Did you mean 60?

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
