### ISSUE TITLE
Bitwarden cannot be used for passkey authentication on mobile

### ISSUE THREAD

**Issue by platnub** [bitwarden/mobile#3237]
### Steps To Reproduce

1. Go to any website and authenticate via passkey
2. Bitwarden will not show up to authenticate passkey. Both the mobile app and browser extension don't work on mobile

### Expected Result

Bitwarden opens to authenticate passkey

### Actual Result

Either the local phone passkey authentication system open, or it straight up fails the passkey authentication immediatley

### Additional Context

I am using Firefox 125.3.0 and I have tried the Bitwarden mobile app and the extension that runs in Firefox

### Operating System

Android

### Operating System Version

13

### Device

OnePlus 9 Pro

### Build Version

2024.4.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by danielesegato** [comment]
I've the same issue with Chrome and Android + Bitwarden

I've successfully setup Passkey for my Github account but when I try to use it:

1. I select sign in with passkey on Github
2. Chrome show me the device and I click continue
3. I get the passkey check on my device
4. I continue there
5. bitwarden opens up and I unlock it with biometric
6. I chose Github in bitwarden
7. I insert my password in bitwarden (master re-verification for Github)
8. the browser on Github inform me the authentication failed
