### ISSUE TITLE
Cannot Generate a password, only passphrase.

### ISSUE THREAD

**Issue by CIAIT** [bitwarden/mobile#3243]
### Steps To Reproduce

In the Microsoft Edge - Bitwarden app:
![image](https://github.com/bitwarden/mobile/assets/105372553/c250c115-eacf-4732-b99e-3433e44e979c)

When using the password/passphrase generator, I cannot choose the password option. When actually clicking the password option, it generates a passphrase.  This is regardless of what we have set for our corporate settings (we allow both).

The problem with passphrases is when some sites dont support high character counts, a passphrase can sometimes be less useful, and require manual character removal. This makes auto-saving the password not work.

Here is a video showing the problem:

https://app.screencast.com/tBFr8XT0u3Xno

This is a screenshot of our current password generate policy for reference:

![image](https://github.com/bitwarden/mobile/assets/105372553/7eba3586-8c60-41cf-a735-2df3180119ef)

Thank you,

### Expected Result

If choosing password, it should still generate a random character password, not a passphrase.

### Actual Result

It keeps generating a passphrase.

### Screenshots or Videos

https://app.screencast.com/tBFr8XT0u3Xno

### Additional Context

Windows, MS Edge Chromium (latest build), Bitwarden v2024.4.2 (Server v2024.4.2).

### Operating System

Android

### Operating System Version

Windows 11 Enterprise/Pro

### Device

Windows

### Build Version

2024.4.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Adedamola-Aina** [comment]
hello @CIAIT 

I am unable to reproduce this issue, If you have more information that can help us, please add it below. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

Thank you.
