### ISSUE TITLE
app is slow and stutters here and there

### ISSUE THREAD

**Issue by userforsource** [bitwarden/mobile#3246]
### Steps To Reproduce

I am recently using proton pass which smooth as butter where as bitwarden is too stuttering while using not that smooth

### Expected Result

Make it smooth

### Actual Result

Does android app for bitwarden a electron app

### Operating System

Android

### Operating System Version

android 11

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.4.0 (10172)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hello there,

Have you tried reinstalling the Bitwarden app?

**Comment by userforsource** [comment]
Done.
But no success.

**Comment by userforsource** [comment]
https://github.com/bitwarden/mobile/assets/162728301/be04990e-6963-4692-af90-d75b68315b2f


https://github.com/bitwarden/mobile/assets/162728301/4111b603-bbe5-4d26-8144-5036b2ef45f9

This are the 2 simple approch i can send you proton pass also which is smooth as butter.

**Comment by Krychaz** [comment]
The provided recordings look correct. I do not see any stutter.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
