### ISSUE TITLE
Android: Passkeys don't work with Mastodon

### ISSUE THREAD

**Issue by kyrias** [bitwarden/mobile#3254]
### Steps To Reproduce

1. Go to a Mastodon instance (e.g. https://mastodon.world/)
2. Click log in
3. Fill in e-mail and password
4. Click on 'LOG IN'
5. Click on 'USE SECURITY KEY'

or

1. Go to a Mastodon instance where you're already logged in
2. Go to Settings -> Account -> Two-factor Auth
3. Click on 'Edit' next to 'Security keys'
4. Type some name into the nickname field
5. Click on 'ADD NEW SECURITY KEY'

### Expected Result

You're asked to either select a Bitwarden pass key, or to save a new passkey in Bitwarden.

### Actual Result

It just offers the standard Google passkey implementation options.

### Additional Context

Using passkeys with Bitwarden works through the same Mastodon frontend on desktop Chrome with the Bitwarden extension.

Using passkeys with the Android Bitwarden app works on other websites through Chrome for Android.

### Operating System

Android

### Operating System Version

14

### Device

Pixel 8a

### Build Version

2024.4.1 (10283)

### Beta

- [X] Using a pre-release version of the application.

**Comment by kyrias** [comment]
I'd be happy to try whatever necessary to help debug this and provide whatever additional details are necessary.  I tried looking at what Mastodon passes to `navigator.credentials.create`/`.get` but couldn't really see anything that stood out to me as particularly strange.

**Comment by kyrias** [comment]
Ah, investigating some more it seems like the mobile app only supports using passkeys when `requireResidentKey` is `true`, whereas the browser extension doesn't have that limitation.

**Comment by SergeantConfused** [comment]
Hi @kyrias,

Thank you for this report. Yes, Android would not allow intercepting and storing a new passkey when ```requireResidentKey``` is ```true```; However, you should be able to use such a passkey from inside your individual Bitwarden account to log in on mobile, assuming you initially saved it via the browser extension. With regard to the fact that Bitwarden is not being shown as an option when attempting to pass the 2FA stage, that's expected as outlined in the [warning in the documentation](https://bitwarden.com/help/auto-fill-android/#setup-bitwarden-for-use-with-passkeys).

I will now proceed and close this GitHub report; Please feel free to [get in touch](https://bitwarden.com/help/) if you have any questions or concerns.

Thank you again,

**Comment by kyrias** [comment]
> Thank you for this report. Yes, Android would not allow intercepting and storing a new passkey when `requireResidentKey` is `true`; However, you should be able to use such a passkey from inside your individual Bitwarden account to log in on mobile, assuming you initially saved it via the browser extension. With regard to the fact that Bitwarden is not being shown as an option when attempting to pass the 2FA stage, that's expected as outlined in the [warning in the documentation](https://bitwarden.com/help/auto-fill-android/#setup-bitwarden-for-use-with-passkeys).

Ah, completely missed that note, sorry about that.  Is there any upstream Android ticket or similar about this that one can keep track of requesting this to be changed?  Because a website setting `residentKey` to `discouraged` shouldn't prevent the client from creating a resident key if it wants to.

But using a passkey that was saved using the browser extension doesn't work, so if you're saying that it's *supposed* to currently work then it seems like this is still a valid bug report?

**Comment by SergeantConfused** [comment]
Hi @kyrias,

Just to make sure that you and I are on the same page, by "a passkey that was saved using the browser extension doesn't work" you're referring to the FIDO2 Key that's used as 2FA in your first set of reproduction steps?

Thank you in advance,

**Comment by kyrias** [comment]
Correct.
