### ISSUE TITLE
Passkey selection not working on IOS with vault offline

### ISSUE THREAD

**Issue by pkinerd** [bitwarden/mobile#3262]
### Steps To Reproduce

4. Click on '...'

### Expected Result

Bitwarden pop allows selection of relevant passkey

### Actual Result

Password/passkeys selection hangs with spinner

### Screenshots or Videos

Go to website

![image](https://github.com/bitwarden/mobile/assets/169779439/27a50b04-c22e-4fef-ae3a-44f858f7566c)

Select bitwarden

![image](https://github.com/bitwarden/mobile/assets/169779439/d3c90983-0f60-4d18-aac4-7e0e6b5f3225)

Pass through faceid auth on bitwarden popup 

Get stuck on selection screen with spinner

![image](https://github.com/bitwarden/mobile/assets/169779439/bef8026b-de16-4407-b3ff-8308396865f1)

Switch to network with access to vault

bitwarden popup has no trouble showing relevant passkeys and passwords

![image](https://github.com/bitwarden/mobile/assets/169779439/75f216b7-1a0f-4839-8b74-622acd0286bd)

### Operating System

iOS

### Operating System Version

17.5.1

### Device

iPhone 15 Pro

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.5.1 (7674)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Adedamola-Aina** [comment]
Hi @pkinerd 

Your issue appears to be describing the intended behavior of the software. as after you selected the passkey you would still need the internet to login to the webpage. 

We use GitHub issues as a place to track bugs and other development related issues. 

This issue will now be closed. 
Thanks!

**Comment by pkinerd** [comment]
There was an internet connection - just no access to privately hosted vault.

I believe using bitwarden when the vault is inaccessible is supposed to be supported?

**Comment by pkinerd** [comment]
Hi @Adedamola-Aina 

My understanding is that bitwarden app should work even where the vault it is connected to is not available (as was the case in my original report).

I’m an engineer, this was not a clueless report of “I can’t login to website without internet” that you’ve indicated.

Your comment indicates you’ve misunderstood the context of the reported bug.

should we re open this?

**Comment by pkinerd** [comment]
Ultimately bitwarden mobile app storage needs an overhaul to support offline / remote / disconnected-from-vault use cases…

e.g. you can’t save changes to entries whilst offline, the above case of the ui locking up when trying to read passkeys.

**Comment by edwardgalligan** [comment]
> bitwarden mobile app storage needs an overhaul to support offline / remote / disconnected-from-vault use cases

I came here to open an issue about the above - @Adedamola-Aina what is the more appropriate action here? Should I open a fresh duplicate Github issue or will this one be re-opened?
