### ISSUE TITLE
IOS - It does not automatically fill in custom fields

### ISSUE THREAD

**Issue by Angel-Karasu** [bitwarden/mobile#3263]
### Steps To Reproduce

1. Go to a website that you have custom fields.
2. Click on autofill with Bitwarden

### Expected Result

It fills in custom fields

### Actual Result

It does not fill in custom fields

### Operating System

iOS

### Operating System Version

iOS 17.5.1 (21F90)

### Device

iPhone 12 mini

### Build Version

2024.5.1 (7674)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hello there, 

Due to mobile apps limitation, custom fields are currently not functioning with autofill on mobile devices.

**Comment by blunket** [comment]
This appears to have been implemented in a PR: https://github.com/bitwarden/android/pull/6243

**Comment by fkoemep** [comment]
@Krychaz please, would you kindly take a look at gryphon2411's PR? Or tell someone from your team to review it? This feature is a MUST for all systems and it's been stale for a long time now https://github.com/bitwarden/android/pull/6243
