### ISSUE TITLE
Autofill not works at all 

### ISSUE THREAD

**Issue by janos-szenfner** [bitwarden/mobile#331]
After the latest update the autofill not works at all. Not for Android browser or apps. 

Kind Regards, 
Szefi

**Comment by kspearrin** [comment]
Is it turned on?

**Comment by janos-szenfner** [comment]
Yes of course. It is miui 9.5.11.
Nothing changed only the upgrade.

**Comment by kspearrin** [comment]
Can you post a screenshot of Android Settings -> Accessibility?

**Comment by janos-szenfner** [comment]
Turned it off and on again. It solved the problem. Thanks.
