### ISSUE TITLE
OTP not copied into the clipboard for Twitter app

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/mobile#333]
Hi,
The OTP code doesn't work with the official Twitter app.
Android 8.1 - OnePlus 3T

[Video record](https://primokorn-drive.mycozy.cloud/public?sharecode=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGFyZSIsImlhdCI6MTUyOTY3NzYxMSwiaXNzIjoicHJpbW9rb3JuLm15Y296eS5jbG91ZCIsInN1YiI6ImVtYWlsIn0.4HOZu6w7c8mTxkHma7PGQ5a24WoUZ8ke18M8qYo2xOq9TF8BmIi9pHudeJB9KD1aRi4quo_GKG_pMbW5UF-1pA&id=349227e23138a888c71daae1fa68fec2)

Thank you.

EDIT: previous text removed.

**Comment by kspearrin** [comment]
I just tested https://www.forum-generationmobiles.net/login and it worked fine.

Your video is showing something with twitter, not https://www.forum-generationmobiles.net/login

**Comment by Primokorn** [comment]
Sorry I mixed up two things...
The problem is indeed with Twitter. The OTP is not copied into the clipboard.

**Comment by kspearrin** [comment]
Can you try v2.0 on play store beta? OTP copying should be working for both autofill services now.
