### ISSUE TITLE
Android beta - email field is case sensitive on login

### ISSUE THREAD

**Issue by BertoMejia** [bitwarden/mobile#3335]
### Steps To Reproduce

1. Try to log on with a car insensitive email
2. Pass captcha
3. It will show a wrong email and password message

### Expected Result

Should log in with case insensitive email. 

### Actual Result

Wrong email or password message with no indication that it may be case insensitive. 

### Additional Context

I always use my email with uppercase for the first letter of my name for legibility. When bitwarden saved my email it saved it in lowercase, so if I try the same email I originally typed, it will fail. 

### Operating System

Android

### Build Version

2024.6 1

### Beta

- [X] Using a pre-release version of the application.

**Comment by daniellbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
