### ISSUE TITLE
App crashes when trying to select and delete notes of vault item

### ISSUE THREAD

**Issue by Marius336** [bitwarden/mobile#3340]
### Steps To Reproduce

1.open vault
2. click on any vault item with a multi line entry in the notes 
3. click edit
4. Select everything in the notes field
5. Click the backspace key
6. App freezes 

### Expected Result

Field entries are deleted

### Actual Result

App freezes 

### Additional Context

App language is set to German

### Operating System

iOS

### Operating System Version

17.5.1

### Device

iPhone 15

### Build Version

2024.6.0 (7846)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hello @Marius336,

Thank you for this report. Does that Note field contain many dashes? I'm asking as I suspect that could be related to [this report](https://github.com/bitwarden/mobile/issues/3146).


Thank you in advance,

**Comment by Marius336** [comment]
Hi, It might be related tho I am not sure. Editing the field with larger notes and multiple dashes works fine, the app only crashes when attempting to select and delete the whole field at once.CheersMarius Am 29.06.2024 um 16:45 schrieb SergeantConfused ***@***.***>:﻿
Hello @Marius336,
Thank you for this report. Does that Note field contain many dashes? I'm asking as I suspect that could be related to this report.
Thank you in advance,

**Comment by SergeantConfused** [comment]
Hi @Marius336,

Thank you. I tested this on iOS 17.5.1 with Bitwarden 2024.6.0; I launched Bitwarden, tapped on Logins and then on a Login-type vault item with a large body of text (Lorem Ipsum), tapped on (Edit) and then on the Notes field, and tapped on (Select All) and then on (Backspace), and that did not cause Bitwarden to close unexpectedly; This was tested whilst the Bitwarden interface was set to English and to German. I would recommend that you test this with a fresh new installation; Please uninstall Bitwarden off your iOS device, turn your device off (long press) and back on, install Bitwarden anew from the Apple App Store, and test that once more.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket; Please also consider including a video screen recording of you reproducing this.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
