### ISSUE TITLE
I cannot login to Bitwarden for a few days. It is showing the error "Exception message: Connection failure".

### ISSUE THREAD

**Issue by VanillaTwilight123** [bitwarden/mobile#3360]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

Device: Redmi 3S Prime
Android version: Android 6.0.1 Marshmallow
ROM: MIUI Global 10.2 [Stable 10.2.2.0 (MALMIXM)]

Steps reproduce this error:
1) Download the latest version of Bitwarden app from the play store
2) Open the app and type in your Bitwarden email address
3) Click on Continue
Now you will see this error.

### Expected Result

I should be able to login to the Bitwarden Android app.

### Actual Result

I cannot log in to the Bitwarden Android app. The following error is showing---
"Exception message: Connection failure"

### Screenshots or Videos

![1721065454438](https://github.com/user-attachments/assets/7f28b272-1410-447a-84c7-3b471c33d4f5)

### Operating System

Android

### Operating System Version

Android 6.0.1 Marshmallow

### Device

Redmi 3S Prime

### Build Version

2024.6.0

**Comment by daniellbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by VanillaTwilight123** [comment]
Bitwarden is working absolutely fine on my Android 13 and Android 14 smartphones. It is also working fine on the Bitwarden website, the Bitwarden Windows app, and the Bitwarden Chrome and Firefox extensions.
But it is not working on the following device:

**_Device:_** Redmi 3S Prime
**_Android version:_** Android 6.0.1 Marshmallow
**_ROM:_** MIUI Global 10.2 [Stable 10.2.2.0 (MALMIXM)]

More elaborate steps to reproduce this issue:
Step 1: If you already have Bitwarden installed on your smartphone, then uninstall it first.
Step 2: Restart or reboot your device.
Step 3: Download the latest version of the Bitwarden app from the Google Play Store. Right now, the latest version of the Bitwarden app is 2024.6.0
Step 4: Open the Bitwarden app and type in your Bitwarden email address.
Step 5: Click on Continue.
Now you will see the error. The error is "Exception message: Connection failure". It was working fine a few weeks ago. But now I am unable to log in. Please solve this issue.

**Comment by VanillaTwilight123** [comment]
Hello. Is there any update on this matter? I am eagerly waiting. As a long-time happy Bitwarden user, I am disappointed for the first time. Some people in the Google Play Store are also complaining about this issue. Please do something and solve this issue. Thank you.

**Comment by VanillaTwilight123** [comment]
> I'm having the same issue on an older Samsung tablet. Works fine on tab s9, s8, pixel 8 & pixel 3a, but Tab S2 once I select bitwarden.com in the app login screen (opposed to.eu) it says Connection Failure (switching back to eu doesn't popup this error)then the password says it's incorrect, yet I can log in to other devices and web vault using the same credentials. No vpn, no adblock dns etc.

Yes. Someone on the Google Play Store also wrote that he cannot login to the Bitwarden app on his Android 7 device. It seems like the Bitwarden server has some issues.

**Comment by fredgolightly** [comment]
Only way I got around this was to export my vault, recreate an account on the .eu server and login using the eu way

**Comment by VanillaTwilight123** [comment]
> Only way I got around this was to export my vault, recreate an account on the .eu server and login using the eu way

Wow! It's a very good solution. Thanks for sharing with us. Let's see how long Bitwarden takes to actually solve this issue.

**Comment by CarloHD** [comment]
Me too
Huawei Mediapad M3 - Android 7 - Emui 5.0.4
When i try to login on the "bitwarden.com" server i get the same error

**Comment by VanillaTwilight123** [comment]
> Me too Huawei Mediapad M3 - Android 7 - Emui 5.0.4 Bitwarden App v. 2024.6.0 installed from PlayStore When i try to login on the "bitwarden.com" server i get the same error

Yes, a lot of people are facing the same issue. It's been a few days, but still no fix. It's unfortunate.

**Comment by aknighty74** [comment]
Same here. I can't log into the server. Any credential, even _test@bitwarden.com_, triggers this issue for me. My guess is there's some kind of unannounced incompatibility problem with devices that run older Android OS. This problem started a couple of days ago for me.

Bitwarden version: 2024.7.1 from Play Store.
Device: SM-G532M
Android version of the reported device: 6.0.1.

**Comment by bencew** [comment]
Same here.
Android: 7.0
BitWarden: 2024.7.1 (11086)

**Comment by aknighty74** [comment]
To add more info and narrow the problem further, I have found that this problem happens to me even if no internet connection is active.

**Comment by Doetje** [comment]
I seem to have the same issue on:
- Samsung Galaxy S21FE 5G (Android 14)
- Self-hosted bitwarden instance (up-to-date), behind Cloudflare (using CloudFlare SSL certificate issued by Google Trust)
- Valid Let's Encrypt ECDSA certificate (issued by their new "E5" issuer)

When connecting over wifi I bypass Cloudflare and connect directly, hitting the Let's Encrypt certificate. This **doesn't work** in the Android app (works directly in a browser, windows app, or the firefox app).

When connecting over 5G (so through Cloudflare) it **does work**.

This leads me to believe there are issues connecting to an endpoint using the newer Let's Encrypt certificates?

**Comment by hrshtein** [comment]
I am also facing the same issue, recently noticed that vault is not syncing on my secondary device, it failed to sync, it was showing that last sync was on 28 July. So i unistalled the app thought to relogin but when i download app from playstore it failed to log in.

Device- Oppo a57 (CPH1701)
Android version-6.0.1
App version- 2024.7.1, also tried 2024.6.0
![Uploading IMG_20240812_221943_649.jpg…]()

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. This is occurring due to a change in [Let's Encrypt's chain of trust](https://letsencrypt.org/2023/07/10/cross-sign-expiration.html); With that in mind, please check if you're able to update to a newer version of Android; If that is not an option, you can consider accessing your vaults through the [Bitwarden Web App](https://bitwarden.com/help/getting-started-webvault/) via the Firefox browser, as it uses its own trust store instead of the operating system's trust store.

This GitHub report will now be closed. If you have any questions or concerns, please feel free to [get in touch with us](https://bitwarden.com/help/) and please include a link to this GitHub report if you do.

Thank you all again,

**Comment by hrshtein** [comment]
Hii, is there any other option for people with old android version like to make it compatible with old android version or any other option like web app or legacy app?

**Comment by VanillaTwilight123** [comment]
Yes, there should be a way for older Android devices. Using web vault in Firefox on a device is honestly very bad. Bitwarden should do something.

**Comment by Christykitsune** [comment]
https://knowledgebase.geolantis.com/HOW%20TO/how-to-install-root-certificate-on-android-6-0-device/
Download these two chain of trust certificates and install them. This fixed my issue on my android 6.  
This is due to the certificates expiring.

**Comment by VanillaTwilight123** [comment]
> https://knowledgebase.geolantis.com/HOW%20TO/how-to-install-root-certificate-on-android-6-0-device/ Download these two chain of trust certificates and install them. This fixed my issue on my android 6. This is due to the certificates expiring.

Thank you so much. It has fixed the issue.

**Comment by CarloHD** [comment]
> https://knowledgebase.geolantis.com/HOW%20TO/how-to-install-root-certificate-on-android-6-0-device/ Download these two chain of trust certificates and install them. This fixed my issue on my android 6. This is due to the certificates expiring.

On my device even wirh those certificates installed still doesn't work

**Comment by doorssbm** [comment]
> > https://knowledgebase.geolantis.com/HOW%20TO/how-to-install-root-certificate-on-android-6-0-device/ Download these two chain of trust certificates and install them. This fixed my issue on my android 6. This is due to the certificates expiring.
> 
> On my device even wirh those certificates installed still doesn't work

Android 7.0, same issue after installing those two certs

**Comment by e-volusian** [comment]
Hi, I am also facing this issue. I realize these are very old versions of Android, but there must be tens of millions of these devices still in active use. Some kind of remediation steps would be nice 😞

**Comment by PaulMcF1987** [comment]
I am having the same issue
However my phone is a galaxy s22 running android 14 which i wouldn't say was an old version?

**Comment by Aspage** [comment]
Same problem here, with selfhosted Bitwarden on Debian and personal wildcard certificate (not letsencrypt, but official certificate).

Works great with browser, app and extension in Chrome and Edge. Does not want to connect through my Samsung Galaxy S23 Ultra.

Tried over internet and over local network. I have split DNS, so certificate should also work inside my own network.

Bit keep getting: exception message connection failure

**Comment by PEMtl** [comment]
> I've found the solution online, btw! I'm sorry, original solution-provider, but I don't remember your name or where I've found it.
> 
> The 'trick' for me, was to include all the certificates into the CSR you're using for Bitwarden. Even if it works with the app and in the browser, on Android it expects the fullchain certification.
> 
> Try that! It fixed it for me!

Sorry, but how did you do that? I don't see how.

**Comment by Aspage** [comment]
Are you using a custom certificate? If so, you had to upload the CSR, right?

You can just open the CSR and 'see' your certificate. Just copy/paste the other certifcates of the chain in there. You must've gotten those from your certificate provider.

**Comment by PEMtl** [comment]
> Are you using a custom certificate? If so, you had to upload the CSR, right?
> 
> You can just open the CSR and 'see' your certificate. Just copy/paste the other certifcates of the chain in there. You must've gotten those from your certificate provider.

@Aspage I use a free basic Let's Encrypt certificate on my web environment (OVHcloud), I haven't done anything else, and no special configuration. I tried to regenerate it but without success

**Comment by Mode3rn** [comment]
> https://knowledgebase.geolantis.com/HOW%20TO/how-to-install-root-certificate-on-android-6-0-device/ Download these two chain of trust certificates and install them. This fixed my issue on my android 6. This is due to the certificates expiring.

This did not work on an android 7 device, in which these certs were not installed. Bitwarden is still showing Exception Message : Connection Failure on the older version of the app
