### ISSUE TITLE
Can't scan and store passkey in iOS 18 public beta

### ISSUE THREAD

**Issue by MattisBeck** [bitwarden/mobile#3368]
### Production Build

- [ ] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

I want to add a passkey to bitwarden on my iPhone 15 Pro via the camera app, it recognizes it but I can't confirm it, so it doesn't save the passkey.

### Expected Result

store passkey

### Actual Result

didn't store passkey

### Screenshots or Videos

![grafik](https://github.com/user-attachments/assets/681acd09-2f26-4f7f-a816-d78c5c5cde67)

### Operating System

iOS

### Operating System Version

18.0 (22A5316k)

### Device

iPhonw 15 Pro

### Build Version

2024.6.0

**Comment by BBGhub** [comment]
Thanks for reaching out and sorry to hear about the trouble you are having. Please remember that beta versions of mobile operating systems are not targeted for official support. Using said versions may or may not lead to decreased functionality and are to be used at your own risk.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

**Comment by MattisBeck** [comment]
Hey,I know that using the beta is on my own risk. But eventually the beta will become public and then it probably still isn’t working and many more users will experience issues.On 1. Aug 2024, at 02:49, BBit ***@***.***> wrote:﻿
Thanks for reaching out and sorry to hear about the trouble you are having. Please remember that beta versions of mobile operating systems are not targeted for official support. Using said versions may or may not lead to decreased functionality and are to be used at your own risk.
We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
