### ISSUE TITLE
[Bug] Android app manually sync fails with server

### ISSUE THREAD

**Issue by sushantnadkar** [bitwarden/mobile#338]
It's almost a year I have been using Bitwarden App on my Android now, and even the latest update hasn't seemed to address the sync problem. Whenever I try to manually sync the vault with my account on regular Bitwarden server using the Sync option available in the settings tab, it always gives the message saying _Sync Faild_. I am facing the issue on Xiaomi Redmi Note 4 with  all permissions granted and the following specs:
- MIUI version: MIUI Global 9.5 | Stable i.e. 9.5.11(NCFMIFA)
- Android version: 7.0 NRD90M
- Kernal version: 3.18.31-perf-g08ef48a

**Comment by kspearrin** [comment]
Sounds like a networking problem. Does this happen on every network? How have you been using the app for over a year without being able to sync it?

**Comment by sushantnadkar** [comment]
Yes, this happens on every network.
I have been using Bitwarden on other platforms without an issue but, not on Android.

**Comment by k3davis** [comment]
I'm having a similar problem with the Android app; though it sometimes syncs as expected it usually does so only after a long delay and several timeouts. Inevitably the mobile app will require a clear of app data and a re-login which will perform a clean, successful sync. I've not had this issue on web vault, browser add-ons, or Windows app.

**Comment by sushantnadkar** [comment]
Looks like the issue exists with the Readmi mobiles, as the Sync function works properly in Vivo and Lenove mobiles that I have tested so far.

**Comment by ArrowComputingTech** [comment]
Android 8, Verizon Galaxy S7, won't sync manually or auto.
