### ISSUE TITLE
Inability to scroll to additional entries when site has multiple logins

### ISSUE THREAD

**Issue by TS6ix2GaH3q679h5** [bitwarden/mobile#3383]
### Production Build

- [ ] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Open BitWarden vault
2. “Search vault"
3. Type my search term
4. Results appear
5. **When more results are present than can fit the screen**, any below the current viewing area are cut off and inaccessible.

Seems like I could access them in theory (if the keyboard would get out of the way) but there seems to be no way for me to make the keyboard go away. Scrolling by touching the BitWarden credentials fields won’t scroll the visible ones enough to view those that are presumably at the bottom, hidden by the keyboard. 

I expected hitting “Search” on the iOS keyboard would remove the keyboard, but it permanently stays in this way. As the specific credential I need is “below” those visible, I can't access it. 

### Expected Result

Hitting “search” on the keyboard would remove the keyboard entirely. Or, I could scroll with my finger on the displayed credentials to reveal the ones below.

### Actual Result

I have no way of getting to the further credentials that are under the visible ones. 

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/e21eb46e-9f49-4bb9-bccc-89c3045821ba)

### Operating System

iOS

### Operating System Version

iOS 16 / iOS 17

### Device

iPhone SE

### Build Version

2024.7.1

**Comment by BBGhub** [comment]
Hi There!

Thank you for bringing this issue to our attention. We've confirmed that the issue with the iOS app exists in the legacy app but has been resolved in the upcoming native beta app, which is nearing its release.

To resolve this issue, we recommend trying out the beta version of our native app. You can join our beta program and download the app by following the instructions at this link: https://community.bitwarden.com/t/about-the-beta-program/39185  

Recent updates in the beta builds have addressed several issues, including the one you've encountered.

We appreciate your cooperation and encourage you to provide us with feedback on your experience with the beta version.

**Comment by TS6ix2GaH3q679h5** [comment]
Just confirming that this is fixed in the new Swift version of the BW app. Thanks guys!
