### ISSUE TITLE
IOS 18: Cannot create passkey

### ISSUE THREAD

**Issue by rveda** [bitwarden/mobile#3394]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. go to https://webauthn.io
2. Enter a username
3. click on register
4. click the continue button

### Expected Result

A passkey is created

### Actual Result

The contibue button flashes, but nothing happens

### Screenshots or Videos

https://github.com/user-attachments/assets/9907fd1a-5de0-4090-8a94-f03cf9f5f7da

### Operating System

iOS

### Operating System Version

18

### Device

Iphone 14 Pro

### Build Version

Version: 2024.7.1 (8086)

**Comment by msiqx9** [comment]
I had this exact problem until I updated the Bitwarden app to 2024.9.2 and it's now working perfectly on my iPad 10 on iPadOS 18 testing with WebAuthn.io

**Comment by rveda** [comment]
I updated my app manually now and the issue is indeed resolved in 2024.9.2

Closing this
