### ISSUE TITLE
Upgrade tls client version to 1.2/1.3

### ISSUE THREAD

**Issue by mqus** [bitwarden/mobile#340]
Today I installed the self-hosted binary of bitwarden_rs and all clients worked fine.
Only the mobile app threw a "There is a problem connecting to the server" pretty much immediately when I tried to login. 

After a while I found out that my reverse-proxy blocked the request:

```
Jul 12 22:53:54 myserver caddy[15936]: 2018/07/12 22:53:54 http: TLS handshake error from 12.34.56.78:42305: tls: client offered an unsupported, maximum protocol version of 301
Jul 12 22:53:54 myserver caddy[15936]: 2018/07/12 22:53:54 http: TLS handshake error from 12.34.56.78:42306: tls: client offered an unsupported, maximum protocol version of 300
```
It seems that the mobile app is still using TLS 1.0 (and even tried to use SSL 3.0). I can work around my specific error by configuring caddy (the reverse proxy) but TLS1.0 seems a bit insecure, even for sending already encrypted stuff.

Would it be possible to use/support TLS 1.2 or even 1.3?

**Comment by salquier** [comment]
Hi,

I've also had some problem with my SSL configuration on my reverse-proxy.
I've solve my problems by using the nginx configuration generated by https://mozilla.github.io/server-side-tls/ssl-config-generator/.

Btw, the app work with TLS 1.2.

**Comment by mqus** [comment]
Maybe it has to do with the Android version , I use Android 4.4.

**Comment by mqus** [comment]
I just researched a bit, this is indeed the case: 
https://github.com/ssllabs/ssllabs-scan/issues/258

With solutions mentioned [here.](https://github.com/auth0/Auth0.Android/issues/126)

**Comment by salquier** [comment]
Compatible but not enabled by default...
Solution for xamarin [here](https://stackoverflow.com/questions/33112340/how-do-i-enable-tlsv1-1-on-xamarin-android-api-16-19).

**Comment by kspearrin** [comment]
Can you try latest build here? https://ci.appveyor.com/project/bitwarden/mobile/build/artifacts

I added the mentioned fix using Play Services "Safety Net" for <= KitKat devices.
