### ISSUE TITLE
Auto-Fill does not work with SecureGo plus

### ISSUE THREAD

**Issue by devurandom** [bitwarden/mobile#3400]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

Check permissions and configuration in Android System Settings:
1. Ensure all permissions listed on https://bitwarden.com/help/auto-fill-android-troubleshooting/ are enabled:
   - Apps > Special app access > Display over other apps > Bitwarden > Shows "Allowed"
   - Accessibility > Downloaded apps > "Bitwarden" is listed as "On/Assist with filling username and password in other apps and on the web".
     - When opening the setting, "Use Bitwarden" is toggled "on"
   - Privacy > Accessibility usage > "Bitwarden" is listed
   - Passwords and accounts > Auto-fill service > "Bitwarden" is selected

Check configuration in the Bitwarden app on your Android device:
1. Press "Settings" in the bottom right corner
2. Press "Auto-fill"
3. Ensure all sliders in the "Auto-fill" section are toggled to "on":
   - "Auto-fill services"
   - "Use inline autofill"
   - "Use accessibility"
   - "Use draw-over"

Ensure there a password entry exists in the Bitwarden app on your Android device:
1. Press the "magnifying glass" icon in the top right corner
2. Search for "securego"
3. Press on the found item
4. Press the "pencil" icon in the bottom right corner
5. Scroll to "URIs"
6. Ensure there is an "URI" with value "androidapp://de.fiduciagad.securego.wl"

Reproduce the issue:
1. Issue a transaction on a bank account that is authenticated with the SecureGo plus app
2. Your bank will ask you to confirm the transaction using SecureGo plus
3. In the SecureGo plus app on your Android device, you will see a new transaction show up
4. Press "Accept"
   - (Once the transaction has finished loading and the "Approve" button has turned into the "Accept" button.)
5. SecureGo plus will prompt you to enter your "Authentication"
   - The input field is labelled "Authentication".
6. No auto-fill prompt will show up for the (password) input field
   - Any input is masked using big dots, like in a password input field.
7. The keyboard does not show an auto-fill option either
   - In other apps, both an overlay over the password input field and in the keyboard auto-completion bar would show.

Workaround:
1. Open Bitwarden, find the SecureGo plus password entry, copy the password into the clipboard
   - This makes it available to all apps, as far as I understand, which appears to be less secure than what the auto-fill feature would do
2. Return to SecureGo plus, long press into the "Authentication" input field, which opens the context menu, which allows to "Paste" the password

### Expected Result

I would expect both an overlay over the password input field and in the keyboard auto-completion bar to show for SecureGo plus' "authentication" input field.

### Actual Result

Neither an overlay over the password input field, nor an entry in the keyboard auto-completion bar show for SecureGo plus' "authentication" input field.

### Additional Context

SecureGo plus is: [de.fiduciagad.securego.wl](https://play.google.com/store/apps/details?id=de.fiduciagad.securego.wl) version 3.6.4

### Operating System

Android

### Operating System Version

13

### Device

Fairphone FP3 (non-plus)

### Build Version

6.A.030.0

**Comment by cbbit** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
