### ISSUE TITLE
iOS app gives "An error occurred" dialog box on login attempt to self-hosted server

### ISSUE THREAD

**Issue by spktkl** [bitwarden/mobile#3402]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Fresh download of Bitwarden app from iOS App Store
2. Choose a self-hosted server (Vaultwarden in my case) in "Logging in on"
3. Type email
4. Press continue
5. Type master password
6. Press "Log in with master password"

Alternately:

4. Use device logon button
5. Confirm on Mac OS app

### Expected Result

Successful login

### Actual Result

A dialog box appears with text "An error has occurred."

### Screenshots or Videos

![bitwarden-error](https://github.com/user-attachments/assets/16290531-caa1-4dcf-9f15-c94e31745953)

### Additional Context

I tried logging in on the iOS app multiple times to rule out email/password typos. Restarting the phone did not solve the problem, neither did swiping out of the app in the multitask screen and relaunching it. Bitwarden is the only enabled password manager on the device.

Using the same email and password, I logged in successfully via the Mac OS app, WIndows app, Chrome extension, and the self-hosted Vaultwarden web interface. The same iPhone is able to log into the web interface just fine at the same address, indicating it can see the server over the network.

This error has never appeared for me before, and the app was functioning as expected before today. I haven't made any changes to my Vaultwarden configuration in at least a month.

No messages appear in the Vaultwarden server logs from these login attempts. The nginx log shows only 1 line without any errors:

> 192.168.86.1 - - [01/Oct/2024:11:41:01 -0700] "POST /vaultwarden/identity/accounts/prelogin HTTP/2.0" 200 75 "-" "Bitwarden_Mobile/2024.9.2 (iOS 18.1; Model iPhone)"

### Operating System

iOS

### Operating System Version

iOS 18.1 beta (22B5034e)

### Device

iPhone 15 Pro

### Build Version

2024.9.2

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. It is important to note that Vaultwarden is not associated with Bitwarden. Vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organisation. 

The issue here will be closed.

Thanks!

**Comment by spktkl** [comment]
> Hi there,
> 
> 
> 
> I attempted to reproduce your issue and was unable to do so. It is important to note that Vaultwarden is not associated with Bitwarden. Vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organisation. 
> 
> 
> 
> The issue here will be closed.
> 
> 
> 
> Thanks!

I appreciate you looking into it. While I understand Vaultwarden is separate from Bitwarden, I do still believe the issue is within the iOS Bitwarden app, since Bitwarden clients on every other platform had no issues connecting, and there were no errors within Vaultwarden.

**Comment by fabiopicchi** [comment]
I am facing the exact same problem

**Comment by spktkl** [comment]
> I am facing the exact same problem

Do you mind sharing the details of what parts of your setup are the same? I've been trying to pick apart what the weak link is here, my best guess is the iOS beta isn't playing well with the Bitwarden app, but if you're on a different OS or have a different server setup that could help rule out some things.

**Comment by spktkl** [comment]
Well now I feel silly. I updated the Vaultwarden server from 1.30 to 1.32 and everything is working fine. Sorry for blaming you, Bitwarden.

**Comment by fabiopicchi** [comment]
For future generations... Turns out docker-compose down, docker-compose up doesn't pull the latest images even if you specify the latest tag in the compose yaml file. I manually docker pull'd the latest vaultwarden and everything works now... 

I was on a very old version.
