### ISSUE TITLE
iOS keyboard AutoFill doesnt match if URI is IP+Port

### ISSUE THREAD

**Issue by nicomerl** [bitwarden/mobile#3406]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Enable Bitwarden AutoFill in Settings
2. Configure Entry with IP+Port URI (e.g., 192.168.178.1:1000, 192.168.178.1:2000, 192.168.178.1:3000)
3. Create Bitwarden login and password entries for each Credentials, enter a URI, and set URI match to ‘host’
4. Navigate to IP1, IP2, IP3 and inspect the keyboard AutoFill suggestion that appears to the left of the key that invokes BitWarden’s pop up and to the entrys under key-icon on the right.

### Expected Result

Bitwarden Keyboard autofill should only match exact IP+Port as in URI.

### Actual Result

First Match in Autofill is just the First entry i can find for IP 192.168.178.1 -> Port is ignored.

If i Click the key-Icon, i get a List with all matching entrys for 192.168.178.1 -> Port is ignored.

If i Click Bitwarden in this list, FaceID opens to unlock vault. Bitwarden Matches IP+Port.
 
![IMG_0862](https://github.com/user-attachments/assets/4767356b-fd06-4482-a5da-79df018ed5eb)

### Additional Context

Tried with the new iOS 18 Passwords App and i cant get this Issue there. So my guess is, that this is an issue in Bitwarden.

### Operating System

iOS

### Operating System Version

18.0.1

### Device

iPhone 14 Pro

### Build Version

2024.9.2

**Comment by luc-bw** [comment]
Hi @nicomerl 

Thank you for the report. The repository for the native iOS application is https://github.com/bitwarden/ios.

This behavior seen here is expected. See our Help Center article, and specifically the "warning" under the Host option, for more info:
https://bitwarden.com/help/uri-match-detection/#host

Thanks!
