### ISSUE TITLE
Autofilo not working on Android 8.0.1

### ISSUE THREAD

**Issue by poltergeisha** [bitwarden/mobile#341]
The persistent autofill notification will not appear and the two scanning options don't seem to work now either. I've tried toggling them all on and off with no luck, and I tried uninstalling and reinstalling the app.

**Comment by Vistaus** [comment]
I can confirm this. Accessibility service is enabled, yet autofill doesn't work on my BlackBerry Key2 running Android 8.1

**Comment by TheRealNox** [comment]
Same here on a Pixel 2 XL

**Comment by fredgolightly** [comment]
We shouldn't have to run the accessibility service on <8.0; I'm on Pie (released yesterday) on a Pixel 2 and while Bitwarden works for apps it never and has never activated in Chrome, Brave, or Kiwi browsers. Is this something Google is working on (still, after announcing it years ago) or something Bitwarden has integrated with but isn't working on Android yet?

**Comment by RePacked** [comment]
Same here. I am running LineageOS, Android 8.1.0 on my Nexus 5X.

**Comment by insulind** [comment]
Same issue here using One plus 2.
Oxygen Is V 3.6.1
Android Version 6.0.1

It was working then suddenly stopped. I've made no charges to settings and all things that should be enabled are

**Comment by rob151515** [comment]
@kspearrin Chrome seems to work fine - if I minimise it and open it back up I get the prompt again. I also tested DuckDuckGo browser and that seems to work fine as well...

**Comment by kspearrin** [comment]
Sounds like a problem with Brave then. Try reporting it to them.

**Comment by regrettably** [comment]
I can't seem to get Bitwarden to autofill on any browser, even Chrome, despite both the Autofill service and the Accessibility service being enabled. I'm on Android 9.

**Comment by kspearrin** [comment]
@regrettably Android 9 support is in the beta. Try that.
