### ISSUE TITLE
Bypass Password through Persistent Notification

### ISSUE THREAD

**Issue by xHippoCrit** [bitwarden/mobile#342]
If I double tap on the persistent notification for autofilling, I am able to access all my stored details without needing my password.

I'm using a Pixel running Android 8.1.0

**Comment by kspearrin** [comment]
Hi,
I tried reproducing this and was not successful. What is your lock option set to?

**Comment by xHippoCrit** [comment]
Lock after 1 minute, using my full password and not a pin, and the persist notification.

**Comment by Tobirexy** [comment]
I can reproduce this issue on my device with Android 8.1.0, persistent notification, lock after 15 minutes and fingerprint.

**Comment by kspearrin** [comment]
I was able to reproduce it with password and PIN. looking into a fix.

**Comment by kspearrin** [comment]
Can you try the latest beta on google play (1.17.2) for a possible fix. I block spam clicking the notification now. https://play.google.com/apps/testing/com.x8bit.bitwarden

**Comment by Tobirexy** [comment]
Still works with the latest beta 1.17.2

**Comment by kspearrin** [comment]
@Tobirexy You probably don't have he latest beta. I literally just published it so it takes a bit to roll out. It should be build number 1479

**Comment by kspearrin** [comment]
Could also download the raw APK from here if you want to test: https://ci.appveyor.com/project/bitwarden/mobile/build/artifacts

**Comment by Tobirexy** [comment]
Just tested again. Still works with build number 1479.

**Comment by Tobirexy** [comment]
I tested it with fingerprint.

**Comment by xHippoCrit** [comment]
Tested on build number 1479, the bug still remains for me

**Comment by xHippoCrit** [comment]
Bug also works after restarting my device without having unlocked Bitwarden yet in the session (both on beta and stable builds), concerning that it can acccess my logins without a password (I thought they'd be encrypted locally as well)

**Comment by kspearrin** [comment]
Can you try 1480 for another possible fix?

@xHippoCrit On Android your key is stored in the Android Keystore, so it is not required to be entered to decrypt data like in other apps without protected storage.

**Comment by xHippoCrit** [comment]
Build 1480 appears to fix it for me.
@kspearrin Thanks for the explanation, it's reassuring

**Comment by Tobirexy** [comment]
Build 1480 fixed the issue for me too

**Comment by kspearrin** [comment]
Thanks all.
