### ISSUE TITLE
App closes when pressing the back button

### ISSUE THREAD

**Issue by Tobirexy** [bitwarden/mobile#343]
When I press my phone's back button in a folder or a settings window, the app closes. However, it should return to the previous screen.

OnePlus 5 with Android 8.1.0 (I tested this problem on other phones and could not reproduce it). 
I don't know if any other phones or apps have this problem as well, but BitWarden is the only app where I experience this. Maybe the issue is somehow related to Xamarin?

![image](https://user-images.githubusercontent.com/6097749/42749979-e24edd20-88e5-11e8-8241-1ed0b7a2236e.png)

**Comment by kspearrin** [comment]
I am not sure why. I can sue either button on my Nexus 5X on Android 8.1. Can you try the latest beta on play store?

**Comment by Tobirexy** [comment]
This was on the latest beta. I don't know why but the problem has resolved after a reinstallation! I will update you if it happens again.
