### ISSUE TITLE
Passkey support on native Android app

### ISSUE THREAD

**Issue by Molenaar2** [bitwarden/mobile#3437]
### Production Build

- [ ] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

Android 14, Bitwarden 2024.10.2

I have two accounts for UBank, Australia. Both accounts have a passkey defined. One account sits in my own vault, the other account sits in the organisation I belong to.

When I try to log in to the site in the UBank app, I get an error that the passkey operation failed, because the user could not be verified. In the previous non-native version I got a pop-up showing the two passkeys (unfortunately not the user IDs!) and I could select the passkey/account I wanted to use. With the new native version, due to the error, I can no longer login.

### Expected Result

Loved in via passkey with option which account to be used

### Actual Result

Error message that passkey operation failed because user could not be verified.

### Screenshots or Videos

My banking app doesn't allow to make screenshots

### Operating System

Android

### Operating System Version

14

### Device

Samsung Galaxy A34

### Build Version

2024.10.2

**Comment by lufee84** [comment]
Having same issues with Ubank with passkey even with single account.

Error has occured.

"passkey operation failed because user could not be verified"

Running current version 2024.11.1 with Andriod 14 (S24 Ultra)

**Comment by Molenaar2** [comment]
Duplicate of #3866 reported for the Android beta app. Closing this issue.

**Comment by seanf** [comment]
https://github.com/bitwarden/android/issues/3866
