### ISSUE TITLE
Unlock with pin option doesn't ask for pin confirmation

### ISSUE THREAD

**Issue by fredgolightly** [bitwarden/mobile#348]
In the app when selecting unlock by pin it asks for a new unlock pin, but it does not ask for this to be confirmed, thus mis-typing can easily lock you out - this needs to be accepted then confirmed by second entry.

**Comment by kspearrin** [comment]
If for some reason you mis-type your PIN you can always log out and back in with your master password to reset it. You won't be locked out.
