### ISSUE TITLE
Broken password length validation

### ISSUE THREAD

**Issue by larsks** [bitwarden/mobile#35]
I tried creating a bitwarden account using the Android application, and after entrying a 27 character password it told me that "my password must be at least 8 characters".

**Comment by larsks** [comment]
FWIW, the same password works fine via the web UI.

**Comment by kspearrin** [comment]
This is a weird one that I havent been able to reproduce. Does it happen with any password that you try of that length?

**Comment by kspearrin** [comment]
We fixed this in latest version.
