### ISSUE TITLE
Change Auto-fill Notification to low-priority

### ISSUE THREAD

**Issue by nkm8** [bitwarden/mobile#351]
Tested on Android P DP5 running a Pixel 2.  I use a Garmin fitness tracker that supports displaying notifications from third-party apps.  When I installed Bitwarden, this feature defaulted to on.

If an auto-fill notification opens, my fitness tracker (vivosmart HR+) was immediately spammed with at least a dozen instances of the Bitwarden auto-fill notifications.

I was able to fix this issue by manually disabling Bitwarden smart notifications in the Garmin Connect app.  However, it may be beneficial to change the auto-fill notifications to low-priority to prevent issues like this with other fitness trackers or Android Wear devices.

**Comment by IiroP** [comment]
I think it depends on the usage. Personally I like that the notifaction pops to screen as priority notification (without sound though).

But you can change the notification channel priority in settings? At least in Oreo it's possible, I haven't tried P though.

**Comment by nkm8** [comment]
@IiroP I don't think you can do this in Oreo, either (at least not without third-party work-arounds).  Bitwarden doesn't implement notification channels, so there is no way to change this behavior by default: https://www.xda-developers.com/notification-importance-controls-all-apps-android-oreo/

This behavior seems to have changed even further on P because I can't change the priority on any apps, including those that use notification channels.

**Comment by IiroP** [comment]
I have notification channels for Bitwarden... 🤔 Not sure if it's a beta feature though

**Comment by nkm8** [comment]
@IiroP Nevermind, you are correct.  The UI changed in P and isn't very intuitive, but you must tap on the channel to modify the settings (priority, sound, vibrate, etc.)

I was able to modify the auto-fill notification to be a low-priority notification manually, so this is not an issue.
