### ISSUE TITLE
Baconreader/android prompts to fill in passwords on "add a comment" screen

### ISSUE THREAD

**Issue by jeremymeyers** [bitwarden/mobile#357]
I would imagine this is applicable to more than just this one app but generally BW is asking to fill in a pw when trying to add a comment, and since there's no per-app way to disable BW it gets annoying real fast

**Comment by kspearrin** [comment]
This would only happen if the comment field is marked with the `TextVariationPassword` input type flag. Why they would do that in their app for a comment field, I have no idea.

**Comment by kspearrin** [comment]
Should be fixed next version. ref: https://www.reddit.com/r/baconreader/comments/autdvu/bitwarden_thinks_comment_replies_are_password/
