### ISSUE TITLE
Autofill for Zalando app in iOS

### ISSUE THREAD

**Issue by Schwitzd** [bitwarden/mobile#359]
Dear Dev Team,

I would like to report you that the autofill function is not working for Zalando App in iOS.

App version: 4.31.1
iOS: 11.4.1

Regards
Schwitzd

**Comment by kspearrin** [comment]
Can you link to the app? I don't know what the Zalando app is...

**Comment by Schwitzd** [comment]
Here the app link: https://itunes.apple.com/ch/app/zalando-shopping-und-fashion/id585629514?mt=8

**Comment by kspearrin** [comment]
Unfortunately I cannot download this app in the U.S.

What part of the autofill is not working? What happens?

**Comment by Schwitzd** [comment]
autofill is not working at all.
Attached the printscreen
![file 17 08 18 14 02 25](https://user-images.githubusercontent.com/20871459/44280482-316dcf00-a255-11e8-871e-a121dade59a6.jpeg)

**Comment by kspearrin** [comment]
I don't see the icon in this app indicating that it even supports autofill. We can't autofill if the app doesn't support it.

**Comment by Schwitzd** [comment]
Remove the app from the autofill list ;)
https://bitwarden.com/ios/

**Comment by kspearrin** [comment]
Done. Thanks!
