### ISSUE TITLE
Mobile: autofill doesn't work with Firefox 

### ISSUE THREAD

**Issue by kaasplank** [bitwarden/mobile#362]
Like the title says, autofill doesn't work with Firefox for android. I've tried the extension but it doesn't work either.

Thanks for making such a great app btw :)

**Comment by kspearrin** [comment]
It never had. Firefox on Android does not support accessibility services or oreo autofill. This is documented here: https://help.bitwarden.com/article/auto-fill-android/#troubleshooting-the-auto-fill-accessibility-service

**Comment by kumarharsh** [comment]
@kspearrin firefox 64 mobile supports Autofill now. https://github.com/bitwarden/mobile/issues/107#issuecomment-417586099

**Comment by krystian3w** [comment]
I can confirm, detect login pages on my phone with Oreo 8.0 and FX 64 (I have activated "oreo autofill" and choiced Bitwarden).
