### ISSUE TITLE
Auto-fill support for Brave browser (Android) 

### ISSUE THREAD

**Issue by jwsp1** [bitwarden/mobile#366]
Hi, any chance that brave browser gets auto-fill support? Would be very nice if you could add it, thanks!

**Comment by jwsp1** [comment]
Sorry - looks like it's already supported but I'm facing issues with the recognition of the password field (which then makes bitwarden displaying a notification). 
Looks like my Huawei force closes bitwarden after a while. I'll check my settings.

**Comment by Crocmagnon** [comment]
You could maybe add a link to the related issue here ? :)
