### ISSUE TITLE
Slow loading & Crashing on moto e5 Play (Android 8.0.0)

### ISSUE THREAD

**Issue by ian70203** [bitwarden/mobile#369]
When I'm unlocking my vault, the app gets slow and it sometimes crashes.

**Comment by ian70203** [comment]
This is a real problem that plagues my experience with bitwarden on mobile.

**Comment by kspearrin** [comment]
How large is your vault?

**Comment by ian70203** [comment]
131 logins and 5 notes.

**Comment by kspearrin** [comment]
Seems pretty small. Do you happen to have another Android device you could test on to see if the same problems occur there too?

**Comment by ian70203** [comment]
No, I don't. If it helps, I can provide CPU-Z screenshots.

**Comment by ian70203** [comment]
![screenshot_20181011-151602](https://user-images.githubusercontent.com/10983868/46828996-836d3580-cd6a-11e8-8220-a00c57f907f2.png)
![screenshot_20181011-151618](https://user-images.githubusercontent.com/10983868/46828997-836d3580-cd6a-11e8-825d-921fd167663d.png)
![screenshot_20181011-151623](https://user-images.githubusercontent.com/10983868/46828999-836d3580-cd6a-11e8-84f8-385604786495.png)

**Comment by kspearrin** [comment]
What version of android?

**Comment by ian70203** [comment]
8.0 Oreo

**Comment by kspearrin** [comment]
Unfortunately I don't have any good suggestions at this time. I haven't been able to reproduce this so it would seem isolated to your environment. We'll have to keep investigating.

**Comment by kspearrin** [comment]
One thing you could try is disabling the autofill accessibility service (if you're using that). Maybe that is causing some issue?

**Comment by ian70203** [comment]
The accessibility service is disabled already.

**Comment by ian70203** [comment]
For some reason, it fixed itself. I'll open another issue when it starts to act up.
