### ISSUE TITLE
iOS: Saving a Hidden Custom Type while it's displayed (eye crossed) permanently changes the field type to Text

### ISSUE THREAD

**Issue by maxrom** [bitwarden/mobile#372]
This happens on either first creation or later editing of the field. I can replicate it for Logins and Cards alike.

**Comment by dustindauncey** [comment]
Verified bug. I am also observing this same behaviour on latest iOS Bitwarden app version (1.21.0) with latest iOS version (12.1.3).

**Comment by kspearrin** [comment]
Should be fixed next version
