### ISSUE TITLE
Bitwarden suggests completion in unknown (not added web)

### ISSUE THREAD

**Issue by asier-gutierrez** [bitwarden/mobile#375]
When I enter some websites I get password completion suggestion even if I have not added any login details for that website.

There are many cases in which this happens. For example, at the website https://m.compradiccion.com (spanish website that aggregates and publishes online shop offers)

This makes me feel somehow worried because if this web can perform Bitwarden to suggest password completions, this could also be used for phising purposes.

I hope I could give you more technical details but since I do not know how Bitwarden works, I prefer not to give my opinion.

Many thanks for your aweasome work!

**Comment by kspearrin** [comment]
I’m not sure I understand the problem. What is a “password completion suggestion”?

**Comment by asier-gutierrez** [comment]
I get a notification telling that I have login details for that website

**Comment by kspearrin** [comment]
You will get the autofill notification on any website or app where a pasword field is encountered on screen. This would be expected if you are using the always scan option (default) under settings > options.

**Comment by asier-gutierrez** [comment]
I'm so sorry for wasting your time. The thing is that this rarely happens to me.
