### ISSUE TITLE
Bitwarden iOS app - can't connect to vault when using https connection

### ISSUE THREAD

**Issue by Haxy89** [bitwarden/mobile#376]
The newest web vault support only https (can't login on Chrome when http is using), but on iOS 12 is not possible to connect using self signed certificate so Bitwarden app is useless when server is using https.

Trying to connect in app get error: "There is a problem connecting to the server"

**Comment by kspearrin** [comment]
The iOS app should work fine with using a self signed certificate, if it is valid and trusted by the device.

**Comment by Haxy89** [comment]
How make it trusted? On iOS 12 there is no possibility to add certificate as trusted
