### ISSUE TITLE
iOS: AutoFill not working properly with the "Starts with" match detection option

### ISSUE THREAD

**Issue by vaganemm** [bitwarden/mobile#379]
If there are multiple accounts for a website (_example.com_) and one of these accounts (AccountX) works only on a specific subdomain (_subdomain.example.com_), because I have the "Starts with" option selected for the AccountX, then this account will be offered by the AutoFill even on the _example.com_.

But Safari extension works properly.

**Comment by emon5010** [comment]
Example:

1. First account (default match detection)
![3](https://user-images.githubusercontent.com/14804545/46164947-9b838600-c28f-11e8-976d-5f733c8a05b9.jpg)
2. Second account ("starts with" match detection)
![2](https://user-images.githubusercontent.com/14804545/46164945-9aeaef80-c28f-11e8-9101-2bce8967a2aa.jpg)
3. iOS AutoFill 
![1](https://user-images.githubusercontent.com/14804545/46164944-9aeaef80-c28f-11e8-9944-3e61db767bd3.jpg)
4. Bitwarden Safari extension
![4](https://user-images.githubusercontent.com/14804545/46164948-9b838600-c28f-11e8-83da-30729a256c8a.jpg)

**Comment by zzhhbyt1** [comment]
I think what the dev would like to say is that he can't control the way iOS choose which account is for this site for you.
Correct me if I'm wrong or close issue if I'm correct?
