### ISSUE TITLE
Stuck at "Verify PIN"

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/mobile#38]
Hi,

At the "_Verify PIN_" screen we are forced to enter the PIN code to open bitwarden.
Could you allow the **Back button** to simply close the app? At the moment, the Back button doesn't do anything.

Thanks.

**Comment by kspearrin** [comment]
Fixed with. https://github.com/bitwarden/mobile/commit/e970ca49e8f791786906bdcc5fc7c64e3eb31966
