### ISSUE TITLE
Chameleon Keyboard showing password

### ISSUE THREAD

**Issue by zer0byzer0** [bitwarden/mobile#380]
Hi!

I use "Chrooma - Chameleon Smart Keyboard" from "GameLounge - Keyboard and Loopsie app for Android" as my default keyboard app.
If you swipe up from the backspace key you delete the whole text in the current field an it shows this text as suggestion.
Normally password fields are not be shown only in the Bitwarden App the MPW appears.
My first thoughts were that this was a bug from the keyboard app.
So I tried this also in Firefox on different websites and in some other apps. I couldn't reproduce this behavior in any other app I've tried. Now I think it is maybe an issue on the MPW field in the Android app.

**Comment by kspearrin** [comment]
I am not sure why this keyboard would do that. The field is marked as a password field.

**Comment by zer0byzer0** [comment]
Thanks for the reply.
OK I'll try to get in contact with the keyboard app developers, maybe they know something about this.

**Comment by zer0byzer0** [comment]
no answer 🤷‍♂️ -> close
