### ISSUE TITLE
iOS 12’s new instant auto-fill doesn’t work (properly) in Firefox

### ISSUE THREAD

**Issue by frickenate** [bitwarden/mobile#381]
It works in Safari. However, in FireFox a primary auto-fill suggestion is never properly given. No matter what site I am on, the suggestion given is for my Firefox Sync account. ex: Open github login form, and the suggestion is my login for accounts.firefox.com, not github.

I took the URL off my Firefox entry and renamed it to not include the word “Firefox”, in case it was a precedence bug but now Firefox simply doesn’t suggest a primary one-tap login at all.

Is this a bug in Bitwarden, or a limitation of Firefox on iOS 12?

**Comment by kspearrin** [comment]
This is a Firefox problem. They need to properly integrate with iOS 12 autofill.

**Comment by frickenate** [comment]
You’re releasing new iOS features faster than Mozilla. And responding to GitHub issues in ~1 minute. You’re a beast. Thanks!
