### ISSUE TITLE
Behaviour After Security Information Updates

### ISSUE THREAD

**Issue by Adam-Antios** [bitwarden/mobile#382]
I updated my security by adding two factor authentication to my account, but I had forgotten about it. So I was trying quite a while to find out why the app couldn't sync to my web vault. Moreover I realised that for a long time I was using an old version of my web vault as all the newest passwords were not synced. 

The app itself didn't offer any warning that my information was updated so I could log in again from the app but it was working as usually, without of course having synced to the vault.

I don't think that this is the intended behaviour, is it? After the information gets updated I guess the app is supposed to alert the user or maybe log out, prompting him to log in again. At the very least a message should pop up that the security information has changed.

**Comment by kspearrin** [comment]
v2.0 has some improvements to log the user out on certain security events.

**Comment by djsmith85** [comment]
Hi @Adam-Antios, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
