### ISSUE TITLE
Auto Fill Not Working After Information Update

### ISSUE THREAD

**Issue by Adam-Antios** [bitwarden/mobile#383]
After I updated my security information and logged in the app again, auto fill no longer works at all.

It doesn't offer to auto fill on Firefox Focus, Firefox and Chrome.

Also after turning off auto fill, the app was still saying that it was still Enabled. No matter what I did I couldn't make it say Disabled.

**Comment by kspearrin** [comment]
Can you try v2.0 please?

**Comment by Ad-An** [comment]
I did try it today but I can't manage to get Bitwarden to autofill. Is this a general problem or am I doing something wrong?

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
