### ISSUE TITLE
iOS app exits while manual searching from keyboard during AutoFill

### ISSUE THREAD

**Issue by tomwassenberg** [bitwarden/mobile#386]
I really like the new AutoFill functionality from the keyboard on iOS. However, for some apps, no entry is proposed. I assume this is due to the apps themselves, or the domain that's present in the desired entry.

This wouldn't be a problem for me, but manually selecting the entry isn't working. When my focus is in the password field of the app, and I click on the "Passwords" button in the keyboard, Bitwarden opens the "Search Vault" view. When I then start entering my search term, Bitwarden suddenly closes before I've selected any entry and I'm back in my app without a password having been filled.

In more detail: Bitwarden closes after I've entered one or two characters in the search field. When it exactly exits, depends on what characters I start my search term with, and happens after I've stopped typing for half a second or so. I haven't been able to pinpoint it further than that.

**Comment by kspearrin** [comment]
Sounds like it's probably crashing for whatever reason. Are you able to scroll the list (without entering a search term) and select an item without issue?

**Comment by tomwassenberg** [comment]
> Are you able to scroll the list (without entering a search term) and select an item without issue?

Hadn't tried that (since I got too much stuff in my vault), but yes, that works without any issues. So it's the search where the crash is occurring.

**Comment by rggjan** [comment]
I can confirm this issue (works when scrolling, crashes when searching)...

**Comment by kspearrin** [comment]
Should be fixed in next version.

**Comment by tomwassenberg** [comment]
Thanks, it's fixed indeed in the latest version :)
