### ISSUE TITLE
Android app search doesn't work correctly

### ISSUE THREAD

**Issue by crackers8199** [bitwarden/mobile#388]
I had tried to search via folder name, but that doesn't work.  as a work around, I added my search terms to the notes for each item I wanted to see...but that doesn't work either.

**Comment by kspearrin** [comment]
The mobile app has limited/basic search features at this time. Read more about search here:
https://help.bitwarden.com/article/searching-vault/

**Comment by crackers8199** [comment]
that's kind of a big issue.  is there a timeline for when this will be available?

**Comment by crackers8199** [comment]
is there any plan to make the mobile search work the same as the web vault 
search? not being able to search folder names from within the app is a big 
problem for me...

**Comment by kspearrin** [comment]
@crackers8199 Yes, it is planned to eventually support search like the other apps.
