### ISSUE TITLE
TOTP Code doesn't show on Android app

### ISSUE THREAD

**Issue by ReeSilva** [bitwarden/mobile#390]
On Android app when I have a TOTP code configured for an account it doesn't show, also it doesn't show on Chrome app. It only shows on Web Vault and Linux app.

**Comment by ReeSilva** [comment]
Yes, I have. I'll give a try.

**Comment by ReeSilva** [comment]
Yeah, it works now. Was only logout and login back.

Thank you.

**Comment by anhofmann** [comment]
I had the same problem and was searching the Internet why on bitwarden for android I can't see totp data. Thanks for the hint, I was very irritated by this behavior and I would consider this as a bug.

**Comment by schurlinga** [comment]
This little hint should definitely be added to the [TOTP help page](https://bitwarden.com/help/article/authenticator-keys/)!

**Comment by mvdan** [comment]
@kspearrin please mention this in the help page. I purchased premium two weeks ago and I must have read that help page five times, but I still couldn't get TOTP tokens to generate on Android or Firefox. Almost to the point that I thought Bitwarden took my money and didn't give me Premium at all :)

It would also be nice if the upgrade to premium worked out of the box without having to log out and back in again. It took me ten minutes to do that across my devices, which is an unnecessary bump.
