### ISSUE TITLE
Oreo Autofill - Android Firefox support

### ISSUE THREAD

**Issue by ericschultz** [bitwarden/mobile#392]
Currently Bitwarden on Android doesn't integrate fully with Firefox on Android because it didn't support the Oreo Autofill framework. According to https://bugzilla.mozilla.org/show_bug.cgi?id=1330257, Firefox 63 (which is in beta), does support Oreo autofill. Perhaps it can be moved to a trusted browser in: https://github.com/bitwarden/mobile/blob/master/src/Android/Autofill/AutofillHelpers.cs?

**Comment by kspearrin** [comment]
We already have Firefox beta whitelisted there. Does it not work?

**Comment by ericschultz** [comment]
I doesn't work for me, no.

**Comment by arunsathiya** [comment]
I just tested on Firefox 63 for Android. The Bitwarden autofill doesn't appear on it.

**Comment by kspearrin** [comment]
Are you using android 9? I don’t think 8 is supported.

**Comment by arunsathiya** [comment]
Looks like you are right. 👍🏽I just checked and it turns out I am on Android 8.1.0.

**Comment by ericschultz** [comment]
I'm using Android 9 and the autofill doesn't work for me.

**Comment by marcinsmialek** [comment]
Firefox 64.0b6 here, Android 8.0 on Note 8 - Bitwarden works fine with just autofill service enabled, without accessibility service.

**Comment by ericschultz** [comment]
Hey, I noticed this has started working in the last week or so I'll close it. No clue what the cause was earlier.
