### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by Biepa** [bitwarden/mobile#399]
Hello,
in the german translation of the Vault the MasterPassword is always written as "Master-Passwort".
In the app I always see it written as "Masterpasswort".

So maybe we could change that "Masterpasswort" to "Master-Passwort " or the other way round (personaly i prefer "Master-Passwort") so that it looks the same.

**Comment by kspearrin** [comment]
Hi,
See here: https://help.bitwarden.com/article/localization/

**Comment by Biepa** [comment]
Some strings were already updated and the rest of them was updated by me:
Just need to be approved.
