### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/mobile#4]
- Finish implementing proper `AppResource` strings throughout the app.
- Find contributors to translate app into various languages.

**Comment by Igetin** [comment]
Will gladly help with the Finnish translation when the resource string system has been implemented.

**Comment by thomasbrunstrom** [comment]
I could help with translation to Swedish.

**Comment by uselessanim** [comment]
I'm a newbie, but i want to help with translation. If someone will show me from technical side how to do this, i will try to translate it to Russian.

**Comment by gaoyaoxin** [comment]
Glad to translate it into Chinese.
A sample file for translation is needed.

**Comment by kspearrin** [comment]
All AppResource strings have now been implemented. Resource files can be translated for new languages.

**Comment by nonintanon** [comment]
Im native Thai. Pls let me know if I can contribute to this proj.

**Comment by kspearrin** [comment]
All i18n can now be done. Please follow the contributing guide here if you want to help out. Thanks.  https://github.com/bitwarden/mobile/blob/master/CONTRIBUTING.md
