### ISSUE TITLE
Doesn't match URI without http prefix

### ISSUE THREAD

**Issue by a-m-s** [bitwarden/mobile#40]
If I have a site saved with only the machine name in the URI field then the Android app does not match it when filling web browser forms.

E.g.
  URI "cineworld.co.uk" does not match
  URI "https://cineworld.co.uk" is OK

This does not appear to affect the browser plugin, and in-app vault search finds it OK.

**Comment by kspearrin** [comment]
I have a possible fix for this in the next release.

**Comment by kspearrin** [comment]
You can try the new beta version and let me know if this is still an issue for you:

Get the beta here: https://play.google.com/apps/testing/com.x8bit.bitwarden

**Comment by a-m-s** [comment]
Confirmed fixed.
