### ISSUE TITLE
Auto fill option stopped working after a period of time and reinstallation does not fix the issue 

### ISSUE THREAD

**Issue by Syed-SoftwareTester** [bitwarden/mobile#401]
Device -  Blackberry Motion BBD100-1
Android version -  8.1.0 

Since first installing Bitwarden on my device, the auto fill option was working to begin with, but after some time the option stopped appearing and the only way to access my passwords is to manually switch out of the device and load bitwarden.

I have tried the different auto fill options to see if that made a difference and it didn't. I have also tried several reinstallations and that has also made no difference.

**Comment by kspearrin** [comment]
Can you check under Android settings to see if Bitwarden autofill and/or the accessibility service is enabled?

**Comment by Syed-SoftwareTester** [comment]
Yes that does seem to fix it, sorry ???? the option must've been reset during system updates.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
