### ISSUE TITLE
It doesn't work correctly with via browser

### ISSUE THREAD

**Issue by maple3142** [bitwarden/mobile#404]
Video: https://streamable.com/pk5g2
It should show accounts on `github.com` instead of `mark.via` app.

[Via Browser](https://play.google.com/store/apps/details?id=mark.via.gp)

**Comment by kspearrin** [comment]
You have to turn on the setting to show the URL in the nav bar. See https://github.com/bitwarden/mobile/issues/315#issuecomment-390729321

**Comment by maple3142** [comment]
![](https://i.imgur.com/PMhS68z.png)
It doesn't seem to work correctly even if it show URL in nav bar.

**Comment by maple3142** [comment]
Any response?

**Comment by maple3142** [comment]
@kspearrin I find that Bitwarden works well with Google Play version of via browser (`mark.via.gp`), but it doesn't work with China version (`mark.via`).
