### ISSUE TITLE
iOS Autofill with Bitwarden does not populate the newly added vaults 

### ISSUE THREAD

**Issue by kunxia** [bitwarden/mobile#405]
I've turned on the Autofill feature in iOS with Bitwarden app. After I add few new vaults in my Bitwarden and try the autofill, I don't see those newly added vaults populated (after the screen is switched from the current app to Bitwarden), however when I open the Bitwarden app separately, I can see all the vaults including the newly added ones. 
This issue goes away if I restart my iPhone, otherwise, it persists even I restart the Bitwarden app.

**Comment by kspearrin** [comment]
Try turning off autofill for Bitwarden under iOS Settings and then back on.

**Comment by kunxia** [comment]
I’ve actually tried this option before reporting the issue, still not refreshed.

________________________________

**Comment by mrkcee** [comment]
I am encountering the same issue as well. Turning off autofill does not refresh the list. Logging out and then logging in again in Bitwarden app does not also refresh the list.

My workaround is to add a dummy entry while in the iOS autofill screen and then exit. Then invoke the iOS autofill screen again.

iOS 12.1 on XS Max.

**Comment by briankung** [comment]
My wife is also encountering this error and @mrkcee's hack is the only way to get it working

**Comment by XuejinHuang** [comment]
Bitwarden does not update vault when in password autofill window. 
Opening the bitwarden app itself will update the vault.

**Comment by mexson** [comment]
This issue is quite annoying, I rarely use the IOS app since I mainly create my password on computer and use autofill in IOS to log in on websites. Each time I want to log in somewhere on my iPhone I have to first open the app, log-in, then go back and enter again my master password to retrieve the credentials to be auto-filled :-(
I think a simple "pull to refresh" gesture inside the autofill window would be a really great workaround !!

**Comment by lodgic** [comment]
> Bitwarden does not update vault when in password autofill window.
> Opening the bitwarden app itself will update the vault.

This does not work anymore on an iPhone Xr with iOS 13.5.1 Bitwarden Version: 2.5.0 (193)

**Comment by dozzman** [comment]
I’m also encountering the same issue, furthermore with the recent discovery of some apps stealing your clipboard contents I’m hesitant about copying and pasting my credentials directly from the Bitwarden app...

**Comment by AdamKearn** [comment]
Same I am still having issues, I have to uninstall the app and then redonload and setup the auto fill again.  Please fix.

**Comment by AdamKearn** [comment]
@kenijo are you still having issues with updated / new items in the volt are not showing on iOS autofill.

I have to completely uninstall he app and sing back in again for it to sync the changes to iOS autofill.

**Comment by urchersetawayedsho** [comment]
I am also still having this issue. I can go into the app itself and see the updated vault, but when I got to a form to autofill, it doesn't have the updated vault with the new login. It's like the autofill vault isn't synchronizing with the actual vault.

**Comment by kenijo** [comment]
> re you still having issues with updated / new items in the volt are not showing on iOS autofill.

I am not having the issue anymore but this is because:

- I went to the https://bitwarden.com/
- Emptied the items from the trash
- Went back to my iOS app
- Fully logged out (actually, I even deleted the app to be sure)
- Re-log in the app

The items in the trash show up in the iOS autofill vault only (not in the app itself) and it made me believe there was a sync issue.

**Comment by jebeaudet** [comment]
Same here on iPhone 11 pro, iOS 13.6.1. Any fix better than rebooting? Kind of ridiculous this has been opened for 2 years...

**Comment by nyuszika7h** [comment]
I'm experiencing this issue too on iPhone XR, iOS 14.0 beta 8. I was about to switch to Bitwarden but seeing this issue open and not fixed for 2 years is very disappointing.

**Comment by TayZ3r** [comment]
I have the same issue on iPhone XS Max with iOS 14. Is there any solution to solve this issue?

**Comment by jebeaudet** [comment]
Might be related to https://github.com/bitwarden/mobile/issues/980

I fixed it by setting the iPhone to english, trying to get more people to test that. Some people wrote they have their iPhone in a different language but nobody actually tested changing it and reporting it seems.

**Comment by nyuszika7h** [comment]
My iPhone was already in English. Changing the iPhone language does refresh the autofill logins because it triggers a respring. However, next time you save a new login the issue will appear again.

**Comment by AdamKearn** [comment]
I'm not sure if this is a limitation with Apple's autofill or just an issue with Bitwarden.

I have never used any other password manager, do other services like lastpass also have this issue?

Being as the Bitwarden app is open source anyone with a Mac might be able to change the code to implement this feature.

I would help if I could, but I don't have a Mac to do debugging with ;(

**Comment by nyuszika7h** [comment]
1Password tends to update with new entries automatically, although old entries sometimes get stuck until I go into the app and open the AutoFill section where it says "AutoFill passwords updating..."

Bitwarden doesn't even seem to use the native iOS login chooser UI at all so I don't see why it's an issue.

**Comment by AdamKearn** [comment]
@nyuszika7h Might be worth the Devs redesigning the auto fill interface then...

**Comment by jebeaudet** [comment]
@nyuszika7h thanks for reporting back. For me, going from French to English completely solved the issue, once the new entry has synced, it's visible from the auto fill.

I used lastpass in the past and didn't have a similar issue.

**Comment by wylel** [comment]
As posted in 1068 and on Reddit, clearing Safari History and Website Data fixes the issue after syncing the vault from inside the app.

My question is, why does Safari cache the autofill content? This fixed it for all apps.

**Comment by BryanC1968** [comment]
I am having this same issue happen to me...   I am using Bitwarden iOS App Version: 2.7.0 (358) on an iPhone 7+ with iOS Version: 14.2...  Autofill does not sync new or changed data from the Bitwarden Vault...  I have to clear Safari History and website Data to get it to update...  Does anyone know if there has been a fix for this yet or if it is still being worked on..?
