### ISSUE TITLE
URI input fields in Login items are not formatted best for entering URLs

### ISSUE THREAD

**Issue by jmot205** [bitwarden/mobile#406]
This is for the Android app. 

I'm not sure of the official terminology, but basically this relates to typing in the numbered URI fields in a Login item - URI 1, URI2, etc. When typing with a keyboard that has auto formatting options (I'm currently using SwiftKey, but this isn't specific to that keyboard), when I type the period to put in a .com, the keyboard applies autoformatting and puts in a space after the period and starts with a new capital letter, like typing a normal sentence. 

This autoformatting doesn't happen when typing directly in the URL bar of e.g. Chrome or Firefox, so I think it has to do with how the text input field is set up (e.g. like how some fields can be set up so that the keyboard knows it's a numerical input, and so the numpad part of the keyboard comes up by default - I'm guessing there's one typically used for URL fields, so that the keyboard knows not to apply any automatic formatting to what's typed in that field.)

**Comment by kspearrin** [comment]
The field is set to keyboard type "Url" with DisableAutocapitalize=true and Autocorrect=false . Does this happen whenever you try using another keyboard?

**Comment by jmot205** [comment]
Ah right, those definitely sound like options that should prevent this happening :/

Yeah, this behaviour also happens when I use Fleksy, for example. I've just now also tried with Gboard, and  it is behaving as expected (i.e. no auto formatting) with Gboard. 

One thing I also noticed when comparing the keyboard inputs just now is that when clicking into an empty URI input field, SwiftKey and Fleksy start with a capital letter, whereas Gboard starts with lower case, which kind of matches how the first two still apply autoformatting and the latter doesn't.

**Comment by kspearrin** [comment]
I am not sure why the keyboards are not respecting the input field flags. It sounds like a bug with the keyboard itself.

**Comment by jmot205** [comment]
Yeah, I originally asked because I thought maybe the flags weren't set for the URI field, and that's why it would act normally in Chrome and Firefox URL fields. But given that you've got the flags in there, it seems fair enough that it's just a bug in SwiftKey and Fleksy to not respect the flags.
