### ISSUE TITLE
Auto fill service doesn't work in Brave browser

### ISSUE THREAD

**Issue by PopeRigby** [bitwarden/mobile#408]
The prompt to unlock Bitwarden and have it fill in your password doesn't show up on any website in Brave.

**Comment by kspearrin** [comment]
Does brave support autofill services?

**Comment by PopeRigby** [comment]
I would assume so. It's based on Chromium and Chromium does if I'm not mistaken.

**Comment by leobel96** [comment]
I am running the last version of brave (1.0.69) on my android 9 smartphone and autofill works. Brave supports autofill and it should work also on you device.

**Comment by Zurandis** [comment]
I'm using the Brave browser on my Pixel 2 running Android 9 and the autofill works, but only the one where it shows up as a notification and you swipe down and select it.

**Comment by PopeRigby** [comment]
I'm talking about the built in autofill service that first started with Android 8

**Comment by leobel96** [comment]
For me it's like @Zurandis. I think it is the autofill service because the notification doesn't appear with Firefox that doesn't support autofill

**Comment by Moxville** [comment]
check below link
https://github.com/brave/browser-android-tabs/issues/619

**Comment by dunxd** [comment]
I'm using Brave version 1.3.2 which is based on Chromium 76.0.3809.132, running on Android Pie with August 2019 security update applied.

Today I tried some testing with the amazon.co.uk login page.

At first when I clicked on a login field, the Bitwarden icon appeared, and I could click it and login with my fingerprint, my amazon logins appeared and I could click on one to successfully complete the email and password fields!  Great. However, I then logged out and tried again and this time the Bitwarden pop-up did not appear.

I compared this to Chrome version 77.0.3865.73 and exactly the same issue.

This intermittence suggests to me that Brave does have the API.  But what is making it unreliable?

I have both the Auto-fill service and Auto-fill accessibility service enabled.  The Auto-fill accessibility service works more reliably, although it doesn't always detect the URL from my browser so I have to search for login.

**Comment by dunxd** [comment]
Just hunted around and it looks like this is a bug in Android versions older than Q at least affecting LastPass: https://issuetracker.google.com/issues/135571749 

Apparently it is fixed for Android 10 - don't know when I'll be able to test.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
