### ISSUE TITLE
Android app not syncing during autofill selection

### ISSUE THREAD

**Issue by needs-coffee** [bitwarden/mobile#409]
**Device:** Samsung S9 (SM_G960F)
**Android Version :** 8.0.0 (Oreo)
**Bitwarden app version :** 1.19.0 (1585) (current play store release)

There is an issue i have found on the mobile app whereby the vault does not sync when auto filling passwords. This has occurred via every app i have used to auto fill , with both the "Auto-fill service" and the "auto-fill Accessibility service".
If a password is changed on another client it syncs in real time between them (as intended). However if you then open an app on your device and click autofill -> the vault is opened and the login selected however the displayed and filled password is the previous one. 
This also occurs with adding fresh items as well as updating items as above. 
This resolves when the bitwarden app is opened nativity and syncs with the server. From then on the autofill is correct. 

**Steps to reproduce:**

1. close mobile bitwarden app
2. change password for an app (e.g. spotify) on the web vault + app website
3. Signout of the app on the mobile device 
4. sign in using the autofill service (fingerprint locked)
5. Old password will be filled by the service 

Would adding an automatic sync when the autofill service loads work ? 
Or is this already intended but is not working correctly? 

I have other android devices i will test this on when i have them to hand.

**Comment by JoeyKangaroo92** [comment]
[iOS Autofill with Bitwarden does not populate the newly added vaults #405]
(https://github.com/bitwarden/mobile/issues/405)
the above issue appears to be similar however on IOS instead.

I have tested this with:

- **Device: Samsung S6 (G920F) Android 7.** Syncs correctly when autofilling intermittently when there is no lock on the app. when a pin lock is enabled in the app the issue occurs as reported above.
- **Device: HTC M8 Android 5**. Issue as reported above both with and without pin lock.

**Comment by kspearrin** [comment]
Maybe your device is not receiving push notification updates? Try reinstall the app so that push is re-registered.

**Comment by JoeyKangaroo92** [comment]
I reinstalled on my main device while testing and the issue persisted - including several clear cache and data rounds
Both the other devices were tested with clean installs from the play store (both never had bitwarden on them and were clean android installs) all tested on a reliable WiFi connection (and cellular for the s9)

**Comment by Hejado** [comment]
I'm running Android 9 on a Nokia 7 Plus and I'm also experiencing this issue.

Push/Sync is enabled, but opening Bitwarden via the auto fill won't have a new entry. Going back and opening Bitwarden via the app drawer will at once show the new entry: I don't have to manually sync anything, which is why I think it's generally working.

**Comment by m3gg3** [comment]
Same problem here and I opened a issue at #457

**Comment by SgtReckless** [comment]
Update to this issue - still present but has a simple workaround :
- sync occurs correctly if the app is opened directly as expected
- sync does not occur if the app is opened via the autofill prompt/pane,
Problem is resolved by closing the autofill pane, opening the app directly and waiting for sync to complete (or forcing manual sync), and returning to autofill. 
also mentioned at - > #457 #490

perhaps a sync button in the autofill pane like the manual sync button in the main app?

**Comment by needs-coffee** [comment]
Stale issue - no longer a problem with recent releases.

**Comment by plantroon** [comment]
This problem persists. Could it maybe be dependent on vault login expiry settings?

> Update to this issue - still present but has a simple workaround :
> 
> * sync occurs correctly if the app is opened directly as expected
> * sync does not occur if the app is opened via the autofill prompt/pane,
>   Problem is resolved by closing the autofill pane, opening the app directly and waiting for sync to complete (or forcing manual sync), and returning to autofill.
>   also mentioned at - > [Password vault not syncing at every login #457](https://github.com/bitwarden/mobile/issues/457) [Sync not starting consistent at app start #490](https://github.com/bitwarden/mobile/issues/490)
> 
> perhaps a sync button in the autofill pane like the manual sync button in the main app?

This does not in any way solve the problem though, because there is no such problem when directly opening the app. The problem of autofill not triggering a sync remains.
