### ISSUE TITLE
TouchID on iOS - Fallback to device passphrase

### ISSUE THREAD

**Issue by Ardtas** [bitwarden/mobile#412]
On iOS Devices (App Version 1.19.4 (41)) you can bypass TouchID and use the normally much weaker device passphrase, if you enable unlock by TouchID.

To reproduce the problem:
- Enable TouchID in the Bitwarden iOS App
- Lock your database or let the auto-lock time pass
- Open your database
- Unlock via a not stored finger
- Press logout
- Now you can unlock your Bitwarden database via your device code

I think this is an unwanted way to unlock your database, since most people's device codes are only 4-8 digits and definitly weakens the security. I tried this on android (Nexus 5X, Android 8.1.0 (via LineageOS) , App Version 1.19.0 (1585)) too, logout instead leads to a logout in the Bitwarden app.
Sadly I have no FaceID device available, maybe someone else could try this out on one of the FaceID devices.

**Comment by kspearrin** [comment]
This seems like a pretty standard way of falling back from TouchID.

If someone knows the users passcode, they can easily just disable TouchID on the device anyways, along with decrypting the keychain and whatever else they want to do. The passcode is the thing that protects the device in the end.

**Comment by Ardtas** [comment]
Thank you for the answer. In the mean time, I have verified, that the same behaviour applies for the iCloud Keychain. I think the behaviour with android would be better in a security-wise way, but I think this is something that cannot be changed by a single application.

**Comment by luckydonald** [comment]
In the 1Password app 3x failing the TouchID causes you to enter the vaults password.

Also TouchID gets disabled after 24 hours of not using the app.

**Comment by luckydonald** [comment]
The 1password behaviour is to fall back to the actual vault password, which is much more secure than a 4 digit password which is the same as the device password.
The device password might already be known to the attacker as the phone is unlocked.

**Comment by Crocmagnon** [comment]
Well just set your device passcode to something more secure than 4 digits...
iOS defaults to 6 digits now I believe and you can always use a real passphrase with a full keyboard.
If you have TouchID or FaceID you will rarely have to type it anyway.
