### ISSUE TITLE
Fingerprint missing on Galaxy S9+ Android Pie Beta

### ISSUE THREAD

**Issue by rix1337** [bitwarden/mobile#413]
I have just installed the Android 9 beta on my Samsung Galaxy S9+.

The option to log in with my fingerprint/biometrics is gone.

**Comment by kspearrin** [comment]
This is a known issue at the moment. Should be fixed with https://github.com/smstuebe/xamarin-fingerprint/pull/116

**Comment by rix1337** [comment]
Thank you for the swift reply

**Comment by rix1337** [comment]
> If you want to give it a test in Bitwarden. Dev build APK with this update is available here:
> https://ci.appveyor.com/project/bitwarden/mobile/build/artifacts

**Comment by kspearrin** [comment]
Did it work?

**Comment by PalmArchive** [comment]
Confirmed working 👍

**Comment by rix1337** [comment]
Eagerly waiting for the stable release :+1:
