### ISSUE TITLE
Touch / Face ID lock has no passcode fallback

### ISSUE THREAD

**Issue by mahyar** [bitwarden/mobile#414]
You have to logout or take off whatever is covering your face, because your in a cold / polluted environment.

Other password managers let you fall back to imputing your PIN or password without having to log out fully.

I would suggest putting an 'insert password' button on the face id lock screen.

**Comment by kspearrin** [comment]
This should already be handled by the Touch/Face ID prompt. If it fails or you cancel the prompt you can fall back to the device's PIN instead.

**Comment by jacopo-j** [comment]
@kspearrin actually, no. The app should handle the passcode authentication if Face ID fails. As of now, you are left with the only option of logging out the app.

**Comment by RubenMeeuw** [comment]
It actually is falling back on the touch-id password. However I think this lacks security since you can now open your vault with a 4 or 6 character password instead of the master-password for the vault. Best would be if touch-id fails to fall back on the master-password. Correct me if I'm wrong.

**Comment by nashbridges** [comment]
@RubenMeeuw see https://github.com/bitwarden/mobile/issues/412

**Comment by RubenMeeuw** [comment]
@nashbridges Ah thanks, didn't see that thread. I knew that but still it is a security vulnerability. However out of the scope to be resolved by bitwarden alone ;)

**Comment by luckydonald** [comment]
In the 1Password app 3x failing the TouchID causes you to enter the vaults password.

Also you can't use TouchID after 24 hours of not using the app, it gets disabled automatically 

On my device I have a wonky home button, therefore I actually like the fallback to the short password. Still, forcing to use the vaults password instead of device methods after 24h of inactivity would be a nice security  addition to security.

**Comment by Crocmagnon** [comment]
> Still, forcing to use the vault's password instead of device methods after 24h of inactivity would be a nice security addition to security

I'd prefer this to be an opt-in, or something we can change the delay to "never". I sometimes don't use my password manager for more than 24 hours and I'd hate it to ask for my loooong passphrase everytime this happens.

**Comment by luckydonald** [comment]
@Crocmagnon please do, yes.

**Comment by Crocmagnon** [comment]
Sorry, I won't have time for this in the near future, plus it's not my request but yours ;)
Feel free to post in the relevant section of the community forum (I guess app:mobile), I'd be happy to add more info if needed.
Don't forget to link back to this issue for reference :)

**Comment by kspearrin** [comment]
Fingerprint + pin can now be used together in v2.0.
