### ISSUE TITLE
Autofill on Safari not working under certain circumstances

### ISSUE THREAD

**Issue by jacopo-j** [bitwarden/mobile#416]
When an item is saved with a password but without a username, Bitwarden fails to fill in the password if the autofill is prompted from the  "keyboard menu" instead of the "share" contextual menu.

Attachments:
[The "keyboard" menu does not work](https://imgur.com/kjvmroV)
[The "share" menu works](https://imgur.com/QCfQsKt)
[The password item](https://imgur.com/Tiu7c5a)

**Comment by kspearrin** [comment]
Yes, this is because iOS's autofill framework requires a username and password to work. Otherwise you will have the use the old share extension method.
