### ISSUE TITLE
Pixel 3 - Android 9.0: Syncing Fails At Intial Device Setup

### ISSUE THREAD

**Issue by morris-t** [bitwarden/mobile#418]
I have a Pixel 3 running Android 9.0 (November security update).

When first trying to login to Bitwarden, the app accepts my username and Password, it then goes to the TOTP code entry screen, it then seems to get stuck on "validating".

When the screen ties out, I then have to re-enter the password to unlock the app, sign-in appears successful, however there are now passwords. Manually initiating a sync leads to a "syncing failed" error.

I have tried wiping the app storage and logging in again and that doesn't work.

I have also granted all permissions.

I also have a Nexus 5X running Android 8.0, where syncing works fine.

**Comment by kspearrin** [comment]
Unfortunately I don't have any ideas at the moment. Is this with v1.20?

**Comment by morris-t** [comment]
Yes this is on 1.20.

Is there any way for me to view any Bitwarden logs that might be helpful?

**Comment by kspearrin** [comment]
@morris-t Not without having a rooted device or connecting it to Android Studio.

**Comment by morris-t** [comment]
It turns out this not a Bitwarden issue, it seems that on Android pie that some apps are affected by packet fragmentation, and some are not:

https://support.google.com/pixelphone/forum/AAAAb4-OgUsRBW3mz1I21M/?hl=by

At least in my case it seems to be caused by using a PPPoE modem with my router.

I haven't resolved this yet on my end, but in case anyone else comes across this issue with a similar problem, the below links may be a good starting point for finding a solution:

https://samuel.kadolph.com/2015/02/mtu-and-tcp-mss-when-using-pppoe-2/

https://community.ubnt.com/t5/EdgeRouter/No-Netflix-with-EdgerouterX/td-p/1934270
