### ISSUE TITLE
Force close on launch (Signature/MAC verification failed)

### ISSUE THREAD

**Issue by cawilliamson** [bitwarden/mobile#422]
Hey folks,

I've recently switched from Samsung Stock ROM on my note 9 to a Treble GSI image along with opengapps and so moved from 8.1 to 9.0.

With this change - Bitwarden (fresh install) crashes on launch with the error:

```android.security.KeyStoreException: Signature/MAC verification failed```

Some research on this makes me think it could be related to opengapps as was hinted to here:

https://github.com/bitwarden/mobile/issues/264

That having been said - this is a different error. Also to add to this - I am running the latest beta build from Play Store.

**Comment by kspearrin** [comment]
For whatever reason your revise is crashing when we try to access the Android KeyStore. Maybe you need to configure a biometric or PIN code or something on the device to enable the keystore properly?

**Comment by cawilliamson** [comment]
@kspearrin I have added a fingerprint already to the device already.

I've filed a bug report with the ROM maintainer and linked that over to this ticket and I'll update here if I make any progress.

**Comment by kspearrin** [comment]
Can you try v2.0 from play store beta?

**Comment by cawilliamson** [comment]
@kspearrin Yeah this has been resolved for a fair long time now. :)
