### ISSUE TITLE
input behavior for URL field on Android

### ISSUE THREAD

**Issue by MarcusWolschon** [bitwarden/mobile#423]
This is related to #406

When editing an existing URL, after every entered character the cursor jumps to the end of the input.
This makes it difficult to e.g. add a missing "https://" to the front of a URL.
It looks like a badly behaved TextView.OnEditorActionListener or TextWatcher that replaces the text every time instead of making any changes in TextWatcher. afterTextChanged by modifying the CharSequence parameter.

(It would also be really nice to have the URL fields pre-filled with "https://")

**Comment by kspearrin** [comment]
This seems to be happening in all fields.

**Comment by MarcusWolschon** [comment]
Any update on this?
It seems to still exist in the current Android app version after 4 month.

**Comment by danijelh** [comment]
Also here for this. A colleague of mine is really annoyed by this. Please fix :)

**Comment by kspearrin** [comment]
Fixed in v2.0
