### ISSUE TITLE
Connection problems with iOS App on locally hosted bitwarden server

### ISSUE THREAD

**Issue by seehma** [bitwarden/mobile#425]
Hi there,
I have setup a Bitwarden Docker Image on my Synology NAS. Unfortunately it works fine on the web interface and the Linux client (running on Arch Linux). The only problem i have is on the Bitwarden iOS App. I cant get this thing to work. It always says "An error has occured. - There is a problem connecting to the server."
I'am in my local WiFi network and on the same phone i can connect to the web interface of the Bitwarden server by using safari or Firefox (also with the same Username/Email and Password).
I don't use a SSL Certificate and the URL what i locally use is http://server:2000
On the Synology i used the mprasil/bitwarden Image. Any ideas whats the problem here?
Thanks in advance.
M.

**Comment by kspearrin** [comment]
Https is required.

**Comment by seehma** [comment]
ok, i assumed that. Any ideas how i can get https to work with that docker image?

**Comment by seehma** [comment]
Found that.
https://hub.docker.com/r/mprasil/bitwarden/#enabling-https

**Comment by kspearrin** [comment]
No, sorry. you should try contacting the authors or that project.
