### ISSUE TITLE
Android app doesn't auto-fill apps in my Android work profile

### ISSUE THREAD

**Issue by jikquantopian** [bitwarden/mobile#427]
I have a work profile configured on my Android phone for security reasons.

Bitwarden's auto-fill functionality appears to be completely non-functional when I am using an app in my work profile.

I am using the most recent Android on a Pixel 3 XL.

I've tested this in both Chrome and Expensify apps in my work profile. Bitwarden simply doesn't offer to auto-fill when I try to log in in one of these apps. in Chrome, I was trying to log into github.com, in Expensify, I was (obviously) trying to log into Expensify.

I tested exactly the same workflow in Chrome in my personal profile, and auto-fill worked just fine.

FYI, I tested this in four password managers other than Bitwarden. It works fine in LastPass, 1Password, and Dashlane and doesn't work in KeeperFill.

**Comment by kspearrin** [comment]
Which autofill service are you trying to use? Is the autofill service for Bitwarden properly enabled on the work profile?

**Comment by jikquantopian** [comment]
>Which autofill service are you trying to use?

I have autofill, accessibility, and draw over other apps all enabled for Bitwarden. Auto-fill only allows one app to be selected at a time, so obviously for that only Bitwarden is selected. For accessibility I manually made sure that Bitwarden was enabled and all the other password manager apps were disabled. I believe I had "draw over other apps" enabled for multiple password manager apps but I don't think that would matter.

>Is the autofill service for Bitwarden properly enabled on the work profile?

I don't follow your question. As far as I know there is no separate autofill service setting for the work profile. Are you sure there is such a setting, and if so, do you know how I can get to it?

(And just to reiterate, three other password manager apps are able to auto-fill without such a setting enabled, if there is one that I don't know about.)

**Comment by kspearrin** [comment]
I am not familiar with how Android profiles work, but I was suggesting that when you are in the work profile, go to Android's settings and confirm that the Bitwarden autofill services are indeed still enabled there.

**Comment by jikquantopian** [comment]
>I am not familiar with how Android profiles work, but I was suggesting that when you are in the work profile, go to Android's settings and confirm that the Bitwarden autofill services are indeed still enabled there.

Yes, your suggestion confirms that you are not familiar with how Android work profiles work. ;-)

There are no separate settings when you're in the work profile. As an analogy, you can think of Android work profiles as a way to run certain apps while sudo'd to a different user ID, while otherwise remaining logged in to your main user ID.

**Comment by jikquantopian** [comment]
Note: I just noticed today that although Bitwarden isn't displaying the pop-up directly over the app on my screen inviting me to auto-fill, it is displaying an Android notification I can tap to do it, so there's that.

**Comment by kspearrin** [comment]
The notification is part of the autofill accessibility service. The popup is part of the standard autofill service.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
