### ISSUE TITLE
iOS - Add credential, hitting Save with blank URI results in duplicate entries

### ISSUE THREAD

**Issue by luckman212** [bitwarden/mobile#428]
Repro:

- from an iOS app that requires login, tap "Bitwarden..."
- tap + to add credential
- fill out Name, Username, Password fields
- if URI field is blank, leave it
(if URI is not blank, clear it)
- tap Save

Result:

-  Nothing visibly happens; the form remains on the screen
- Behind the scenes though, an entry has been created with a blank URI
- You can keep tapping "Save" and additional duplicate entries will be added

Instead, an error message should be shown to inform the user that URI should not be blank. Or, if blank URI is acceptable, then edit form should close.

possibly related: #426

**Comment by kspearrin** [comment]
Should be fixed in next version.
