### ISSUE TITLE
Opera not supported anymore?

### ISSUE THREAD

**Issue by ponchofiesta** [bitwarden/mobile#435]
When Autofill started in 2017 Opera was one of the supported browsers on Android. I tryied it now and it didn't work. I tried the original Opera and Opera Touch. Bitwarden says always "com.opera..." and not the website domain.

Using Android 8 with accessibility service. Opera and Bitwarden from Play Store.

**Comment by kspearrin** [comment]
This is probably happening because the address bar disappears when scrolling down in opera. If the address bar isn't visible on screen, the accessibility service cant read the URL to know what website you are on. Is there a setting to keep the address bar visible.

**Comment by ponchofiesta** [comment]
Ok, this was the problem. It's working with a visbile address bar. thanks.

**Comment by ghaschel** [comment]
Still wont work with opera touch and visible address bar
