### ISSUE TITLE
Android: can I use bitwarden to store 2fa for evernote?

### ISSUE THREAD

**Issue by TheNetAdmin** [bitwarden/mobile#436]
Hi, I'm considering using bitwarden these days, but when I tried to add evernote 2fa to bitwarden Android, it's not working.

I scaned the Evernote 2FA QR code through bitwarden `add login`, it shows a long sequence of letters in field `Authenticator Key (TOTP)`, but I cannot find any 2FA code on the main page.

Maybe bitwarden is not compatible with Evernote 2FA? Or am I missing something?

**Comment by kspearrin** [comment]
You need a premium membership to generate the 2FA codes. See https://blog.bitwarden.com/premium-features-file-attachments-2fa-options-totp-priority-support-d4c12e2d9018
