### ISSUE TITLE
Android app doesn't work offline?

### ISSUE THREAD

**Issue by rlipscombe** [bitwarden/mobile#438]
If I log into Bitvault and then disconnect from the internet (no wifi, no 4G) and then hit log out, I can't log back in without reconnecting to the internet. Is this expected? I was expecting that my passphrase would be usable offline.

This makes Bitwarden impossible to use if I can't get connectivity.

**Comment by Crocmagnon** [comment]
Logging out destructs the data stored on your device, so when you try to log back in again the app (whether iOS, Android or browser) tries to sync to the server so yes, it's expected.

You can however lock your vault, which requires your passphrase to unlock and works offline. While offline, your vault is in readonly mode.

**Comment by rlipscombe** [comment]
Ah, OK. I missed that distinction. I wonder if it would be worth putting the Account options on a submenu, to make it harder to find that option, since it's sorta destructive.

**Comment by rlipscombe** [comment]
Closing as PEBCAK.
