### ISSUE TITLE
[Android] Verify Pin keyboard should restrict the on-screen keyboard to the numeric input type.

### ISSUE THREAD

**Issue by kvithayathil** [bitwarden/mobile#446]
As a usability/accessibility improvement - could the Verify Pin screen request the input type to be `numberPassword` (or Xamarin equivalent) so that the keyboard that appears is just nummeric digits?

I've attached an example to illustrate:

![numpad-pin_bitwarden](https://user-images.githubusercontent.com/1056073/51398680-3986af00-1b12-11e9-94b1-e31c448a1609.png)

**Comment by ShirokaiLon** [comment]
The input method is already set to Keyboard.Numeric, which is the closest Xamarin equivalent to what you're asking for.

The exact form this takes depends on your keyboard. With the Samsung keyboard I get a layout similar to the one in your picture, but with Swiftkey there's a lot of additional symbols.

A way to make the input method consistent could be to make in-app buttons, similar to how Sync does it:

![screenshot_2019-01-22-23-41-16](https://user-images.githubusercontent.com/6662937/51573682-43a60600-1ea2-11e9-8cc8-ef763e0c1440.png)

**Comment by kvithayathil** [comment]
Thanks for sharing @ShirokaiLon. I'm not familiar with the Xamarin options so that's interesting to know.

My device is actually a Note 9 running SwiftKey - which is what that picture is showing.  🤔

**Comment by ShirokaiLon** [comment]
You're quite right. It seems that Xamarin simply does not have a Keyboard option which triggers the numbers-only layout of SwiftKey.

The only way to solve this is to circumvent the Xamarin Keyboard settings and set the Android InputType directly:

![screenshot_2019-01-24-17-50-54](https://user-images.githubusercontent.com/6662937/51698930-71ef2700-2003-11e9-819e-3b1dbc0ffbee.png)

I also compared how the Samsung keyboard changes:

Using Xamarin Keyboard.Numeric:
![screenshot_2019-01-24-17-56-03](https://user-images.githubusercontent.com/6662937/51698986-90552280-2003-11e9-859c-625f8d5708a4.png)

Setting the InputType directly:
![screenshot_2019-01-24-17-53-53](https://user-images.githubusercontent.com/6662937/51699028-a7941000-2003-11e9-8f08-03e271e550d7.png)

So, I think the 'numberPassword' layout is better in general, but not being able to set it using the Xamarin Keyboard makes it slightly messier.

I'll create a pull request and let the powers that be decide 😁

**Comment by kvithayathil** [comment]
@ShirokaiLon Thank you - appreciate the rapid responses to this issue 👍
