### ISSUE TITLE
TOTP not copied when using password autofill service on Android Pie

### ISSUE THREAD

**Issue by serovar** [bitwarden/mobile#448]
The TOTP is not copied when autofilling a password on Android Pie (I am using a Pixel 2 XL with the stock ROM) using the native autofill service, while it is copied using the autofill accessibility service.

**Comment by NE-MO-MO** [comment]
@kspearrin can you please check this problem ,

**Comment by Primokorn** [comment]
What's the problem here? I thought it could be fixed faster. Does it come from Android API? 
Thank you.

**Comment by kspearrin** [comment]
TOTP copy for autofill service should now occur in v2.0 whenevr you select the autofill entry from within the app itself (not the dropdown menu, unfortunately). Can you try play store beta?

**Comment by anstosa** [comment]
> TOTP copy for autofill service should now occur in v2.0 whenevr you select the autofill entry from within the app itself (not the dropdown menu, unfortunately). Can you try play store beta?

Isn't that the same as it was before? The original ticket stats the the accessibility service (notification which opens the Bitwarden app) does work but the autofill service (dropdown) does not.

**Comment by kspearrin** [comment]
@anstosa As far as I can see, it is not possible to invoke a TOTP copy action when a user selects autofill from the dropdown menu. We just provide the items to show in the dropdown. There is no callback that notifies me that the user actually selected an item. 

Previously the TOTP code would not be copied even if you autofilled from opening the app screen ("Auto-fill with Bitwarden" option int he dropdown). This problem should be resolved in v2.0.

**Comment by anstosa** [comment]
Ah, understood. I'm not familiar with Android's APIs. Is it possible to use the accessibility service to observe user interactions with the auto-fill dialog?

**Comment by Primokorn** [comment]
V2.0 with Via browser the totp code is properly copied using the drop-down menu! It does work on my end.
Tested on Github website.

**Comment by kspearrin** [comment]
@anstosa I know of no way to accomplish this with accessibility. Closing since we added it as the only way possible in v2.0.
