### ISSUE TITLE
High battery and Ram usage

### ISSUE THREAD

**Issue by jerryn70** [bitwarden/mobile#45]
There is high battery and Ram usage even if the app is not used.

**Comment by sreich** [comment]
Here is under services ram usage of bitwarden. 1.4gb

http://i.imgur.com/UTRXlCd.png

For comparison's sake, LastPass is at 120mb or so:

http://i.imgur.com/P5cY7T9.png

**Comment by kspearrin** [comment]
These two are related: https://github.com/bitwarden/mobile/issues/42

It appears there is a memory leak somewhere on Android. I'm working on tracking it down.

**Comment by kspearrin** [comment]
I pushed build 467 to google play beta which disables the push notification service. That appeared to be leaking memory. Let me know if anything changes with that build.

**Comment by kspearrin** [comment]
This is related to the accessibility service, which there is a memory leak. I have opened an issue with Xamarin here: https://bugzilla.xamarin.com/show_bug.cgi?id=52616

**Comment by kspearrin** [comment]
This should now be resolved with the 491 build in the play store beta.
