### ISSUE TITLE
Android Poor Performance 

### ISSUE THREAD

**Issue by 0xA354** [bitwarden/mobile#453]
I have 30 entries in my bitwarden vault. When I'm scrolling down on my Android App it feels very laggy. Even when I'm trying to open an entry.

**Comment by mds08011** [comment]
Are you able to provide more information?  I have ~50 entries in my app and do not notice any issues.

**Device:** Google Pixel 2
**Android version:** 9.0
**Bitwarden version:** 1.21.0

**Comment by 0xA354** [comment]
Device: Samsung Galaxy s7 edge
SuperMan-Rom
Android version: 7.0
Bitwarden version: 1.21.0

**Comment by al-bashkir** [comment]
Same problem.
Device: OnePlus 3T
Android version: 9.0 (OxygenOS 9 beta)
Bitwarden version: 1.22.0

**Comment by kspearrin** [comment]
Can you try v2.0 from play store beta? is it better?

**Comment by PopeRigby** [comment]
I'm using v2 and it seems even worse. Everything feels slower.

**Comment by Xeunyx-Cypher** [comment]
Yes! I'm having similar. When I try to open my Vault at the start. It takes 15-20 seconds. I have 246 logins and only 3 notes. 
Bitwarden v2.5.0 on Redmi 4A

**Comment by djsmith85** [comment]
I'm closing this now due to age, but if this is still an issue please feel free to re-open. Please provide any further information that may be helpful in reproducing the problem or helping you further.

**Comment by Oakwas** [comment]
I'm experiencing the same issue
Scrolling is very laggy

**Comment by fedemkr** [comment]
Hi thank you for the update, could you provide us with the device model and operative system version where you experience the lagginess?

**Comment by Oakwas** [comment]
I'm using a galaxy a21s and running android 11

**Comment by Surferlul** [comment]
I also have performance issues, I'm on a Pixel 8
