### ISSUE TITLE
Autofill Chrome iOS

### ISSUE THREAD

**Issue by sn00pster** [bitwarden/mobile#454]
On iOS Using the autofill password on the Bitwarden site itself results in both the username and password thinking they haven’t been filled in, you have to insert a character and then delete it to make the field valid.

Assume this is a bug in the JavaScript.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
