### ISSUE TITLE
Not detecting internet connection on Sailfish X with Android layer

### ISSUE THREAD

**Issue by adelnoureddine** [bitwarden/mobile#455]
I am having a similar problem as with the [issue here](https://github.com/bitwarden/mobile/issues/334#issuecomment-406592515).

As soon as I try to login to the app, I get an error "Not connected to the internet".
I have no google play services, and I am using an Android compatibility layer on Salfish X (android version 8.1).

I tried downloading the beta APK in the above issue, but it seems it's the latest beta.
This is the only Android app I tested that fails to connect to the internet o WLAN or mobile data.

**Comment by kspearrin** [comment]
Can you try v2.0 from play store beta?

**Comment by adelnoureddine** [comment]
Thanks. Tested version 2.2.6 and it is working.
