### ISSUE TITLE
Doesn't work on rooted Android phones

### ISSUE THREAD

**Issue by ash-at-work** [bitwarden/mobile#461]
Have tested this out on an unrooted, then rooted, then unrooted Pixel 3 - the Bitwarden app doesn't login on a rooted phone - it just hangs, as if it's getting no internet connection. If it's already logged in (i.e. unrooted login, then rooted the phone) it is never again able to update or sync with the server (but does log in using the master password).

Coudn't find this posted elsewhere (although similar issues on Android have been posted, so perhaps those are due to the same thing?).

Pixel 3, Android 9, latest stable version through Play Store

Awesome product, by the way

**Comment by kspearrin** [comment]
Unfortunately I don't have a rooted Pixel 3 device to test this one. Are there any interesting logs on logcat?

**Comment by ash-at-work** [comment]
So did a bit more troubleshooting and turns out I was mistaken - the one other thing that was being autoactivated with root was Adguard. Deactivating that for Bitwarden fixed the issue!

No idea what was actually going on from the adblocking end to prevent Bitwarden from going online, but if anyone else has issues with 'no network' then disabling your adblock might be the answer.
