### ISSUE TITLE
Android app offers to autofill and save password fields that aren't password fields.

### ISSUE THREAD

**Issue by JaredDiCioccio** [bitwarden/mobile#464]
I just started using BaconReader, a reddit application. Whenever I start entering a reply to a comment the "Auto-fill with Bitwarden" popup appears. And then if I submit a comment or simply back out, it offers to "Save password to Bitwarden?"

I have 

"Always Scan", "Scan when password field focused", and "Persist notification" all disabled. I'm not sure how to make Bitwarden NOT keep offering to auto-fill or save these forms that are clearly not passwords. 

I'm not sure if this happens with other apps. BaconReader's really the only app I use that I enter text into. 

And I can't find any way to blacklist certain apps from auto-fill (which isn't desired, since I may need to actually input user/pass information to BaconReader), or have it not prompt the auto fill popup.

**Comment by kspearrin** [comment]
We only offer autofill prompts whenever the input field as flagged as a password field. I am not sure why BaconReader would be doing this for a standard input field. Maybe you can ask the.

Unfortunately, at the moment there is no blacklist, but it is something we are looking in to.

**Comment by kspearrin** [comment]
Should be fixed next version. ref: https://www.reddit.com/r/baconreader/comments/autdvu/bitwarden_thinks_comment_replies_are_password/
