### ISSUE TITLE
No syncing on Android 9 

### ISSUE THREAD

**Issue by tullio53** [bitwarden/mobile#467]
Hi, I have installed Bitwarden App on Android 5 and it runs perfectly. On the contrary, on my Xiaomi Mi A2 Lite with Android One  9 release Febrauary '19, the App can't sync at all; my local vault is empty. The message error is "Syncing error". Thanks in advance for support

**Comment by kspearrin** [comment]
Could you try changing networks and see if that makes any difference?

**Comment by tullio53** [comment]
I checked and I found a quite strange situation. Connecting with my
domestic WiFi, device with Android P doesn't sync, another device with
Android 5 syncs without any problem. On different WiFi or with 4G data
connection, Android P syncs!!. I can't explain by myself...
Many thanks for your reply

Il sab 2 mar 2019, 20:03 Kyle Spearrin <notifications@github.com> ha
scritto:

**Comment by marcinsmialek** [comment]
This should be reopened.
I'm experiencing the same issue - both Firefox addon and stand-alone Windows client sync properly, and the client on Android device doesn't,
Moreover, the spinner on the phone stays for some time, closes, and there is no info whatsoever that the sync failed. On other network the forced sync is fast, and successful.

We need:
1. Reliable Android sync
2. If sync fails, there should be a message displayed, which has to be manually acknowledged, so the end user is aware that the sync failed.

**Comment by Schnuecks** [comment]
Same here,
i use the selfhosted variant. 
the extension works fine the vault web-version works, only the android client doesn't want to sync. i have a nokia 7 plus with pie patches july.

no error in docker logs or log on webserver. all seems fine.

**Comment by oltdaniel** [comment]
This is still an issue and there is no solution to it.

**Comment by richardy2** [comment]
I have just come accross the same problem with Android 6.0.1 on a Samsung Galaxy S5 mini. Would not sync on house WiFi but log onto a mobile hot spot and it synced without any trouble. This is certainly big drawback.

**Comment by jzahraoui** [comment]
Is this can be related to TLS version used by nginx ?

**Comment by Holewijn** [comment]
same problem here, OnePlus 7pro login works, sync not.

**Comment by adilakport** [comment]
This is not a Bitwarden related issue it is related to the MTU Value setting in your router. I solved this by manually finding out the MTU value and entering the correct value in the user configuration page. 

[How to find out MTU Value for your ISP](http://www.dlink.cc/d-link-router/how-to-find-the-proper-mtu-size-on-d-link-router.html)

Use this method to determine the value and then go to the user configuration page, commonly, 192.168.1.1, and then enter the value in WAN/Internter Configuration.
