### ISSUE TITLE
Full choice of credentials when logging into a service (Android)

### ISSUE THREAD

**Issue by atlasax** [bitwarden/mobile#469]
Whenever I try to log in to a service on my phone, I can choose a credential with matching URL from my Vault (intended behavior).
Sometimes the Vault doesn't know what I want to log in to (e.g. in case of the app name not matching the base URL). In that case it won't show the appropriate credentials in the selection window. It would be practical to have an option there to select from all credentials instead of only the matching, and maybe get a prompt to add the current URL to the credential's URLs on selection.

**Comment by kspearrin** [comment]
You can already do this. Select the search icon and then pick the credential that you want to autofill.

**Comment by atlasax** [comment]
Oh, I just thought that was for filtering the results. My bad.
Having that view still filter{ed,able} by folders would be nice to have, still.
