### ISSUE TITLE
Ignore auto fill option for specific apps

### ISSUE THREAD

**Issue by jerryn70** [bitwarden/mobile#47]
By making ignore auto fill option we can add apps to the list that we don't what to show auto fill. Otherwise auto fill will appear on every apps including apps that we don't need auto fill assist. 
By this idea we can save more battery and Ram.

**Comment by kspearrin** [comment]
This is not the correct solution for saving battery and RAM. There is an underlying issue with he accessibility service where it leaks memory that is being discussed here: https://github.com/bitwarden/mobile/issues/45

**Comment by jerryn70** [comment]
You are mistaken. 
what should i do if i don't what to show auto fill for xda app ?
There is no option to exclude particular apps . 
That kind of option what I'm talking about.

**Comment by kspearrin** [comment]
Next version will have a "Never" option for URLs so you can turn it off for autofilling.
