### ISSUE TITLE
TOTP is not getting copied to your clipboard with android autofill API

### ISSUE THREAD

**Issue by djohannes** [bitwarden/mobile#470]
When you use autofill via the notification, your TOTP code is getting copied to your clipboard so you don't need to go back to the bitwarden app to copy it there.
But when you use autofill via the Android autofill API it doesn't get copied to your clipboard and you are forced to manually go to your bitwarden app.

**Comment by kspearrin** [comment]
duplicate https://github.com/bitwarden/mobile/issues/448

**Comment by djohannes** [comment]
@kspearrin Ah, sry. Didn't found the search on mobile.
