### ISSUE TITLE
Disable Google Firebase Analytics and HockeyApp

### ISSUE THREAD

**Issue by ItzHaunT** [bitwarden/mobile#471]
Can we have an option to disable trackers? I read the issues that were opened about this before, but it has been some time since they have been open. Almost two years (https://github.com/bitwarden/mobile/issues/8) and one year ago today (https://github.com/bitwarden/mobile/issues/178). 

I put this is the issue section rather than the feature requests because tracking in an app designed for privacy is a serious issue. I understand the want for usage reporting, but it should be optional. 

I really don't like the idea of Google gobbling up all my data, especially data about my password manager. It is extremely off-putting. Please give us the option to opt-out of usage reporting, or preferably remove it all together.

**Comment by kspearrin** [comment]
1. We use Firebase for push notifications to keep your vault in sync. We don't collection analytics data from it.
2. We use HockeyApp for crash reporting.

If you want to avoid these, we do offer a fdroid APK that you can download manually from here: https://github.com/bitwarden/mobile/releases , but you will lose autoupdates from the play store this way.

**Comment by ItzHaunT** [comment]
> 
> 
>     1. We use Firebase for push notifications to keep your vault in sync. We don't collection analytics data from it.
> 
>     2. We use HockeyApp for crash reporting.
> 
> 
> If you want to avoid these, we do offer a fdroid APK that you can download manually from here: https://github.com/bitwarden/mobile/releases , but you will lose autoupdates from the play store this way.

Thank you for the quick reply!

I wasn't aware of the f-droid APK. I'll be using that from now on then.
