### ISSUE TITLE
iOS New Passwords Save

### ISSUE THREAD

**Issue by gt2416** [bitwarden/mobile#473]
Using iOS 12.1.2 using the latest bitwarden docker passwords do not get saved if I access a new webpage.
Using chrome(on a desktop) when I login to a new website it asks if I want to save the password, however on iOS it never does. I always have to manually add it which is a pain. 
Also on domains that are not public like my personal guacamole.home / xenorchestra.home sites the autofill does not work on iOS, on chrome on a PC however it does. 
The only change from the default settings is that I use a non default port for http and https as port 80/443 is used for something else. 
id: 1.30
admin: 1.30
web: 2.9.0
api: 1.30
web: 2.9.0
iPhone X: iOS 12.1.2 

Is this a known bug ?

**Comment by kspearrin** [comment]
We can't offer to save new logins automatically on iOS. This is a limitation of the OS autofill features. Only Apple's keychain autofill service can do that.

**Comment by gt2416** [comment]
Dang, thats a shame

**Comment by rochakgupta** [comment]
Dang it Apple!

**Comment by chimeworld** [comment]
> We can't offer to save new logins automatically on iOS. This is a limitation of the OS autofill features. Only Apple's keychain autofill service can do that.

Is this still the case?

**Comment by Ihor-Khomenko** [comment]
> 
> 
> > We can't offer to save new logins automatically on iOS. This is a limitation of the OS autofill features. Only Apple's keychain autofill service can do that.
> 
> Is this still the case?

Unfortunately, yes

**Comment by rochakgupta** [comment]
Apple being Apple and trying to lock people into their ecosystem. I hope they allow for more third party applications given they have allowed users to change their default browser and mail client.

**Comment by m4ttheweric** [comment]
Any update on this @Ihor-Khomenko ?

I have tried to fully migrate to BitWarden but this is the only missing piece.
