### ISSUE TITLE
can't connect self-hosted vault with Android App

### ISSUE THREAD

**Issue by Catskan** [bitwarden/mobile#474]
Hi all,

I have my personal Bitwarden server in my Synology with Docker and it works perfectly.

I just have a Xiaomi MI 9 and it's my first time in Android OS. 
So, I installed Bitwarden Android App, change the server with my Self-hosted server (https://my.server:customport) and I can't connect to my Vault.

I tried with Firefox browser and Chrome (in my android) and the connection works.

In the application, I have "there is a problem connecting to the server".

Before, I had the Bitwarden iOS app and I never had a problem.

I use 1&1(ionos) certificate when I installed my bitwarden server.

I don't understand ...

In android, I have to set something ?

Thanks you for your help.

Regards

**Comment by kspearrin** [comment]
Android has stricter SSL requirements. Check your cert for issues here: https://www.digicert.com/help/

**Comment by Catskan** [comment]
Here is results of the digicert check : 
![image](https://user-images.githubusercontent.com/17289964/54599329-ac40d780-4a3a-11e9-80a3-efc174120d7a.png)

**Comment by kspearrin** [comment]
I am not sure. I would try contacting your certificate provider for help.

**Comment by Catskan** [comment]
My certificate provider is ionos.com
The web page on the ssl certificate https://www.ionos.com/security/ssl-certificate

I have a domain in .fr with all of certificate ssl.
![image](https://user-images.githubusercontent.com/17289964/54606792-0cd91000-4a4d-11e9-8980-244750471141.png)

How can I help you ?

**Comment by Catskan** [comment]
Hi kspearrin,

Have you any news for this problem ? Have you need others informations ?

Regards,

**Comment by dagavi** [comment]
I think that you already post your problem in the digicert check: The server is not sending the required intermediate certificate

I don't remember where I read this but Android needs a full chain certificate to work.

You can try with Let's Encrypt and see that this works with the full chain.

**Comment by Catskan** [comment]
Hi,

I installed my certificates into Android directly and Bitwarden app works now.

Thanks for your help !
