### ISSUE TITLE
Editing an existing field

### ISSUE THREAD

**Issue by gavthompson** [bitwarden/mobile#476]
If you attempt to editing an existing items field (name/URL etc) after typing the first character the cursor will jump the end of the field.

For example:
Trying to change hyyps://google.com would require me to move the cursor back into position twice as after correcting the first "y" the cursor would jump to the end of ".com".

This behaviour has been observed on Android 8.1
App version: 1.22.0 (1652)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/mobile/issues/423
