### ISSUE TITLE
New Mozilla browsers on Android need autofill whitelisting

### ISSUE THREAD

**Issue by callahad** [bitwarden/mobile#477]
Hi Kyle, thanks for Bitwarden!

We have a few Android browser projects under development that need whitelisting in the autofill service:

- `org.mozilla.fenix`
- `org.mozilla.reference.browser`
- `org.mozilla.rocket`

All support native Oreo/Pie autofill.

*(See also: https://bugzil.la/1538385)*

**Comment by kspearrin** [comment]
Any idea if these work with the compat shim or "natively" with Pie autofill?

**Comment by makotokato** [comment]
GeckoView based browsers (`org.mozilla.fenix` and `org.mozilla.reference.browser`) are same implementation as Firefox/Android.
 
> Any idea if these work with the compat shim or "natively" with Pie autofill?

What's "natively" meant?  Current Gecko supports Android O/P's auto fill framework.

**Comment by kspearrin** [comment]
AS far as I know, Geko uses the compatibility mode of the Autofill Framework. https://developer.android.com/reference/android/service/autofill/AutofillService.html#CompatibilityMode

**Comment by makotokato** [comment]
Firefox 63+ starts native API implementation by https://bugzilla.mozilla.org/show_bug.cgi?id=1330257.  So at least, `org.mozilla.fenix` and `org.mozilla.reference.browser` should be added to `CompatBrowsers` list due to same implementation.

**Comment by kspearrin** [comment]
Feel free to try this fix with the APKs built here: https://ci.appveyor.com/project/bitwarden/mobile/build/artifacts

**Comment by callahad** [comment]
I can confirm that the in-app prompts work correctly with that APK, including properly filtering suggestions, and with the accessibility service disabled. Thank you!

If I enable the accessibility service, I get a system-wide autofill notification when password fields are focused. Tapping on that notification takes me to Bitwarden, but with entries filtered on the package name (`org.mozilla.fenix`) instead of the site URL. Selecting an entry does correctly autofill it.

Is that something that can be fixed, or is it an necessary quirk of Android's autofill implementation?

**Comment by kspearrin** [comment]
@callahad I'll need to add it to the supported browser list for the accessibility service, seen here:
https://github.com/bitwarden/mobile/blob/master/src/Android/AutofillService.cs#L28

For this, I need to know the id of the view element that contains the URL of the current website you are viewing. For example, on Firefox stable, this is `url_bar_title`. Is the view id the same on these versions? If you don't know I can try to look them up myself if you tell me how I can download these apps.

**Comment by callahad** [comment]
@agi90, can you answer the above for Fenix and Reference Browser?

@kspearrin: You grab nightly builds from Taskcluster: [Fenix](https://tools.taskcluster.net/index/project.mobile.fenix.signed-nightly.nightly/latest), [Reference Browser](https://tools.taskcluster.net/index/project.mobile.reference-browser.signed-nightly.nightly/latest).

The source for these projects lives at [mozilla-mobile/fenix](https://github.com/mozilla-mobile/fenix/) and [mozilla-mobile/reference-browser](https://github.com/mozilla-mobile/reference-browser), respectively.

**Comment by kspearrin** [comment]
@callahad For whatever reason, I can't open any of those APK files on my test device or Windows emulator. They just say "Can't open file" after downloading them in Chrome. Normally I can sideload apks without issue, so I am not sure what the problem is here.

**Comment by colintheshots** [comment]
I believe both Fenix and the Reference Browser use the BrowserToolbar Android Component. This means they use a view ID of mozac_browser_toolbar_edit_url_view for editing and mozac_browser_toolbar_url_view for viewing. Both views are always present, but only one is visible.

**Comment by kspearrin** [comment]
@callahad Feel free to try latest dev APK here now for accessibility service support: https://ci.appveyor.com/project/bitwarden/mobile/build/artifacts

I added `mozac_browser_toolbar_url_view` as the view id for both fenix and reference.
