### ISSUE TITLE
Android Client Sync without Internet connection

### ISSUE THREAD

**Issue by jonathanmmm** [bitwarden/mobile#478]
Hello Bitwarden Team,

Thank You for your work and great password manager.

I am trying to sync an Android device to my local server which has no Internet connection.

I know that the Apps are using normally the Google Push Notification technology over https://push.bitwarden.com

But you have written in another post that (https://community.bitwarden.com/t/self-hosted-outbound-push-notification-url/1157/8) it will sync time to time?

How big is the interval that the client tries to sync manually and is it still build in?
(would be a feature request maybe to make a toggle in settings to sync when app is opened or every hour or so?)

The "sync manually" is really deep hidden and normally I don't open a password manager on the phone and just use autofill through it in browser or apps so is it syncing maybe every few hours?

To make sure that your servers are not flooded with useless requests is there a way to make this manual sync option only available when self hosting so you don't have to worry about network traffic (like written in here: https://community.bitwarden.com/t/auto-sync-on-all-platformes/355/9)

Greeatings

**Comment by kspearrin** [comment]
If it hasn’t synced in ~1 hr, it should automatically sync whenever you open the app.

**Comment by jonathanmmm** [comment]
Ok great, thank you for your fast reply.
Does this also happen when I am not opening the app directly but requesting the autofill API in Android Oreo?

**Comment by kspearrin** [comment]
No. That would require push notifications.

**Comment by jonathanmmm** [comment]
Ok, thanks.
Would be great if the app could do this. Like a cronjob in the app checking every hour or when startet by accessible service or autofill API to sync if not synced in the last ~ 1 hr.

**Comment by jonathanmmm** [comment]
So I have to manually open the app from time to time which I rarerly do, right? (I have the Autofill API, so normally there is no reason for me to do so).

**Comment by kspearrin** [comment]
Correct.

**Comment by jonathanmmm** [comment]
Thanks for your great help 👍 

Another question would be: I just have to enter in the settings before the URL/IP in the top and don't have to enter it below only if e.g. the API is on another server, right? This would only be needed in a big environment.
I have written some things about compiling the App yourself to change push.bitwarden.com to your own push server, would this be the way to go?

Also what does the F-Droid .apk that can be downloaded differently, especially in terms of push notification? (https://github.com/bitwarden/mobile/issues/6#issuecomment-357073126)
Has the F-Droid .apk no Google Push Notification build in so no push notification will work at all only open around every hour?

**Comment by kspearrin** [comment]
We don't have any guidance on using your own push server at this time since push notifications require a signed application from the app store with a specific package id.

The fdroid version has all google dependencies removed from the app.
