### ISSUE TITLE
Logins search should search all fields

### ISSUE THREAD

**Issue by sreich** [bitwarden/mobile#48]
I've noticed that, at least for a login site I have stored, searching for the URL in the app, will only find it by name. 

It should probably be searching for URL too. As well as the notes area itself. This is what lastpass does, makes it much easier if you only remember the URL.

**Comment by sreich** [comment]
And I thank autocorrect for the typo in the original title...

**Comment by boriskindy** [comment]
I too would like to see this feature added. I have a folder entitled Secure Notes in bitwarden with records stored inside. I would like the Notes part of those records to be included in any search performed as is the case with Keeper password manager. This is a useful feature if you only happen to remember part of the note stored.

**Comment by boriskindy** [comment]
Just wondering if this is a planned feature, ie, the ability to have all fields of a record included in search results? I was looking for the login details to a mailing website I use, but I couldn't remember the name of the website. Keywords stored in the Notes section of the record within bitwarden would have located it. Alas, they were not included in the search.

**Comment by kspearrin** [comment]
@boriskindy It is not planned as of now. We'll need to figure out a better way to do search since right now it would be too inefficient to add notes to the current routine.

**Comment by vtashev** [comment]
@kspearrin Hey is there any news on search for all fields, including custom ones, notes etc?

**Comment by kspearrin** [comment]
I started looking into adding Solr.js to the apps to make search more advanced, however, I am waiting on a few more features in that library before we can use it. No ETA at the moment.

**Comment by Crocmagnon** [comment]
Maybe you mean lunr.js ? :)

**Comment by kspearrin** [comment]
Yes, I did :)
