### ISSUE TITLE
Android 9 + SwiftKey - Master password is shown in keyboard suggestion bar when logging into the app

### ISSUE THREAD

**Issue by lorenzodb1** [bitwarden/mobile#480]
Other apps just don't show the suggestion bar when typing in the password field.

**Comment by kspearrin** [comment]
Not sure why SwiftKey does this. The field is marked as a password.

**Comment by lorenzodb1** [comment]
I couldn't take a screenshot but I took a picture of my screen to show you the issue. It doesn't do that consistently, though.

![esmZskpPFkCxxfdvXLQdNUsuBpQ](https://user-images.githubusercontent.com/16848175/55507017-abe43700-560b-11e9-8051-8a1b4f33a401.jpeg)

**Comment by Crocmagnon** [comment]
Does this also happen when typing in a password field of another application ?

**Comment by lorenzodb1** [comment]
I tried with other apps (bank app, phone company app, Facebook, Snapchat, Instagram) and I never encountered the same issue.

**Comment by QPFNAbch68** [comment]
If I go to a field that is NOT a password entry field (username, email, etc.), the password is visible in SwiftKey. If I move to a field intended for a password, the option to paste the password is removed.

Here's a side note... SwiftKey has an extended clipboard. It stores you most recent items copied to the clipboard. I can view the list in SwiftKey and any passwords are clearly visible. It's my guess this "feature" is what allows the copied password to be visible as that in the original post.

**Comment by lorenzodb1** [comment]
@QPFNAbch68 I'm not sure if I understood your comment as intended, but I didn't copy and paste that password, I just typed it.

**Comment by kspearrin** [comment]
Can you try v2.0 from play store beta? I added incognito keyboard throughout.

**Comment by lorenzodb1** [comment]
I'm sorry, I didn't see that comment on time, but I just updated the app to the latest version and it looks like it's working now!

Thank you so much guys for taking care of it!
