### ISSUE TITLE
Accessibility service gets switched off 

### ISSUE THREAD

**Issue by Stephan-P** [bitwarden/mobile#484]
On my Android 9 phone the Accessibility service gets switched off. I don't know how and I don't know by who or what. 
Is there a way to prevent this?

**Comment by kspearrin** [comment]
Probably need to disable battery optimization settings for Bitwarden under your android settings. See https://dontkillmyapp.com/

**Comment by Stephan-P** [comment]
I'd already disabled Power saving for the Bitwarden app and still it was closed/killed.

Thanks for that link. My phone is a Nokia, listed there as a notorious app killer thanks to some system app. I've applied the solution given there. Let's see how things are faring from here.


Van: Kyle Spearrin
Verstuurd: maandag 15 april 04:49
Onderwerp: Re: [bitwarden/mobile] Accessibility service gets switched off  (#484)
Aan: bitwarden/mobile
Cc: Stephan Paternotte, Author


Probably need to disable battery optimization settings for Bitwarden under your android settings. See https://dontkillmyapp.com/

**Comment by Stephan-P** [comment]
Update: With power saving disabled for Bitwarden and system apps Power Saving disabled as per https://dontkillmyapp.com/, the Bitwarden accessibility service still gets automagically disabled.

Stephan

________________________________

**Comment by Stephan-P** [comment]
Update: after working with HMD (Nokia) support, who had met go through numerous Cache wipings and App preferences resets, the issue remains: I set Bitwarden Accessiblity service, a few hours later it is automagically switched off.

**Comment by m3gg3** [comment]
Same Problem on my Samsung s9 with Android 9 - issue #488

**Comment by Stephan-P** [comment]
Disabling system apps com.evenwell.powersaving.g3.* as per https://dontkillmyapp.com/ did not help for me and my Nokia 3.1 . 
Another tip mentioned on https://dontkillmyapp.com/ is to disable MediaTek DuraSpeed. I need to get up to speed with adb to be able to do this. Steep learning curves these days. I'll report back.

**Comment by kometchtech** [comment]
I use Xiaomi Mi5s (Android 8.0 based MIUI 10), but I also have this problem.

I reviewed the battery settings referring to https://dontkillmyapp.com/xiaomi, but the situation did not improve.

**Comment by SuperSandro2000** [comment]
My s8 has sometimes similar issues with other apps. Just don't restart.

**Comment by Stephan-P** [comment]
Meanwhile I've managed to permanently disable the Nokia 3.1 system module DuraSpeed and this solves my problem. Bitwarden accessibility service as well as other apps background services are no longer shut down.

**Comment by tboldini** [comment]
Hi everyone. On TCL 10 SE/Android 10 same bug. Accessibility is lost without battery optimization for Bitwarden.
Accessibility is kept for a while (few/some hours) then I find again off. Very annoying.
I gave back a Xiaomi 9 PRO after 2 weeks for this reason and the new TCL had the same issue.
Who knows it!?
