### ISSUE TITLE
8 digit TOTP QR not being parsed

### ISSUE THREAD

**Issue by dagavi** [bitwarden/mobile#485]
BitWarden has support for QR parameters since some months: https://community.bitwarden.com/t/support-totp-auth-parameters/37/6

The code generation is working fine (including mobile).

The problem is that adding 8 digit QR is ignoring all the encoded string (that is all the string that you should insert in TOTP field) and only copy the key, so it generates 6 digits TOTP.

I scanned the QR with a 3rd party app and saw that the QR contains all the string that I added to "TOTP" field manually to start generating 8 digit TOTP in BitWarden.

For example, you can try:
`otpauth://totp/MyTest:12345?secret=ASFAS75ASDF75889G9AD7S69AS7697AS&issuer=MyTest&digits=8
`

And (generated by: http://goqr.me):
![QR](https://user-images.githubusercontent.com/956364/56094843-29932700-5ed7-11e9-87f0-559f5392642f.png)

**Comment by kspearrin** [comment]
Should be fixed next version.
