### ISSUE TITLE
Title (Mr, Mrs, etc) in “identity” entries doesn’t match

### ISSUE THREAD

**Issue by otavzcsx** [bitwarden/mobile#486]
I was able to recreate this on the iOS app, but do not know if it is limited to it.

Create an “Identity” entry. Give entry a title- in my test, I assigned a title of “Mr”. After saving and coming back, it has me showing as “Ms”. When setting to “Ms” and going back in to edit, it shows “Dr” and so forth with this logic. One may need to add it, go back out to the main screen, then go back into the identity to see this. If that does not recreate, try to edit the entry.

**Comment by kspearrin** [comment]
Sounds like an index off by 1 error somewhere.

**Comment by kspearrin** [comment]
Should be fixed in v2.0
