### ISSUE TITLE
iOS [2.2.0] crash when triggering Autofill from Octal app

### ISSUE THREAD

**Issue by luckman212** [bitwarden/mobile#487]
Have only encountered this bug with [Octal](https://itunes.apple.com/us/app/id1308885491?mt=8) so far, but it's strange indeed.

- iOS 12.4 / iPhoneXS 512GB

When clicking on the Login button in Octal, and then triggering Bitwarden's autofill function, the password "sheet" will appear momentarily (after FaceID) and then after about 1.5 seconds, it will (crash? disappear?). This is repeatable.

To see if the bug was with Octal itself, I switched the Autofill function to use Lastpass instead, and then reproduced the steps. It did not crash. Same thing with iCloud. So for whatever reason this only affects Bitwarden.

Here's a small video clip:

![RPReplay_Final1555651082-s 2019-04-20 09_07_20](https://user-images.githubusercontent.com/1992842/56457637-d7755a00-634b-11e9-9dd7-7e3f0e4c3df4.gif)

**Comment by kspearrin** [comment]
I can reproduce the problem when debugging here locally. Unfortunately, I am not seeing anything helpful that is showing me why it is crashing.

**Comment by luckman212** [comment]
@kspearrin Thanks- I opened https://github.com/dangwu/Octal/issues/65 over there as well, so maybe @dangwu has some idea...

**Comment by luckman212** [comment]
@kspearrin: Daniel [responded](https://github.com/dangwu/Octal/issues/65#issuecomment-486366120) that he doesn't know what's causing this crash. Is there any way to further debug this? Could it be something crazy like the name or URI that gets passed from the app conflicting somehow with an internal Bitwarden variable?

**Comment by kspearrin** [comment]
We are currently working on a large re-write of the mobile app. I will see about debugging it further when it comes to working on that feature.

**Comment by luckman212** [comment]
Saw the new rewritten app out today (thank you!) so I installed it & tried this again.

Sadly it still crashes after 1 second in exactly the same way as before. Not sure if you ever got to look at this during the rewrite but I hope there's some way to figure out where the bug is now.

https://github.com/dangwu/Octal/issues/65#issuecomment-510861365

**Comment by luckman212** [comment]
FWIW I've updated the top comment to reflect the fact that this crash still happens on iOS 12.4

I also tried deleting & reinstalling both Bitwarden and Octal apps, but that didn't help.

**Comment by luckman212** [comment]
Just noting that this bug persists with iOS app v2.2.0

@kspearrin Is there any way I can help debug what's causing this?

**Comment by kspearrin** [comment]
I've spent some time again this morning trying to debug this more. Unfortunately, I still am not getting much useful information at the time of the crash to see what is causing it. 

The best I could see, was a `[Common] _BSMachError: port be1b; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"` output in console, but I am unsure if this is caused by the crash or not.

**Comment by luckman212** [comment]
Bitwarden iOS app ver 2.2.1 seems to fix this crash! Not sure if that was a side effect of some other changes, but I'll take it! Thank you

**Comment by kspearrin** [comment]
I have no idea what fixed it, but great!
