### ISSUE TITLE
Password field input pointer position is reset on change

### ISSUE THREAD

**Issue by rkkr** [bitwarden/mobile#496]
Bitwarden 1.22.00. Android 8.1.

1. Edit Login item with saved password
2. Click eye to show password
3. Click middle of the password (move pointer)
4. Delete or add one character
5. Input pointer is moved to the end of the password

**Comment by kspearrin** [comment]
This is a known bug that should be fixed next major version.

**Comment by kspearrin** [comment]
Fixed in v2.0
