### ISSUE TITLE
Android app started giving error connecting to server

### ISSUE THREAD

**Issue by hank** [bitwarden/mobile#497]
The android app was working great until today. Now I can't get it to connect to my server anymore. I'm using Letsencrypt certificates that work fine in mobile chrome with no warnings. Login through mobile chrome works perfectly. Please let me know how I can display the actual error.

**Comment by kspearrin** [comment]
Nothing has changed with the Android app in weeks, so something else has caused this problem, likely with your server. I suggest checking the trust chain for your server with https://www.digicert.com/help/

**Comment by hank** [comment]
![Capture](https://user-images.githubusercontent.com/8534/57591510-ca3d2c80-74ff-11e9-8d3c-4c36f154d57a.PNG)

**Comment by hank** [comment]
![Capture](https://user-images.githubusercontent.com/8534/57591597-391a8580-7500-11e9-89e1-83022465a303.PNG)

**Comment by hank** [comment]
Did a couple more tests and saw this: could it be the culprit?

OCSP STAPLING ERROR: OCSP response expired on Thu May 09 19:00:00 UTC 2019
--

**Comment by hank** [comment]
Also I only support TLS 1.2 - would that be an issue?

**Comment by hank** [comment]
Turns out I had a permissions issue on my ocsp response cache:

```
May 12 22:42:38 caddy caddy[8129]: 2019/05/12 22:42:38 [WARNING] Stapling OCSP: unable to write OCSP staple file for [bitwarden.mydoma.in]: open /etc/caddy/ocsp/bitwarden.mydoma.in-a7a7a7a7: permission denied
```

I corrected this and restarted caddy to update the cache. Then I tried the app again and everything worked. The strange part is: I don't have OCSP must staple on:

```
OCSP Must Staple | No
```

Please add a better error for this case if it occurs to steer people in the right direction. Something like "OCSP validation failed: expired response" or something to that effect would do the trick.
