### ISSUE TITLE
Android, Bacon Reader, BW thinks any text-entry field is a password field

### ISSUE THREAD

**Issue by mkaito** [bitwarden/mobile#498]
BaconReader is a Reddit client for Android.

Android 9
BaconReader 5.5.2

When writing a new comment, BitWarden offers to auto-fill the textfield. Upon posting it, BW offers to save it as a password.

**Comment by kspearrin** [comment]
I added a possible fix for this a while back. Can you try the beta to see if the same issue occurs there?

**Comment by mkaito** [comment]
Alright, I'm waiting for gplay to let me into the beta. Will report back.

**Comment by mkaito** [comment]
Seems to work! Thanks!
