### ISSUE TITLE
Invalid TOTP Code Generation for Reddit

### ISSUE THREAD

**Issue by hmnd** [bitwarden/mobile#499]
The TOTP code generated by the mobile app on Android does not match with the one on desktop for Reddit. The desktop one works, mobile does not. This appears to only affect Reddit for me, as, though there is still a discrepancy between mobile and desktop, both codes still work for Google.

**Comment by kspearrin** [comment]
Is your system time correct on both devices?

**Comment by hmnd** [comment]
Yes.

**Comment by Crocmagnon** [comment]
I encountered a similar problem a while ago : the TOTP key didn't sync correctly, ending up with two different TOTP keys on two different devices.
Did you check that the TOTP key was identical on your mobile and desktop ? You can check it in the login edit page.

**Comment by hmnd** [comment]
@Crocmagnon I did. This issue has persisted after multiple phone resets and app reinstalls as well.

**Comment by kspearrin** [comment]
Unfortunately, I am not able to reproduce the issue. On mobile and in the browser extension and in desktop, the TOTP codes for my Reddit account are generating the same values.

**Comment by hmnd** [comment]
Strange. I disabled and re-enabled two factor on my reddit account and that appears to have fixed it. Even tried setting the token in Bitwarden back to the original one, but can't reproduce it anymore.

**Comment by hmnd** [comment]
It looks like this __could__ actually be some bizzare issue with Reddit's implementation of TOTP. I just experienced a similar bug on desktop, but neither my mobile-generated or browser-generated token would let me in. Had backup codes, so could thankfully use those.
