### ISSUE TITLE
Bitwarden autofill android Dolphin not working anymore

### ISSUE THREAD

**Issue by dmys2019** [bitwarden/mobile#500]
Was working until a few days ago but yesterday just stopped.  Seems to be working on Chrome browser though.

**Comment by kspearrin** [comment]
I don't know what Dolphin is. Is this a browser?

**Comment by dmys2019** [comment]
Sorry... Dolphin browser, running on a Samsung Galaxy S9+  with Android 9.0.  Have tried both Autofill and Accessibility separately and individually but it doesn't work.  It is something that just happened a day ago, prior to that BitWarden was working on both Chrome and Dolphin browsers; now it is working only on Chrome

**Comment by kspearrin** [comment]
Have you tried restarting? Did Dolphin update or something? We have not released any updates.

**Comment by dmys2019** [comment]
I have tried uninstalling and reinstalling both Dolphin and Bitwarden; Dolphin last updated May 9th, 2019 but Bitwarden has been working since that date until yesterday, no problems.  Further to this, by "not working" I mean when trying to autofill on online logins it will generate the autofill icon/pull down but when tapped it opens up a blank page advising "There are no items in your vault"  with an "ADD AN ITEM" box below.  I followed through with manually adding the login information for some sites and once I do that autofill works but only for those items, none of the other items in my vault.

**Comment by kspearrin** [comment]
I installed Dolphin to test the problem. The issue is that the address bar does not contain the URL of the website any more, so it is unable to determine that website to show you records for when autofiling. Is there a way to get this back? You could also just search for the record.

**Comment by dmys2019** [comment]
Thanks for testing Dolphin. I am not sure what you mean when you say the address bar does not contain the website URL anymore? I am using the most recent version of Dolphin and the asdr

**Comment by dmys2019** [comment]
Hi Kyle, I uninstalled Dolphin and reinstalled an earlier version; current version 12.1.1 uninstalled and version 12.0.2 installed. Everything works again!  Thanks for your patience and help troubleshooting this for me.
