### ISSUE TITLE
Typing in Item name always jumps to the end

### ISSUE THREAD

**Issue by SuperSandro2000** [bitwarden/mobile#502]
When I change the name of an item the cursor always jumps to the back after 1 or 2 characters.
Android Pie, Galaxy S8, Gboard English/German

**Comment by RomRider** [comment]
Same here with OP6T, Android 9, SwiftKey keyboard

**Comment by pb1051** [comment]
I tried to record the behavior, but I couldn't because of the security issue that would create. Great job, Bitwarden. BUT this incident needs to be resolved in the next release. This is very frustrating on a mobile device.

**Comment by kspearrin** [comment]
Fixed in v2.0

**Comment by pb1051** [comment]
Confirmed in 2.0 to be working
