### ISSUE TITLE
Opéra Mobile

### ISSUE THREAD

**Issue by Galiwyx** [bitwarden/mobile#504]
Hey,

I use Bitwarden for mobile, no problem with Firefox Mobile. I prefer Opera Mobile on my smartphone but Bitwarden popup doesn't appears when I want to login on a website.

Is it a bug ? I use the last version of Bitwarden (1.22.0) / Opera. I check auto fill settings on Android. Everything is ok. My phone is an OnePlus 7 Pro on Android P.

Thank you :)

**Comment by kspearrin** [comment]
Does Opera mobile support autofill services? You may need to use the accessibility service instead.

**Comment by Galiwyx** [comment]
Hey, 
None of both options seems work :(

**Comment by kspearrin** [comment]
You also need to make sure the browser's address bar shows. I think you can turn this on under opera settings.

**Comment by Galiwyx** [comment]
It's okay thank you
