### ISSUE TITLE
Saving via auto-fill doesn't seem to be working at all

### ISSUE THREAD

**Issue by yacoob** [bitwarden/mobile#506]
I've configured bitwarden on my Android device, and synced it to an existing account containing logins imported from a chrome browser. Enabled auto-fill service. So far so good, a pop up from bitwarden shows up on password fields and allows me to pick from saved data. There are some minor problems like positioning of the password list dropdown or the fact that it sometimes only pops up if you switch the control and focus the password field again.

I can't, however, seem to trigger a save of credentials from an application login field. As I understand, field needs to be marked in a specific way, so that Android understands that it's a password. I've picked an application for which previously I've saved a password successfully (via OS's auto-fill service) - Headspace. I've focused the password field, and bitwarden has shown the previously saved password. I've typed in new email, new password, and processed with the sign up. At no point has bitwarden picked up on the fact that there has been a new account created.

So, are saves supported? FWIW, I don't even know what *should* happen - a pop up? Notification? I'm keeping the vault unlocked for the test, and I can press '+' and add password by hand just fine. It then syncs to the server, and other clients.

Pixel 2, Android 9 (Pq3A.190605.003). Bitwarden 1.22.0 (1652)

Thanks!

**Comment by kspearrin** [comment]
> There are some minor problems like positioning of the password list dropdown or the fact that it sometimes only pops up if you switch the control and focus the password field again.

We cannot really control this. Android (or the host apps) are often glitchy with when it fires autofill events. We just respond to those events when they occur.

Saves should be supported. What should happen if a popup from the bottom should ask you to save these credentials to Bitwarden. This popup is handled by the OS, we just feed it with data. Saves work in my test app, but I'll need to look at this specific app to see what may be going on.

**Comment by kspearrin** [comment]
> I can't, however, seem to trigger a save of credentials from an application login field.

I just tested this with the headspace app and I was not able to reproduce the problem. Upon logging in, the autofill service prompted me to save new credentials with Bitwarden.

**Comment by yacoob** [comment]
Allright, clearly the problem is on my end then. Is there any good way for me to debug this? Event snooping? Logs? I have almost zero android development experience, but I'm happy to dig in here, if it improves things :D

**Comment by kspearrin** [comment]
I don't know of any way you could debug this on your side. Does the same prompt show for any app? Is it only this app that is the problem?

**Comment by yacoob** [comment]
No, I haven't noticed save prompt for any app I've tested it with. The fill-in service works (glitches described in first update aside), but I can't get the save to work. Are there any checks in the autofill service that would inhibit the prompt? I'm testing the whole thing with a self-hosted `bitwarden_rs` instance FWIW - maybe that's a factor?

**Comment by yacoob** [comment]
Things got substantially better in recent releases, so I'm going to close this one.
