### ISSUE TITLE
iOS: Multiple services on a single host are indistinguishable

### ISSUE THREAD

**Issue by wixoff** [bitwarden/mobile#507]
Bitwarden is working great on my iPhone and iPad, but there's one area that's pretty frustrating.

I run multiple services with web interfaces on a single server -- UniFi controller, Portainer, Grafana, Plex, etc.  When I try to log into one of these sites from my local network using Bitwarden, I can't distinguish among the returned matches.  I get something that looks like this:

![IMG_E8299](https://user-images.githubusercontent.com/945097/58709902-2241b300-8389-11e9-8546-ec9935a46693.JPG)

This isn't helpful!  All of the services, operating on different ports, show up as "for this website."

Can we get a match operation that takes into account port number, or is this an iOS limitation?

I guess as a workaround I can give each service a unique administrator username (like "admin-portainer" for example) but that seems suboptimal.  I'd rather have a single correct match so autofill will work.

**Comment by kspearrin** [comment]
Unfortunately, we don't have control over that interface or how matching works from the keyboard. We simply provide iOS with a database of credentials and associated URLs and it handles displaying the matches for whatever website or app you are on.

If you open the app extension with the "Passwords" or "Bitwarden" option, you should see more precise match detection that is available in our other apps.

**Comment by wixoff** [comment]
Thanks - I was afraid of that.  Apple doesn't give a lot of control around UI.  I'll close this.

In any case, the workaround (using different "admin" names for each) seems to work OK.  It's nicer than having to click through to the app because I'm lazy.  I want it in the list!
