### ISSUE TITLE
Auto Fill appears in com.android.settings app

### ISSUE THREAD

**Issue by matus201** [bitwarden/mobile#508]
Auto fill pop up appears in the settings app for fields like wifi passwords, device pin, etc. I don't think this is a desirable behaviour.

**Comment by kspearrin** [comment]
I've added `com.android.settings` to the exclusion list in the next version. Thanks.

**Comment by shoogle** [comment]
Sorry, but this was my favourite feature!

I deliberately added all my Wi-Fi passwords with the `androidapp://com.android.settings` URI to get autofill. I showed it to my friends and they started doing the same. I was even considering making a YouTube video specifically to highlight this little-known feature.

@kspearrin, please can you re-enable autofill for `androidapp://com.android.settings`. Maybe you could provide an option to turn it off for those that don't want it, but for the sake of discoverability I think it should be enabled by default.

(Google, if you're reading this, please create a URI for `androidapp://com.android.settings.wifi`)

**Comment by kspearrin** [comment]
I reverted com.android.settings from the hardcoded blacklist for next update.

If you want to blacklist com.android.settings, the user can add `androidapp://com.android.settings` to the URI blacklist for autofill under Settings > Options in the Bitwarden app.

**Comment by shoogle** [comment]
@kspearrin, thanks very much! For why WiFi is important and related suggestions, see:

- https://community.bitwarden.com/t/wifi-logins-and-organizations/6469
- https://community.bitwarden.com/t/share-wifi-passwords-via-qr-codes-and-nfc/6472

**Comment by quyleanh** [comment]
@shoogle could you please check this function again on Android 11. It seems does not work for me.

**Comment by shoogle** [comment]
@quyleanh, autofill suggestions stopped working a while a go in Android Settings but I don't think it's Bitwarden's fault; I think Google changed some APIs or something.

**Comment by quyleanh** [comment]
As I remember, Keepass2Android app does allow autofill. I check with 1Password, it does allow as well.
So the problem might be on Bitwarden side.
Could you please check @kspearrin? Thank you.

**Comment by winkler-winsen** [comment]
Please remove com.android.settings from exclusion list to grab WiFi passwords from Bitwarden

**Comment by winkler-winsen** [comment]
> I've added `com.android.settings` to the exclusion list in the next version. Thanks.

@quyleanh I was referring to this post from @kspearrin
