### ISSUE TITLE
High battery consumption caused by Autofill Service

### ISSUE THREAD

**Issue by jerryn70** [bitwarden/mobile#51]
Need some tweaks to reduce battery consumption.

**Comment by kspearrin** [comment]
Can you provide some information as to why you believe bitwarden is abnormally consuming your battery? We have not yet had this report. Is it tied to use of the autofill service?

**Comment by jerryn70** [comment]
Without using the app battery consumption is increasing time to time.

**Comment by jerryn70** [comment]
Well here is the battery consumption comparison between other password managers & bitwarden .
●Lastpass
●Dashlane 
●PassKeep2Android 
●Bitwarden

After boot (battery between 90% - 99%)
-Lastpass used : 1.3%
-Dashlane : 2.1%
-keepass2android : 0.3
-bitwarden : 5.2%

Battery between (5% -15%)

-lastpass : 7.3%
-dashlane : 9%
-Keepass2android : 5.2%
-Bitwarden : 16.2%

.I think bitwarden is always connected to net server and while others connect only when their is new entry or edit.
Next day After the phn boot i kept the phn ideal for 1 hr without opening bitwarden and checked the battery consumption of apps, bitwarden  scores the top consumption of 3.2%. You need to do something about this.

My phone:  moto x play 
Stock marshmallow 6.0.1
Non rooted

**Comment by kspearrin** [comment]
I suspect some of this has to do with the autofill service running. Can you try your tests with autofill turned off?

**Comment by jerryn70** [comment]
When i turned off auto fill, battery consumption is reduced .

**Comment by kspearrin** [comment]
Ok, that makes a little more sense. Do you have the autofill services turned on in the other apps you are comparing bitwarden to?

**Comment by jerryn70** [comment]
Yes auto fill is turned ON in other apps when i compared. 
The other thing that i noticed is, all other apps optimize battery (reduce consumption)  itself when phn is in ideal or they didn't find any auto fill columns for a while. But bitwarden is increasing its battery consumption time to time.

**Comment by jerryn70** [comment]
![picsart_04-22-10 29 01](https://cloud.githubusercontent.com/assets/23030460/25306484/8611c9b0-27ab-11e7-82dc-986bd060911f.jpg)
![picsart_04-22-10 29 52](https://cloud.githubusercontent.com/assets/23030460/25306485/861907f2-27ab-11e7-9cb0-8635ae64c0b8.jpg)

@kspearrin see the difference . Auto fill is enabled on both .

**Comment by jerryn70** [comment]
![screenshot_20170428-203053](https://cloud.githubusercontent.com/assets/23030460/25535346/55726226-2c54-11e7-9a1e-b68dcd4266f0.png)
![screenshot_20170428-203030](https://cloud.githubusercontent.com/assets/23030460/25535361/5fb71c68-2c54-11e7-8ae6-8a4a41a0f326.png)
![screenshot_20170428-203017](https://cloud.githubusercontent.com/assets/23030460/25535371/66236494-2c54-11e7-81e1-b3a5765022b9.png)
Only bitwarden has push notifications process, maybe this causing high battery consumption

**Comment by kspearrin** [comment]
Possibly. Can you try stopping it to see if it helps for you?

**Comment by jerryn70** [comment]
I have tried but no use still consumption is increasing

**Comment by kspearrin** [comment]
Yes, it is most likely the autofill service then. There are two things that are weird here:

1. You are the only person who has ever reported that this is causing battery issues for them.
2. Our implementation is basically exactly the same as Keepass2Android, yet you are saying theirs is not causing any problems for you.

Will have to continue to investigate.

**Comment by jerryn70** [comment]
See the difference between bitwarden n keepass2android 
![screenshot_20170428-220458](https://cloud.githubusercontent.com/assets/23030460/25538110/ffe48892-2c5e-11e7-9fd1-d8ac70eb9bcc.png)

**Comment by jerryn70** [comment]
There is no battery if i disable auto fill accessibility

**Comment by ralesi** [comment]
I have noticed this as well, on both rooted and unrooted devices.

**Comment by ralesi** [comment]
When rooted, I was tracking bitwarden at around 5% drain.

**Comment by jerryn70** [comment]
Yes I'm the only person reported battery consumption issue, maybe others are not concerned about battery life or maybe they didn't notice the consumption rate. 
 The thing i noticed is bitwarden's  cpu usage (battery consumption) is increasing in every minute. While keepass2android cpu usage (battery consumption) increase only when we browse sites or uses apps .  
I think bitwarden looks for password box ever time  even if the phn is in ideal , at same time keepass2android looks only if we open apps or sites .

These are my assumptions. I'm not a dev or tech .

But still im wondering how lastpass manages to make very low battery consumption. I think the use extra script for  accessibility auto fill service.

I Hope you will fix the battery issue in the next release.

**Comment by kspearrin** [comment]
@jerryn70 does it still drain the battery even if the phone is asleep?

**Comment by jerryn70** [comment]
Yes, but at that time consumption is slower . 

While phones screen is ON and not using any apps or anything it consumes 1% in every 1 minute.

While browsing sites or using any apps 1% to 5% consumption in every 1 minute 

While sleep 1% consumption in every 2 minutes

**Comment by kspearrin** [comment]
@jerryn70 I have pushed a new build (550) to the beta channel on Google Play store. Can you try it out and see if any improvements?

**Comment by jerryn70** [comment]
@kspearrin  i have tried but there is no difference. Still same as the current stable version

**Comment by Primokorn** [comment]
@jerryn70 I have the same issue on my device:
![screenshot_20170502-110327](https://cloud.githubusercontent.com/assets/5938828/25611586/f7320596-2f27-11e7-81f7-704cdac2fcc9.png)

**Comment by jerryn70** [comment]
@kspearrin @Primokorn all my test shows bitwarden uses doubles the battery of keepass2android  . If kP2A uses 10% bitwarden will be 20% or above. And we cannot compare bitwarden's consumption with lastpass because last pass is very good in battery saving. You can see comparison between lastpass on my previous post.
Here is the result of latest bitwarden with KP2A
![screenshot_20170504-172116 01](https://cloud.githubusercontent.com/assets/23030460/25702539/1a6417b6-30ef-11e7-8f8d-f2f3e22d884c.png)

**Comment by kspearrin** [comment]
Thinking about this more, real optimizations will only come if we reduce the number of times the service scans the screen looking for password fields. Currently this happens every time the app detects that there is a change to the screen (a lot!).

What if we changed it so that the notification was always present and when the user taps the notification, only then do we scan the screen to collect username/password field data? That way screen scanning is on demand instead of happening all the time.

The downside to this is of course that the app will no longer be as intelligent about offering the notification only when it can actually help.

**Comment by ralesi** [comment]
I think in a way this might be how LastPass works sometimes. There are always cases where I have to click the notification in order for it to determine what the auto fill.

Is there a way to get it to scan the window periodically or in the first 5 seconds and then stop?  

Is there a way when not rooted to disable individual services an app uses?

**Comment by ralesi** [comment]
Can we scan only when keyboard is opened? That would be a good time to guess that we are inputting login info.

**Comment by kspearrin** [comment]
@ralesi That's a possibility. We could make it a setting?

**Comment by jerryn70** [comment]
'Scan only when keyboard is open' is a good idea. 
Lastpass works like that , lastpass shows autofill only when we open keyboard or we click on username/password box . I think that's why lastpass has very low battery consumption.

**Comment by ep2017** [comment]
I've also noticed this. 

I'd be fine with having to click on either a Quick Tile or Bitwarden in the notification shade for it to scan the page/app for a login form. 

In LastPass, I often have to click on the password field for it to trigger the popup telling me that I have an option to auto-fill. It's convenient, but I would imagine this still taxes the battery on some level. 

My preference would be to have to manually click on a button to get the auto-fill option - saving the greatest amount of battery life.

**Comment by jerryn70** [comment]
@kspearrin As you said the service scans the screen looking for password fields everytime when the app detects screen changes.
My question is this, is the screen scanning rate is same as keepass2android or higher.?

**Comment by kspearrin** [comment]
@jerryn70 

As far as I know, our implementation is identical to KP2A.

I will release a beta sometime soon with some changes that you can test for me.

**Comment by jerryn70** [comment]
@kspearrin just tag me when new beta is available. I will test n report back.

**Comment by kspearrin** [comment]
@jerryn70 Will do. I plan to start working on it soon. Thanks for the testing thus far.

**Comment by kspearrin** [comment]
@jerryn70 Can you send me an email at https://bitwarden.com/contact so that I can send you some custom builds to try?

**Comment by kspearrin** [comment]
@jerryn70 and others:

Here is a custom build that tests the strategy we discussed above about always showing the notification and only scanning for password fields whenever the autofill is attempted.

https://ci.appveyor.com/api/buildjobs/4gby8sxkvhjh5b10/artifacts/com.x8bit.bitwarden-767.apk

Please let me know if it helps at all.

**Comment by jerryn70** [comment]
@kspearrin The ways we discussed

1, Always show notification :- scan for password fields when we click on the notification.

2, Scan only when keyboard is opened.

3, Scan when we click on password field (like laspass)

So the 1st method is created . And iam testing it. 
Do you have plan for method 2 and 3 ?

**Comment by kspearrin** [comment]
No plans for 2 or 3 yet.

**Comment by ep2017** [comment]
I've been testing the new build since last night and there's a huge difference now - basically zero battery life with general use.  The feature works exactly as expected. 

I did have to set the notification (through Android) to "Low Priority) to get rid of the persistent icon and drop it lower on lists of notifications showing on the notification shade. But those are personal preferences.

**Comment by kspearrin** [comment]
@ep2017 I may be able to adjust that priority programmatically. What does the priority do to the notification (I'm not an Android user)?

**Comment by ep2017** [comment]
@kspearrin "Never make sound or vibrate. never peek and LED. Hide from lock screen and status bar. Notifications will be shown at the bottom of the notification center."

That's the official tool tip.  Private Internet Access VPN operates in "low priority" mode and it helps to unclutter things!

**Comment by jerryn70** [comment]
@kspearrin Success 😀😀
![screenshot_20170527-215359 01](https://cloud.githubusercontent.com/assets/23030460/26522878/cc27c0a2-4327-11e7-9e05-0035274dec35.png)
![screenshot_20170527-215411 01](https://cloud.githubusercontent.com/assets/23030460/26522880/d70bd756-4327-11e7-9b82-c680b36fe437.png)

**Comment by kspearrin** [comment]
Great! Any issues using the autofill that you have found?

**Comment by jerryn70** [comment]
@kspearrin  No issues . I will investigate more in coming days.

Can you please remove the app icon from the notification bar.? See  screenshot
![2017-05-27-22-40-51](https://cloud.githubusercontent.com/assets/23030460/26523122/2bebc62c-432e-11e7-846a-308a710463e3.jpg)

**Comment by ep2017** [comment]
@jerryn70 You can remove the icon now by setting Bitwarden to low priority for notifications as I described above (at least until this is an option to do it in the app).

**Comment by jerryn70** [comment]
@ep2017 i don't know how to do that. this is the default settings in my phone. In on stock marshmallow. Can you plz guide me .
![screenshot_20170528-094126](https://cloud.githubusercontent.com/assets/23030460/26526046/1fcd6934-438a-11e7-9fc8-b2006c577a91.png)

**Comment by ep2017** [comment]
@jerryn70 Ah,looks like Nougat makes it easier. 
![screenshot_20170528-002009](https://cloud.githubusercontent.com/assets/28403574/26526080/822e06c8-433b-11e7-84c8-7143d0dac144.png)

**Comment by jerryn70** [comment]
@ep2017 But users below android 7 has no way to get rid of it.

**Comment by jerryn70** [comment]
@kspearrin  Till  now there is no issues on the test version. When I tap on the notification it will correctly shows the matching result. The only problem I noticed is bitwarden icon on the notification  bar. Check my above post for its screenshot.

**Comment by ep2017** [comment]
@jerryn70 I'm sure the feature will be added in-app. I'm using that method because it's a temporary option in Nougat. I also don't like persistent icons for most things.

**Comment by Primokorn** [comment]
I think this issue shouldn't be closed.

This fix isn't perfect:
• it adds a persistent notification (one more line in the notification panel and I already have my firewall, VPN and Privacy Guard)
• seeing the notification was a way to see if a browser is supported. No notification in Firefox => bitwarden won't work.

> 3, Scan when we click on password field (like laspass)
This is the best solution that you should try to implement IMO.

**Comment by kspearrin** [comment]
@ep2017 @Primokorn @jerryn70 

New test build: https://ci.appveyor.com/api/buildjobs/nxfyju03xeb212v1/artifacts/com.x8bit.bitwarden-778.apk

Find these new settings under Settings > Features. Please try them and let me know if any issues.

- Always Scan (default)
- Scan When Password Field Focused
- Persist Notification (I adjust the notification priority to low for this setting)

![autofill](https://cloud.githubusercontent.com/assets/1190944/26555550/834ed81a-4463-11e7-8f82-a7371a812f70.png)

**Comment by ep2017** [comment]
@kspearrin Nice! They all seem to work as expected (tested in three different apps), but the persistent notification icon is still showing at the top of the screen (unlike when I manually switch it to low priority). 

In terms of battery consumption, is it safe to assume that persistent notification is the most battery friendly (since it never actively scans anything)?

**Comment by jerryn70** [comment]
@kspearrin 

There is a issue with 'scan only when password field clicked'

**Comment by kspearrin** [comment]
New build with more fixes @jerryn70 : https://ci.appveyor.com/api/buildjobs/9y5bvx63i0u1mjex/artifacts/com.x8bit.bitwarden-783.apk

This build also adjusts the notification priority for "Persist Notification" to the lowest setting that I can set @ep2017 . Let me know if it has any affect:

**Comment by ep2017** [comment]
@kspearrin I can't seem to get the auto fill service to enable (I've even uninstalled/reinstalled).  It says that Bitwarden's accessibility option is "on", but the app stays: Status: Disabled.

**Comment by kspearrin** [comment]
@ep2017 Just close the autofill screen and navigate back to it. It should show it enabled. It doesn't auto-refresh when you back out to it from the android autofill settings menus.

**Comment by ep2017** [comment]
@kspearrin Yeah, that's what I've been doing for the last several builds, but it's refusing to switch to "enabled" and the notification icon isn't showing up regardless of the setting. 

Let me revert to the previous build and report back...

**Comment by ep2017** [comment]
@kspearrin Ok, I uninstalled 783 (reverted the accessibility setting back to "off"first), rebooted, then reinstalled 778.

Turned auto-fill back on SUCCESSFULLY.

So I repeated the steps, but installed 783 and it won't even start the app - lots of errors in the logcat. 
![screenshot_20170529-214822](https://cloud.githubusercontent.com/assets/28403574/26565370/a149cbae-44b8-11e7-890f-69a25c0fd581.png)

**Comment by kspearrin** [comment]
@ep2017 try https://ci.appveyor.com/api/buildjobs/vi6s0co30m8ckjff/artifacts/com.x8bit.bitwarden-784.apk

I was playing with the build target on the last one as well which may have screwed stuff up.

**Comment by ep2017** [comment]
@kspearrin 784 works.  The icon is still on the top bar, though.

**Comment by kspearrin** [comment]
@ep2017 See https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Priority .

I tried default, low, and min. The build you have now is setting priority to min for the persist mode. Not sure what else I can do 🤷‍

**Comment by ep2017** [comment]
@kspearrin I suspect that many apps simply work around the problem by hiding the icon as described here:
https://forum.xda-developers.com/showthread.php?t=1286318

> The magic happens in two steps :
we move the icon to the edge of the bar so that it doesn't take some place between 2 other icons
we replace the original icon with a transparent 1x1px icon (R.drawable.icon_hidden)

**Comment by Primokorn** [comment]
_Scan When Password Field Focused_ is still the best solution but it doesn't work on my end (v784).
With _Persist Notification_ we don't have any indicator that a filed can be autofilled.

Both alternatives use less battery (good news) but we can still notice an increase of consumption even when there's no field to autofill on the screen.

Check [this](https://ncloud.zaclys.com/index.php/s/AN0solDKKXJjLgB) out.

**Comment by jerryn70** [comment]
@kspearrin

Version : 784.
method : scan on when password field focused .

when i click on the password field , auto fill notification shows and immediately it will remove from the notification panel.  This issue occurs  only on some sites. 
Example try this : 

https://www.desidime.com/login

@ep2017 Test the above link with 'scan only when password field focused' method

**Comment by kspearrin** [comment]
@jerryn70 @ep2017 @Primokorn 

New build with more fixes to the password field focus option:
https://ci.appveyor.com/api/buildjobs/k0wr6ub3mw8r1c2m/artifacts/com.x8bit.bitwarden-785.apk

**Comment by ep2017** [comment]
@jerryn70 The field focus seems to work with the 785 build. 

@kspearrin 785 crashed on first start, but seems fine now. Will report if that happens again.

**Comment by Primokorn** [comment]
It's working now on the password field but not on the login field.
High battery consumption when opening a new screen (no changes)

Finally the notification doesn't disappear after returning to a previous web page.

**Comment by kspearrin** [comment]
@Primokorn It's only suppose to work on the password field.

> Finally the notification doesn't disappear after returning to a previous web page.

Can you explain the steps for this one please?

**Comment by jerryn70** [comment]
v785  is not showing favorites and my vault. It always loading...........

**Comment by kspearrin** [comment]
@jerryn70 Try restarting the app?

**Comment by jerryn70** [comment]
Restart didn't worked.  Force stop clear data worked .

But another issue is  start-up take too much time . 
This happens only if I remove bitwarden from recent apps ( means removing minimized app)

**Comment by kspearrin** [comment]
@jerryn70 Cold start times are a known problem. Unless the startup time is different/worse in these builds than previous, lets leave that discussion on another topic.

**Comment by jerryn70** [comment]
I know the cold startup issue, but the issue I said is not cold startup.  Anyway lets leave that because now after few start and stop that issue is solved.

**Comment by Primokorn** [comment]
@kspearrin 
> Can you explain the steps for this one please?
1. I open [https://zimbra.free.fr](https://zimbra.free.fr) (webmail of my ISP) from the search results of **Startpage.com** (with Firefox Focus Blink Edition).
2. I select the password field ==> bitwarden's notifications shows up
3. I press the Back button of my phone ==> the keyboard is closed
4. I press the Back button of my phone ==> back to the search results and the notification is still there.

**Comment by jerryn70** [comment]
I reproduced primokorn's issue in brave browser and focus browser. There is no issues with brave but there is issue with the focus . Its a browser specific issue.

What about  having  'time out' settings for auto fill notification ? 
Like after 20 seconds (or any other seconds/minutes choosen by the user) notification will be removed automatically.  This will help to solve the issue (maybe be a temporary solution)

**Comment by kspearrin** [comment]
@Primkorn Firefox must not be sending the proper accessibility event for the back button change. Can you confirm that if you do another action, like go to another page or background the app that the notification will go away then?

**Comment by jerryn70** [comment]
@kspearrin Battery result of 'scan only when password field focused'.
And I didn't find any issues with this method. 



![](http://i.imgur.com/YTD6BjZ.png)

![](http://i.imgur.com/RenBCxO.png)

**Comment by kspearrin** [comment]
@jerryn70 Great! Can you try out the persist notification option for some time as well to make sure no issues? If all is good I will release this version soon.

**Comment by jerryn70** [comment]
@kspearrin  There is a bug. All 3 methods have this same issue.

Open brave browser - open site 1 and immediately switched tab and open site 2. 
 Then switched tab to site 1 and try auto fill 
- no notification for the default method,.
-no notification for scan only password field focused.
- Always on notification method Not filling the field.


Everything is working on the site 2 .


Example If 1 open 3 tabs immediately then bitwarden won't recognize tab 1 and 2. Only The last created tab is  recognized

**Comment by kspearrin** [comment]
@jerryn70 I cannot seem to reproduce that using the Android browser in the emulator. It sounds like some events might not get fired when switching tabs or something. Can you see if it happens in other browsers besides brave?

**Comment by jerryn70** [comment]
@kspearrin  i tested it with tunga browser and it also have that issue

**Comment by jerryn70** [comment]
@kspearrin If 2 tabs load at the same time . Bitwarden recognize only the 2nd tab.  And its not showing auto fill for tab 1 .  It shows only for tab 2. 
After showing auto fill on tab 2, if we switch to the 1st tab then it will show auto fill.
[brave Test.zip](https://github.com/bitwarden/mobile/files/1047147/brave.Test.zip)


[tunga test.zip](https://github.com/bitwarden/mobile/files/1047174/tunga.test.zip)

**Comment by jerryn70** [comment]
Iam facing the same issue that early post by Primokorn 
```
1. I open https://zimbra.free.fr (webmail of my ISP) from the search results of Startpage.com (with Firefox Focus Blink Edition).
2. I select the password field ==> bitwarden's notifications shows up
3. I press the Back button of my phone ==> the keyboard is closed
4. I press the Back button of my phone ==> back to the search results and the notification is still there.
```

The issue is with password field focus method.  I faced this issue in application like flipkart app, jabong app etc. 
The notification automatically removes after 30sec but IMO 30sec is too long .
15sec is enough i think. 

Iam using v798

**Comment by kspearrin** [comment]
@jerryn70 Unfortunately within non-browser applications I cannot detect when the password field is no longer there (without consumer your battery), which is why it is on a 30 second timer.

**Comment by jerryn70** [comment]
@kspearrin okey then there is no other issues. I think now you can release it to public.

**Comment by kspearrin** [comment]
v1.6.1 is now available. Thanks all for the help in testing this.

**Comment by dougmaitelli** [comment]
Just noticed today a battery consumption of 22% after last update.

**Comment by Primokorn** [comment]
@dougmaitelli Which option do you use to get the bitwarden notification?

**Comment by dougmaitelli** [comment]
@Primokorn Was using the default settings, didn't noticed it was the most battery consuming one.

Thanks,

**Comment by Primokorn** [comment]
@dougmaitelli Yes, not a good idea for newcomers indeed. (@kspearrin what about switching to a more battery-friendly option by default? Don't you have bad ratings on Google Play?)

**Comment by dougmaitelli** [comment]
@Primokorn Also, the way I understand is that the app does not take advantage of the new auto fill services features on Android, this is why the scanning of fields on screen is needed.

Maybe it would make sense to invest in this new feature?

**Comment by Primokorn** [comment]
@dougmaitelli #57

**Comment by jerryn70** [comment]
@Primokorn but we need android 8.0 device . Iam i correct ?

**Comment by Primokorn** [comment]
@jerryn70 Yep an Oreo firmware. (OT here btw)

**Comment by dougmaitelli** [comment]
@jerryn70 For the new auto complete features you would need an Oreo device, but old phones would work with the old feature anyway.

**Comment by tandr** [comment]
Fellas, I installed bitwarden a week ago, and now my battery gets to 70% overnight, where previously it was losing 2-3% maybe.
I don't think this bug is fixed.
