### ISSUE TITLE
Android app and Chrome

### ISSUE THREAD

**Issue by Chippel** [bitwarden/mobile#519]
I switched from Firefox to Chrome and I have issues when using the auto fill option. On a lot or sites I have to use the auto fill accessibility instead of auto fill since Bitwarden won't put my login incredencials there. So far so good. But when I click on the Bitwarden app it takes like 20 seconds for the app to load. It's kinda annoying that way. I have no problems with speed and the accessibility feature when using Firefox. I'm on a Galaxy S10e with Android 9.

**Comment by kspearrin** [comment]
Can you try v2.0 that is in beta on the play store and see if it is any faster?

**Comment by djsmith85** [comment]
Hi @Chippel, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
