### ISSUE TITLE
[BUG] Switching apps returns to the lock screen

### ISSUE THREAD

**Issue by junderw** [bitwarden/mobile#524]
Using Android Beta.

Reproduce:

1. Turn on Fingerprint unlock
2. Set autolock to 5 minutes
3. Open an entry
4. Hit the switch app button on the lower left of any Android device's screen and switch to another app (chrome etc.)
5. Hit the switch app button again and return to Bitwarden after a couple seconds.

Expected:
- 5 minutes has not passed, so expect to be able to continue copying data immediately without needing to unlock or to navigate back to the item I had open.

Result:
- The lock screen asks for my fingerprint, and after authorizing, I am brought to the main vault menu, and have to go digging for the item again.

Compromise:
- At the very least, if we must lock after every app switch, at least bring me to the same page I was at when I switched... also, the app lock time setting seems useless if this is a desired effect...

I am assuming it's a bug, but let me know if it isn't.

**Comment by kspearrin** [comment]
This should be fixed now in the latest beta version, build 1870 (rolling out now).
