### ISSUE TITLE
Not working on Samsung Internet

### ISSUE THREAD

**Issue by Chippel** [bitwarden/mobile#525]
Hey. Is it somehow possible to get Bitwarden working with that browser? I'm kinda confused why it's not working since the browser is based on Chromium isn't it? No issues with the new Edge and Chrome browser. But since I'm a Samsung user I would really like to use that browser but I can't if I can't use the auto fill function not the accessibility feature.

**Comment by kspearrin** [comment]
There isn't anything that can be come. As far as I can tell, their browser (unlike all others that we support) does not expose the things necessary to detect autofilling.

**Comment by fvlaicu** [comment]
it works with 1password - so it is possible.

**Comment by sleepyhound** [comment]
just curious, is this going to be reopened now that it's reported to be working 1password? could bitwarden use similar functionality?

**Comment by T-bond** [comment]
I would also like Samsung Internet support.

**Comment by mportune-bw** [comment]
We discovered that Samsung uses a whitelist for password managers.  Their latest beta (12.x) works with Bitwarden, though not for everybody for some reason (see #895)

**Comment by douglasparker** [comment]
> We discovered that Samsung uses a whitelist for password managers. Their latest beta (12.x) works with Bitwarden, though not for everybody for some reason (see #895)

I like many others in the issue you referenced still have major problems with the autofill service for Samsung Internet. Are you guys able to investigate this further?
