### ISSUE TITLE
Toggle to turn off splash screen

### ISSUE THREAD

**Issue by killoid** [bitwarden/mobile#529]
the splash screen always makes the app to launch delayed when it is launched after a device has been restarted. an option to turn off the splash screen or completely removing it would be great. using the latest beta from google play.

**Comment by kspearrin** [comment]
Turning off the splash screen is not going to make things any faster. A cold boot still ya to bootstrap the app whether you show a splash screen or not. The splash screen just gives you something to look at while it’s loading.

**Comment by killoid** [comment]
i guess it makes sense. thanks for your reply. i will close the issue.
