### ISSUE TITLE
Custom domains doesn't work on my Android device

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/mobile#53]
Hi,
I don't get it working. Here is my issue:
* [Turtl](https://play.google.com/store/apps/details?id=com.lyonbros.turtl) app.
* From a web browser, I'm logged from [this URL](https://mes.framanotes.org/users/login). Framanotes is using Turtl to host notes for its users.
* I added an **Equivalent Domain** from the web vault: `mes.framanotes.org, androidapp://com.lyonbros.turtl, com.lyonbros.turtl`

After pressing the bitwarden notification on my Android device it doesn't find the equivalent domain **mes.framanotes.org**:
> Logins for com.lyonbros.turtl

_bitwarden 1.4.0_

**Comment by kspearrin** [comment]
You shouldn't use the subdomain for the website. Use the base domain `framanotes.org, androidapp://com.lyonbros.turtl`

**Comment by Primokorn** [comment]
Ok, thanks.
