### ISSUE TITLE
Constant notification on emui 9.1.0

### ISSUE THREAD

**Issue by pb1051** [bitwarden/mobile#530]
I have a persistent notification that is on top of active apps with no password fields.

![Screenshot_20190611_191240_com android chrome](https://user-images.githubusercontent.com/6139274/59314887-ea861580-8c7c-11e9-8575-26c54f8ad5be.jpg)
![Screenshot_20190611_190328](https://user-images.githubusercontent.com/6139274/59314892-ed810600-8c7c-11e9-8f0e-160f09a2a68e.jpg)
![Screenshot_20190611_190110](https://user-images.githubusercontent.com/6139274/59314895-f07bf680-8c7c-11e9-988c-c387dd072b88.jpg)

**Comment by pb1051** [comment]
I'm running the current beta as of 2019/6/11

**Comment by kspearrin** [comment]
Can you adjust the priority of the notification so that it only shows in the notification bar? That is the expected behavior.

**Comment by pb1051** [comment]
> Can you adjust the priority of the notification so that it only shows in the notification bar? That is the expected behavior.

This is a new OS to me. I had to turn off the "Banner" setting in notifications. All is resolved.
