### ISSUE TITLE
TOTP working without premium

### ISSUE THREAD

**Issue by djohannes** [bitwarden/mobile#532]
I don't have Premium but I still can use TOTP in the app, I can even create new entries with TOTP.

**Comment by kspearrin** [comment]
I am not able to reproduce the issue. Are you a member or an organization that grants premium access?

**Comment by djohannes** [comment]
@kspearrin no, I can't use it on other devices and for example 2FA is also limited. I am on Android 9, Pixel 2 and just upgraded. I was Premium before

**Comment by djohannes** [comment]
@kspearrin If you like I can also send you my email address per email so you can check if it's my account, but I was never in any organisation, I don't have premium anymore and I can't use it on other devices.

**Comment by djohannes** [comment]
@kspearrin With the new beta from today I can't see the TOTP in the details of an entry anymore, BUT I can still copy it via the 3 dots next to the entry -> Copy TOTP and it still works with autofill and I can still add new entries with a TOTP code. So it's still working.
And no there is no organisation, I just was premium some time ago. On other devices it isn't working (and other Premium features aren't working either like attachments).

**Comment by kspearrin** [comment]
Should be resolved now in next update. Thanks.
