### ISSUE TITLE
Autofill service not working for CREDEM bank app

### ISSUE THREAD

**Issue by consdel** [bitwarden/mobile#533]
Autofill service not working on [CREDEM](https://play.google.com/store/apps/details?id=com.CredemMobile) Android app. 

Device: Xiaomi Mi A1
OS: Android 9
bitwarden App version: 2.0.6

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
