### ISSUE TITLE
IOS Auto-Filling Not Working With Firefox or Brave

### ISSUE THREAD

**Issue by cwmke** [bitwarden/mobile#54]
I have enabled the app extension option for IOS and confirmed it works with Safari and Chrome but no sites are found when using it with Firefox and Brave. I tested with an Ipad Air 2 that is up to date.

**Comment by kspearrin** [comment]
We've submitted pull requests to fix this issue and are waiting for Firefox and brave to patch and release an update for them. See:

https://github.com/brave/browser-ios/pull/744
https://github.com/brave/browser-ios/pull/746
https://github.com/mozilla-mobile/firefox-ios/pull/2497

Please vote for them on those PRs
