### ISSUE TITLE
Unable to turn on accessibility service. 

### ISSUE THREAD

**Issue by stuartmaxwell** [bitwarden/mobile#540]
Since the latest update was released I'm unable to turn on the accessibility service without disabling secure startup. I get the following pop-up when attempting to enable the feature: "Bitwarden and Secure startup cannot be turned on at the same time. Secure startup will be turned off."

Is this expected behaviour?

**Comment by kspearrin** [comment]
I am not sure why accessibility services would affect that, however, according to my Googling, you can disable secure boot, enable the service and then enable secure boot again and it should work.

**Comment by djsmith85** [comment]
Hi @stuartmaxwell, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
