### ISSUE TITLE
Mobile app does not display subcollections

### ISSUE THREAD

**Issue by mprasil** [bitwarden/mobile#542]
Steps to reproduce:

1. In the organization create two collections: `a` and `a/b`. 
2. In the web interface, they are shown as `a` and `b` that is nested under `a`. (as expected)
3. Mobile client only shows `a` (the ciphers in the `a/b` collection can still be searched, but the collection is not visible in the interface)

**Comment by kspearrin** [comment]
Fixed next version. Thanks.
