### ISSUE TITLE
Autofill does not work for M1 finance android app

### ISSUE THREAD

**Issue by Fealthas** [bitwarden/mobile#543]
Password field fills ok.
Email field doesn't bring up prompt to autofill, nor does it get autofilled.

**Comment by Fealthas** [comment]
entering a custom field:
regex = .*email.* 
Causes it to be filled properly.

Can close I guess? But it would be nice if it was smart enough to figure this stuff automatically.

**Comment by Fealthas** [comment]
Nevermind. Stopped working again.

**Comment by Fealthas** [comment]
It sometimes succeeds to fill in the email field, after using the accessibility api/notification method as opposed to the android autofill.

It does so on the 2nd try though, never the first.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
