### ISSUE TITLE
Android app often needs two attempts to auto-fill

### ISSUE THREAD

**Issue by scotsman42** [bitwarden/mobile#544]
Steps to re-produce
1. Using Chrome on Android go to website such as https://myaccount.nytimes.com/auth/login
2. Tap password field (no autofill is displayed)
3. Open notifications and select Bitwarden Auto-fill Service
4. select nytimes.com from "items for nytimes.com"
5. returned to Chrome, form is not filled in
6. open notifications and select Bitwarden Auto-fill Service
4. select nytimes.com from "items for nytimes.com"
5. returned to Chrome, form is now filled in.

Occurs for most sites, doesn't appear to be site specific.
Auto-fill Service: Enabled
Auto-fill Accessibility Service: Enabled

Bitwarden (Android) version 2.0.6 (1938)
Chrome 74.0.3729.149
Android 10; Pixel 3 Build/QPP4.190502.019, 
Also re-producible on Android 9

**Comment by kspearrin** [comment]
After step 5, try tapping the password field on page again. Does it fill it then?

**Comment by mindrunner** [comment]
Can confirm this, however in step 4, I always observe that I do not autofill for "sitename.com", but for "com.google.chrome". Or any other appid, depending on the chrome-version I am using. This happens with 
- chrome
- chromium
- brave
- probably all other browsers on chrome base as well

> After step 5, try tapping the password field on page again. Does it fill it then?

Second attempt always works. It seems, that on first autofill, the website name is not detected, but only the browser's app id. 

Can provide a screencast, if that helps. But I suppose, this is easily reproducible.

I am on OnePlus 5, latest Android (9.x)

**Comment by mportune-bw** [comment]
@scotsman42 Is this still happening for you with the latest beta? The accessibility service was completely rewritten.

**Comment by mindrunner** [comment]
On my side that looks way better now. Haven't experienced that for a while now. Imho, this can be closed. I will come back here if it happens again.

**Comment by mportune-bw** [comment]
Great, glad to hear it!
