### ISSUE TITLE
Fennec F-Droid (Firefox) doesn't autofill on Android

### ISSUE THREAD

**Issue by logic** [bitwarden/mobile#548]
Looks like `org.mozilla.fennec_fdroid` just needs to be added to [this list](https://github.com/bitwarden/mobile/blob/master/src/Android/Autofill/AutofillHelpers.cs)?

F-Droid link for the build: https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/

**Comment by kspearrin** [comment]
Available next release.
