### ISSUE TITLE
android: disable website icon toggle bug

### ISSUE THREAD

**Issue by KCAS** [bitwarden/mobile#549]
samsung galaxy s10e snapdragon 855 on latest asf1
downloaded bitwarden from play store
unlocking via password/pin/fingerprint

disable website icon even if toggled will still show website icons but does not happen most of the time.
can reproduce the bug by locking bitwarden via the lock now option in settings, then unlocking it shows website icons even if disable website icon is toggled. have to re-toggle it back for it to disable website icons again.

**Comment by kspearrin** [comment]
Fixed next version. Thanks.
