### ISSUE TITLE
Equivalent Domains on Android

### ISSUE THREAD

**Issue by accountForIssues** [bitwarden/mobile#550]
I don't know if this is a known issue but it seems to like the equivalent domains are not working on mobile.

I have tried amazon and ebay domains. The uri's for them are "https://amazon.com/" and "https://signin.ebay.com/" with default matching (never changed the settings).

Everything works fine on desktop Chrome but on Android (tried on Firefox Klar) only the actual uri works i.e. amazon.com and ebay.com. If I visit say amazon.de, it'll prompt me to go the vault to fill the items but will return zero results for "items with amazon.de".

I know I can search for the actual amazon.com and fill them using those details and then add another site but then the equivalent domain feature would be redundant.

Is there anyway to fix it ? I'm assuming the equivalent domains should work on all platforms. Am I wrong and missing something ?

Device: Samsung Galaxy S9+ with Android 9 and latest Bitwarden

**Comment by kspearrin** [comment]
Fixed next version. thanks.
