### ISSUE TITLE
[Android] bitwarden.com used in UI when self-hosted url variable is set

### ISSUE THREAD

**Issue by karelvanhecke** [bitwarden/mobile#552]
Android 9
Bitwarden Android App version: 2.0.6

Expected:
`self-hosted url variable: vault.domain.tld`

`Logged in as user@email on vault.domain.tld` on unlock screen
Web Vault under settings should direct the user to `vault.domain.tld`

Actual:
`self-hosted url variable: vault.domain.tld`

`Logged in as user@email on bitwarden.com` on unlock screen
Web Vault under settings should direct the user to `vault.bitwarden.com`

Note: This doesn't affect functionality, it still connects to the self-hosted instance.

**Comment by kspearrin** [comment]
What values are you using in the environment settings page? Just base URL or web vault URL too?

**Comment by karelvanhecke** [comment]
Just the base URL.

**Comment by kspearrin** [comment]
Should be fixed next version. Thanks.
