### ISSUE TITLE
"There are no items in your vault." [Android]

### ISSUE THREAD

**Issue by mcclure** [bitwarden/mobile#558]
I have been using Bitwarden on Mac and on Android successfully for several months.

Today, I opened up Bitwarden on my Android. It said "There are no items in your vault." Used to there were items listed. I tapped the vertical … menu and said "sync". Nothing happened. I tried selecting "sync vault" in the File menu on mac (where my data is all still present), then "sync"ing on Android. Nothing happened. I tried "Add an item" on the Android side. I added a new account. I added a "secure note". I said "sync" again. Still neither the items I expect to sync from my mac *nor* the items I added inside Android appear on Android. I tried exiting both the Android and the Mac and logging back in. I confirmed both are logging in with the same account name. Still the Android vault is empty. I tried switching from Wifi to 4g because another issue on this site said to. I tried rebooting the phone. Still nothing.

How should I proceed?

**Comment by kspearrin** [comment]
Have you tried reinstalling the app? I am not sure.

**Comment by mcclure** [comment]
I uninstalled and reinstalled the app. When I logged in again it downloaded all my passwords and everything was correct. My problem is now resolved. You might want to be worried about this if this is a thing that can happen. Like, what if the store on my phone had been my only copy? The store would have been lost. I guess it isn't worrying about if this is the only time this has been seen.

**Comment by kspearrin** [comment]
Your data is always stored on the server. So it can be accessed from any device. I am not sure what caused your device to not be able to access that data, but I’m glad you are sorted now.

**Comment by mcclure** [comment]
Thanks for the help
