### ISSUE TITLE
[Bug][IOS] Bitwarden crashes after enabling fingerprint 

### ISSUE THREAD

**Issue by urvish0215** [bitwarden/mobile#559]
After enabling the fingerprint option in the Bitwarden app, Bitwarden locks the vault and asks for fingerprint, and when you fingerprint-unlock it, it crashes immediately. 
Then if you reopen the app again, it will ask you for your fingerprint, and when you fingerprint-unlock it, it crashes again. Repeat and same result.

But if you use cancel the fingerprint request and password-unlock it, it works properly.Then If you lock it again, fingerprint-unlock also starts working properly.

You can replicate this issue by disabling the fingerprint option in the bitwarden app and then re-enabling it.

Device Details:
Iphone 6s, IOS 12.3.1, bitwarden 2.1.0

**Comment by kspearrin** [comment]
I have not been able to replicate the issue. Could you try reinstalling and see if that changes anything?

**Comment by urvish0215** [comment]
I deleted and reinstalled the app.
It looks like this bug only happens if you set the lock option to “immediately” instead of a time.

**Comment by kspearrin** [comment]
OK, I can reproduce it with "immediately" lock options. Should be fixed next version.
