### ISSUE TITLE
Autofill only works with Safari on iOS

### ISSUE THREAD

**Issue by nxferenc** [bitwarden/mobile#560]
Password autofill not working with Firefox/Chrome/Brave/etc browser on iOS.

**Comment by Crocmagnon** [comment]
Autofill works for me in Firefox iOS. I have to tap "Passwords" (over the keyboard) and then it opens Bitwarden window. It's not as integrated as Safari though where the username is directly shown over the keyboard.

**Comment by nxferenc** [comment]
I've reinstalled bitwarden, now autofill works.
