### ISSUE TITLE
iOS shows TouchId on iPhone X when using Finnish system language

### ISSUE THREAD

**Issue by Kaali** [bitwarden/mobile#561]
iPhone X only has FaceID, but Bitwarden settings shows TouchID not enabled in the settings when using Finnish system language. Tapping the item does nothing.

I switched my system language to English and the FaceID option replaced the TouchID option and worked fine. When switching language to Finnish, the FaceID remains enabled and works fine.

**Comment by kspearrin** [comment]
There was an error in the finish translations that caused this problem. Should be resolved next version.
