### ISSUE TITLE
Bitwarden autofill not working on Tutanota app

### ISSUE THREAD

**Issue by IOI-655321** [bitwarden/mobile#572]
See conversation with Tutanota staff here

https://old.reddit.com/r/tutanota/comments/cjcrv4/android_autofill_and_tutanota_app/

The Tutanota app just wont autofill using accessibility or oreo autofill, Tutanota staff tried with LastPass and Keypass XC and these apparently worked.

Scan for password field doesnt work, always scan doesnt work, persistant notification will autofill it bu theres never an oreo autofill prompt.

Can this be looked at please?

**Comment by charlag** [comment]
Please note that autofill *does* work with exactly same fields on [mail.tutanota.com](https://mail.tutanota.com)

**Comment by kspearrin** [comment]
I just tested this with the autofill accessibility service and it worked as expected. I do see some issues with the standard autofill service, so I am looking into that.

**Comment by kspearrin** [comment]
The reason the standard autofill service is failing is because I am not able to locate the package id of the tutanota app.

Currently, we look for ViewNode.IdPackage to locate this, however, this is always null on ViewNode's in Tutanota. Do you know why @charlag ?

https://github.com/bitwarden/mobile/blob/master/src/Android/Autofill/Parser.cs#L137

**Comment by kspearrin** [comment]
See https://developer.android.com/reference/android/app/assist/AssistStructure.ViewNode.html#getIdPackage()

**Comment by charlag** [comment]
@kspearrin because it's WebView I guess?

**Comment by kspearrin** [comment]
I am not seeing any properties that would give me the package id of the calling app in this case.

**Comment by kspearrin** [comment]
I've added a hacky workaround to extract a package id from the calling add's activity title. See https://github.com/bitwarden/mobile/blob/master/src/Android/Autofill/Parser.cs#L159

This seems to work. Will be available next release.

**Comment by charlag** [comment]
@kspearrin great, thanks, quite some users complain about this. I'm not sure why you need to get the package though.

**Comment by kspearrin** [comment]
We need the package id to identify what app you are autofilling. This is how we make autofill suggestions from the password vault.
