### ISSUE TITLE
iOS password length not working 

### ISSUE THREAD

**Issue by ThomasBahen** [bitwarden/mobile#575]
I recently changed a bank app's password from 16 characters to 40 characters. This password works with the AutoFill feature on my FF Bitwarden extension but not iOS. Changing the password back to a new 16 character password fixed the issue.

**Comment by kspearrin** [comment]
Is your bank trimming the password or something when you autofill it?

**Comment by ThomasBahen** [comment]
Yes, that was it sorry.
