### ISSUE TITLE
eBay app on iOS autofill issues

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/mobile#58]
See https://twitter.com/CryptoSquirreL/status/852231459146522625

**Comment by eliykat** [comment]
Closed as part of the effort to collect all autofill issues in #1389.

---

Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
