### ISSUE TITLE
Are TOTP codes stored in the local data store?

### ISSUE THREAD

**Issue by chasebrewsky** [bitwarden/mobile#581]
Out of curiousity, are TOTP codes stored in the local copy of our vault, or are those generally stored server side? I'm wondering about the security implications of what would happen if my device was compromised and the attacker had access to both my passwords and TOTP codes.

**Comment by kspearrin** [comment]
TOTP keys are stored the same way all other data in your vault is stored. Locally and on the server in encrypted form.

**Comment by chasebrewsky** [comment]
Awesome, thank you!
