### ISSUE TITLE
Keyboard stays light while using Bitwarden in OLED dark mode

### ISSUE THREAD

**Issue by A1p1n3** [bitwarden/mobile#588]
After setting the app theme to black the keyboard does not automatically go dark. 

iOS 12.4

**Comment by ijd** [comment]
@kspearrin UIKeyboardAppearanceDark

https://developer.apple.com/documentation/uikit/uikeyboardappearance/uikeyboardappearancedark

**Comment by kspearrin** [comment]
Added for next version. Thanks.
