### ISSUE TITLE
Doesn't auto suggest password on iOS with basic access authentication (Safari)

### ISSUE THREAD

**Issue by egalitarian** [bitwarden/mobile#589]
When I open a site in Safari protected by basic access authentication (the password pop-up window) Bitwarden does not auto-suggest password based on the URL. Instead I have to search the correct password manually every time.

Bitwarden 2.2.1 on iOS 12.4.1

**Comment by kspearrin** [comment]
This is really a limitation of the autofill API provided by iOS. If we aren't given the URL for the website currently in view, we can't filter to result list.

**Comment by egalitarian** [comment]
Let's hope they fix this. It doesn't make sense not give the URL.
