### ISSUE TITLE
Bug when highlighting a secure note

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/mobile#59]
Hi,
I can't take screenshots within bitwarden so here is a screenshot from another app.
When highlighting the text of a secure note I don't have the cursors:
![screenshot_20170414-092528](https://cloud.githubusercontent.com/assets/5938828/25036521/9ac0dd3c-20f4-11e7-8fc9-78f2fbf321dd.png)
I have to press the text to bring them out.

**Comment by kspearrin** [comment]
Duplicate? https://github.com/bitwarden/mobile/issues/50

**Comment by Primokorn** [comment]
Exactly. My bad.
