### ISSUE TITLE
Autofill not working with home screen wesbite apps

### ISSUE THREAD

**Issue by egalitarian** [bitwarden/mobile#591]
Cryptee is an encrypted cloud notes and photos service that has web frontend (url: crypt.ee). It works fine in Safari with Bitwarden. The problem is that Cryptee has something of an app installed by using Safari's Add to Home Screen and if you start it from there and try to get you password Bitwarden activates and shows the "Touch ID for Bitwarden" dialog but then no matter how much you try to authenticate using the fingerprint reader it does nothing.

Bitwarden 2.2.1 on iOS 12.4.1

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
