### ISSUE TITLE
android crash in loading vault

### ISSUE THREAD

**Issue by neptu39701** [bitwarden/mobile#595]
in android on my vault section  crash happens when you try to scroll not fully loaded list
android 7.1.1 Resurrection remix

**Comment by kspearrin** [comment]
Do you know how many items are in your vault?

**Comment by neptu39701** [comment]
18 and it happens on first load after sign in

On September 6, 2019 4:19:25 PM GMT+04:30, Kyle Spearrin <notifications@github.com> wrote:
>Do you know how many items are in your vault?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bitwarden/mobile/issues/595#issuecomment-528823592

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kspearrin** [comment]
Would you mind sharing a few timestamps on when a crash occurs so I can try to locate them in our crash logs.

**Comment by neptu39701** [comment]
Just happened in 23:03 in tehran time zone

(Switched to Stock rom,marshmallow, problem presists)

**Comment by neptu39701** [comment]
just changed my phone and using android 9 , issue resolved
