### ISSUE TITLE
A browser support (Naver Whale for Android)

### ISSUE THREAD

**Issue by HyungjooLee** [bitwarden/mobile#600]
I'm enjoying bitwarden but encountered a small problem with my new browser

Bitwarden seems to recognize Naver Whale as a application not a browser

In every attempt to log in at any website with Whale browser, bitwarden recommends password for Naver which is a search engine in Korea

**Comment by djsmith85** [comment]
Hi @HyungjooLee thanks to @ashthompson your requested browser is supported via bitwarden. Could you please close this issue.

**Comment by dongwoo21** [comment]
After the recent update (v.3.0.2.2), the accessibility id of url is changed to "url_bar_in_bottom" if I turn off the option "Show address bar at top" in the setting (i.e., url bar is located at bottom). If I select this option (i.e., url bar is at top), the accessibility id is still "url_bar" and there is no problem. Is it possible to fix this issue?
