### ISSUE TITLE
Android app generating invalid codes for Microsoft accounts (2FA)

### ISSUE THREAD

**Issue by pedroCX486** [bitwarden/mobile#604]
Hi there, 

My Android app is generating invalid codes for Microsoft 2FA. I noticed the QRCode gives an URI of sorts (for Microsoft Authenticator?). I tried adding the 2FA code generated on the web vault and it works flawlessly, but the codes generated by the mobile app are always invalid.

Device: Galaxy Note 9
Android: 9.0 Pie - September Security Release
Language: English (Same as desktop.)
Date and Time: GMT -3 (Recife Timezone - Same as desktop.)
Tried reinstalling? Yes.
Rebooted device? Yes.
Installed from Play Store.
Version: 2.2.2
Error on Device App: None.

**Comment by kspearrin** [comment]
Is your system time incorrect on your mobile device?

**Comment by pedroCX486** [comment]
> Is your system time incorrect on your mobile device?

No. I mentioned that in the post, both my computer and PC are synchronized to the GMT -3 timezone using through NTP servers. I don't fiddle with those settings, and both times match down to the second.

**Comment by kspearrin** [comment]
Can you share what your TOTP key value looks like? Is it just a base 32 string or a URI?

**Comment by pedroCX486** [comment]
It's in this format: xxxx xxxx xxxx xxxx

Same one on web generates a valid code, on mobile does not.

If I scan the qrcode on MS website it generates an URI but containing this string in it. I can't get the exact URI right now (no access to a computer right now, but will do in the morning).

**Comment by kspearrin** [comment]
Does it work correctly if you remove the spaces?

**Comment by pedroCX486** [comment]
On web, yes.
On mobile, no.

Also Microsoft generates a QRCode with this:
otpauth://totp/Microsoft:pedrocx486@gmail.com?secret=XXXXXXXXXXXXXXXX&issuer=Microsoft

XXXXXXXXXXXXXXXX being the token. I tried both the url and the token in the XXXXXXXXXXXXXXXX format and, both work on the web vault, but not on mobile.

**Comment by pedroCX486** [comment]
An update... I went to the vault on my browser on my phone. And the codes generated were also invalid. 

I tried installing the app on my work device (Moto G5 Play) and it also didn't work. There's something  I must be missing to connect the dots.

**Comment by pedroCX486** [comment]
An update... I went to the vault on my browser on my phone. And the codes generated were also invalid. 

I tried installing the app on my work device (Moto G5 Play) and it worked. I went ahead and wiped my personal device... And it works. I don't know what Samsung broke, but they screwed something in there.
