### ISSUE TITLE
iOS 13 password autofill freezes 

### ISSUE THREAD

**Issue by netvl** [bitwarden/mobile#606]
After I upgraded my phone to iOS 13, autofill of passwords with Bitwarden stopped working. When I press the “passwords” button above the keyboard when the caret is in a password field, a bitwarden splash dialog opens, but then it freezes and does not show any actual functionality. I have to switch to another app and then switch back to unfreeze the application in which I tried using autofill. Now I have to open the main Bitwarden app and then copy-paste passwords and logins manually, which is really frustrating.

**Comment by mattrobins** [comment]
I am having the same issue on iOS 13.1 that was released earlier today.

**Comment by kspearrin** [comment]
v2.2.3 is rolling out in the app store with iOS 13 fixes.
