### ISSUE TITLE
[iOS Login Problem]

### ISSUE THREAD

**Issue by Huradisc** [bitwarden/mobile#607]
Hello Everyone, 
I am contacting you today because i deployed Bitwarden with docker using this docker image : 
bitwardenrs/server
The deployment with docker worked correctly. I arrived to create my account without any problem. 
BUT
When i try to connect on bitwarden mobile with the same credentials i used on the internet, i got an error like : 
"Username or password wrong"
I would like to know if some has ever had this problem on iOS ? Have i something to enable on bitwarden web interface to allow mobile login ? 

Hope you could help me :)

Huradisc

**Comment by kspearrin** [comment]
Are you using https?

**Comment by Huradisc** [comment]
Hello, 

I solved the problem. 
I use HTTPS behind a reverse proxy. 
My mistake was:
I forgot to add my Bitwarden personnal address. 
Thx
