### ISSUE TITLE
iOS/ipadOS 13.x cannot login on selfhosted bitwarden instance

### ISSUE THREAD

**Issue by l0rda** [bitwarden/mobile#608]
Hello, 
i have own bw instance in docker container at local network.
CA certificate is added to ipad and iphone. It is fully trusted. I can login via browser, but mobile app says: "There is a problem connecting to the server". Of course, https is enabled. Container logs are empty, so i think there is problem with certificate.

This is started when updated to ios/ipados 13.1 (also maybe 13.0).

**Comment by nessor** [comment]
Can't confirm this with iOS 13 and iOS 13.1.

Are you trying to login the first time or are you already logged in while updating to the new iOS?

**Comment by l0rda** [comment]
On ipadOS was clean install.
On phone i was previously logged in. I tried to sync and it is not work, then logged out and tried to log in again, got this error.

**Comment by l0rda** [comment]
I found, what can be a problem:
https://support.apple.com/en-us/HT210176

Additionally, all TLS server certificates issued after July 1, 2019 (as indicated in the NotBefore field of the certificate) must follow these guidelines:
TLS server certificates must contain an ExtendedKeyUsage (EKU) extension containing the id-kp-serverAuth OID.
TLS server certificates must have a validity period of 825 days or fewer (as expressed in the NotBefore and NotAfter fields of the certificate).
Connections to TLS servers violating these new requirements will fail and may cause network failures, apps to fail, and websites to not load in Safari in iOS 13 and macOS 10.15.

**Comment by l0rda** [comment]
I confirm, certificate was issued at 9 july 2019 and has a validity period more than 825.
With new server certificate all work fine.
