### ISSUE TITLE
[iOS] Vault unlocked after restoring from iCloud backup

### ISSUE THREAD

**Issue by JamesMcMahon** [bitwarden/mobile#610]
I recently had to go through an 'Erase All Content and Setting' procedure with my iPad and then I restored the factory reset machine to an iCloud backup. After restoring I expected to have ro reenter my master password and 2FA but the vault was already unlocked and just required my fingerprint to open. The fingerprint, in this case, was newly configured during the setup process for my factory reset iPad.

Not sure this is a bug or expected behavior but it was a bit alarming to me so I figured I would report it. Is it possible for an attacker to restore an iCloud backup to a new device and get access to my vault?

Maybe a case of an encryption key being persisted [like they are for Android](https://github.com/bitwarden/mobile/issues/270).  I just wanted to put this on your radar in case there was anything unintentional here.

**Comment by kspearrin** [comment]
This sounds expected since your encryption key is persisted in the iOS keychain, which survives an application reinstall. We can probably do some detection on fingerprint changes to require typing the master password again, but that doesn't change the fact that the key is still persisted.

**Comment by JamesMcMahon** [comment]
Is the encryption key my master password or something else?

Didn't realize anything was saved to Keychain but that is probably me being about iOS security. I assume you need to save that to Keychain to enable Touch Id?

**Comment by kspearrin** [comment]
The master password is not persisted anywhere. Your encryption key is derived from your master password using PBKDF2.

Yes, to use Fingerprint we need to save the key.

**Comment by JamesMcMahon** [comment]
Makes sense to me. Thanks for your patience in explaining that.

Hopefully having it posted here will save you answering the same question again in the future.
