### ISSUE TITLE
[iOS 13] Text entered in search with dark mode enabled via System Settings is invisible

### ISSUE THREAD

**Issue by OnlinePlayer865** [bitwarden/mobile#612]
There is an issue with searching for an entry with iOS 13 and Dark Mode enabled via the iOS System Settings. 
With Dark Mode enabled and going to search for an entry, the text I type in is not visible. The text of what I am typing in is black, which makes it invisible with Dark Mode enabled.
If I turn on Light Mode via iOS System Settings and go to search for an entry in Bitwarden, the text I type is visible again. 

I do have the Nord theme enabled.

**Comment by Crocmagnon** [comment]
Here's a quick screen recording of the issue I also experience.

https://share.icloud.com/photos/0fmVkpk8boTZq0Sy37L24gyjw

![IMG_2464](https://user-images.githubusercontent.com/3630554/65942261-3677e880-e42d-11e9-8e9b-c8f114577725.gif)

**Comment by kspearrin** [comment]
Will be fixed in v2.2.4
