### ISSUE TITLE
Can't autofill anything other than login details on iOS

### ISSUE THREAD

**Issue by woobs** [bitwarden/mobile#617]
Issue #249 was closed a while ago, saying autofill of identity information is supported on mobile (Android).

Not sure if this is a bug or simply an unimplemented feature, but noticed I can't autofill credit card or identity information in Safari on iOS.

**Comment by kspearrin** [comment]
iOS Auto fill only supports filling usernames/passwords. This is a limitation of iOS itself so I am afraid there isn't much we can do.

**Comment by jcsteh** [comment]
Is it not possible to support this using an app extension (i.e. via the Share button)? For example, [1Password apparently supports this](https://support.1password.com/1password-extension-ios/).
