### ISSUE TITLE
Auto display keyboard when selecting search icon

### ISSUE THREAD

**Issue by mikey32230** [bitwarden/mobile#619]
When using the Bitwarden "extension" in apps or safari. When selecting the search icon, they keyboard is not automatically shown. In order to display the keyboard you must select the search icon and then also select the search bar.

In the actual Bitwarden app, if you select the search icon, the keyboard is immediately and automatically shown as expected.

I realize this is small, so hopefully easily to resolve. I just wanted to mention it.

iOS 13.1.2

**Comment by kspearrin** [comment]
Fixed next version.
