### ISSUE TITLE
Passphrase option missing from password generator in iOS “Extension”

### ISSUE THREAD

**Issue by mikey32230** [bitwarden/mobile#620]
When using the Bitwarden "extension" in apps or safari:

Select Add Item > Generate Password > the password generator page is missing any options to generate a “passphrase” based password.

In the actual Bitwarden app, if you select the generator tab, you are able to select a “passphrase” type password to generate as expected.

I realize this is small, so hopefully easily to resolve. I just wanted to mention it.

iOS 13.1.2

**Comment by aaron-meyers** [comment]
I just ran into this the other day as well. I thought that the mobile app must not support passphrase generation at all but glad to know it's only the extension. Would like to see this fixed still.

**Comment by mikey32230** [comment]
@mportune-bw Not being pushy at all. I understand development processes and priorities.
I'm actually just curious if its purely a bug, or if there is a reason or issue with implementation

**Comment by krystof-k** [comment]
Please fix this, really annoying… :(

Also it would be great being able to further customize the syntax (something like `{word with uppercase letter}-{another word}-{#####}`).

**Comment by FrederickTF** [comment]
I am currently going through all my passwords to change them to random passphrases, and this missing option requires me to do some weird gymnastics to changes my IOS app passwords, is there any ETA on this?

**Comment by eliykat** [comment]
Hi all, I've picked this up and I'm working on it, so hopefully you'll see some activity here soon.
