### ISSUE TITLE
Android 9.0 certain site autocomplete feature does not work.

### ISSUE THREAD

**Issue by sH1222J** [bitwarden/mobile#621]
Model: Galaxy S10
Browser: Mobile Chrome
App Version: 2.2.2 (2072)
Applicable site: naver.com

**Comment by djsmith85** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: https://github.com/bitwarden/mobile/issues/1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
