### ISSUE TITLE
Browser support request

### ISSUE THREAD

**Issue by Ariette** [bitwarden/mobile#622]
TF Browser is my favorite android internet browser, but bitwarden recognizes it as a normal application(via Autofill API), not as a browser.
I already read #600 , so I hope this information could help you support the browser.

Package name : [com.feedback.browser.wjbrowser](https://play.google.com/store/apps/details?id=com.feedback.browser.wjbrowser)
Accessibility id of url : addressbar_url

Thank you.

**Comment by kspearrin** [comment]
Thanks. I can add this. May I ask, how did you locate the accessibility id of the URL? I do this programmatically, but maybe you have some other way that makes it easy for users to locate?

**Comment by Ariette** [comment]
I simply used Google's [Accessibility Auditor](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor) to find out the id.
In fact, I can't be sure whether it is just what you need.... but I guess it is.

**Comment by kspearrin** [comment]
Not really sure how to use this browser since it's not in English and I can't navigate it well, but from my debugging, it looks like the URL field at the top is id `sliding_window_title`. Though this doesn't appear to be a field I can tap and change, so I am not entirely sure.

**Comment by kspearrin** [comment]
Nevermind, you were correct. I figured it out. It is `addressbar_url`.

Added for next version.
