### ISSUE TITLE
No autofill for DuckDuck Go or Vivaldi browser

### ISSUE THREAD

**Issue by Stephan-P** [bitwarden/mobile#623]
Even though support for the Vivaldi browser was [added to Bitwarden Android](https://github.com/bitwarden/mobile/commit/f657edf195d4770c610cf2cd03b88a5f00d5d033), I do not get any Autofill popups when browsing login pages.

Mine is a Nokia 3.1, with android 9 (september update), 
Pesky Nokia system app for battery optimization (Duraspeed) thorughly disabled,
Bitwarden v2.22.2 (battery optimization disabled), 
Bitwarden autofill framework service enabled,
Vivaldi 2.7.1624.219
DuckDuck Go browser 5.34.0

From the [Help/FAQ](https://help.bitwarden.com/article/auto-fill-android/) I gather that my Android 9 device should not require the Autofill accessibility service or am I getting this wrong?

**Comment by kspearrin** [comment]
Do we know if Vivaldi even has support for the auofill framework on their side?

**Comment by Stephan-P** [comment]
Vivaldi Android does have some issues re. password managers.
https://forum.vivaldi.net/topic/40841/vivaldi-for-android-and-lastpass/6


Stephan Paternotte
---------------------------------------------
E: stephan@paternottes.net

**Comment by Stephan-P** [comment]
Okay, I've tested a bit further.
With DDG, the Bitwarden autofill overlay pops up when I long press in the login entry field. It's not as automatic as I'd expect, but it's workable, possibly even preferable. 

In Vivaldi nothing seems to work in getting BW to connect.

**Comment by Stephan-P** [comment]
Assuming the problem lies with Vivaldi I'll close this issue.
