### ISSUE TITLE
iOS: Extension sheet freezes when swiped down

### ISSUE THREAD

**Issue by fefrei** [bitwarden/mobile#624]
On iOS, the extension can be locked up by an unexpected swipe. Here's how to reproduce it:

1. Open any app that can integrate with Bitwarden. We'll use Safari.
2. Open the share sheet.
3. Tap Bitwarden.
4. You'll see a Bitwarden background slide up, then see the authentication prompt appear within.
5. Authenticate, e.g. using Face ID.
6. The _Items_ menu appears. Grab it by its title, and slide it down.

The _Items_ menu is now dismissed, leaving the blank Bitwarden sheet behind. It cannot be dismissed, forcing a restart of Safari.
Instead, the action should be fully canceled when the sheet is swiped out.

I reproduced this on iPadOS 13, with Bitwarden 2.2.5 (59).

**Comment by kspearrin** [comment]
I can reproduce.
