### ISSUE TITLE
Support Korean browser Naver Welsh

### ISSUE THREAD

**Issue by sH1222J** [bitwarden/mobile#625]
<.
제발 기능을 제출하지 않는다면. 그[공동체 포럼][1]a다
제품 기능에 대한 토론에 투표를 제출하는 데 섹션.
[1]:https://community.bitwarden.com
-->
Not the way to code.
Can't you officially put it in?

**Comment by djsmith85** [comment]
Hi @sH1222J I think the browser you mentioned is now supported thanks to @ashthompson with PR #837. If that is the case could you please close this issue.
