### ISSUE TITLE
Auto-fill does not work on Firefox

### ISSUE THREAD

**Issue by HerrHulaHoop** [bitwarden/mobile#627]
Firstly, I'd like to clarify that I've been using Bitwarden for about 6 months and auto-fill used to work perfectly. However, since the past couple days, the auto-fill consistently does nothing across a variety of websites. If I click the notification icon and select the login detail to auto-fill, it will succeed only once out of ten attempts. So it's not like it doesn't work at all, but will require multiple attempts.

OS: Android 9 (Oxygen OS 9.0.9)
Phone: OnePlus 6
Bitwarden version: 2.2.2
Firefox version: 68.1.1

Firefox updated for me on 13th October so I suspect it changed something to cause this problem. And yes, both the Auto-fill service and Auto-fill Accessibility Service are enabled. The Auto-fill service still works flawlessly on Chrome, so this is a Firefox specific issue.

**Comment by kspearrin** [comment]
I just tried the Autofill Service on Android 9 with Firefox 68.1.1 and it seems to work fine for me. This is on an Android emulator, however, so it could be something specific with that type of device. Have you tried a device restart?

**Comment by HerrHulaHoop** [comment]
Wow... that fixed it. I can't believe that's all it was. I'm sorry for wasting your time :(
