### ISSUE TITLE
After update to Miui 9.1.0.217 no persistent notification

### ISSUE THREAD

**Issue by pb1051** [bitwarden/mobile#629]
I updated my Huawei P30 yesterday and after a restart the persistent notification stopped working. I'm on 9.1.0.217 now.

**Comment by kspearrin** [comment]
Have you confirmed that 1) The autofill accessibility service is still enabled and 2) your persist notification setting is still enabled?

**Comment by pb1051** [comment]
Go ahead and close this one. After toggling and toggling I found these were
the correct ones
