### ISSUE TITLE
Auto-fill Service notification keeps disappearing

### ISSUE THREAD

**Issue by THEOCKID** [bitwarden/mobile#632]
I've seen this issue elsewhere, and I've ensured that my Auto-fill service  and Auto-fill Accessibility Services are Running, and that in App notification settings the notifications are on. (Silent)  

Just can't seem to keep BW Auto-fill active.  New Galaxy Note 10+ but was same on prior Galaxy S9. I guess, more accurately, the notification doesn't always exist when I'm in a situation where I'd like it to be there for me to autofill fields.

Not a dev but I'm happy to do any troubleshooting or log-posting that you'd like me to do.  I love the app; just can't seem to get it to stay persistent

Note: I have been using the default "Always Scan" setting in BW, but just changed it to "Persist Notification".  I'll see how this works.

THANK YOU in advance for your time and work on this app.  It's just terrific.

**Comment by kspearrin** [comment]
It sounds like your device's OS may be disabling the accessibility service.  See https://dontkillmyapp.com/


Have you tried disabling the battery optimization settings for Bitwarden?

**Comment by THEOCKID** [comment]
I have actually, thanks.  But what's working for me now is the "persist notification".  Does what I want it to and I have no complaints.  @kspearrin thanks very much for the feedback and for your unending work on BW.   I fear the day you get tired of this and then I grudgingly have to go back to a 2013 version of mSecure....
