### ISSUE TITLE
Not logged out in Android app after changing password in web vault

### ISSUE THREAD

**Issue by jikamens** [bitwarden/mobile#633]
After I change my master password in the web vault, I'm not logged out in the Android app. When I tell the Android app to sync it claims it was successful (but wasn't really). When I edit and try to save a vault entry the app crashes. The only solution I've found is to explicitly log out and log back in. I should be forced to log in again automatically when my master password is changed.

**Comment by kspearrin** [comment]
Are you using Bitwarden cloud or on-prem server?

**Comment by jikamens** [comment]
Cloud

**Comment by kspearrin** [comment]
Thanks. I was able to reproduce. Fixed in next version.
