### ISSUE TITLE
No Support for VIA Browser  

### ISSUE THREAD

**Issue by ercan-akar** [bitwarden/mobile#634]
Hi,

Can you please add support for VIA Browser? Thank you.

**Comment by kspearrin** [comment]
via browser is already supported. You need to make sure the address bar is visible.

**Comment by djsmith85** [comment]
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.
