### ISSUE TITLE
[Chrome Android] Autofill fills password into user field

### ISSUE THREAD

**Issue by quthla** [bitwarden/mobile#640]
Autofill (not accessibility) fills password into user field in Chrome on Android

https://www.paypal.com/signin
https://accounts.google.com/

Maybe this needs to be tracked upstream too?

**Comment by kspearrin** [comment]
For whatever reason, the `InputType` of this email field is:

`Android.Text.InputTypes.ClassText | Android.Text.InputTypes.DatetimeVariationDate | Android.Text.InputTypes.TextVariationPassword | Android.Text.InputTypes.TextVariationShortMessage`

We treat input types with `TextVariationPassword` as a password field.

**Comment by quthla** [comment]
It's obviously wrong then. No such issue in Firefox Preview (again). 

I assume this must be tracked upstream too.

**Comment by Rollk1** [comment]
Same issue here.

**Comment by quthla** [comment]
It works fine with LastPass and EnPass.

Maybe @mportune-bw is able to fix this?

**Comment by perariontaeadastra** [comment]
+1. Brave, Chrome... same story

**Comment by quthla** [comment]
@mportune-bw @kspearrin Still an issue on Amazon, PayPal etc with native autofill service

@fmeum sorry for mentioning you again but is this also an issue with your password manager or is it only an issue with Bitwarden?

**Comment by fmeum** [comment]
At least for https://accounts.google.com and https://paypal.com/signin the input type of the Autofill node is `0xD1`, which corresponds to `TYPE_CLASS_TEXT | TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS`. This appears to be a Bitwarden-specific issue.

**Comment by quthla** [comment]
Thanks once again.

@kspearrin is there any chances getting this fixed and closing this issue then after more than a year maybe? Would be really great.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
