### ISSUE TITLE
Android native auto-fill doesn't work in Chrome unless accessibility service is enabled (Samsung)

### ISSUE THREAD

**Issue by wchae** [bitwarden/mobile#643]
OS: Android 9 PPR1.180610.011
Device: SM-G960W (Galaxy S9, Snapdragon)
Browser: Chrome & Brave, Chromium 78.0.3904.62
Bitwarden: 2.2.6
Auto-fill Service: Enabled

Android's native auto-fill service for Bitwarden does NOT work with Chromium 78.0.3904.62 on Galaxy S9 on Android 9.

The issue can be remedied by enabling the auto-fill ACCESSIBILITY service. With the accessibility service enabled, both the native auto-fill AND the accessibility service auto-fill work properly with Chromium 78.0.3904.62.

The issue does not seem to be present in a) other non-browser apps, b) firefox, and c) Essential Phone.

Other password managers (e.g. LastPass) work properly on the S9.

Thanks!

**Comment by captainwarptime** [comment]
OS: Android 9 PPR1.180610.011
Device: SM-N970F (Galaxy Note10, Exynos)
Browser: Microsoft Edge (Opera, Vivaldi)
Bitwarden: 2.2.6 (2112)
Auto-fill Service: Enabled

Exact same issue on Galaxy Note10 running Android 9.

The native auto-fill service does not work anymore in any Chromium-based browser, but works fine in other apps and Firefox (including Firefox Preview).

Thanks!

**Comment by danielpo** [comment]
Same with s10+

**Comment by danielpo** [comment]
> Same with s10+

Update: it works efter updating to Android 10😀

**Comment by Stephan-P** [comment]
Chiming in from Nokia 3.1 with Edge as well as Vivaldi browser.
BTW, DuckDuckGo browser does work. 

Beta version: 2.3.1 (2380)
Nokia 3.1 (Android 9)
Autofill service: on
Accessibility service: off
URL matching: base domain

With accessibility service on everything works just fine, but we want the proper autofill service to function as well, don't we?
