### ISSUE TITLE
iOS app new password autocapitalizes 

### ISSUE THREAD

**Issue by micheloosterhof** [bitwarden/mobile#647]
Manually entered passwords on the iOS app are autocapitalized (which means first letter is automatically turned into a capital). For password input this is probably not the correct behaviour. This is both for editing an existing item and creating a new item. 

(Also for TOTP key and Username field but that is less of a problem)

**Comment by kspearrin** [comment]
Which password field are you referring to, on Add/Edit Item?

**Comment by micheloosterhof** [comment]
Yes both the + button at the top right to add an item and when editing an
item.

**Comment by kspearrin** [comment]
I can reproduce, but only when the password field is revealed. Can you confirm?

**Comment by micheloosterhof** [comment]
I only tested with revealed.

**Comment by kspearrin** [comment]
Should be fixed next version with https://github.com/bitwarden/mobile/commit/58084810f35a9bc139cab2912c1db5c1ee32aa64
