### ISSUE TITLE
Bitwarden-App on Android is using trackers

### ISSUE THREAD

**Issue by jsuelwald** [bitwarden/mobile#649]
This application uses trackers (HockeyApp & Google Firebase Analytics) - and a password manager should not use them, especially if they are advertised with security and privacy. 

Source: https://reports.exodus-privacy.eu.org/en/reports/com.x8bit.bitwarden/latest/

**Comment by kspearrin** [comment]
This is why we offer an F-Droid version. See https://mobileapp.bitwarden.com/fdroid/

**Comment by jsuelwald** [comment]
Why is the version on F-Droid different?

+ Other password manager do not use trackers, even on PlayStore

**Comment by kspearrin** [comment]
We use HockeyApp for crash reporting and Firebase messaging for push notifications to keep your vault in sync.

**Comment by gmwubs** [comment]
Today I read that LastPass Android App most certainly did ;-)

**Comment by AlphaJack** [comment]
Why don't just add an opt-out feature?  
Does the iOS version features these trackers?
