### ISSUE TITLE
there is a problem connecting to the server

### ISSUE THREAD

**Issue by pbwind** [bitwarden/mobile#654]
The bitwarden database uses a self-built server.
The certificate uses a certificate issued by let's encrypt.
I then use the 2.6 version of the app, the following prompt appears: there is a problem connecting to the server.
PC, chrome, ios, android web pages are all accessed normally.
Android added intermediate certificate, and it didn't work.
When using version 2.2, you need to add an intermediate certificate to your phone.
After the addition, the app can be accessed normally.
Above, there may be problems with the 2.6 version re-certification.
I can't optimize the certificate, I don't like the step of importing the intermediate certificate.

I think the app's certificate correlation is the biggest problem with this app. I also saw a lot of people and I have the same problem.

I hope you can solve this problem.

**Comment by kspearrin** [comment]
Is your server publicly available? Could you share your endpoint with me so that I can test against it? You can send it to me private via email at https://kylespearrin.com

**Comment by pbwind** [comment]
Additional information:
1, 2.2.6 version can not be accessed normally.
2. The version 2.2.2 requires an intermediate certificate to be installed before it can be accessed normally.
address:https://letsencrypt.org/zh-cn/certificates/
Intermediate Certificates--Active-- Let’s Encrypt Authority X3 (IdenTrust cross-signed)  and Let’s Encrypt Authority X3 (Signed by ISRG Root X1)
3. Whenever possible, PC / Chrome / ios / android network can be accessed normally.

**Comment by kspearrin** [comment]
@pbwind After installing the 2 Let's Encrypt CA certs, I was able to connect to your server using v2.2.6 without issue.

**Comment by kspearrin** [comment]
Can you try build number 2125 from the beta track on the play store? I just pushed it out.

**Comment by pbwind** [comment]
hi ，
Updated to 2125. After installing 2 "Let's encrypt CA" certificate, the app can be used normally.
This is a happy result.

Can you have a better app?
For example, if I don't need to import the two intermediate certificates of "Let's encrypt the CA", I can still use it normally.

Already tested, 2125 version, when there is no intermediate certificate installed in my mobile phone, the following error message will appear: Exception message:java.security.cert.CertPath ValidatorException:Truset anchor for certification path not found

I really want to use the app normally without importing the intermediate certificate.

Like pc/chrome/android web, I don't need some extra work.

**Comment by pbwind** [comment]
In order to ensure that I have the server security. I have closed the registration, web login, but you can still log in through the app.
Test account, password I have passed your link:https://kylespearrin.com
 Send it to you, please check it out.

**Comment by kspearrin** [comment]
@pbwind The reason you have to add the CA cert is because the SSL configuration on your server has issues. Type your domain in here and you will see: https://www.digicert.com/help/
