### ISSUE TITLE
URI match detection ignored on iOS autofill

### ISSUE THREAD

**Issue by rggjan** [bitwarden/mobile#655]
I have a page with two logins, one of them has URI match detection set to „Never“.

This seems to be ignored in iOS 13 autofill, as it keeps showing both logins...

**Comment by kspearrin** [comment]
Yes, unfortunately, iOS itself does not support an implementation that allows match detection rules.

**Comment by rggjan** [comment]
But if match detection is set to "never", can't you just hide the entry from iOS?

**Comment by kspearrin** [comment]
Sorry, I misunderstood. Yes, we could do that. See https://github.com/bitwarden/mobile/commit/429e62e6b57153afdeee9e1f0cd94f03531b1113

**Comment by rggjan** [comment]
Awesome, thanks! That's already a great improvement, as it allows excluding suggestions which are only used occasionally and keep appearing on top...
