### ISSUE TITLE
Android - Bitwarden prompts for biometrics when locking

### ISSUE THREAD

**Issue by nkm8** [bitwarden/mobile#658]
I am using a Pixel 3 running Android 10 and I am able to reproduce this issue on a different device (also a Pixel 3 running Android 10).  I have already tried uninstalling/re-installing Bitwarden.

Steps to reproduce:
1. Set 'Lock Options' setting to 1 minute (the issue occurs with any of the values in minutes)
2. Open a different application (I am done using Bitwarden at this point)
3. After the lock timeout, the system 'Use biometrics to verify' fingerprint prompt shows up (it shouldn't)

The issue still occurs even if the device is no longer being used.  I have ambient display enabled, so the biometrics prompt appears on the lock screen and keeps the screen active until you either hit cancel or validate your fingerprint.

**Comment by kspearrin** [comment]
This should be fixed in the latest beta in the play store. Can you give that a try?

**Comment by nkm8** [comment]
Tested as resolved on beta version 2.2.6.

I'm not sure if it is intended, but I had my lock timeout set to 1 minute for testing before the upgrade.  After the upgrade, the timeout was set to 5 minutes - I had to manually set it back to 1 minute to validate the fix.

**Comment by kspearrin** [comment]
I don’t know why your timeout setting would have changed.
