### ISSUE TITLE
iOS integration not working in apps

### ISSUE THREAD

**Issue by aahaselgrove** [bitwarden/mobile#659]
I have an app (eg. Ticketmaster) for which I have a saved login. When I go to the sign-in page on that app, the 'passwords' icon shows up above my keyboard, which gives me the options of 'Bitwarden' and 'iCloud Keychain' when selected. Selecting 'Bitwarden' causes the app to become unresponsive. Previously when I tried this, a window popped up and the bitwarden logo appeared (as if starting the app) at which point it hanged.

iPhone SE
iOS 13.1.3

**Comment by kspearrin** [comment]
Does this only occur in the Ticketmaster app or all apps?

**Comment by aahaselgrove** [comment]
All apps I believe. I replicated the issue in Dropbox. 

Apps with integrated webpages (eg. login for google apps) work fine, it's just occurring for logins in the actual app.

**Comment by kspearrin** [comment]
I cannot reproduce the issue on my iPhone 11. Could you try reinstalling the app and see if that resolves the problem?

**Comment by aahaselgrove** [comment]
I reinstalled both Bitwarden and Dropbox and behaviour is unchanged for me.

**Comment by dfrakes1** [comment]
My wife is having the exact same problem on her iPhone SE running IOS 13.2.3 and Bitwarden 2.2.5.  When using signing into an app like Amazon Music, clicking on bitwarden, doesn't show the popup and causes the app to become unresponsive. 

I have an iPhone 6s (same IOS version & Bitwarden version) and it works for me. 

Based on originator post sounds like might be an issue with the SE model of the phone.

**Comment by sktle** [comment]
I have an iPhone 7 Plus  (iOS 13.3) and am experiencing the same issues. Password autofill does not work at all. Bitwarden 2.2.5. 

Selecting Bitwarden from the AutoFill Passwords setting in the Settings app causes the Settings app to hang (requiring a force close).

Here is a video: https://youtu.be/OZQy9O4RkLc

Bitwarden password autofill does not work in any apps either.

**Comment by aahaselgrove** [comment]
@sktle I don’t think this is the same issue. Password auto fill does work for me in chrome and in web-based forms

**Comment by varnie** [comment]
I have the same issue on an iPhone 6 (iOS 12.4.7) while using Safari.

**Comment by alphabt** [comment]
Same here. iPhone 6s iOS 13.5.5. Happens when using Chrome, Safari, or any app on the device.
