### ISSUE TITLE
Accessibility service is disabled after a force close

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/mobile#66]
Hi,
On my OnePlus 3T running Android 7.1.2 the service is disabled after force closing bitwarden by holding the back button.
I have to manually return to the Accessibility menu to enable it again.

bitwarden v1.4.4

**Comment by kspearrin** [comment]
Any of this apply? https://lastpass.com/support.php?cmd=showfaq&id=9272

**Comment by kspearrin** [comment]
Any update here @Primokorn ?

**Comment by Primokorn** [comment]
It doesn't help.
1. Battery optimization OFF for bitwarden
2. Disable the accessibility service for bitwarden
3. Enable the accessibility service for bitwarden
4. Force close bitwarden app
=> bitwarden if OFF again the Accessibility menu.

I have no external SD card.

**Comment by jerryn70** [comment]
Today I faced similar issue with 1.6.1.

1,Forced stop bitwarden
2, accessibility got disabled
3, open bitwarden and enabled accessibility
4, bitwarden still showing accessibility is disabled and  auto fill is not showing.

5, Restarted phone. 

Now issue is fixed.

**Comment by kspearrin** [comment]
Does this still happen?

**Comment by Primokorn** [comment]
Yes but the problem is the same with Macrodroid app (the only two apps that use this service on my Android device).
So I guess it's related to how Android works.

**Comment by RePacked** [comment]
@Primokorn Yea Android itself is the problem, I tested it with an other app for which I turned accessibility on. Same problem.

**Comment by Primokorn** [comment]
@RePacked Thanks for your confirmation.
Closed since it can't be fixed by Bitwarden.
