### ISSUE TITLE
iOS - App crashes when saving new entries and editing existing entries

### ISSUE THREAD

**Issue by SileemFarghaly** [bitwarden/mobile#665]
Devices: iPhone XS iOS 13.2.3
iPad Mini 5th Gen iPad OS 13.2.3
App Version 2.2.5 (59)

Attempting to save or edit an entry in the Bitwarden iOS and iPad OS app causes the Saving dialog to show for a few seconds, followed by the app crashing. The changes are not saved.

**Comment by kspearrin** [comment]
Can you try reinstalling the app and see if it still occurs? I am thinking something might have become corrupted.

**Comment by SileemFarghaly** [comment]
> 
> 
> Can you try reinstalling the app and see if it still occurs? I am thinking something might have become corrupted.

That did it. Didn't think it would since it was happening one two devices. Oh well, thanks!.
