### ISSUE TITLE
How to set NordTheme as default in Android?

### ISSUE THREAD

**Issue by pdarcos** [bitwarden/mobile#667]
Hi again,

I think the Nord Theme looks much better than the default Light Theme and I want to programatically set Nord Theme as default instead of Light.

In MainActivity.cs I've changed the them to Theme = "@style/NordTheme.Splash",
and in the manifest I also changed it there to @style/NordTheme.Splash

but I don't see any difference. Bitwarden still starts up with the default theme and the only way to change it is to go into the Options menu in the app.

Am I missing something?

Thanks

**Comment by kspearrin** [comment]
I am confused. Why not just change it under the Settings > Options menu in the app? That should persist.

**Comment by pdarcos** [comment]
That is indeed the easy way, but if you have older family members that aren't very tech savvy it's easier to distribute the app with everything already setup by default.

I noticed that indeed I'm able to force Nord/Dark theme splashscreen by changing the settings I described above, but the the base theme stays the same.

I imagine it should be a fairly simple change to have NordTheme as default instead of LightTheme, but I'm not sure where in the code I should set this change.

Thanks

**Comment by kspearrin** [comment]
I would not recommend distributing custom builds of the app. How are you going to maintain updates?

If you want to change the default theme, you could do that here:
https://github.com/bitwarden/mobile/blob/master/src/App/Utilities/ThemeManager.cs#L14
