### ISSUE TITLE
iOS : Unable to generate passphrase in Safari even if selected as default method

### ISSUE THREAD

**Issue by mexson** [bitwarden/mobile#670]
Generator works as expected in Firefox extension (Windows), but not in Safari on iOS.

Expected behavior in Firefox : 
1. Click "Generator" in Bitwarden extension
2. Choose "Passphrase" instead of "Password" and edit some settings like the separator character
3. During a sign-up process, right click the new password field > Bitwarden > Generate password
4. CTRL + V and you get a passphrase

Unexpected behavior on Safari for iOS :
1. Click "Generator" in Bitwarden extension
2. Choose "Passphrase" instead of "Password" and edit some settings like the separator character
3. During a sign-up process, tap on the password field > tap the key icon on the right > tap Bitwarden > tap "+" > tap "Generate a password"
4. A password is generated, not a passphrase, and you are unable to generate a passphrase from there (altough otherwise stated at the bottom of this screen)

Device : iOS 12.4.3 (Iphone 6)

Thank you,
J

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/mobile/issues/620
