### ISSUE TITLE
Auto-Lock not working on Motorola Moto One Vision after November Security Update

### ISSUE THREAD

**Issue by pavelhonner** [bitwarden/mobile#672]
Auto-Lock stopped working on Motorola Moto One Vision (XT1970-3) Android One: PSA29.160-55-7. Tried immediate and 1 min option, both without succes.

**Comment by kspearrin** [comment]
This should be fixed in the latest beta, build 2134. Can you give that a try and report back?

**Comment by darkenedcolossal** [comment]
Version: 2.2.7 (2134) fixes the issue for me.
