### ISSUE TITLE
Bitwarden autofill popup not clickable

### ISSUE THREAD

**Issue by charlyschulte** [bitwarden/mobile#676]
i have a bug on Bitwarden where i cant click the popup which automaticly comes when my bitwarden is locked.

my workaround is to open the bitwarden app, login and set the lock bitwarden automaticly option to never. if i then restart the app where i want to use the autofill feature, it shows the logins correctly.

it happend with my xiaomi mi 9 lite, android 10.

here is a video for better understanding: https://drive.google.com/file/d/1-0CPZmhNrqeZXIb0jlL5prqvf92enVc6/view?usp=sharing 

sorry for my bad english, if you have any questions, please send my an answer. this bug is really annoying for me

**Comment by kspearrin** [comment]
Does this happen every time the app is locked?

**Comment by charlyschulte** [comment]
yes

**Comment by kspearrin** [comment]
Unfortunately I am not sure. I have never seen this before. We will have to look further and see if anything can be found.

**Comment by limuc** [comment]
Thats a problem with MIUI. Its easy to solve. You have to grant the app the permission to "open pop up window while working in background" (That is NOT the correct translation, as i don't know how it is described in the english ROM as i use another language). You will find that setting when you go into Settings > Apps > Organize Apps (or something like that) > Bitwarden > Other Permissions.
Then it works flawlessly.
