### ISSUE TITLE
Number of entries shows incorrect value after scrolling

### ISSUE THREAD

**Issue by limuc** [bitwarden/mobile#678]
Hey,

i am on Android 10.

I have the following minor problem:
The number of the entries that is shown next to the 4 types (Login, Card, Identity, Secure Note) is showing something like:
Login 201
Card 4
Identity 3
Secure Note 59

When i scroll down (i have a few folders) and up again the numbers are the following:
Login 20
Card 4
Identity 3
Secure Note 5

It seems like it cuts of the last number if the number had at least 2 digits.

**Comment by mportune-bw** [comment]
I'm unable to reproduce this on any version of Android.  Any chance you can provide a screenshot so I can be sure that I'm looking at the right thing?

**Comment by limuc** [comment]
Hey, there was an update of the app and since then i can not reproduce the issue. So i assumed it was fixed. Forgot to close the issue here, sry.

**Comment by mportune-bw** [comment]
No worries, glad to hear it!
