### ISSUE TITLE
Auto-fill doesn't work for sites added to home screen through Chrome

### ISSUE THREAD

**Issue by c24w** [bitwarden/mobile#68]
When launching a full screen site, which has been added to the home screen, bitwarden doesn't recognise the site.  Clicking the auto-fill notification launches bitwarden showing "Logins for android.chrome".  Proceeding to add a login pre-poppulates:

Name: android.chrome
URI: androidapp://com.android.chrome

**Comment by kspearrin** [comment]
Unfortunately I don't see a way to make this work with the current autofill accessibility service implementation. The service currently looks for a URL bar in the browser to figure out the website address. A webview launched from he home screen likely doesn't have this. We may have to wait for Android O autofill (https://github.com/bitwarden/mobile/issues/57) to resolve this one.
