### ISSUE TITLE
AUTO-FILL ACCESSIBILITY SERVICE with Microsoft Edge Android (Chrome based)

### ISSUE THREAD

**Issue by jcl78** [bitwarden/mobile#685]
Hi, 
1-Installing Bitwarden extension on Microsoft Edge for Windows (Chrome based), creating vault record, auto fill feature seems ok
2- Installing Bitwarden app on Adroid 7.1.1, validate AUTO-FILL ACCESSIBILITY SERVICE, but when trying to log the site registred in vault with Microsoft Edge Android (Chrome based), no Bitwarden auto-fill notification will appear. Dont work also with Android Google Chrome.

**Comment by kspearrin** [comment]
Can you go to Android Settings > Accessibility and confirm that the Bitwarden service is enabled?

**Comment by Stephan-P** [comment]
See: https://github.com/bitwarden/mobile/issues/489#issuecomment-575640154 
Suggestions are that the issue may lie in Chrome or even Android.

**Comment by zoeff50** [comment]
Same problem here with Edge-Android. New Bitwarden user. Installed BW browser extension in new Microsoft Edge-Chrromium on two Windows 10 laptops and working fine. Imported passwords from Keepass2. Installed BW app on Android 8.1 smartphone. Followed setup steps and BW service is enabled. All passwords are visible in login list. No BW autofill notification will appear on any site. Use copy & paste for the time being.

**Comment by theFisher86** [comment]
Same issue for me with LastPass on Edge for Android

**Comment by Stephan-P** [comment]
After having found that bitwarden beta works with Vivaldi through the Android Accessibility service now , I thought I'd give the latest Edge browser a test as well. Unfortunately the connection between the two is not well. The Bitwarden autofill dialogue does pop up, but after clicking it as, the corresponding database item is not found. It looks like the url is not caught in order, as it is looking for items for - -

**Comment by Stephan-P** [comment]
Today's beta version: 2.3.1 (2376) is giving me a nice Bitwarden pop up overlay to tap, after which I can select the corresponding item for autofill.

- Nokia 3.1, Android 9
- Vivaldi and Edge browsers
- Accessibility service on, Autofill service off
- URL matching option: Base domain or Hostname

**Comment by zoeff50** [comment]
Good news, thanks for that. Can you advise where I can download this beta version or do I have to wait for the final version published in the G Play Store?

**Comment by Stephan-P** [comment]
Open Play store - my apps - Bitwarden
There you will find the option to join the beta testing. Select it and you will receive beta updates.
