### ISSUE TITLE
iOS app crashes on naming entry “Raspberry Pi 3”

### ISSUE THREAD

**Issue by luismateopineda** [bitwarden/mobile#688]
Hi Bitwarden devs,

I seem to have found a bug where when I name a password entry a certain name it crashes the iOS app.
When I enter Raspberry Pi 3 as the name the app crashes entirely.

**Comment by kspearrin** [comment]
And if you enter any other name it does not crash?

**Comment by djsmith85** [comment]
Hi @luismateopineda, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
