### ISSUE TITLE
Improve Cold Start Time / AOT LLVM

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/mobile#69]
There are some known issues around Xamarin Forms startup time on Android. This is not really the fault of anything bitwarden is doing. However, in my testing of different build configurations, when enabled AOT LLVM compilations I see a dramatic improvement in in cold startup times. Unfortunately AOT/LLVM is labeled as an experimental feature by Xamarin and is not recommended for production. I suggest that we try it out in a beta to see if is causes issues for anyone.

**Comment by kspearrin** [comment]
@jerryn70 Can you try this new build to see if it improves your cold start times at all? 

https://ci.appveyor.com/api/buildjobs/v4ejfv1c2aol4ro7/artifacts/com.x8bit.bitwarden-798.apk

**Comment by Primokorn** [comment]
The load time is divided by 3 (from 10s to 3s).
However my fingerprint protection is no longer required to access the data o_O

**Comment by jerryn70** [comment]
Same as Primokorn's 
```
The load time is divided by 3 (from 10s to 3s).
```

**Comment by kspearrin** [comment]
Hmm. It just never prompts for fingerprint anymore? Can you try turning the fingerprint setting and lock options on and off again to see if it changes anything?

**Comment by kspearrin** [comment]
Can you also try PIN instead of fingerprint to see if that works? That will tell me if it is an issue with fingerprint or lock options.

**Comment by kspearrin** [comment]
Here is a new build with updating fingerprint libraries. See if that helps: https://ci.appveyor.com/api/buildjobs/bi6r8cfd0gw9j1cx/artifacts/com.x8bit.bitwarden-802.apk

**Comment by Primokorn** [comment]
**Tested with v802**

> Hmm. It just never prompts for fingerprint anymore?
No.

> Can you try turning the fingerprint setting and lock options on and off again to see if it changes anything?
It does help. The fingerprint protection is required again.

**Comment by kspearrin** [comment]
This should now be much better.
