### ISSUE TITLE
Frequently ANR on android

### ISSUE THREAD

**Issue by LambdaAlpha** [bitwarden/mobile#690]
- My device info: android 9, MIUI 11, Xiaomi 6, Bitwarden 2.2.8.
- I enabled those 2 auto-fill services. 
- I kept the options of the two untouched. 
- I allowed the auto-start permission of this app.
- I disabled the battery-saving strategy on this app.
- I locked the app in the memory so it won't be killed by the system.

With these settings, this app frequently (0-3 times per day) causes ANR.

**Comment by Husna105** [comment]
Due to their OS optimazation it would happen.
check this for best Chat app [https://www.troopmessenger.com/blogs/best-chat-apps-for-team](url)

**Comment by LambdaAlpha** [comment]
it hasn't reproduced for months. close it.
