### ISSUE TITLE
Autofill Non-Functional on Android 10 with Edge Mobile

### ISSUE THREAD

**Issue by liamfoneill** [bitwarden/mobile#692]
Handset: Samsung Galaxy Note 10 5g
Android Version: 10
Edge Version: 44.11.24.4121

Repro Steps:

a) Make sure 1) Autofill Framework is enabled for BitWarden 2) Accessibility Service for BitWarden is disabled.
b) Browse to https://www.github.com/login
c) Try to fill username/password from Bitwarden

Expected Behaviour: Bitwarden recognises the URL from Edge and suggests the appropriate vault entry matching Github.

Actual Behaviour: BitWarden tries to match on 'com.microsoft.emmx'

Please note: I know it can get it to kind of work with Accessibility Service but I am reporting this bug with the Autofill framework. Also, I get the same behaviour on Chrome. This issue seems to be confined to Chromium based browsers.

I would like to help get Autofill working again due to the fact it doesn't slow down my device like accessibility service does.

**Comment by kspearrin** [comment]
After testing this more this appears to be a bug in Edge itself. They are not longer passing the `WebDomain` property on the `ViewNode` tree. Without this, we cannot determine the website that is currently being viewed and it falls back to the package id of the app.

**Comment by liamfoneill** [comment]
Thanks, I have reported this to the Edge Team

**Comment by rcdailey** [comment]
Do you have a link to a bug report on the Microsoft side?

**Comment by Dark4Codrutz** [comment]
any news on this ?

**Comment by maxbog** [comment]
Any news? This is a deal breaker for me. Password manager does not work and it's the only thing that keeps me from using Edge. I suppose I'm not the only one that thinks similarly.

**Comment by superm1** [comment]
FYI it seems fixed for me in the edge that just updated today.

Version 45.01.04.4900.

Autofill is offering the correct websites!

**Comment by Dark4Codrutz** [comment]
Confirming, works fine now.... Finally MS!

Sent from Mail for Windows 10

**Comment by liamfoneill** [comment]
Works for me too!
