### ISSUE TITLE
Opera Browser support inconsistent

### ISSUE THREAD

**Issue by J055Y** [bitwarden/mobile#699]
The only time when autofill works within the browser is when initially signing into an Opera account upon first launching the application. Outside of that, neither the autofill or accessibility service work for me.

It seems unusual that it would work initially then never again, hence why I have wondered if it is an issue on my end.

**Comment by Stephan-P** [comment]
See: https://github.com/bitwarden/mobile/issues/489#issuecomment-575640154
The problem you're describing occurs with many browsers and there are suggestions that the issue may lie within Chrome or Android itself

**Comment by djsmith85** [comment]
As mentioned by @Stephan-P this is an upstream issue with Opera.

Closing this now.
