### ISSUE TITLE
Extension in Firefox not matching login in vault

### ISSUE THREAD

**Issue by piejanssens** [bitwarden/mobile#70]
Although I have two logins for github.com, when I open bitwarden from within firefox it says there are no matches. 

![](http://i.imgur.com/6EvtNS6.jpg)

![](http://i.imgur.com/PDVVlfj.jpg)

![](http://i.imgur.com/HyPqUJM.jpg)

**Comment by kspearrin** [comment]
This is a known issue that has been addressed in Firefox 8.0 (unreleased still).

See more here: https://bugzilla.mozilla.org/show_bug.cgi?id=1344994

**Comment by piejanssens** [comment]
@kspearrin Thanks for clearing that up. It might be better to keep issues like this open and close them when the affected product (Firefox iOS) has been updated. That way I would have found an open issue and saved you some time 😄
