### ISSUE TITLE
Pressing "search"/enter key on keyboard when searching crashes app (Android)

### ISSUE THREAD

**Issue by snoozysoft** [bitwarden/mobile#703]
Say you're logging into a website, and you use the autofill accessibility service, but the app doesn't properly recognize what login it should give you for whatever reason. Fair enough, you'll do a search for it instead. Here's where the quirk happens. If you type what you want in, it'll serve up anything matching that term, which is a-ok. But the problem is that, on Gboard at the very least, if one presses the enter/"search" key after typing in what you want, the entire app crashes and restarts. It's really strange and I've noticed it happen on both Android 8 (what I'm currently using) and Android 9 respectively.

**Comment by kspearrin** [comment]
Can you reproduce this every time or only sometimes?

**Comment by snoozysoft** [comment]
It seems it only sometimes happens. Weird, I remember it being more constant. Currently, whenever I press the search key after typing in something that would normally bring up results, it just tells me "no results found", which is a blatant lie. Other times, it crashes and restarts. Something screwy is definitely going on with it.
