### ISSUE TITLE
Unlimited pin tries on iOS/ iPadOS

### ISSUE THREAD

**Issue by wizard78** [bitwarden/mobile#708]
If I use the mobile apps everything works fine: After 5 failed pin attempts I am completely logged off. However if I use the share feature in e.g. Safari to open bitwarden I have unlimited trys to unlock my vault. Same thing happens when the password autofill functionality is used.

**Comment by jmiguel-hdez** [comment]
it appears this is only a problem if you say no when it prompts for "do you want to require unlocking with your master password when the application is restarted?"
It has the behavior that the counter resets after the app is restarted.  
Also, when the option to ask for master password on restart is enabled it doesn't let me use the pin code from safari. 

I guess every launch from safari is its own app context hence the counter is always lost

**Comment by tgreer-bw** [comment]
@mportune-bw I think this is addressed in the next release, right?

**Comment by mportune-bw** [comment]
@tgreer-bw It is!
