### ISSUE TITLE
Missing login on mobile [Android]

### ISSUE THREAD

**Issue by renolc** [bitwarden/mobile#71]
I have a Nexus 5X on Android 7.1.2 with the current latest version of bitwarden -- 1.5.0 (553).

I'm not entirely sure when this started happening, but I just noticed today that I have a login that just isn't showing up on my phone at all. It's still present in the Chrome extension as well as the web vault, so I know it's there.

This could potentially be related to the new sharing feature. I set up an Org where I am the only current member and I started sharing certain logins to it. The login in question was not shared, but it was the only one in that folder that wasn't. All other logins seem to be appearing correctly, it's just this one login that isn't.

I tried force syncing a few times in different orders. I even tried deleting and recreating the login to no avail.

**Comment by renolc** [comment]
Doing some further testing, it seems my Android bitwarden isn't picking up any new logins at all. I just tried creating a new dummy one for github, force syncing the chrome extension, then force syncing the android app, and the new github didn't show up.

**Comment by kspearrin** [comment]
Can you try logging out and back in to see if that changes anything?

**Comment by kspearrin** [comment]
Also this new one you just tested for github, is it still just on android that it isn't showing up?

**Comment by renolc** [comment]
Yes, I forgot to mention I tried logging in and out. Correct, only on Android is it not showing up.

Also, I just tried to create a new login directly on the phone and during save it seemed to crash. Didn't get a notification of a crash, but it completely closed and on reopen it didn't have the new login. I might try uninstall and reinstall to see if that helps.

**Comment by kspearrin** [comment]
When you force sync does the toast notification say that is was successful or failed?

**Comment by renolc** [comment]
It says "syncing complete" and updates the timestamp. It doesn't specify success or failure, but it seems like a success due to the lack of a failure notice and the updated timestamp.

**Comment by renolc** [comment]
Reinstalling seems to have fixed it. All previously missing logins are now present, including the ones I just previously created on the phone itself. Creating new entries on the phone also works as expected again. I'll go ahead and close this issue since it seems to have been environmental.

Thanks!

**Comment by kspearrin** [comment]
Very weird. I wish I could have figured out what was going on since it is likely that there is actually some underlying bug. Regardless, glad you're working now.

**Comment by CircuitGuy** [comment]
So... Do you still want a test case? Got this issue 2x now. Won't sync to the shared vault and (I think - maybe human error) BitWarden is "forgetting" some new entries created in the app. Happened once before and I cleared all data to fix the issue.
