### ISSUE TITLE
Android Overlay obscures menu and cannot paste 

### ISSUE THREAD

**Issue by hinaloe** [bitwarden/mobile#716]
Android accessibility service overlay (#695) is on a higher layer than the system context action menu, so sometimes hide them and makes it impossible to copy and paste.

![image](https://user-images.githubusercontent.com/5253290/73760045-2b084580-47b0-11ea-9022-9c6ec8e3f23e.png)

**Comment by kspearrin** [comment]
Should be fixed in beta build 2173, rolling out to play store now.
