### ISSUE TITLE
[Android ]Autofill does not work properly in MS Edge

### ISSUE THREAD

**Issue by dustojnikhummer** [bitwarden/mobile#719]
Lastest version of Bitwarden app, using the native Android autofill

Instead of Bitwarden picking up the website and filling that in, it picks the app itself, aka com.microsoft.emmx

No idea why this is happening. Cannot take a screenshot since either Bitwarden or Edge is blocking it.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/mobile/issues/692
