### ISSUE TITLE
Username field not recognized by accessibility service

### ISSUE THREAD

**Issue by larena1** [bitwarden/mobile#720]
Tested in Firefox and Chrome. Both don't show the new tooltip to autofill. It works on other sites where there is a username and password field together.

Example logins: Google, Paypal

**Comment by dagadbm** [comment]
yes i cannot use bitwarden on brave for example it just doesn't work . with or without the accessibility service.

will this ever be fixed? it is the only missing feature to make this fully 100% cross platform imo

**Comment by kspearrin** [comment]
Is there a password field on screen? We cannot detect a username field if there is not a password field accompanying it.

**Comment by larena1** [comment]
@kspearrin There's only a username field on the site. But iirc the previous version of Bitwarden still showed a notification there.

And Android's system-wide autofill also offers to autofill these fields even without a password field present.  I wonder how Android detects it.

These are two very prominent sites on the internet and there are probably many other examples. Isn't there some workaround to make this possible? Can you read the attributes of the form field? Or check if the url contains something like login or so?

**Comment by Step2Web** [comment]
I appear to have a related problem. I'm using Android 9 with Firefox (68.6.0) on my Xiaomi Mi A2 Lite and the Bitwarden app (Version 2.3.1 - 2257) doesn't auto-complete the username on one of the websites ([ing.at](https://banking.ing.at/online-banking/wicket/login?0)) I'm often using. 

It does, however, contrary to what @larena1 said, fill in the login information correctly on pages where no password field is present (google.com, amazon.de) and also on many other sites where both fields are present work fine.

I've also tested ing.at on Firefox on Windows using the Bitwarden browser extension and it works just fine (also when accessing the mobile version of ing.at).

Let me know if you want a screen recording.

**Comment by larena1** [comment]
Fun fact: Bitwarden Android app won't even detect the password field on the Bitwarden vault website when the vault is locked.

At least I can use LastPass' accessibility service, which detects the field just fine, to login to the Bitwarden web vault. They must've some kind of magic formula or maybe just a more advanced app.

**Comment by larena1** [comment]
It actually shouldn't be that hard anyway. If you detect a password field on a website which has credentials stored in the vault, offer it to autofill that password field.
