### ISSUE TITLE
Following update to Android 10, bitwarden no longer has a persistent notification 

### ISSUE THREAD

**Issue by NicholasConrad** [bitwarden/mobile#721]
My note9 updated to Android 10 and OneUI 2 yesterday, and now I don't have my persistent bitwarden notification. More puzzling, I don't even see an option to enable it any more in the app! Very confusing.

I've uninstalled and reinstalled bitwarden, but that didn't resolve the issue. Version: 2.3.0 (2173)

**Comment by kspearrin** [comment]
Sounds like you are using the latest beta. We're using an overlay for autofill accessibility service now. Notifications are no longer used.
