### ISSUE TITLE
Auto-fill always recognizes the app's package rather than the URL under some browsers！

### ISSUE THREAD

**Issue by TUT123456** [bitwarden/mobile#724]
I have this situation in via browser and edge browser. When I log in to Github, on the edge, the password given by the auto-fill of bitwarden is Microsoft, and when I click to add an item, The package name of edge is given in the URL bar, com.microsoft .***, not https://github.com,also on via browser, it can not even give the context menu。

**Comment by BohdanQQ** [comment]
Might be wrong but what I was able to find out from a little of debugging.
In Parser.cs/Parser.SetPackageAndDomain property node.WebDomain is always null or whitespace for each node, therefore Website doesn't get set and Uri getter in the end returns the androidapp://packageName.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/mobile/issues/692
