### ISSUE TITLE
Application crash during record add on IOS v13.3

### ISSUE THREAD

**Issue by TylerRudie** [bitwarden/mobile#726]
For some reason the Bitwarden app crashes when I attempt to add a record on my Iphone.

IOS v13.3
Bitwarden v2.2.5

Steps to reproduce:
-New Record
-Add Name
-Add Username
-Generate Password
-Save

At this point the Application Crashes and the record is lost.

**Comment by kspearrin** [comment]
Try logging out and back in, then try again?

**Comment by TylerRudie** [comment]
That solved it. Thanks.
