### ISSUE TITLE
Application exits on back button in submenu

### ISSUE THREAD

**Issue by f1u77y** [bitwarden/mobile#73]
## Steps to reproduce:
1. Open Settings tab
2. Open Folders menu
3. Press Back button

## Expected results
Application should send you back to Settings tab

## Actual results
Application exits

## Details
OS: Android 6.0

**Comment by kspearrin** [comment]
Thanks, I'll have to look into this.

**Comment by f1u77y** [comment]
Fixed for me now, so closing.

_Sent from my Xiaomi Redmi 4A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
