### ISSUE TITLE
No items for "com.opera.browser" on Android

### ISSUE THREAD

**Issue by Hakun1n** [bitwarden/mobile#732]
Hi, 

I have issue that anytime i open page with logon fields the auto-fill does not work properly. It won't pick the URL of the page but instead looks for "com.opera.browser". I have to click the username/password fields several times till it suddenly starts working. Sometimes single tap into username filed is enough but sometimes i need to do it several times. This is quite annoying :/

OS: Android 8.0
Browser: Opera 56.1.2780.51589 (last available version)

![image](https://user-images.githubusercontent.com/12685294/74607992-bbfaed00-50dd-11ea-9dcb-3b7627dfc6f5.png)

**Comment by kspearrin** [comment]
Is this with the accessibility service? Can you try the latest beta on the Play Store?

**Comment by Hakun1n** [comment]
@kspearrin This is with "Auto-fill Accessibility Service".

The Auto-Fill service does not work for me at all. I am not getting the "flying overlay" window. I've checked "Apps and Notifications" -> "Special app access" -> "Display over other apps" and Bitwarden is not even there. (I see Lastpass there just to compare). Note that if i switch to LastPass service the overlay works OK.

**Comment by Hakun1n** [comment]
Okay so the BETA (2.3.0) adds the "Display overlay" permission and now it works :]

Thank you for your your time and effort!
