### ISSUE TITLE
URI matching does now work properly

### ISSUE THREAD

**Issue by Hakun1n** [bitwarden/mobile#733]
Hi,

So i have bellow web-pages stored in Bitwarden:
**https://www.ixsystems.com/community/**
**https://jira.ixsystems.com**

Each service has separate user database so i need to maintain separate logon credential for them.
As you can see the domain name is the same "ixsystems.com" so the "Default detection" for the URI does not work as Bitwarden wants to store the credentials under the same record (works as designed). 
So I've created two records in Bitwarden and set "Starts with" as URI detection. Both of them works flawlessly on Desktop app and Firefox addon.

The problem i have is that it does NOT work on Android phone at all. It just says "There are no items in your vault for ixsystems.com" even the URL in browser is one of the stored ones.

Record 1:
![image](https://user-images.githubusercontent.com/12685294/74608144-fca73600-50de-11ea-907c-04c695786c55.png)

Record 2:
![image](https://user-images.githubusercontent.com/12685294/74608150-03ce4400-50df-11ea-8b85-ad60f3d84881.png)

Desktop works OK
![image](https://user-images.githubusercontent.com/12685294/74608191-5c9ddc80-50df-11ea-9843-1c824ed0f54d.png)

Behavior on Android 8.0 + Opera browser
![image](https://user-images.githubusercontent.com/12685294/74608214-94a51f80-50df-11ea-894f-26fa472fcabb.png)

![image](https://user-images.githubusercontent.com/12685294/74608200-6d4e5280-50df-11ea-94e4-e54c4c9545d3.png)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/mobile/issues/578
