### ISSUE TITLE
No syncing on Android 9.1.0 EMUI Huawei/Android 10 Samsung A71.

### ISSUE THREAD

**Issue by ScaryNick** [bitwarden/mobile#735]
So, i tried changing my password, my encryption key and reinstalled app. Nothing helped. On any other device syncing work properly. I tried using other wifi and LTE, still not sync. My app work normaly and after a month it just stop syncing. 
My mobilephone is Huawei P20 Lite (ANE-LX1).
Android 9
EMUI 9.1.0
Is there any solution?

**Comment by ScaryNick** [comment]
I loged in on another device with the same encryption key and the same happened. New device is Samsung A71 with Android 10 and still i can't synchronize my vault... I need some help or solution or patch..

**Comment by almanzarj** [comment]
I am having the same issue on Android 9 using Samsung Galaxy S8+ with Bitwarden version 2.3.1.

I have tried uninstall app, install app, clear cache, log out and login. 

When I try to do sync vault now...I get error Syncing failed message.

**Comment by kspearrin** [comment]
Are you using Bitwarden cloud or your own hosted server?

**Comment by almanzarj** [comment]
self hosted server. sync works properly on desktop app and browser add-ons.

**Comment by kspearrin** [comment]
Bitwarden official or bitwarden_rs?

**Comment by almanzarj** [comment]
I am using https://hub.docker.com/r/bitwardenrs/server

**Comment by kspearrin** [comment]
This is not an official Bitwarden server. Please contact the authors of that project if you are having problems.

**Comment by ScaryNick** [comment]
I'm using other voult then original but on offical Bitwarden server.
