### ISSUE TITLE
Android App: Can't autofill WhatsApp two-step verification

### ISSUE THREAD

**Issue by cagapisto** [bitwarden/mobile#745]
The Android app of Bitwarden can't autofill the two-step verification prompt of WhatsApp (WA ask from time to time for the the six numbers long code, even if you're logged into the app). When clicking on the entry field the autofill toast of Bitwarden appears for some milliseconds but vanishes after that and also isn't clickable during that time.

**Info**
Bitwarden app version: 2.3.0
WhatsApp-version: 2.20.62
Phone: Xiaomi Mi4 (cancro)
Android Version: 10 (Q)
ROM: MoKee Open Source 10 QQ1B.200205.002

**Comment by kspearrin** [comment]
Bitwarden never autofills two-step login fields. We can only target username/password fields.

**Comment by cagapisto** [comment]
Oh, sorry my bad. Didn't knew that. Thanks for the hyper fast response
