### ISSUE TITLE
Android: Unable to paste data into Notes section of an item

### ISSUE THREAD

**Issue by clayadams5226** [bitwarden/mobile#747]
Tested on Samsung Galaxy S10 running Android 10

**Steps to Reproduce:**

- Copy text from an application other than Bitwarden
- Open the Bitwarden App
- Log into your vault
- Add a new Item
- Scroll to the "Notes" section
- Long Press in the field

**Expected Result:** The option to paste appears

**Actual Result:** Unable to paste.

**Notes:** I have validated the ability to paste works in iOS as well as in the desktop app and browser extensions.

**Comment by mportune-bw** [comment]
This appears to be a bug with Xamarin.Forms when using an Editor control within a ScrollView.  Some folks seem to have had luck with some hacks, none of which are working for us unfortunately.  I'm in the process of updating to the latest Xamarin.Forms (4.5.x) so let's revisit this once that's ready.

Workaround:  If you type something into the field (anything, like a single char, then delete it) it seems to poke the system into allowing cut/copy/paste to work again.

**Comment by tp0** [comment]
> Workaround: If you type something into the field (anything, like a single char, then delete it) it seems to poke the system into allowing cut/copy/paste to work again.

Works when creating a new item, but does not seem to work and long tap does not work at all notes field in "Edit item" view.
