### ISSUE TITLE
Android: App crashes when trying to login with Duo on Android Samsung S10.

### ISSUE THREAD

**Issue by clayadams5226** [bitwarden/mobile#748]
**OS:** Android 10.0
**Prereq:** Configure a Bitwarden account to use Duo as 2FA method for login.
**Steps:** 
- Launch the Bitwarden App
- Enter a valid username and Master Password
- Tap “Log In”
- On the Duo screen ensure your S10 is selected as the “Device”
- Tap Send Me a Push
- Tap the Notification to view Actions
- Tap “Approve”

**Expected Result:** User is logged into their vault
**Actual Result:** App Crashes

**NOTES:** If you tap the notification instead of “Approve” it will launch the Duo app. Tapping approve here brings you back to the Bitwarden screen with the Duo overlay and a “success logging in” message. However, the app never advances from this screen. Tested it on Pixel 2 and Razer Phone and couldn’t reproduce.

**Comment by kspearrin** [comment]
Can you test the regular .apk version from here?
https://ci.appveyor.com/project/bitwarden/mobile/build/job/bekc2a728ytrnarb/artifacts

This should have been fixed recently.

**Comment by clayadams5226** [comment]
Confirmed the first half of this ticket is resolved in the new build. However, if the user taps into the Duo app instead of using the notification they never get taken to their web vault. I've attached a video. Let me know if you want a new ticket for this, or if I should just update the title and steps.

[DuoDefect.zip](https://github.com/bitwarden/mobile/files/4285172/DuoDefect.zip)

**Comment by clayadams5226** [comment]
Validated, this has been resolved with the above merge.
