### ISSUE TITLE
anyway to get Bitwarden to recognize apps (iOS)?

### ISSUE THREAD

**Issue by al-muftah** [bitwarden/mobile#749]
When I log into some app, I have to open up Bitwarden and search for my login then tap it to auto-fill.

Is there anyway to associate certain apps with certain logins in Bitwarden?

**Comment by kspearrin** [comment]
Yes, you can use `androidapp://package.name`. Please see https://help.bitwarden.com/article/uri-match-detection/

**Comment by ferritopia** [comment]
> Yes, you can use `androidapp://package.name`. Please see https://help.bitwarden.com/article/uri-match-detection/

It works on Android app, [this page ](https://help.bitwarden.com/article/uri-match-detection/) only shows how to do it on Android. 
iOS users need a working matching url for iOS apps.
