### ISSUE TITLE
Android Firefox works fine, while chromium browsers website suggestions doesn't work.

### ISSUE THREAD

**Issue by anacondaq** [bitwarden/mobile#750]
My problem in short:
1. I open website for example AAA.com in Firefox. And hit login field, because I have account here.
2. In notifications I see bitwarden and I press on it. Bitwarden now open
3. Bitwarden now suggest me the correct credentials to fill in browser fields.
4. I press in bitwarden app on this UI element, and password filled, everything is good.

Now how it works on all chromium browsers:

1. Same as for ff
2. Same as for ff
3. Bitwarden window opened, but not suggested a correct credentials for the website at all, instead suggested some bullshit.
4. Now I closebitwarden fully and repeat again step 2 up to 3
5. And only after when I again (second time reopen app) bitwarden, now bitwarden suggest me the correct credentials for correct website. This happen always.
6. Also, autofill feature doesn't work on chromium browsers at all, only notifications. While on ff everything ok

Bitwarden 2.2.8, build 2136. I can reproduce it on all devices with Android 8.1, 9.0

**Comment by kspearrin** [comment]
Please try the latest beta from Chrome web store. This should no longer be an issue when using the accessibility service.
