### ISSUE TITLE
In-app Photo/Image Viewer

### ISSUE THREAD

**Issue by sevensixseven** [bitwarden/mobile#760]
> **_Mobile, Usability_**
<details>
  <summary>Description</summary>
The ability to open attached images within the mobile app and not need to download the image.
</details>

**Comment by marlongerson** [comment]
This really needs to be implemented. I just purchased premium in order to store files, and I can't even view them on my phone.

**Comment by cscharf** [comment]
@sevensixseven, can we please move this to the community forum (and link back here)? You can keep the same card linked in Asana, but please move from the issues board to the backlog/product board but closing this in GitHub and add the link to the community post in Asana.
