### ISSUE TITLE
fdroid repository not in sync?

### ISSUE THREAD

**Issue by lowtower** [bitwarden/mobile#762]
## Describe the Bug

The fdroid repository doesn't seem to be in sync.
While Google Play already offers version 2.3.0, fdroid is stuck at Version 2.2.8

## Expected Result

Keep fdroid in sync with Google Play and offer the same version in both app Stores.

## Environment

- Operating system: android

**Comment by kspearrin** [comment]
Android app update is rolling out on the play store. Whenever that process completes successfully we will update f-droid.

**Comment by lowtower** [comment]
Thanks for clarifying

**Comment by lowtower** [comment]
Just one extra question:
The new version is in Play Store since 06.03.2020.
How long does the process take?

**Comment by lowtower** [comment]
Strange:
now, version 2.3.0 disappeared from Google Play
