### ISSUE TITLE
Android: Autofill option disappears after a split second in Chrome

### ISSUE THREAD

**Issue by clayadams5226** [bitwarden/mobile#763]
## Describe the Bug

A number of users have reported that the autofill option in Chrome disappears after a split second with the latest release. This seems to happen more on specific websites than others. Can not reproduce consistently.

## Steps To Reproduce

1. Log into the Bitwarden app on an Android device
2. Ensure all Auto-Fill services are enabled
3. Open Chrome
4. navigate to https://mtggoldfish.com
5. Click the hamburger menu in the top right corner
6. click "login"
7. Tap the "Email Address" field.

## Expected Result

Auto-fill with Bitwarden layover should appear to allow the user to autofill their password.

## Actual Result

If you look closely you can see it appears briefly for a second then disappears. (if you scroll slowly on the screen you can bring it back).

## Screenshots or Videos

Video: https://photos.google.com/share/AF1QipPJ9YTc-NlWFdVJs7HThshaHckr2kCKtU8E-s0pm8BhxXGYc45CI0T_JfUILoG0FA?key=bzVIVmxOV0pSMXVyY2l5cVBSQXlDZDI1TF9vNlln

## Environment

- Device: Reproduced on Galaxy S10
- Operating system: Android 10
- Build Version (go to "Settings" → "About" in the app): 2.3.0 (2231)
- Is this a Beta release? N

## Additional Context

Have seen reports from other devices as well. Samsung S9 running Android 9, Note 9 running Android 9.

**Comment by clayadams5226** [comment]
Similar to issue https://github.com/bitwarden/mobile/issues/489

**Comment by kspearrin** [comment]
Autofill service or the accessibility service?

**Comment by clayadams5226** [comment]
Accessibility service

**Comment by mportune-bw** [comment]
The view positions we're receiving from accessibility via chrome on this site are strange (initial hit jumping off-screen and scrolling utilizing an acceleration curve).  Not sure what this site is doing.
