### ISSUE TITLE
Android: App fails to Sync 

### ISSUE THREAD

**Issue by clayadams5226** [bitwarden/mobile#765]
## Describe the Bug

There have been several reports of users being unable to sync the app using Android devices. They continuously get "Sync Failed".

## Steps To Reproduce

1. Log into the Bitwarden application
2. Tap on Settings
3. Tap on 'Sync'

## Expected Result

Application syncs with the server and the new sync date and time appear

## Actual Result

"Sync Failed" message appears

## Environment

- Device: Samsung Note 8
- Operating system: Android 9
- Build Version (go to "Settings" → "About" in the app): 2.3.0 (2234)
- Is this a Beta release? N

## Additional Context

The CS team has been unable to reproduce this issue, but have seen a spike in the number of users reporting it. We've tried the following troubleshooting measure:

- Uninstall the app
- Ensure no VPN is installed
- No custom DNS was being used
- Attempted on Wifi and Cellular Data
- One customer went as far as doing a factory reset on their device
- Other devices and OS versions have reported similar issues

**Comment by kspearrin** [comment]
Have we had them try an older version of the app to see if it is related to our related release or not?

**Comment by clayadams5226** [comment]
Waiting to hear back on results.
