### ISSUE TITLE
Swiping down the Bitwarden login selection window remains on top of the browser. 

### ISSUE THREAD

**Issue by tankmohit** [bitwarden/mobile#766]
# Describe the Bug
In safari on ios13, swiping down a login selection overlay without choosing a password to autofill makes overlay permanent on safari. There is no option to close it. Safari needs to be force closed. 

## Steps To Reproduce

1. Go to any login page
2. Click on “key” icon to open list of logins
3. Swipe down the bitwarden window without choosing any login or clicking on cancel button. 

## Expected Result

Swiping down the overlay should close the bitwarden selection window and return to safari login page. 

## Actual Result

It shows bitwarden splash screen and freezes there

## Screenshots or Videos

https://streamable.com/8snov

## Environment

- Device: iphone XR
- Operating system: iOS 13.3.1
- Build Version: Version: 2.2.5 (59)
- Is this a Beta release? :No

**Comment by clayadams5226** [comment]
I'm able to reproduce this successfully. As a work around, if you tap on "cancel" (instead of swiping down) the Bitwarden app closes as expected.

**Comment by fabiosoft** [comment]
yes, for sure it's a modal presentation issue from iOS13.
Fix should be 1 line of code (native)

**Comment by phillipo6** [comment]
Any news on this? Have the same problem :(

**Comment by charlyschulte** [comment]
i can also reproduce this issue :(
