### ISSUE TITLE
Exporting vault in csv format not working

### ISSUE THREAD

**Issue by mKoonrad** [bitwarden/mobile#768]
## Steps To Reproduce
1. Open Bitwarden app
2. Click on Settings
3. Click on Export Vault
4. Change format to .csv file
5. Type valid master password and click Export Vault button

## Expected Result
Opening system file manager to save csv file like when I export json file.

## Actual Result
Clearing master password field

## Environment
- Device: OnePlus 5T
- Operating system: Android 9
- Build Version: 2.3.0 (2231)
- Is this a Beta release? No

**Comment by mportune-bw** [comment]
@mKoonrad Can you try the latest beta from the Play Store (build 2248)?  We're unable to reproduce this but went ahead and updated the CSV exporter library and added the missing error dialog.  If it still isn't working for you just reopen this issue and let us know if anything changed.

**Comment by mKoonrad** [comment]
@mportune-bw I reinstall app and download beta version. Now, after typing valid master password I have error "There was a problem exporting your vault.  If the problem persists, you'll need to export from the web vault."

**Comment by mportune-bw** [comment]
Thanks @mKoonrad - I'm reopening the issue and will continue observing.

**Comment by mKoonrad** [comment]
@mportune-bw Fixed in 2.4.2 (2501)

**Comment by mportune-bw** [comment]
Fantastic, thanks @mKoonrad !
