### ISSUE TITLE
Android + Yubikey not working

### ISSUE THREAD

**Issue by Iotaslair** [bitwarden/mobile#769]
## Describe the Bug

When plugging in a Yubikey for 2FA while logging in the user gets sent back to the starting log in screen.

## Steps To Reproduce

1. Set up a Yubikey as a 2FA device for your account
2. Log in
3. Click on the box so that the Yubikey can type it's key
4. Plug in key
5. Get sent back to the log in screen

## Expected Result

Log into the Bitwarden app and get to the Vault

## Actual Result

Sent back to the start of the login process

## Environment

- Device: Pixel 3
- Operating system: Android 10
- Build Version: 2.2.8
- Is this a Beta release? No
- Yubikey Version: Yubikey 5C

## Additional Context

I just am getting started with Yubikey and Bitwarden so there's a chance I have misconfigured something, but I kind of doubt this is expected behavior. 

**Also it seems like Android is treating the Yubikey as a separate keyboard, my guess is that this is somehow tied to it**

**Comment by curtisbelt** [comment]
I have this exact same problem as well. I switched to Bitwarden in a couple months ago, and it was like that from the start. Hopefully this gets more attention!

## Environment
* Device: Pixel 3 XL
* Operating system: Android 10
* Build Version: 2.3.1
* Is this a Beta release? No
* Yubikey Version: Yubikey 5C

I'm going to try to join the Beta program and see if that helps.

**Comment by curtisbelt** [comment]
@Iotaslair So I have a hacky workaround -- I plugged in my yubikey first, then used Lastpass to auto-fill my Bitwarden password, that way I can get to the next screen and use my yubikey... lol.

**Comment by Iotaslair** [comment]
@curtisbelt Thanks for the temporary workaround. I don't think I want to use it but it seems interesting

**Comment by smartin015** [comment]
I'm seeing the same issue (Pixel 2, Android 11, app v2.6.1) - it "crashes" back to initial login if the key is plugged in after entering the master password. This sounds like the same report as #350 (Open >2yr). 

I can use 2FA if I plug in my yubikey *before* entering the master password, but I have to make sure to tap/focus the input text box (slightly hidden / low contrast) on the "use security key" part of the login flow. There's no indication that the text box isn't focused, which took me a bit to realize at first.

**Comment by permster** [comment]
@smartin015, thank you!  That worked for me.  The key part I was missing was:
> make sure to tap/focus the input text box (slightly hidden / low contrast) on the "use security key" part of the login flow

Perhaps if the primary issue can't be fixed easily maybe the devs could at least have the security key input box have focus by default on that screen.  See [screenshot ](https://drive.google.com/file/d/1YfpU84_Wo8-6DdADNM6ZfL-V3rlfyYEx/view?usp=sharing)link of the input box were talking about.

**Comment by Iotaslair** [comment]
Thanks for getting this fixed up @eliykat 🙏
