### ISSUE TITLE
Trim spaces from the email address in the login field before processing the form

### ISSUE THREAD

**Issue by flawiddsouza** [bitwarden/mobile#77]
Currently the email address entered is accepted as it is. With trailing spaces and what not. This should definitely be fixed. Otherwise the login form processes the request and returns invalid username and password even when the email and password are correct.

**Comment by kspearrin** [comment]
This is already being done. See

https://github.com/bitwarden/mobile/blob/master/src/App/Services/AuthService.cs#L216
and https://github.com/bitwarden/mobile/blob/master/src/App/Services/AuthService.cs#L254

I am not able to reproduce?

**Comment by flawiddsouza** [comment]
Weird. You're right, it works perfectly with my phone. Maybe it has something to do with the custom os shipped with the phone my friend had. Sorry about this.

**Comment by kspearrin** [comment]
Please let me know if you figure anything out. There have been some really weird reports coming in from a few users about the registration/login process on Android that I cannot reproduce.

**Comment by flawiddsouza** [comment]
I'll try to get access to the phone and reproduce the problem. If I find anything, I'll let you know.

**Comment by jmlag** [comment]
I am having this issue on the latest Android app and Firefox extension. @kspearrin

**Comment by kspearrin** [comment]
@jmlag Can you reproduce the issue?

**Comment by jmlag** [comment]
I just created a login with leading/trailing spaces. If you use the "copy username" button or fill in a site that doesn't trim their inputs you get the untrimmed string. The spaces are also preserved if I look at the entry in the web vault.

On a somewhat related note, if you go to "View Item" and manually highlight the "Name" or "Username" it doesn't display the leading/trailing spaces but it always adds a single trailing space at the end, even for names/usernames without trailing spaces.

**Comment by kspearrin** [comment]
This issue is about registering and logging in with a Bitwarden account, not data stored in your vault.

**Comment by jmlag** [comment]
Whoops, my mistake. Should I create a new issue or is this behaviour intended?

**Comment by kspearrin** [comment]
It sounds like intended behavior. We expect to take vault field information from the user without modification.
