### ISSUE TITLE
Android and Chrome vault show blank names an no icons.

### ISSUE THREAD

**Issue by shadoskill** [bitwarden/mobile#778]
For the last few days my android app and my chrome extension vaults show blank name fields with the default grey globe icon.

Screenshot of the issue.
https://i.imgur.com/Z2FKOnG.png

Using the website login everything is normal.
This prevents me from using the autofill and from copying username and password manually.

My phone is the Google Pixle 4 XL Android 10: last patched March 5th 2020
Bitwarden Version 2.2.8 (2136)

Chrome is on Windows 10 Version	10.0.18363 Build 18363
Chrome Version 80.0.3987.132 (Official Build) (64-bit)
Bitwarden Version: 1.43.3

**Comment by kspearrin** [comment]
Can you try logging out and then back in?

**Comment by djsmith85** [comment]
Hi @shadoskill, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
