### ISSUE TITLE
Can't upload attachment to entry when I have lock option set to Immediately option

### ISSUE THREAD

**Issue by mKoonrad** [bitwarden/mobile#780]
## Describe the Bug
I can't upload attachment to entry when app lock is set to Immediately option. After choosing file from system file manager I need to unlock app. After unlocking app my earlier steps aren't saved.

## Steps To Reproduce
1. Open Bitwarden Android app
2. In settings set lock option to Immediately
3. Try to add attachment to any entry

## Expected Result
After choosing file from file manager I should have possibility to save this attachment.

## Actual Result
After choosing attachment app is locked. After unlocking app my earlier steps aren't saved. I need to try save attachment once again and once again. The only way to bypass this issue is changing lock option from Immediately another one.

## Environment
- Device: OnePlus 5T
- Operating system: Android 9.0
- Build Version: 2.3.0 (2251)
- Is this a Beta release? No

**Comment by clayadams5226** [comment]
Verified on Samsung 10
