### ISSUE TITLE
iOS bug: Stuck in the autofill pop-up interface

### ISSUE THREAD

**Issue by zhangchenkai** [bitwarden/mobile#785]
## Describe the Bug
Cannot pop up in the iOS password autofill settings, also the popup in iOS safari.

Until then, I have been using lastpass and it works normally.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/10665923/77072585-ea475180-6a28-11ea-9266-693557f18974.png)

## Environment

- Device:  iPhone6s
- Operating system:  iOS 13.3.1
- Build Version (go to "Settings" → "About" in the app): latest in AppStore
- Is this a Beta release? [N]

**Comment by zhangchenkai** [comment]
Also the app extension are not working. (If I remember correctly, this interface only rendered properly at the very first time. Then this problem persists when reinstalling the application.)

Reinstall and reboot cannot solve this problem.

![IMG_0711](https://user-images.githubusercontent.com/10665923/77075207-f503e580-6a2c-11ea-957b-325a2fde768b.png)

**Comment by kingrocks95** [comment]
Any solutions? I'm facing the same issue.

**Comment by zhangchenkai** [comment]
@kingrocks95 I had turned to 1password now. If you still want to report this problem, feel free to reopen this issue.

**Comment by github-account1111** [comment]
This is still happening on the latest version on iOS 14. With no way to exit other than force-closing the app and losing all the progress.
![IMG_3154](https://user-images.githubusercontent.com/5728319/97608469-4f751380-1a0a-11eb-83fd-2103d55ae432.PNG)

**Comment by mportune-bw** [comment]
@github-account1111 Are you seeing this when setting up autofill, or when using autofill after successful setup?  The issue fixed here was with setup.  The other issue was with swiping away the autofill interface during use (instead of hitting the `Cancel` button) which would result in a frozen splash screen.  That was fixed recently with #1117 but has not been pushed to production yet.
