### ISSUE TITLE
[Android] Tresor won't unlock if fingerprint mismatches at the first try

### ISSUE THREAD

**Issue by NiArq** [bitwarden/mobile#791]
## Describe the Bug
I setup Bitwarden to unlock with my fingerprint. If I want to use Bitwarden the following happens:
- I open the app
- fingerprint prompt appears
- first fingerprint mismatches
- second (or a following try) succeeds
- fingerprint prompt disappears
- tresor still locked

After that nothing happens. I have to tap on "use biometric data to unlock" or enter the password. That happens again and again until I succeed at the first try with my fingerprint.

## Steps To Reproduce

1. Setup Bitwarden to unlock with fingerprint
2. Lock Bitwarden if needed
3. Open Bitwarden / use biometric data to unlock
4. Fail on the first try at unlocking with your fingerprint
5. Succeed on a following try
6. Fingerprint prompt disappears and Bitwarden won't unlock.

## Expected Result

If the fingerprint matches at any try (even if the first try fails) your tresor should unlock.

## Actual Result

Nothing happens / tresor won't unlock. You're still on the main screen and have to unlock Bitwarden via password or biometric data.

## Screenshots or Videos

Can't take a screenshot or video from Bitwarden. The app blocks both of it.

## Environment

- Device: Huawei P30
- Operating system: Android 10 / EMUI 10.0.0
- Build Version (go to "Settings" → "About" in the app): 10.0.0.186 (C432E22R2P5)
- Is this a Beta release? No
- Bitwarden Version: 2.3.1

**Comment by watk** [comment]
I'm still seeing the issue. Could we reopen the issue please? I can reproduce it on the tip of master, built today. May I ask whether you verified that updating the libraries fixed this?

Thanks

**Comment by mportune-bw** [comment]
@watk The fix isn't in master yet.

**Comment by watk** [comment]
No problem, thanks!

**Comment by mportune-bw** [comment]
@watk Updating the libraries did indeed fix this on a Pixel 3, but I have since added additional devices to my test bed and confirmed it did not work across the board.  Your fix seems to fill the gap.  Thanks!
