### ISSUE TITLE
Android: Add Item button not labeled for Accessability

### ISSUE THREAD

**Issue by clayadams5226** [bitwarden/mobile#792]
## Steps To Reproduce

1. Navigate to device settings 
2. Tap on Accessibility 
3. Tap on Installed Services
4. Tap on "Talk Back" and switch it to "on"
5. Open Bitwarden
6. Tap on the "add Item" button

## Environment

- Device: Galaxy S10
- Operating system: Android 10
- Build Version (go to "Settings" → "About" in the app): 2.3.1 (2557)
- Is this a Beta release? N

**Comment by mportune-bw** [comment]
@clayadams5226 Try this in today's beta as well (it's working for me - the FAB lib was replaced with a custom view, and it announces itself as "Add Item Button" when clicked)

**Comment by clayadams5226** [comment]
@mportune-bw still reading as "unlabeled" for me.

**Comment by clayadams5226** [comment]
Issue seems to be resolved with latest app build.
