### ISSUE TITLE
Android: App crashes on Samsung Tab 3 upon tapping Log In

### ISSUE THREAD

**Issue by clayadams5226** [bitwarden/mobile#796]
## Describe the Bug
On a Samsung Tab 3 when the user taps Log In from a fresh install the application crashes

## Steps To Reproduce

1. Download the app on a Samsung Tab 3
2. Open the app
3. Tap Log In

## Expected Result

User is presented with the login screen

## Actual Result

App Crashes

## Environment

- Device: Samsung Tab 3
- Operating system: Originally reported on 4.4 replicated on 5.1.1
- Build Version 2.3.1
- Is this a Beta release? No (

## Additional Context

Logs attached
[error.log](https://github.com/bitwarden/mobile/files/4385249/error.log)

**Comment by mportune-bw** [comment]
@clayadams5226 Can you try this again with the beta that went live today?

**Comment by clayadams5226** [comment]
@mportune-bw issue seems to be resolved on the latest beta build.

**Comment by mportune-bw** [comment]
Solved by 915e8cf072bfcf77509271cc78cccf9d435bce28
