### ISSUE TITLE
IOS cannot use https with port

### ISSUE THREAD

**Issue by XPPA0215** [bitwarden/mobile#797]
## Describe the Bug
https://my.domin.com:8666
It can be used in webpage, PC and android,But it prompts ssl error on ios/macos.

## Steps To Reproduce

4. Click on '...'

## Actual Result
![image](https://user-images.githubusercontent.com/15919455/77655533-7ddecc00-6fad-11ea-8bf3-982e93c9ce20.png)

## Environment

- Device: [e.g. iPhonex]
- Operating system: [e.g. iOS 13.3.1]

**Comment by kspearrin** [comment]
Looks like an SSL issue. Are you using a self-signed certificate that your device doesn't trust?

**Comment by XPPA0215** [comment]
> Looks like an SSL issue. Are you using a self-signed certificate that your device doesn't trust?
Thank you for your reply.
Is signed by acme.
On the iphone, I use Chrome or safari, and the links are secure.
![image](https://user-images.githubusercontent.com/15919455/77658639-edef5100-6fb1-11ea-9f6c-12f446658431.png)

**Comment by XPPA0215** [comment]
Thanks, today I found a warning on Chrome on the MAC that doesn't exist on the PC.
![image](https://user-images.githubusercontent.com/15919455/77714559-41928680-7014-11ea-895f-da2015a85c0f.png)
I changed the configuration of nginx and now it works on ios
