### ISSUE TITLE
iOS: € (Euro Currency) sign displays incorrectly when viewing password

### ISSUE THREAD

**Issue by clayadams5226** [bitwarden/mobile#799]
## Describe the Bug

When I view the item in the Bitwarden iPhone App it's displayed as the following: â,¬
However, then I go into edit mode, the sign is displayed correctly as € sign.

## Steps To Reproduce

1. Open the iOS app
2. Add a new item 
3. Enter € as the password
4. Tap save
5. View the item password

## Expected Result

The password displays as €

## Actual Result

The item displays as â,¬

## Screenshots or Videos

![TestEditItem](https://user-images.githubusercontent.com/61576435/77727267-46354b80-6fd0-11ea-8308-388ca66d7e2d.png)
![TestViewItem](https://user-images.githubusercontent.com/61576435/77727269-46cde200-6fd0-11ea-973d-a595810a1f56.png)

## Environment

- Device: iPhone XS
- Operating system: 13.3.1
- Build Version (go to "Settings" → "About" in the app): 2.3.1 (64)
- Is this a Beta release? N

**Comment by kspearrin** [comment]
Seems like an encoding issue with that html string.
