### ISSUE TITLE
The latest released version cannot run on Android 10!

### ISSUE THREAD

**Issue by FanyangMengDev** [bitwarden/mobile#805]
Hi there, just upgraded Bitwarden to the latest beta version on Google Play. And I found that it keeps crushing. I cannot use it anymore!

My system is Android 10 MIUI 11, Mi 10 Pro

Please check and fix this problem thanks!!!!

**Comment by mportune-bw** [comment]
Build 2279 was just pushed to the beta channel and fixes the crash.  Google's review time is longer than usual due to adjusted work schedules, so it may take some time before it becomes available.

**Comment by tplunket** [comment]
Even leaving the beta program and installing the "retail" release leaves me with Bitwarden crashing almost immediately after startup. I'm not familiar with the Google Play beta stuff though so maybe it's just reinstalling the beta even though I've left the channel?

**Comment by mportune-bw** [comment]
@tplunket That would be my guess as well.  Have you tried re-installing again now that some time has passed after you left the beta?

**Comment by Chartman123** [comment]
> Build 2279 was just pushed to the beta channel and fixes the crash. Google's review time is longer than usual due to adjusted work schedules, so it may take some time before it becomes available.

Would it be possible to post the new build here for downloading and installing it until Google will publish it?

**Comment by FanyangMengDev** [comment]
@mportune-bw Actually it has been a few days and Google still has not published it. Could you please release the latest version here or in the release page which will make us upgrade it now? Now I have to join in beta version every day to check if it has been released and switch to stable verison again.

**Comment by nopynoop** [comment]
The latest Bitwarden beta 2.3.1 is also constantly crashing in Google Pixel 4 XL, running the latest Android 10 with March update.

**Comment by mportune-bw** [comment]
@FanyangMengDev and everyone else - Agreed, this is frustrating.  Here is the APK that we pushed to beta:

https://ci.appveyor.com/api/buildjobs/erijmv3pk5v2q9a2/artifacts/com.x8bit.bitwarden.apk

You should be able to remain in the beta after installing that.

**Comment by FanyangMengDev** [comment]
@mportune-bw Thank you very much for your understanding and link. I really like bitwarden. I hope we can have a place to push the new app immediately in the future, so that more users will not be limited by the publish speed of Google play

**Comment by Chartman123** [comment]
@mportune-bw works like a charm, thank you very much!

**Comment by ckujau** [comment]
I think I've received 3 [Signal](https://github.com/signalapp/Signal-Android) updates while waiting for the fixed Bitwarden release to be pushed to the Play Store. Can anyone explain what's the issue here? I'm hesitant to install `.apk` files from a random website.

Maybe the missing **release** is the problem here? According to [bitwarden/mobile/releases ](https://github.com/bitwarden/mobile/releases) the latest release is still `Version 2.3.1`, released 21 days ago. Or are Google packages generated from arbitrary git commits?

Hm, the "beta" in the "Beta Program" should've told me something :-)

**Comment by Flat** [comment]
The linked APK from a "random site" is signed with the same key used by the package for the Google play beta. Likely Google has given priority to certain app updates during this time.

**Comment by mportune-bw** [comment]
> I think I've received 3 [Signal](https://github.com/signalapp/Signal-Android) updates while waiting for the fixed Bitwarden release to be pushed to the Play Store. Can anyone explain what's the issue here? 

We don't know what Google's reasoning is here.  We can only guess that beta releases are lowest on their review priorities atm.

> I'm hesitant to install `.apk` files from a random website.

And you should be :) However that link is generated by our automated build system, and as @Flat mentioned is signed with the same key as the Google Play build.  If you (understandably) aren't comfortable with that, the best course of action would be to leave the beta via the Play Store and use the public release until this clears up.

> Maybe the missing **release** is the problem here? According to [bitwarden/mobile/releases ](https://github.com/bitwarden/mobile/releases) the latest release is still `Version 2.3.1`, released 21 days ago. Or are Google packages generated from arbitrary git commits?

The latter.

**Comment by txsjohnny** [comment]
I left your beta program after experiencing crash after crash with the Bitwarden app. I have uninstalled and re-installed it now 3 times to no avail. On the last re-install at least the app lets me get to the log-in screen but keeps giving me an "exception error." What gives Bitwarden? This is very frustrating.
![Screenshot_20200405-135306_Smart Launcher](https://user-images.githubusercontent.com/34135444/79030699-54ef3700-7b68-11ea-834d-f3d4e7e3699c.jpg)

**Comment by mportune-bw** [comment]
@txsjohnny See https://github.com/bitwarden/mobile/issues/805#issuecomment-609786671

**Comment by nopynoop** [comment]
So, 12 days later since the beta was pushed to the beta channel, still isn't approved by Google?

**Comment by mportune-bw** [comment]
@nopynoop That is correct.  We're just as confused as everyone else.

**Comment by Zamotic** [comment]
Just for the record, this is/was affecting users with Android 9 as well (both my Samsung Galaxy S8 and Samsung Tab S5E). Thank you for the link above, it was driving me crazy having to log into the vault website to get my saved passwords.

**Comment by reruem** [comment]
Still seems like the beta isnt available on the play store, at least for me on pixel 2

**Comment by tplunket** [comment]
@mportune-bw It's been a while so apologies for the time it took for me to respond... I figured out that the problem was that I have a "work" profile on my phone in addition to my personal profile, even though my work profile wasn't in the beta program, I guess the way that Google Play works is that it just linked the installations together so uninstalling/reinstalling in my "personal" profile just unlinked and relinked it to the installation that was shared. So I uninstalled from both profiles and then reinstalled out of the beta program and it was all good. FYI, this was a weird one and not obvious until I noticed that the re-install wasn't actually downloading anything.

**Comment by mportune-bw** [comment]
For everyone still following, beta 2279 is now live on the Play Store.

**Comment by nopynoop** [comment]
> For everyone still following, beta 2279 is now live on the Play Store.

I can confirm the beta version 2.3.1 was installed from Play Store and it's working fine.

Finally.

Thank you.

**Comment by ehlxr** [comment]
> For everyone still following, beta 2279 is now live on the Play Store.

The  beta 2279 on Google Play is working fine for me now. thx
