### ISSUE TITLE
Session Loss and Crash on v2.3.1

### ISSUE THREAD

**Issue by KinshipCourier** [bitwarden/mobile#809]
## Describe the Bug
I'm in the beta channel on Google Play. After updating to the newest version, I was logged out and experienced a consistent crash when attempting to log in again.

## Steps To Reproduce

1. Open app after update
2. Tap "Login" 
3. App Crashes
4. Wipe Data
5. Uninstall
6. Opt-out Google Play Beta Program for 
     Birwarden.
7. Install stable version (Success!)
8. Opt-in to Beta Program and Update.
9. Session is lost and app crashes when "Login" is pressed 

## Expected Result

Vault Session to be kept and accessible. 

## Actual Result

Vault Session is lost and irretrievable.

## Screenshots or Videos

Root-enabled logs.

[logcat_04-01-2020_01-10-12.txt](https://github.com/bitwarden/mobile/files/4412940/logcat_04-01-2020_01-10-12.txt)

## Environment

- Device: Google Pixel XL {Marlin}
- Operating system: LineageOS {Android 9}
- Build Version Version:

Cannot See App Version! I can't get to Setting>About>Version. The stable version with no problems is: 2.3.1 (2257) The current beta in Google Play is the version having issues.
- Is this a Beta release? Y

**Comment by Bluetexon** [comment]
Already seems to be resolved and fixed. See #805 :)
