### ISSUE TITLE
Test Sync to Asana

### ISSUE THREAD

**Issue by sevensixseven** [bitwarden/mobile#811]
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. iOS 8.1]
- Build Version (go to "Settings" → "About" in the app): [e.g. 2.3.0 (2221)]
- Is this a Beta release? [Y/N]

## Additional Context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1169444489336079/1169447398617223) by [Unito](https://www.unito.io/learn-more)

**Comment by kspearrin** [comment]
➤ Aaron Marshall commented:

Update to GitHub

**Comment by sevensixseven** [comment]
Test complete.
