### ISSUE TITLE
Last Android Beta Release completely breaks the app

### ISSUE THREAD

**Issue by dougmaitelli** [bitwarden/mobile#812]
## Describe the Bug

Since last Bitwarden Android Beta release (1 or 2 days ago) the app does not work at all, it just crashes right after opening. Rolling back to the non beta version fixes the issue.

## Environment

- Device: Pixel 4 XL
- Operating system: Android 10
- Build Version: No idea, the app don't even open
- Is this a Beta release? Y

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1169444489336079/1169473987984575) by [Unito](https://www.unito.io/learn-more)

**Comment by mportune-bw** [comment]
See #805
