### ISSUE TITLE
Bitwarden crashes when trying to log in

### ISSUE THREAD

**Issue by julroy67** [bitwarden/mobile#813]
## Describe the Bug

Bitwarden crashes when trying to log in.

## Steps To Reproduce

1. Open Bitwarden
2. Click on "Login"
3. Crash occurs

## Expected Result

Bitwarden should not crash when trying to login.

## Actual Result

Bitwarden crashes when trying to login.

## Screenshots or Videos

[Bitwarden_crash_video.zip](https://github.com/bitwarden/mobile/files/4419924/Bitwarden_crash_video.zip)

## Environment

- Device: OnePlus 6
- Operating system: Android 10
- Build Version (go to "Settings" → "About" in the app): 2.3.1
- Is this a Beta release? Y

## Additional Context

Happens since last update (update pushed to beta channel of Play Store)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1169444489336079/1169544834636489) by [Unito](https://www.unito.io/learn-more)

**Comment by Forsaked** [comment]
Can confirm this, same here with Beta App.

**Comment by kspearrin** [comment]
DUplicate
