### ISSUE TITLE
Bug after update

### ISSUE THREAD

**Issue by AndreKoepke** [bitwarden/mobile#815]
## Describe the Bug
I am using bitwarden as a self-hosted service. After the update (which was shipped yesterday, I think) the app on all my devices stopped working. The app crashes after startup (only a few seconds). The new version is 2.3.1

I tried to delete cache and app-data already.

## Steps To Reproduce

1. Install v2.3.1
2. Enter the address of a self-hosted bitwarden
3. Press "Sign in"
4. Now the app crashes and by now after each start.

## Environment

- Device: Galaxy S7, Galaxy S8
- Operating system: Android 9, Android 8
- Build Version (go to "Settings" → "About" in the app): 2.3.1 (2276)
- Is this a Beta release? No

## Additional Context

Maybe it happen only with my server. Try to use: "https://pass.akop.online"

And a screen of the stacktrace. I dont know how to get the stacktrace as text.
![image](https://user-images.githubusercontent.com/15613049/78254763-a8bda880-74f6-11ea-8d36-12fed92a92c1.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1169444489336079/1169585761642855) by [Unito](https://www.unito.io/learn-more)

**Comment by mportune-bw** [comment]
2276 is a beta (2257 is current production).  See #805

**Comment by AndreKoepke** [comment]
Oh, my bad. Sorry. :see_no_evil:
