### ISSUE TITLE
Bitwarden crashes on Dark Theme Xiaomi Mi9

### ISSUE THREAD

**Issue by achmetinternet** [bitwarden/mobile#821]
## Describe the Bug

Today a new MIUI update rolled out for the Xiaomi Mi9 SE. Since then I am running my OS in dark mode and so all apps adapt except Bitwarden so far seems to have a problem. It starts but then crashes.

## Steps To Reproduce

Install Bitwarden on a Xiaomi with the newest OS and set it to dark mode. Try to open Bitwarden.

## Expected Result

For Bitwarden to work :)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1169444489336079/1169880440670880) by [Unito](https://www.unito.io/learn-more)

**Comment by 2q1w2007** [comment]
My phone is xiaomi9. The APP crash everytime when I try to login after update in play store. I have clean all data of the app, but crash still occur whether the dark mode is on or off. I think its not related to the dark mode.

**Comment by 2q1w2007** [comment]
> My phone is xiaomi9. The APP crash everytime when I try to login after update in play store. I have clean all data of the app, but crash still occur whether the dark mode is on or off. I think its not related to the dark mode.

Maybe the issue #805 cause the crash on my phone.

**Comment by mportune-bw** [comment]
@2q1w2007 Can you try installing the beta using the APK link I posted in #805 ?  Hopefully that's all it is.

**Comment by 2q1w2007** [comment]
> @2q1w2007 Can you try installing the beta using the APK link I posted in #805 ? Hopefully that's all it is.

Thanks, the problem solved on my phone.

**Comment by mportune-bw** [comment]
Glad to hear it!
