### ISSUE TITLE
When using BitWarden accessibility on Android, other app crashes due to interference  

### ISSUE THREAD

**Issue by l-ra** [bitwarden/mobile#824]
## Describe the Bug

ButWarden interfere with other app (@Voice Aloud Reader). When Accessibility is granted to BitWarden, it causes crashing the @Voice Aloud Reader application under certain circumstances. 
When the screen of @Voice Aloud Reader contains many short lines of text, it crashes when BitWarden is allowed to use accessibility API. When I disable BitWarden accessibility API access, the @Voice application stops crashing.

## Steps To Reproduce

Unfortanutelly I can't share the file that causes crashes in other app due to BitWarden interference as it is copyrighted material.  But the reproduction is as follows:
1. install BitWarden
2. install @Voice Aloud Read
3. open epub book with a part containing many short paragraphs
4. let the @Voice read aloud text using TTS
5. see the app crashing

## Expected Result

No interference which causes crash or a setting in BitWarden to blacklist certain apps from accessibility. 

## Actual Result

Crashes of other app due to interference.

## Environment

- Device: Doogee BL7000 
- Operating system: Android 7
- Build Version (go to "Settings" → "About" in the app): 2.3.1 (2257)
- Is this a Beta release? N

**Comment by mportune-bw** [comment]
I'm unable to reproduce this using @Voice Aloud Reader (free) version 19.5.5 with an epub containing lots of short paragraphs (technical documentation so it's full of one-liners).  I've not customized any settings in the Reader app - is there maybe something else I should adjust?

**Comment by l-ra** [comment]
After further testing I discovered it is not bitwarden issue only. Tasker and other applications using accessibility setting is causing the interference. I suppose it is not bitwarde issue but the OS or the Voice app.
