### ISSUE TITLE
[Android] unable to login on pokemon go app

### ISSUE THREAD

**Issue by eleith** [bitwarden/mobile#826]
when the password field first gets focus, the bitwarden overlay briefly flashes near the bottom before disappearing.

one can time it very quickly to tap the pop-up, then select the login, but the password is still never entered.

autofill in quick settings doesn't work either. 

no workaround seems to exist, other than memorizing the password (the app somehow disables pasting into the form fields)

## Environment

- Device: pixel 2
- Operating system: 10
- Build Version: 2299
- Is this a Beta release? Y

## Additional Context

possibly related to #784 . 

however I can use bitwarden to login to other apps just fine. only this app is problematic (which appears to use custom fields / opengl and not the default Android sdk).

**Comment by mportune-bw** [comment]
I think your theory about non-standard fields is correct.  They don't even show up as editable nodes from accessibility, which may also explain the lack of system-level cut/copy/paste controls.  The node position returned is also questionable (X:1056984576, Y:2030 on a Pixel 3) resulting in the overlay appearing at the bottom right then immediately removed once it's established that the keyboard is open.

If the fields were at least editable from the system's point of view, the quick settings tile would function as a workaround.  However I believe the best thing would be for Niantic to implement Autofill Service support for use with password managers.  Without that I don't think there's anything we can do here.

**Comment by eleith** [comment]
@mportune-bw why does the bitwarden auto fill dialog show up briefly when the password field does get focus (and then disappears)?

**Comment by mportune-bw** [comment]
The pressed/focused node is seen as `password` type to accessibility which is what kicks off the process and draws the initial overlay and begins tracking the anchor's position on screen.  However due to the odd anchor coordinates returned by accessibility the overlay is drawn at the bottom/right of the screen, and our secondary tracking code sees this as being behind the keyboard so it's immediately hidden.

**Comment by eleith** [comment]
after some testing, i was able to get auto-fill in the quick settings to work. i just had to spam it a couple of times. most of the time, no text is filled, but eventually it gets filled in.

anyhow, thanks for looking into it. much appreciated.

**Comment by mportune-bw** [comment]
Interesting, thanks for the followup.
