### ISSUE TITLE
Unable to use the app at all due to crashing when it opens

### ISSUE THREAD

**Issue by CorruptComputer** [bitwarden/mobile#832]
## Describe the Bug
I have been unable to use the mobile app for about a month now, and have been hoping for an update to fix it. But no update has come through, so I'm thinking that this may have not been reported yet. The app constantly crashes when I try to log into sites and I can't even open the app itself as it crashes immediately when opening.

## Steps To Reproduce
1. Open the app, or have the autofill prompt pop up
2. CRASH

## Expected Result
The app shouldn't crash.

## Actual Result
The app crashes.

## Screenshots or Videos
I can't copy and paste the stacktrace, but here is a screenshot of it. I did submit the crash report through the feedback pop-up if you're able to look it up somehow.
![image](https://user-images.githubusercontent.com/5573038/79253200-6aa27c00-7e48-11ea-80dd-35a681795e72.png)

## Environment
- Device: Pixel 2 XL
- Operating system: Android 10, April 5 2020 Security Patch (Although its been crashing since last month)
- Build Version (go to "Settings" → "About" in the app): 2.3.1, I'm not able to open the app.
- Is this a Beta release? Yes...? Not quite sure, I'm in the beta on Google Play but I don't know if this is a beta release or not.

## Additional Context
I've tried clearing data and cache, as well as reinstalling the app. But no luck in getting it to work. This started last month around the time 2.3.1 released but I also updated Android on the same day, so I'm not sure which is the cause.

**Comment by tgreer-bw** [comment]
This is actually a known item - the beta release crashes, well that build anyway. It’s been fixed but the beta hasn’t made it out to the play store yet (it’s been submitted, though)

You can find the whole story here: https://github.com/bitwarden/Mobile/issues/805

**Comment by CorruptComputer** [comment]
@tgreer-bw Ah my bad, I had not seen that issue! Installing the APK provided by the Bitwarden team fixed the issue and it works perfectly now. Thank you!
