### ISSUE TITLE
Android Accessability Permission Popup persists when permission has been granted

### ISSUE THREAD

**Issue by AutumnalAntlers** [bitwarden/mobile#836]
## Describe the Bug

On both my Moto G6 Play (Android 9, build PPS29.118-68-5) and a housemate's Samsung A10, Bitwarden Autofill functions perfectly fine, but the grey notification that Accessibility permissions needs enabled persists even though all permission have been enabled through the links in the bitwarden settings. It does not appear every time, but frequently. I've disabled a variety of packages (such as google play services) on my phone, and am not surprised by apps misbehaving, but having seen the behavior on a stock A10, I thought I'd make a report. Please comment if you have experienced this issue yourself.

**Comment by doctor-owl** [comment]
I've been experiencing this too. Samsung Galaxy S9+ with Android 10. Only pops up sometimes.

**Comment by 2q1w2007** [comment]
Permission requirement pop up too on my mi9 with Android10.
