### ISSUE TITLE
Not able to add new login credentials. 

### ISSUE THREAD

**Issue by rohanvitrouthu** [bitwarden/mobile#838]
## Describe the Bug

I have been trying to add login credentials for a new website but I have not been able to do so for the past few days. 

## Steps To Reproduce

1. Open Bitwarden app. 
2. Tap on '+' button at the bottom-right of the screen. 
3. Specify login as the type. 
4. Fill all the necessary credentials. 
5. Tap on Save once done.

## Expected Result

I expected the app to succefully save the login credentials. 

## Actual Result

Once I tap on 'Save' it keeps loading and it doesn't save the credentials. 

## Environment

- Device: Samsung Galaxy J7 Prime
- Operating system: Android 8.1
- Build Version (go to "Settings" → "About" in the app): M1AJQ.G610FDDU1CSK2
- Is this a Beta release? [Y/N]: N

**Comment by kspearrin** [comment]
Are you using the Bitwarden cloud server or self-hosted?

**Comment by rohanvitrouthu** [comment]
Hey, I am using Bitwarden cloud server I think because I don't remember
configuring anything to self host those credentials.

**Comment by kspearrin** [comment]
Can you try another network and see if that may be the issue? For example, switch to wifi or a mobile network?

**Comment by rohanvitrouthu** [comment]
Yes it's working on mobile data.

**Comment by kspearrin** [comment]
Are you able to access bitwarden.com website?

**Comment by rohanvitrouthu** [comment]
Yes I am able to access the website

**Comment by kspearrin** [comment]
How about https://api.bitwarden.com/alive ?

Also, try reinstalling the app maybe?

**Comment by rohanvitrouthu** [comment]
Yeah reinstalling the app made the difference. Now I am able to add new
login credentials through the app on wi-Fi.

**Comment by rohanvitrouthu** [comment]
Thank you for all the help.
