### ISSUE TITLE
Autofill on iOS freezes at startup/logo overlay

### ISSUE THREAD

**Issue by Twiglet1022** [bitwarden/mobile#839]
## Describe the Bug
The functionality to autofill passwords within apps on iOS regularly freezes at the point where the Bitwarden overlay shows up.
## Steps To Reproduce

It breaks regularly (more than a third of the time) but inconsistently so these steps aren’t guaranteed to reproduce the issue.

1. Go to any website or app that you have a login for.
2. Select the username field to bring up the keyboard.
3. Try to autofill the password by tapping on the prompt above the keyboard.

## Expected Result
Bitwarden overlay will show up, ask for my fingerprint, then present me with autofill options.
## Actual Result
Bitwarden overlay either fails to appear or gets frozen.

## Screenshots or Videos
Here is a GIF demonstrating the scenario where the overlay appears and freezes.

https://gfycat.com/gratefulbogusantelopegroundsquirrel

## Environment

- Device: iPhone SE (1st gen)
- Operating system: iOS 13.4
- Build Version (go to "Settings" → "About" in the app): Version: 2.3.1 (64)
- Is this a Beta release? N

## Additional Context
Sometimes the Bitwarden overlay shows up and just hangs there. Sometimes just a transparent overlay shows up which I can actually drag down off the screen. Other times simply nothing happens.

I’ve had this problem for over 6 months so it’s been persistent for at least a few versions of the app and multiple updates to iOS.

In the GIF I have shared, my username didn’t show up above the keyboard as it often does. But this happens regardless of that. I just chose this example to record because it doesn’t have my username/email in it.

The only resolution I have found is to simply wait until it begins working again. This could be as little as 10 minutes, to as long as hours. Things I have tried to fix it which have all failed:

- Toggling autofill passwords on/off in iOS settings
- Opening the app (I can open the app fine and copy the password from there, but autofill still doesn’t work)
- Toggling iOS keychain on/off (I leave it off)
- Having the in app extension on and off (I understand it’s unrelated, but thought I’d try)
- Reinstalling Bitwarden.
- Erasing my phone and reinstalling iOS (I was desperate)

Just to demonstrate that this does sometimes work when doing the exact same thing. It worked for me about an hour later:

https://gfycat.com/tediousaltruisticherculesbeetle

https://gfycat.com/bogusoddamurratsnake

**Comment by kspearrin** [comment]
Thanks. We'll need to see if we can observe an errors or crash reports around this.

**Comment by I-like-stuff** [comment]
I too am having this problem using iPadOS 13.5.5 (17G5035d) Public Beta 1
