### ISSUE TITLE
Sharing entry only shows one collection (iOS)

### ISSUE THREAD

**Issue by Kofl** [bitwarden/mobile#841]
Hi,

latest iOS release of the Bitwarden app.
If you share an item, it only shows one organization although I would have to organizations to share items with.

Sharing with the webclient or browsers plugins shows all available organizations.

Best,
Thomas

**Comment by kspearrin** [comment]
I cannot reproduce the issue. Have you tried syncing?

**Comment by Kofl** [comment]
Thanks for the fast response, reinstall solved the issue. B
