### ISSUE TITLE
Overlay accessibility popup -- bad user experience compared to the old notification

### ISSUE THREAD

**Issue by hokkanen** [bitwarden/mobile#870]
#  Describe the Bug

Two main problems introduced by Version 2.3.0:

1. Autofill popup often hides important text or buttons which are needed at the login page
 - having an option to use the old-style notification fixes this
 - a movable/minimizable popup could be helpful as well

2. Not all password fields are recognized 
 - having an option to use the old-style persistent notification fixes this

## Environment

- Device: Samsung S20
- Operating system: Android 10

## Additional Context

Please bring back the old notification option for submitting the credentials. Currently the only solution is to use version 2.2.8.

**Comment by kspearrin** [comment]
@hokkanen We have an autofill tile available in the latest beta. This behaves similarly to the old notification way.

**Comment by mportune-bw** [comment]
@hokkanen The way the old notification worked was not battery-friendly.  As Kyle mentioned you can use the new autofill tile to achieve the same behavior in the latest beta.  It also includes numerous improvements to the popup handling as well.  I recommend switching over and if you still encounter issues, file bugs with additional details (browser, url, & app settings) as these all affect how accessibility works.
