### ISSUE TITLE
Issues with €-sign in password on iOS App

### ISSUE THREAD

**Issue by heidlma** [bitwarden/mobile#871]
## Steps To Reproduce
1. Setup a new login-information with any username and  a password containing the "€" sign.
2. Sync Vault
3. Open iOS-App, search for the new generated password and in the search result, click on the "eye"-button to display it. It shows up scrambled as in screenshot attached.
4. However, when you edit the password in the iOS app, it is displayed correctly. 

So far, so goo.
## Expected Result

Expected result is, that the correct password is pasted into apps.

## Actual Result
It seems to copy over the scrambled password to the apps. I was not able to login with such a password until I edited the entry in the app and manually copied the password. 

## Screenshots or Videos
Screenshot shows scrambled password, it should actually read "PasswordWith€Sign"

## Environment

- Device: iPhone 7
- Operating system: iOS 13.4.1
- Is this a Beta release? N
<img width="375" alt="2020-05-03 10-39-23-1" src="https://user-images.githubusercontent.com/25526560/80909721-bb601300-8d2a-11ea-8eac-208841d3c832.png">

**Comment by mportune-bw** [comment]
Already fixed in #746
