### ISSUE TITLE
OVERLAY not working in Opera browser for Android

### ISSUE THREAD

**Issue by THEOCKID** [bitwarden/mobile#885]
Quick flash of bitwarden fill box below username or password field then gone. Stays up about 0.25 sec, maybe less. Too fast for me to click on. 

## Steps To Reproduce

4. Click on '...'

## Environment

- Device: Samsung Galaxy S20+
- Operating system: Android OS v 10. Build number  QP1A.190711.020.G986USQU1ATCT
- Build Version (go to "Settings" → "About" in the app): Version: 2.3.1 (2257)
- Is this a Beta release? N

**Comment by mportune-bw** [comment]
This is fixed in the beta and will be included in the next public release.
