### ISSUE TITLE
[Android] App theme isn't selected via global theme setting.

### ISSUE THREAD

**Issue by the4anoni** [bitwarden/mobile#894]
Describe the Bug
Default theme is always white,  app ignores system-wide android theme setting.

## Steps To Reproduce

1. Run app.

## Expected Result

App launches with theme based on theme flag.

## Actual Result

App will always launch with white theme, until it will be changed manually in app settings.

## Environment

- Device: Samsung Galaxy S10
- Operating system: Android Q OneUi 2.1
- Build Version: 2.3.1 (2413)

**Comment by jean-io** [comment]
Same on iOS: no system wide dark mode support.
