### ISSUE TITLE
[Android] Auto-fill doesn't work on Samsung browser Stable and Beta.

### ISSUE THREAD

**Issue by the4anoni** [bitwarden/mobile#895]
##  Describe the Bug

Like in topic

## Steps To Reproduce

Try to login via auto-fill on Samsung browser. 

## Expected Result

Bitwarden auto-fill suggest you to fill passwords. 

## Actual Result

There isn't suggestion to auto-fill login and password 

## Screenshots or Video
![Screenshot_20200510-223101_Samsung Internet](https://user-images.githubusercontent.com/13403084/81510073-85fd8b80-930f-11ea-8863-0027aba5d4fd.jpg)

## Environment

- Device: Samsung Galaxy S10
- Operating system: Android Q OneUI 2.1
- App Build Version: 2.3.1 (2413)

**Comment by mportune-bw** [comment]
Samsung released an updated browser beta today which properly allows both the autofill service and our autofill accessibility service to function.

**Comment by dardaner** [comment]
I can't make it work automatic filling
- I have installed the latest beta version of Samsung Internet
- I installed the latest version of Bitwarden
But Bitwarden autofill on Android 10 still doesn't work

**Comment by the4anoni** [comment]
Autofill also doesn't work for me, I have latest Bitwarden and tried on latest S Browser Beta

**Comment by mportune-bw** [comment]
Beta version 12.0.1.4 is working with both accessibility and autofill service (though their autofill service values are a bit strange - give the beta more time to cook).

![device-2020-05-13-090941](https://user-images.githubusercontent.com/59324545/81816822-dcc6b900-94f9-11ea-9c35-a895bdd87e99.png)

**Comment by dardaner** [comment]
Hello
thank you for your reply
Where can we find the beta versions of Bitwarden and Samsung Internet Browser 12.0.1.4
Do you have any links please?
Thank you

**Comment by dardaner** [comment]
It's good it works, THANKS: +1:
i found on apk mirror
For those who are interested
https://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-internet-beta/samsung-internet-beta-12-0-1-4-release/

for me it works with Bitwarden 2.3.1 official version, without beta version
but with Samsung Internet Browser Beta 12.0.1.4

**Comment by mportune-bw** [comment]
It's also available on the Play Store as a separate installation:

https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser.beta

**Comment by dardaner** [comment]
do you have a link for Bitwarden in beta version? I can't find it
Thank you

**Comment by mportune-bw** [comment]
For Bitwarden use the 'join beta' button on our Play Store page and your existing installation will be upgraded.

**Comment by the4anoni** [comment]
Auto fill doesn't works for me
Bitwarden app version: 2.3.1 (2413)
![Screenshot_20200518-170034_Samsung Internet Beta](https://user-images.githubusercontent.com/13403084/82228393-5959fd00-9929-11ea-9d28-7197e4c6d606.png)

**Comment by the4anoni** [comment]
@mportune-bw I also tried v11.1.2.2 but it also doesn't work

**Comment by mportune-bw** [comment]
@the4anoni It definitely requires the newer v12.x.x.x release, but unfortunately I'm not sure why that isn't even working for you when it works for others (as well as myself).  Maybe something else on your device is interfering with autofill and/or accessibility?

**Comment by the4anoni** [comment]
> @the4anoni It definitely requires the newer v12.x.x.x release, but unfortunately I'm not sure why that isn't even working for you when it works for others (as well as myself). Maybe something else on your device is interfering with autofill and/or accessibility?

Auto fill works on chrome

**Comment by mportune-bw** [comment]
Did you check the settings in v12?  `Settings > Privacy and security > Autofill forms`

**Comment by OJ7** [comment]
> Did you check the settings in v12? `Settings > Privacy and security > Autofill forms`

Tried with this enabled/disabled and still not working on latest beta for both apps. 
Also tried disabling the options under Usernames and Passwords to see if that made any difference but no luck.

**Comment by mportune-bw** [comment]
I'm at a loss.  I'll keep an eye out for any clues as to why it's not working for you, but for the moment... /shrug

**Comment by the4anoni** [comment]
> Did you check the settings in v12? `Settings > Privacy and security > Autofill forms`

I had enabled this, but auto filk still doesn't work.
Samsung Internet 12.0.1.17 beta

**Comment by MatyCZ** [comment]
I have the same problem, autofill doesn`t work in Samsung Internet. Tried enable/disable some options in Setting and still not working.

Autofill works in Edge and Chrome on same device.

Bitwarden Beta 2.3.1 (2413)
Samsung Internet Beta 12.0.1.17

**Comment by the4anoni** [comment]
@mportune-bw can you re-open issue?

**Comment by dardaner** [comment]
With me it works
Not always 100%, but it works when it wants
Some sites are not working well yet, automatic detection is not always reactive

Conditions for it to work
- install Bitwarden Beta 2.3.1 (2413) on PlayStore
- install Samsung Browser Beta 12.0.1.4 on APK mirror
- I use Gboard the Google keyboard
- In Parameters / System / Language and input / Automatic input service: Select Bitwarden
- Being on Android 10
- Activate the filling and accessibility options on Bitwarden

**Comment by the4anoni** [comment]
> With me it works
> Not always 100%, but it works when it wants
> Some sites are not working well yet, automatic detection is not always reactive
> 
> Conditions for it to work
> 
> * install Bitwarden 2.3.1 on PlayStore
> * install Samsung Browser Beta 12.0.1.17 on APK mirror
> * I use Gboard the Google keyboard
> * In Parameters / System / Language and input / Automatic input service: Select Bitwarden
> * Being on Android 10
> * Activate the filling and accessibility options on Bitwarden
> * In the Settings of Samsung Browser,
>   1 .Settings / Useful functions / Authorized applications / Bitwarden ACTIVE
> 
> 1. Parameters / Confidentiality and security / Automatic filling of ACTIVE forms

Can you give one example site on which auto fill works?

**Comment by UQzero** [comment]
Try this.
1. Enter the address below in the url text box of the Samsung browser
internet://flags/#force-renderer-accessibility
2. Change WebAccessibility to enable and then restart browser
3. That could work.

p.s. Sorry I can't speak English. I wrote it with a translator.

**Comment by the4anoni** [comment]
> Try this.
> 
> 1. Enter the address below in the url text box of the Samsung browser
>    internet://flags/#force-renderer-accessibility
> 2. Change WebAccessibility to enable and then restart browser
> 3. That could work.
> 
> * Please upgrade Samsung browser and bitwarden to beta.
> 
> p.s. Sorry I can't speak English. I wrote it with a translator.

Doesn't work for me, tried on last SBrowser beta and Bitwarden last beta.

**Comment by the4anoni** [comment]
Sbrowser beta 12.0.1.36 and bitwarden 2.4.3, autofill still doesn't work @mportune-bw

**Comment by neodada** [comment]
> Sbrowser beta 12.0.1.36 and bitwarden 2.4.3, autofill still doesn't work @mportune-bw
Working fine here

**Comment by neodada** [comment]
It doesn't work fine. For example google account sign in. I would suggest to implement a keyboard for such cases.
https://github.com/bitwarden/mobile/issues/62

**Comment by the4anoni** [comment]
![Screenshot_20200613-122453_Samsung Internet Beta](https://user-images.githubusercontent.com/13403084/84566396-f49b9200-ad70-11ea-90ad-664dc93b1892.png)
Now it works for me :)

**Comment by neodada** [comment]
@the4anoni clicking on that fills password not email address.

**Comment by the4anoni** [comment]
> @the4anoni clicking on that fills password not email address.

Only on google.com, on github it works ok.

Also on chrome I've noticed this same bug.

**Comment by OJ7** [comment]
Auto fill seems to finally work now after the most recent Samsung Internet (not beta) update.

**Comment by alksjd** [comment]
> Auto fill seems to finally work now after the most recent Samsung Internet (not beta) update.

I get the auto-fill option but clicking on it doesn't give me respective login details instead I get this prompt 'there are no items in you vault for com.sec.android.app.sbrowser.beta'.

**Comment by raghusundaram** [comment]
> Auto fill seems to finally work now after the most recent Samsung Internet (not beta) update.

Can you please report back the exact version number ?

**Comment by raghusundaram** [comment]
I want to make it clear the problem some people face in using the Auto-fill service using the accessibility feature.

Don't try to use Bitwarden with any browsers in Android until and unless it natively surfaces Bitwarden using Android Autofill API.
Forcing the browsers to integrate with Bitwarden using accessibility service would be useless.
As Bitwarden can only know the application name using accessibility service and not the website URL.
In that case, it would offer incorrect choices.

Instead you can use Bitwarden with any apps such as Instagram, or your banking app in Android.
As in this case, Bitwarden just needs to know the application name alone.

**Comment by aaronstc1** [comment]
For me auto fill "works" but it just seems Samsung Browser as an app and won't show me webpage log ins like in chrome.

**Comment by raghusundaram** [comment]
> For me auto fill "works" but it just sees Samsung Browser as an app and won't show me webpage log ins like in chrome.

Please refer my previous comment.
I have given a clear explanation.

**Comment by yurividal** [comment]
Any updates on this? As mentioned above, accessibility services is NOT an option for using with this browser.

**Comment by douglasparker** [comment]
I'm having major issues with the autofill service in Samsung Internet for a long time now. Is there any more information on this @mportune-bw?

**Comment by yurividal** [comment]
> I'm having major issues with the autofill service in Samsung Internet for a long time now. Is there any more information on this @mportune-bw?

As far as I understand, Samsung is not too committed to implementing this on their browser, since they rather push users to their own Samsung Pass. But, maybe when they upgrade their chromium base in future builds this might get inherited. 
I have tried to reach many of Samsung browser's devs on their Twitter and their Blog, and on Samsung forums, about this, but I am always ignored.

**Comment by douglasparker** [comment]
> > I'm having major issues with the autofill service in Samsung Internet for a long time now. Is there any more information on this @mportune-bw?
> 
> As far as I understand, Samsung is not too committed to implementing this on their browser, since they rather push users to their own Samsung Pass. But, maybe when they upgrade their chromium base in future builds this might get inherited. 
> I have tried to reach many of Samsung browser's devs on their Twitter and their Blog, and on Samsung forums, about this, but I am always ignored. 

Damn, that is extremely unfortunate. Hopefully they'll fully embrace the autofill framework to push more users to their browser.

**Comment by Tosko4** [comment]
@mportune-bw  i found out when it stops working and what to do as a workaround to make it work again. When I go to the tab view in Samsung internet and open a new tab, i go to the login page it doesn't work. When I close the samsung internet app and re-open it. It starts loading the login page of that particular website again and voila, bitwarden works.

Test scenario 2: when i open two new tabs with two different websited and go to the login pages of both websites, close samsung internet and reopen the app, then bitwarden works on both tabs. I can switch between the tabs and it remains working. When I close one of the two and the other one remains working until both tabs are closed and obviously to browse you need a new tab.

So, workaround for now is: when I reach a login page, close samsung internet and reopen. Even though this workaround works 100% of the time for me, it has become slightly annoying that I have to keep doing this. Is this a bitwarden or samsung internet app issue?

Versions
Bitwarden: Version: 2.9.1 (3444)
Samsung Internet: 14.0.1.62

**Comment by Tosko4** [comment]
> @mportune-bw i found out when it stops working and what to do as a workaround to make it work again. When I go to the tab view in Samsung internet and open a new tab, i go to the login page of that particular website, and bitwarden doesn't work. When I close the samsung internet app and re-open it. It starts loading the login page of that particular website again and voila, bitwarden works.
> 
> Test scenario 2: when i open two new tabs with two different websited and go to the login pages of both websites, close samsung internet and reopen the app, then bitwarden works on both tabs. I can switch between the tabs and it remains working. When I close one of the two and the other one remains working until both tabs are closed and obviously to browse you need a new tab.
> 
> So, workaround for now is: when I reach a login page, close samsung internet and reopen. Even though this workaround works 100% of the time for me, it has become slightly annoying that I have to keep doing this. Is this a bitwarden or samsung internet app issue?
> 
> Versions
> Bitwarden: Version: 2.9.1 (3444)
> Samsung Internet: 14.0.1.62
> 
> Edit: also raised an issue with samsung regarding samsung internet app. So both parties can have a look at it. It seems to be more of an issue with Samsung Internet app than Bitwarden. As if theres a bug how Samsung Internet allows third party apps to use the auto fill feature. Because Bitwarden works fine on other browser apps (chrome, brave and above confirmed by other users: firefox etc)

So response from Samsung is expected utterly useless!! Or the support agent didn't take the time to really read my error description or lack the knowledge to think and see the bigger picture. Their response was:

```
Dear Customer,

Thank you for contacting us. We appreciate the opportunity to assist you.

I understand you wish to use third party apps. Since we are not directly afilitated we can offer no assistance in this regard. Samsung will not change the browser for a company they have no partnerships with.

Also know that you might receive a short survey regarding our interaction. Please take a few seconds to it fill out it would greatly help us improve our customer support experience!
```

I have sent a new inquiry to have them read my problem description again and try to think along. Or is there something you can do without their support @mportune-bw

**Comment by yurividal** [comment]
Try contacting them on Twitter @samsunginternet.  Their Browser development team is based in the UK, and seems to be pretty separate from the rest of their development, which takes part mostly in India.

**Comment by Tosko4** [comment]
> Try contacting them on Twitter @SamsungInternet. Their Browser development team is based in the UK, and seems to be pretty separate from the rest of their development, which takes part mostly in India.

I just sent them an email. Hope we get a better response or at least a point into the right direction if they're convinced its not a samsung internet issue.

**Comment by mportune-bw** [comment]
> `Samsung will not change the browser for a company they have no partnerships with.`

@Tosko4 This is the only substance in the reply.  Awhile back we tested the theory that they were whitelisting 3rd party password managers instead of allowing use of the API across the board.  I renamed the Bitwarden package name to match another popular password manager that we know works for sure with Samsung Internet, and viola - Bitwarden worked perfectly.  We've made several attempts to contact Samsung to add Bitwarden to the whitelist, but we've never received a response.

**Comment by Tosko4** [comment]
> > `Samsung will not change the browser for a company they have no partnerships with.`
> 
> @Tosko4 This is the only substance in the reply. Awhile back we tested the theory that they were whitelisting 3rd party password managers instead of allowing use of the API across the board. I renamed the Bitwarden package name to match another popular password manager that we know works for sure with Samsung Internet, and viola - Bitwarden worked perfectly. We've made several attempts to contact Samsung to add Bitwarden to the whitelist, but we've never received a response.

@mportune-bw It's weird. If bitwarden is not whitelisted, then it shouldn't work at all right? Maybe a silly question. But it works for me when I close and reopen samsung internet app. So I tend to lean more towards what @yurividal said, the android autofill api compatibility, no?

**Comment by mportune-bw** [comment]
@Tosko4 It's hard to say for sure.  The fact that it _sometimes_ works without the whitelist could just be a bug in their whitelist implementation.  I can tell you this much though - we don't receive a single blip from the autofill event stream when using Samsung Internet (without the forged package name).  It's like it's not even turned on.

**Comment by Tosko4** [comment]
@mportune-bw gotcha, thanks for responding. I have sent an update to samsung, hoping they respond *fingers crossed*  i'll keep you guys posted

**Comment by yurividal** [comment]
The "sometimes" working is probably the legacy "Accessibility" api...
We need to make some noise, get our voice heard and hopefully the Samsung Internet team will do something about it...

**Comment by Phangan** [comment]
Could you give us a "beta" version that has a forged package name until Samsung has finally fixed this?

**Comment by douglasparker** [comment]
You'd think Samsung would want to gain market share for their mobile browser. 🤔

**Comment by mportune-bw** [comment]
> Could you give us a "beta" version that has a forged package name until Samsung has finally fixed this?

That would be a bad idea for lots of reasons that are beyond the scope of this issue.  :)

**Comment by douglasparker** [comment]
Is there anything that we can do to help get their attention? Is there no way to get in contact with an engineer that maintains the Samsung Browser?

Surely there is some channel for communication, or someone with contacts within Samsung?

From what I understand it works fine with other password managers. Would a smaller company like AgileBits be willing to provide insight on this issue? I know they're Bitwarden's competition, but it would be nice for someone to help for the "greater good" of providing a safe and secure web.

**Comment by Phangan** [comment]
@mportune-bw Sorry, I forgot to add some irony, don't take this too seriously! ;)

**Comment by mportune-bw** [comment]
@Phangan Understood, lol :)

So I just updated to Samsung Internet 14 stable, and Autofill is working and even supports inline via the Samsung keyboard.  Both of these things are something I never expected to see.  Anybody else?  (I'm on an S10 w/ Android 11)

**Comment by Tosko4** [comment]
@mportune-bw as you can see in the version numbering here: https://github.com/bitwarden/mobile/issues/895#issuecomment-822058758

I've been rocking 14 stable but experience the bug. So annoying. The dev has it all working and users have issues xD

**Comment by mportune-bw** [comment]
@Tosko4 Bummer, mine is the same browser build.  The only difference is I'm running an internal build of Bitwarden (2.9.2) but I don't believe anything autofill related has been touched since 2.9.1.  Hopefully I can get a beta out relatively soon in case i'm wrong.

**Comment by douglasparker** [comment]
> So I just updated to Samsung Internet 14 stable, and Autofill is working and even supports inline via the Samsung keyboard.  Both of these things are something I never expected to see.  Anybody else?  (I'm on an S10 w/ Android 11)

It doesn't work for me at all. Only the accessibility service works for me.

Samsung Internet v14.0.1.62
Samsung Galaxy S21 Ultra running Android 11

**Comment by mportune-bw** [comment]
Just confirming - has everyone disabled the browser's built-in autofill settings in **Internet Settings > Personal Data > Autofill forms** (and the two switches in **Usernames and passwords**)?

**Comment by douglasparker** [comment]
> Just confirming - has everyone disabled the browser's built-in autofill settings in **Internet Settings > Personal Data > Autofill forms** (and the two switches in **Usernames and passwords**)?
> 
Yes, I disabled all of those settings a long time ago and I just confirmed that they are still disabled.

Thanks again for trying to help.

Samsung DeX mode on their latest tablets is really awesome and the DeX experience in the browser is also great.

I just can't bring myself to use the browser without proper support for Bitwarden.

**Comment by Tosko4** [comment]
> Just confirming - has everyone disabled the browser's built-in autofill settings in **Internet Settings > Personal Data > Autofill forms** (and the two switches in **Usernames and passwords**)?

Yep. All disabled

**Comment by raghusundaram** [comment]
> @mportune-bw i found out when it stops working and what to do as a workaround to make it work again. When I go to the tab view in Samsung internet and open a new tab, i go to the login page of that particular website, and bitwarden doesn't work. When I close the samsung internet app and re-open it. It starts loading the login page of that particular website again and voila, bitwarden works.
> 
> Test scenario 2: when i open two new tabs with two different websited and go to the login pages of both websites, close samsung internet and reopen the app, then bitwarden works on both tabs. I can switch between the tabs and it remains working. When I close one of the two and the other one remains working until both tabs are closed and obviously to browse you need a new tab.
> 
> So, workaround for now is: when I reach a login page, close samsung internet and reopen. Even though this workaround works 100% of the time for me, it has become slightly annoying that I have to keep doing this. Is this a bitwarden or samsung internet app issue?
> 
> Versions
> Bitwarden: Version: 2.9.1 (3444)
> Samsung Internet: 14.0.1.62
> 
> Edit: also raised an issue with samsung regarding samsung internet app. So both parties can have a look at it. It seems to be more of an issue with Samsung Internet app than Bitwarden. As if theres a bug how Samsung Internet allows third party apps to use the auto fill feature. Because Bitwarden works fine on other browser apps (chrome, brave and above confirmed by other users: firefox etc)

The above solution works here.
Bitwarden working natively.

**Comment by yurividal** [comment]
> @Tosko4 Bummer, mine is the same browser build. The only difference is I'm running an internal build of Bitwarden (2.9.2) but I don't believe anything autofill related has been touched since 2.9.1. Hopefully I can get a beta out relatively soon in case i'm wrong.

Same build here. In-line autofill does "work", but, as stated before, it only works sometimes. In many occasions bitwarden does not recognize the website (it either identifies the website as being "--" or being "package:com.sec.android.app.sbrowser.beta") so you have to manually search for the site in bitwarden. Then, clicking the correct site, it also only actually fills in sometimes.

**Comment by mdvmeijer** [comment]
> @Tosko4 This is the only substance in the reply. Awhile back we tested the theory that they were whitelisting 3rd party password managers instead of allowing use of the API across the board. I renamed the Bitwarden package name to match another popular password manager that we know works for sure with Samsung Internet, and viola - Bitwarden worked perfectly. We've made several attempts to contact Samsung to add Bitwarden to the whitelist, but we've never received a response.

From what I can see of the curent behaviour of the Bitwarden app, it seems to have been added to this 'whitelist'. Would you mind sharing how you managed to fix this in the end? I am running into the same issue with my own project.

**Comment by yurividal** [comment]
The weirdest thing is that, if you close Samsung browser (recents, swipe up) and relaunch it, bitwarden works and you get the inline autofill. It works for a while, and then after some minutes it stops again. So, it's definitely some sort of timer or timeout that is going on, that somehow kills the autofill service for the browser.

**Comment by mdvmeijer** [comment]
@yurividal So if I understand correctly, you still have problems with the Bitwarden autofill service in combination with the Samsung browser? I did some tests today of both the accessibility service and the autofill service with the browser, and they functioned as they should for at least 15 minutes (as long as I ran the tests) so the problem seems fixed on my end (most recent versions of Bitwarden and the Samsung browser)

**Comment by douglasparker** [comment]
> @yurividal So if I understand correctly, you still have problems with the Bitwarden autofill service in combination with the Samsung browser? I did some tests today of both the accessibility service and the autofill service with the browser, and they functioned as they should for at least 15 minutes (as long as I ran the tests) so the problem seems fixed on my end (most recent versions of Bitwarden and the Samsung browser)
> 
> 

@mdvmeijer Only the accessibility service prompt pops up, and once in a while even that fails.

Samsung Galaxy S21 Ultra running Android 11 w/ One UI 3.1

**Comment by yurividal** [comment]
> @yurividal So if I understand correctly, you still have problems with the Bitwarden autofill service in combination with the Samsung browser? I did some tests today of both the accessibility service and the autofill service with the browser, and they functioned as they should for at least 15 minutes (as long as I ran the tests) so the problem seems fixed on my end (most recent versions of Bitwarden and the Samsung browser)

Accessibility is completely disabled, to make sure I'm using autofill API. Autofill works with Samsung Browser only sometimes. It's like if the service has some sort of timeout. If you kill the browser (swipe up from recent) and relaunch the browser on the same page, autofill will work.
After some minutes, it stops again. This only happens on the browser. For other autofill areas, such as apps, it works pretty consistently.

**Comment by yurividal** [comment]
It can also be related to turning the screen off, instead of an actual timeout.

**Comment by yurividal** [comment]
@mdvmeijer this video shows exactly what I mean: 
![ezgif-1-27a8f283035f](https://user-images.githubusercontent.com/8555749/131554544-03482065-71fb-4ce6-a9cb-1a07732ea462.gif)

**Comment by mdvmeijer** [comment]
I see, it indeed seems like there is still something interfering with the autofill service.
Regarding the accessibility service and why I think Bitwarden managed to get into this "Samsung whitelist": When I just have the accessibility service of my own app running, no accessibility events are emitted by the app. Hence it can provide no functionality at all to the user if they are using the Samsung browser. However, if I enable the accessibility (or autofill, works for both) service of Bitwarden, the Samsung browser starts emitting accessibility events. These can then also be caught by my app. However, if I disable the Bitwarden service the browser stops emitting events again. Hence it looks like the Samsung browser notices whether Bitwarden is running, and based on that either emits these accessibility events or not. The same is the case with Dashlane and Lastpass: if either of them run, the browser emits events.

@mportune-bw Could you maybe shed some light on this or is this still a mystery to the team?

**Comment by Tosko4** [comment]
I have the same issue as @yurividal , i mentioned this before in a previous comment. But I'd like to point out something. Might help troubleshooting, because we might be looking in the wrong area. It's not just Samsung Browser related. Other browsers have same issue with bitwarden, exactly the same as recorded in @yurividal his video. Such as, chrome, brave etc. Sometimes bitwarden recognizes the login field and shows the bitwarden button to fill in credentials. Other times it doesn't, I close the browser, reopen the browser and voila, bitwarden button is shown.

I believe the issue is not a compatibility problem with a specific browser, or a whitelisting issue, but more fundamental.

On my iOS devices I don't have issues with bitwarden, only on Android devices.

**Comment by mdvmeijer** [comment]
@Tosko4 True, this sounds like a more fundamental problem separate from the whitelisting stuff. I can confirm from my own testing that this whitelist does exist however, and somehow Bitwarden managed to get on it (maybe someone at the Samsung browser dev team really likes Bitwarden :p). If someone on the Bitwarden team has any idea how you managed this then I'd love to hear it.

**Comment by mportune-bw** [comment]
@mdvmeijer Based on the power consumption used by accessibility (the event stream can be insane depending on the app) I would guess they stop emitting events unless an app is configured to receive them.  I don't know this for sure, however.

@Tosko4 I would love to know the answer to this as well, since debugging shows our autofill service alive and well but simply no longer receiving events from the system.

@mdvmeijer We've tried to contact them in the past to get whitelisted but never heard anything back.  Maybe they finally added us.

**Comment by Tosko4** [comment]
@mportune-bw I tried putting the apps related to each other (Brave, Bitwarden, Chrome, Samsung Browser) in a never deep sleep mode.

The new power management on android creates a lot of issues so to say. Not sure if you were referring to that? I'd have no clue how I could help any further honestly. If theres anything I can provide, let me know

**Comment by douglasparker** [comment]
> @mportune-bw I tried putting the apps related to each other (Brave, Bitwarden, Chrome, Samsung Browser) in a never deep sleep mode.
> 
> The new power management on android creates a lot of issues so to say. Not sure if you were referring to that? I'd have no clue how I could help any further honestly. If theres anything I can provide, let me know

I've excluded these apps from deep sleep as well and still have more issues with Samsung Internet than other Chromium based browsers.

Honestly, why is autofill such a nightmare in Android? It's been a buggy mess for so long now.

**Comment by yurividal** [comment]
@douglasparker i think the reason why its a mess is because it depends on a proper and precise implementation from Browsers, Keyboards, and Password Providers. 3 different players have to work together to have it work properly. No wonder why the only proper implementation is on pixel phones using Chrome, GBoard and Google Password Manager.

**Comment by mdvmeijer** [comment]
> @mdvmeijer We've tried to contact them in the past to get whitelisted but never heard anything back. Maybe they finally added us.

@mportune-bw Thank you for your reply. Do you know which channel was used to try to contact them? Then I will try my luck as well.
