### ISSUE TITLE
iOS App Extension doesn't update without first opening the Bitwarden App

### ISSUE THREAD

**Issue by clayadams5226** [bitwarden/mobile#901]
## Describe the Bug

Sync doesn't seem to work for iOS if I just use the extension and don't first open the Bitwarden app. 

## Steps To Reproduce

1. Change PW for an item in the web vault (or any other client). 
2. In Mobile Safari, use BW iOS extension to fill PW. BW extension fills OLD PW. 
3. Launch iOS client. 
4. Repeat step 2. Now BW fills UPDATED PW. 

## Expected Result

The new password is filled without needing to open the iOs client.

## Actual Result

The client needs to be open before the password syncs.

## Environment

- Device: iPhone XS
- Operating system: 13.4.1
- Build Version (go to "Settings" → "About" in the app): 2.3.1 (64)
- Is this a Beta release? N

**Comment by kspearrin** [comment]
This is due to issues with push syncs. See https://github.com/bitwarden/mobile/issues/457 https://github.com/bitwarden/mobile/issues/782
