### ISSUE TITLE
Cannot sync to selfhosted instance on Android 10

### ISSUE THREAD

**Issue by evangelos-ch** [bitwarden/mobile#904]
Apologies if this should be posted under the "server" repository instead but every other client works fine with my setup.

## Describe the Bug

I have a self-hosted instance running at ports 8393 for HTTP and 8394 for HTTPS, behind an nginx reverse proxy routing to port 8393. SSL is configured at reverse proxy level. I can access everything and sync properly fine from browser add-ons and the desktop client, but not the mobile client on Android 10.

The app manages to log in to my instance but whenever I try to sync I get a toast with "Syncing Failed".

## Steps To Reproduce

1. Open App.
2. Log in to self-hosted instance.
3. Click on the context menu on top right.
4. Click on "Sync".

## Expected Result

My vault entries appearing on the mobile app.

## Actual Result

A toast displaying "Syncing failed"

## Environment

- Device: OnePlus 6
- Operating system: Android 10.3.2
- Build Version (go to "Settings" → "About" in the app): 2.3.1 (2257)
- Is this a Beta release? N

## Additional Context

The instance I am trying to connect to is self-hosted and is behind a reverse proxy so I can run it alongside other servers on my machine and not have it bind to 80 / 443. I also installed the cert I have on the reverse proxy manually to the android device to no avail. It also seems like I can connect fine to the vault using the phone's browser, it's just the app not working.

**Comment by kspearrin** [comment]
Check your server's SSL config here: https://www.digicert.com/help/ 

Any issues?

**Comment by evangelos-ch** [comment]
Nope, all green.

**Comment by kspearrin** [comment]
This is the official Bitwarden server? Or some other community edition?

**Comment by evangelos-ch** [comment]
I am using the official Bitwarden server self hosted via its docker image as described in this [this guide](https://bitwarden.com/help/article/install-on-premise/), not Bitwarden_rs or similar, if that's what your question is.

**Comment by evangelos-ch** [comment]
I would like to add that I just tested it with the iOS version of the client, and that works fine. So it seems to be just the Android version of the client that is having this issue.

**Comment by kspearrin** [comment]
The only time I have never seen this occur is when there is some SSL related issue. Could you share your server URL here or via email so I could test against it?

**Comment by evangelos-ch** [comment]
Sure, I would prefer sharing it via e-mail though. What address should I mail it to?

**Comment by kspearrin** [comment]
support@bitwarden.com and just put "attention kspearrin" with a link to this issue.

**Comment by evangelos-ch** [comment]
Sent and included the phrase in both the title and body, thank you for any help in advance!

**Comment by kspearrin** [comment]
I debugged your server and here is the response I am getting when calling any authenticated API from the android app:

```
<html>
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>Request Header Or Cookie Too Large</center>
</body>
</html>

```

It seems you need to upadte your nginx proxy to allow larger header sizes.

**Comment by evangelos-ch** [comment]
Perfect, thank you so much for taking your time to debug this.

For future reference I solved this by adding the following to my `server` block and it now works fine with the Android client.

```
server {
    ....
    large_client_header_buffers 4 32k;
    ...
}
```
