### ISSUE TITLE
"Verif. code" screen: focus problem when BW is reduced+reopened

### ISSUE THREAD

**Issue by contribucious** [bitwarden/mobile#905]
## Describe the Bug

On the screen of the 6-digit verification code, asked right after the master password, when Bitwarden is reduced and then reopened, the wrong field has the focus (that of the master password, now invisible at this stage), hence the wrong keyboard (standard, A-Z) instead of the good (numeric, 1-9) that appears.

:information_source: The problem is present in both the stable and beta versions.

## Steps To Reproduce

**0.** Configure Bitwarden from your web vault in "two-step login" mode and choose "authenticator app".

###### &nbsp;
**1.** Open Bitwarden and enter your master password. You are now asked for a 6-digit code, as shown below.

![Screenshot_20200516-173141](https://user-images.githubusercontent.com/4764956/82124704-2422a300-97a1-11ea-8e63-3d9616cd2205.jpg)

###### &nbsp;
**2.** Minimize Bitwarden (press the "Home" button on your smartphone). Typically at this point, on a smartphone, we will open our "authenticator app" and copy the 6-digit code to the clipboard, but for our demonstration, let's skip this passage and reopen Bitwarden directly.

![Screenshot_20200516-173302_One UI Home](https://user-images.githubusercontent.com/4764956/82124714-297fed80-97a1-11ea-93f9-209ec63cb009.jpg)

###### &nbsp;
**3.** As can be seen below, the "Verification Code" field has lost its focus. The master password field has taken it back (despite its non-visibility). Hence the display of a standard keyboard (A-Z) instead of numeric (1-9).

:arrow_right_hook: At this point, of course, if you select the "Verification Code" field, the correct keyboard will reappear. But let's type "hello" in this keyboard that appears to see if it actually appears in the master password field.

![Screenshot_20200516-173310](https://user-images.githubusercontent.com/4764956/82124721-2d137480-97a1-11ea-9b04-a3729cf0d408.jpg)

###### &nbsp;
**4.** Let's check it out easily. Just press the "Back" button on your smartphone once. The keyboard is now hidden.

![Screenshot_20200516-173320](https://user-images.githubusercontent.com/4764956/82124726-30a6fb80-97a1-11ea-8103-628636b12dfc.jpg)

###### &nbsp;
**5.** Do it again. We can see our master password field with 5 hidden characters.

![Screenshot_20200516-173357](https://user-images.githubusercontent.com/4764956/82127692-dfedcd80-97b5-11ea-8d4e-6c5c50dc76c3.png)

###### &nbsp;
**6.** Let's display the master password and see. We can see that our "hello" has been typed in fact in this field.

![Screenshot_20200516-173410](https://user-images.githubusercontent.com/4764956/82127698-e8de9f00-97b5-11ea-809e-05f6fd4cb498.png)

## Expected Result

Focus on the correct field when Bitwarden is reopened, that of the 6-digit verification code (keypad 1-9 will then appear).

## Actual Result

Focus in the wrong field when Bitwarden is reopened, that of the master password, invisible at this stage (hence the A-Z keyboard appearing).

## Environment

- Battery optimization: **OFF**

- Device/OS:
  - Samsung Galaxy J5 2017 (**Android 9**)
  - Samsung Galaxy Tab S 10.5" (**Android 6.0.1**)
&nbsp;
- Build Version (go to "Settings" → "About" in the app):

  - both devices listed above have been tested with:

    - **stable** 2.3.1 (2257) **[problematic]**
    - **beta** 2.3.1 (2413) **[problematic]**
    - **a very recent tree** from this repository<sup>1</sup> **[problematic]**
&nbsp;

<sup>1</sup> Screenshots taken with this version (allowing me to do so by modifying the source code).

**Comment by mportune-bw** [comment]
Reopening as I realize there's a better way to handle this (and eliminate the clumsiness of the keyboard switching)

**Comment by mportune-bw** [comment]
Disregard reopening - this will require a larger arch change to eliminate the switching keyboard so I'll circle back later.  As it stands the correct keyboard type (numeric) is still showing in the end.
