### ISSUE TITLE
Android BW app always propose to save a password from another app 

### ISSUE THREAD

**Issue by rgarrigue** [bitwarden/mobile#911]
## Describe the Bug

It's more an annoying behavior than a bug I'ld say.

I'm running Aegis app (from F-Droid). Bitwarden app, whose vault is locked at the time, is always bothering me about "Do you want to ave the password in Bitwarden ?" when I log in this one. But it's already saved in Bitwarden ! I guess it's because of the locked vault. But the popup takes a 3rd of the screen, that annoying.

## Steps To Reproduce

1. Open up Aegis app & log in (I guess other app would do)
2. Save the password in Bitwarden
3. Lock Bitwarden's vault
4. Log out of the app
5. Log back in
6. There should be "Do you want to save..." popup

## Expected Result

I wish there would be no popup when the password's already saved, even when the vault is locked

## Environment

- Device: Samsung A3 2017 (SM-A320FL)
- Operating system: 8.0.0 + Samsung Experience 9.0
- Bitwarden 2.3.1 (2257)
- Is this a Beta release? N

- Aegis 1.1.4

**Comment by kspearrin** [comment]
You can blacklist app package names from autofill under Settings > Options.
