### ISSUE TITLE
Android autofill popup on any input control

### ISSUE THREAD

**Issue by rg9400** [bitwarden/mobile#914]
## Describe the Bug

I use both the Autofill + Accessibility services, though not sure if that's the root cause of the issue. Whenever I am on a website, I notice that on any input control, the autofill option pops up, even if that is not a field for a username/password.

As such, this is a minor annoyance usually, but I noticed it becoming extremely cumbersome when I am trying to do things on a terminal from my phone. I use Pulseway to access a remote terminal to my computer, and Bitwarden offers to "fill" the password for the command line interface. The real annoying portion of this bug is that even after typing in a command manually, once sent, the line is blank again and the popup reappears.

## Steps To Reproduce

1. Turn on Accessibility and Autofill frameworks on the Android app (beta version 2413)
2. Use the terminal portion of the Pulseway App

## Expected Result

Bitwarden should be intelligent enough to know that the input form is not at all a password field. If this is not fully possible, the autofill popup should not reappear if not clicked on, even if the field is reset to a blank state.

On LastPass, the mobile app only displays the overlay if the website is already saved in its vault. If not, to save a new site, you'd need to click the Quick Settings tile. I think this is also acceptable behavior since there's no point in showing an autofill option if Bitwarden will not be able to actually autofill anyways.

## Screenshots or Videos
![20200521-120737_Pulseway_LI](https://user-images.githubusercontent.com/39887349/82585724-1a5fbd80-9b5c-11ea-82ae-fbe82b7b40f9.jpg)

## Environment

- Device: Samsung Note 8
- Operating system: Android 9
- Build Version (go to "Settings" → "About" in the app): 2413
- Is this a Beta release? Y

**Comment by mandaputtra** [comment]
Also had these problem **sometimes**.
![Screenshot_20200608-091807](https://user-images.githubusercontent.com/23342943/83987069-31c6e500-a969-11ea-944e-92b970f34730.png)

**Comment by RayBB** [comment]
It seems like a similar issue is also happening on the `Samsung Secure folder` app as mentioned [here](https://www.androidpolice.com/2020/07/04/these-are-the-browser-extensions-the-android-police-staff-cant-live-without/#comment-4979541665).

<img width="699" alt="image" src="https://user-images.githubusercontent.com/921217/86519762-1508ba80-be0c-11ea-9786-a7be1cb17115.png">

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
