### ISSUE TITLE
TOTP working without premium (new TOPT input bypass using app)

### ISSUE THREAD

**Issue by TriHoangSG** [bitwarden/mobile#926]
A non-premium user can use TOTP feature.

Steps to reproduce:

1. Login using a non-premium Bitwarden account
2. Using web browser, go to a website that requires OTP and add this website new entry without OTP 
3. Login using a non-premium Bitwarden account on mobile app (iOS 13.4.1 Bitwarden v2.3.1)
4. On mobile app, find website entry, open the entry and click Edit
5. **Able to see "Authenticator Key (TOTP)" field and Camera Icon, user can proceed to scan QR code and save entry with TOTP** 
6. Using web browser, go back the website
7. On the website, right click anywhere on the page and choose Bitwarden in the menu (Bitwarden extension v1.43.4)
8. Able to see and click **Copy Verification Code**
9. Focus cursor on OTP field on the website and Paste, able to **paste the code into OTP field on the website**

Expected behaviour:
1. "Authenticator Key (TOTP)" field should not be available in mobile app (iOS and Android) when editing a Login entry as non-premium user
2. "Copy Verification Code" option should be not available in any web browsers as non-premium user

**Comment by kspearrin** [comment]
Using the camera option is allowed when not premium, but the context menu option in the browser extension should be hidden. Fixed with https://github.com/bitwarden/browser/pull/1252
