### ISSUE TITLE
Auto-fill should not be invoced by BankID

### ISSUE THREAD

**Issue by forteller** [bitwarden/mobile#935]
Hi. Thank you for a great product!

## Describe the Bug

The auto-fill feature is great, but there's one situation where it's just in the way, for all your users in Norway.

In Norway, every time you want to log in to your bank or any other place where you need to verify your real ID, you log in with something called Bank ID. BankID is not a normal app, you don't install it yourself and it's not available through your list of apps. It's connected to your SIM card, and when you try to log in with it on a website it pops up on your phone, asking you for a pin code. If you close this screen asking for the pin you can not open it again, without waiting for a time out and then going trough the process again.

The problem is that Bitwarden autofill shows up and covers almost the entire OK button. You're supposed to input a 4 digit pin code, which is obviously easier to remember than your Bitwarden password. Also, if you miss the OK button and hit the Auto-fill popup instead, BankID closes, and you must wait for the timeout. So the auto-fill popup should never show in this situation, because you don't want to and can not use it. 

In addition: If you are able to press OK, then the popup lingers on after the BankID screen is gone.

## Steps To Reproduce

1. Have a phone with a BankID compatible SIM card
2. Go to a page where you log in with BankID on mobile
3. Input your phone number and birth date
4. Wait for the BankID screen to pop up on your phone
5. Confirm the first screen
6. Notice that on the second screen, where you input your pin code the Auto-fill popup covers almost the entire OK button.

## Expected Result

The pop-up should not show in this situation

## Actual Result

It does show up, making it very hard to get BankID to work

## Screenshots or Videos

![Screenshot_20200530-011652_SIM Toolkit](https://user-images.githubusercontent.com/343561/83312659-750bb000-a213-11ea-8caf-bb1d8dac41fb.jpg)

## Environment

- Device: Samsung Galaxy S7
- Operating system: Android 8.0
- Build Version: 2.3.1 (2257)
- Is this a Beta release? N

## Additional Context
https://www.bankid.no/en/company/

**Comment by kspearrin** [comment]
Can you add this apps package id to the autofill blacklist under Settings > Options in Bitwarden?

**Comment by forteller** [comment]
How do I find that? It's not on any list of apps.

**Comment by kspearrin** [comment]
Select the autofill notification and it should open Bitwarden telling you the package id.

**Comment by forteller** [comment]
Ok, good. It says "There's no items in your vault for com.android.stk". Does this help finding out how to disable it for BankID for everyone?

I tried adding it to the blacklist, but when I tap away from the text box where I write the blacklist, the text just disappears.

**Comment by kspearrin** [comment]
Add `androidapp://com.android.stk` to the blacklist

**Comment by forteller** [comment]
Thanks! That worked. My issue still stands, though. This should be the default. The pop up is not needed and is just a nuisance on the BankID screen.

**Comment by kspearrin** [comment]
We cannot vet every app there is to blacklist in the app by default. This is why we have a user setting.

**Comment by forteller** [comment]
I've already given you the information you need: This makes the user experience of Bitwarden for all Norwegians pretty bad, and I've told you the Android ID of it. We might not be the largest market in the world, but we're still 5 million pretty affluent people. Isn't it worth it to just use the info I've already given you to make sure most of them don't figure Bitwarden stops them from using a service they need to use _all the time_ (every time any Norwegian logs in to any bank, or any public website of any kind, and many other places where we need to verify our ID) and thus stops using Bitwarden?

**Comment by godzillamesel** [comment]
I did get it done with the hotfix presented here doing exclusions, i should have done this weeks ago tho, #notime #tomuchtoogoogle!!!!. 
The only thing i might do not apreciate to much, is that BankID is using "com.android.stk". It could make trouble if they just block that "app". What about duo-sim with different country. 
The app "com.android.stk" is the Sim Application Toolkit. This is a common library, it should not be autoblocked in any way as that is native! The power of default.

What i would sincerelly ask for:
            "Possibility to move the bitwarden autofill window"
