### ISSUE TITLE
Russian missing in iOS app description (although the language is available)

### ISSUE THREAD

**Issue by kachkaev** [bitwarden/mobile#936]
## Describe the Bug

👋 folks, another transitioning LastPass customer here! 😁

One of the reason I’ve been seeking alternatives was that LastPass discontinued Russian a couple of years ago without notice. This made their app inaccessible for my parents, so I was really happy to discover Bitwarden supporting Russian – this gave me yet another reason to switch.

When checking out your iOS app description in App Store though, I noticed that Russian was not in the list of languages. This seems to be a small metadata issue, so hope that it won’t be too hard to fix.

Russian may be not the only language that’s missing from the list, so it’d be great if you could check others too. Each omitted language represents a small missed opportunity for your team – folks who don’t speak English will be less willing to try the product if they believe their language is missed.

## Steps To Reproduce

1. Open Bitwarden page in App store: https://apps.apple.com/gb/app/bitwarden-password-manager/id1137397744

1. See no Russian in the list of supported languages

1. Go to iOS i18n settings, change language to Russian

1. Open Bitwarden, confirm that the UI is in Russian

## Expected Result

Since I did see Bitwarden web and iOS UIs in Russian, I expected App store to advertise this language too

## Actual Result

![image](https://user-images.githubusercontent.com/608862/83351429-ac757c00-a33b-11ea-8829-58410a302bef.png)

## Environment

- Device: iPhone 6s
- Operating system: 13.5
- Build Version (go to "Settings" → "About" in the app): N/A
- Is this a Beta release? [Y/N]

**Comment by kspearrin** [comment]
Thanks. I updated the metadata on the app for next release.

**Comment by kachkaev** [comment]
Thanks! I can confirm that it is now correct! 🎉

<img width="340" alt="image" src="https://user-images.githubusercontent.com/608862/83943682-fce65100-a7f5-11ea-9203-3ed1b48e7d9b.png">
