### ISSUE TITLE
Splash screen doesn't follow dark theme

### ISSUE THREAD

**Issue by yegle** [bitwarden/mobile#938]
## Describe the Bug

The splash screen is a white screen with bitwarden logo. It doesn't follow the theme that I set to dark theme.

## Steps To Reproduce

1. Go to Settings - Options - Theme, choose Black
2. Swipe the app away, open again

## Expected Result

The splash screen should be a dark image with Bitwarden logo.

## Actual Result

It still has white background.

## Screenshots or Videos

 None (The splash screen happen too fast to have a screenshot)

## Environment

- Device: Pixel 4 XL
- Operating system: Android R DP (but it should not matter)
- Build Version (go to "Settings" → "About" in the app): 2.4.0 (2479)
- Is this a Beta release? Y

**Comment by cscharf** [comment]
We've have this on our development backlog as this will take some refactoring of our theming engine through Xamarin.
