### ISSUE TITLE
Bitwarden updated by f-droid : playstore wants to update it now

### ISSUE THREAD

**Issue by MisteurZZ** [bitwarden/mobile#939]
Hi,
I've updated my 2.3.1 f-droid version to the 2.4.0 version in f-droid.
It works great!
Now, Google playstore wants to update it to the same 2.4.0.
And if I accept to update, it replace bitwarden with the playstore version (seen on the info menu if the app).
What to do?

**Comment by MisteurZZ** [comment]
Ok, thank you

**Comment by mportune-bw** [comment]
@MisteurZZ We've updated the F-Droid signing key to prevent conflicts with Google Play.  This means you'll need to uninstall and re-install Bitwarden via the F-Droid app.  You'll end up with version 2.4.2 and the Play Store should no longer touch it.

**Comment by MisteurZZ** [comment]
Perfect, thank you
