### ISSUE TITLE
[Android] Force close after updating to 1.6.0

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/mobile#95]
Hi,
I have just updated to the version 1.6.0 from the Play Store and I have a force close when I try to open the app. (I didn't have this issue with the testing apk)

Here is the log:
[Log_2017-06-07_08-31-08.txt](https://github.com/bitwarden/mobile/files/1057079/Log_2017-06-07_08-31-08.txt)

**Comment by jerryn70** [comment]
Maybe the test apk and play store apk do not match. What about fresh install ?

Still i didn't received 1.6.0 version on my play store and there is no 1.6.0 apk  release in github.

**Comment by ple103** [comment]
@jerryn70 Same here. The latest version for me is 1.5.1 on the Play Store.
Test APKs can be found here: https://ci.appveyor.com/project/bitwarden/mobile/history.

**Comment by jerryn70** [comment]
@ple103  i know about the test apk. 
I mean there is no 1.6.0 version in this page  
https://github.com/bitwarden/mobile/releases

**Comment by Primokorn** [comment]
Yes, I'm on the beta program and I was talking about the testing apk [v802](https://github.com/bitwarden/mobile/issues/69).

I cleared app data then uninstalled it. So I have now a fresh installation.
I no longer have the force but I don't get any notification... The Accessibility service is enabled (btw we could have a request to enable it when launching the app for the first time).
idk what could be the problem...

**Comment by jerryn70** [comment]
@Primokorn you mean fresh install from play store ? Or update from old version?

If it is update, then i can't do that because I'm currently running on test version 798 and in play store no update is showing. 

To test 1.6.0 i need to uninstall v798 i think.

**Comment by jerryn70** [comment]
@Primokorn Joined bitwarden beta. 
Installed test version 802 then updated to 1.6.0 beta from play store . And got FC

![](http://i.imgur.com/Ml8MXOy.png)

**Comment by kspearrin** [comment]
This should now be resolved in the beta with build 824. If you can, please help test the following scenario:

1. Uninstall bitwarden completely.
2. Leave beta program.
3. Install non-beta version (v1.5.1)
4. Log in and activate fingerprint or other lock option.
5. Join beta program.
6. Update to 1.6.0 beta (824)
7. Confirm that you did not get logged out and no crashes are happening.
8. Edit and/or add a login.

**Comment by Primokorn** [comment]
Everything is working flawlessly. 
It was a problem due to the testing version?

**Comment by kspearrin** [comment]
@Primokorn Yes, there was a bug in the last beta build. @ple103 and I fixed it last night.
