### ISSUE TITLE
Autofill service fails

### ISSUE THREAD

**Issue by Stephan-P** [bitwarden/mobile#952]
Bitwarden Version: 2.4.2 (2501)

Browsers:
- Duckduckgo (55501)
- Vivaldi Snapshot (3.1.1929.3)

Test websites:
- github.com
- crowdin.com

Autofill service enabled + Accessibility service disabled:
- Duckduckgo browser does not show autofill overlay
- Vivaldi Snapshot does not show autofill overlay

Autofill service disabled + Accessibility service enabled:
- Duckduckgo browser shows autofill overlay, corresponding item is found in database, autofill functions 
- Vivaldi Snapshot shows autofill overlay, corresponding item is found in database, autofill functions

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
