### ISSUE TITLE
[ios] Header bar missing on fresh app start

### ISSUE THREAD

**Issue by ingria** [bitwarden/mobile#955]
## Describe the Bug
When app is first opened, it doesn’t have a header bar (the one with the clock, battery icon, carrier info, etc).

![BBDBE371-986A-4E22-9C9B-4E44A692417D](https://user-images.githubusercontent.com/2178368/83830042-e7d1cb00-a6ec-11ea-974a-081990aabd4e.jpeg)

After that, any subsequent closing and opening the app works fine (header bar is on its place):

![D7AD2D68-D620-4979-B432-EB57B683BCA7](https://user-images.githubusercontent.com/2178368/83830136-13ed4c00-a6ed-11ea-950b-77ea8a967418.jpeg)

After some time (when app is unloaded from the memory) or after force-closing, header bar goes missing again.

## Steps To Reproduce

1. Have a Bitwarden app locked with Touch ID 
2. Force-close the app
3. Open the app
4. Header bar is missing

## Environment

- Device: iPhone 7 Plus 
- Operating system: ios 12.3.1
- Build Version: ~2.4.2 (68)~, ~2.4.3 (69)~, 2.5.0 (193)
- Is this a Beta release? N

**Comment by kspearrin** [comment]
I cannot reproduce on iPhone 11

**Comment by ingria** [comment]
I think this is only reproducible on rectangular screens (without notch).

**Comment by MattTheDev** [comment]
@ingria Hi there!

I'm testing with an iPhone 8, no notch. I am unable to repro this issue. Does it persist? If so - can you try reinstalling the app and seeing if that resolves the problem?

**Comment by MattTheDev** [comment]
We’ve been unable to reproduce this issue ourselves. If this issue persists, please reopen it, and we’d be happy to help resolve the problem.
