### ISSUE TITLE
iOS Workaround for broken auto fill after last update

### ISSUE THREAD

**Issue by urvish0215** [bitwarden/mobile#956]
On IOS, It looks like the most recent update broke autofill for me. When pressing my login above keyboard, nothing happens. If I press the key button and then click bitwarden… the bitwarden opening screen shows up but then freezes on that screen. It doesn’t ask for password or fingeprint. The same problem as https://github.com/bitwarden/mobile/issues/839#issue-601550423

This has happened many times in the past year ever since I update to iOS 13 and normally I would just restart my device and it would start working again but this time, even after restart, it is still broken. I found out that I autoupdated the app earlier today. I tried deleting the app and reinstalling it but the problem persisted.

The workaround I found only works on safari, chrome and maybe a few other places. It is clicking the share button, then clicking bitwarden. Then bitwarden successfully opens up without freezing and you can procede like normal.

The share button is the button with a square and an arrow pointing up. It is probably at the top of screen or bottom of screen.

If bitwarden doesn’t show up. Press edit actions and toggle it on.

If that doesn’t work, open up the bitwarden app, go to setting, click app extension, click enable app extension, something should pop up and then press bitwarden on the pop up. It should say it was activated. Then go back and see if the bitwarden option is there after clicking the share button or in edit actions.

**Comment by I-like-stuff** [comment]
I too am having this problem using iPadOS 13.5.5 (17G5035d)

**Comment by eric-bednarz-dev** [comment]
@urvish0215 When I use the Safari share action, I get a smaller overlay; while the logotype fits into it instead of bleeding halfway out of the right boundary, it still freezes the app and requires force quitting.

**Comment by urvish0215** [comment]
@eric-bednarz-dev 

Did you uninstall and then reinstall bitwarden? 

My device is iPhone 6S running iOS 13.5

**Comment by eric-bednarz-dev** [comment]
@urvish0215 

> Did you uninstall and then reinstall bitwarden?

Yep, did that yesterday first thing and restarted the device, too. But see my updated answer 👍 
 
> My device is iPhone 6S running iOS 13.5

FWIF, iPad mini 4, iPadOS 13.4.1

**Comment by urvish0215** [comment]
That’s good to hear

**Comment by eric-bednarz-dev** [comment]
> That’s good to hear

Seems to be a bit hit and miss. Just tried

- Brave on same device: immediate success
- Firefox: immediate freeze
- Edge: share button didn't react first two taps

**Comment by urvish0215** [comment]
@eric-bednarz-dev 

That’s strange. I tried it on mine and it worked for both Firefox and Brave flawlessly.

Try reenabling the app extension

Open the bitwarden app, go to setting, app extensions, enable app extension, press bitwarden on the pop up

Then try again on the browsers

**Comment by urvish0215** [comment]
If that doesn’t work, then you might try restarting ur device and try again.

Also the website I test was github.
