### ISSUE TITLE
[iOS] Frozen BitWarden screen when trying to access logins from Safari

### ISSUE THREAD

**Issue by kingrocks95** [bitwarden/mobile#958]
## Describe the Bug
I installed Bitwarden 2.4.2 on my iPhone 6S iOS version 12.1.1.<br/>

I tried to set the autofill options in settings to Bitwarden, but every time I do, the screen opens Bitwarden's name page and gets frozen as shown below in the video.
This same thing happens when I try to fill my logins on safari.

<blockquote class="imgur-embed-pub" lang="en" data-id="a/R5WXIcK"  ><a href="//imgur.com/a/R5WXIcK">Bitwarden bug</a></blockquote>

## Environment

- Device: iPhone6S
- Operating system: iOS 12.1.1 (jailbroken)
- Is this a Beta release? [Y/N]

**Comment by florisdipt** [comment]
Simular isseu while logging in to add to this report. I get this sometimes on the newest version of Bitwarden on iPhonen SE 2020(iOS 13.5)
There a few variations of this for me personally. I get it the isseu described as before and sometimes I get i dont even get the Bitwarden screen.
Thanks to all contributers

**Comment by florisdipt** [comment]
Thanks appreciated
