### ISSUE TITLE
On Premise login not working

### ISSUE THREAD

**Issue by matze2090** [bitwarden/mobile#959]
I have installed bitwarden with a selfsign certificate.
I works fine with Browser an Chrome-plugin.
Under the android app there is a problem with the local login not working.
"Exception message: java.security.cert.CertPathValidatorException: Trust anchor for certification"

**Comment by kspearrin** [comment]
Check your cert chain at https://www.digicert.com/help/

**Comment by matze2090** [comment]
Its a self sign certificate. Its only local reachable

**Comment by kspearrin** [comment]
Did you add the cert to the trusted store on your android device?

**Comment by matze2090** [comment]
No, how can i do that?

**Comment by Greenderella** [comment]
The procedure varies from phone to phone, here is the explanation for Pixel phones: https://support.google.com/pixelphone/answer/2844832?hl=en but you can google your specific model

**Comment by djsmith85** [comment]
@matze2090 Here's a link to our Help site documenting the steps needed: https://bitwarden.com/help/certificates/#android

Closing this issue now.
