### ISSUE TITLE
[android] Autofill service does not work in Firefox

### ISSUE THREAD

**Issue by f1u77y** [bitwarden/mobile#96]
Subject. Works perfectly for the same sites in Chrome. The notification of the service does not appear when using Firefox.

**Comment by kspearrin** [comment]
This is a known problem and there isn't really anything that can be done about it currently. Firefox simply doesn't provide accessibility events in the browser on Android. I have talked with the mozilla dev team and they have acknowledged this.

The only workaround at the moment (I have been told) is to use Firefox Focus.

**Comment by Primokorn** [comment]
The WebKit Edition actually available [here](https://forum.xda-developers.com/android/apps-games/4-1-focus-mozilla-t3605123).

**Comment by f1u77y** [comment]
Thanks! Sorry for bothering you.
BTW, I've found the same issue with Firefox iOS but thought things are not the same on android. So, could I close the issue in favor of the older one for Fx iOS?

**Comment by kspearrin** [comment]
The iOS problem is fixed in Firefox 8.0 (unreleased still).

See more here: https://bugzilla.mozilla.org/show_bug.cgi?id=1344994

**Comment by f1u77y** [comment]
It's strange that issue is solved for iOS and isn't for Android. Thanks for support anyway.
