### ISSUE TITLE
[Android] Wrong string on biometric unlock prompt

### ISSUE THREAD

**Issue by sgango** [bitwarden/mobile#963]
On my Galaxy S8, the Bitwarden app has started using the iris scanner to unlock instead of the fingerprint scanner. However, the iris scanner prompt still says "Use your fingerprint to verify", even though the fingerprint scanner doesn't work on this screen.

## Steps To Reproduce

- Set up iris scanner on a Samsung Galaxy device
- Set "preferred biometric" to "irises"
- Enable "Unlock with fingerprint" in Bitwarden settings
- Close and re-open app

## Expected Result

A prompt like "Use irises to verify" or similar. 

(Or maybe just "use biometrics to unlock"? Although this might suggest that fingerprints could also be used, which they can't.)

## Actual Result

"Use your fingerprint to verify" on the iris scanner screen.

## Screenshots or Videos

<img src="https://user-images.githubusercontent.com/25332542/83977149-29819200-a8f6-11ea-94a2-43ed01fb4f92.png" width=300>

## Environment

- Device: Samsung Galaxy S8
- Operating system: Android 9
- Build Version: 2.4.2 (2501)
- Not a beta release.

## Additional Context

Most other apps on my phone just use fingerprint authentication, ignoring the "preferred biometric" option. Being able to use my irises to unlock my Bitwarden vault was a nice surprise!

The Android source code [has a list of devices](https://android.googlesource.com/platform/frameworks/support/+/dbcf7a846dca49f83abd0d720497e3d9a42acb57/biometric/src/main/res/values/devices.xml) which "should explicitly fall back to using FingerprintDialogFragment and FingerprintHelperFragment when crypto-based authentication is invoked."

**Comment by mportune-bw** [comment]
@sgango Thanks for reporting this. I believe it's fixed but we have no way to test it.  We pushed an update to the beta track so once it goes live I'm interested to know the results.

**Comment by sgango** [comment]
@mportune-bw Biometric prompt works as expected on version 2.5.0 (3093).

**Comment by mportune-bw** [comment]
Beautiful, thanks for the confirmation @sgango
