### ISSUE TITLE
Host matching on Android returns all androidapp:// entries

### ISSUE THREAD

**Issue by realansgar** [bitwarden/mobile#967]
## Describe the Bug

On Android with Host URI matching, all `androidapp://` entries match login forms instead of the only the expected matching ones.

## Steps To Reproduce

1. Set Default URI matching detection to host.
1. Have more than one password entry with different `androidapp://` URIs
1. Go to any app of your choice with a login form that is not a browser. For example `com.example.app`.
2. Use the Bitwarden Autofill Popup to get matches for that login form.

## Expected Result

Only the matching `androidapp://com.example.app` entries should match and be displayed.
## Actual Result
All existing `androidapp://` entries match and are displayed.

## Environment

- Device: OnePlus 3
- Operating system: Android 9
- Build Version: 2.4.2 (2501)
- Is this a Beta release? No

## Additional Context

This maybe has to do with #944 since this PR got implemented because of https://github.com/bitwarden/browser/issues/1267 and I can't remember this being a problem before this fix.

**Comment by Racle** [comment]
+1
Annoying issue. 

I've changed manually every androidapp:// uri to use "Starts with" detection mode so it won't interfere anymore. Quick but unnecessary workaround.

**Comment by timcappalli** [comment]
Seeing the same thing here. And when I click Use and Save, it just keeps creating additional URI entries.

![IMG_20200702_095319](https://user-images.githubusercontent.com/6476604/86368091-c829b600-bc4a-11ea-972d-0a8843f65c6a.jpg)

**Comment by timcappalli** [comment]
Has there been any movement on this? This is a pretty major bug to be sitting idle for so long.

**Comment by bugQ** [comment]
> I've changed manually every androidapp:// uri to use "Starts with" detection mode so it won't interfere anymore. Quick but unnecessary workaround.

Here to thank you for the hint, and to mention that "Default" match detection also works properly.  This issue popped up for me when I switched the order of the URIs without checking match detection modes to work around #1120, which is also pretty annoying.

Despite the existence of workarounds, I agree that this deserves attention.

**Comment by WROIATE** [comment]
+1
