### ISSUE TITLE
Support for custom package name?

### ISSUE THREAD

**Issue by wchen342** [bitwarden/mobile#969]
## Describe the Bug
I am the developer of [ungoogled-chromium-android](https://github.com/wchen342/ungoogled-chromium-android). There is a bug report regarding my browser returning package name (`org.ungoogled.chromium`) instead of the correct url. See wchen342/ungoogled-chromium-android/issues/38.
I figured that the cause of the problem is the change of package name, but I cannot figure out why. I happened to stumble into 9e7b741, and I am wondering is it because of my package name is not in the list of `CompatBrowsers`?

The following sections are copyed from the original issue:

## Steps To Reproduce

   1. Go to any website and login
   2. Bitwarden Autofill notification appears
   3. Select the notification
   4. It shows org.ungoogled.chromium instead of website

## Expected Result
Need to direct to the relevant website that user is trying to login

## Actual Result
It shows org.ungoogled.chromium on top

## Environment

- Device: OnePlus 5T
- Operating system: Stock
- Build Version Unkown. @sivuda can answer.
- Is this a Beta release? Unkown. @sivuda can answer.

**Comment by mportune-bw** [comment]
Hi, your theory is most likely correct.  Can I get a quick build to test locally?  (Your F-Droid link is returning 403)

**Comment by wchen342** [comment]
Here you go: [https://github.com/wchen342/ungoogled-chromium-android/releases/download/83.0.4103.97-1/ChromePublic_arm64.apk](https://github.com/wchen342/ungoogled-chromium-android/releases/download/83.0.4103.97-1/ChromePublic_arm64.apk)

**Comment by mportune-bw** [comment]
Thanks @wchen342 - fix will go out in the next release.

**Comment by nullsurfer** [comment]
I'm running Bitwarden 2.4.4. Accessibility service works, but not Autofill service.

**Comment by sivuda** [comment]
> Thanks @wchen342 - fix will go out in the next release.

Hi, there are two packages that @wchen342 build. One is `org.ungoogled.chromium` and the other is `org.ungoogled.chromium.extensions` . Looks like you guys added the first package name and not the second. Thanks

**Comment by mportune-bw** [comment]
@wchen342 Can you confirm this?

**Comment by wchen342** [comment]
@mportune-bw Yes that's a newly added package name.
