### ISSUE TITLE
View and Copy Password not visible in "locked" upgrade path

### ISSUE THREAD

**Issue by cscharf** [bitwarden/mobile#973]
## Describe the Bug

When upgrading Bitwarden from the prior version and your vault is only locked (not logged out), ciphers are not re-pulled from the API/servers and therefore changes from recent hidden password functionally which set the default of `View = true` are not set, leaving the value `false` and therefore hides all passwords/disabled copy.

## Steps To Reproduce

Tested on iOS v2.4.4 (175) via Test Flight (beta) from latest build; test from https://github.com/bitwarden/mobile/pull/920.

1. Open Bitwarden app and log in
2. Upgrade to latest version of application
3. View any password cipher
4. Note view or copy options are not present until you log out and back in

## Expected Result

`Cipher` class should handle a scenario where "not set" plays into a default of "true" rather than purely relying on the server fetch operation wholly in this scenario (a common upgrade path scenario).

When I open my vault without any preference set, after upgrading to this version, I should have view and copy password options available.

## Actual Result

When I open my vault without any preference set, after upgrading to this version, I do not have view and copy password options available.

## Environment

- Device: iPhone Xs
- Operating system: iOS 13.4.1
- BW Version: iOS v2.4.4 (175)
- Is this a Beta release? Y (Test Flight)

## Additional Context

see: https://github.com/bitwarden/mobile/pull/920...

**Could this also affect other clients in a similar scenario (desktop, browser and web)?**

CC: @Hinton

**Comment by Hinton** [comment]
Hmm, nice find.

Re-checking the PR, my current theory is that we only set the `CipherResponse` to contain the default value. So in the event of a user not receiving new data the `CipherData` would default to false.

I'll see if I can replicate the issue and get a PR open to resolve it. And verify if it exists on other clients.
