### ISSUE TITLE
Download program problem

### ISSUE THREAD

**Issue by stevezh1998** [bitwarden/mobile#976]
Hello, I am a user from China, can I add verification information to the binary files released on "releases"?For example md5.
My English is not good. The above is the content translated by Google.
“您好，我是中国用户，可以在“发行”上发布的二进制文件中添加验证信息吗？例如md5”

**Comment by clayadams5226** [comment]
感谢您与我们联系并引起我们的注意！ 我们想进一步为您提供帮助。 我们要求您使用我们的联系页面（https://bitwarden.com/contact）与我们联系。 您可以在邮件内容中包含指向此问题的链接。 这里的问题将被关闭并移至我们的服务台。
