### ISSUE TITLE
Autofill pop-up remains after switching to different screen

### ISSUE THREAD

**Issue by vertigo220** [bitwarden/mobile#988]
## Describe the Bug

Title says it all. I tap on a field which brings up the BitWarden autofill popup, then I switch to another app, but the popup remains, getting in the way.

## Steps To Reproduce

See above

## Screenshots or Videos

![1](https://user-images.githubusercontent.com/12024557/85162772-e4cbf400-b22f-11ea-8095-020bb3b640c1.png)
![2](https://user-images.githubusercontent.com/12024557/85162776-e5648a80-b22f-11ea-8d5c-5599537548df.png)
![3](https://user-images.githubusercontent.com/12024557/85162778-e5648a80-b22f-11ea-9369-88f502f11216.png)
![4](https://user-images.githubusercontent.com/12024557/85162779-e5fd2100-b22f-11ea-8d0b-a3b7d59a3268.png)

## Environment

- Device: Moto Z Play
- Operating system: Android 8.0
- Build Version (go to "Settings" → "About" in the app): 2.4.2 (2501)
- Is this a Beta release? [N]

**Comment by vertigo220** [comment]
Also, this may be related to #728

**Comment by clayadams5226** [comment]
Hey @vertigo220, can you retry with the latest app in the Playstore and let us know if you're still having this issue?

**Comment by clayadams5226** [comment]
it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Comment by oSumAtrIX** [comment]
This issue is also persistent on the default oneplus filemanager, when entering a lockbox pin. Unfortunately android does not allow to take screenshots frim the app
