### ISSUE TITLE
Clipboard doesn’t clear iOS 

### ISSUE THREAD

**Issue by usernameandpassword1** [bitwarden/mobile#991]
Hello,
I am using 11 pro max running 13.5.1 and bitwarden is running 2.4.3. I noticed there was an issue with the clipboard not clearing after a set time, even after changing the time the issue remained. I have only noticed this issue on iOS for the moment.
Best regards,
F

**Comment by cscharf** [comment]
@usernameandpassword1 , can you please provide a little more detail on steps to reproduce on your device?
i.e.
* Did you lock your device in-between?
* Did you close Bitwarden on your device?
* How long was the set time?
* How long did you wait to see if the value had been cleared?
* Is this consistently reproducible with the above steps or has it only happened once?

Thanks!

**Comment by usernameandpassword1** [comment]
Hello @cscharf,

To answer all your questions in one short summary, I used all four timers available and tried these steps:
-Set timer then copied a password
-these steps were attempted for each timer in separate procedures {
-Waited for timer to run out without force closing the application or locking my phone
-Waited for timer to run out with force closing the application and not locking my phone
-Waited for timer to run out without force closing the application and locking my phone
}
All these tests failed to clear the clipboard and returned consistent results.

**Comment by usernameandpassword1** [comment]
Version 2.5.0 fixed this issue

**Comment by MrL0** [comment]
What is happening is if you remove Bitwarden app from the background before the timed amount set, it won’t clear it. You must keep the app in the app switcher for it to clear the clipboard.

Tested this by:
1. Kept app in app switcher: Copied password, waited 20 secs, and tried pasting and it didn’t.
2. Copied password, closed app from background/app switcher, waited 20+ secs and it still pasted it.

As long as you don’t close the app from the switcher it will clear it the clipboard.
