### ISSUE TITLE
Fingerprint unlock stopped working in newest release

### ISSUE THREAD

**Issue by IamGimli** [bitwarden/mobile#993]
Ever since I updated Bitwarden to version 2.4.2 (2501) on my Umidigi X phone (Android 9) the in-screen fingerprint reader no longer works (only in Bitwarden).

I disabled the option to unlock using fingerprint and tried re-enabling it and a window pops up asking me to put my finger on the fingerprint reader but it's not the phone's window and the right area on the screen doesn't light up. 

- Device: Umidigi X
- Operating system: Android 9
- Build Version (go to "Settings" → "About" in the app): 2.4.2 (2501)
- Is this a Beta release? N

In-screen fingerprint reader is working in every other app.

**Comment by IamGimli** [comment]
Issue is still present in version 2.5.0 (3093)

**Comment by clayadams5226** [comment]
@IamGimli are you still having this issue with the latest build? Have you tried to uninstall and install a fresh build?

**Comment by IamGimli** [comment]
I actually replaced that phone for a new model just last week and it was still not working at the time. Unfortunately I sold the Umidigi X so can no longer test it out. We can probably close this if nobody else has reported the issue, it's not exactly a common device.
