### ISSUE TITLE
Biometric unlocking restarts the phone 

### ISSUE THREAD

**Issue by themascarade** [bitwarden/mobile#995]
## Describe the Bug

Tapping on biometric unlocking in settings restarts the phone. It seems to kill all processes for a second and then sends me to the splash screen.

## Steps To Reproduce

1. Go to settings
2. Tap on biometric unlock once or multiple times.

## Environment

- Device: Samsung galaxy a10
- Operating system: Android
- Build Version: 2.4.2
- Is this a Beta release?: N

**Comment by daveliao** [comment]
@themascarade - what's your Android operating system version?

**Comment by themascarade** [comment]
@daveliao android 10

**Comment by mportune-bw** [comment]
@themascarade I've never heard of this - Is it still happening with version 2.5.0?

**Comment by themascarade** [comment]
@mportune-bw Still happening in 2.0.5.

**Comment by clayadams5226** [comment]
@themascarade are you still having this issue? Have you tried to uninstall and then install a fresh build?

**Comment by clayadams5226** [comment]
Hi @themascarade , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
