### ISSUE TITLE
Auto-Fill Framework Stop Working

### ISSUE THREAD

**Issue by rageebm** [bitwarden/mobile#998]
## Describe the Bug

The auto-fill stops working after a short period of time, varying from 1-2 hours. This could be either time based or use-case based. After this is triggered, no Bitwarden auto-fill dialogue appears until the service is disabled and then re-enabled via Android settings.

## Steps To Reproduce

1. Go to 'settings -> autofill'
2. Enable Bitwarden
3. Go to bitwarden
4. Ensure that only framework is enabled and accessibility is disabled.

## Expected Result

Bitwarden should be an autofill option until set otherwise.

## Actual Result

As above

## Environment

- Device: Google Pixel 2XL & Huawei Nova 3e
- Operating system: Android 10 & Emui 9.1.0
- Build Version: 2.4.2 2501
- Is this a Beta release? [N]

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
